### ISSUE TITLE
Using docker getting permission issue for ruby 

### ISSUE THREAD

**Issue by abdulhanan001** [docker/compose#10212]
```
dockerize-rails-product-web-1  | /usr/local/lib/ruby/3.0.0/rubygems.rb:1357:in `rescue in <top (required)>': Operation not permitted - Operation not permitted @ rb_sysopen - /app/Gemfile.lock (Errno::EPERM)
dockerize-rails-product-web-1  | Loading the rubygems/defaults/operating_system.rb file caused an error. This file is owned by your OS, not by rubygems upstream. Please find out which OS package this file belongs to and follow the guidelines from your OS to report the problem and ask for help.
dockerize-rails-product-web-1  | 	from /usr/local/lib/ruby/3.0.0/rubygems.rb:1344:in `<top (required)>'
dockerize-rails-product-web-1  | 	from <internal:gem_prelude>:2:in `require'
dockerize-rails-product-web-1  | 	from <internal:gem_prelude>:2:in `<internal:gem_prelude>'
dockerize-rails-product-web-1  | /usr/local/lib/ruby/3.0.0/rubygems/bundler_version_finder.rb:106:in `read': Operation not permitted @ rb_sysopen - /app/Gemfile.lock (Errno::EPERM)
dockerize-rails-product-web-1  | 	from /usr/local/lib/ruby/3.0.0/rubygems/bundler_version_finder.rb:106:in `lockfile_contents'
dockerize-rails-product-web-1  | 	from /usr/local/lib/ruby/3.0.0/rubygems/bundler_version_finder.rb:71:in `lockfile_version'
dockerize-rails-product-web-1  | 	from /usr/local/lib/ruby/3.0.0/rubygems/bundler_version_finder.rb:20:in `bundler_version_with_reason'
dockerize-rails-product-web-1  | 	from /usr/local/lib/ruby/3.0.0/rubygems/bundler_version_finder.rb:5:in `bundler_version'
dockerize-rails-product-web-1  | 	from /usr/local/lib/ruby/3.0.0/rubygems/bundler_version_finder.rb:37:in `compatible?'
dockerize-rails-product-web-1  | 	from /usr/local/lib/ruby/3.0.0/rubygems/specification.rb:1000:in `block in find_by_path'
dockerize-rails-product-web-1  | 	from /usr/local/lib/ruby/3.0.0/rubygems/specification.rb:999:in `each'
dockerize-rails-product-web-1  | 	from /usr/local/lib/ruby/3.0.0/rubygems/specification.rb:999:in `find'
dockerize-rails-product-web-1  | 	from /usr/local/lib/ruby/3.0.0/rubygems/specification.rb:999:in `find_by_path'
dockerize-rails-product-web-1  | 	from /usr/local/lib/ruby/3.0.0/rubygems.rb:210:in `try_activate'
dockerize-rails-product-web-1  | 	from <internal:/usr/local/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:153:in `rescue in require'
dockerize-rails-product-web-1  | 	from <internal:/usr/local/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:149:in `require'
dockerize-rails-product-web-1  | 	from /usr/local/lib/ruby/3.0.0/rubygems.rb:1348:in `<top (required)>'
dockerize-rails-product-web-1  | 	from <internal:gem_prelude>:2:in `require'
dockerize-rails-product-web-1  | 	from <internal:gem_prelude>:2:in `<internal:gem_prelude>'
dockerize-rails-product-web-1  | <internal:/usr/local/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require': cannot load such file -- rubygems/defaults/operating_system (LoadError)
dockerize-rails-product-web-1  | 	from <internal:/usr/local/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
dockerize-rails-product-web-1  | 	from /usr/local/lib/ruby/3.0.0/rubygems.rb:1348:in `<top (required)>'
dockerize-rails-product-web-1  | 	from <internal:gem_prelude>:2:in `require'
dockerize-rails-product-web-1  | 	from <internal:gem_prelude>:2:in `<internal:gem_prelude>'
dockerize-rails-product-web-1 exited with code 1

```

Dockerfile
```
|FROM ruby:3.0.0

ENV RAILS_ROOT /app
RUN mkdir -p $RAILS_ROOT
WORKDIR $RAILS_ROOT

COPY . $RAILS_ROOT

ADD Gemfile /$RAILS_ROOT/Gemfile
ADD Gemfile.lock /$RAILS_ROOT/Gemfile.lock
RUN bundle install
```

docker-compose.yml 

```
version: '3'
services:
  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
  db:
    image: postgres:10.7
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
```

**Comment by ndeloof** [comment]
can you successfully run:
```sh
docker build .
docker run bundle exec rails s -p 3000 -b '0.0.0.0'
```
otherwise, this issue is not related to compose, but a more generic docker-ization issue

**Comment by abdulhanan001** [comment]
`docker build .`
working fine, But getting issue on docker-compose up
https://github.com/docker/compose/issues/10212#issue-1561038470

**Comment by ndeloof** [comment]
sure, so me asking to run the equivalent command with `docker run ...` to confirm issue is related to docker compose, not a more generic one

**Comment by ndeloof** [comment]
closing this issue for lack of answer
