### ISSUE TITLE
[BUG] Failure when pulling a (particular?) image

### ISSUE THREAD

**Issue by Phxntxm** [docker/compose#10322]
### Description

I'll apologize first off, as I'm unsure how understandable this one is going to be... because I cannot replicate this manually, it's during a services' automated process that this fails - in the same service, running manually, it works fine.. I'll do my best to describe the issue though.

I use the service https://gitpod.io and am building some containers in a prebuild, for usage later. During that prebuild step, when pulling a pretty standard postgres image, it fails with this traceback:

```
[+] Running 38/3
 ⠏ postgres-test Pulling                                                  10.0s 
panic: strings: negative Repeat count⣿⣿⣤⣿⣿⣿⣿⣿⠀⠀⠀⠀] 101.6MB/270MB   Pulling 9.9s s 
 ⠇ postgres 13 layers [⣿⣿⣿⣿⣿⣿⣿⣿⡀⣿⣿⣿⣿] 14.48MB/71.54MB Pulling              9.9s 
goroutine 39 [running]:
strings.Repeat({0x226f8d0?, 0x4?}, 0xc0003eb640?)
        strings/strings.go:538 +0x438
github.com/docker/compose/v2/pkg/progress.align({0xc00013f600, 0xac}, {0xc000738570, 0xf}, 0x50)
        github.com/docker/compose/v2/pkg/progress/tty.go:284 +0x1df
github.com/docker/compose/v2/pkg/progress.(*ttyWriter).lineText(0xc000320070, {{0xc000057bf8, 0x2}, {0x0, 0x0}, {0x1f83285, 0x7}, 0x0, {0x0, 0x0}, ...}, ...)
        github.com/docker/compose/v2/pkg/progress/tty.go:266 +0xb0c
github.com/docker/compose/v2/pkg/progress.(*ttyWriter).print(0xc000320070)
        github.com/docker/compose/v2/pkg/progress/tty.go:179 +0x82c
github.com/docker/compose/v2/pkg/progress.(*ttyWriter).Start(0xc000320070, {0x22926f8, 0xc000132000})
        github.com/docker/compose/v2/pkg/progress/tty.go:63 +0xa5
github.com/docker/compose/v2/pkg/progress.RunWithStatus.func1()
        github.com/docker/compose/v2/pkg/progress/writer.go:77 +0x30
golang.org/x/sync/errgroup.(*Group).Go.func1()
        golang.org/x/sync@v0.1.0/errgroup/errgroup.go:75 +0x64
created by golang.org/x/sync/errgroup.(*Group).Go
        golang.org/x/sync@v0.1.0/errgroup/errgroup.go:72 +0xa5
make: *** [makefile:29: setup] Error 2
```

The service in the docker-compose is like this:

```
  postgres-test:
    image: postgres:11
    networks:
      - [hardcoded name]
    environment:
      - POSTGRES_DB=[hardcoded database]
      - POSTGRES_USER=[hardcoded user]
      - POSTGRES_PASSWORD=[hardcoded password]
    ports:
      - 5433:5433
    command: -p 5433
```

(Sorry for the censoring, but it's company data, they're all hardcoded so they're guaranteed to not be empty or something like that)

This failure happens when running `docker-compose up -d` 

If any more information is needed, I can try to provide it, but it's a bit difficult since this happens inside of a third-party's automated service, and it works perfectly fine in the same service... when running the commands manually.

### Compose Version

```Text
Docker Compose version v2.16.0-gitpod.0
```

### Docker Environment

```Text
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Docker Buildx (Docker Inc., v0.8.2-docker)
  compose: Docker Compose (Docker Inc., v2.16.0-gitpod.0)

Server:
 Containers: 5
  Running: 5
  Paused: 0
  Stopped: 0
 Images: 4
 Server Version: 20.10.17
 Storage Driver: overlay2
  Backing Filesystem: xfs
  Supports d_type: true
  Native Overlay Diff: false
  userxattr: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: gitpod io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: gitpod
 Init Binary: docker-init
 containerd version: 9cd3357b7fd7218e4aec3eae239db1f68a5a6ec6
 runc version: v1.1.4-0-g5fd4c4d1
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
  cgroupns
 Kernel Version: 5.15.0-47-generic
 Operating System: Ubuntu 20.04.5 LTS (containerized)
 OSType: linux
 Architecture: x86_64
 CPUs: 16
 Total Memory: 62.8GiB
 Name: lims-lims-6lfqyacqjhy
 ID: NKQ7:RFEM:332H:C4E7:JXKE:OQPD:J5WL:B43Q:AZTA:WKAG:H4SW:F3Q2
 Docker Root Dir: /workspace/.docker-root
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Comment by laurazard** [comment]
@ndeloof looks like this might have been introduced by https://github.com/docker/compose/pull/10281

**Comment by ndeloof** [comment]
After dealing with "not high enough terminal" here we need to manage "not large enough terminal" :P

proposed a fool guard on https://github.com/docker/compose/pull/10336
still UX will be broken
