### ISSUE TITLE
Docker compose up fails with "fatal error: concurrent map writes" 

### ISSUE THREAD

**Issue by dejapong** [docker/compose#10468]
### Description

Docker compose is sometimes failing on `up` with the following error:
`fatal error: concurrent map writes` 

The command which launches it is:

`docker compose -f /some/path/docker-compose-production.yml up`

Interestingly, the issue is does not occur everytime I run the command and I'm not sure what triggers it. I'm hoping theres something I can do to work around this. 

Full log here below:
```
 time="2023-04-13T07:24:39Z" level=warning msg="`scale` is deprecated. Use the `deploy.replicas` element"
  Container test-image-1  Recreate
  Container test-image-2  Recreate
 fatal error: concurrent map writes
 goroutine 101 [running]:
 github.com/docker/compose/v2/pkg/compose.(*composeService).recreateContainer(_, {_, _}, _, {{0xc0004483a8, 0x12}, {0x0, 0x0, 0x0}, 0x0, ...}, ...)
         github.com/docker/compose/v2/pkg/compose/convergence.go:427 +0x2f0
 github.com/docker/compose/v2/pkg/compose.(*convergence).ensureService.func2()
         github.com/docker/compose/v2/pkg/compose/convergence.go:199 +0xd0
 golang.org/x/sync/errgroup.(*Group).Go.func1()
         golang.org/x/sync@v0.1.0/errgroup/errgroup.go:75 +0x64
 created by golang.org/x/sync/errgroup.(*Group).Go
         golang.org/x/sync@v0.1.0/errgroup/errgroup.go:72 +0xa5
 goroutine 1 [semacquire]:
 sync.runtime_Semacquire(0xc0000061a0?)
         runtime/sema.go:62 +0x25
 sync.(*WaitGroup).Wait(0x3166701?)
         sync/waitgroup.go:139 +0x52
 golang.org/x/sync/errgroup.(*Group).Wait(0xc0003940c0)
         golang.org/x/sync@v0.1.0/errgroup/errgroup.go:53 +0x27
 github.com/docker/compose/v2/pkg/progress.RunWithStatus({0x222c500, 0xc00015e000}, 0xc0009324e0)
         github.com/docker/compose/v2/pkg/progress/writer.go:91 +0x21e
 github.com/docker/compose/v2/pkg/progress.Run({0x222c500, 0xc00015e000}, 0xc0009307e0)
         github.com/docker/compose/v2/pkg/progress/writer.go:62 +0x6d
 github.com/docker/compose/v2/pkg/compose.(*composeService).Up(0xc0007a6580, {0x222c500, 0xc00015e000}, 0xc000922820, {{{0x3166738, 0x0, 0x0}, 0x0, 0x0, {0x1efab83, ...}, ...}, ...})
         github.com/docker/compose/v2/pkg/compose/up.go:34 +0x13f
 github.com/docker/compose/v2/pkg/api.(*ServiceProxy).Up(0xc0003f61e0, {0x222c500, 0xc00015e000}, 0x0?, {{{0x3166738, 0x0, 0x0}, 0x0, 0x0, {0x1efab83, ...}, ...}, ...})
         github.com/docker/compose/v2/pkg/api/proxy.go:181 +0x143
 github.com/docker/compose/v2/cmd/compose.runUp({0x222c500?, 0xc00015e000}, {0x7fe7457ee558, 0xc0001d4400}, {0x2242f10, 0xc0003f61e0}, {0x0, 0x0, {0x1ef941a, 0x7}, ...}, ...)
         github.com/docker/compose/v2/cmd/compose/up.go:191 +0x931
 github.com/docker/compose/v2/cmd/compose.upCommand.func2({0x222c500, 0xc00015e000}, 0xc000922820, {0x3166738, 0x0, 0x0})
         github.com/docker/compose/v2/cmd/compose/up.go:87 +0x1e5
 github.com/docker/compose/v2/cmd/compose.(*ProjectOptions).WithServices.func1({0x222c500, 0xc00015e000}, {0x3166738, 0x0, 0x0})
         github.com/docker/compose/v2/cmd/compose/compose.go:127 +0xd7
 github.com/docker/compose/v2/cmd/compose.Adapt.func1({0x222c500?, 0xc00015e000?}, 0x2?, {0x3166738?, 0x1?, 0x0?})
         github.com/docker/compose/v2/cmd/compose/compose.go:92 +0x36
 github.com/docker/compose/v2/cmd/compose.AdaptCmd.func1(0xc0002c2f00, {0x3166738, 0x0, 0x0})
         github.com/docker/compose/v2/cmd/compose/compose.go:71 +0x21c
 github.com/spf13/cobra.(*Command).execute(0xc0002c2f00, {0xc0005c5d10, 0x0, 0x0})
         github.com/spf13/cobra@v1.6.1/command.go:916 +0x862
 github.com/spf13/cobra.(*Command).ExecuteC(0xc0004bf200)
         github.com/spf13/cobra@v1.6.1/command.go:1044 +0x3bd
 github.com/spf13/cobra.(*Command).Execute(...)
         github.com/spf13/cobra@v1.6.1/command.go:968
 github.com/docker/cli/cli-plugins/plugin.RunPlugin(0x40db07?, 0xc0002c2c00, {{0x1ef54f1, 0x5}, {0x1efec87, 0xb}, {0x2209b28, 0x7}, {0x0, 0x0}, ...})
         github.com/docker/cli@v23.0.0+incompatible/cli-plugins/plugin/plugin.go:51 +0x130
 github.com/docker/cli/cli-plugins/plugin.Run(0x2012c20, {{0x1ef54f1, 0x5}, {0x1efec87, 0xb}, {0x2209b28, 0x7}, {0x0, 0x0}, {0x0, ...}, ...})
         github.com/docker/cli@v23.0.0+incompatible/cli-plugins/plugin/plugin.go:64 +0xee
 main.pluginMain()
         github.com/docker/compose/v2/cmd/main.go:36 +0xdf
 main.main()
         github.com/docker/compose/v2/cmd/main.go:68 +0x198
 goroutine 76 [syscall]:
 os/signal.signal_recv()
         runtime/sigqueue.go:152 +0x2f
 os/signal.loop()
         os/signal/signal_unix.go:23 +0x19
 created by os/signal.Notify.func1.1
         os/signal/signal.go:151 +0x2a
 goroutine 58 [chan receive]:
 github.com/docker/compose/v2/cmd/compose.AdaptCmd.func1.1()
         github.com/docker/compose/v2/cmd/compose/compose.go:67 +0x28
 created by github.com/docker/compose/v2/cmd/compose.AdaptCmd.func1
         github.com/docker/compose/v2/cmd/compose/compose.go:66 +0x1da
 goroutine 59 [chan receive]:
 github.com/docker/compose/v2/cmd/compose.AdaptCmd.func1.1()
         github.com/docker/compose/v2/cmd/compose/compose.go:67 +0x28
 created by github.com/docker/compose/v2/cmd/compose.AdaptCmd.func1
         github.com/docker/compose/v2/cmd/compose/compose.go:66 +0x1da
 goroutine 61 [select]:
 github.com/docker/compose/v2/pkg/progress.(*plainWriter).Start(0xc000930800, {0x222c538, 0xc000054058})
         github.com/docker/compose/v2/pkg/progress/plain.go:34 +0x6d
 github.com/docker/compose/v2/pkg/progress.RunWithStatus.func1()
         github.com/docker/compose/v2/pkg/progress/writer.go:77 +0x30
 golang.org/x/sync/errgroup.(*Group).Go.func1()
         golang.org/x/sync@v0.1.0/errgroup/errgroup.go:75 +0x64
 created by golang.org/x/sync/errgroup.(*Group).Go
         golang.org/x/sync@v0.1.0/errgroup/errgroup.go:72 +0xa5
 goroutine 62 [semacquire]:
 sync.runtime_Semacquire(0xc00015e680?)
         runtime/sema.go:62 +0x25
 sync.(*WaitGroup).Wait(0x222c500?)
         sync/waitgroup.go:139 +0x52
 golang.org/x/sync/errgroup.(*Group).Wait(0xc00015e640)
         golang.org/x/sync@v0.1.0/errgroup/errgroup.go:53 +0x27
 github.com/docker/compose/v2/pkg/compose.(*graphTraversal).visit(0xc00013a050, {0x222c5a8, 0xc0009217a0}, 0x40db07?)
         github.com/docker/compose/v2/pkg/compose/dependencies.go:108 +0x10f
 github.com/docker/compose/v2/pkg/compose.InDependencyOrder({0x222c5a8, 0xc0009217a0}, 0xc000203d78?, 0xc00029a150, {0x0, 0x0, 0x1?})
         github.com/docker/compose/v2/pkg/compose/dependencies.go:86 +0x110
 github.com/docker/compose/v2/pkg/compose.(*convergence).apply(0xc00011ff20, {0x222c5a8, 0xc0009217a0}, 0xc000922820, {{0xc000932510, 0x1, 0x1}, 0x0, 0x0, {0x1efab83, ...}, ...})
         github.com/docker/compose/v2/pkg/compose/convergence.go:90 +0x111
 github.com/docker/compose/v2/pkg/compose.(*composeService).create(0xc0007a6580?, {0x222c5a8, 0xc0009217a0}, 0xc000922820, {{0xc000932510, 0x1, 0x1}, 0x0, 0x0, {0x1efab83, ...}, ...})
         github.com/docker/compose/v2/pkg/compose/create.go:114 +0x6b0
 github.com/docker/compose/v2/pkg/compose.(*composeService).Up.func1({0x222c5a8, 0xc0009217a0})
         github.com/docker/compose/v2/pkg/compose/up.go:35 +0xaa
 github.com/docker/compose/v2/pkg/progress.Run.func1({0x222c5a8?, 0xc0009217a0?})
         github.com/docker/compose/v2/pkg/progress/writer.go:63 +0x27
 github.com/docker/compose/v2/pkg/progress.RunWithStatus.func2()
         github.com/docker/compose/v2/pkg/progress/writer.go:84 +0x87
 golang.org/x/sync/errgroup.(*Group).Go.func1()
         golang.org/x/sync@v0.1.0/errgroup/errgroup.go:75 +0x64
 created by golang.org/x/sync/errgroup.(*Group).Go
         golang.org/x/sync@v0.1.0/errgroup/errgroup.go:72 +0xa5
 goroutine 64 [IO wait]:
 internal/poll.runtime_pollWait(0x7fe745aa4308, 0x72)
         runtime/netpoll.go:305 +0x89
 internal/poll.(*pollDesc).wait(0xc000924400?, 0xc000944000?, 0x0)
         internal/poll/fd_poll_runtime.go:84 +0x32
 internal/poll.(*pollDesc).waitRead(...)
         internal/poll/fd_poll_runtime.go:89
 internal/poll.(*FD).Read(0xc000924400, {0xc000944000, 0x1000, 0x1000})
         internal/poll/fd_unix.go:167 +0x25a
 net.(*netFD).Read(0xc000924400, {0xc000944000?, 0x4062b1?, 0x4?})
         net/fd_posix.go:55 +0x29
 net.(*conn).Read(0xc0006b4a20, {0xc000944000?, 0x0?, 0x0?})
         net/net.go:183 +0x45
 net/http.(*persistConn).Read(0xc000885c20, {0xc000944000?, 0xc0000fc960?, 0xc00093cd30?})
         net/http/transport.go:1929 +0x4e
 bufio.(*Reader).fill(0xc0001397a0)
         bufio/bufio.go:106 +0xff
 bufio.(*Reader).Peek(0xc0001397a0, 0x1)
         bufio/bufio.go:144 +0x5d
 net/http.(*persistConn).readLoop(0xc000885c20)
         net/http/transport.go:2093 +0x1ac
 created by net/http.(*Transport).dialConn
         net/http/transport.go:1751 +0x173e
 goroutine 81 [select]:
 net/http.(*persistConn).writeLoop(0xc000885c20)
         net/http/transport.go:2392 +0xf5
 created by net/http.(*Transport).dialConn
         net/http/transport.go:1752 +0x1791
 goroutine 97 [semacquire]:
 sync.runtime_Semacquire(0xc000203d08?)
         runtime/sema.go:62 +0x25
 sync.(*WaitGroup).Wait(0x4?)
         sync/waitgroup.go:139 +0x52
 golang.org/x/sync/errgroup.(*Group).Wait(0xc00015e700)
         golang.org/x/sync@v0.1.0/errgroup/errgroup.go:53 +0x27
 github.com/docker/compose/v2/pkg/compose.(*convergence).ensureService(_, {_, _}, _, {{0xc0004483a8, 0x12}, {0x0, 0x0, 0x0}, 0x0, ...}, ...)
         github.com/docker/compose/v2/pkg/compose/convergence.go:239 +0x3e8
 github.com/docker/compose/v2/pkg/compose.(*convergence).apply.func1({0x222c500, 0xc00015e600}, {0xc0004483a8, 0x12})
         github.com/docker/compose/v2/pkg/compose/convergence.go:100 +0x1ce
 github.com/docker/compose/v2/pkg/compose.(*graphTraversal).run.func1()
         github.com/docker/compose/v2/pkg/compose/dependencies.go:127 +0x63
 golang.org/x/sync/errgroup.(*Group).Go.func1()
         golang.org/x/sync@v0.1.0/errgroup/errgroup.go:75 +0x64
 created by golang.org/x/sync/errgroup.(*Group).Go
         golang.org/x/sync@v0.1.0/errgroup/errgroup.go:72 +0xa5
 goroutine 98 [runnable]:
 github.com/docker/compose/v2/pkg/compose.(*composeService).getCreateOptions(_, {_, _}, _, {{0xc0004483a8, 0x12}, {0x0, 0x0, 0x0}, 0x0, ...}, ...)
         github.com/docker/compose/v2/pkg/compose/create.go:239 +0x143e
 github.com/docker/compose/v2/pkg/compose.(*composeService).createMobyContainer(_, {_, _}, _, {{0xc0004483a8, 0x12}, {0x0, 0x0, 0x0}, 0x0, ...}, ...)
         github.com/docker/compose/v2/pkg/compose/convergence.go:481 +0xe6
 github.com/docker/compose/v2/pkg/compose.(*composeService).recreateContainer(_, {_, _}, _, {{0xc0004483a8, 0x12}, {0x0, 0x0, 0x0}, 0x0, ...}, ...)
         github.com/docker/compose/v2/pkg/compose/convergence.go:428 +0x3f2
 github.com/docker/compose/v2/pkg/compose.(*convergence).ensureService.func2()
         github.com/docker/compose/v2/pkg/compose/convergence.go:199 +0xd0
 golang.org/x/sync/errgroup.(*Group).Go.func1()
         golang.org/x/sync@v0.1.0/errgroup/errgroup.go:75 +0x64
 created by golang.org/x/sync/errgroup.(*Group).Go
         golang.org/x/sync@v0.1.0/errgroup/errgroup.go:72 +0xa5
 goroutine 99 [runnable]:
 github.com/docker/compose/v2/pkg/compose.(*composeService).recreateContainer(_, {_, _}, _, {{0xc0004483a8, 0x12}, {0x0, 0x0, 0x0}, 0x0, ...}, ...)
         github.com/docker/compose/v2/pkg/compose/convergence.go:410 +0x889
 github.com/docker/compose/v2/pkg/compose.(*convergence).ensureService.func2()
         github.com/docker/compose/v2/pkg/compose/convergence.go:199 +0xd0
 golang.org/x/sync/errgroup.(*Group).Go.func1()
         golang.org/x/sync@v0.1.0/errgroup/errgroup.go:75 +0x64
 created by golang.org/x/sync/errgroup.(*Group).Go
         golang.org/x/sync@v0.1.0/errgroup/errgroup.go:72 +0xa5
 goroutine 100 [runnable]:
 golang.org/x/sync/errgroup.(*Group).Go.func1()
         golang.org/x/sync@v0.1.0/errgroup/errgroup.go:72
 created by golang.org/x/sync/errgroup.(*Group).Go
         golang.org/x/sync@v0.1.0/errgroup/errgroup.go:72 +0xa5

Main process exited, code=exited, status=2/INVALIDARGUMENT
```

### Steps To Reproduce

`docker compose -f /some/path/docker-compose.yml up`

### Compose Version

```Text
Client: Docker Engine - Community
 Version:           23.0.1
 API version:       1.42
 Go version:        go1.19.5
 Git commit:        a5ee5b1
 Built:             Thu Feb  9 19:46:56 2023
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          23.0.1
  API version:      1.42 (minimum version 1.12)
  Go version:       go1.19.5
  Git commit:       bc3805a
  Built:            Thu Feb  9 19:46:56 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.18
  GitCommit:        2456e983eb9e37e47538f59ea18f2043c9a73640
 runc:
  Version:          1.1.4
  GitCommit:        v1.1.4-0-g5fd4c4d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### Docker Environment

```Text
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.10.2
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.16.0
    Path:     /usr/libexec/docker/cli-plugins/docker-compose
  scan: Docker Scan (Docker Inc.)
    Version:  v0.17.0
    Path:     /usr/libexec/docker/cli-plugins/docker-scan

Server:
 Containers: 9
  Running: 5
  Paused: 0
  Stopped: 4
 Images: 18
 Server Version: 23.0.1
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 2456e983eb9e37e47538f59ea18f2043c9a73640
 runc version: v1.1.4-0-g5fd4c4d
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
 Kernel Version: 5.11.15-xanmod1
 Operating System: Ubuntu 20.04.4 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 48
 Total Memory: 188.8GiB
 Name: datasci-srv01.int.archer.com
 ID: W22R:RAFT:QX6W:MRLB:P3UI:D7CI:5UKP:4JKA:HW3O:VSUH:3PBD:SQZD
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Default Address Pools:
   Base: 198.18.0.0/15, Size: 24
```

### Anything else?

Docker compose file:
```
version: '3'

services:
  test_image:
    privileged: true
    restart: always
    network_mode: 'host'
    scale: 4
    image: test_image:latest
    command: -run_auto
    volumes:
      - logging:/app/logging'
```

**Comment by ndeloof** [comment]
Thanks for reporting this bug
This has been fixed already by https://github.com/docker/compose/commit/bfeb1dc2775c962c6994c662d063e18f2ac9956d
