### ISSUE TITLE
[BUG] <title>

### ISSUE THREAD

**Issue by derklauer** [docker/compose#10524]
### Description

Docker-Compose throws urllib3 errors starting 3/28/2023 on the 
image `amazon/aws-cli:2.10.2` service `docker:23.0.4-cli-alpine3.17`
`Traceback (most recent call last):
  File "/usr/local/bin/docker-compose", line 5, in <module>
    from compose.cli.main import main
  File "/usr/local/lib/python3.7/site-packages/compose/cli/main.py", line 13, in <module>
    import docker.errors
  File "/usr/local/lib/python3.7/site-packages/docker/__init__.py", line 2, in <module>
    from .api import APIClient
  File "/usr/local/lib/python3.7/site-packages/docker/api/__init__.py", line 2, in <module>
    from .client import APIClient
  File "/usr/local/lib/python3.7/site-packages/docker/api/client.py", line 6, in <module>
    import requests
  File "/usr/local/lib/python3.7/site-packages/requests/__init__.py", line 43, in <module>
    import urllib3
  File "/usr/local/lib/python3.7/site-packages/urllib3/__init__.py", line 39, in <module>
    "urllib3 v2.0 only supports OpenSSL 1.1.1+, currently "
ImportError: urllib3 v2.0 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with OpenSSL 1.0.2k-fips  26 Jan 2017.`

### Steps To Reproduce

      1. amazon-linux-extras install docker
      2. yum install python3-pip -y
      3. pip3 install docker-compose

### Compose Version

```Text
latest
```

### Docker Environment

```Text
image: `amazon/aws-cli:2.10.2` service `docker:23.0.4-cli-alpine3.17`
```

### Anything else?

It seems related to this issue: https://github.com/psf/requests/issues/6432

**Comment by glours** [comment]
Thanks for taking the time to create this issue/pull request!

Unfortunately, Docker Compose V1 has reached end-of-life and we are not accepting any more changes (except for security issues). Please try and reproduce your issue with Compose V2 or rewrite your pull request to be based on the v2 branch and create a new issue or PR with the relevant Compose V2 information.
