### ISSUE TITLE
unexpected error while I'm trying to use compose command

### ISSUE THREAD

**Issue by dc-developer-master** [docker/compose#10729]
### Description

When I enter the docker compose command to the console or when I try to do something about the container from docker desktop, it gives an error. I shared the error below.

### Steps To Reproduce

```
Deletion failed
compose [down --remove-orphans] exit status 2. fatal error: unexpected signal during runtime execution
[signal SIGBUS: bus error code=0x2 addr=0x2fd04a0 pc=0x45bed0]

runtime stack:
runtime.throw({0x1ff4b56?, 0x1?})
	runtime/panic.go:1047 +0x5d fp=0xc000095690 sp=0xc000095660 pc=0x4381bd
runtime.sigpanic()
	runtime/signal_unix.go:821 +0x3e9 fp=0xc0000956f0 sp=0xc000095690 pc=0x44e669
runtime.gentraceback(0x0?, 0x0?, 0x0?, 0xc0000061a0, 0x0, 0x0, 0x7fffffff, 0x20ca598, 0x369?, 0x0)
	runtime/traceback.go:135 +0x3f0 fp=0xc000095a48 sp=0xc0000956f0 pc=0x45bed0
runtime.copystack(0xc0000061a0, 0xc000095dc8?)
	runtime/stack.go:934 +0x2f5 fp=0xc000095c00 sp=0xc000095a48 pc=0x4515d5
runtime.shrinkstack(0xc0000061a0)
	runtime/stack.go:1216 +0x134 fp=0xc000095c20 sp=0xc000095c00 pc=0x452494
runtime.scanstack(0xc0000061a0, 0xc00006bc38)
	runtime/mgcmark.go:775 +0xf2 fp=0xc000095e28 sp=0xc000095c20 pc=0x420172
runtime.markroot.func1()
	runtime/mgcmark.go:239 +0xb5 fp=0xc000095e78 sp=0xc000095e28 pc=0x41f075
runtime.markroot(0xc00006bc38, 0x15, 0x1)
	runtime/mgcmark.go:213 +0x1a5 fp=0xc000095f18 sp=0xc000095e78 pc=0x41ed25
runtime.gcDrain(0xc00006bc38, 0x2)
	runtime/mgcmark.go:1069 +0x39f fp=0xc000095f78 sp=0xc000095f18 pc=0x420e1f
runtime.gcBgMarkWorker.func2()
	runtime/mgc.go:1363 +0x157 fp=0xc000095fc8 sp=0xc000095f78 pc=0x41d3d7
runtime.systemstack()
	runtime/asm_amd64.s:496 +0x49 fp=0xc000095fd0 sp=0xc000095fc8 pc=0x469e29

goroutine 22 [GC worker (active)]:
runtime.systemstack_switch()
	runtime/asm_amd64.s:463 fp=0xc00051bf50 sp=0xc00051bf48 pc=0x469dc0
runtime.gcBgMarkWorker()
	runtime/mgc.go:1335 +0x205 fp=0xc00051bfe0 sp=0xc00051bf50 pc=0x41cfc5
runtime.goexit()
	runtime/asm_amd64.s:1598 +0x1 fp=0xc00051bfe8 sp=0xc00051bfe0 pc=0x46bea1
created by runtime.gcBgMarkStartWorkers
	runtime/mgc.go:1199 +0x25

goroutine 1 [GC assist marking (scan), locked to thread]:
runtime.systemstack_switch()
	runtime/asm_amd64.s:463 fp=0xc0007bf398 sp=0xc0007bf390 pc=0x469dc0
runtime.gcAssistAlloc(0xc0000061a0)
	runtime/mgcmark.go:474 +0x1a5 fp=0xc0007bf3f8 sp=0xc0007bf398 pc=0x41f805
runtime.deductAssistCredit(0x31fc9a0?)
	runtime/malloc.go:1217 +0x5a fp=0xc0007bf420 sp=0xc0007bf3f8 pc=0x40df1a
runtime.mallocgc(0x110, 0x1dfcb40, 0x1)
	runtime/malloc.go:932 +0xd0 fp=0xc0007bf488 sp=0xc0007bf420 pc=0x40d730
runtime.newobject(...)
	runtime/malloc.go:1254
runtime.mapassign_faststr(0x1caad00, 0xc00034e000, {0x0, 0x0})
	runtime/map_faststr.go:221 +0xa8 fp=0xc0007bf4f8 sp=0xc0007bf488 pc=0x413ba8
fatal error: unexpected signal during runtime execution
panic during panic
[signal SIGBUS: bus error code=0x2 addr=0x2fd04a0 pc=0x45bed0]

runtime stack:
runtime.throw({0x1ff4b56?, 0x229b478?})
	runtime/panic.go:1047 +0x5d fp=0xc000094f18 sp=0xc000094ee8 pc=0x4381bd
runtime.sigpanic()
	runtime/signal_unix.go:821 +0x3e9 fp=0xc000094f78 sp=0xc000094f18 pc=0x44e669
runtime.gentraceback(0x2bf4dd8?, 0x3169860?, 0xc000095330?, 0xc0000061a0, 0x0, 0x0, 0x64, 0x0, 0x41cd65?, 0x0)
	runtime/traceback.go:135 +0x3f0 fp=0xc0000952d0 sp=0xc000094f78 pc=0x45bed0
runtime.traceback1(0xc0000061a0?, 0x439c00?, 0x3?, 0xc0000061a0, 0x45f19b?)
	runtime/traceback.go:776 +0x1b6 fp=0xc000095490 sp=0xc0000952d0 pc=0x45e496
runtime.traceback(...)
	runtime/traceback.go:723
runtime.tracebackothers.func1(0xc0000061a0)
	runtime/traceback.go:992 +0xe5 fp=0xc0000954d0 sp=0xc000095490 pc=0x45f3c5
runtime.forEachGRace(0xc000095538)
	runtime/proc.go:604 +0x4d fp=0xc000095500 sp=0xc0000954d0 pc=0x43ba0d
runtime.tracebackothers(0xc000007040?)
	runtime/traceback.go:978 +0xe5 fp=0xc000095568 sp=0xc000095500 pc=0x45f2a5
runtime.dopanic_m(0xc000007040, 0x229b478?, 0x1?)
	runtime/panic.go:1269 +0x285 fp=0xc0000955e0 sp=0xc000095568 pc=0x438b65
runtime.fatalthrow.func1()
	runtime/panic.go:1123 +0x48 fp=0xc000095620 sp=0xc0000955e0 pc=0x438588
runtime.fatalthrow(0x95668?)
	runtime/panic.go:1120 +0x6c fp=0xc000095660 sp=0xc000095620 pc=0x43850c
runtime.throw({0x1ff4b56?, 0x1?})
	runtime/panic.go:1047 +0x5d fp=0xc000095690 sp=0xc000095660 pc=0x4381bd
runtime.sigpanic()
	runtime/signal_unix.go:821 +0x3e9 fp=0xc0000956f0 sp=0xc000095690 pc=0x44e669
runtime.gentraceback(0x0?, 0x0?, 0x0?, 0xc0000061a0, 0x0, 0x0, 0x7fffffff, 0x20ca598, 0x369?, 0x0)
	runtime/traceback.go:135 +0x3f0 fp=0xc000095a48 sp=0xc0000956f0 pc=0x45bed0
runtime.copystack(0xc0000061a0, 0xc000095dc8?)
	runtime/stack.go:934 +0x2f5 fp=0xc000095c00 sp=0xc000095a48 pc=0x4515d5
runtime.shrinkstack(0xc0000061a0)
	runtime/stack.go:1216 +0x134 fp=0xc000095c20 sp=0xc000095c00 pc=0x452494
runtime.scanstack(0xc0000061a0, 0xc00006bc38)
	runtime/mgcmark.go:775 +0xf2 fp=0xc000095e28 sp=0xc000095c20 pc=0x420172
runtime.markroot.func1()
	runtime/mgcmark.go:239 +0xb5 fp=0xc000095e78 sp=0xc000095e28 pc=0x41f075
runtime.markroot(0xc00006bc38, 0x15, 0x1)
	runtime/mgcmark.go:213 +0x1a5 fp=0xc000095f18 sp=0xc000095e78 pc=0x41ed25
runtime.gcDrain(0xc00006bc38, 0x2)
	runtime/mgcmark.go:1069 +0x39f fp=0xc000095f78 sp=0xc000095f18 pc=0x420e1f
runtime.gcBgMarkWorker.func2()
	runtime/mgc.go:1363 +0x157 fp=0xc000095fc8 sp=0xc000095f78 pc=0x41d3d7
runtime.systemstack()
	runtime/asm_amd64.s:496 +0x49 fp=0xc000095fd0 sp=0xc000095fc8 pc=0x469e29
```

### Compose Version

```Text
Docker Compose version v2.18.1
```

### Docker Environment

```Text
gives same error I don't know container info
```

### Anything else?

![image](https://github.com/docker/compose/assets/75244291/9631cd53-c66b-4311-9f74-e37937791c36)
![image](https://github.com/docker/compose/assets/75244291/821e502e-98d2-4cba-bc2f-b656a964e02e)
![image](https://github.com/docker/compose/assets/75244291/b155490a-af4d-4648-9bee-4aa69c02f9d0)

**Comment by milas** [comment]
We've seen errors like this under WSL2 sometimes. Try running `wsl --update` to ensure you've got the latest kernel, etc. and see if that helps.

**Comment by ndeloof** [comment]
I'm closing this issue as obsolete with no update for 1 year
