### ISSUE TITLE
Docker dependency issue

### ISSUE THREAD

**Issue by Mchim91** [docker/compose#10869]
I have installed opencv-python that's compatible to my python version inside my docker container and when I ran the container I was getting 
```
✔ Container docker-app-1  Created                                                                                                                                                     0.0s 
Attaching to docker-app-1
docker-app-1  | Traceback (most recent call last):
docker-app-1  |   File "<frozen runpy>", line 198, in _run_module_as_main
docker-app-1  |   File "<frozen runpy>", line 88, in _run_code
docker-app-1  |   File "C:\Python\Scripts\uvicorn.exe\__main__.py", line 7, in <module>
docker-app-1  |   File "C:\Python\Lib\site-packages\click\core.py", line 1157, in __call__
docker-app-1  |     return self.main(*args, **kwargs)
docker-app-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^
docker-app-1  |   File "C:\Python\Lib\site-packages\click\core.py", line 1078, in main
docker-app-1  |     rv = self.invoke(ctx)
docker-app-1  |          ^^^^^^^^^^^^^^^^
docker-app-1  |   File "C:\Python\Lib\site-packages\click\core.py", line 1434, in invoke
docker-app-1  |     return ctx.invoke(self.callback, **ctx.params)
docker-app-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
docker-app-1  |   File "C:\Python\Lib\site-packages\click\core.py", line 783, in invoke
docker-app-1  |     return __callback(*args, **kwargs)
docker-app-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
docker-app-1  |   File "C:\Python\Lib\site-packages\uvicorn\main.py", line 416, in main
docker-app-1  |     run(
docker-app-1  |   File "C:\Python\Lib\site-packages\uvicorn\main.py", line 587, in run
docker-app-1  |     server.run()
docker-app-1  |   File "C:\Python\Lib\site-packages\uvicorn\server.py", line 61, in run
docker-app-1  |     return asyncio.run(self.serve(sockets=sockets))
docker-app-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
docker-app-1  |   File "C:\Python\Lib\asyncio\runners.py", line 190, in run
docker-app-1  |     return runner.run(main)
docker-app-1  |            ^^^^^^^^^^^^^^^^
docker-app-1  |   File "C:\Python\Lib\asyncio\runners.py", line 118, in run
docker-app-1  |     return self._loop.run_until_complete(task)
docker-app-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
docker-app-1  |   File "C:\Python\Lib\asyncio\base_events.py", line 653, in run_until_complete
docker-app-1  |     return future.result()
docker-app-1  |            ^^^^^^^^^^^^^^^
docker-app-1  |   File "C:\Python\Lib\site-packages\uvicorn\server.py", line 68, in serve
docker-app-1  |     config.load()
docker-app-1  |   File "C:\Python\Lib\site-packages\uvicorn\config.py", line 467, in load
docker-app-1  |     self.loaded_app = import_from_string(self.app)
docker-app-1  |                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
docker-app-1  |   File "C:\Python\Lib\site-packages\uvicorn\importer.py", line 21, in import_from_string
docker-app-1  |     module = importlib.import_module(module_str)
docker-app-1  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
docker-app-1  |   File "C:\Python\Lib\importlib\__init__.py", line 126, in import_module
docker-app-1  |     return _bootstrap._gcd_import(name[level:], package, level)
docker-app-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
docker-app-1  |   File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
docker-app-1  |   File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
docker-app-1  |   File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
docker-app-1  |   File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
docker-app-1  |   File "<frozen importlib._bootstrap_external>", line 940, in exec_module
docker-app-1  |   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
docker-app-1  |   File "C:\code\app\main.py", line 3, in <module>
docker-app-1  |     import cv2
docker-app-1  |   File "C:\Python\Lib\site-packages\cv2\__init__.py", line 181, in <module>
docker-app-1  |     bootstrap()
docker-app-1  |   File "C:\Python\Lib\site-packages\cv2\__init__.py", line 153, in bootstrap
docker-app-1  |     native_module = importlib.import_module("cv2")
docker-app-1  |                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
docker-app-1  |   File "C:\Python\Lib\importlib\__init__.py", line 126, in import_module
docker-app-1  |     return _bootstrap._gcd_import(name[level:], package, level)
docker-app-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
docker-app-1  | ImportError: DLL load failed while importing cv2: The specified module could not be found.
```
How can I be able to solve this issue?

**Comment by glours** [comment]
Hello @Mchim91
Could you please respect the issue template, this give us important information to help you.

Nevermind, I don't think this is a Compose issue. 
Can you test with a `docker run` command to check if you reproduce the problem

**Comment by milas** [comment]
Yes, this looks like it's not an issue with Compose.

The Python import is failing with a DLL error, you likely are missing the required files inside of the container. For example, take a look at https://stackoverflow.com/questions/46147012/opencv-import-failed-in-windows-container-on-windows-server-2016
