### ISSUE TITLE
ValueError: dictionary update sequence element #0 has length 1; 2 is required

### ISSUE THREAD

**Issue by dw72** [docker/compose#1101]
When i do docker-compose up:

Creating kurs_mysql_1...
Traceback (most recent call last):
  File "<string>", line 3, in <module>
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.cli.main", line 31, in main
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.cli.docopt_command", line 21, in sys_dispatch
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.cli.command", line 27, in dispatch
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.cli.docopt_command", line 24, in dispatch
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.cli.command", line 59, in perform_command
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.cli.main", line 445, in up
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.project", line 184, in up
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.service", line 259, in recreate_containers
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.service", line 227, in create_container
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.service", line 453, in _get_container_create_options
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.service", line 642, in merge_environment
ValueError: dictionary update sequence element #0 has length 1; 2 is required

My [docker-compose.yml](https://gist.github.com/dw72/dbec2c81841902c78189) file

**Comment by dnephin** [comment]
The value you're assigning to `environemt` needs to be a list or mapping, you're passing it a string. You'll need to add a dash. This is fixed in master by #970 and will give a proper error.

**Comment by dw72** [comment]
Thanks, its working now :)

**Comment by huaweichen** [comment]
Actually:

$ docker-compose up -d 
```

ERROR: The Compose file './docker-compose.yml' is invalid because:
services.mariadb.environment contains {"MYSQL_ROOT_PASSWORD": "password"}, which is an invalid type, it should be a string
services.nginx.environment contains {"NGINX_STATIC_CONTENT_OPEN_FILE_CACHE": "off"}, which is an invalid type, it should be a string
services.php.environment contains {"PHP_SENDMAIL_PATH": "/usr/sbin/sendmail -t -i -S mailhog:1025"}, which is an invalid type, it should be a string
services.pma.environment contains {"PMA_HOST": "mariadb"}, which is an invalid type, it should be a string

```
