### ISSUE TITLE
[BUG] panic: sync: WaitGroup is reused before previous Wait has returned after pressing Ctrl+C

### ISSUE THREAD

**Issue by cvybhu** [docker/compose#11056]
### Description

After pressing Ctrl+C to stop all containers started with `docker compose up`, docker compose crashed with the following error:

```
^CGracefully stopping... (press Ctrl+C again to force)
Aborting on container exit...
panic: sync: WaitGroup is reused before previous Wait has returned

goroutine 1 [running]:
sync.(*WaitGroup).Wait(0x202a8e0?)
        sync/waitgroup.go:118 +0x7f
golang.org/x/sync/errgroup.(*Group).Wait(0xc0004c1940)
        golang.org/x/sync@v0.3.0/errgroup/errgroup.go:53 +0x27
github.com/docker/compose/v2/pkg/compose.(*composeService).Up(0xc0001a6c30, {0x2637c80, 0xc0005f8320}, 0xc00063e0c0, {{{0xc0001a59e0, 0x0, 0x1}, 0x0, 0x0, {0x22d56e5, ...}, ...}, ...})
        github.com/docker/compose/v2/pkg/compose/up.go:105 +0x69c
github.com/docker/compose/v2/pkg/api.(*ServiceProxy).Up(0xc00011c100, {0x2637c80, 0xc0005f8320}, 0x0?, {{{0xc0001a59e0, 0x0, 0x1}, 0x0, 0x0, {0x22d56e5, ...}, ...}, ...})
        github.com/docker/compose/v2/pkg/api/proxy.go:185 +0x14a
github.com/docker/compose/v2/cmd/compose.runUp({0x2637c80?, 0xc0005f8320}, {0x7fa0c148ca80, 0xc0006720f0}, {0x2650338, _}, {0x1, 0x0, {0x22d3e0f, 0x7}, ...}, ...)
        github.com/docker/compose/v2/cmd/compose/up.go:217 +0xa31
github.com/docker/compose/v2/cmd/compose.upCommand.func2({0x2637c80, 0xc0005f8320}, 0xc00063e0c0, {0xc0001a59e0, 0x0, 0x1})
        github.com/docker/compose/v2/cmd/compose/up.go:93 +0x265
github.com/docker/compose/v2/cmd/compose.(*ProjectOptions).WithServices.func1({0x2637c80?, 0xc0005f8320}, {0xc0001a59e0, 0x0, 0x1})
        github.com/docker/compose/v2/cmd/compose/compose.go:161 +0x248
github.com/docker/compose/v2/cmd/compose.Adapt.func1({0x2637c80?, 0xc0005f8320?}, 0x2?, {0xc0001a59e0?, 0x1?, 0xc00047d950?})
        github.com/docker/compose/v2/cmd/compose/compose.go:108 +0x36
github.com/docker/compose/v2/cmd/compose.AdaptCmd.func1(0xc000004900, {0xc0001a59e0, 0x0, 0x1})
        github.com/docker/compose/v2/cmd/compose/compose.go:87 +0x21c
github.com/docker/compose/v2/cmd/cmdtrace.wrapRunE.func2(0xc000004900?, {0xc0001a59e0?, 0x0?, 0x1?})
        github.com/docker/compose/v2/cmd/cmdtrace/cmd_span.go:80 +0x73
github.com/spf13/cobra.(*Command).execute(0xc000004900, {0xc0002680b0, 0x1, 0x1})
        github.com/spf13/cobra@v1.7.0/command.go:940 +0x862
github.com/spf13/cobra.(*Command).ExecuteC(0xc000262f00)
        github.com/spf13/cobra@v1.7.0/command.go:1068 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
        github.com/spf13/cobra@v1.7.0/command.go:992
github.com/docker/cli/cli-plugins/plugin.RunPlugin(0x188?, 0xc000004600, {{0x22cfb8e, 0x5}, {0x22d9ca9, 0xb}, {0x2610938, 0x7}, {0x0, 0x0}, ...})
        github.com/docker/cli@v24.0.5+incompatible/cli-plugins/plugin/plugin.go:51 +0x130
github.com/docker/cli/cli-plugins/plugin.Run(0x240d410, {{0x22cfb8e, 0x5}, {0x22d9ca9, 0xb}, {0x2610938, 0x7}, {0x0, 0x0}, {0x0, ...}, ...})
        github.com/docker/cli@v24.0.5+incompatible/cli-plugins/plugin/plugin.go:64 +0xee
main.pluginMain()
        github.com/docker/compose/v2/cmd/main.go:37 +0xdf
main.main()
        github.com/docker/compose/v2/cmd/main.go:75 +0x198
```

The containers weren't stopped, I had to manually run `docker compose down` to stop them.

I expected `docker compose` not to crash.

### Steps To Reproduce

1. Create a docker compose with a single, long running service
2. Run `docker compose up --build`
3. Stop everything by pressing `Ctrl + C`
4. Crash

It happened only once, reproducing probably requires specific timing

### Compose Version

```Text
Docker Compose Version v2.21.0
```

### Docker Environment

```Text
Client: Docker Engine - Community
 Version:    24.0.6
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.11.2
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.21.0
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 1
  Running: 1
  Paused: 0
  Stopped: 0
 Images: 39
 Server Version: 24.0.6
 Storage Driver: overlay2
  Backing Filesystem: btrfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 61f9fd88f79f081d64d6fa3bb1a0dc71ec870523
 runc version: v1.1.9-0-gccaecfc
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 6.1.0-12-amd64
 Operating System: Debian GNU/Linux 12 (bookworm)
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 11.6GiB
 Name: <redacted>
 ID: <redacted>
 Docker Root Dir: <redacted>
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Comment by ndeloof** [comment]
Already fixed by https://github.com/docker/compose/pull/10934
