### ISSUE TITLE
[BUG] WSL Docker compose up : panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by LuizProject46** [docker/compose#11148]
### Description

`docker compose up -d`

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x187e506]

goroutine 14 [running]:
github.com/docker/compose/v2/pkg/compose.(*composeService).getDrivers(0xc00060d938, {0x20a35e8, 0xc000885830})
        github.com/docker/compose/v2/pkg/compose/build_buildkit.go:95 +0xc6
github.com/docker/compose/v2/pkg/compose.(*composeService).doBuildBuildkit(0xc00060d938, {0x20a35e8, 0xc000885830}, 0x0?, {0x1d9286a, 0x4})
        github.com/docker/compose/v2/pkg/compose/build_buildkit.go:47 +0x87
github.com/docker/compose/v2/pkg/compose.(*composeService).doBuild(0xc00060d938, {0x20a35e8, 0xc000885830}, 0xc000888280?, 0xc0000d8990, {0x1d9286a, 0x4})
        github.com/docker/compose/v2/pkg/compose/build.go:218 +0xc5
github.com/docker/compose/v2/pkg/compose.(*composeService).ensureImagesExists(0x0?, {0x20a35e8, 0xc000885830}, 0xc000888280, 0x0)
        github.com/docker/compose/v2/pkg/compose/build.go:127 +0x14d
github.com/docker/compose/v2/pkg/compose.(*composeService).create(0xc00060d938?, {0x20a35e8, 0xc000885830}, 0xc000888280, {{0xc0003b8680, 0x5, 0x8}, 0x0, 0x0, {0x1d9830b, ...}, ...})
        github.com/docker/compose/v2/pkg/compose/create.go:68 +0x173
github.com/docker/compose/v2/pkg/compose.(*composeService).Up.func1({0x20a35e8, 0xc000885830})
        github.com/docker/compose/v2/pkg/compose/up.go:35 +0xaa
github.com/docker/compose/v2/pkg/progress.Run.func1({0x20a35e8?, 0xc000885830?})
        github.com/docker/compose/v2/pkg/progress/writer.go:61 +0x27
github.com/docker/compose/v2/pkg/progress.RunWithStatus.func2()
        github.com/docker/compose/v2/pkg/progress/writer.go:82 +0x87
golang.org/x/sync/errgroup.(*Group).Go.func1()
        golang.org/x/sync@v0.1.0/errgroup/errgroup.go:75 +0x64
created by golang.org/x/sync/errgroup.(*Group).Go
        golang.org/x/sync@v0.1.0/errgroup/errgroup.go:72 +0xa5
```

**Comment by ndeloof** [comment]
Which version are your running (`docker compose version`) ?
AFAICT you're running an old version, can you please install latest release and confirm this but has been fixed ?

**Comment by rhtenhove** [comment]
Can confirm this happens with version `2.21.0`, which is the latest provided by the ubuntu package. Updating it manually to `2.22.0` or later solves the problem. Like so:

```shell
sudo wget https://github.com/docker/compose/releases/download/v2.23.0/docker-compose-linux-x86_64 -O /usr/libexec/docker/cli-plugins/docker-compose
sudo chmod +x /usr/libexec/docker/cli-plugins/docker-compose
```

Not sure if when the apt package is updated, this will just be overwritten with the new version in there. Probably so.

**Comment by glours** [comment]
@LuizProject46 @rhtenhove are you using Docker Desktop for Windows or do you install Docker+Compose by yourself inside your WSL VM?

**Comment by rhtenhove** [comment]
I've installed it using the [install on Ubuntu](https://docs.docker.com/engine/install/ubuntu/) steps

**Comment by ndeloof** [comment]
the debian/ubuntu packages are managed by https://github.com/docker/docker-ce-packaging and don't align with our release cycle, so this is not a surprise you don't get the "latest" release using those.
I'm closing this issue as you confirmed a recent release fixed this issue
