### ISSUE TITLE
ERROR: Service failed to build : Build failed

### ISSUE THREAD

**Issue by louistwiice** [docker/compose#11432]
### Description

I don't know why but I can not run this docker-compose file in this environment. I receive the error 

```
The command '/bin/sh -c pip install --upgrade pip' returned a non-zero code: 2
ERROR: Service 'api' failed to build : Build failed
```

Do you guyz know how to solve this issue please ?

### Steps To Reproduce

1. Environnement

- Docker: 20.10.5
- Docker compose: 1.29.1

2. Config

My Dockerfile

```
# pull official base image
FROM python:3.10

# set work directory
WORKDIR /app

# set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# install dependencies
RUN pip install --upgrade pip
COPY ./requirements.txt .
RUN pip install -r requirements.txt

# copy project
COPY . .

CMD ["sh", "-c", "python manage.py collectstatic --no-input; python manage.py migrate; gunicorn wzdistri.wsgi -b 0.0.0.0:8000 -w 3 -k gevent --worker-tmp-dir /dev/shm --timeout 470 --reload"]
```

My docker-compose file

```
version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: unless-stopped
    volumes:
      - ./:/usr/src/app
      - api-static:/app/static
      - api-media:/app/media
      - ${PROD_DOCKER_LOGS_PATH_API}:/app/logs/
    ports:
      - "${PROD_PORT_API}:8000"
    env_file:
      - ./.env.prod
    logging:
      driver: "fluentd"
      options:
        fluentd-address: ${FLUENTD_ADDRESS}
        tag: wz-distri_prod

  nginx:
    image: nginx:1.20.1
    restart: unless-stopped
    ports:
      - "${PROD_PORT_NGINX}:80"
    volumes:
      - ./config/nginx/conf.d:/etc/nginx/conf.d
      - api-static:/app/static
      - api-media:/app/media
    links:
      - api
    depends_on:
      - api

volumes:
  api-static:
  api-media:
```

My .env file

```
PROD_PORT_NGINX=7001
PROD_PORT_API=7010
PROD_DOCKER_LOGS_PATH_API=/my/path/
FLUENTD_ASYNC_CONNECT=false
FLUENTD_ADDRESS=IP_ADDRESS:24200
```

### Compose Version

```Text
docker-compose version 1.29.1, build c34c88b2
docker-py version: 5.0.0
CPython version: 3.7.10
OpenSSL version: OpenSSL 1.1.0l  10 Sep 2019
```

### Docker Environment

```Text
Client: Docker Engine - Community
 Version:           20.10.5
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        55c4c88
 Built:             Tue Mar  2 20:18:05 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.5
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       363e9a8
  Built:            Tue Mar  2 20:16:00 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.4
  GitCommit:        05f951a3781f4f2c1911b05e61c160e9c30eaa8e
 runc:
  Version:          1.0.0-rc93
  GitCommit:        12644e614e25b05da6fd08a38ffa0cfe1903fdec
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### Anything else?

this is what I got when I run `docker-compose build`

nginx uses an image, skipping
Building api
Sending build context to Docker daemon   1.58MB
Step 1/9 : FROM python:3.10
 ---> e399a6a8821d
Step 2/9 : WORKDIR /app
 ---> Using cache
 ---> 663092649a23
Step 3/9 : ENV PYTHONDONTWRITEBYTECODE 1
 ---> Using cache
 ---> 20fe314696f6
Step 4/9 : ENV PYTHONUNBUFFERED 1
 ---> Using cache
 ---> 25db1ab121ae
Step 5/9 : RUN pip install --upgrade pip
 ---> Running in 9057e60550cf
Requirement already satisfied: pip in /usr/local/lib/python3.10/site-packages (23.0.1)
Collecting pip
  Downloading pip-23.3.2-py3-none-any.whl (2.1 MB)
ERROR: Exception:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/pip/_internal/cli/base_command.py", line 160, in exc_logging_wrapper
    status = run_func(*args)
  File "/usr/local/lib/python3.10/site-packages/pip/_internal/cli/req_command.py", line 247, in wrapper
    return func(self, options, args)
  File "/usr/local/lib/python3.10/site-packages/pip/_internal/commands/install.py", line 419, in run
    requirement_set = resolver.resolve(
  File "/usr/local/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 92, in resolve
    result = self._result = resolver.resolve(
  File "/usr/local/lib/python3.10/site-packages/pip/_vendor/resolvelib/resolvers.py", line 481, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "/usr/local/lib/python3.10/site-packages/pip/_vendor/resolvelib/resolvers.py", line 348, in resolve
    self._add_to_criteria(self.state.criteria, r, parent=None)
  File "/usr/local/lib/python3.10/site-packages/pip/_vendor/resolvelib/resolvers.py", line 172, in _add_to_criteria
    if not criterion.candidates:
  File "/usr/local/lib/python3.10/site-packages/pip/_vendor/resolvelib/structs.py", line 151, in __bool__
    return bool(self._sequence)
  File "/usr/local/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 155, in __bool__
    return any(self)
  File "/usr/local/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 143, in <genexpr>
    return (c for c in iterator if id(c) not in self._incompatible_ids)
  File "/usr/local/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 97, in _iter_built_with_inserted
    candidate = func()
  File "/usr/local/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 206, in _make_candidate_from_link
    self._link_candidate_cache[link] = LinkCandidate(
  File "/usr/local/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 297, in __init__
    super().__init__(
  File "/usr/local/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 162, in __init__
    self.dist = self._prepare()
  File "/usr/local/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 231, in _prepare
    dist = self._prepare_distribution()
  File "/usr/local/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 308, in _prepare_distribution
    return preparer.prepare_linked_requirement(self._ireq, parallel_builds=True)
  File "/usr/local/lib/python3.10/site-packages/pip/_internal/operations/prepare.py", line 491, in prepare_linked_requirement
    return self._prepare_linked_requirement(req, parallel_builds)
  File "/usr/local/lib/python3.10/site-packages/pip/_internal/operations/prepare.py", line 536, in _prepare_linked_requirement
    local_file = unpack_url(
  File "/usr/local/lib/python3.10/site-packages/pip/_internal/operations/prepare.py", line 166, in unpack_url
    file = get_http_url(
  File "/usr/local/lib/python3.10/site-packages/pip/_internal/operations/prepare.py", line 107, in get_http_url
    from_path, content_type = download(link, temp_dir.path)
  File "/usr/local/lib/python3.10/site-packages/pip/_internal/network/download.py", line 147, in __call__
    for chunk in chunks:
  File "/usr/local/lib/python3.10/site-packages/pip/_internal/cli/progress_bars.py", line 52, in _rich_progress_bar
    with progress:
  File "/usr/local/lib/python3.10/site-packages/pip/_vendor/rich/progress.py", line 1169, in __enter__
    self.start()
  File "/usr/local/lib/python3.10/site-packages/pip/_vendor/rich/progress.py", line 1160, in start
    self.live.start(refresh=True)
  File "/usr/local/lib/python3.10/site-packages/pip/_vendor/rich/live.py", line 132, in start
    self._refresh_thread.start()
  File "/usr/local/lib/python3.10/threading.py", line 935, in start
    _start_new_thread(self._bootstrap, ())
RuntimeError: can't start new thread

[notice] A new release of pip is available: 23.0.1 -> 23.3.2
[notice] To update, run: pip install --upgrade pip
The command '/bin/sh -c pip install --upgrade pip' returned a non-zero code: 2
ERROR: Service 'api' failed to build : Build failed

**Comment by jhrotko** [comment]
Hello, @louistwiice 

This error is not related with compose. The status message `ERROR: Service 'api' failed to build : Build failed` is related with an error that occurred during your build. 
I would also suggest updating your Docker and Docker compose. (currently Docker -> 24.0.7 Compose -> v2.24.6)
