### ISSUE TITLE
pip install docker-compose Generates AttributeError: cython_sources

### ISSUE THREAD

**Issue by zackees** [docker/compose#11530]
### Description

This happens in windows

```
pip install docker-compose
```

```
C:\Users\niteris\test>uv pip install docker-compose
Resolved 28 packages in 20ms
error: Failed to download distributions
  Caused by: Failed to fetch wheel: pyyaml==5.4.1
  Caused by: Failed to build: pyyaml==5.4.1
  Caused by: Build backend failed to determine extra requires with `build_wheel()`:
--- stdout:
running egg_info
writing lib3\PyYAML.egg-info\PKG-INFO
writing dependency_links to lib3\PyYAML.egg-info\dependency_links.txt
writing top-level names to lib3\PyYAML.egg-info\top_level.txt
--- stderr:
Traceback (most recent call last):
  File "<string>", line 10, in <module>
  File "C:\Users\niteris\AppData\Local\Temp\.tmp24N7yB\.venv\lib\site-packages\setuptools\build_meta.py", line 325, in get_requires_for_build_wheel
    return self._get_build_requires(config_settings, requirements=['wheel'])
  File "C:\Users\niteris\AppData\Local\Temp\.tmp24N7yB\.venv\lib\site-packages\setuptools\build_meta.py", line 295, in _get_build_requires
    self.run_setup()
  File "C:\Users\niteris\AppData\Local\Temp\.tmp24N7yB\.venv\lib\site-packages\setuptools\build_meta.py", line 311, in run_setup
    exec(code, locals())
  File "<string>", line 271, in <module>
  File "C:\Users\niteris\AppData\Local\Temp\.tmp24N7yB\.venv\lib\site-packages\setuptools\__init__.py", line 103, in setup
    return distutils.core.setup(**attrs)
  File "C:\Users\niteris\AppData\Local\Temp\.tmp24N7yB\.venv\lib\site-packages\setuptools\_distutils\core.py", line 185, in setup
    return run_commands(dist)
  File "C:\Users\niteris\AppData\Local\Temp\.tmp24N7yB\.venv\lib\site-packages\setuptools\_distutils\core.py", line 201, in run_commands
    dist.run_commands()
  File "C:\Users\niteris\AppData\Local\Temp\.tmp24N7yB\.venv\lib\site-packages\setuptools\_distutils\dist.py", line 969, in run_commands
    self.run_command(cmd)
  File "C:\Users\niteris\AppData\Local\Temp\.tmp24N7yB\.venv\lib\site-packages\setuptools\dist.py", line 963, in run_command
    super().run_command(command)
  File "C:\Users\niteris\AppData\Local\Temp\.tmp24N7yB\.venv\lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
    cmd_obj.run()
  File "C:\Users\niteris\AppData\Local\Temp\.tmp24N7yB\.venv\lib\site-packages\setuptools\command\egg_info.py", line 321, in run
    self.find_sources()
  File "C:\Users\niteris\AppData\Local\Temp\.tmp24N7yB\.venv\lib\site-packages\setuptools\command\egg_info.py", line 329, in find_sources
    mm.run()
  File "C:\Users\niteris\AppData\Local\Temp\.tmp24N7yB\.venv\lib\site-packages\setuptools\command\egg_info.py", line 550, in run
    self.add_defaults()
  File "C:\Users\niteris\AppData\Local\Temp\.tmp24N7yB\.venv\lib\site-packages\setuptools\command\egg_info.py", line 588, in add_defaults
    sdist.add_defaults(self)
  File "C:\Users\niteris\AppData\Local\Temp\.tmp24N7yB\.venv\lib\site-packages\setuptools\command\sdist.py", line 102, in add_defaults
    super().add_defaults()
  File "C:\Users\niteris\AppData\Local\Temp\.tmp24N7yB\.venv\lib\site-packages\setuptools\_distutils\command\sdist.py", line 251, in add_defaults
    self._add_defaults_ext()
  File "C:\Users\niteris\AppData\Local\Temp\.tmp24N7yB\.venv\lib\site-packages\setuptools\_distutils\command\sdist.py", line 336, in _add_defaults_ext
    self.filelist.extend(build_ext.get_source_files())
  File "<string>", line 201, in get_source_files
  File "C:\Users\niteris\AppData\Local\Temp\.tmp24N7yB\.venv\lib\site-packages\setuptools\_distutils\cmd.py", line 107, in __getattr__
    raise AttributeError(attr)
AttributeError: cython_sources
---
```

### Anything else?

If you get this working then please provide a copy of a locked pip file from say `pip freeze`. The dependency combinations to get this working again are large and I don't know exactly what I'm doing. I spent about 2 hours debugging this and trying to get docker-compose to work. I'd really like the binaries to be distributed with my apps that I use docker to run.

**Comment by glours** [comment]
Hello @zackees 
The python version of Docker Compose has been deprecated and is EOL since June 2023, please avoid to use it's not maintained anymore
