### ISSUE TITLE
Error response from daemon: error while creating mount source path

### ISSUE THREAD

**Issue by dss010101** [docker/compose#11610]
### Description

I am running Docker Desktop on Windows 11, using VSCode + devcontainers as my dev environment.

When Docker Desktop is restarted i am able to open my project, build and all works fine.  However, if my system falls asleep, then i reopen my project, i see the following error:

```
[2024-03-13T03:07:27.677Z] Error response from daemon: error while creating mount source path '/run/desktop
/mnt/host/g/My Drive/Documents/Projects/stock-analysis/alpha_insite/alpha_insite
_app/database/postgres': mkdir /run/desktop/mnt/host/g: file exists
[2024-03-13T03:07:27.798Z] Stop (7475 ms): Run: docker-compose --project-name alpha_insite_app_devcontainer -f g:\My Drive\Documents\Projects\stock-analysis\alpha_insite\alpha_insite_app\.devcontainer\docker-compose.yml -f c:\Users\devuser1\AppData\Roaming\Code - Insiders\User\globalStorage\ms-vscode-remote.remote-containers\data\docker-compose\docker-compose.devcontainer.build-1710299183626.yml -f c:\Users\devuser1\AppData\Roaming\Code - Insiders\User\globalStorage\ms-vscode-remote.remote-containers\data\docker-compose\docker-compose.devcontainer.containerFeatures-1710299240321.yml up -d
[2024-03-13T03:07:27.801Z] Error: Command failed: docker-compose --project-name alpha_insite_app_devcontainer -f g:\My Drive\Documents\Projects\stock-analysis\alpha_insite\alpha_insite_app\.devcontainer\docker-compose.yml -f c:\Users\devuser1\AppData\Roaming\Code - Insiders\User\globalStorage\ms-vscode-remote.remote-containers\data\docker-compose\docker-compose.devcontainer.build-1710299183626.yml -f c:\Users\devuser1\AppData\Roaming\Code - Insiders\User\globalStorage\ms-vscode-remote.remote-containers\data\docker-compose\docker-compose.devcontainer.containerFeatures-1710299240321.yml up -d
[2024-03-13T03:07:27.801Z]     at itA (c:\Users\devuser1\.vscode-insiders\extensions\ms-vscode-remote.remote-containers-0.349.0\dist\spec-node\devContainersSpecCLI.js:429:3379)
[2024-03-13T03:07:27.801Z]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[2024-03-13T03:07:27.801Z]     at async ttA (c:\Users\devuser1\.vscode-insiders\extensions\ms-vscode-remote.remote-containers-0.349.0\dist\spec-node\devContainersSpecCLI.js:409:3170)
[2024-03-13T03:07:27.801Z]     at async StA (c:\Users\devuser1\.vscode-insiders\extensions\ms-vscode-remote.remote-containers-0.349.0\dist\spec-node\devContainersSpecCLI.js:481:3833)
[2024-03-13T03:07:27.801Z]     at async ZC (c:\Users\devuser1\.vscode-insiders\extensions\ms-vscode-remote.remote-containers-0.349.0\dist\spec-node\devContainersSpecCLI.js:481:4775)
[2024-03-13T03:07:27.802Z]     at async trA (c:\Users\devuser1\.vscode-insiders\extensions\ms-vscode-remote.remote-containers-0.349.0\dist\spec-node\devContainersSpecCLI.js:614:11269)
[2024-03-13T03:07:27.802Z]     at async erA (c:\Users\devuser1\.vscode-insiders\extensions\ms-vscode-remote.remote-containers-0.349.0\dist\spec-node\devContainersSpecCLI.js:614:11010)
[2024-03-13T03:07:27.818Z] Stop (71378 ms): Run: C:\Users\devuser1\AppData\Local\Programs\Microsoft VS Code Insiders\Code - Insiders.exe c:\Users\devuser1\.vscode-insiders\extensions\ms-vscode-remote.remote-containers-0.349.0\dist\spec-node\devContainersSpecCLI.js up --user-data-folder c:\Users\devuser1\AppData\Roaming\Code - Insiders\User\globalStorage\ms-vscode-remote.remote-containers\data --container-session-data-folder /tmp/devcontainers-af8afa31-27d7-4fe3-bd10-d893107ac82f1710299166319 --workspace-folder g:\My Drive\Documents\Projects\stock-analysis\alpha_insite\alpha_insite_app --workspace-mount-consistency cached --id-label devcontainer.local_folder=g:\My Drive\Documents\Projects\stock-analysis\alpha_insite\alpha_insite_app --id-label devcontainer.config_file=g:\My Drive\Documents\Projects\stock-analysis\alpha_insite\alpha_insite_app\.devcontainer\devcontainer.json --log-level debug --log-format json --config g:\My Drive\Documents\Projects\stock-analysis\alpha_insite\alpha_insite_app\.devcontainer\devcontainer.json --default-user-env-probe loginInteractiveShell --build-no-cache --remove-existing-container --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root
[2024-03-13T03:07:27.818Z] Exit code 1
[2024-03-13T03:07:27.824Z] Command failed: C:\Users\devuser1\AppData\Local\Programs\Microsoft VS Code Insiders\Code - Insiders.exe c:\Users\devuser1\.vscode-insiders\extensions\ms-vscode-remote.remote-containers-0.349.0\dist\spec-node\devContainersSpecCLI.js up --user-data-folder c:\Users\devuser1\AppData\Roaming\Code - Insiders\User\globalStorage\ms-vscode-remote.remote-containers\data --container-session-data-folder /tmp/devcontainers-af8afa31-27d7-4fe3-bd10-d893107ac82f1710299166319 --workspace-folder g:\My Drive\Documents\Projects\stock-analysis\alpha_insite\alpha_insite_app --workspace-mount-consistency cached --id-label devcontainer.local_folder=g:\My Drive\Documents\Projects\stock-analysis\alpha_insite\alpha_insite_app --id-label devcontainer.config_file=g:\My Drive\Documents\Projects\stock-analysis\alpha_insite\alpha_insite_app\.devcontainer\devcontainer.json --log-level debug --log-format json --config g:\My Drive\Documents\Projects\stock-analysis\alpha_insite\alpha_insite_app\.devcontainer\devcontainer.json --default-user-env-probe loginInteractiveShell --build-no-cache --remove-existing-container --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root
[2024-03-13T03:07:27.824Z] Exit code 1
```

i dont quite understand this part - since i dont have such a mount specified in my compose file:
```
mount source path '/run/desktop
/mnt/host/g/My Drive/Documents/Projects/stock-analysis/alpha_insite/alpha_insite
_app/database/postgres': mkdir /run/desktop/mnt/host/g: file exists
```

My compose file has the following:
```
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    env_file:
      - ./.env      
    volumes:
    #  - ../..:/workspaces:cached
      - ../..:/workspaces
      - ~/.ssh:/home/${USER_NAME}/.ssh
```

**In order to resolve this,  i must run cmd ```wsl --shutdown``` and restart docker-desktop.**

### Docker Environment

```Text
Client:
 Version:    24.0.7
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.12.0-desktop.2
    Path:     C:\Program Files\Docker\cli-plugins\docker-buildx.exe
  compose: Docker Compose (Docker Inc.)
    Version:  v2.23.3-desktop.2
    Path:     C:\Program Files\Docker\cli-plugins\docker-compose.exe
  dev: Docker Dev Environments (Docker Inc.)
    Version:  v0.1.0
    Path:     C:\Program Files\Docker\cli-plugins\docker-dev.exe
  extension: Manages Docker extensions (Docker Inc.)
    Version:  v0.2.21
    Path:     C:\Program Files\Docker\cli-plugins\docker-extension.exe
  feedback: Provide feedback, right in your terminal! (Docker Inc.)
    Version:  0.1
    Path:     C:\Program Files\Docker\cli-plugins\docker-feedback.exe
  init: Creates Docker-related starter files for your project (Docker Inc.)
    Version:  v0.1.0-beta.10
    Path:     C:\Program Files\Docker\cli-plugins\docker-init.exe
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc.)
    Version:  0.6.0
    Path:     C:\Program Files\Docker\cli-plugins\docker-sbom.exe
  scan: Docker Scan (Docker Inc.)
    Version:  v0.26.0
    Path:     C:\Program Files\Docker\cli-plugins\docker-scan.exe
  scout: Docker Scout (Docker Inc.)
    Version:  v1.2.0
    Path:     C:\Program Files\Docker\cli-plugins\docker-scout.exe

Server:
 Containers: 4
  Running: 1
  Paused: 0
  Stopped: 3
 Images: 16
 Server Version: 24.0.7
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: d8f198a4ed8892c764191ef7b3b06d8a2eeb5c7f
 runc version: v1.1.10-0-g18a0cb0
 init version: de40ad0
 Security Options:
  seccomp
   Profile: unconfined
 Kernel Version: 5.15.146.1-microsoft-standard-WSL2
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 16
 Total Memory: 19.25GiB
 Name: docker-desktop
 ID: 27fa49f8-2bb6-4fc3-8a08-342f8072a5a4
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 No Proxy: hubproxy.docker.internal
 Experimental: false
 Insecure Registries:
  hubproxy.docker.internal:5555
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No blkio throttle.read_bps_device support
WARNING: No blkio throttle.write_bps_device support
WARNING: No blkio throttle.read_iops_device support
WARNING: No blkio throttle.write_iops_device support
WARNING: daemon is not using the default seccomp profile
```

**Comment by ndeloof** [comment]
AFAICT this is a docker desktop issue, not a compose one. Please report on https://github.com/docker/for-win
