### ISSUE TITLE
[BUG] ERROR: for database  'ContainerConfig'

### ISSUE THREAD

**Issue by Nefcanto** [docker/compose#11693]
### Description

We create `docker-compose.yml` files dynamically and then use them to load containers. For the first time there is no problem. But when the container already exists, we get this error:

```
Creating MariaDB container
Recreating MenuTimeDatabases ... 
Recreating MenuTimeAdminer   ... 

ERROR: for MenuTimeAdminer  'ContainerConfig'

ERROR: for MenuTimeDatabases  'ContainerConfig'

ERROR: for adminer  'ContainerConfig'

ERROR: for database  'ContainerConfig'
Traceback (most recent call last):
  File "docker-compose", line 3, in <module>
  File "compose/cli/main.py", line 81, in main
  File "compose/cli/main.py", line 203, in perform_command
  File "compose/metrics/decorator.py", line 18, in wrapper
  File "compose/cli/main.py", line 1186, in up
  File "compose/cli/main.py", line 1182, in up
  File "compose/project.py", line 702, in up
  File "compose/parallel.py", line 108, in parallel_execute
  File "compose/parallel.py", line 206, in producer
  File "compose/project.py", line 688, in do
  File "compose/service.py", line 581, in execute_convergence_plan
  File "compose/service.py", line 503, in _execute_convergence_recreate
  File "compose/parallel.py", line 108, in parallel_execute
  File "compose/parallel.py", line 206, in producer
  File "compose/service.py", line 496, in recreate
  File "compose/service.py", line 615, in recreate_container
  File "compose/service.py", line 334, in create_container
  File "compose/service.py", line 922, in _get_container_create_options
  File "compose/service.py", line 962, in _build_container_volume_options
  File "compose/service.py", line 1549, in merge_volume_bindings
  File "compose/service.py", line 1579, in get_container_data_volumes
KeyError: 'ContainerConfig'
[152892] Failed to execute script docker-compose
```

### Compose Version

```Text
Docker Compose version v2.25.0

---------

docker-compose version 1.29.2, build 5becea4c
docker-py version: 5.0.0
CPython version: 3.7.10
OpenSSL version: OpenSSL 1.1.0l  10 Sep 2019
```

### Docker Environment

```Text
Client: Docker Engine - Community
 Version:    26.0.0
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.13.1
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.25.0
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 7
  Running: 5
  Paused: 0
  Stopped: 2
 Images: 7
 Server Version: 26.0.0
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: runc io.containerd.runc.v2
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: ae07eda36dd25f8a1b98dfbf587313b99c0190bb
 runc version: v1.1.12-0-g51d5e94
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 6.5.0-26-generic
 Operating System: Ubuntu 22.04.4 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 15.49GiB
 Name: local
 ID: e7f63485-b5dc-461b-a82b-a0c3535c13b3
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

### Anything else?

This is the generated `docker-compose.yml`:

```
version: "3.9"
services:
    database:
        image: mariadb:latest
        container_name: MenuTimeDatabases
        hostname: database
        volumes:
            - /HolismHolding/Infra:/HolismHolding/Infra
            - /Temp/MenuTime/Databases:/var/lib/mysql
        environment:
            - MARIADB_ROOT_PASSWORD=somepass
        ports:
            - 43543:3306
        logging:
            driver: none
        # restart: always
        networks:
            - MenuTimeNetwork
    # database:
    #     image: postgres:latest
    #     container_name: MenuTimeDatabases
    #     hostname: database
    #     volumes:
    #         - /HolismHolding/Infra:/HolismHolding/Infra
    #         - /Temp/MenuTime/Databases/Data:/data/postgres
    #     environment:
    #         - POSTGRES_USER=someuser
    #         - POSTGRES_PASSWORD=somepass
    #         - PGDATA=/data/postgres
    #     ports:
    #         - 43543:5432
    #     logging:
    #         driver: none
    #     # restart: always
    #     networks:
    #         - MenuTimeNetwork
    adminer:
        image: adminer
        container_name: MenuTimeAdminer
        # restart: always
        logging:
            driver: none
        ports:
            - 55631:8080
        environment:
            - ADMINER_DEFAULT_SERVER=database
            # - ADMINER_DEFAULT_USER=root
            # - ADMINER_DEFAULT_PASSWORD=somepass
            # - ADMINER_DEFAULT_TYPE=postgres
        networks:
            - MenuTimeNetwork
    # pma:
    #     image: phpmyadmin
    #     container_name: MenuTimePma
    #     restart: always
    #     logging:
    #         driver: none
    #     ports:
    #         - 49987:80
    #     environment:
    #         - PMA_HOST=database
    #     networks:
    #         - MenuTimeNetwork
networks:
    MenuTimeNetwork:
        name: MenuTimeNetwork
        driver: bridge

```

**Comment by ndeloof** [comment]
You're using legacy Docker Compose v1 ("1.29.2" python codebase) which is End of Life.
Double check your PATH and/or update your script to run `docker compose` (with space) command

**Comment by mviniciusca** [comment]
> You're using legacy Docker Compose v1 ("1.29.2" python codebase) which is End of Life. Double check your PATH and/or update your script to run `docker compose` (with space) command

thank you so much bro! this docker           (oh yeah, this f* space)                compose helps me a lot ahahahah
