### ISSUE TITLE
panic: interface conversion: interface {} is map[string]interface {}, not string

### ISSUE THREAD

**Issue by shuther** [docker/compose#11754]
### Description

docker compose down is failing with the error below (it is possible I have an issue with the docker compose file but I would not expect a panic error)

```
panic: interface conversion: interface {} is map[string]interface {}, not string

goroutine 1 [running]:
github.com/compose-spec/compose-go/v2/override.keyValueIndexer({0x1eb2360?, 0xc0005aa900?}, {0xc000529d20?, 0x1?})
	github.com/compose-spec/compose-go/v2@v2.0.0-rc.7/override/uncity.go:111 +0x79
github.com/compose-spec/compose-go/v2/override.enforceUnicity({0x1d705c0?, 0xc000010fc0?}, {0xc0006204c0, 0x1c})
	github.com/compose-spec/compose-go/v2@v2.0.0-rc.7/override/uncity.go:92 +0x415
github.com/compose-spec/compose-go/v2/override.enforceUnicity({0x1eb2360?, 0xc0005a8420?}, {0xc000529d00, 0x10})
	github.com/compose-spec/compose-go/v2@v2.0.0-rc.7/override/uncity.go:79 +0x1b3
github.com/compose-spec/compose-go/v2/override.enforceUnicity({0x1eb2360?, 0xc000516fc0?}, {0x2268cdb, 0x8})
	github.com/compose-spec/compose-go/v2@v2.0.0-rc.7/override/uncity.go:79 +0x1b3
github.com/compose-spec/compose-go/v2/override.enforceUnicity({0x1eb2360?, 0xc0003a9d40?}, {0x0, 0x0})
	github.com/compose-spec/compose-go/v2@v2.0.0-rc.7/override/uncity.go:79 +0x1b3
github.com/compose-spec/compose-go/v2/override.EnforceUnicity(0x0?)
	github.com/compose-spec/compose-go/v2@v2.0.0-rc.7/override/uncity.go:68 +0x46
github.com/compose-spec/compose-go/v2/loader.loadYamlModel.func1({0x1eb2360?, 0xc0002bb500?}, {0xc00058e2b8, 0x1, 0x1})
	github.com/compose-spec/compose-go/v2@v2.0.0-rc.7/loader/loader.go:385 +0x3e5
github.com/compose-spec/compose-go/v2/loader.loadYamlModel({0x25d8880?, 0xc0000c6730}, {{0x0, 0x0}, {0xc000125580, 0x2a}, {0xc0005436b0, 0x1, 0x1}, 0xc000543410}, ...)
	github.com/compose-spec/compose-go/v2@v2.0.0-rc.7/loader/loader.go:412 +0x8ff
github.com/compose-spec/compose-go/v2/loader.load({0x25d8880, 0xc0000c6730}, {{0x0, 0x0}, {0xc000125580, 0x2a}, {0xc0005436b0, 0x1, 0x1}, 0xc000543410}, ...)
	github.com/compose-spec/compose-go/v2@v2.0.0-rc.7/loader/loader.go:471 +0x38e
github.com/compose-spec/compose-go/v2/loader.LoadWithContext({0x25d8880, 0xc0000c6730}, {{0x0, 0x0}, {0xc000125580, 0x2a}, {0xc0005436b0, 0x1, 0x1}, 0xc000543410}, ...)
	github.com/compose-spec/compose-go/v2@v2.0.0-rc.7/loader/loader.go:322 +0x46f
github.com/compose-spec/compose-go/v2/cli.ProjectFromOptions(0xc0003ac1e0)
	github.com/compose-spec/compose-go/v2@v2.0.0-rc.7/cli/options.go:458 +0x612
github.com/docker/compose/v2/cmd/compose.(*ProjectOptions).ToProject(0xc0005d20a0, {0x25d8880?, 0xc0000c6730}, {0x25eb940, 0xc0001fb200}, {0xc000496aa0, 0x0, 0x1}, {0xc00058f6d0, 0x1, ...})
	github.com/docker/compose/v2/cmd/compose/compose.go:246 +0x608
github.com/docker/compose/v2/cmd/compose.(*ProjectOptions).projectOrName(0x40768b?, {0x25d8880?, 0xc0000c6730?}, {0x25eb940?, 0xc0001fb200?}, {0xc000496aa0?, 0xc00058f7d0?, 0x4185e8?})
	github.com/docker/compose/v2/cmd/compose/compose.go:173 +0x87
github.com/docker/compose/v2/cmd/compose.runDown({0x25d8880, 0xc0000c6730}, {0x25eb940?, 0xc0001fb200}, {0x25f4280, 0xc000485170}, {0xc0005d20a0, 0x1, 0x0, 0x0, ...}, ...)
	github.com/docker/compose/v2/cmd/compose/down.go:81 +0x95
github.com/docker/compose/v2/cmd/compose.downCommand.func2({0x25d8880?, 0xc0000c6730?}, {0xc000496aa0?, 0xc0000061a0?, 0x1c4e7f9?})
	github.com/docker/compose/v2/cmd/compose/down.go:60 +0x73
github.com/docker/compose/v2/cmd/compose.downCommand.Adapt.func5({0x25d8880?, 0xc0000c6730?}, 0x2?, {0xc000496aa0?, 0x0?, 0x0?})
	github.com/docker/compose/v2/cmd/compose/compose.go:109 +0x30
github.com/docker/compose/v2/cmd/compose.downCommand.Adapt.AdaptCmd.func7(0x0?, {0xc000496aa0, 0x0, 0x1})
	github.com/docker/compose/v2/cmd/compose/compose.go:88 +0x14e
github.com/docker/compose/v2/cmd/cmdtrace.Setup.wrapRunE.func2(0xc0001fa100?, {0xc000496aa0?, 0x0?, 0x1?})
	github.com/docker/compose/v2/cmd/cmdtrace/cmd_span.go:84 +0x65
github.com/spf13/cobra.(*Command).execute(0xc000564000, {0xc0005426b0, 0x1, 0x1})
	github.com/spf13/cobra@v1.8.0/command.go:983 +0xabc
github.com/spf13/cobra.(*Command).ExecuteC(0xc0002ef800)
	github.com/spf13/cobra@v1.8.0/command.go:1115 +0x3ff
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.8.0/command.go:1039
github.com/docker/cli/cli-plugins/plugin.RunPlugin(0x1c6fc33?, 0xc000004300, {{0x2263e7b, 0x5}, {0x226d9e6, 0xb}, {0x25af8d0, 0x7}, {0x0, 0x0}, ...})
	github.com/docker/cli@v25.0.3+incompatible/cli-plugins/plugin/plugin.go:64 +0x10e
github.com/docker/cli/cli-plugins/plugin.Run(0x239ff80, {{0x2263e7b, 0x5}, {0x226d9e6, 0xb}, {0x25af8d0, 0x7}, {0x0, 0x0}, {0x0, ...}})
	github.com/docker/cli@v25.0.3+incompatible/cli-plugins/plugin/plugin.go:77 +0xe5
main.pluginMain()
	github.com/docker/compose/v2/cmd/main.go:37 +0xa5
main.main()
	github.com/docker/compose/v2/cmd/main.go:94 +0x19c
```

### Steps To Reproduce

docker-compose.yaml file:

```
version: '3.9'

#see: https://github.com/seaweedfs/seaweedfs/blob/master/docker/seaweedfs-compose.yml
# docker compose exec master sh
# curl not present
#      test: [ "CMD", "curl", "--fail", "-I", "http://localhost:9333/cluster/healthz" ]
# replaced by
#      test: wget --no-verbose --tries=1 --spider http://localhost:9333/cluster/healthz || exit 1

networks:
  external_network:
    internal: false
#    driver: bridge
#    external: true
  internal_network:
    internal: true
  watch_network:
    internal: true

services:

  master:
    image: chrislusf/seaweedfs # use a remote image
    ports:
      - 9333:9333
# no need to share metrics to the host
      - 19333:19333 # for grpc/hearthbeet?

# For metrics
#      - 9324:9324
# https://github.com/seaweedfs/seaweedfs/wiki/Environment-Variables
# olumeSizeLimitMB, volumePreallocate, mdir, dir, and max have to be set in the command line
#mdir: metadata
    container_name: seaweedfs_master
    command: "master -ip=master -metricsPort=9324 -ip.bind=0.0.0.0 -mdir=/data --volumePreallocate=false -volumeSizeLimitMB=2048 -garbageThreshold=0.01"
# extra commands TBC: -v=1
#    environment:
#      - IP_BIND=0.0.0.0
    volumes:
      - ./mmdata:/data
      - ./master.toml:/etc/seaweedfs/master.toml
      - ./security.toml:/etc/seaweedfs/security.toml
      - ./shell.toml:/etc/seaweedfs/shell.toml
#      - ./certs:/etc/seaweedfs/certs
#      - ./tls:/etc/seaweedfs/tls
    networks:
      - internal_network
# for testing (port 9333)
      - external_network
    healthcheck:
#      test: [ "CMD", "curl", "--fail", "-I", "http://localhost:9333/cluster/healthz" ]
      test: wget --no-verbose --tries=1 --spider http://localhost:9333/cluster/healthz || exit 1
      interval: 5s
      timeout: 60s
      start_period: 1m
      retries: 20
    restart: always

  volume1:
    image: chrislusf/seaweedfs # use a remote image
    container_name: seaweedfs_vol1
#    ports:
#      - 8080:8080
#      - 18080:18080
# For metrics
#      - 9325:9325
# see: https://github.com/seaweedfs/seaweedfs/wiki/Production-Setup
# -logtostderr=true for logs
# 50000 -> 50G
# not clear if the disk sdd is supported (https://www.365chnews.net/?_=%2Fseaweedfs%2Fseaweedfs%2Fissues%2F5328%23KJWqMdlUlBnsIvkdRR%2BuhIT4)
    command: 'volume -mserver="master:9333"  -metricsPort=9325 -dataCenter=DefaultDataCenter -rack=DefaultRack -disk hdd -index leveldb'
#     command: 'volume -mserver="master:9333" -ip.bind=0.0.0.0 -port=8080  -metricsPort=9325 -dir=/data -dataCenter=DefaultDataCenter -rack=DefaultRack -disk hdd>
# extra commands: -v=1 -preStopSeconds=1 -idleTimeout=30
# idleTimeout is to manage long network delay for large files
    environment:
      - IP_BIND: 0.0.0.0
      - MDIR: /data # need to confirm if it is dir or mdir
      - PORT: 8080
      - MAX: 0
      - VOLUMEPREALLOCATE: false
    depends_on:
      master:
        condition: service_healthy
    volumes:
      - ./vmdata1:/data
#       - ./tls:/etc/seaweedfs/tls 
    networks:
      - internal_network
    healthcheck:
#      test: [ "CMD", "curl", "--fail", "-I", "http://localhost:8080/healthz" ]
      test: wget --no-verbose --tries=1 --spider http://localhost:8080/healthz || exit 1
      interval: 3s
      timeout: 60s
      start_period: 20s
    restart: always

  volume2:
    image: chrislusf/seaweedfs # use a remote image
    container_name: seaweedfs_vol2
#    ports:
#      - 8080:8080
#      - 18080:18080
# For metrics
#      - 9329:9329
# see: https://github.com/seaweedfs/seaweedfs/wiki/Production-Setup
# -logtostderr=true for logs
# 50000 -> 50G
    command: 'volume -mserver="master:9333" -ip.bind=0.0.0.0 -port=8080  -metricsPort=9329 -dir=/data -dataCenter=DefaultDataCenter -rack=DefaultRack -disk hdd -max 50000 -index leveldb'
#    environment:
#
    depends_on:
      master:
        condition: service_healthy
    volumes:
      - ./vmdata2:/data
    networks:
      - internal_network
    healthcheck:
#      test: [ "CMD", "curl", "--fail", "-I", "http://localhost:8080/healthz" ]
      test: wget --no-verbose --tries=1 --spider http://localhost:8080/healthz || exit 1
      interval: 3s
      timeout: 60s
      start_period: 22s
    restart: always

  filer:
    image: chrislusf/seaweedfs # use a remote image
#    ports:
#      - 8888:8888
#      - 18888:18888
# For metrics
#      - 9326:9326
# -dataCenter=dc1 -rack=rack1 - for 1st volume
# see: https://github.com/seaweedfs/seaweedfs/wiki/Production-Setup
    command: 'filer -master="master:9333" -ip.bind=0.0.0.0 -metricsPort=9326 -disk hdd -maxMB=100'
# extra commands:  -iam -iam.ip=filer
    tty: true
    stdin_open: true
#    volumes:
#      - ./tls:/etc/seaweedfs/tls
#      - ./fdata:/data
    depends_on:
      master:
        condition: service_healthy
# at least one service should be up
      volume1:
        condition: service_healthy
      volume2:
#        condition: service_started
        condition: service_healthy
    networks:
      - internal_network
# for testing (port 8888)
      - external_network
    healthcheck:
#      test: [ "CMD", "curl", "--fail", "-I", "http://localhost:8888" ]
      test: wget --no-verbose --tries=1 --spider http://localhost:8888 || exit 1
      interval: 5s
      timeout: 30s
    restart: always

  s3:
    image: chrislusf/seaweedfs # use a remote image
    ports:
      - 8333:8333
# For metrics
#      - 9327:9327
    command: 's3 -filer="filer:8888" -ip.bind=0.0.0.0 -metricsPort=9327 -allowEmptyFolder false -allowDeleteBucketNotEmpty false -config=/etc/seaweedfs/s3.json'
# extra commands: -v=4
    depends_on:
      master:
        condition: service_healthy
      volume1:
        condition: service_healthy
      volume2:
        condition: service_healthy
#        condition: service_started
      filer:
        condition: service_healthy
    networks:
      - internal_network
# for testing (port 8333)
# be carefull as no permission
      - external_network
    volumes:
      - ./s3.json:/etc/seaweedfs/s3.json
    restart: always

  webdav:
    image: chrislusf/seaweedfs # use a remote image
    ports:
      - 7333:7333
# For metrics
#      - 9328:9328
#not working -webdav.disk ssd
# not supported -metricsPort=9328 -logtostderr
# -v=4 for extra logs
    command: 'webdav -filer="filer:8888" -maxMB=100'
    depends_on:
      master:
        condition: service_healthy
      volume1:
#        condition: service_healthy
        condition: service_started
      volume2:
#        condition: service_healthy
        condition: service_started
      filer:
        condition: service_healthy
#        condition: service_started
    networks:
      - internal_network
# for testing (port 7333), but needed for Kopia
      - external_network
    restart: always

  prometheus:
    image: prom/prometheus:latest
    ports:
      - 9242:9090
    volumes:
      - ./prometheus:/etc/prometheus
    command: --web.enable-lifecycle  --config.file=/etc/prometheus/prometheus.yml
    depends_on:
      s3:
        condition: service_started
      webdav:
        condition: service_started
    restart: always
    networks:
      - internal_network
      - external_network
    logging:
       driver: none

# https://github.com/containrrr/watchtower/blob/main/docker-compose.yml
  watchtower:
    image: containrrr/watchtower:latest
#    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
#    command: --interval 300
    restart: always
    depends_on:
      prometheus:
        condition: service_started
# port 8080 could be used and is causing issues
    networks:
      - watch_network
    logging:
       driver: none


```

### Compose Version

```Text
docker compose version
Docker Compose version v2.24.6

docker-compose version
Docker Compose version v2.24.6
```

### Docker Environment

```Text
Client: Docker Engine - Community
 Version:    26.0.2
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.14.0
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.24.6
    Path:     /usr/local/lib/docker/cli-plugins/docker-compose

Server:
 Containers: 142
  Running: 44
  Paused: 0
  Stopped: 98
 Images: 249
 Server Version: 26.0.2
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: e377cd56a71523140ca6ae87e30244719194a521
 runc version: v1.1.12-0-g51d5e94
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 5.15.0-105-generic
 Operating System: Ubuntu 22.04.4 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 24.23GiB
 Name: ubuntu-vm
 ID: XT5Z:RCE6:UGTN:DFHA:FGIA:T6JW:DS54:AJRU:EMHT:P4VY:WIUY:TFWH
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Comment by ndeloof** [comment]
> still I am not sure docker should panic

indeed !

**Comment by Kernel-source** [comment]
> I found the problem, I used : instead of = in the env section; still I am not sure docker should panic?

Legend. Thank you
