### ISSUE TITLE
[BUG] panic on empty environment variable

### ISSUE THREAD

**Issue by lovasoa** [docker/compose#11768]
### Description

Running a docker-compose.yaml that contains an empty environment variable declaration results in a panic

### Steps To Reproduce

1. Create the following compose file:

```yaml
services:
  x:
    environment:
      - 
```

2. run `docker compose up`

3. Expected: an error messages mentioning the empty environment variable
3. Actual:

```
docker compose -f bug.yaml up 
panic: interface conversion: interface {} is nil, not string

goroutine 1 [running]:
github.com/compose-spec/compose-go/v2/override.keyValueIndexer({0x0?, 0x0?}, {0xc0002c6caa?, 0x1?})
        github.com/compose-spec/compose-go/v2@v2.0.0-rc.7/override/uncity.go:111 +0x79
github.com/compose-spec/compose-go/v2/override.enforceUnicity({0x1db7960, 0xc0004d22e8}, {0xc00018cc60, 0x16})
        github.com/compose-spec/compose-go/v2@v2.0.0-rc.7/override/uncity.go:92 +0x415
github.com/compose-spec/compose-go/v2/override.enforceUnicity({0x1efbf00?, 0xc000551110}, {0xc0002c6d30, 0xa})
        github.com/compose-spec/compose-go/v2@v2.0.0-rc.7/override/uncity.go:79 +0x1b9
github.com/compose-spec/compose-go/v2/override.enforceUnicity({0x1efbf00?, 0xc0005510e0}, {0x229689c, 0x8})
        github.com/compose-spec/compose-go/v2@v2.0.0-rc.7/override/uncity.go:79 +0x1b9
github.com/compose-spec/compose-go/v2/override.enforceUnicity({0x1efbf00?, 0xc000550e70}, {0x0, 0x0})
        github.com/compose-spec/compose-go/v2@v2.0.0-rc.7/override/uncity.go:79 +0x1b9
github.com/compose-spec/compose-go/v2/override.EnforceUnicity(0xc000550e70)
        github.com/compose-spec/compose-go/v2@v2.0.0-rc.7/override/uncity.go:68 +0x46
github.com/compose-spec/compose-go/v2/loader.loadYamlModel.func1({0x1efbf00?, 0xc000551020?}, {0xc000630490, 0x1, 0x1})
        github.com/compose-spec/compose-go/v2@v2.0.0-rc.7/loader/loader.go:385 +0x3e5
github.com/compose-spec/compose-go/v2/loader.loadYamlModel({0x2613a00, 0xc000414000}, {{0x0, 0x0}, {0xc000060690, 0x45}, {0xc000550360, 0x1, 0x1}, 0xc000894060}, ...)
        github.com/compose-spec/compose-go/v2@v2.0.0-rc.7/loader/loader.go:412 +0x8b8
github.com/compose-spec/compose-go/v2/loader.load({0x2613a00, 0xc000414000}, {{0x0, 0x0}, {0xc000060690, 0x45}, {0xc000550360, 0x1, 0x1}, 0xc000894060}, ...)
        github.com/compose-spec/compose-go/v2@v2.0.0-rc.7/loader/loader.go:471 +0x38e
github.com/compose-spec/compose-go/v2/loader.LoadWithContext({0x2613a00, 0xc000414000}, {{0x0, 0x0}, {0xc000060690, 0x45}, {0xc000550360, 0x1, 0x1}, 0xc000894060}, ...)
        github.com/compose-spec/compose-go/v2@v2.0.0-rc.7/loader/loader.go:322 +0x46f
github.com/compose-spec/compose-go/v2/cli.ProjectFromOptions(0xc00089a000)
        github.com/compose-spec/compose-go/v2@v2.0.0-rc.7/cli/options.go:458 +0x618
github.com/docker/compose/v2/cmd/compose.(*ProjectOptions).ToProject(0xc00037c280, {0x2613a00, 0xc000414000}, {0x2627f20, 0xc000200300}, {0x3820ec0, 0x0, 0x0}, {0xc000631860, 0x2, ...})
        github.com/docker/compose/v2/cmd/compose/compose.go:246 +0x5e8
github.com/docker/compose/v2/cmd/compose.upCommand.(*ProjectOptions).WithServices.func4({0x2613a00, 0xc000414000}, {0x3820ec0, 0x0, 0x0})
        github.com/docker/compose/v2/cmd/compose/compose.go:146 +0xf9
github.com/docker/compose/v2/cmd/compose.upCommand.(*ProjectOptions).WithServices.Adapt.func6({0x2613a00?, 0xc000414000?}, 0x2?, {0x3820ec0?, 0x0?, 0x0?})
        github.com/docker/compose/v2/cmd/compose/compose.go:109 +0x30
github.com/docker/compose/v2/cmd/compose.upCommand.(*ProjectOptions).WithServices.Adapt.AdaptCmd.func7(0xc0000e6908, {0x3820ec0, 0x0, 0x0})
        github.com/docker/compose/v2/cmd/compose/compose.go:88 +0x154
github.com/docker/compose/v2/cmd/cmdtrace.Setup.wrapRunE.func2(0xc0000e6908?, {0x3820ec0?, 0x0?, 0x0?})
        github.com/docker/compose/v2/cmd/cmdtrace/cmd_span.go:84 +0x63
github.com/spf13/cobra.(*Command).execute(0xc0000e6908, {0xc0007098d0, 0x0, 0x0})
        github.com/spf13/cobra@v1.8.0/command.go:983 +0xaca
github.com/spf13/cobra.(*Command).ExecuteC(0xc00054b508)
        github.com/spf13/cobra@v1.8.0/command.go:1115 +0x3ff
github.com/spf13/cobra.(*Command).Execute(...)
        github.com/spf13/cobra@v1.8.0/command.go:1039
github.com/docker/cli/cli-plugins/plugin.RunPlugin(0x1c86dd3?, 0xc0000e6608, {{0x2291946, 0x5}, {0x229b67c, 0xb}, {0x25ee1e0, 0x13}, {0x0, 0x0}, ...})
        github.com/docker/cli@v25.0.3+incompatible/cli-plugins/plugin/plugin.go:64 +0x10e
github.com/docker/cli/cli-plugins/plugin.Run(0x23ced10, {{0x2291946, 0x5}, {0x229b67c, 0xb}, {0x25ee1e0, 0x13}, {0x0, 0x0}, {0x0, ...}})
        github.com/docker/cli@v25.0.3+incompatible/cli-plugins/plugin/plugin.go:77 +0xe5
main.pluginMain()
        github.com/docker/compose/v2/cmd/main.go:37 +0xa5
main.main()
        github.com/docker/compose/v2/cmd/main.go:94 +0x19c
```

### Compose Version

```Text
Docker Compose version 2.24.6+ds1-0ubuntu2
```
```


### Docker Environment

```Text
docker info
Client:
 Version:    24.0.7
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  0.12.1
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  2.24.6+ds1-0ubuntu2
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 17
  Running: 0
  Paused: 0
  Stopped: 17
 Images: 26
 Server Version: 24.0.7
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc io.containerd.runc.v2
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 
 runc version: 
 init version: 
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 6.8.0-22-generic
 Operating System: Ubuntu Noble Numbat (development branch)
 OSType: linux
 Architecture: x86_64
 CPUs: 12
 Total Memory: 15.29GiB
 Name: ophirwork
 ID: ddca1514-574b-4cc2-8d91-aa2ef7bb80f7
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Username: lovasoa
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```
```


### Anything else?

_No response_

**Comment by glours** [comment]
Hello @lovasoa 
Can you upgrade your Compose version please, this bug has been already fixed.

```shell
> docker compose version
Docker Compose version v2.26.1-desktop.1
> docker compose -f compose.yaml up
services.x.environment.[0]: unexpected type <nil>
```
