### ISSUE TITLE
[BUG] `Watch` crashes when sync folders overlap

### ISSUE THREAD

**Issue by korverdev** [docker/compose#11857]
### Description

`docker compose watch` crashes when `sync` actions for multiple containers use the same `path`. This is the config I use for three separate containers which all need access to the same source code.

```
watch:
        - action: sync
          path: ./src
          target: /home/user/adapt/src/
```

### Steps To Reproduce

I haven't been able to consistently reproduce this behavior, but by running `docker compose watch` when the conditions described above are met and working as normally, it will crash basically every day from a full work day. In this example, I hit an error immediately, but that's uncommon. The error only occurs on file sync, so repeatedly changing a file should cause it to happen quickly.

### Compose Version

```Text
Docker Compose version v2.27.0-desktop.2
```

### Docker Environment

```Text
Client:
 Version:    26.1.1
 Context:    desktop-linux
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.14.0-desktop.1
    Path:     /Users/casey/.docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.27.0-desktop.2
    Path:     /Users/casey/.docker/cli-plugins/docker-compose
  debug: Get a shell into any image or container (Docker Inc.)
    Version:  0.0.29
    Path:     /Users/casey/.docker/cli-plugins/docker-debug
  dev: Docker Dev Environments (Docker Inc.)
    Version:  v0.1.2
    Path:     /Users/casey/.docker/cli-plugins/docker-dev
  extension: Manages Docker extensions (Docker Inc.)
    Version:  v0.2.23
    Path:     /Users/casey/.docker/cli-plugins/docker-extension
  feedback: Provide feedback, right in your terminal! (Docker Inc.)
    Version:  v1.0.4
    Path:     /Users/casey/.docker/cli-plugins/docker-feedback
  init: Creates Docker-related starter files for your project (Docker Inc.)
    Version:  v1.1.0
    Path:     /Users/casey/.docker/cli-plugins/docker-init
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc.)
    Version:  0.6.0
    Path:     /Users/casey/.docker/cli-plugins/docker-sbom
  scout: Docker Scout (Docker Inc.)
    Version:  v1.8.0
    Path:     /Users/casey/.docker/cli-plugins/docker-scout

Server:
 Containers: 7
  Running: 1
  Paused: 0
  Stopped: 6
 Images: 32
 Server Version: 26.1.1
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: active
  NodeID: z01yb96pa5zqf6o7x4yx08w95
  Is Manager: true
  ClusterID: qc5k81dhcgdghaais6dgq5jw6
  Managers: 1
  Nodes: 1
  Default Address Pool: 10.0.0.0/8  
  SubnetSize: 24
  Data Path Port: 4789
  Orchestration:
   Task History Retention Limit: 5
  Raft:
   Snapshot Interval: 10000
   Number of Old Snapshots to Retain: 0
   Heartbeat Tick: 1
   Election Tick: 10
  Dispatcher:
   Heartbeat Period: 5 seconds
  CA Configuration:
   Expiry Duration: 3 months
   Force Rotate: 0
  Autolock Managers: false
  Root Rotation In Progress: false
  Node Address: 192.168.65.3
  Manager Addresses:
   192.168.65.3:2377
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: e377cd56a71523140ca6ae87e30244719194a521
 runc version: v1.1.12-0-g51d5e94
 init version: de40ad0
 Security Options:
  seccomp
   Profile: unconfined
  cgroupns
 Kernel Version: 6.6.26-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: aarch64
 CPUs: 8
 Total Memory: 15.6GiB
 Name: docker-desktop
 ID: 605cc3ce-e083-48e9-a7a6-6b99462313bc
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 No Proxy: hubproxy.docker.internal
 Labels:
  com.docker.desktop.address=unix:///Users/casey/Library/Containers/com.docker.docker/Data/docker-cli.sock
 Experimental: false
 Insecure Registries:
  hubproxy.docker.internal:5555
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: daemon is not using the default seccomp profile
```

### Anything else?

The output I got in it's entirety:
```
Watch enabled
Syncing "celery_high_memory" after changes were detected
Syncing "celery_low_memory" after changes were detected
Syncing "server" after changes were detected
fatal error: concurrent map writes

goroutine 2817 [running]:
github.com/docker/compose/v2/pkg/compose.(*composeService).restart(0x40001ad600, {0x218f520?, 0x4000b473b0}, {0x40002600a0, 0x5}, {0x4000fa6c60, 0x0, {0x4000520c30, 0x1, 0x1}, ...})
github.com/docker/compose/v2/pkg/compose/restart.go:62 +0x470
github.com/docker/compose/v2/pkg/compose.(*composeService).Restart.func1({0x218f520, 0x4000b473b0})
github.com/docker/compose/v2/pkg/compose/restart.go:33 +0x74
github.com/docker/compose/v2/pkg/progress.RunWithTitle.func1({0x218f520?, 0x4000b473b0?})
github.com/docker/compose/v2/pkg/progress/writer.go:71 +0x2c
github.com/docker/compose/v2/pkg/progress.RunWithStatus.func2()
github.com/docker/compose/v2/pkg/progress/writer.go:92 +0x7c
golang.org/x/sync/errgroup.(*Group).Go.func1()
golang.org/x/sync@v0.7.0/errgroup/errgroup.go:78 +0x58
created by golang.org/x/sync/errgroup.(*Group).Go in goroutine 2780
golang.org/x/sync@v0.7.0/errgroup/errgroup.go:75 +0x98

goroutine 1 [semacquire]:
sync.runtime_Semacquire(0x40003c58c0?)
runtime/sema.go:62 +0x2c
sync.(*WaitGroup).Wait(0x40004b35c8)
sync/waitgroup.go:116 +0x74
golang.org/x/sync/errgroup.(*Group).Wait(0x40004b35c0)
golang.org/x/sync@v0.7.0/errgroup/errgroup.go:56 +0x2c
github.com/docker/compose/v2/pkg/compose.(*composeService).Watch(0x40001ad600, {0x218f558, 0x40003ec050}, 0x40005e0fc0, {0x3391e00, 0x0, 0x0}, {0x400043ca80?, {0x218f2d8?, 0x4000ae3800?}})
github.com/docker/compose/v2/pkg/compose/watch.go:183 +0x348
github.com/docker/compose/v2/cmd/compose.runWatch({0x218f558?, 0x40003ec050}, {0x21a4d58, 0x400031f900}, {0x21aa210, 0x40001ad600}, {0x4000401a40?, 0xb0?}, {0x4000401a40, 0x0, ...}, ...)
github.com/docker/compose/v2/cmd/compose/watch.go:118 +0x45c
github.com/docker/compose/v2/cmd/compose.watchCommand.func2({0x218f558, 0x40003ec050}, 0x2?, {0x3391e00, 0x0, 0x0})
github.com/docker/compose/v2/cmd/compose/watch.go:55 +0x120
github.com/docker/compose/v2/cmd/compose.watchCommand.AdaptCmd.func4(0x0?, {0x3391e00, 0x0, 0x0})
github.com/docker/compose/v2/cmd/compose/compose.go:100 +0x114
github.com/docker/compose/v2/cmd/cmdtrace.Setup.wrapRunE.func2(0x40001e6500?, {0x3391e00?, 0x0?, 0x0?})
github.com/docker/compose/v2/cmd/cmdtrace/cmd_span.go:84 +0x58
github.com/spf13/cobra.(*Command).execute(0x400068f800, {0x40003d8bd0, 0x0, 0x0})
github.com/spf13/cobra@v1.8.0/command.go:983 +0x840
github.com/spf13/cobra.(*Command).ExecuteC(0x4000692600)
github.com/spf13/cobra@v1.8.0/command.go:1115 +0x344
github.com/spf13/cobra.(*Command).Execute(...)
github.com/spf13/cobra@v1.8.0/command.go:1039
github.com/docker/cli/cli-plugins/plugin.RunPlugin(0x21a4d58?, 0x4000189500, {{0x1df5775, 0x5}, {0x1dff6de, 0xb}, {0x2164ad8, 0x8}, {0x0, 0x0}, ...})
github.com/docker/cli@v26.1.0+incompatible/cli-plugins/plugin/plugin.go:66 +0x124
github.com/docker/cli/cli-plugins/plugin.Run(0x1f42998, {{0x1df5775, 0x5}, {0x1dff6de, 0xb}, {0x2164ad8, 0x8}, {0x0, 0x0}, {0x0, ...}})
github.com/docker/cli@v26.1.0+incompatible/cli-plugins/plugin/plugin.go:81 +0x160
main.pluginMain()
github.com/docker/compose/v2/cmd/main.go:38 +0x98
main.main()
github.com/docker/compose/v2/cmd/main.go:98 +0x1a4

goroutine 9 [IO wait]:
internal/poll.runtime_pollWait(0xffff74853e58, 0x72)
runtime/netpoll.go:343 +0xa0
internal/poll.(*pollDesc).wait(0x40000d6500?, 0x4000497fb7?, 0x0)
internal/poll/fd_poll_runtime.go:84 +0x28
internal/poll.(*pollDesc).waitRead(...)
internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).Read(0x40000d6500, {0x4000497fb7, 0x1, 0x1})
internal/poll/fd_unix.go:164 +0x200
net.(*netFD).Read(0x40000d6500, {0x4000497fb7?, 0x0?, 0x0?})
net/fd_posix.go:55 +0x28
net.(*conn).Read(0x40000923b8, {0x4000497fb7?, 0x0?, 0x0?})
net/net.go:179 +0x34
github.com/docker/cli/cli-plugins/socket.ConnectAndWait.func1()
github.com/docker/cli@v26.1.0+incompatible/cli-plugins/socket/socket.go:151 +0x48
created by github.com/docker/cli/cli-plugins/socket.ConnectAndWait in goroutine 1
github.com/docker/cli@v26.1.0+incompatible/cli-plugins/socket/socket.go:148 +0xf8

goroutine 50 [syscall]:
os/signal.signal_recv()
runtime/sigqueue.go:152 +0x30
os/signal.loop()
os/signal/signal_unix.go:23 +0x1c
created by os/signal.Notify.func1.1 in goroutine 1
os/signal/signal.go:151 +0x28

goroutine 22 [chan receive]:
github.com/docker/compose/v2/cmd/compose.watchCommand.Adapt.AdaptCmd.func6.1()
github.com/docker/compose/v2/cmd/compose/compose.go:94 +0x30
created by github.com/docker/compose/v2/cmd/compose.watchCommand.Adapt.AdaptCmd.func6 in goroutine 1
github.com/docker/compose/v2/cmd/compose/compose.go:93 +0xec

goroutine 23 [chan receive]:
github.com/docker/compose/v2/cmd/compose.watchCommand.AdaptCmd.func4.1()
github.com/docker/compose/v2/cmd/compose/compose.go:94 +0x30
created by github.com/docker/compose/v2/cmd/compose.watchCommand.AdaptCmd.func4 in goroutine 1
github.com/docker/compose/v2/cmd/compose/compose.go:93 +0xec

goroutine 2762 [syscall]:
syscall.Syscall6(0x40012e3b48?, 0x5fbc8?, 0x40012e3b18?, 0x5f260?, 0x48?, 0x400095e780?, 0x40012e3b18?)
syscall/syscall_linux.go:91 +0x2c
golang.org/x/sys/unix.EpollWait(0x0?, {0x40012e3bd0?, 0x0?, 0x2?}, 0x40012e3c28?)
golang.org/x/sys@v0.19.0/unix/zsyscall_linux_arm64.go:55 +0x4c
github.com/tilt-dev/fsnotify.(*fdPoller).wait(0x40003650e0)
github.com/tilt-dev/fsnotify@v1.4.8-0.20220602155310-fff9c274a375/inotify_poller.go:86 +0x5c
github.com/tilt-dev/fsnotify.(*Watcher).readEvents(0x4000ab1ae0)
github.com/tilt-dev/fsnotify@v1.4.8-0.20220602155310-fff9c274a375/inotify.go:213 +0x250
created by github.com/tilt-dev/fsnotify.NewWatcher in goroutine 1
github.com/tilt-dev/fsnotify@v1.4.8-0.20220602155310-fff9c274a375/inotify.go:60 +0x174

goroutine 2763 [chan receive]:
github.com/docker/compose/v2/pkg/watch.(*naiveNotify).loop(0x4000ab1b30)
github.com/docker/compose/v2/pkg/watch/watcher_naive.go:162 +0x78
created by github.com/docker/compose/v2/pkg/watch.(*naiveNotify).Start in goroutine 1
github.com/docker/compose/v2/pkg/watch/watcher_naive.go:102 +0x414

goroutine 2797 [syscall]:
syscall.Syscall6(0x40008dbb48?, 0x5fbc8?, 0x40008dbb18?, 0x5f260?, 0x48?, 0x4000a11220?, 0x40008dbb18?)
syscall/syscall_linux.go:91 +0x2c
golang.org/x/sys/unix.EpollWait(0x0?, {0x40008dbbd0?, 0x0?, 0x2?}, 0x40008dbc28?)
golang.org/x/sys@v0.19.0/unix/zsyscall_linux_arm64.go:55 +0x4c
github.com/tilt-dev/fsnotify.(*fdPoller).wait(0x4000a36020)
github.com/tilt-dev/fsnotify@v1.4.8-0.20220602155310-fff9c274a375/inotify_poller.go:86 +0x5c
github.com/tilt-dev/fsnotify.(*Watcher).readEvents(0x40008a2cd0)
github.com/tilt-dev/fsnotify@v1.4.8-0.20220602155310-fff9c274a375/inotify.go:213 +0x250
created by github.com/tilt-dev/fsnotify.NewWatcher in goroutine 1
github.com/tilt-dev/fsnotify@v1.4.8-0.20220602155310-fff9c274a375/inotify.go:60 +0x174

goroutine 2799 [select]:
github.com/docker/compose/v2/pkg/compose.(*composeService).watch(0x40001ad600, {0x218f558?, 0x4000ab1a90?}, 0x4000fa6c60, {0x4000260bd6, 0x6}, {0x400043ca80?, {0x218f2d8?, 0x4000ae3800?}}, {0x218fa60, ...}, ...)
github.com/docker/compose/v2/pkg/compose/watch.go:221 +0x39c
github.com/docker/compose/v2/pkg/compose.(*composeService).Watch.func1()
github.com/docker/compose/v2/pkg/compose/watch.go:175 +0xac
golang.org/x/sync/errgroup.(*Group).Go.func1()
golang.org/x/sync@v0.7.0/errgroup/errgroup.go:78 +0x58
created by golang.org/x/sync/errgroup.(*Group).Go in goroutine 1
golang.org/x/sync@v0.7.0/errgroup/errgroup.go:75 +0x98

goroutine 2764 [select]:
github.com/docker/compose/v2/pkg/compose.(*composeService).watch(0x40001ad600, {0x218f558?, 0x4000ab1a90?}, 0x4000fa6c60, {0x40001584e0, 0x12}, {0x400043ca80?, {0x218f2d8?, 0x4000ae3800?}}, {0x218fa60, ...}, ...)
github.com/docker/compose/v2/pkg/compose/watch.go:221 +0x39c
github.com/docker/compose/v2/pkg/compose.(*composeService).Watch.func1()
github.com/docker/compose/v2/pkg/compose/watch.go:175 +0xac
golang.org/x/sync/errgroup.(*Group).Go.func1()
golang.org/x/sync@v0.7.0/errgroup/errgroup.go:78 +0x58
created by golang.org/x/sync/errgroup.(*Group).Go in goroutine 1
golang.org/x/sync@v0.7.0/errgroup/errgroup.go:75 +0x98

goroutine 345 [select]:
net/http.(*persistConn).writeLoop(0x400099a5a0)
net/http/transport.go:2421 +0x9c
created by net/http.(*Transport).dialConn in goroutine 343
net/http/transport.go:1777 +0x118c

goroutine 2798 [chan receive]:
github.com/docker/compose/v2/pkg/watch.(*naiveNotify).loop(0x40008a2d20)
github.com/docker/compose/v2/pkg/watch/watcher_naive.go:162 +0x78
created by github.com/docker/compose/v2/pkg/watch.(*naiveNotify).Start in goroutine 1
github.com/docker/compose/v2/pkg/watch/watcher_naive.go:102 +0x414

goroutine 72 [IO wait]:
internal/poll.runtime_pollWait(0xffff74853b70, 0x72)
runtime/netpoll.go:343 +0xa0
internal/poll.(*pollDesc).wait(0x40000d6100?, 0x4000326000?, 0x0)
internal/poll/fd_poll_runtime.go:84 +0x28
internal/poll.(*pollDesc).waitRead(...)
internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).Read(0x40000d6100, {0x4000326000, 0x1000, 0x1000})
internal/poll/fd_unix.go:164 +0x200
net.(*netFD).Read(0x40000d6100, {0x4000326000?, 0x0?, 0x0?})
net/fd_posix.go:55 +0x28
net.(*conn).Read(0x400012c310, {0x4000326000?, 0x0?, 0x0?})
net/net.go:179 +0x34
net/http.(*persistConn).Read(0x4000554000, {0x4000326000?, 0x19e00?, 0x40000646c0?})
net/http/transport.go:1954 +0x50
bufio.(*Reader).fill(0x400013e9c0)
bufio/bufio.go:113 +0xf8
bufio.(*Reader).Peek(0x400013e9c0, 0x1)
bufio/bufio.go:151 +0x60
net/http.(*persistConn).readLoop(0x4000554000)
net/http/transport.go:2118 +0x14c
created by net/http.(*Transport).dialConn in goroutine 71
net/http/transport.go:1776 +0x1144

goroutine 73 [select]:
net/http.(*persistConn).writeLoop(0x4000554000)
net/http/transport.go:2421 +0x9c
created by net/http.(*Transport).dialConn in goroutine 71
net/http/transport.go:1777 +0x118c

goroutine 342 [select]:
net/http.(*persistConn).writeLoop(0x400099a240)
net/http/transport.go:2421 +0x9c
created by net/http.(*Transport).dialConn in goroutine 340
net/http/transport.go:1777 +0x118c

goroutine 2782 [semacquire]:
sync.runtime_Semacquire(0x40004c9088?)
runtime/sema.go:62 +0x2c
sync.(*WaitGroup).Wait(0x400006cb48)
sync/waitgroup.go:116 +0x74
golang.org/x/sync/errgroup.(*Group).Wait(0x400006cb40)
golang.org/x/sync@v0.7.0/errgroup/errgroup.go:56 +0x2c
github.com/docker/compose/v2/pkg/progress.RunWithStatus({0x218f558, 0x4000d54000}, 0x4000736690, {0x21690a0, 0x400012c028}, {0x1dfddc0, 0xa})
github.com/docker/compose/v2/pkg/progress/writer.go:99 +0x1bc
github.com/docker/compose/v2/pkg/progress.RunWithTitle({0x218f558, 0x4000d54000}, 0x40000c2280, {0x21690a0, 0x400012c028}, {0x1dfddc0, 0xa})
github.com/docker/compose/v2/pkg/progress/writer.go:70 +0x90
github.com/docker/compose/v2/pkg/compose.(*composeService).Restart(0x40001ad600, {0x218f558, 0x4000d54000}, {0x40002600a0, 0x5}, {0x4000fa6c60, 0x0, {0x4000736680, 0x1, 0x1}, ...})
github.com/docker/compose/v2/pkg/compose/restart.go:32 +0x10c
github.com/docker/compose/v2/pkg/compose.(*composeService).handleWatchBatch(0x4000159470?, {0x218f558, 0x4000d54000}, 0x4000fa6c60, {0x4000159470, 0x11}, {0x400043ca80?, {0x218f2d8?, 0x4000ae3800?}}, {0x400099a000, ...}, ...)
github.com/docker/compose/v2/pkg/compose/watch.go:504 +0x730
github.com/docker/compose/v2/pkg/compose.(*composeService).watch.func1()
github.com/docker/compose/v2/pkg/compose/watch.go:211 +0x23c
created by github.com/docker/compose/v2/pkg/compose.(*composeService).watch in goroutine 2796
github.com/docker/compose/v2/pkg/compose/watch.go:202 +0x324

goroutine 28 [IO wait]:
internal/poll.runtime_pollWait(0xffff74853c68, 0x72)
runtime/netpoll.go:343 +0xa0
internal/poll.(*pollDesc).wait(0x400043d300?, 0x40006a7000?, 0x0)
internal/poll/fd_poll_runtime.go:84 +0x28
internal/poll.(*pollDesc).waitRead(...)
internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).Read(0x400043d300, {0x40006a7000, 0x1000, 0x1000})
internal/poll/fd_unix.go:164 +0x200
net.(*netFD).Read(0x400043d300, {0x40006a7000?, 0x4000395a00?, 0x3?})
net/fd_posix.go:55 +0x28
net.(*conn).Read(0x40007a16b8, {0x40006a7000?, 0x0?, 0x0?})
net/net.go:179 +0x34
net/http.(*persistConn).Read(0x4000554480, {0x40006a7000?, 0x400028cd18?, 0x60580?})
net/http/transport.go:1954 +0x50
bufio.(*Reader).fill(0x4000917d40)
bufio/bufio.go:113 +0xf8
bufio.(*Reader).Peek(0x4000917d40, 0x1)
bufio/bufio.go:151 +0x60
net/http.(*persistConn).readLoop(0x4000554480)
net/http/transport.go:2118 +0x14c
created by net/http.(*Transport).dialConn in goroutine 27
net/http/transport.go:1776 +0x1144

goroutine 29 [select]:
net/http.(*persistConn).writeLoop(0x4000554480)
net/http/transport.go:2421 +0x9c
created by net/http.(*Transport).dialConn in goroutine 27
net/http/transport.go:1777 +0x118c

goroutine 2796 [select]:
github.com/docker/compose/v2/pkg/compose.(*composeService).watch(0x40001ad600, {0x218f558?, 0x4000ab1a90?}, 0x4000fa6c60, {0x4000159470, 0x11}, {0x400043ca80?, {0x218f2d8?, 0x4000ae3800?}}, {0x218fa60, ...}, ...)
github.com/docker/compose/v2/pkg/compose/watch.go:221 +0x39c
github.com/docker/compose/v2/pkg/compose.(*composeService).Watch.func1()
github.com/docker/compose/v2/pkg/compose/watch.go:175 +0xac
golang.org/x/sync/errgroup.(*Group).Go.func1()
golang.org/x/sync@v0.7.0/errgroup/errgroup.go:78 +0x58
created by golang.org/x/sync/errgroup.(*Group).Go in goroutine 1
golang.org/x/sync@v0.7.0/errgroup/errgroup.go:75 +0x98

goroutine 341 [IO wait]:
internal/poll.runtime_pollWait(0xffff748533b0, 0x72)
runtime/netpoll.go:343 +0xa0
internal/poll.(*pollDesc).wait(0x40003e8c80?, 0x400099c000?, 0x0)
internal/poll/fd_poll_runtime.go:84 +0x28
internal/poll.(*pollDesc).waitRead(...)
internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).Read(0x40003e8c80, {0x400099c000, 0x1000, 0x1000})
internal/poll/fd_unix.go:164 +0x200
net.(*netFD).Read(0x40003e8c80, {0x400099c000?, 0x0?, 0x0?})
net/fd_posix.go:55 +0x28
net.(*conn).Read(0x4000594200, {0x400099c000?, 0x0?, 0x0?})
net/net.go:179 +0x34
net/http.(*persistConn).Read(0x400099a240, {0x400099c000?, 0x19e00?, 0x400071b5c0?})
net/http/transport.go:1954 +0x50
bufio.(*Reader).fill(0x40009177a0)
bufio/bufio.go:113 +0xf8
bufio.(*Reader).Peek(0x40009177a0, 0x1)
bufio/bufio.go:151 +0x60
net/http.(*persistConn).readLoop(0x400099a240)
net/http/transport.go:2118 +0x14c
created by net/http.(*Transport).dialConn in goroutine 340
net/http/transport.go:1776 +0x1144

goroutine 2750 [runnable]:
github.com/mitchellh/copystructure.(*walker).Enter(0x400059a820, 0xa?)
github.com/mitchellh/copystructure@v1.2.0/copystructure.go:166 +0x168
github.com/mitchellh/reflectwalk.Walk({0x1d83fe0?, 0x4000fa6c60?}, {0x1d590c0, 0x400059a820})
github.com/mitchellh/reflectwalk@v1.0.2/reflectwalk.go:95 +0xc8
github.com/mitchellh/copystructure.Config.Copy({0x48?, 0x0?, 0x0?}, {0x1d83fe0, 0x4000fa6c60})
github.com/mitchellh/copystructure@v1.2.0/copystructure.go:116 +0x150
github.com/mitchellh/copystructure.Copy(...)
github.com/mitchellh/copystructure@v1.2.0/copystructure.go:36
github.com/compose-spec/compose-go/v2/types.(*Project).deepCopy(0xffff7484dab0?)
github.com/compose-spec/compose-go/v2@v2.1.0/types/project.go:649 +0x38
github.com/compose-spec/compose-go/v2/types.(*Project).WithSelectedServices(0x40008f38e8?, {0x4000736680, 0x1, 0x1}, {0x40008f3848, 0x1, 0x1})
github.com/compose-spec/compose-go/v2@v2.1.0/types/project.go:474 +0x40
github.com/docker/compose/v2/pkg/compose.(*composeService).restart(0x40001ad600, {0x218f520?, 0x4000c826f0}, {0x40002600a0, 0x5}, {0x4000fa6c60, 0x0, {0x4000736680, 0x1, 0x1}, ...})
github.com/docker/compose/v2/pkg/compose/restart.go:69 +0x27c
github.com/docker/compose/v2/pkg/compose.(*composeService).Restart.func1({0x218f520, 0x4000c826f0})
github.com/docker/compose/v2/pkg/compose/restart.go:33 +0x74
github.com/docker/compose/v2/pkg/progress.RunWithTitle.func1({0x218f520?, 0x4000c826f0?})
github.com/docker/compose/v2/pkg/progress/writer.go:71 +0x2c
github.com/docker/compose/v2/pkg/progress.RunWithStatus.func2()
github.com/docker/compose/v2/pkg/progress/writer.go:92 +0x7c
golang.org/x/sync/errgroup.(*Group).Go.func1()
golang.org/x/sync@v0.7.0/errgroup/errgroup.go:78 +0x58
created by golang.org/x/sync/errgroup.(*Group).Go in goroutine 2782
golang.org/x/sync@v0.7.0/errgroup/errgroup.go:75 +0x98

goroutine 344 [IO wait]:
internal/poll.runtime_pollWait(0xffff748535a0, 0x72)
runtime/netpoll.go:343 +0xa0
internal/poll.(*pollDesc).wait(0x40003e8e80?, 0x40009a2000?, 0x0)
internal/poll/fd_poll_runtime.go:84 +0x28
internal/poll.(*pollDesc).waitRead(...)
internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).Read(0x40003e8e80, {0x40009a2000, 0x1000, 0x1000})
internal/poll/fd_unix.go:164 +0x200
net.(*netFD).Read(0x40003e8e80, {0x40009a2000?, 0x0?, 0x0?})
net/fd_posix.go:55 +0x28
net.(*conn).Read(0x4000594220, {0x40009a2000?, 0x0?, 0x0?})
net/net.go:179 +0x34
net/http.(*persistConn).Read(0x400099a5a0, {0x40009a2000?, 0x19e00?, 0x4000565440?})
net/http/transport.go:1954 +0x50
bufio.(*Reader).fill(0x40009a00c0)
bufio/bufio.go:113 +0xf8
bufio.(*Reader).Peek(0x40009a00c0, 0x1)
bufio/bufio.go:151 +0x60
net/http.(*persistConn).readLoop(0x400099a5a0)
net/http/transport.go:2118 +0x14c
created by net/http.(*Transport).dialConn in goroutine 343
net/http/transport.go:1776 +0x1144

goroutine 47 [IO wait]:
internal/poll.runtime_pollWait(0xffff74853a78, 0x72)
runtime/netpoll.go:343 +0xa0
internal/poll.(*pollDesc).wait(0x40003e8500?, 0x400071e000?, 0x0)
internal/poll/fd_poll_runtime.go:84 +0x28
internal/poll.(*pollDesc).waitRead(...)
internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).Read(0x40003e8500, {0x400071e000, 0x1000, 0x1000})
internal/poll/fd_unix.go:164 +0x200
net.(*netFD).Read(0x40003e8500, {0x400071e000?, 0x0?, 0x0?})
net/fd_posix.go:55 +0x28
net.(*conn).Read(0x4000594088, {0x400071e000?, 0x0?, 0x0?})
net/net.go:179 +0x34
net/http.(*persistConn).Read(0x4000754480, {0x400071e000?, 0x19e00?, 0x4000564480?})
net/http/transport.go:1954 +0x50
bufio.(*Reader).fill(0x400080e3c0)
bufio/bufio.go:113 +0xf8
bufio.(*Reader).Peek(0x400080e3c0, 0x1)
bufio/bufio.go:151 +0x60
net/http.(*persistConn).readLoop
```

**Comment by ndeloof** [comment]
Thanks for reporting this with error details
