### ISSUE TITLE
Show a better error when a service doesn't have `build` or `image` set

### ISSUE THREAD

**Issue by aanand** [docker/compose#1224]
Currently you get a stack trace with `KeyError: u'image'`, which isn't very helpful.

Sort-of-related to #129.

**Comment by mchasal** [comment]
I'm working on a fix for this. Should have a PR ready soon.

**Comment by mchasal** [comment]
PR #1293 created with fix and testcase.

**Comment by mchasal** [comment]
PR has been merged, so this can be closed out.

**Comment by funkytaco** [comment]
This is happening to me and I have the latest Docker Toolbox.

docker-compose up -d
Traceback (most recent call last):
  File "<string>", line 3, in <module>
  File "/compose/build/docker-compose/out00-PYZ.pyz/compose.cli.main", line 39, in main
  File "/compose/build/docker-compose/out00-PYZ.pyz/compose.cli.docopt_command", line 21, in sys_dispatch
  File "/compose/build/docker-compose/out00-PYZ.pyz/compose.cli.command", line 27, in dispatch
  File "/compose/build/docker-compose/out00-PYZ.pyz/compose.cli.docopt_command", line 24, in dispatch
  File "/compose/build/docker-compose/out00-PYZ.pyz/compose.cli.command", line 57, in perform_command
  File "/compose/build/docker-compose/out00-PYZ.pyz/compose.cli.command", line 78, in get_project
  File "/compose/build/docker-compose/out00-PYZ.pyz/compose.config", line 142, in load
  File "/compose/build/docker-compose/out00-PYZ.pyz/compose.config", line 166, in make_service_dict
  File "/compose/build/docker-compose/out00-PYZ.pyz/compose.config", line 193, in resolve_extends
KeyError: 'micro-php'


$ docker-compose -v
docker-compose version: 1.4.0


My directory layout:

ls .          
README.md          build_microlith.sh destroy_docker.sh  **docker-compose.yml** microlith

ls microlith/*/*.yml
microlith/micro-php/**docker-compose.yml**    microlith/microlith-mvc/docker-compose.yml


The top level docker-compose.yml extends a YAML file in a sub-directory. When I ran this, I expected it to not work because I knew that I had renamed "php-soa" to "micro-php" in the top-level YAML file (but hadn't modified the child YAML file). I just wasn't sure why, and I figured it out with some testing (the parent key in the YAML file needed to be changed to 'micro-php').

**Comment by dnephin** [comment]
@funkytaco this is fixed in master, and will be in the 1.5.0 release

**Comment by funkytaco** [comment]
@dnephin Thanks.

Is there any way I can see what release a pull request would go out with on Github? I can't tell by looking at https://github.com/funkyfuture/docker-compose/commit/f9bd4278c8a6e993547b502aceabf562f765bf55
