### ISSUE TITLE
Can't run compose on windows

### ISSUE THREAD

**Issue by blizart** [docker/compose#1281]
Hello, I am trying to run compose on Windows, i am instaling it using python package as instructed in installation manual, but after installation when i check docker-compose --version i get followin error:

$ docker-compose --version
Traceback (most recent call last):
  File "C:\Users\Entaro\appdata\local\scoop\apps\python\3.4.3\scripts\docker-compose-script.py", line 9, in <module>
    load_entry_point('docker-compose==1.1.0', 'console_scripts', 'docker-compose')()
  File "C:\Users\Entaro\appdata\local\scoop\apps\python\3.4.3\lib\site-packages\pkg_resources\__init__.py", line 519, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "C:\Users\Entaro\appdata\local\scoop\apps\python\3.4.3\lib\site-packages\pkg_resources\__init__.py", line 2630, in load_entry_point
    return ep.load()
  File "C:\Users\Entaro\appdata\local\scoop\apps\python\3.4.3\lib\site-packages\pkg_resources\__init__.py", line 2310, in load
    return self.resolve()
  File "C:\Users\Entaro\appdata\local\scoop\apps\python\3.4.3\lib\site-packages\pkg_resources\__init__.py", line 2316, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "C:\Users\Entaro\appdata\local\scoop\apps\python\3.4.3\lib\site-packages\compose\__init__.py", line 2, in <module>
    from .service import Service  # noqa:flake8
  File "C:\Users\Entaro\appdata\local\scoop\apps\python\3.4.3\lib\site-packages\compose\service.py", line 485
    except StreamOutputError, e:
                            ^
SyntaxError: invalid syntax

**Comment by thaJeztah** [comment]
This is a known issue, and support for windows is being worked on. See https://github.com/docker/compose/issues/1085

I think this can be closed as a duplicate of https://github.com/docker/compose/issues/1085

**Comment by blizart** [comment]
Thanks for you answer.

**Comment by thaJeztah** [comment]
You're welcome! Unfortunately, no full solution yet
