### ISSUE TITLE
docker-compose run with custom environment variable throw TypeError

### ISSUE THREAD

**Issue by terbooter** [docker/compose#1286]
Docker version 1.5.0, build a8a31ef
docker-compose 1.1.0

```docker-compose run -e ENV_VAR=local web``` throws error
```
Traceback (most recent call last):
  File "<string>", line 3, in <module>
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.cli.main", line 31, in main
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.cli.docopt_command", line 21, in sys_dispatch
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.cli.command", line 27, in dispatch
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.cli.docopt_command", line 24, in dispatch
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.cli.command", line 59, in perform_command
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.cli.main", line 323, in run
TypeError: list indices must be integers, not unicode
```
compose man says that
> Usage: run [options] [-e KEY=VAL...] SERVICE [COMMAND] [ARGS...]
...
-e KEY=VAL            Set an environment variable (can be used multiple times)

**Comment by dnephin** [comment]
This was fixed in #970, it's in the 1.2 release candidates, if you want to try that.
