### ISSUE TITLE
Only load extend file if it exists

### ISSUE THREAD

**Issue by kevinsimper** [docker/compose#1310]
Right now docker compose will just output an unscripted error if the file contains something to extends does not exists:
```
Traceback (most recent call last):
  File "<string>", line 3, in <module>
  File "/compose/build/docker-compose/out00-PYZ.pyz/compose.cli.main", line 31, in main
  File "/compose/build/docker-compose/out00-PYZ.pyz/compose.cli.docopt_command", line 21, in sys_dispatch
  File "/compose/build/docker-compose/out00-PYZ.pyz/compose.cli.command", line 27, in dispatch
  File "/compose/build/docker-compose/out00-PYZ.pyz/compose.cli.docopt_command", line 24, in dispatch
  File "/compose/build/docker-compose/out00-PYZ.pyz/compose.cli.command", line 57, in perform_command
  File "/compose/build/docker-compose/out00-PYZ.pyz/compose.cli.command", line 76, in get_project
  File "/compose/build/docker-compose/out00-PYZ.pyz/compose.config", line 55, in load
  File "/compose/build/docker-compose/out00-PYZ.pyz/compose.config", line 65, in from_dictionary
  File "/compose/build/docker-compose/out00-PYZ.pyz/compose.config", line 88, in make_service_dict
  File "/compose/build/docker-compose/out00-PYZ.pyz/compose.config", line 110, in resolve_extends
TypeError: 'NoneType' object has no attribute '__getitem__'
```

I propose that it should check if the file exists and only include it if it does.

This provide a nice way to override certain values in your own development environment very easy, and that can be gitignore as well, make it convenient to develop with.

**Comment by aanand** [comment]
I'm not seeing this behaviour. Can you provide a reproducible test case?

**Comment by kevinsimper** [comment]
If the file you specify do not exist, it will fail. It is not an error, just thinking on how to use docker-compose with multiple developers, that can have different environments locally.

The file `config/development.yml` would contain enviroment variables, that would config the different application like `$DB_HOST`. I know docker links and that is what most people would use, but sometimes you may want to specify a different `$DB_HOST`.

```
frontend:
  extends:
    file: config/development.yml
    service: common
  build: ./frontend/
```
`config/development.yml` does not exist and would be optional to provide.

**Comment by dnephin** [comment]
I think silently ignoring a file that doesn't exist is not the right behaviour for `extends`. If this is just for environment variables, what about using different variations of `env_file` ?

**Comment by dnephin** [comment]
You can now use `docker-compose.override.yml` to provide optional dev overrides http://docs.docker.com/compose/extends/#multiple-compose-files
