### ISSUE TITLE
docker-compose up fail

### ISSUE THREAD

**Issue by Fangfenghua** [docker/compose#1336]
[root@kolla compose]# docker-compose -f glance-api-registry.yml up -d
Traceback (most recent call last):
  File "/usr/bin/docker-compose", line 9, in <module>
    load_entry_point('docker-compose==1.3.0dev', 'console_scripts', 'docker-compose')()
  File "/opt/dev/compose/compose/cli/main.py", line 31, in main
    command.sys_dispatch()
  File "/opt/dev/compose/compose/cli/docopt_command.py", line 21, in sys_dispatch
    self.dispatch(sys.argv[1:], None)
  File "/opt/dev/compose/compose/cli/command.py", line 27, in dispatch
    super(Command, self).dispatch(*args, **kwargs)
  File "/opt/dev/compose/compose/cli/docopt_command.py", line 24, in dispatch
    self.perform_command(*self.parse(argv, global_options))
  File "/opt/dev/compose/compose/cli/command.py", line 59, in perform_command
    handler(project, command_options)
  File "/opt/dev/compose/compose/cli/main.py", line 467, in up
    do_build=not options['--no-build'],
  File "/opt/dev/compose/compose/project.py", line 208, in up
    do_build=do_build):
  File "/opt/dev/compose/compose/service.py", line 211, in recreate_containers
    containers = self.containers(stopped=True)
  File "/opt/dev/compose/compose/service.py", line 77, in containers
    for container in self.client.containers(all=stopped)
  File "/usr/lib/python2.7/site-packages/docker/client.py", line 423, in containers
    res = self._result(self._get(u, params=params), True)
  File "/usr/lib/python2.7/site-packages/docker/client.py", line 103, in _get
    return self.get(url, **self._set_request_timeout(kwargs))
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 468, in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 456, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 559, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/adapters.py", line 327, in send
    timeout=timeout
  File "/usr/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 532, in urlopen
    timeout_obj = self._get_timeout(timeout)
  File "/usr/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 298, in _get_timeout
    return Timeout.from_float(timeout)
  File "/usr/lib/python2.7/site-packages/requests/packages/urllib3/util/timeout.py", line 152, in from_float
    return Timeout(read=timeout, connect=timeout)
  File "/usr/lib/python2.7/site-packages/requests/packages/urllib3/util/timeout.py", line 95, in __init__
    self._connect = self._validate_timeout(connect, 'connect')
  File "/usr/lib/python2.7/site-packages/requests/packages/urllib3/util/timeout.py", line 125, in _validate_timeout
    "int or float." % (name, value))
ValueError: Timeout value connect was Timeout(connect=60, read=60, total=None), but it must be an int or float.

**Comment by ebuildy** [comment]
Seems same issue than https://github.com/docker/docker-py/issues/377 ?

**Comment by Fangfenghua** [comment]
@ebuildy  i will chect it. tks

**Comment by Fangfenghua** [comment]
ping @ebuildy  it looks like the same problem.But it close, right?I didn't got the solution from the discuss.
Also i found that the compose didn't specify it dependence request? Should we add it?

**Comment by ebuildy** [comment]
Can you post your YML file here?

**Comment by Fangfenghua** [comment]
@ebuildy  i had found the reason. That because i use yum install a pkg that dependence request with different version used by compose.Then cause the problem. After i erase the pkg ,docker-copse worked well.
So i think can we release a official image for docker-compose?

**Comment by Fangfenghua** [comment]
just close the bug.it's not compose problem

**Comment by dminca** [comment]
@Fangfenghua what was that package called? I'm experiencing the same issue atm and I'm curious how to fix it...
Reinstalling `docker-compose` didn't fix it...
