### ISSUE TITLE
Timeout while instantiating large containers

### ISSUE THREAD

**Issue by vidarl** [docker/compose#1365]
Looks like compose will make a timeout error instantiating a  container from a large ( 700Mb ) image

```
Creating swarm_mysite_1...
Traceback (most recent call last):
  File "<string>", line 3, in <module>
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.cli.main", line 31, in main
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.cli.docopt_command", line 21, in sys_dispatch
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.cli.command", line 27, in dispatch
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.cli.docopt_command", line 24, in dispatch
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.cli.command", line 59, in perform_command
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.cli.main", line 464, in up
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.project", line 214, in up
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.service", line 288, in start_or_create_containers
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.service", line 190, in create_container
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.container", line 36, in create
  File "/code/build/docker-compose/out00-PYZ.pyz/docker.client", line 425, in create_container
  File "/code/build/docker-compose/out00-PYZ.pyz/docker.client", line 432, in create_container_from_config
  File "/code/build/docker-compose/out00-PYZ.pyz/docker.client", line 119, in _post_json
  File "/code/build/docker-compose/out00-PYZ.pyz/docker.client", line 79, in _post
  File "/code/build/docker-compose/out00-PYZ.pyz/requests.sessions", line 425, in post
  File "/code/build/docker-compose/out00-PYZ.pyz/requests.sessions", line 383, in request
  File "/code/build/docker-compose/out00-PYZ.pyz/requests.sessions", line 486, in send
  File "/code/build/docker-compose/out00-PYZ.pyz/requests.adapters", line 387, in send
requests.exceptions.Timeout: HTTPConnectionPool(host='swarm1', port=8888): Read timed out. (read timeout=60)
```

```
$ docker images
swarm               latest              96b8c18d1208        11 days ago

$ docker --version
Docker version 1.6.0, build 4749651

$ docker-compose --version
docker-compose 1.2.0
```

**Comment by vidarl** [comment]
A few updates on the matter....

Now tested on Docker 1.6.2, docker-compose 1.3.1 ( without swarm, so swarm is irrelevant ).
It seems like I was a bit mistaken in my initial report.
The problem do not occur when downloading the image, but when instantiating the container. I will update the issue report accordingly.

Also, there is also a "special" characteristic with the image
The image has 700Mb in /data and has declared 'VOLUME [ "/data ]'
Meaning those 700Mb are actually copied from the image to a volume ( so container does not access those files via a layer in the union file system ).
I suspect that it is this copying which takes too long and causes compose to timeout

**Comment by dnephin** [comment]
There are a bunch of these ConnectionTimeout issues, I'm consolidating them all into  #1923.

There isn't much we can do about this from the client, except for adding a more helpful error message.
