### ISSUE TITLE
docker-compose up exception thrown

### ISSUE THREAD

**Issue by BardiaAfshin** [docker/compose#1465]
I'm following the docs on setting up demo docker-compose project.

When I run
```shell
docker-compose up
```

I get the following exception

```log
docker-compose up
Traceback (most recent call last):
  File "<string>", line 3, in <module>
  File "/compose/build/docker-compose/out00-PYZ.pyz/compose.cli.main", line 31, in main
  File "/compose/build/docker-compose/out00-PYZ.pyz/compose.cli.docopt_command", line 21, in sys_dispatch
  File "/compose/build/docker-compose/out00-PYZ.pyz/compose.cli.command", line 27, in dispatch
  File "/compose/build/docker-compose/out00-PYZ.pyz/compose.cli.docopt_command", line 24, in dispatch
  File "/compose/build/docker-compose/out00-PYZ.pyz/compose.cli.command", line 59, in perform_command
  File "/compose/build/docker-compose/out00-PYZ.pyz/compose.cli.main", line 464, in up
  File "/compose/build/docker-compose/out00-PYZ.pyz/compose.project", line 208, in up
  File "/compose/build/docker-compose/out00-PYZ.pyz/compose.service", line 208, in recreate_containers
  File "/compose/build/docker-compose/out00-PYZ.pyz/compose.service", line 74, in containers
  File "/compose/build/docker-compose/out00-PYZ.pyz/docker.client", line 385, in containers
  File "/compose/build/docker-compose/out00-PYZ.pyz/docker.client", line 102, in _result
  File "/compose/build/docker-compose/out00-PYZ.pyz/requests.models", line 741, in json
  File "/compose/build/docker-compose/out00-PYZ.pyz/json", line 338, in loads
  File "/compose/build/docker-compose/out00-PYZ.pyz/json.decoder", line 365, in decode
  File "/compose/build/docker-compose/out00-PYZ.pyz/json.decoder", line 383, in raw_decode
ValueError: No JSON object could be decoded
```

**Comment by dnephin** [comment]
It looks like there was a problem getting the results from the docker daemon.  Is there a proxy between compose and daemon that might be returning an unexpected response?

**Comment by BardiaAfshin** [comment]
no. I'm using boot2docker, when I run

```
boot2docker up
```

it comes back with a set up export statements. I run these export statements before executiong the forementioned commands.

**Comment by justintime4tea** [comment]
Receiving similar set of errors though on Arch linux minimal system, brand new install virtually nothing set up except docker, python and docker-compose and dependencies.

Both errors look similar one claims a byte is being passed instead of string and the other has a string arg without encoding :)

Can provide any command outputs, logs or sys-info.
Will try to take a closer look and see if I can find anything more helpful.

Have another machine Arch Linux docker-compose 1.2 with docker same-build which is running fine.

------------------------------------------------------------------------------
Arch Linux 4.0.4-2 x86_64
Docker version 1.6.2 build 7c8fca2
docker-compose version 1.3.0dev
docker-compose installed via python ./setup.py install
All docker-compose dependencies satisfied/verified.
First attempt was done with docker-compose 1.2 installed via pip install docker-compose, ran into second set of errors, tried dev-build 1.3.0 and first set of errors appeared.

Docker is working though, ran: [ docker run -it dock0/arch ] successfully
------------------------------------------------------------------------------

1.3.0 - stdout:

Building logstash...
Traceback (most recent call last):
  File "/usr/bin/docker-compose", line 9, in <module>
    load_entry_point('docker-compose==1.3.0.dev0', 'console_scripts', 'docker-compose')()
  File "/usr/lib/python3.4/site-packages/docker_compose-1.3.0.dev0-py3.4.egg/compose/cli/main.py", line 31, in main
  File "/usr/lib/python3.4/site-packages/docker_compose-1.3.0.dev0-py3.4.egg/compose/cli/docopt_command.py", line 21, in sys_dispatch
  File "/usr/lib/python3.4/site-packages/docker_compose-1.3.0.dev0-py3.4.egg/compose/cli/command.py", line 34, in dispatch
  File "/usr/lib/python3.4/site-packages/docker_compose-1.3.0.dev0-py3.4.egg/compose/cli/docopt_command.py", line 24, in dispatch
  File "/usr/lib/python3.4/site-packages/docker_compose-1.3.0.dev0-py3.4.egg/compose/cli/command.py", line 66, in perform_command
  File "/usr/lib/python3.4/site-packages/docker_compose-1.3.0.dev0-py3.4.egg/compose/cli/main.py", line 124, in build
  File "/usr/lib/python3.4/site-packages/docker_compose-1.3.0.dev0-py3.4.egg/compose/project.py", line 204, in build
  File "/usr/lib/python3.4/site-packages/docker_compose-1.3.0.dev0-py3.4.egg/compose/service.py", line 639, in build
TypeError: string argument without an encoding

------------------------------------------------------------------------------------------------------

1.2.0 - stdout:

Building logstash...
Traceback (most recent call last):
  File "/usr/local/bin/docker-compose", line 3, in <module>
    main()
  File "/usr/lib/python3.4/site-packages/compose/cli/main.py", line 31, in main
    command.sys_dispatch()
  File "/usr/lib/python3.4/site-packages/compose/cli/docopt_command.py", line 21, in sys_dispatch
    self.dispatch(sys.argv[1:], None)
  File "/usr/lib/python3.4/site-packages/compose/cli/command.py", line 27, in dispatch
    super(Command, self).dispatch(*args, **kwargs)
  File "/usr/lib/python3.4/site-packages/compose/cli/docopt_command.py", line 24, in dispatch
    self.perform_command(*self.parse(argv, global_options))
  File "/usr/lib/python3.4/site-packages/compose/cli/command.py", line 59, in perform_command
    handler(project, command_options)
  File "/usr/lib/python3.4/site-packages/compose/cli/main.py", line 119, in build
    project.build(service_names=options['SERVICE'], no_cache=no_cache)
  File "/usr/lib/python3.4/site-packages/compose/project.py", line 191, in build
    service.build(no_cache)
  File "/usr/lib/python3.4/site-packages/compose/service.py", line 479, in build
    all_events = stream_output(build_output, sys.stdout)
  File "/usr/lib/python3.4/site-packages/compose/progress_stream.py", line 18, in stream_output
    event = json.loads(chunk)
  File "/usr/lib/python3.4/json/__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'bytes'

**Comment by aanand** [comment]
@justintime4tea Looks like a Python 3 problem - we're still not fully compatible.

**Comment by justintime4tea** [comment]
It's working fine under Python3 with docker-compose 1.2 and Docker 1.6.2 on a different machine running Arch so not sure if this is the case. Both versions of python3 (one on machine with working docker-compose, one on machine with non-working docker-compose) are identical so to me it doesn't sound like Python3 issue.

Might have been a recent change somewhere on one of the packages that aren't identical between the two machines that broke something or maybe I've made a mistake.

I'll take an exact copy of working docker-compose (with Py3) over to non-working docker-compose machine and test again. 

If this works I'll see if I can track the differences between the two to narrow down the issue. I've been working with Python3 for a REST back-end service so if it is a Python3 issue I may be able to lend a hand.

Nice work on this project though and thank you kindly for the quick feedback! :)

**Comment by freefood89** [comment]
Hello, I've got similar problems doing ```docker-compose build``` on a ubuntu14.04 with docker compose v1.2.0 docker v1.6.2. I went through and changed the following files locally and was able to deploy my [stupid webapp](/freefood89/Fishtank):

/usr/local/lib/python3.4/dist-packages/compose/progress_stream.py (line 318)
-event = json.loads(chunk)
+event = json.loads(chunk.decode())

/usr/lib/python3.4/codecs.py (line 369)
-self.stream.write(data)
+self.stream.write(data.decode())

/usr/local/lib/python3.4/dist-packages/compose/service.py (line 481)
-raise BuildError(self, unicode(e))
+raise BuildError(self, str(e))

/usr/local/lib/python3.4/dist-packages/compose/cli/utils.py (line 78)
-buffered += data
+buffered += data.decode()

/usr/local/lib/python3.4/dist-packages/compose/cli/utils.py (line 60)
-yield prefix + line
+yield prefix + line.encode()

/usr/local/lib/python3.4/dist-packages/compose/cli/utils.py (line 23)
-self.output.write(line)
+self.output.write(line.decode())

@borikanes maybe we shouldn't use compose yet...

**Comment by justintime4tea** [comment]
If you read the above/previous comments you see Python3 support is still in the works so don't fret! We'll get there eventually. Many many MANY applications/services/processes only work with Python2, its common place. It's a weird phenomena in the Python community but if you write or use many Python applications you'll notice this more. There are environment handlers for Python like there are for Ruby which enable you to install and use multiple versions of Python. Ruby has a similar issue with apps dependant on a specific version of Ruby though in my opinion Ruby version dependency is more fragmented. Python we have just two for the most part, 2 & 3. Sadly Python3 adoption is taking the world a lot longer than Python would like :) Also, everyone has been suggesting to wait to use docker-compose for production since it literally is only slightly older than a newborn. Docker is just barely becoming ready for production itself.

**Comment by dnephin** [comment]
python3 support is in master.  The origin error should have also been fixed a while ago.
