### ISSUE TITLE
unable to run example docker-compose

### ISSUE THREAD

**Issue by ak47** [docker/compose#1485]
When following this example:
https://docs.docker.com/compose/

I consistently get the below error:

```
╰─➤  docker-compose up
Traceback (most recent call last):
  File "<string>", line 3, in <module>
  File "/compose/build/docker-compose/out00-PYZ.pyz/compose.cli.main", line 31, in main
  File "/compose/build/docker-compose/out00-PYZ.pyz/compose.cli.docopt_command", line 21, in sys_dispatch
  File "/compose/build/docker-compose/out00-PYZ.pyz/compose.cli.command", line 27, in dispatch
  File "/compose/build/docker-compose/out00-PYZ.pyz/compose.cli.docopt_command", line 24, in dispatch
  File "/compose/build/docker-compose/out00-PYZ.pyz/compose.cli.command", line 57, in perform_command
  File "/compose/build/docker-compose/out00-PYZ.pyz/compose.cli.command", line 77, in get_project
  File "/compose/build/docker-compose/out00-PYZ.pyz/compose.project", line 69, in from_dicts
  File "/compose/build/docker-compose/out00-PYZ.pyz/compose.project", line 49, in sort_service_dicts
  File "/compose/build/docker-compose/out00-PYZ.pyz/compose.project", line 42, in visit
  File "/compose/build/docker-compose/out00-PYZ.pyz/compose.project", line 27, in get_service_dependents
  File "/compose/build/docker-compose/out00-PYZ.pyz/compose.project", line 21, in get_service_names
TypeError: 'NoneType' object is not utterable
```

I've tried python 3.4.3 & 2.7.10 via pyenv on my MBP
I've installed docker-compose via 'brew cask install' and the 'curl' method shown on docker-compose installation instructions.

here is a dump of my files:
https://gist.github.com/ak47/cfd48c827eea2f18a8c7

I have no more ideas on what I'm doing wrong.  Thanks for any help.

**Comment by dnephin** [comment]
I think there might be something wrong with the yaml config. It seems like the links are coming in as `None`, but from the paste I can't see exactly why that would be. Could you try `links: [redis]` ?

**Comment by ak47** [comment]
```
web:
  build: .
  command: python app.py
  ports:
    - "5000:5000"
  volumes:
    - .:/code
  links: [redis]
redis:
  image: redis
```

same result

```
╰─➤  docker-compose up                                             255 ↵
Traceback (most recent call last):
  File "<string>", line 3, in <module>
  File "/compose/build/docker-compose/out00-PYZ.pyz/compose.cli.main", line 31, in main
  File "/compose/build/docker-compose/out00-PYZ.pyz/compose.cli.docopt_command", line 21, in sys_dispatch
  File "/compose/build/docker-compose/out00-PYZ.pyz/compose.cli.command", line 27, in dispatch
  File "/compose/build/docker-compose/out00-PYZ.pyz/compose.cli.docopt_command", line 24, in dispatch
  File "/compose/build/docker-compose/out00-PYZ.pyz/compose.cli.command", line 57, in perform_command
  File "/compose/build/docker-compose/out00-PYZ.pyz/compose.cli.command", line 77, in get_project
  File "/compose/build/docker-compose/out00-PYZ.pyz/compose.project", line 69, in from_dicts
  File "/compose/build/docker-compose/out00-PYZ.pyz/compose.project", line 49, in sort_service_dicts
  File "/compose/build/docker-compose/out00-PYZ.pyz/compose.project", line 42, in visit
  File "/compose/build/docker-compose/out00-PYZ.pyz/compose.project", line 27, in get_service_dependents
  File "/compose/build/docker-compose/out00-PYZ.pyz/compose.project", line 21, in get_service_names
TypeError: 'NoneType' object is not utterable
```

**Comment by ak47** [comment]
hey, it works!  I carefully removed everything related to docker installed via brew, removed ~/.docker* files/dirs, and then reinstalled via 'brew cask install boot2docker' and then 'docker-compose'

however, there is an error at the end - and I'm unable to hit the "http://0.0.0.0:5000/" via any method

```
╰─➤  docker-compose up
Creating composetest_redis_1...
Pulling image redis:latest...
latest: Pulling from redis
7a3e804ed6c0: Pull complete
b96d1548a24e: Pull complete
5ba9a5b9710f: Pull complete
37f07aacbfe5: Pull complete
ec7f3a6b5dc6: Pull complete
499b313c4d4e: Pull complete
4416945429c6: Pull complete
0daf71066555: Pull complete
1f86439b265d: Pull complete
9e6288fa06c0: Pull complete
3c083702089f: Pull complete
71cc4c7123fc: Pull complete
91e5e3734476: Pull complete
8d7fb9bd09ab: Pull complete
e6b7cf8bf1b1: Pull complete
96182c1bd121: Pull complete
4b7672067154: Already exists
redis:latest: The image you are pulling has been verified. Important: image verification is a tech preview feature and should not be relied on to provide security.
Digest: sha256:01b59520487a9ada4b8e31558c0580930a4e5f2a565a1cb85b66efe7c6ce810d
Status: Downloaded newer image for redis:latest
Creating composetest_web_1...
Building web...
Step 0 : FROM python:2.7
2.7: Pulling from python
39bb80489af7: Pull complete
df2a0347c9d0: Pull complete
7a3871ba15f8: Pull complete
a2703ed272d7: Pull complete
c9e3effdd23a: Pull complete
24b3549417de: Pull complete
3009dde7a8a5: Pull complete
9da97b9166df: Pull complete
a80d186674da: Pull complete
fe7091222d5c: Pull complete
29d755a35726: Pull complete
1452a2aa19dd: Pull complete
9fa21a3e9f2f: Already exists
python:2.7: The image you are pulling has been verified. Important: image verification is a tech preview feature and should not be relied on to provide security.
Digest: sha256:f9ac8551d91f27ba63ac6ac7362c2ebc0026d84f602f70d9e55bd58468dd9fb6
Status: Downloaded newer image for python:2.7
 ---> 9fa21a3e9f2f
Step 1 : ADD . /code
 ---> 5033f8ed5f70
Removing intermediate container 6569be452d90
Step 2 : WORKDIR /code
 ---> Running in 83c4fc5747e9
 ---> 10e6c3081458
Removing intermediate container 83c4fc5747e9
Step 3 : RUN pip install -r requirements.txt
 ---> Running in dc537e172768
Collecting flask (from -r requirements.txt (line 1))
  Downloading Flask-0.10.1.tar.gz (544kB)
Collecting redis (from -r requirements.txt (line 2))
  Downloading redis-2.10.3.tar.gz (86kB)
Collecting Werkzeug>=0.7 (from flask->-r requirements.txt (line 1))
  Downloading Werkzeug-0.10.4-py2.py3-none-any.whl (293kB)
Collecting Jinja2>=2.4 (from flask->-r requirements.txt (line 1))
  Downloading Jinja2-2.7.3.tar.gz (378kB)
Collecting itsdangerous>=0.21 (from flask->-r requirements.txt (line 1))
  Downloading itsdangerous-0.24.tar.gz (46kB)
Collecting markupsafe (from Jinja2>=2.4->flask->-r requirements.txt (line 1))
  Downloading MarkupSafe-0.23.tar.gz
Building wheels for collected packages: flask, redis, Jinja2, itsdangerous, markupsafe
  Running setup.py bdist_wheel for flask
  Stored in directory: /root/.cache/pip/wheels/d2/db/61/cb9b80526b8f3ba89248ec0a29d6da1bb6013681c930fca987
  Running setup.py bdist_wheel for redis
  Stored in directory: /root/.cache/pip/wheels/b4/82/09/7713ff9bc6f6a58e41b0a89433aed5d2293fd5868f76adef94
  Running setup.py bdist_wheel for Jinja2
  Stored in directory: /root/.cache/pip/wheels/b3/c0/62/8908d15b90a7de8bd15e2e6e5f5ba1398c0d9940d62a6bf8f5
  Running setup.py bdist_wheel for itsdangerous
  Stored in directory: /root/.cache/pip/wheels/97/c0/b8/b37c320ff57e15f993ba0ac98013eee778920b4a7b3ebae3cf
  Running setup.py bdist_wheel for markupsafe
  Stored in directory: /root/.cache/pip/wheels/94/a7/79/f79a998b64c1281cb99fa9bbd33cfc9b8b5775f438218d17a7
Successfully built flask redis Jinja2 itsdangerous markupsafe
Installing collected packages: Werkzeug, markupsafe, Jinja2, itsdangerous, flask, redis
Successfully installed Jinja2-2.7.3 Werkzeug-0.10.4 flask-0.10.1 itsdangerous-0.24 markupsafe-0.23 redis-2.10.3
 ---> 874a18252c20
Removing intermediate container dc537e172768
Successfully built 874a18252c20
Attaching to composetest_redis_1, composetest_web_1
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/compose/build/docker-compose/out00-PYZ.pyz/threading", line 810, in __bootstrap_inner
  File "/compose/build/docker-compose/out00-PYZ.pyz/threading", line 763, in run
  File "/compose/build/docker-compose/out00-PYZ.pyz/compose.cli.multiplexer", line 41, in _enqueue_output
  File "/compose/build/docker-compose/out00-PYZ.pyz/compose.cli.log_printer", line 59, in _make_log_generator
  File "/compose/build/docker-compose/out00-PYZ.pyz/compose.cli.utils", line 77, in split_buffer
  File "/compose/build/docker-compose/out00-PYZ.pyz/docker.client", line 199, in _multiplexed_response_stream_helper
  File "/compose/build/docker-compose/out00-PYZ.pyz/docker.client", line 143, in _get_raw_response_socket
  File "/compose/build/docker-compose/out00-PYZ.pyz/docker.client", line 95, in _raise_for_status
APIError: 500 Server Error: Internal Server Error ("http: Hijack is incompatible with use of CloseNotifier")

web_1   |  * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
web_1   |  * Restarting with stat
```

**Comment by ak47** [comment]
(success)

```
VBoxManage modifyvm "boot2docker-vm" --natpf1 "tcp-port5000,tcp,,5000,,5000";
```

https://www.dropbox.com/s/a0vln5sno722yfd/Screenshot%202015-06-01%2010.37.04.png?dl=0
