### ISSUE TITLE
Comments in docker-compose.yml result in "yaml.reader.ReaderError: unacceptable character #x0000: special characters are not allowed"

### ISSUE THREAD

**Issue by edmorley** [docker/compose#1524]
I'm using Windows, so have to use the docker compose python package from pypi, since there isn't a native binary.

docker-compose.yml:
```yaml
foo:
  # a comment
  image: busybox
```

With both the python docker-compose 1.2.0 and 1.3.0rc1 packages, I get:
```bash
[~/src/tmp]$ docker-compose ps
Traceback (most recent call last):
  File "/usr/bin/docker-compose", line 9, in <module>
    load_entry_point('docker-compose==1.2.0', 'console_scripts', 'docker-compose')()
  File "/usr/lib/python2.7/site-packages/compose/cli/main.py", line 31, in main
    command.sys_dispatch()
  File "/usr/lib/python2.7/site-packages/compose/cli/docopt_command.py", line 21, in sys_dispatch
    self.dispatch(sys.argv[1:], None)
  File "/usr/lib/python2.7/site-packages/compose/cli/command.py", line 27, in dispatch
    super(Command, self).dispatch(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/compose/cli/docopt_command.py", line 24, in dispatch
    self.perform_command(*self.parse(argv, global_options))
  File "/usr/lib/python2.7/site-packages/compose/cli/command.py", line 57, in perform_command
    verbose=options.get('--verbose'))
  File "/usr/lib/python2.7/site-packages/compose/cli/command.py", line 76, in get_project
    config.load(config_path),
  File "/usr/lib/python2.7/site-packages/compose/config.py", line 55, in load
    return from_dictionary(load_yaml(filename), working_dir=working_dir, filename=filename)
  File "/usr/lib/python2.7/site-packages/compose/config.py", line 409, in load_yaml
    return yaml.safe_load(fh)
  File "/usr/lib/python2.7/site-packages/yaml/__init__.py", line 93, in safe_load
    return load(stream, SafeLoader)
  File "/usr/lib/python2.7/site-packages/yaml/__init__.py", line 69, in load
    loader = Loader(stream)
  File "/usr/lib/python2.7/site-packages/yaml/loader.py", line 24, in __init__
    Reader.__init__(self, stream)
  File "/usr/lib/python2.7/site-packages/yaml/reader.py", line 85, in __init__
    self.determine_encoding()
  File "/usr/lib/python2.7/site-packages/yaml/reader.py", line 135, in determine_encoding
    self.update(1)
  File "/usr/lib/python2.7/site-packages/yaml/reader.py", line 169, in update
    self.check_printable(data)
  File "/usr/lib/python2.7/site-packages/yaml/reader.py", line 144, in check_printable
    'unicode', "special characters are not allowed")
yaml.reader.ReaderError: unacceptable character #x0000: special characters are not allowed
  in "./docker-compose.yml", position 22
```

This is being run on Windows 8.1, inside an MSYS2 shell, with Python 2.7.9 and Docker version 1.6.2.

**Comment by edmorley** [comment]
This seems related perhaps?
http://pyyaml.org/ticket/204

Even if this is an upstream PyYAML issue, it would be good to try and work around it in compose if possible - particularly since Windows users have no choice other than to use the Python package at the moment :-)

**Comment by funkyfuture** [comment]
can you test if a change like here catches you error: https://github.com/funkyfuture/docker-compose/blob/config_validation/compose/config.py#L414

**Comment by edmorley** [comment]
So I tried to do this - and in the process found that I was using a mixture of the native Windows python and the msys2 python2 package.

I've since tried using _just_ the native Windows python (which results in the `ImportError: No module named fcntl` of d11wtq/dockerpty#7, so is a non-starter) and also 100% msys2 python - with the latter giving me:
``SSL error: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:585)``

...so I'm not able to get it working again now enough to repro :-(

**Comment by edmorley** [comment]
Ok so the SSL error turned out to be due to needing to downgrade from openssl-1.0.2a to 1.0.1.

Once I've done that I can run docker-compose again - and trying the above no longer reproduces - so not sure it was that fixed it. Is up to you whether to close the issue now - or leave open since presumably some docker-compose+python combo doesn't work well with yaml comments.

**Comment by phazei** [comment]
I'm still getting this in windows, using
```
echo 'alias docker-compose='"'"'docker run --rm -it \
        -v /$(pwd):/app \
        -v //var/run/docker.sock://var/run/docker.sock \
        -e COMPOSE_PROJECT_NAME=$(basename /$(pwd)) \
         dduportal/docker-compose:latest'"'" >> /home/docker/.ashrc
```
With windows native client, or in boot2docker

It didn't seem to have any issues a couple days ago.

**Comment by dnephin** [comment]
Is anyone able to reproduce this with the docker-compose 1.5 release? (which is the first release to officially support windows).

**Comment by edmorley** [comment]
I don't have docker installed on this machine at the moment, it may be a while before I have a chance to double back to this - happy to call it fixed in the meantime, if you'd prefer :-)
