### ISSUE TITLE
x-smart-recreate crashes when modified image name/tag

### ISSUE THREAD

**Issue by josephpage** [docker/compose#1561]
Just got this error with docker-compose 1.3.0rc2 :

```
$ docker-compose up --x-smart-recreate
Traceback (most recent call last):
  File "<string>", line 3, in <module>
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.cli.main", line 31, in main
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.cli.docopt_command", line 21, in sys_dispatch
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.cli.command", line 34, in dispatch
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.cli.docopt_command", line 24, in dispatch
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.cli.command", line 66, in perform_command
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.cli.main", line 469, in up
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.project", line 221, in up
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.project", line 261, in _get_convergence_plans
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.service", line 285, in convergence_plan
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.service", line 299, in _containers_have_diverged
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.service", line 415, in config_hash
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.service", line 420, in config_dict
TypeError: 'NoneType' object has no attribute '__getitem__'
```

Resolved after `docker-compose pull`

**Comment by aanand** [comment]
Can you provide more information please? What sequence of commands did you type? What does your YAML look like? Does the problem only occur if you use `--x-smart-recreate`?

**Comment by josephpage** [comment]
Simple case : 

```
$ cat <<EOF > docker-compose.yml
example:
  image: debian:latest
  command: echo "hello world"
EOF

$ docker-compose up -d --x-smart-recreate
Pulling example (debian:latest)...
latest: Pulling from debian
64e5325c0d9d: Pull complete
bf84c1d84a8f: Already exists
debian:latest: The image you are pulling has been verified. Important: image verification is a tech preview feature and should not be relied on to provide security.
Digest: sha256:2613dd69166e1bcc0a3e4b1f7cfe30d3dfde7762aea0e2f467632bda681d9765
Status: Downloaded newer image for debian:latest
Creating demo_example_1...
```

```
$ cat <<EOF > docker-compose.yml
example:
  image: debian:8.1
  command: echo "hello world"
EOF

$ docker-compose up -d --x-smart-recreate
Traceback (most recent call last):
  File "/usr/local/bin/docker-compose", line 9, in <module>
    load_entry_point('docker-compose==1.4.0.dev0', 'console_scripts', 'docker-compose')()
  File "/Users/joseph/git-workplace/contrib/compose/compose/cli/main.py", line 33, in main
    command.sys_dispatch()
  File "/Users/joseph/git-workplace/contrib/compose/compose/cli/docopt_command.py", line 21, in sys_dispatch
    self.dispatch(sys.argv[1:], None)
  File "/Users/joseph/git-workplace/contrib/compose/compose/cli/command.py", line 34, in dispatch
    super(Command, self).dispatch(*args, **kwargs)
  File "/Users/joseph/git-workplace/contrib/compose/compose/cli/docopt_command.py", line 24, in dispatch
    self.perform_command(*self.parse(argv, global_options))
  File "/Users/joseph/git-workplace/contrib/compose/compose/cli/command.py", line 66, in perform_command
    handler(project, command_options)
  File "/Users/joseph/git-workplace/contrib/compose/compose/cli/main.py", line 465, in up
    timeout=timeout
  File "/Users/joseph/git-workplace/contrib/compose/compose/project.py", line 232, in up
    smart_recreate=smart_recreate,
  File "/Users/joseph/git-workplace/contrib/compose/compose/project.py", line 273, in _get_convergence_plans
    smart_recreate=smart_recreate,
  File "/Users/joseph/git-workplace/contrib/compose/compose/service.py", line 264, in convergence_plan
    if smart_recreate and not self._containers_have_diverged(containers):
  File "/Users/joseph/git-workplace/contrib/compose/compose/service.py", line 278, in _containers_have_diverged
    config_hash = self.config_hash()
  File "/Users/joseph/git-workplace/contrib/compose/compose/service.py", line 382, in config_hash
    return json_hash(self.config_dict())
  File "/Users/joseph/git-workplace/contrib/compose/compose/service.py", line 387, in config_dict
    'image_id': self.image()['Id'],
TypeError: 'NoneType' object has no attribute '__getitem__'
```

```
$ docker pull debian:8.1
8.1: Pulling from debian
64e5325c0d9d: Already exists 
bf84c1d84a8f: Already exists 
debian:8.1: The image you are pulling has been verified. Important: image verification is a tech preview feature and should not be relied on to provide security.
Digest: sha256:44241b371e469ff74cd6b401231bfef80832108b5ee0e6bb7a2ac26a70326dd5
Status: Downloaded newer image for debian:8.1

$ docker-compose up -d --x-smart-recreate
Recreating demo_example_1...
```

The bug appears when changing the tag (or name ?) of the image.
