### ISSUE TITLE
Unable to run any compose command

### ISSUE THREAD

**Issue by scan** [docker/compose#1629]
The only other issue related is #1485, but I tried their solution and it did not work.

I'm using Docker 1.7.0 on Arch Linux. It took me a while to find out how to install compose, and in the end I used 

```bash
sudo pip install docker-compose
```

Which installed docker-compose 1.3.1 for me. I ran the command `docker-compose` and it worked fine. But trying an further command like `docker-compose build` or `docker-compose up`, I always get the same error message:

```bash
$ docker-compose up
Traceback (most recent call last):
  File "/usr/bin/docker-compose", line 9, in <module>
    load_entry_point('docker-compose==1.3.1', 'console_scripts', 'docker-compose')()
  File "/usr/lib/python3.4/site-packages/compose/cli/main.py", line 31, in main
    command.sys_dispatch()
  File "/usr/lib/python3.4/site-packages/compose/cli/docopt_command.py", line 21, in sys_dispatch
    self.dispatch(sys.argv[1:], None)
  File "/usr/lib/python3.4/site-packages/compose/cli/command.py", line 34, in dispatch
    super(Command, self).dispatch(*args, **kwargs)
  File "/usr/lib/python3.4/site-packages/compose/cli/docopt_command.py", line 24, in dispatch
    self.perform_command(*self.parse(argv, global_options))
  File "/usr/lib/python3.4/site-packages/compose/cli/command.py", line 64, in perform_command
    verbose=options.get('--verbose'))
  File "/usr/lib/python3.4/site-packages/compose/cli/command.py", line 83, in get_project
    config.load(config_path),
  File "/usr/lib/python3.4/site-packages/compose/config.py", line 68, in load
    return from_dictionary(load_yaml(filename), working_dir=working_dir, filename=filename)
  File "/usr/lib/python3.4/site-packages/compose/config.py", line 78, in from_dictionary
    service_dict = loader.make_service_dict(service_name, service_dict)
  File "/usr/lib/python3.4/site-packages/compose/config.py", line 103, in make_service_dict
    return process_container_options(service_dict, working_dir=self.working_dir)
  File "/usr/lib/python3.4/site-packages/compose/config.py", line 189, in process_container_options
    service_dict['build'] = resolve_build_path(service_dict['build'], working_dir=working_dir)
  File "/usr/lib/python3.4/site-packages/compose/config.py", line 367, in resolve_build_path
    return expand_path(working_dir, build_path)
  File "/usr/lib/python3.4/site-packages/compose/config.py", line 440, in expand_path
    return os.path.abspath(os.path.join(working_dir, path))
  File "/usr/lib/python3.4/posixpath.py", line 79, in join
    if b.startswith(sep):
AttributeError: 'NoneType' object has no attribute 'startswith'
```

Anyone can help me out there?

**Comment by scan** [comment]
It seems I forgot to type a `.` from the example file. My apologies.
