### ISSUE TITLE
Crash: TypeError: Unicode-objects must be encoded before hashing

### ISSUE THREAD

**Issue by jemc** [docker/compose#1635]
```
 docker-compose --version
docker-compose version: 1.3.1
CPython version: 3.4.2
OpenSSL version: OpenSSL 1.0.1k-fips 8 Jan 2015
```

I get the following unicode-related error when trying to run `docker-compose up` on even this trivial `docker-compose.yml` file.

```
# docker-compose.yml
redis:
  image: redis
```

```
 sudo docker-compose up

Traceback (most recent call last):
  File "/bin/docker-compose", line 9, in <module>
    load_entry_point('docker-compose==1.3.1', 'console_scripts', 'docker-compose')()
  File "/usr/lib/python3.4/site-packages/compose/cli/main.py", line 31, in main
    command.sys_dispatch()
  File "/usr/lib/python3.4/site-packages/compose/cli/docopt_command.py", line 21, in sys_dispatch
    self.dispatch(sys.argv[1:], None)
  File "/usr/lib/python3.4/site-packages/compose/cli/command.py", line 34, in dispatch
    super(Command, self).dispatch(*args, **kwargs)
  File "/usr/lib/python3.4/site-packages/compose/cli/docopt_command.py", line 24, in dispatch
    self.perform_command(*self.parse(argv, global_options))
  File "/usr/lib/python3.4/site-packages/compose/cli/command.py", line 66, in perform_command
    handler(project, command_options)
  File "/usr/lib/python3.4/site-packages/compose/cli/main.py", line 460, in up
    do_build=not options['--no-build'],
  File "/usr/lib/python3.4/site-packages/compose/project.py", line 226, in up
    for service in services
  File "/usr/lib/python3.4/site-packages/compose/project.py", line 230, in <listcomp>
    do_build=do_build,
  File "/usr/lib/python3.4/site-packages/compose/service.py", line 320, in execute_convergence_plan
    do_build=do_build,
  File "/usr/lib/python3.4/site-packages/compose/service.py", line 215, in create_container
    previous_container=previous_container,
  File "/usr/lib/python3.4/site-packages/compose/service.py", line 510, in _get_container_create_options
    config_hash = self.config_hash()
  File "/usr/lib/python3.4/site-packages/compose/service.py", line 398, in config_hash
    return json_hash(self.config_dict())
  File "/usr/lib/python3.4/site-packages/compose/utils.py", line 8, in json_hash
    h.update(dump)
TypeError: Unicode-objects must be encoded before hashing
```

Looking in `compose/utils.py`, I see:

```python
import json
import hashlib


def json_hash(obj):
    dump = json.dumps(obj, sort_keys=True, separators=(',', ':'))
    h = hashlib.sha256()
    h.update(dump)
    return h.hexdigest()
```

If I add the following print lines to that function before the `h.update(dump)` line that crashes, I get the following printed:
```python
    print(dump)
    print(type(dump))
```
```python
{"image_id":"0ecdc1a8a4c9eb53830ec59072a7f5dd7bf69c6077f60215cf4a99cd351dd5a1","options":{"image":"redis"}}
<class 'str'>
```

**Comment by jemc** [comment]
Looking for other users with a similar problem, I found this: http://stackoverflow.com/questions/30997213/docker-compose-error-unicode-objects-must-be-encoded-before-hashing

**Comment by dnephin** [comment]
@jemc we're not python3 compatible yet , see #440

**Comment by jemc** [comment]
Okay, didn't realize - sorry for the noise - I had assumed it was python2 support that was lackluster when I ran into symptoms like #1288 and proceeded to try python3.
