### ISSUE TITLE
Unable to run `docker-compose up` due to unhandled python exception

### ISSUE THREAD

**Issue by globexdesigns** [docker/compose#1789]
I've tried this in docker-compose v1.3.3 and 1.4.0-rc2 and I get this error every time I run `docker-compose up`:

```
> docker-compose up
Traceback (most recent call last):
  File "/usr/local/bin/docker-compose", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/compose/cli/main.py", line 32, in main
    command.sys_dispatch()
  File "/usr/local/lib/python2.7/site-packages/compose/cli/docopt_command.py", line 21, in sys_dispatch
    self.dispatch(sys.argv[1:], None)
  File "/usr/local/lib/python2.7/site-packages/compose/cli/command.py", line 34, in dispatch
    super(Command, self).dispatch(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/compose/cli/docopt_command.py", line 24, in dispatch
    self.perform_command(*self.parse(argv, global_options))
  File "/usr/local/lib/python2.7/site-packages/compose/cli/command.py", line 66, in perform_command
    handler(project, command_options)
  File "/usr/local/lib/python2.7/site-packages/compose/cli/main.py", line 471, in up
    timeout=timeout
  File "/usr/local/lib/python2.7/site-packages/compose/project.py", line 230, in up
    service.remove_duplicate_containers()
  File "/usr/local/lib/python2.7/site-packages/compose/service.py", line 398, in remove_duplicate_containers
    for c in self.duplicate_containers():
  File "/usr/local/lib/python2.7/site-packages/compose/service.py", line 405, in duplicate_containers
    self.containers(stopped=True),
  File "/usr/local/lib/python2.7/site-packages/compose/service.py", line 106, in containers
    filters={'label': self.labels(one_off=one_off)})]
  File "/usr/local/lib/python2.7/site-packages/docker/client.py", line 202, in containers
    res = self._result(self._get(u, params=params), True)
  File "/usr/local/lib/python2.7/site-packages/docker/clientbase.py", line 86, in _get
    return self.get(url, **self._set_request_timeout(kwargs))
  File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 477, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 465, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/adapters.py", line 370, in send
    timeout=timeout
  File "/usr/local/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 544, in urlopen
    body=body, headers=headers)
  File "/usr/local/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 344, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=conn.timeout)
  File "/usr/local/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 314, in _raise_timeout
    if 'timed out' in str(err) or 'did not complete (read)' in str(err):  # Python 2.6
TypeError: __str__ returned non-string (type Error)
```

**Comment by ollyw** [comment]
I get the same stack trace. I am using docker compose on the Mac OS X, with the following versions:
docker-compose version: 1.3.3
CPython version: 2.7.10
OpenSSL version: OpenSSL 1.0.2d 9 Jul 2015

**Comment by ollyw** [comment]
This issue was fixed for me when I upgraded boot2docker with ```boot2docker upgrade```

**Comment by dnephin** [comment]
This is a failure from the `requests` package. I believe this would have been fixed when we upgraded requests, which we've done a couple times since this issue was created.

I'm going to close this issue, but please do re-open if you see it again with the latest compose.

**Comment by valendesigns** [comment]
@dnephin I am getting this error while testing on a single AWS EC2 instance. Any ideas why this would be happening?
```
Traceback (most recent call last):
  File "/usr/local/bin/docker-compose", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/compose/cli/main.py", line 68, in main
    command()
  File "/usr/local/lib/python2.7/site-packages/compose/cli/main.py", line 118, in perform_command
    handler(command, command_options)
  File "/usr/local/lib/python2.7/site-packages/compose/cli/main.py", line 942, in up
    cascade_starter = log_printer.run()
  File "/usr/local/lib/python2.7/site-packages/compose/cli/log_printer.py", line 87, in run
    for line in consume_queue(queue, self.cascade_stop):
  File "/usr/local/lib/python2.7/site-packages/compose/cli/log_printer.py", line 235, in consume_queue
    raise item.exc
MemoryError
```
