### ISSUE TITLE
TypeError when service name is a number

### ISSUE THREAD

**Issue by juliantaylor** [docker/compose#1845]
```
1:
    build: .
```

leads to a type error and not a useful error message like invalid name

```
Traceback (most recent call last):
  File "<string>", line 3, in <module>
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.cli.main", line 39, in main
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.cli.docopt_command", line 21, in sys_dispatch
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.cli.command", line 27, in dispatch
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.cli.docopt_command", line 24, in dispatch
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.cli.command", line 57, in perform_command
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.cli.command", line 79, in get_project
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.project", line 85, in from_dicts
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.service", line 85, in __init__
  File "/code/build/docker-compose/out00-PYZ.pyz/re", line 141, in match
TypeError: expected string or buffer
```

**Comment by aanand** [comment]
@mnowster: Will #1808 catch this?

**Comment by mnowster** [comment]
@aanand yes, only these chars are allowed `[a-zA-Z0-9._-]`

**Comment by juliantaylor** [comment]
a number matches that pattern

**Comment by mnowster** [comment]
sorry, yes you're absolutely right @juliantaylor , I need to drink some more coffee before re-reading my regexes.

**Comment by mnowster** [comment]
I'll add to my list to fix :+1:

**Comment by juliantaylor** [comment]
I assume it could be a valid service name, compose might just need to convert integer dictionary keys to strings.

**Comment by mnowster** [comment]
@juliantaylor yep, I think it could be a valid service name. This will get sorted in a separate PR rather than #1808 
Thanks for reporting the issue!

**Comment by mnowster** [comment]
Fixed by https://github.com/docker/compose/pull/1855 but I didn't put the fixes in the comment so it didn't close this. *face-palm*
