### ISSUE TITLE
JSON error when building against Swarm

### ISSUE THREAD

**Issue by ehazlett** [docker/compose#1913]
I'm getting this issue when trying to build against Swarm:

```
Building web...
docker build <- (pull=False, nocache=False, stream=True, tag=u'composetest_web', path='/home/ehazlett/sandbox/composetest', rm=True, dockerfile=None)
docker build -> <generator object _stream_helper at 0x7f4daf6525a0>
Step 0 : FROM python:2.7
 ---> e1857ee1f3b5
Step 1 : ADD . /code
 ---> 65534a2a411c
Traceback (most recent call last):
  File "<string>", line 3, in <module>
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.cli.main", line 32, in main
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.cli.docopt_command", line 21, in sys_dispatch
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.cli.command", line 34, in dispatch
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.cli.docopt_command", line 24, in dispatch
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.cli.command", line 66, in perform_command
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.cli.main", line 471, in up
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.project", line 245, in up
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.service", line 318, in execute_convergence_plan
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.service", line 212, in create_container
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.service", line 239, in ensure_image_exists
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.service", line 657, in build
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.progress_stream", line 18, in stream_output
  File "/code/build/docker-compose/out00-PYZ.pyz/json", line 338, in loads
  File "/code/build/docker-compose/out00-PYZ.pyz/json.decoder", line 369, in decode
ValueError: Extra data: line 2 column 1 - line 3 column 1 (char 61 - 100)
```

The build works fine using the Docker CLI against Swarm  so I think the JSON should be what is expected from the API.

**Comment by aanand** [comment]
The JSON decoding in Compose is probably quite out of date compared to the Docker client.

We should probably add more debug in so that we can at least see what the blob was that caused the error.

**Comment by dhiltgen** [comment]
I instrumented the code a bit, and it appears the problem is an assumption that must no longer hold true.  In compose/progress_stream.py around line 23, the chunk may not contain a complete json block.  I dumped it out, and I see a bunch of valid json chunks like '{"stream":"Step 1 : FROM busybox:latest\n"}' but the very last one in the chunk is incomplete.  In my test it came up with '{"stream":"'

It does appear that the blocks are newline wrapped (although I don't know if that assumption is formally defined), so one possibility would be to split the chunk into lines and deserialize them one at a time, and if the last one fails, combine it with the next chunk.

**Comment by dnephin** [comment]
That sounds like a bug in swarm. The response should be a valid json object per line. That's what the engine returns. It might also just be a buffering issue maybe?

I have a pending PR (#1248) which fixes a bug in swarm that prevents us from running our test suite against swarm.  Running the suite against the fixed version we're able to reproduce this error from a few tests.  I'll be continuing to fix these test fails over the next couple of weeks until the entire suite runs against swarm.

**Comment by dnephin** [comment]
@dhiltgen I think https://github.com/docker/compose/blob/master/compose/cli/utils.py#L39 does what you suggest, but we're not using it for the build stream at this time.

**Comment by dhiltgen** [comment]
It might be buffering... I don't see a newline on the last line of output with the truncated json.

**Comment by dhiltgen** [comment]
Yes, the length of data in the chunk is exactly 2048 bytes - awfully convenient...

**Comment by dnephin** [comment]
It looks like both engine and swarm use a `NewWriteFlusher`, the problem is that it doesn't work in the case of swarm. `NewWriteFlusher` flushes on every call to write, but in swarm, write is only called once per buffer (in engine it's called once per line).

Either way we're going to need to do the buffer joining somewhere, so I guess I'll do it in compose for now.
