### ISSUE TITLE
log_driver: "json-file"  : what syntax for log_opt : max-file & max-size?

### ISSUE THREAD

**Issue by carbip** [docker/compose#1969]
Hi, 
Currently trying to specify max-file & max-size options for default log_driver "json-file", but just can't make it work.
Tried this for example, as suggested in the compose syntax for syslog driver:

log_driver: "json-file"
    log_opt:
        max-size:"30m"
        max-file:"10"

but throws error when starting container

Looked in the associated schema, but ends with type "object" for log_opt which leads me nowhere.
Also looked in unit tests, but only the test for syslog is implemented.

Thanks

**Comment by mnowster** [comment]
Hi,

What version of docker-compose and docker are you using? Can you paste in your docker-compose.yml?

Your .yml for log_opt needs to be an object, so should look like this:

`
log_driver: "json-file"
log_opt:
    max-size: "30m"
    max-file: "10"
`

**Comment by carbip** [comment]
$ docker-compose -v
docker-compose version: 1.4.0

>> file docker.compose.yml
myContainer:
    extends:
        file: docker-compose_main.yml
        service: myContainer
    restart: always
    log_driver: "json-file"
    log_opt:
       max-size:"30m"
       max-file:"10"
    environment:
    - LOG_LEVEL=info
[..]

>> file docker.compose_mail.yml
myContainer:
    build: .
    dockerfile: Dockerfiles/Dockerfile_myContainer
    environment:
    - LOG_LEVEL=debug

error: 
sudo docker-compose -f docker-compose_staging.yml up -d myContainer
Recreating carbip_myContainer_1...
Traceback (most recent call last):
  File "<string>", line 3, in <module>
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.cli.main", line 39, in main
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.cli.docopt_command", line 21, in sys_dispatch
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.cli.command", line 27, in dispatch
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.cli.docopt_command", line 24, in dispatch
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.cli.command", line 59, in perform_command
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.cli.main", line 495, in up
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.project", line 265, in up
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.service", line 381, in execute_convergence_plan
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.service", line 428, in recreate_container
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.service", line 270, in create_container
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.service", line 643, in _get_container_create_options
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.service", line 656, in _get_container_host_config
  File "/code/build/docker-compose/out00-PYZ.pyz/docker.utils.types", line 30, in __init__
ValueError: LogConfig.config must be a dictionary

**Comment by carbip** [comment]
actually I just made it work, by adding a space after max-size: and max-file:
this way: 
log_driver: "json-file"
log_opt:
    max-size: "30m"
    max-file: "10"

is it normal ?

btw, doing inline does not work : 
log_driver: "json-file" log_opt: max-size: "30m" max-file: "10"

**Comment by mnowster** [comment]
Yes that is correct, you need a space between the key name and the value, that's yaml syntax. 

Inline won't work as it won't parse it as an object, it has to be on the next line as you've now got it.

Glad it's now working :+1:
