### ISSUE TITLE
Getting a TypeError when using compose with engine 1.9-dev

### ISSUE THREAD

**Issue by nicolaka** [docker/compose#2009]
I tried to run docker-compose with multiple compose projects on multiple engines and same result....

```
root@ip-10-0-0-80:~/dockchat# docker-compose up -d
Traceback (most recent call last):
  File "/usr/local/bin/docker-compose", line 9, in <module>
    load_entry_point('docker-compose==1.4.0', 'console_scripts', 'docker-compose')()
  File "/usr/local/lib/python2.7/dist-packages/compose/cli/main.py", line 39, in main
    command.sys_dispatch()
  File "/usr/local/lib/python2.7/dist-packages/compose/cli/docopt_command.py", line 21, in sys_dispatch
    self.dispatch(sys.argv[1:], None)
  File "/usr/local/lib/python2.7/dist-packages/compose/cli/command.py", line 27, in dispatch
    super(Command, self).dispatch(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/compose/cli/docopt_command.py", line 24, in dispatch
    self.perform_command(*self.parse(argv, global_options))
  File "/usr/local/lib/python2.7/dist-packages/compose/cli/command.py", line 59, in perform_command
    handler(project, command_options)
  File "/usr/local/lib/python2.7/dist-packages/compose/cli/main.py", line 495, in up
    timeout=timeout
  File "/usr/local/lib/python2.7/dist-packages/compose/project.py", line 251, in up
    service.remove_duplicate_containers()
  File "/usr/local/lib/python2.7/dist-packages/compose/service.py", line 446, in remove_duplicate_containers
    for c in self.duplicate_containers():
  File "/usr/local/lib/python2.7/dist-packages/compose/service.py", line 453, in duplicate_containers
    self.containers(stopped=True),
  File "/usr/local/lib/python2.7/dist-packages/compose/service.py", line 110, in containers
    filters={'label': self.labels(one_off=one_off)})])
TypeError: 'NoneType' object is not iterable

root@ip-10-0-0-80:~/dockchat# docker version
Client:
 Version:      1.9.0-dev
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   5b46d8f
 Built:        Fri Sep  4 17:08:24 UTC 2015
 OS/Arch:      linux/amd64
 Experimental: true

Server:
 Version:      1.9.0-dev
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   5b46d8f
 Built:        Fri Sep  4 17:08:24 UTC 2015
 OS/Arch:      linux/amd64
 Experimental: true

root@ip-10-0-0-80:~/dockchat# docker-compose version
docker-compose version: 1.4.0
docker-py version: 1.3.1
CPython version: 2.7.6
OpenSSL version: OpenSSL 1.0.1f 6 Jan 2014
```

**Comment by runcom** [comment]
Got this error as well while using compose 1.4.0 against docker 1.9.0-dev and the same happens when I try to `docker-compose run something bash` on docker-compose master build (this is not happening to me with compose master if I just `docker-compose up -d` for instance)

**Comment by nicolaka** [comment]
This issue isn't seen with compose 1.2. Error is hit with 1.3 and 1.4.

**Comment by HuKeping** [comment]
I came across a similar issue

**Comment by dnephin** [comment]
This feels like a bug in engine, `curl  $DOCKER_HOST/v1.19/containers/json` returns `null`. It should return `[]`.

**Comment by dnephin** [comment]
Fixed in docker at https://github.com/docker/docker/pull/16403
