### ISSUE TITLE
`up` always fails: ReadTimeout

### ISSUE THREAD

**Issue by chris-martin** [docker/compose#2036]
I'm trying to run docker-compose for the first time.

The trivial `docker-compose.yml` I'm using for testing:

```
redis:
  image: redis
```

Running `docker-compose up`, I get this result (tried repeatedly in case the problem is intermittent, but it isn't):

```
Traceback (most recent call last):
  File "/home/chris/.virtualenvs/docker/bin/docker-compose", line 9, in <module>
    load_entry_point('docker-compose==1.4.0', 'console_scripts', 'docker-compose')()
  File "/home/chris/.virtualenvs/docker/lib/python2.7/site-packages/compose/cli/main.py", line 39, in main
    command.sys_dispatch()
  File "/home/chris/.virtualenvs/docker/lib/python2.7/site-packages/compose/cli/docopt_command.py", line 21, in sys_dispatch
    self.dispatch(sys.argv[1:], None)
  File "/home/chris/.virtualenvs/docker/lib/python2.7/site-packages/compose/cli/command.py", line 27, in dispatch
    super(Command, self).dispatch(*args, **kwargs)
  File "/home/chris/.virtualenvs/docker/lib/python2.7/site-packages/compose/cli/docopt_command.py", line 24, in dispatch
    self.perform_command(*self.parse(argv, global_options))
  File "/home/chris/.virtualenvs/docker/lib/python2.7/site-packages/compose/cli/command.py", line 59, in perform_command
    handler(project, command_options)
  File "/home/chris/.virtualenvs/docker/lib/python2.7/site-packages/compose/cli/main.py", line 495, in up
    timeout=timeout
  File "/home/chris/.virtualenvs/docker/lib/python2.7/site-packages/compose/project.py", line 251, in up
    service.remove_duplicate_containers()
  File "/home/chris/.virtualenvs/docker/lib/python2.7/site-packages/compose/service.py", line 446, in remove_duplicate_containers
    for c in self.duplicate_containers():
  File "/home/chris/.virtualenvs/docker/lib/python2.7/site-packages/compose/service.py", line 453, in duplicate_containers
    self.containers(stopped=True),
  File "/home/chris/.virtualenvs/docker/lib/python2.7/site-packages/compose/service.py", line 110, in containers
    filters={'label': self.labels(one_off=one_off)})])
  File "/home/chris/.virtualenvs/docker/lib/python2.7/site-packages/docker/client.py", line 202, in containers
    res = self._result(self._get(u, params=params), True)
  File "/home/chris/.virtualenvs/docker/lib/python2.7/site-packages/docker/clientbase.py", line 86, in _get
    return self.get(url, **self._set_request_timeout(kwargs))
  File "/home/chris/.virtualenvs/docker/lib/python2.7/site-packages/requests/sessions.py", line 477, in get
    return self.request('GET', url, **kwargs)
  File "/home/chris/.virtualenvs/docker/lib/python2.7/site-packages/requests/sessions.py", line 465, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/chris/.virtualenvs/docker/lib/python2.7/site-packages/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/home/chris/.virtualenvs/docker/lib/python2.7/site-packages/requests/adapters.py", line 433, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)
```

docker-compose version: 1.4.0

Docker version 1.8.1, build d12ea79

**Comment by aanand** [comment]
You're getting an HTTP timeout. There could be many different reasons for that. The error message isn't great, but we're improving on that - see https://github.com/docker/compose/pull/1963.

- Where is Docker running? On your host machine, in a VM, on a remote server?
- Does the `docker` command work fine, e.g. does `docker ps` list containers?

**Comment by chris-martin** [comment]
1. Host machine.
2. A lot has happened in the last few days - long story short, I don't have docker installed anymore, it may be a little while before I can get back to this.

**Comment by chris-martin** [comment]
I'm happy to just call this a duplicate of #1923, though.

**Comment by chris-martin** [comment]
I can't reproduce this anymore, guess there's no point leaving it open.
