### ISSUE TITLE
 The system cannot find the file specified: u'\\fields_schema.json

### ISSUE THREAD

**Issue by alexandrev** [docker/compose#2037]
First of all, I want to apologize because I don't know if this is a bug or a misconfiguration on my side, but I tried to look for this problem but I don't have any response back. 

I'm trying to use the docker-compose in Windows. I'm trying the pull request https://github.com/docker/compose/pull/1957 and I'm getting this error when I try to run an up command:

jsonschema.exceptions.RefResolutionError: <urlopen error [Error 2] The system cannot find the file specified: u'\\fields_schema.json'>

This is the full stacktrace I'm getting:

Traceback (most recent call last):
  File "<string>", line 3, in <module>
  File "D:\Projects\GitHub\compose\build\docker-compose\out00-PYZ.pyz\compose.cli.main", line 51, in main
  File "D:\Projects\GitHub\compose\build\docker-compose\out00-PYZ.pyz\compose.cli.docopt_command", line 23, in sys_dispa
tch
  File "D:\Projects\GitHub\compose\build\docker-compose\out00-PYZ.pyz\compose.cli.command", line 32, in dispatch
  File "D:\Projects\GitHub\compose\build\docker-compose\out00-PYZ.pyz\compose.cli.docopt_command", line 26, in dispatch
  File "D:\Projects\GitHub\compose\build\docker-compose\out00-PYZ.pyz\compose.cli.main", line 146, in perform_command
  File "D:\Projects\GitHub\compose\build\docker-compose\out00-PYZ.pyz\compose.cli.command", line 62, in perform_command
  File "D:\Projects\GitHub\compose\build\docker-compose\out00-PYZ.pyz\compose.cli.command", line 83, in get_project
  File "D:\Projects\GitHub\compose\build\docker-compose\out00-PYZ.pyz\compose.config.config", line 153, in load
  File "D:\Projects\GitHub\compose\build\docker-compose\out00-PYZ.pyz\compose.config.config", line 187, in make_service_
dict
  File "D:\Projects\GitHub\compose\build\docker-compose\out00-PYZ.pyz\compose.config.validation", line 224, in validate_
against_service_schema
  File "D:\Projects\GitHub\compose\build\docker-compose\out00-PYZ.pyz\compose.config.validation", line 237, in _validate
_against_schema
  File "D:\Projects\GitHub\compose\build\docker-compose\out00-PYZ.pyz\jsonschema.validators", line 98, in iter_errors
  File "D:\Projects\GitHub\compose\build\docker-compose\out00-PYZ.pyz\jsonschema._validators", line 320, in allOf_draft4

  File "D:\Projects\GitHub\compose\build\docker-compose\out00-PYZ.pyz\jsonschema.validators", line 114, in descend
  File "D:\Projects\GitHub\compose\build\docker-compose\out00-PYZ.pyz\jsonschema.validators", line 98, in iter_errors
  File "D:\Projects\GitHub\compose\build\docker-compose\out00-PYZ.pyz\jsonschema._validators", line 199, in ref
  File "D:\Projects\GitHub\compose\build\docker-compose\out00-PYZ.pyz\jsonschema.validators", line 336, in resolve
  File "D:\Projects\GitHub\compose\build\docker-compose\out00-PYZ.pyz\functools32.functools32", line 400, in wrapper
  File "D:\Projects\GitHub\compose\build\docker-compose\out00-PYZ.pyz\jsonschema.validators", line 346, in resolve_from_
url
jsonschema.exceptions.RefResolutionError: <urlopen error [Error 2] The system cannot find the file specified: u'\\fields
_schema.json'>

Thanks in advance and sorry if this is not a real bug :(

**Comment by dnephin** [comment]
It is a bug, and someone has submitted a fix in #2035 , we just need to get that merged.

**Comment by alexandrev** [comment]
Thanks for your quick response. I try the change in the Fix you referenced but I'm getting the same error response..

**Comment by alexandrev** [comment]
I did a few investigations and I think the problem is related to this piece of code inside the service_schema.json:

"  "allOf": [
 -->    {"$ref": "fields_schema.json#/definitions/service"},
    {"$ref": "#/definitions/service_constraints"}
  ],
"
I don't know why this is the problem but I think it is not resolving right the source form this reference and crash the program. 

I don't have nowadays the knowledge to know how compose is built but I hope with this information you can address better this unexpected behavior.

**Comment by dnephin** [comment]
@alexandrev ok, this might actually be a windows issue and not related to #2035

**Comment by alexandrev** [comment]
Also if I bypass the JSON Schema validation I face another error. This one seems more important to me, but once again I don't know a lot about the code:

Traceback (most recent call last):
  File "<string>", line 3, in <module>
  File "D:\Projects\GitHub\compose\build\docker-compose\out00-PYZ.pyz\compose.cli.main", line 51, in main
  File "D:\Projects\GitHub\compose\build\docker-compose\out00-PYZ.pyz\compose.cli.docopt_command", line 23, in sys_disp
tch
  File "D:\Projects\GitHub\compose\build\docker-compose\out00-PYZ.pyz\compose.cli.command", line 32, in dispatch
  File "D:\Projects\GitHub\compose\build\docker-compose\out00-PYZ.pyz\compose.cli.docopt_command", line 26, in dispatch
  File "D:\Projects\GitHub\compose\build\docker-compose\out00-PYZ.pyz\compose.cli.main", line 146, in perform_command
  File "D:\Projects\GitHub\compose\build\docker-compose\out00-PYZ.pyz\compose.cli.command", line 64, in perform_command
  File "D:\Projects\GitHub\compose\build\docker-compose\out00-PYZ.pyz\compose.cli.main", line 551, in up
  File "D:\Projects\GitHub\compose\build\docker-compose\out00-PYZ.pyz\compose.project", line 277, in up
  File "D:\Projects\GitHub\compose\build\docker-compose\out00-PYZ.pyz\compose.service", line 476, in remove_duplicate_c
ntainers
  File "D:\Projects\GitHub\compose\build\docker-compose\out00-PYZ.pyz\compose.service", line 483, in duplicate_containe
s
  File "D:\Projects\GitHub\compose\build\docker-compose\out00-PYZ.pyz\compose.service", line 133, in containers
  File "D:\Projects\GitHub\compose\build\docker-compose\out00-PYZ.pyz\docker.client", line 202, in containers
  File "D:\Projects\GitHub\compose\build\docker-compose\out00-PYZ.pyz\docker.clientbase", line 86, in _get
  File "D:\Projects\GitHub\compose\build\docker-compose\out00-PYZ.pyz\requests.sessions", line 477, in get
  File "D:\Projects\GitHub\compose\build\docker-compose\out00-PYZ.pyz\requests.sessions", line 465, in request
  File "D:\Projects\GitHub\compose\build\docker-compose\out00-PYZ.pyz\requests.sessions", line 573, in send
  File "D:\Projects\GitHub\compose\build\docker-compose\out00-PYZ.pyz\requests.adapters", line 370, in send
  File "D:\Projects\GitHub\compose\build\docker-compose\out00-PYZ.pyz\requests.packages.urllib3.connectionpool", line 5
4, in urlopen
  File "D:\Projects\GitHub\compose\build\docker-compose\out00-PYZ.pyz\requests.packages.urllib3.connectionpool", line 3
9, in _make_request
  File "D:\Projects\GitHub\compose\build\docker-compose\out00-PYZ.pyz\httplib", line 995, in request
  File "D:\Projects\GitHub\compose\build\docker-compose\out00-PYZ.pyz\httplib", line 1029, in _send_request
  File "D:\Projects\GitHub\compose\build\docker-compose\out00-PYZ.pyz\httplib", line 991, in endheaders
  File "D:\Projects\GitHub\compose\build\docker-compose\out00-PYZ.pyz\httplib", line 844, in _send_output
  File "D:\Projects\GitHub\compose\build\docker-compose\out00-PYZ.pyz\httplib", line 806, in send
  File "D:\Projects\GitHub\compose\build\docker-compose\out00-PYZ.pyz\docker.unixconn.unixconn", line 39, in connect
AttributeError: 'module' object has no attribute 'AF_UNIX'

If I could help in anything please, let me know. I'd love to help.

**Comment by alexandrev** [comment]
Hi again,

Forget my last message. The error is because the docker server was not up. (Maybe the error in this case should be another one) but everythings is working if I bypass the JSON validation!

Hope this information could help to identify the issue.

**Comment by mnowster** [comment]
Thanks for reporting the issue @alexandrev :+1: 

I've got a fix waiting to be merged. Once it has, if you have the time and want to try it out, let me know if that fixes the issue for you as well.

**Comment by alexandrev** [comment]
Hi @mnowster, Of course I want to try it when it has been merged! Anything I could do to help.

**Comment by wreiske** [comment]
+1 having this issue too... Can't wait until docker-compose works 100% on Windblows! :exclamation:
