### ISSUE TITLE
ImportError: No module named 'Queue'

### ISSUE THREAD

**Issue by talolard** [docker/compose#2108]
When trying to launch docker-compose in a python 3 environment I get the following error
 ````python
(analytics4)tal@tal-desktop:~/dev/analytics/data_migration$ docker-compose up
Traceback (most recent call last):
  File "/home/tal/.virtualenvs/analytics4/bin/docker-compose", line 9, in <module>
    load_entry_point('docker-compose==1.4.2', 'console_scripts', 'docker-compose')()
  File "/home/tal/.virtualenvs/analytics4/local/lib/python3.4/site-packages/pkg_resources.py", line 356, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/tal/.virtualenvs/analytics4/local/lib/python3.4/site-packages/pkg_resources.py", line 2431, in load_entry_point
    return ep.load()
  File "/home/tal/.virtualenvs/analytics4/local/lib/python3.4/site-packages/pkg_resources.py", line 2147, in load
    ['__name__'])
  File "/home/tal/.virtualenvs/analytics4/local/lib/python3.4/site-packages/compose/cli/main.py", line 16, in <module>
    from ..project import NoSuchService, ConfigurationError
  File "/home/tal/.virtualenvs/analytics4/local/lib/python3.4/site-packages/compose/project.py", line 12, in <module>
    from .service import ContainerNet
  File "/home/tal/.virtualenvs/analytics4/local/lib/python3.4/site-packages/compose/service.py", line 28, in <module>
    from .utils import json_hash, parallel_execute
  File "/home/tal/.virtualenvs/analytics4/local/lib/python3.4/site-packages/compose/utils.py", line 8, in <module>
    from Queue import Queue, Empty
ImportError: No module named 'Queue'
```
Easy enough fix, 
````python
from Queue import Queue, Empty 
````

Should be 
````python
try:
    from Queue import Queue, Empty 
except:
    from queue import Queue, Empty 
````

**Comment by mnowster** [comment]
Hi @talolard what version of docker-compose are you running?

I believe we've already fixed this in master so should go out with the upcoming 1.5 release.

**Comment by joshuataylor** [comment]
Confirmed that using the latest git checkout solved this for me.

If you're using pip, it's pretty straight forward:
```
pip uninstall docker-compose
pip install git+git://github.com/docker/compose.git
```

**Comment by chiefy** [comment]
I'm not a python guy, so not sure, but...

```
sudo pip install -U docker-compose==1.5.0rc2
The directory '/Users/chief/Library/Caches/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/Users/chief/Library/Caches/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting docker-compose==1.5.0rc2
  Downloading docker-compose-1.5.0rc2.tar.gz (100kB)
    100% |████████████████████████████████| 102kB 382kB/s
Requirement already up-to-date: docopt<0.7,>=0.6.1 in /Library/Python/2.7/site-packages (from docker-compose==1.5.0rc2)
Requirement already up-to-date: PyYAML<4,>=3.10 in /Library/Python/2.7/site-packages (from docker-compose==1.5.0rc2)
Collecting requests<2.8,>=2.6.1 (from docker-compose==1.5.0rc2)
  Downloading requests-2.7.0-py2.py3-none-any.whl (470kB)
    100% |████████████████████████████████| 471kB 721kB/s
Requirement already up-to-date: texttable<0.9,>=0.8.1 in /Library/Python/2.7/site-packages (from docker-compose==1.5.0rc2)
Requirement already up-to-date: websocket-client<1.0,>=0.32.0 in /Library/Python/2.7/site-packages (from docker-compose==1.5.0rc2)
Collecting docker-py<2,>=1.5.0 (from docker-compose==1.5.0rc2)
  Downloading docker-py-1.5.0.tar.gz (59kB)
    100% |████████████████████████████████| 61kB 1.9MB/s
Requirement already up-to-date: dockerpty<0.4,>=0.3.4 in /Library/Python/2.7/site-packages (from docker-compose==1.5.0rc2)
Requirement already up-to-date: six<2,>=1.3.0 in /Library/Python/2.7/site-packages (from docker-compose==1.5.0rc2)
Requirement already up-to-date: jsonschema<3,>=2.5.1 in /Library/Python/2.7/site-packages (from docker-compose==1.5.0rc2)
Requirement already up-to-date: enum34<2,>=1.0.4 in /Library/Python/2.7/site-packages (from docker-compose==1.5.0rc2)
Requirement already up-to-date: functools32 in /Library/Python/2.7/site-packages (from jsonschema<3,>=2.5.1->docker-compose==1.5.0rc2)
Installing collected packages: requests, docker-py, docker-compose
  Found existing installation: requests 2.6.2
    Uninstalling requests-2.6.2:
      Successfully uninstalled requests-2.6.2
  Found existing installation: docker-py 1.3.1
    Uninstalling docker-py-1.3.1:
      Successfully uninstalled docker-py-1.3.1
  Running setup.py install for docker-py
  Found existing installation: docker-compose 1.4.2
    Uninstalling docker-compose-1.4.2:
      Successfully uninstalled docker-compose-1.4.2
  Running setup.py install for docker-compose
Successfully installed docker-compose-1.5.0rc2 docker-py-1.5.0 requests-2.7.0

~ 7s
❯ dc
Traceback (most recent call last):
  File "/usr/local/bin/docker-compose", line 9, in <module>
    load_entry_point('docker-compose==1.5.0rc2', 'console_scripts', 'docker-compose')()
  File "/Library/Python/2.7/site-packages/pkg_resources/__init__.py", line 558, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/Library/Python/2.7/site-packages/pkg_resources/__init__.py", line 2682, in load_entry_point
    return ep.load()
  File "/Library/Python/2.7/site-packages/pkg_resources/__init__.py", line 2355, in load
    return self.resolve()
  File "/Library/Python/2.7/site-packages/pkg_resources/__init__.py", line 2361, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/Library/Python/2.7/site-packages/compose/cli/main.py", line 20, in <module>
    from ..progress_stream import StreamOutputError
  File "/Library/Python/2.7/site-packages/compose/progress_stream.py", line 1, in <module>
    from compose import utils
  File "/Library/Python/2.7/site-packages/compose/utils.py", line 11, in <module>
    from six.moves.queue import Empty
ImportError: No module named queue
```

**Comment by MrMMorris** [comment]
@joshuataylor didn't work for me

```
$ pip list | grep compose
docker-compose (1.6.0.dev0)

$ docker-compose -v                                                                  ±[●●][docker]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/bin/docker-compose", line 9, in <module>
    load_entry_point('docker-compose==1.6.0.dev0', 'console_scripts', 'docker-compose')()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pkg_resources/__init__.py", line 558, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2682, in load_entry_point
    return ep.load()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2355, in load
    return self.resolve()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2361, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/compose/cli/main.py", line 20, in <module>
    from ..progress_stream import StreamOutputError
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/compose/progress_stream.py", line 1, in <module>
    from compose import utils
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/compose/utils.py", line 11, in <module>
    from six.moves.queue import Empty
ImportError: No module named queue
```

**Comment by MrMMorris** [comment]
downgrading to 1.4.2 works. This is why I never upgrade anything Docker related...

**Comment by dnephin** [comment]
This is why the new install instructions (http://docs.docker.com/compose/install/#install-using-pip) suggest using a virtualenv. Because the version of six (and other python modules) provided by many OSes are ancient and missing things required by compose.

**Comment by yanqiw** [comment]
from: https://forums.docker.com/t/is-anyone-able-to-run-docker-compose-on-a-mac/4287/4
this works form me:
$ sudo easy_install bpython

**Comment by thelastinuit** [comment]
@yanqiw Gosh! saved my life dude! it worked for me.
