### ISSUE TITLE
[Windows] ValueError: LogConfig.type must be one of (json-file, syslog, none)

### ISSUE THREAD

**Issue by alexandrev** [docker/compose#2135]
I'm getting this error when I was trying to run a docker-compose up command:

```bash
Status: Downloaded newer image for cpuguy83/docker-grand-ambassador:latest===>]     32 B/32 B6 MB
Traceback (most recent call last):
  File "C:\Python34\Scripts\docker-compose-script.py", line 9, in <module>
    load_entry_point('docker-compose==1.5.0dev', 'console_scripts', 'docker-compose')()
  File "d:\projects\github\compose\compose\cli\main.py", line 51, in main
    command.sys_dispatch()
  File "d:\projects\github\compose\compose\cli\docopt_command.py", line 23, in sys_dispatch
    self.dispatch(sys.argv[1:], None)
  File "d:\projects\github\compose\compose\cli\command.py", line 32, in dispatch
    super(Command, self).dispatch(*args, **kwargs)
  File "d:\projects\github\compose\compose\cli\docopt_command.py", line 26, in dispatch
    self.perform_command(*self.parse(argv, global_options))
  File "d:\projects\github\compose\compose\cli\main.py", line 146, in perform_command
    return super(TopLevelCommand, self).perform_command(options, *args, **kwargs)
  File "d:\projects\github\compose\compose\cli\command.py", line 64, in perform_command
    handler(project, command_options)
  File "d:\projects\github\compose\compose\cli\main.py", line 553, in up
    timeout=timeout
  File "d:\projects\github\compose\compose\project.py", line 283, in up
    for service in services
  File "d:\projects\github\compose\compose\project.py", line 287, in <listcomp>
    timeout=timeout
  File "d:\projects\github\compose\compose\service.py", line 399, in execute_convergence_plan
    do_build=do_build,
  File "d:\projects\github\compose\compose\service.py", line 303, in create_container
    previous_container=previous_container,
  File "d:\projects\github\compose\compose\service.py", line 648, in _get_container_create_options
    one_off=one_off)
  File "d:\projects\github\compose\compose\service.py", line 661, in _get_container_host_config
    config=options.get('log_opt', None)
  File "C:\Python34\lib\site-packages\docker\utils\types.py", line 27, in __init__
    ', '.join(self.types._values)
ValueError: LogConfig.type must be one of (json-file, syslog, none)´´´

**Comment by dnephin** [comment]
This error looks like it's using an older version of docker-py.

**Comment by alexandrev** [comment]
Ok @dnephin: Could I do anything to help to fix right this issue?

**Comment by dnephin** [comment]
Could you include the output of `docker-compose version`, `docker version`, and how you installed compose?

From what I can see it's using an older version of `docker-py` which we've fixed in master

**Comment by alexandrev** [comment]
Of course! Anything I could do to help.

Docker-compose version: 
```bash
docker-compose version: 1.5.0dev
```
Docker version:
```bash
Client API version: 1.16
Go version (client): go1.3.3
OS/Arch (client): windows/amd64
Server version: 1.8.2
Server API version: 1.20
Go version (server): go1.4.2
Git commit (server): 0a8c2e3
```
I've installed compose directly from Git with the commit from the 3rd October:

![image](https://cloud.githubusercontent.com/assets/947041/10291534/a59ab116-6baa-11e5-860f-438e208e0e23.png)

**Comment by dnephin** [comment]
hmm, that commit you're referencing with the highlight isn't in master yet.

I think this would have been fixed by d1dd06a7e2f28c0e2f7df53c0a7af13d6b12ece1.  If you're installing from git, how did you install `docker-py` ? Can you verify that you have 1.4.0 installed?

**Comment by alexandrev** [comment]
I don't understand you well, but I'm going to explain myself and see if this information could help you understand your concerns.

I paste the contents of the requirements.txt I use when I compile & build:

![image](https://cloud.githubusercontent.com/assets/947041/10293080/e35df2da-6bb2-11e5-8fd1-76fc7deedfd5.png)

And I use the build-windows.ps1 script to build the docker compose. 

Is this information enoguh for you?

**Comment by dnephin** [comment]
Thanks! yes, that should be correct. 

I'm not sure, but from the stacktrace it seems like it might not be running the binary. `File "C:\Python34\lib\site-packages\docker\utils\types.py", line 27, in __init__` is a system path.

Is it possible you built the binary, but you're actually running the local docker-compose command from the checkout?

Can you try running `.\dist\docker-compose-Windows-x86_64.exe` ?

**Comment by alexandrev** [comment]
Ok, I'm going to try to reproduce with the built compose and come back to
you with the full log traces.

Thanks for you support

**Comment by alexandrev** [comment]
You are right. I cannot reproduce it with the latest version of the git repo but I cand do it with the bundle tool. So, maybe you are right, and that¡s an error that you already fix. 

Sorry, again.

**Comment by alexandrev** [comment]
I forgot to close that issue. I'm doing that now.
