### ISSUE TITLE
Docker compose build for remte with dockerfile

### ISSUE THREAD

**Issue by sebglon** [docker/compose#2282]
I have docker-composne.YML like this:

repo:
# Default credentials are: admin / admin123
  build: repo
  ports:
    - 8083:8081
  volumes:
    - /data-volume/repo:/sonatype-work

I have setting DOCKER_HOST to my remote docker and it is OK
But when i run docker-compose build, i have this error:

```
Traceback (most recent call last):
  File "<string>", line 3, in <module>
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.cli.main", line 39, in main
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.cli.docopt_command", line 21, in sys_dispatch
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.cli.command", line 27, in dispatch
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.cli.docopt_command", line 24, in dispatch
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.cli.command", line 59, in perform_command
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.cli.main", line 495, in up
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.project", line 274, in up
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.service", line 377, in execute_convergence_plan
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.service", line 271, in create_container
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.service", line 297, in ensure_image_exists
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.service", line 696, in build
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.progress_stream", line 18, in stream_output
  File "/code/build/docker-compose/out00-PYZ.pyz/json", line 338, in loads
  File "/code/build/docker-compose/out00-PYZ.pyz/json.decoder", line 369, in decode
ValueError: Extra data: line 2 column 1 - line 3 column 16157 (char 53 - 16266)
```

if i run docker build on repo/Dockerfile, hte build is OK;

I don't understand why?

**Comment by dnephin** [comment]
I think this has been fixed in master. Can you try the latest rc release?

https://github.com/docker/compose/releases/tag/1.5.0rc2

**Comment by sebglon** [comment]
Yes i work on 1.5.0.0rc2

**Comment by dnephin** [comment]
Sorry, Is that "yes it works?" or "yes, I was using rc2" ?

**Comment by sebglon** [comment]
sorry yes it works

**Comment by dmoran-epages** [comment]
I have docker 1.8.2 and docker-compose 1.5.1 and am having this problem too.
Seems the bug was reintroduced?

**Comment by dnephin** [comment]
Please include a paste of the stacktrace for the error

**Comment by dnephin** [comment]
It may be that this wasn't fixed until #2400, which fixes a related issue

**Comment by dmoran-epages** [comment]
[root@team-gold-demo-ms mysql_multi]# docker-compose build
db uses an image, skipping
Building my-rails
Step 0 : FROM rails:4.2.4
4.2.4: Pulling from library/rails
ef2704e74ecc: Pull complete
1d6f63d023f5: Pull complete
4c0cc976b7bb: Pull complete
dc921aeac8d0: Pull complete
c4af890297db: Pull complete
eeb0bd1cf4f5: Pull complete
b3efe9f23fdc: Pull complete
41b5888f5502: Pull complete
697c09635f79: Pull complete
4814018ce827: Pull complete
e4fb9e496d13: Pull complete
3c0c58cb4989: Pull complete
db23b71e46ec: Pull complete
e18b55a247a7: Pull complete
f02b41b12e4e: Pull complete
d1909d9cd993: Pull complete
a98470dd25c0: Pull complete
77c10d13c30e: Pull complete
40f5ded87491: Pull complete
6c23bed7c103: Pull complete
0e12902681d6: Pull complete
Digest: sha256:9d2e78c6fe34df179942c4450be8d772c0ff9c17dadf3fe3e6176e07c9b84052
Status: Downloaded newer image for docker.io/rails:4.2.4
Traceback (most recent call last):
  File "<string>", line 3, in <module>
  File "/code/compose/cli/main.py", line 54, in main
  File "/code/compose/cli/docopt_command.py", line 23, in sys_dispatch
  File "/code/compose/cli/docopt_command.py", line 26, in dispatch
  File "/code/compose/cli/main.py", line 170, in perform_command
  File "/code/compose/cli/main.py", line 188, in build
  File "/code/compose/project.py", line 284, in build
  File "/code/compose/service.py", line 731, in build
  File "/code/compose/progress_stream.py", line 15, in stream_output
  File "/code/compose/utils.py", line 131, in split_buffer
  File "/usr/local/lib/python2.7/json/decoder.py", line 369, in decode
ValueError: Extra data: line 2 column 1 - line 98 column 1 (char 4 - 4365)

**Comment by dnephin** [comment]
Could you try it out with a build from master (https://dl.bintray.com/docker-compose/master/)? I think it was fixed by #2400

**Comment by dmoran-epages** [comment]
Yes, it sems to work fine with that thanks.
Will I have to wait for version 1.6 to get get this fix?
Thanks in Advance

**Comment by dnephin** [comment]
It's in the 1.5.2 milestone, so you shouldn't have to wait for 1.6
