### ISSUE TITLE
Latest 1.5.0 docker-compose issue.

### ISSUE THREAD

**Issue by jgasyna** [docker/compose#2333]
I am using docker-compose to spin up a few containers, and I am running into a new issue since the upgrade:  

Stopping foo_1 ... done
Stopping foo_2 ... done
Traceback (most recent call last):
  File "<string>", line 3, in <module>
  File "/compose/compose/cli/main.py", line 54, in main
  File "/compose/compose/cli/docopt_command.py", line 23, in sys_dispatch
  File "/compose/compose/cli/docopt_command.py", line 26, in dispatch
  File "/compose/compose/cli/main.py", line 170, in perform_command
  File "/compose/compose/cli/main.py", line 588, in up
  File "/compose/compose/cli/main.py", line 658, in attach_to_logs
  File "/compose/compose/cli/log_printer.py", line 27, in run
  File "/compose/compose/cli/multiplexer.py", line 35, in loop
UnicodeDecodeError: 'utf8' codec can't decode byte 0xff in position 24: invalid start byte
docker-compose returned -1

Versions:
Docker version 1.9.0, build 76d6bc9
docker-machine version 0.5.0 (04cfa58)
docker-compose version: 1.5.0
Python 2.7.10

Any hints?

**Comment by jgasyna** [comment]
Looks like duplicate to  #2317.  Hopefully this will give you another angle on it.

**Comment by dnephin** [comment]
Yup, I've got a fix in #2326 , it will be in the next release
