### ISSUE TITLE
docker-compose ls fails

### ISSUE THREAD

**Issue by timsuchanek** [docker/compose#2404]
On Mac OSX 10.10.5
go version: go1.5.1 darwin/amd64
docker-compose version: 1.5.1
docker version: 1.9.0

```sh
$ docker-compose ls
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x20 pc=0xad9d2]

goroutine 1 [running]:
github.com/docker/machine/commands.cmdLs(0x820998480, 0x0, 0x0)
        /go/src/github.com/docker/machine/commands/ls.go:95 +0xa52
github.com/docker/machine/commands.fatalOnError.func1(0x820998480)
        /go/src/github.com/docker/machine/commands/commands.go:44 +0x29
github.com/docker/machine/cli.Command.Run(0x5563a0, 0x2, 0x0, 0x0, 0x0, 0x0, 0x0, 0x55e030, 0xd, 0x0, ...)
        /go/src/github.com/docker/machine/cli/command.go:137 +0x1055
github.com/docker/machine/cli.(*App).Run(0x820998240, 0x8208a8260, 0x2, 0x2, 0x0, 0x0)
        /go/src/github.com/docker/machine/cli/app.go:175 +0xfd6
main.main()
        /go/src/github.com/docker/machine/cmd/machine.go:144 +0xcc3

goroutine 5 [syscall]:
os/signal.loop()
        /usr/local/go/src/os/signal/signal_unix.go:22 +0x18
created by os/signal.init.1
        /usr/local/go/src/os/signal/signal_unix.go:28 +0x37

goroutine 7 [select]:
github.com/docker/machine/libmachine/drivers/plugin/localbinary.(*LocalBinaryPlugin).execServer(0x82099b600, 0x0, 0x0)
        /go/src/github.com/docker/machine/libmachine/drivers/plugin/localbinary/plugin.go:194 +0xc86
github.com/docker/machine/libmachine/drivers/plugin/localbinary.(*LocalBinaryPlugin).Serve(0x82099b600, 0x0, 0x0)
        /go/src/github.com/docker/machine/libmachine/drivers/plugin/localbinary/plugin.go:211 +0x2d
github.com/docker/machine/libmachine/drivers/rpc.NewRpcClientDriver.func1(0x82099b600)
        /go/src/github.com/docker/machine/libmachine/drivers/rpc/client_driver.go:58 +0x25
created by github.com/docker/machine/libmachine/drivers/rpc.NewRpcClientDriver
        /go/src/github.com/docker/machine/libmachine/drivers/rpc/client_driver.go:63 +0xcf

goroutine 9 [select]:
github.com/docker/machine/libmachine/drivers/plugin/localbinary.stream(0x820926500, 0x8208b4960, 0x8208b49c0)
        /go/src/github.com/docker/machine/libmachine/drivers/plugin/localbinary/plugin.go:154 +0x37d
created by github.com/docker/machine/libmachine/drivers/plugin/localbinary.(*LocalBinaryPlugin).AttachStream
        /go/src/github.com/docker/machine/libmachine/drivers/plugin/localbinary/plugin.go:170 +0x8e

goroutine 10 [syscall]:
syscall.Syscall(0x3, 0x3, 0x8209b6010, 0xff0, 0x0, 0x0, 0x0)
        /usr/local/go/src/syscall/asm_darwin_amd64.s:16 +0x5
syscall.read(0x3, 0x8209b6010, 0xff0, 0xff0, 0x0, 0x0, 0x0)
        /usr/local/go/src/syscall/zsyscall_darwin_amd64.go:972 +0x5f
syscall.Read(0x3, 0x8209b6010, 0xff0, 0xff0, 0x0, 0x0, 0x0)
        /usr/local/go/src/syscall/syscall_unix.go:160 +0x4d
os.(*File).read(0x8208ca1a8, 0x8209b6010, 0xff0, 0xff0, 0x0, 0x0, 0x0)
        /usr/local/go/src/os/file_unix.go:211 +0x75
os.(*File).Read(0x8208ca1a8, 0x8209b6010, 0xff0, 0xff0, 0x0, 0x0, 0x0)
        /usr/local/go/src/os/file.go:95 +0x8a
bufio.(*Scanner).Scan(0x820926500, 0x0)
        /usr/local/go/src/bufio/scan.go:180 +0x877
github.com/docker/machine/libmachine/drivers/plugin/localbinary.stream.func1(0x820926500, 0x8208b4a20)
        /go/src/github.com/docker/machine/libmachine/drivers/plugin/localbinary/plugin.go:149 +0x25
created by github.com/docker/machine/libmachine/drivers/plugin/localbinary.stream
        /go/src/github.com/docker/machine/libmachine/drivers/plugin/localbinary/plugin.go:152 +0x81

goroutine 11 [select]:
github.com/docker/machine/libmachine/drivers/plugin/localbinary.stream(0x820926580, 0x8208b4a80, 0x8208b4ae0)
        /go/src/github.com/docker/machine/libmachine/drivers/plugin/localbinary/plugin.go:154 +0x37d
created by github.com/docker/machine/libmachine/drivers/plugin/localbinary.(*LocalBinaryPlugin).AttachStream
        /go/src/github.com/docker/machine/libmachine/drivers/plugin/localbinary/plugin.go:170 +0x8e

goroutine 12 [syscall]:
syscall.Syscall(0x3, 0x5, 0x8209b7000, 0x1000, 0x9de, 0x0, 0x0)
        /usr/local/go/src/syscall/asm_darwin_amd64.s:16 +0x5
syscall.read(0x5, 0x8209b7000, 0x1000, 0x1000, 0x9de, 0x0, 0x0)
        /usr/local/go/src/syscall/zsyscall_darwin_amd64.go:972 +0x5f
syscall.Read(0x5, 0x8209b7000, 0x1000, 0x1000, 0x9de, 0x0, 0x0)
        /usr/local/go/src/syscall/syscall_unix.go:160 +0x4d
os.(*File).read(0x8208ca1b8, 0x8209b7000, 0x1000, 0x1000, 0x300d07, 0x0, 0x0)
        /usr/local/go/src/os/file_unix.go:211 +0x75
os.(*File).Read(0x8208ca1b8, 0x8209b7000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /usr/local/go/src/os/file.go:95 +0x8a
bufio.(*Scanner).Scan(0x820926580, 0x8208b4b40)
        /usr/local/go/src/bufio/scan.go:180 +0x877
github.com/docker/machine/libmachine/drivers/plugin/localbinary.stream.func1(0x820926580, 0x8208b4b40)
        /go/src/github.com/docker/machine/libmachine/drivers/plugin/localbinary/plugin.go:149 +0x25
created by github.com/docker/machine/libmachine/drivers/plugin/localbinary.stream
        /go/src/github.com/docker/machine/libmachine/drivers/plugin/localbinary/plugin.go:152 +0x81

goroutine 17 [IO wait]:
net.runtime_pollWait(0x8820a91000, 0x72, 0x8208ae180)
        /usr/local/go/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0x8209d4060, 0x72, 0x0, 0x0)
        /usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0x8209d4060, 0x0, 0x0)
        /usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0x8209d4000, 0x8209e4000, 0x1000, 0x1000, 0x0, 0x8820a50050, 0x8208ae180)
        /usr/local/go/src/net/fd_unix.go:232 +0x23a
net.(*conn).Read(0x8209da000, 0x8209e4000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/net.go:172 +0xe4
bufio.(*Reader).fill(0x8209dc060)
        /usr/local/go/src/bufio/bufio.go:97 +0x1e9
bufio.(*Reader).Read(0x8209dc060, 0x8209ce040, 0x1, 0x9, 0x0, 0x0, 0x0)
        /usr/local/go/src/bufio/bufio.go:207 +0x260
io.ReadAtLeast(0x8820a91138, 0x8209dc060, 0x8209ce040, 0x1, 0x9, 0x1, 0x0, 0x0, 0x0)
        /usr/local/go/src/io/io.go:298 +0xe6
io.ReadFull(0x8820a91138, 0x8209dc060, 0x8209ce040, 0x1, 0x9, 0x8209d20f0, 0x0, 0x0)
        /usr/local/go/src/io/io.go:316 +0x62
encoding/gob.decodeUintReader(0x8820a91138, 0x8209dc060, 0x8209ce040, 0x9, 0x9, 0x0, 0x1, 0x0, 0x0)
        /usr/local/go/src/encoding/gob/decode.go:121 +0x92
encoding/gob.(*Decoder).recvMessage(0x8209d2080, 0x820993bc0)
        /usr/local/go/src/encoding/gob/decoder.go:76 +0x5e
encoding/gob.(*Decoder).decodeTypeSequence(0x8209d2080, 0x638600, 0x8209d2080)
        /usr/local/go/src/encoding/gob/decoder.go:140 +0x47
encoding/gob.(*Decoder).DecodeValue(0x8209d2080, 0x3cfdc0, 0x820a12000, 0x16, 0x0, 0x0)
        /usr/local/go/src/encoding/gob/decoder.go:208 +0x15d
encoding/gob.(*Decoder).Decode(0x8209d2080, 0x3cfdc0, 0x820a12000, 0x0, 0x0)
        /usr/local/go/src/encoding/gob/decoder.go:185 +0x289
net/rpc.(*gobClientCodec).ReadResponseHeader(0x8209d01b0, 0x820a12000, 0x0, 0x0)
        /usr/local/go/src/net/rpc/client.go:223 +0x51
net/rpc.(*Client).input(0x8209dc120)
        /usr/local/go/src/net/rpc/client.go:109 +0xbf
created by net/rpc.NewClientWithCodec
        /usr/local/go/src/net/rpc/client.go:201 +0xd2

goroutine 18 [sleep]:
time.Sleep(0xbebc200)
        /usr/local/go/src/runtime/time.go:59 +0xf9
github.com/docker/machine/libmachine/drivers/rpc.NewRpcClientDriver.func2(0x8209d6100)
        /go/src/github.com/docker/machine/libmachine/drivers/rpc/client_driver.go:91 +0x1dc
created by github.com/docker/machine/libmachine/drivers/rpc.NewRpcClientDriver
        /go/src/github.com/docker/machine/libmachine/drivers/rpc/client_driver.go:94 +0x38a

goroutine 33 [select]:
github.com/docker/machine/libmachine/drivers/plugin/localbinary.(*LocalBinaryPlugin).execServer(0x820a165c0, 0x0, 0x0)
        /go/src/github.com/docker/machine/libmachine/drivers/plugin/localbinary/plugin.go:194 +0xc86
github.com/docker/machine/libmachine/drivers/plugin/localbinary.(*LocalBinaryPlugin).Serve(0x820a165c0, 0x0, 0x0)
        /go/src/github.com/docker/machine/libmachine/drivers/plugin/localbinary/plugin.go:211 +0x2d
github.com/docker/machine/libmachine/drivers/rpc.NewRpcClientDriver.func1(0x820a165c0)
        /go/src/github.com/docker/machine/libmachine/drivers/rpc/client_driver.go:58 +0x25
created by github.com/docker/machine/libmachine/drivers/rpc.NewRpcClientDriver
        /go/src/github.com/docker/machine/libmachine/drivers/rpc/client_driver.go:63 +0xcf

goroutine 34 [select]:
github.com/docker/machine/libmachine/drivers/plugin/localbinary.stream(0x820a56000, 0x820a44420, 0x820a44480)
        /go/src/github.com/docker/machine/libmachine/drivers/plugin/localbinary/plugin.go:154 +0x37d
created by github.com/docker/machine/libmachine/drivers/plugin/localbinary.(*LocalBinaryPlugin).AttachStream
        /go/src/github.com/docker/machine/libmachine/drivers/plugin/localbinary/plugin.go:170 +0x8e

goroutine 35 [select]:
github.com/docker/machine/libmachine/drivers/plugin/localbinary.stream(0x820a56080, 0x820a444e0, 0x820a44540)
        /go/src/github.com/docker/machine/libmachine/drivers/plugin/localbinary/plugin.go:154 +0x37d
created by github.com/docker/machine/libmachine/drivers/plugin/localbinary.(*LocalBinaryPlugin).AttachStream
        /go/src/github.com/docker/machine/libmachine/drivers/plugin/localbinary/plugin.go:170 +0x8e

goroutine 36 [syscall]:
syscall.Syscall(0x3, 0x9, 0x820a55016, 0xfea, 0x1, 0x0, 0x0)
        /usr/local/go/src/syscall/asm_darwin_amd64.s:16 +0x5
syscall.read(0x9, 0x820a55016, 0xfea, 0xfea, 0x1, 0x0, 0x0)
        /usr/local/go/src/syscall/zsyscall_darwin_amd64.go:972 +0x5f
syscall.Read(0x9, 0x820a55016, 0xfea, 0xfea, 0x1, 0x0, 0x0)
        /usr/local/go/src/syscall/syscall_unix.go:160 +0x4d
os.(*File).read(0x820a46030, 0x820a55016, 0xfea, 0xfea, 0x300d07, 0x0, 0x0)
        /usr/local/go/src/os/file_unix.go:211 +0x75
os.(*File).Read(0x820a46030, 0x820a55016, 0xfea, 0xfea, 0x0, 0x0, 0x0)
        /usr/local/go/src/os/file.go:95 +0x8a
bufio.(*Scanner).Scan(0x820a56080, 0x820a445a0)
        /usr/local/go/src/bufio/scan.go:180 +0x877
github.com/docker/machine/libmachine/drivers/plugin/localbinary.stream.func1(0x820a56080, 0x820a445a0)
        /go/src/github.com/docker/machine/libmachine/drivers/plugin/localbinary/plugin.go:149 +0x25
created by github.com/docker/machine/libmachine/drivers/plugin/localbinary.stream
        /go/src/github.com/docker/machine/libmachine/drivers/plugin/localbinary/plugin.go:152 +0x81

goroutine 49 [syscall]:
syscall.Syscall(0x3, 0x7, 0x820a54010, 0xff0, 0x820891cff, 0x0, 0x11ea0)
        /usr/local/go/src/syscall/asm_darwin_amd64.s:16 +0x5
syscall.read(0x7, 0x820a54010, 0xff0, 0xff0, 0x1, 0x0, 0x0)
        /usr/local/go/src/syscall/zsyscall_darwin_amd64.go:972 +0x5f
syscall.Read(0x7, 0x820a54010, 0xff0, 0xff0, 0x4, 0x0, 0x0)
        /usr/local/go/src/syscall/syscall_unix.go:160 +0x4d
os.(*File).read(0x820a46020, 0x820a54010, 0xff0, 0xff0, 0x4fb20, 0x0, 0x0)
        /usr/local/go/src/os/file_unix.go:211 +0x75
os.(*File).Read(0x820a46020, 0x820a54010, 0xff0, 0xff0, 0x820a24000, 0x0, 0x0)
        /usr/local/go/src/os/file.go:95 +0x8a
bufio.(*Scanner).Scan(0x820a56000, 0x0)
        /usr/local/go/src/bufio/scan.go:180 +0x877
github.com/docker/machine/libmachine/drivers/plugin/localbinary.stream.func1(0x820a56000, 0x820a1e2a0)
        /go/src/github.com/docker/machine/libmachine/drivers/plugin/localbinary/plugin.go:149 +0x25
created by github.com/docker/machine/libmachine/drivers/plugin/localbinary.stream
        /go/src/github.com/docker/machine/libmachine/drivers/plugin/localbinary/plugin.go:152 +0x81

goroutine 13 [IO wait]:
net.runtime_pollWait(0x8820a90f40, 0x72, 0x8208ae180)
        /usr/local/go/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0x8208f68b0, 0x72, 0x0, 0x0)
        /usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0x8208f68b0, 0x0, 0x0)
        /usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0x8208f6850, 0x820a6e000, 0x1000, 0x1000, 0x0, 0x8820a50050, 0x8208ae180)
        /usr/local/go/src/net/fd_unix.go:232 +0x23a
net.(*conn).Read(0x8208ca1d8, 0x820a6e000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/net.go:172 +0xe4
bufio.(*Reader).fill(0x8208b4c00)
        /usr/local/go/src/bufio/bufio.go:97 +0x1e9
bufio.(*Reader).Read(0x8208b4c00, 0x8209a7790, 0x1, 0x9, 0x6377c0, 0x0, 0x0)
        /usr/local/go/src/bufio/bufio.go:207 +0x260
io.ReadAtLeast(0x8820a91138, 0x8208b4c00, 0x8209a7790, 0x1, 0x9, 0x1, 0x0, 0x0, 0x0)
        /usr/local/go/src/io/io.go:298 +0xe6
io.ReadFull(0x8820a91138, 0x8208b4c00, 0x8209a7790, 0x1, 0x9, 0x820926770, 0x0, 0x0)
        /usr/local/go/src/io/io.go:316 +0x62
encoding/gob.decodeUintReader(0x8820a91138, 0x8208b4c00, 0x8209a7790, 0x9, 0x9, 0x0, 0x1, 0x0, 0x0)
        /usr/local/go/src/encoding/gob/decode.go:121 +0x92
encoding/gob.(*Decoder).recvMessage(0x820926700, 0x820a7fbc0)
        /usr/local/go/src/encoding/gob/decoder.go:76 +0x5e
encoding/gob.(*Decoder).decodeTypeSequence(0x820926700, 0x638600, 0x820926700)
        /usr/local/go/src/encoding/gob/decoder.go:140 +0x47
encoding/gob.(*Decoder).DecodeValue(0x820926700, 0x3cfdc0, 0x8209d0570, 0x16, 0x0, 0x0)
        /usr/local/go/src/encoding/gob/decoder.go:208 +0x15d
encoding/gob.(*Decoder).Decode(0x820926700, 0x3cfdc0, 0x8209d0570, 0x0, 0x0)
        /usr/local/go/src/encoding/gob/decoder.go:185 +0x289
net/rpc.(*gobClientCodec).ReadResponseHeader(0x8209b48a0, 0x8209d0570, 0x0, 0x0)
        /usr/local/go/src/net/rpc/client.go:223 +0x51
net/rpc.(*Client).input(0x8208b4cc0)
        /usr/local/go/src/net/rpc/client.go:109 +0xbf
created by net/rpc.NewClientWithCodec
        /usr/local/go/src/net/rpc/client.go:201 +0xd2

goroutine 14 [sleep]:
time.Sleep(0xbebc200)
        /usr/local/go/src/runtime/time.go:59 +0xf9
github.com/docker/machine/libmachine/drivers/rpc.NewRpcClientDriver.func2(0x8209a3640)
        /go/src/github.com/docker/machine/libmachine/drivers/rpc/client_driver.go:91 +0x1dc
created by github.com/docker/machine/libmachine/drivers/rpc.NewRpcClientDriver
        /go/src/github.com/docker/machine/libmachine/drivers/rpc/client_driver.go:94 +0x38a

goroutine 15 [select]:
github.com/docker/machine/libmachine/drivers/plugin/localbinary.(*LocalBinaryPlugin).execServer(0x820a86140, 0x0, 0x0)
        /go/src/github.com/docker/machine/libmachine/drivers/plugin/localbinary/plugin.go:194 +0xc86
github.com/docker/machine/libmachine/drivers/plugin/localbinary.(*LocalBinaryPlugin).Serve(0x820a86140, 0x0, 0x0)
        /go/src/github.com/docker/machine/libmachine/drivers/plugin/localbinary/plugin.go:211 +0x2d
github.com/docker/machine/libmachine/drivers/rpc.NewRpcClientDriver.func1(0x820a86140)
        /go/src/github.com/docker/machine/libmachine/drivers/rpc/client_driver.go:58 +0x25
created by github.com/docker/machine/libmachine/drivers/rpc.NewRpcClientDriver
        /go/src/github.com/docker/machine/libmachine/drivers/rpc/client_driver.go:63 +0xcf

goroutine 16 [select]:
github.com/docker/machine/libmachine/drivers/plugin/localbinary.stream(0x820926780, 0x8208b5260, 0x8208b52c0)
        /go/src/github.com/docker/machine/libmachine/drivers/plugin/localbinary/plugin.go:154 +0x37d
created by github.com/docker/machine/libmachine/drivers/plugin/localbinary.(*LocalBinaryPlugin).AttachStream
        /go/src/github.com/docker/machine/libmachine/drivers/plugin/localbinary/plugin.go:170 +0x8e

goroutine 65 [select]:
github.com/docker/machine/libmachine/drivers/plugin/localbinary.stream(0x820926800, 0x8208b5320, 0x8208b5380)
        /go/src/github.com/docker/machine/libmachine/drivers/plugin/localbinary/plugin.go:154 +0x37d
created by github.com/docker/machine/libmachine/drivers/plugin/localbinary.(*LocalBinaryPlugin).AttachStream
        /go/src/github.com/docker/machine/libmachine/drivers/plugin/localbinary/plugin.go:170 +0x8e

goroutine 66 [syscall]:
syscall.Syscall(0x3, 0xc, 0x820a88000, 0x1000, 0xc26, 0x0, 0x0)
        /usr/local/go/src/syscall/asm_darwin_amd64.s:16 +0x5
syscall.read(0xc, 0x820a88000, 0x1000, 0x1000, 0xc26, 0x0, 0x0)
        /usr/local/go/src/syscall/zsyscall_darwin_amd64.go:972 +0x5f
syscall.Read(0xc, 0x820a88000, 0x1000, 0x1000, 0xc26, 0x0, 0x0)
        /usr/local/go/src/syscall/syscall_unix.go:160 +0x4d
os.(*File).read(0x8208ca218, 0x820a88000, 0x1000, 0x1000, 0x300d07, 0x0, 0x0)
        /usr/local/go/src/os/file_unix.go:211 +0x75
os.(*File).Read(0x8208ca218, 0x820a88000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /usr/local/go/src/os/file.go:95 +0x8a
bufio.(*Scanner).Scan(0x820926800, 0x8208b53e0)
        /usr/local/go/src/bufio/scan.go:180 +0x877
github.com/docker/machine/libmachine/drivers/plugin/localbinary.stream.func1(0x820926800, 0x8208b53e0)
        /go/src/github.com/docker/machine/libmachine/drivers/plugin/localbinary/plugin.go:149 +0x25
created by github.com/docker/machine/libmachine/drivers/plugin/localbinary.stream
        /go/src/github.com/docker/machine/libmachine/drivers/plugin/localbinary/plugin.go:152 +0x81

goroutine 19 [syscall]:
syscall.Syscall(0x3, 0xa, 0x820a6f010, 0xff0, 0x8209d0570, 0x16, 0x3cfdc0)
        /usr/local/go/src/syscall/asm_darwin_amd64.s:16 +0x5
syscall.read(0xa, 0x820a6f010, 0xff0, 0xff0, 0x31e349, 0x0, 0x0)
        /usr/local/go/src/syscall/zsyscall_darwin_amd64.go:972 +0x5f
syscall.Read(0xa, 0x820a6f010, 0xff0, 0xff0, 0x8209d0570, 0x0, 0x0)
        /usr/local/go/src/syscall/syscall_unix.go:160 +0x4d
os.(*File).read(0x8208ca208, 0x820a6f010, 0xff0, 0xff0, 0x3cfdc0, 0x0, 0x0)
        /usr/local/go/src/os/file_unix.go:211 +0x75
os.(*File).Read(0x8208ca208, 0x820a6f010, 0xff0, 0xff0, 0x0, 0x0, 0x0)
        /usr/local/go/src/os/file.go:95 +0x8a
bufio.(*Scanner).Scan(0x820926780, 0x0)
        /usr/local/go/src/bufio/scan.go:180 +0x877
github.com/docker/machine/libmachine/drivers/plugin/localbinary.stream.func1(0x820926780, 0x8209dc7e0)
        /go/src/github.com/docker/machine/libmachine/drivers/plugin/localbinary/plugin.go:149 +0x25
created by github.com/docker/machine/libmachine/drivers/plugin/localbinary.stream
        /go/src/github.com/docker/machine/libmachine/drivers/plugin/localbinary/plugin.go:152 +0x81

goroutine 37 [IO wait]:
net.runtime_pollWait(0x8820a90e80, 0x72, 0x8208ae180)
        /usr/local/go/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0x8209d47d0, 0x72, 0x0, 0x0)
        /usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0x8209d47d0, 0x0, 0x0)
        /usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0x8209d4770, 0x820a98000, 0x1000, 0x1000, 0x0, 0x8820a50050, 0x8208ae180)
        /usr/local/go/src/net/fd_unix.go:232 +0x23a
net.(*conn).Read(0x820a46050, 0x820a98000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/net.go:172 +0xe4
bufio.(*Reader).fill(0x820a44660)
        /usr/local/go/src/bufio/bufio.go:97 +0x1e9
bufio.(*Reader).Read(0x820a44660, 0x820a42180, 0x1, 0x9, 0x0, 0x0, 0x0)
        /usr/local/go/src/bufio/bufio.go:207 +0x260
io.ReadAtLeast(0x8820a91138, 0x820a44660, 0x820a42180, 0x1, 0x9, 0x1, 0x0, 0x0, 0x0)
        /usr/local/go/src/io/io.go:298 +0xe6
io.ReadFull(0x8820a91138, 0x820a44660, 0x820a42180, 0x1, 0x9, 0x820a56170, 0x0, 0x0)
        /usr/local/go/src/io/io.go:316 +0x62
encoding/gob.decodeUintReader(0x8820a91138, 0x820a44660, 0x820a42180, 0x9, 0x9, 0x0, 0x1, 0x0, 0x0)
        /usr/local/go/src/encoding/gob/decode.go:121 +0x92
encoding/gob.(*Decoder).recvMessage(0x820a56100, 0x820a7bbc0)
        /usr/local/go/src/encoding/gob/decoder.go:76 +0x5e
encoding/gob.(*Decoder).decodeTypeSequence(0x820a56100, 0x638600, 0x820a56100)
        /usr/local/go/src/encoding/gob/decoder.go:140 +0x47
encoding/gob.(*Decoder).DecodeValue(0x820a56100, 0x3cfdc0, 0x820a305d0, 0x16, 0x0, 0x0)
        /usr/local/go/src/encoding/gob/decoder.go:208 +0x15d
encoding/gob.(*Decoder).Decode(0x820a56100, 0x3cfdc0, 0x820a305d0, 0x0, 0x0)
        /usr/local/go/src/encoding/gob/decoder.go:185 +0x289
net/rpc.(*gobClientCodec).ReadResponseHeader(0x820a12900, 0x820a305d0, 0x0, 0x0)
        /usr/local/go/src/net/rpc/client.go:223 +0x51
net/rpc.(*Client).input(0x820a44720)
        /usr/local/go/src/net/rpc/client.go:109 +0xbf
created by net/rpc.NewClientWithCodec
        /usr/local/go/src/net/rpc/client.go:201 +0xd2

goroutine 38 [sleep]:
time.Sleep(0xbebc200)
        /usr/local/go/src/runtime/time.go:59 +0xf9
github.com/docker/machine/libmachine/drivers/rpc.NewRpcClientDriver.func2(0x820a40560)
        /go/src/github.com/docker/machine/libmachine/drivers/rpc/client_driver.go:91 +0x1dc
created by github.com/docker/machine/libmachine/drivers/rpc.NewRpcClientDriver
        /go/src/github.com/docker/machine/libmachine/drivers/rpc/client_driver.go:94 +0x38a

goroutine 50 [chan receive]:
github.com/docker/machine/commands.attemptGetHostState(0x8208b44e0, 0x820a1e360)
        /go/src/github.com/docker/machine/commands/ls.go:260 +0x158
created by github.com/docker/machine/commands.getHostState
        /go/src/github.com/docker/machine/commands/ls.go:286 +0x6f

goroutine 52 [chan receive]:
net/rpc.(*Client).Call(0x8208b4cc0, 0x5a6020, 0x16, 0x3e9a40, 0x808728, 0x3d3480, 0x820a3a4c0, 0x0, 0x0)
        /usr/local/go/src/net/rpc/client.go:315 +0xcd
github.com/docker/machine/libmachine/drivers/rpc.(*InternalClient).Call(0x8209a3620, 0x5a6020, 0x16, 0x3e9a40, 0x808728, 0x3d3480, 0x820a3a4c0, 0x0, 0x0)
        /go/src/github.com/docker/machine/libmachine/drivers/rpc/client_driver.go:40 +0xfd
github.com/docker/machine/libmachine/drivers/rpc.(*RpcClientDriver).rpcStringCall(0x8209a3640, 0x5a6020, 0x16, 0x0, 0x0, 0x0, 0x0)
        /go/src/github.com/docker/machine/libmachine/drivers/rpc/client_driver.go:148 +0xe0
github.com/docker/machine/libmachine/drivers/rpc.(*RpcClientDriver).GetURL(0x8209a3640, 0x0, 0x0, 0x0, 0x0)
        /go/src/github.com/docker/machine/libmachine/drivers/rpc/client_driver.go:193 +0x4e
github.com/docker/machine/libmachine/host.(*Host).GetURL(0x8208b44e0, 0x0, 0x0, 0x0, 0x0)
        /go/src/github.com/docker/machine/libmachine/host/host.go:149 +0x52
github.com/docker/machine/commands.attemptGetHostState.func2(0x8208b44e0, 0x820a1e480)
        /go/src/github.com/docker/machine/commands/ls.go:247 +0x52
created by github.com/docker/machine/commands.attemptGetHostState
        /go/src/github.com/docker/machine/commands/ls.go:257 +0xe8


```

**Comment by dnephin** [comment]
This stack trace is from `docker-machine` not `docker-compose` (you can see the name in the stack trace). There is also no `docker-compose ls` command.

Did you accidentally rename the binary to the wrong name?

Either way, I think the right place to report this is on the docker/machine repo.
