### ISSUE TITLE
Dependency for functools32 not installed by pip

### ISSUE THREAD

**Issue by Yajo** [docker/compose#2425]
Installing docker-compose in CentOS under a virtualenv fails with this:

```
Traceback (most recent call last):
  File "/opt/docker/odoo-grupoesoc/pyenv/bin/docker-compose", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/opt/docker/odoo-grupoesoc/pyenv/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3095, in <module>
    @_call_aside
  File "/opt/docker/odoo-grupoesoc/pyenv/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3081, in _call_aside
    f(*args, **kwargs)
  File "/opt/docker/odoo-grupoesoc/pyenv/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3108, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/opt/docker/odoo-grupoesoc/pyenv/lib/python2.7/site-packages/pkg_resources/__init__.py", line 658, in _build_master
    ws.require(__requires__)
  File "/opt/docker/odoo-grupoesoc/pyenv/lib/python2.7/site-packages/pkg_resources/__init__.py", line 959, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/opt/docker/odoo-grupoesoc/pyenv/lib/python2.7/site-packages/pkg_resources/__init__.py", line 846, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'functools32' distribution was not found and is required by jsonschema
```

Steps to reproduce:

```
virtualenv-2.7 pyenv
source ./pyenv/bin/activate
pip install docker-compose
docker-compose pull
```

Workaround: `pip install functools32`

Related to https://github.com/docker/compose/issues/2222?

**Comment by dnephin** [comment]
You can find out more about the issue here: https://github.com/Julian/jsonschema/issues/233

Basically you're using a version of pip that is too old, so it doesn't know to install all the dependencies.  Upgrading pip should work.

**Comment by dnephin** [comment]
I'll add a note to our install section about the required version as pip.
