### ISSUE TITLE
docker-compose missing docker.utils.ports ?

### ISSUE THREAD

**Issue by rduivenvoorde** [docker/compose#2433]
On Debian Testing here.

$ docker -v
Docker version 1.8.3, build f4bf5c7

apt-cache show docker-compose
Package: docker-compose
Version: 1.5.1-1

Trying to run docker-compose (was running fine some time ago):

<pre>
docker-compose
Traceback (most recent call last):
  File "/usr/bin/docker-compose", line 9, in <module>
    load_entry_point('docker-compose==1.5.1', 'console_scripts', 'docker-compose')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 558, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2682, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2355, in load
    return self.resolve()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2361, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python2.7/dist-packages/compose/cli/main.py", line 16, in <module>
    from ..config import ConfigurationError
  File "/usr/lib/python2.7/dist-packages/compose/config/__init__.py", line 2, in <module>
    from .config import ConfigurationError
  File "/usr/lib/python2.7/dist-packages/compose/config/config.py", line 14, in <module>
    from .validation import validate_against_fields_schema
  File "/usr/lib/python2.7/dist-packages/compose/config/validation.py", line 7, in <module>
    from docker.utils.ports import split_port
ImportError: No module named ports
</pre>

Is  docker.utils.ports supposed to be provided by python-docker?

apt-cache show python-docker
Package: python-docker
Version: 1.5.0-1

Does not look like I'm running old stuff is it?

Any ideas?

**Comment by dnephin** [comment]
It should be provided by `docker-py`, which I guess is called `python-docker` in debian. 1.5.0 should be the latest version, and that module has existed since version 1.2.0.

I think this is a bug with the debian packaging, which is not something we maintain.  The install options we support are here: http://docs.docker.com/compose/install/

I think you might need to open an issue on the debian packaging bug tracker.

**Comment by rduivenvoorde** [comment]
@dnephin closing this one, as it was my installing mess that gave rise to this problem.

I fixed my problem thanks to the hints of the Debian packagers:

- removed docker, docker-dompose, python-docker, python-dockerpty
- updatedb;locate docker
- and found there was still a docker egg/package in
/usr/local/lib/python2.7/site-packages
- apparently I installed docker python stuff using pip some time ago...
- after removing that stuff and reinstalling all is working again.

Thanks for your time
