### ISSUE TITLE
Multiple errors when trying to use compose on win 

### ISSUE THREAD

**Issue by aldarund** [docker/compose#2469]
Im trying to launch compose on win 10 without any luck. 
docker-compose version: 1.5.1
Docker version 1.9.1, build a34a1d5  ( all installed via docker-toolbox )
First error is following. I have set  following env vars: DOCKER_CERT_PATH='C:\Users\ShapeR\.docker\machine\machines\default'  ( which is a valid path and keys are there ca.pem, cert.pem, key.pem ).
DOCKER_TLS_VERIFY="1"
When i try to launch docker-compose up i get following error:
C:\Dev\PycharmProjects\django-rentapplication>docker-compose up
Traceback (most recent call last):
  File "<string>", line 3, in <module>
  File "C:\projects\compose\compose\cli\main.py", line 54, in main
  File "C:\projects\compose\compose\cli\docopt_command.py", line 23, in sys_dispatch
  File "C:\projects\compose\compose\cli\docopt_command.py", line 26, in dispatch
  File "C:\projects\compose\compose\cli\main.py", line 169, in perform_command
  File "C:\projects\compose\compose\cli\command.py", line 54, in project_from_options
  File "C:\projects\compose\compose\cli\command.py", line 91, in get_project
  File "C:\projects\compose\compose\cli\command.py", line 71, in get_client
  File "C:\projects\compose\compose\cli\docker_client.py", line 23, in docker_client
  File "c:\projects\compose\venv\lib\site-packages\docker\utils\utils.py", line 412, in kwargs_from_env
  File "c:\projects\compose\venv\lib\site-packages\docker\tls.py", line 46, in __init__
docker.errors.TLSParameterError: Path to a certificate and key files must be provided through the client_config param. TLS configurations should map the Docker CLI client configurations. See http://docs.docker.com/examples/https/ for API details.
docker-compose returned -1

Seems like it doesnt find a keys where they are. Also paths in stacktrace are non existent. ( like C:\projects\compose\ - there is no such folder on my pc)
I looked into sources of compose and figured out if i take out DOCKER_TLS_VERIFY it should run fine. I did it. And get a new error.
C:\Dev\PycharmProjects\django-rentapplication>docker-compose up
Traceback (most recent call last):
  File "<string>", line 3, in <module>
  File "C:\projects\compose\compose\cli\main.py", line 54, in main
  File "C:\projects\compose\compose\cli\docopt_command.py", line 23, in sys_dispatch
  File "C:\projects\compose\compose\cli\docopt_command.py", line 26, in dispatch
  File "C:\projects\compose\compose\cli\main.py", line 169, in perform_command
  File "C:\projects\compose\compose\cli\command.py", line 54, in project_from_options
  File "C:\projects\compose\compose\cli\command.py", line 91, in get_project
  File "C:\projects\compose\compose\cli\command.py", line 71, in get_client
  File "C:\projects\compose\compose\cli\docker_client.py", line 28, in docker_client
  File "c:\projects\compose\venv\lib\site-packages\docker\client.py", line 58, in __init__
  File "c:\projects\compose\venv\lib\site-packages\docker\utils\utils.py", line 336, in parse_host
docker.errors.DockerException: Invalid bind address protocol: "tcp://192.168.99.100:2376"

Which is totally mystery for me, since in utils.py that i find on my disk parse_host is on different line and dont see how it can not strip tcp:// which it should..
But then again i found if i strip tcp:// from addres it should work again. 
But again no luck. New error.

C:\Dev\PycharmProjects\django-rentapplication>docker-compose up
Traceback (most recent call last):
  File "<string>", line 3, in <module>
  File "C:\projects\compose\compose\cli\main.py", line 54, in main
  File "C:\projects\compose\compose\cli\docopt_command.py", line 23, in sys_dispatch
  File "C:\projects\compose\compose\cli\docopt_command.py", line 26, in dispatch
  File "C:\projects\compose\compose\cli\main.py", line 169, in perform_command
  File "C:\projects\compose\compose\cli\command.py", line 54, in project_from_options
  File "C:\projects\compose\compose\cli\command.py", line 91, in get_project
  File "C:\projects\compose\compose\cli\command.py", line 71, in get_client
  File "C:\projects\compose\compose\cli\docker_client.py", line 28, in docker_client
  File "c:\projects\compose\venv\lib\site-packages\docker\client.py", line 58, in __init__
  File "c:\projects\compose\venv\lib\site-packages\docker\utils\utils.py", line 357, in parse_host
docker.errors.DockerException: ('Invalid port: %s', '"192.168.99.100:2376"')
docker-compose returned -1

And at this point i totally lost since don't see how this could happen becvause from sources that i look into its not possible ( well like any previous errors too..) and neither i see how to solve this.

**Comment by aldarund** [comment]
nvm, my bad. " dont need to be in env vars. Thats how docker tells me to add them but it apparently for linux

**Comment by aanand** [comment]
Thanks for reporting! We should definitely:

- make this clear in the docs so other people don't trip up
- show a better error message

**Comment by aanand** [comment]
Could you help us out by describing the install process you went through? e.g.

- Did you install via Toolbox or some other method?
- Did you use the Docker Quickstart Terminal, PowerShell or cmd.exe to run the commands?
- What documentation did you follow?

**Comment by aldarund** [comment]
i installed via toolbox.
Basically the problem is that when running on Win when i launch docker-machine env default ( which was given me when by docker when i was unable to connect ) 
So i run it  ( in cmd) and got following:
>docker-machine env default
export DOCKER_TLS_VERIFY="1"
export DOCKER_HOST="tcp://192.168.99.100:2376"
export DOCKER_CERT_PATH="C:\Users\ShapeR\.docker\machine\machines\default"
export DOCKER_MACHINE_NAME="default"
# Run this command to configure your shell:
# eval "$(docker-machine env default)"

Which is obviously command not for cmd. Then i changed export to set ( because of win) but forgot that there no need for " after = in windows.
Quickstart terminal doesnt work for me. 
Machine default already exists in VirtualBox.
Starting machine default...
Error setting up host only network on machine start: C:\Program Files\Oracle\VirtualBox\VBoxManage.exe modifyvm default --nic2 hostonly --nictype2 82540EM --nicpromisc2 deny --hostonlyadapter2 VirtualBox Host-Only Ethernet Adapter #2 --cableconnected2 on failed:
VBoxManage.exe: error: Code E_FAIL (0x80004005) - Unspecified error (extended info not available)
VBoxManage.exe: error: Context: "LockMachine(a->session, LockType_Write)" at line 493 of file VBoxManageModifyVM.cpp
Looks like something went wrong... Press any key to continue...

**Comment by aanand** [comment]
ping @ehazlett @nathanleclaire - is this a known VirtualBox issue?

**Comment by nathanleclaire** [comment]
VirtualBox host only networking does fall over all the time, so in some sense, yes.  That said, it would be good to have an issue on Machine repo for this with more information about OS version, VirtualBox version, etc.

You can use `--shell cmd` option for `env` to specify `cmd`-style output specifically.  Detecting shell correctly in all cases is pretty difficult.

**Comment by rafaelri** [comment]
I was having a similar problem and stumbled upon this issue. In my case, after trying what @aldarund I noticed that in my case the certificates were in the wrong location, I sincerely don't know why since I've just downloaded Toolbox and installed everything from it (Docker version 1.9.1, build a34a1d5 and docker-compose version 1.5.2, build e5cf49d). Also it seems strange since the command line suggested by docker-machine default env --shell cmd reports the wrong folder for the certificates also (instead of being on Users\myuser\.docker\machine\machines\default they were on Users\myuser\.docker\machine ... after setting the DOCKER_CERT_PATH to the machine folder instead of the default subfolder it worked fine.

**Comment by gregd-icesoft** [comment]
I'm having the above issue, but it's not clear to me from the above what the solution was. 

> docker-machine env default gives: 
export DOCKER_TLS_VERIFY="1"
export DOCKER_HOST="tcp://192.168.99.100:2376"
export DOCKER_CERT_PATH="C:\Users\redacted\.docker\machine\machines\default"
export DOCKER_MACHINE_NAME="default"
# Run this command to configure your shell:
# eval "$(C:\Program Files\DockerToolbox\docker-machine.exe env default)"

The DOCKER_CERT_PATH does indeed point to server.pem and server-key.pem It did not after my install but I was able to generate them with: 
docker-machine regenerate-certs default

**Comment by yaacovCR** [comment]
What works for me when using Docker Toolbox is manually changing the endpoint to the default VirtualBox virtual machine ip address within `prisma.yml`:

`endpoint: http://192.168.99.100:4466
`
