### ISSUE TITLE
Problem when using docker-compose with docker environment variables for remote host with TLS

### ISSUE THREAD

**Issue by drywolf** [docker/compose#2634]
I am trying to use docker-compose to control a remote docker host. I set the following environment variables on the client machine to use the docker remote-host:

```
export DOCKER_CERT_PATH=/vagrant/docker
export DOCKER_TLS_VERIFY=1
export DOCKER_HOST=my-docker-vm.cloudapp.azure.com:2376
```

The docker CLI works just fine with the configuration & certificates, but the docker-compose CLI throws the following error:

```
vagrant@my-docker-vm:/vagrant$ docker-compose stop
Traceback (most recent call last):
File "<string>", line 3, in <module>
  File "/code/compose/cli/main.py", line 54, in main
  File "/code/compose/cli/docopt_command.py", line 23, in sys_dispatch
  File "/code/compose/cli/docopt_command.py", line 26, in dispatch
  File "/code/compose/cli/main.py", line 168, in perform_command
  File "/code/compose/cli/command.py", line 54, in project_from_options
  File "/code/compose/cli/command.py", line 91, in get_project
  File "/code/compose/cli/command.py", line 71, in get_client
  File "/code/compose/cli/docker_client.py", line 28, in docker_client
  File "/code/.tox/py27/lib/python2.7/site-packages/docker/client.py", line 50, in __init__
  docker.errors.TLSParameterError: If using TLS, the base_url argument must begin with "https://".. TLS configurations should map the Docker CLI client configurations. See http://docs.docker.com/examples/https/ for API details.
  docker-compose returned -1
```

**Comment by dnephin** [comment]
Does it work if you make the host `https://my-docker-vm.cloudapp.azure.com:2376` ?

**Comment by drywolf** [comment]
yes that fixes the above problem in docker-compose, but then the docker CLI complains

    Invalid bind address format: https://my-docker-vm.cloudapp.azure.com:2376

Looks like there is an inconsistent behavior in how docker and docker-compose handle the DOCKER_HOST variable ?

**Comment by dnephin** [comment]
Sounds like it. Would you mind opening this issue on https://github.com/docker/docker-py ? That's where the error is coming from. The only change we can make in compose is to upgrade docker-py once it's fixed.

**Comment by dennis-bell** [comment]
@drywolf could you share the issue# at https://github.com/docker/docker-py? am having the same issue.

**Comment by drywolf** [comment]
@dennis-bell I created an issue at docker-py (also linking back here) for further discussion.

**Comment by shin-** [comment]
docker/docker-py#911
