### ISSUE TITLE
SSL error: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:581) with docker 1.9.0 client and server

### ISSUE THREAD

**Issue by yun-wang** [docker/compose#2668]
Server:
- Ubuntu
- Docker 1.9.0

Client:
- Ubuntu 14.04.2 LTS
- kernel 3.13.0-55-generic
- Docker client 1.9.0
- docker-compose version 1.5.2, build 7240ff3
- `DOCKER_TLS_VERIFY=1`
- `DOCKER_HOST=tcp://<host>`
- `DOCKER_CERT_PATH=<path to certs>`

Certs have been working well with `docker cli` to remote docker server.
`curl https://<host>/version --cacert ca.pem --cert cert.pem --key key.pem` also works well with the certs.

Using `docker-compose` gives an SSL error:

```
$ docker-compose up
ERROR: SSL error: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:581)
```

Issue happens after setting `DOCKER_TLS_VERIFY`, `DOCKER_HOST`, and `DOCKER_CERT_PATH`.

**Comment by yun-wang** [comment]
Installed `docker-compose` using `curl`
OpenSSL version 1.0.1f

**Comment by yun-wang** [comment]
Tried the development version of docker-compose (no change to the source code), the certs worked with Python3, but not Python2.

Information about the config that worked:
```
compose.cli.command.get_client: docker-compose version 1.6.0dev, build unknown
docker-py version: 1.6.0
CPython version: 3.5.0b3
OpenSSL version: OpenSSL 0.9.8zg 14 July 2015
```

Didn't work with:
```
docker-compose version 1.6.0dev, build unknown
docker-py version: 1.6.0
CPython version: 2.7.6
OpenSSL version: OpenSSL 1.0.1f 6 Jan 2014
```

Error when running with Python2:
```
/usr/local/lib/python2.7/dist-packages/requests-2.7.0-py2.7.egg/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
Traceback (most recent call last):
  File "/usr/local/bin/docker-compose", line 9, in <module>
    load_entry_point('docker-compose==1.6.0.dev0', 'console_scripts', 'docker-compose')()
  File "/home/yun/Docker/compose/compose/cli/main.py", line 54, in main
    command.sys_dispatch()
  File "/home/yun/Docker/compose/compose/cli/docopt_command.py", line 23, in sys_dispatch
    self.dispatch(sys.argv[1:], None)
  File "/home/yun/Docker/compose/compose/cli/docopt_command.py", line 26, in dispatch
    self.perform_command(*self.parse(argv, global_options))
  File "/home/yun/Docker/compose/compose/cli/main.py", line 171, in perform_command
    project = project_from_options(self.base_dir, options)
  File "/home/yun/Docker/compose/compose/cli/command.py", line 52, in project_from_options
    verbose=options.get('--verbose'),
  File "/home/yun/Docker/compose/compose/cli/command.py", line 85, in get_project
    client = get_client(verbose=verbose, version=api_version)
  File "/home/yun/Docker/compose/compose/cli/command.py", line 68, in get_client
    version_info = six.iteritems(client.version())
  File "/usr/local/lib/python2.7/dist-packages/docker_py-1.6.0-py2.7.egg/docker/api/daemon.py", line 78, in version
    return self._result(self._get(url), json=True)
  File "/usr/local/lib/python2.7/dist-packages/docker_py-1.6.0-py2.7.egg/docker/client.py", line 110, in _get
    return self.get(url, **self._set_request_timeout(kwargs))
  File "/usr/local/lib/python2.7/dist-packages/requests-2.7.0-py2.7.egg/requests/sessions.py", line 477, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests-2.7.0-py2.7.egg/requests/sessions.py", line 465, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests-2.7.0-py2.7.egg/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests-2.7.0-py2.7.egg/requests/adapters.py", line 431, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: [Errno 1] _ssl.c:510: error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed
```

**Comment by yun-wang** [comment]
After running `pip install --upgrade ndg-httpsclient` according to [here](https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning), I was able to get rid of the `InsecurePlatformWarning`, but now I get a different SSLError when running `docker-compose`:

```
Traceback (most recent call last):
  File "/usr/local/bin/docker-compose", line 9, in <module>
    load_entry_point('docker-compose', 'console_scripts', 'docker-compose')()
  File "/home/yun/Docker/compose/compose/cli/main.py", line 54, in main
    command.sys_dispatch()
  File "/home/yun/Docker/compose/compose/cli/docopt_command.py", line 23, in sys_dispatch
    self.dispatch(sys.argv[1:], None)
  File "/home/yun/Docker/compose/compose/cli/docopt_command.py", line 26, in dispatch
    self.perform_command(*self.parse(argv, global_options))
  File "/home/yun/Docker/compose/compose/cli/main.py", line 171, in perform_command
    project = project_from_options(self.base_dir, options)
  File "/home/yun/Docker/compose/compose/cli/command.py", line 52, in project_from_options
    verbose=options.get('--verbose'),
  File "/home/yun/Docker/compose/compose/cli/command.py", line 85, in get_project
    client = get_client(verbose=verbose, version=api_version)
  File "/home/yun/Docker/compose/compose/cli/command.py", line 68, in get_client
    version_info = six.iteritems(client.version())
  File "/usr/local/lib/python2.7/dist-packages/docker_py-1.6.0-py2.7.egg/docker/api/daemon.py", line 78, in version
    return self._result(self._get(url), json=True)
  File "/usr/local/lib/python2.7/dist-packages/docker_py-1.6.0-py2.7.egg/docker/client.py", line 110, in _get
    return self.get(url, **self._set_request_timeout(kwargs))
  File "/usr/local/lib/python2.7/dist-packages/requests-2.7.0-py2.7.egg/requests/sessions.py", line 477, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests-2.7.0-py2.7.egg/requests/sessions.py", line 465, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests-2.7.0-py2.7.egg/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests-2.7.0-py2.7.egg/requests/adapters.py", line 431, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: [Errno bad handshake] [('SSL routines', 'SSL3_GET_SERVER_CERTIFICATE', 'certificate verify failed')]
```

**Comment by czerasz** [comment]
I encounter similar issues while using GitLab's CI and a CoreOS instance.

Here is my `.gitlab-ci.yml`:

```
image: docker:latest

services:
  - docker:dind

stages:
  - build
  - deploy

...

deploy:
  stage: deploy
  variables:
    DOCKER_TLS_VERIFY: "1"
    DOCKER_HOST: "tcp://${SOME_IP}>:2376"
    DOCKER_CERT_PATH: "/.docker/some-path"
  script:
    # Install docker-compose
    - apk add --update python py-pip python-dev && pip install docker-compose
    # Prepare TLS from environment variables
    - mkdir -p /.docker/some-path/
    - echo "$DOCKER_CI_CERTIFICATE_CA_PEM" > /.docker/some-path/ca.pem
    - echo "$DOCKER_CI_CERTIFICATE_CERT_PEM" > /.docker/some-path/cert.pem
    - echo "$DOCKER_CI_CERTIFICATE_KEY_PEM" > /.docker/some-path/key.pem
    - docker info
    # Login to the GitLab's Docker Registry
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    # Pull the blog image
    - docker pull $CI_REGISTRY_IMAGE:blog_${CI_COMMIT_REF_SLUG}
    # Deploy
    - docker-compose up -d --force-recreate blog
```

> **NOTE**
> <br/>The `.gitlab-ci.yml` is used as an example. One could easily reproduce this locally.

From the jobs log I see that the Docker connection was established successfully:

```
$ docker info
Containers: 7
 Running: 6
 Paused: 0
 Stopped: 1
Images: 29
Server Version: 1.12.6
Storage Driver: overlay
 Backing Filesystem: extfs
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: null overlay host bridge
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: 
containerd version: 
runc version: 
init version: 
Security Options:
 seccomp
 selinux
Kernel Version: 4.9.16-coreos-r1
Operating System: Container Linux by CoreOS 1298.7.0 (Ladybug)
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 492.9 MiB
Name: server-01
ID: TTLD:...
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

But the `docker-compose` command returns an error:

```
$ docker-compose up -d --force-recreate blog
SSL error: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:661)
```

If I change the last line of `.gitlab-ci.yml` from:

```
- docker-compose up -d --force-recreate blog
```

to:

```
- docker-compose --tlscacert /.docker/some-path/ca.pem --tlscert /.docker/some-path/cert.pem --tlskey /.docker/some-path/key.pem up -d --force-recreate blog
```

Everything works fine but I got a lot of:

```
/usr/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py:838: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/security.html
  InsecureRequestWarning)
...
```

**Comment by mesutayata** [comment]
I have encountered the same problem. First I though it is because the OpenSSL version differences (Pyhton had 1.0.2 but OS had 0.9.8) I made them both 1.0.2 but it still did not work.
I have solved my problem by simply ssh to docker and then check my certificate in authorized keys and update it. Interestingly somehow it was a wrong certificate there.

Follow these steps please:

`boot2docker ssh`
`docker@boot2docker:~$ cat .ssh/authorized_keys`

Check if this certificate is really the certificate from your computer. If not just copy yours in to this file and save it. Then just run:

`docker-compose up`

This worked for me and hope that it helps.

**Comment by zealotous** [comment]
I have solved this issue by running `update-ca-certificates` command on debian 8
