### ISSUE TITLE
Error "Invalid bind address format: [2001:6b8:1:10::10]:2376"

### ISSUE THREAD

**Issue by narqo** [docker/compose#2879]
Looks like docker-compose doesn't properly parse `DOCKER_HOST` set to IPv6 address.

```
› env | grep DOCKER

DOCKER_CERT_PATH=/Users/varankinv/.docker/machine/machines/os1f
DOCKER_HOST=tcp://[2001:6b8:1:10::10]:2376
DOCKER_MACHINE_NAME=os1f
DOCKER_TLS_VERIFY=1

› docker-compose -f docker/docker-compose.yml build

Traceback (most recent call last):
  File "<string>", line 3, in <module>
  File "/compose/compose/cli/main.py", line 55, in main
  File "/compose/compose/cli/docopt_command.py", line 23, in sys_dispatch
  File "/compose/compose/cli/docopt_command.py", line 26, in dispatch
  File "/compose/compose/cli/main.py", line 172, in perform_command
  File "/compose/compose/cli/command.py", line 52, in project_from_options
  File "/compose/compose/cli/command.py", line 85, in get_project
  File "/compose/compose/cli/command.py", line 66, in get_client
  File "/compose/compose/cli/docker_client.py", line 37, in docker_client
  File "/compose/venv/lib/python2.7/site-packages/docker/client.py", line 58, in __init__
  File "/compose/venv/lib/python2.7/site-packages/docker/utils/utils.py", line 390, in parse_host
docker.errors.DockerException: Invalid bind address format: [2001:6b8:1:10::10]:2376
docker-compose returned -1
```

Related issue has been fixed in docker/docker#15557 and since version 1.10 docker works well with IPv6 addresses in DOCKER_HOST, while docker-compose doesn't.

```
  › docker-compose version
docker-compose version 1.6.0, build d99cad6
docker-py version: 1.7.0
CPython version: 2.7.9
OpenSSL version: OpenSSL 1.0.1j 15 Oct 2014
```

```
› docker version
Client:
 Version:      1.10.0
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   590d5108
 Built:        Thu Feb  4 18:18:11 2016
 OS/Arch:      darwin/amd64

Server:
 Version:      1.10.0
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   590d5108
 Built:        Thu Feb  4 18:36:33 2016
 OS/Arch:      linux/amd64
```

**Comment by dnephin** [comment]
Thanks for the report.

Support needs to be added to docker-py, then we can pick it up in Compose.

**Comment by connected-mgosbee** [comment]
Update?

**Comment by wiziah** [comment]
Seeking an update as well. I am still experiencing the issue with 1.12 RC4

**Comment by aanand** [comment]
I've created https://github.com/docker/docker-py/issues/1135 to track this.

**Comment by connected-mgosbee** [comment]
It seems to still be an issue in latest docker-compose.

**Comment by connected-mgosbee** [comment]
Someone tell me where to patch this, its been a problem for almost a year now.

**Comment by ashnur** [comment]
I just ran into this issue. I don't even understand why it uses ipv6. Can this be changed?
