### ISSUE TITLE
ERROR: SSL error: [Errno 1] _ssl.c:507: error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version

### ISSUE THREAD

**Issue by robertd** [docker/compose#3114]
Experiencing issues with docker-compose (out of the blue since it used to work). Everything was installed through `brew`
```shell
➜  simple-dockerized-dev-env git:(master) docker --version
Docker version 1.10.2, build c3959b1
➜  simple-dockerized-dev-env git:(master) docker-compose --version
docker-compose version 1.6.2, build unknown
➜  simple-dockerized-dev-env git:(master) docker-machine --version
docker-machine version 0.6.0, build e27fb87
➜  simple-dockerized-dev-env git:(master) docker-compose build
db uses an image, skipping
Building autotest
/usr/local/Cellar/docker-compose/1.6.2/libexec/vendor/lib/python2.7/site-packages/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
ERROR: SSL error: [Errno 1] _ssl.c:507: error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version
➜  simple-dockerized-dev-env git:(master)
```

**Comment by robertd** [comment]
With `--verbose` flag
```bash
➜  simple-dockerized-dev-env git:(master) docker-compose --verbose build
compose.config.config.find: Using configuration files: ./docker-compose.yml
docker.auth.auth.load_config: File doesn't exist
/usr/local/Cellar/docker-compose/1.6.2/libexec/vendor/lib/python2.7/site-packages/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
Traceback (most recent call last):
  File "/usr/local/Cellar/docker-compose/1.6.2/libexec/bin/docker-compose", line 9, in <module>
    load_entry_point('docker-compose==1.6.2', 'console_scripts', 'docker-compose')()
  File "/usr/local/Cellar/docker-compose/1.6.2/libexec/lib/python2.7/site-packages/compose/cli/main.py", line 56, in main
    command.sys_dispatch()
  File "/usr/local/Cellar/docker-compose/1.6.2/libexec/lib/python2.7/site-packages/compose/cli/docopt_command.py", line 23, in sys_dispatch
    self.dispatch(sys.argv[1:], None)
  File "/usr/local/Cellar/docker-compose/1.6.2/libexec/lib/python2.7/site-packages/compose/cli/docopt_command.py", line 26, in dispatch
    self.perform_command(*self.parse(argv, global_options))
  File "/usr/local/Cellar/docker-compose/1.6.2/libexec/lib/python2.7/site-packages/compose/cli/main.py", line 189, in perform_command
    project = project_from_options(self.base_dir, options)
  File "/usr/local/Cellar/docker-compose/1.6.2/libexec/lib/python2.7/site-packages/compose/cli/command.py", line 52, in project_from_options
    verbose=options.get('--verbose'),
  File "/usr/local/Cellar/docker-compose/1.6.2/libexec/lib/python2.7/site-packages/compose/cli/command.py", line 85, in get_project
    client = get_client(verbose=verbose, version=api_version)
  File "/usr/local/Cellar/docker-compose/1.6.2/libexec/lib/python2.7/site-packages/compose/cli/command.py", line 68, in get_client
    version_info = six.iteritems(client.version())
  File "/usr/local/Cellar/docker-compose/1.6.2/libexec/vendor/lib/python2.7/site-packages/docker/api/daemon.py", line 78, in version
    return self._result(self._get(url), json=True)
  File "/usr/local/Cellar/docker-compose/1.6.2/libexec/vendor/lib/python2.7/site-packages/docker/utils/decorators.py", line 47, in inner
    return f(self, *args, **kwargs)
  File "/usr/local/Cellar/docker-compose/1.6.2/libexec/vendor/lib/python2.7/site-packages/docker/client.py", line 112, in _get
    return self.get(url, **self._set_request_timeout(kwargs))
  File "/usr/local/Cellar/docker-compose/1.6.2/libexec/vendor/lib/python2.7/site-packages/requests/sessions.py", line 477, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/Cellar/docker-compose/1.6.2/libexec/vendor/lib/python2.7/site-packages/requests/sessions.py", line 465, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/Cellar/docker-compose/1.6.2/libexec/vendor/lib/python2.7/site-packages/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/Cellar/docker-compose/1.6.2/libexec/vendor/lib/python2.7/site-packages/requests/adapters.py", line 431, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: [Errno 1] _ssl.c:507: error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version
```

**Comment by robertd** [comment]
I've tried #890 solution but no luck :disappointed:

**Comment by robertd** [comment]
`docker-compose version` output even though I've installed python `2.7.11` and openssl `1.0.2g` with brew

```shell
➜  ~ openssl version
OpenSSL 1.0.2g  1 Mar 2016
➜  ~ python --version
Python 2.7.11
```

```shell
➜  ~ docker-compose version
docker-compose version 1.6.2, build unknown
docker-py version: 1.7.2
CPython version: 2.7.6
OpenSSL version: OpenSSL 0.9.8za 5 Jun 2014
```

**Comment by robertd** [comment]
Any ideas? .... anybody? I'm pretty sure this is happening because `docker-compose` is trying to use OSX's Python installation by default and not `brew`. Also I wonder why does it say 'docker-compose version 1.6.2, build unknown'?

**Comment by robertd** [comment]
I'm little disappointed that no one even commented on here.

FWIW... I've installed `docker` and `docker-machine` through `brew` and  `docker-compse` through pip and now It's working.

```shell
➜  simple-dockerized-dev-env git:(master) docker-compose version
docker-compose version 1.6.2, build 4d72027
docker-py version: 1.7.2
CPython version: 2.7.11
OpenSSL version: OpenSSL 1.0.2g  1 Mar 2016
```

Definitely something is going on with `docker-compose` on `brew`.

Hope this helps somebody...

**Comment by robertd** [comment]
Forgot to mention to anyone who is wondering... I'm running docker on MacBook Pro 2010 model (#271)

**Comment by lkysow** [comment]
Had the same problem, thanks @robertd for the fix.
