### ISSUE TITLE
Add standard Docker CLI flags for remote Daemon config?

### ISSUE THREAD

**Issue by mattupstate** [docker/compose#3264]
It'd be pretty nice to be able to run commands like you can with the regular docker client, so I don't have to always inject stuff into the shell environment. For example:

    $ docker-compose $(docker-machine config default) up -d web

**Comment by dnephin** [comment]
I believe this should work in 1.7.0-rc1, could you try it out?

**Comment by mattupstate** [comment]
Unfortunately this doesn't work as one might hope...

```
$ docker-compose $(docker-machine config default) up -d mysql
Traceback (most recent call last):
  File "<string>", line 3, in <module>
  File "compose/cli/main.py", line 57, in main
  File "compose/cli/main.py", line 105, in perform_command
  File "compose/cli/command.py", line 30, in project_from_options
  File "compose/cli/docker_client.py", line 36, in tls_config_from_options
  File "site-packages/docker/tls.py", line 47, in __init__
docker.errors.TLSParameterError: Path to a certificate and key files must be provided through the client_config param. TLS configurations should map the Docker CLI client configurations. See https://docs.docker.com/engine/articles/https/ for API details.
docker-compose returned -1
```

Here's the output from the sub-shell:

```
$ docker-machine config default
--tlsverify
--tlscacert="/Users/mwright/.docker/machine/certs/ca.pem"
--tlscert="/Users/mwright/.docker/machine/certs/cert.pem"
--tlskey="/Users/mwright/.docker/machine/certs/key.pem"
-H=tcp://192.168.99.100:2376
```

Additionally, if you simply replace the subshell with the output, the `-H` flag isn't parsed correctly, as the `=` symbol is included in the host string:

```
$ docker-compose \
> --tlsverify \
> --tlscacert="/Users/mwright/.docker/machine/certs/ca.pem" \
> --tlscert="/Users/mwright/.docker/machine/certs/cert.pem" \
> --tlskey="/Users/mwright/.docker/machine/certs/key.pem" \
> -H=tcp://192.168.99.100:2376 \
> up -d mysql
Traceback (most recent call last):
  File "<string>", line 3, in <module>
  File "compose/cli/main.py", line 57, in main
  File "compose/cli/main.py", line 105, in perform_command
  File "compose/cli/command.py", line 31, in project_from_options
  File "compose/cli/command.py", line 76, in get_project
  File "compose/cli/command.py", line 49, in get_client
  File "compose/cli/docker_client.py", line 73, in docker_client
  File "site-packages/docker/client.py", line 62, in __init__
  File "site-packages/docker/utils/utils.py", line 418, in parse_host
docker.errors.DockerException: Invalid bind address protocol: =tcp://192.168.99.100:2376
docker-compose returned -1
```

**Comment by dnephin** [comment]
I think we can make docopt parse the `-H=` correctly
