### ISSUE TITLE
Ctrl-C/SIGINT has erratic behaviour on "docker-compose up"

### ISSUE THREAD

**Issue by FrederikNS** [docker/compose#3317]
Atleast since version 1.6.0 I have had erratic behaviour when pressing ctrl-c to stop a "docker-compose up". Sometimes the containers are stopped gracefully, and sometimes it "aborts", leaving all the containers running. 

I'm still seeing the issue in docker-compose 1.6.2 with docker 1.10.3.

The following is the input and output in my terminal:

    $ docker-compose up
    Starting masqueradeservice_masquerade_1
    Attaching to masqueradeservice_masquerade_1
    masquerade_1 | [2016-04-13 07:15:50,600] [INFO]: Server started at http://0.0.0.0:7777
    ^CGracefully stopping... (press Ctrl+C again to force)
    Stopping masqueradeservice_masquerade_1 ... done
    $ docker-compose up
    Starting masqueradeservice_masquerade_1
    Attaching to masqueradeservice_masquerade_1
    masquerade_1 | [2016-04-13 07:16:02,684] [INFO]: Server started at http://0.0.0.0:7777
    ^CERROR: Aborting.
    $ docker ps
    CONTAINER ID        IMAGE                          COMMAND              CREATED             STATUS              PORTS                    NAMES
    0b6551bb0b31        masqueradeservice_masquerade   "python server.py"   9 minutes ago       Up 20 seconds   0.0.0.0:7777->7777/tcp   masqueradeservice_masquerade_1

**Comment by mcgeeco** [comment]
Same here - docker 1.10.3, docker-compose 1.6.2, Ubuntu 15.10.

**Comment by dnephin** [comment]
See #2904 for more background. A partial fix went in to 1.7.0 (which is being released this week). It doesn't completely fix the issue with pyinstaller, but it does restore it to the pre-1.6.x behaviour, which saw the bug a lot less frequently.

**Comment by dnephin** [comment]
I'll leave this open for now. If you could try it out with 1.7.0-rc2 that would be great.

**Comment by mcgeeco** [comment]
I actually found `tty: true` did the trick for me. But then... 
![image](https://cloud.githubusercontent.com/assets/5881581/14499796/92b0127a-0197-11e6-8a6f-11fa5a6d50e6.png)

**Comment by FrederikNS** [comment]
Docker Compose 1.7.0 fixes this issue for me. Thanks!

**Comment by LeonMelis** [comment]
I still get this problem with `docker-compose version 1.8.0-rc2, build c72c966`
  with one of my database containers, the issue can be reliably reproduced. Is there some way I can help by dumping a log or something?

More on this topic: 
https://github.com/docker/compose/issues/3347
https://github.com/docker/compose/issues/1040
https://github.com/docker/compose/issues/2904

**Comment by robisenberg** [comment]
I seem to be experiencing the same issue with `docker-compose version 1.8.1, build 878cff1`.

**Comment by robertjpayne** [comment]
Yeap, same here getting this issue with docker-compose version 1.8.0.

**Comment by alexyoung91** [comment]
I am observing this with docker-compose version 1.8.1, build 878cff1. It happens about 50% of the time running a microsoft/dotnet:runtime container and a postgres:latest container together.

**Comment by dbroadhurst** [comment]
I'm on OSX docker-compose version 1.9.0, build 2585387 and it's very broken

**Comment by xxx** [comment]
1.10.0 on OSX continues to demonstrate this problem.

**Comment by diversario** [comment]
Same for 1.11.2

**Comment by rchall-gladly** [comment]
+1 for 1.11.2

**Comment by tristanoneil** [comment]
Seeing this too. Details from `docker-compose version`. On OSX w/ Docker For Mac `17.05.0-ce-rc1-mac8 (16582)`.

```
docker-compose version 1.12.0, build b31ff33
docker-py version: 2.2.1
CPython version: 2.7.12
OpenSSL version: OpenSSL 1.0.2j  26 Sep 2016
```

**Comment by tristanoneil** [comment]
Looks like https://github.com/docker/compose/issues/3347 is a duplicate of this one and is open. So will post there as well.

**Comment by ilyakamens** [comment]
Happening for me too.
```
$ docker-compose version
docker-compose version 1.18.0, build 8dd22a9
docker-py version: 2.6.1
CPython version: 2.7.12
OpenSSL version: OpenSSL 1.0.2j  26 Sep 2016

$ docker --version
Docker version 17.12.0-ce, build c97c6d6
```

OS X version `10.13.3 (17D102)`

**Comment by simoncoulton** [comment]
Confirmed it's still happening here too on OS X.

```
❯ docker-compose version
docker-compose version 1.20.1, build 5d8c71b
docker-py version: 3.1.4
CPython version: 3.6.4
OpenSSL version: OpenSSL 1.0.2n  7 Dec 2017

❯ docker --version
Docker version 18.03.0-ce, build 0520e24
```
OS X version `10.13.3 (17D102)`

**Comment by rt-krz** [comment]
Same on OS X 10.13.4

docker-compose --version
docker-compose version 1.20.1, build 5d8c71b

docker --version
Docker version 18.03.0-ce, build 0520e24

**Comment by damouse** [comment]
Same on OSX 10.13.1
Docker Version 18.03.1-ce-mac65 (24312)
docker-compose version 1.21.1, build 5a3f1a3
docker-py version: 3.3.0
CPython version: 3.6.4

`tty: true` did not help.

**Comment by thomasst** [comment]
This is also an issue for me.

**Comment by udondan** [comment]
Same for me. As suggested by @mcgeeco adding `tty: true` to one of my services in the compose file fixed it.

**Comment by fterrag** [comment]
This has been an issue for me for years now. Adding `tty: true` to one or all of the services does not seem to help. Does anyone have any ideas as to what is causing this error?

**Comment by udondan** [comment]
Turned out, `tty: true` did not solve the problem permanently. It was good for some time but somehow now happens again.

I ended up working with a bash alias to ensure the containers are shut down.

```bash
alias docker-compose-up="bash -c \"trap 'docker-compose down' EXIT; docker-compose up\""
```

**Comment by Mathyn** [comment]
Still getting this issue on Mac OS.

Docker version 18.09.0, build 4d60db4
docker-compose version 1.23.1, build b02f1306

Sometimes ctrl+c exits all running Docker containers. Sometimes it just states 'aborting...' and leaves all containers running.

**Comment by alirizakeles** [comment]
I encountered same problem on Arch Linux.

docker-compose version is 1.23.2.
docker version 18.09.3-ce

Same python program (python 3.7) behaves different if it is launched by `docker-compose up`. Program expects to catch a graceful shutdown and do some stuff before exit. It runs on host machine as it is expected. If it is launched by docker-compose, it never reaches / runs graceful shutdown part. Eventually it exits, but not gracefully.

**Comment by SystemDisc** [comment]
I am encountering this on macOS Mojave (10.14.4).

docker-compose version 1.23.2, build 1110ad01
Docker version 18.09.2, build 6247962

I usually get the expected
```
^CGracefully stopping... (press Ctrl+C again to force)
Stopping SERVICENAME ... done
```

But, sometimes I get
```
^CERROR: Aborting.
```

**Comment by KristianWindsor** [comment]
I am also having this issue

**Comment by anowlcalledjosh** [comment]
This isn't limited to OS X – I'm experiencing it with docker-compose 1.18.0 on Ubuntu Xenial.

**Comment by DenisKolodin** [comment]
The same for:
```
Docker version 18.09.2, build 6247962
docker-compose version 1.23.2, build 1110ad01
ProductName:	Mac OS X
ProductVersion:	10.14.5
BuildVersion:	18F203
```

**Comment by hex0cter** [comment]
Same here:
```
docker-compose version 1.25.2, build 698e2846
```
on macOs

**Comment by inieves** [comment]
I am seeing this problem still:
docker-compose version 1.29.2, build 5becea4c
on macOS

**Comment by inieves** [comment]
I am noticing (what seems to be) a failure by Python to parse a docker source file from docker-compose, when control-c is pressed (triggering a graceful shutdown).

I was able to capture this verbose debug output from the moment just after control-c was pressed.  I was able to trigger this failed graceful shutdown output after having about 10 successful graceful shutdowns.  The most relevant part seems to be the last (approximately) 4 lines:

Also, there seems to be an open Python bug that relates quite strongly to this failure behavior:
https://bugs.python.org/issue18961

=============================

^CGracefully stopping... (press Ctrl+C again to force)
compose.cli.verbose_proxy.proxy_callable: docker containers <- (all=False, filters={'label': ['com.docker.compose.project=stuco_dev-route', 'com.docker.compose.oneoff=False']})
--- Logging error ---
Traceback (most recent call last):
  File "compose/cli/main.py", line 1530, in up_shutdown_context
  File "compose/cli/main.py", line 1216, in up
  File "compose/cli/log_printer.py", line 88, in run
  File "compose/cli/log_printer.py", line 241, in consume_queue
  File "queue.py", line 180, in get
  File "threading.py", line 316, in wait
  File "compose/cli/signals.py", line 15, in shutdown
compose.cli.signals.ShutdownException

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging/__init__.py", line 1082, in emit
  File "compose/cli/signals.py", line 15, in shutdown
compose.cli.signals.ShutdownException
Call stack:
Traceback (most recent call last):
  File "compose/cli/main.py", line 1530, in up_shutdown_context
  File "compose/cli/main.py", line 1216, in up
  File "compose/cli/log_printer.py", line 88, in run
  File "compose/cli/log_printer.py", line 241, in consume_queue
  File "queue.py", line 180, in get
  File "threading.py", line 316, in wait
  File "compose/cli/signals.py", line 15, in shutdown
compose.cli.signals.ShutdownException

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging/__init__.py", line 1082, in emit
  File "compose/cli/signals.py", line 15, in shutdown
compose.cli.signals.ShutdownException

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tokenize.py", line 330, in find_cookie
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xcf in position 0: invalid continuation byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "docker-compose", line 3, in <module>
  File "compose/cli/main.py", line 81, in main
  File "compose/cli/main.py", line 203, in perform_command
  File "compose/metrics/decorator.py", line 18, in wrapper
  File "compose/cli/main.py", line 1229, in up
  File "contextlib.py", line 135, in __exit__
  File "compose/cli/main.py", line 1533, in up_shutdown_context
  File "compose/project.py", line 411, in stop
  File "compose/project.py", line 854, in containers
  File "compose/project.py", line 834, in _labeled_containers
  File "compose/cli/verbose_proxy.py", line 45, in proxy_callable
  File "logging/__init__.py", line 1434, in info
  File "logging/__init__.py", line 1577, in _log
  File "logging/__init__.py", line 1587, in handle
  File "logging/__init__.py", line 1649, in callHandlers
  File "logging/__init__.py", line 948, in handle
  File "logging/__init__.py", line 1087, in emit
  File "logging/__init__.py", line 1010, in handleError
  File "/Users/administrator/jenkins/workspace/dsg_compose_1.29.2/build/toolchain/Frameworks/Python.framework/Versions/3.9/lib/python3.9/traceback.py", line 190, in print_stack
  File "/Users/administrator/jenkins/workspace/dsg_compose_1.29.2/build/toolchain/Frameworks/Python.framework/Versions/3.9/lib/python3.9/traceback.py", line 211, in extract_stack
  File "/Users/administrator/jenkins/workspace/dsg_compose_1.29.2/build/toolchain/Frameworks/Python.framework/Versions/3.9/lib/python3.9/traceback.py", line 366, in extract
  File "/Users/administrator/jenkins/workspace/dsg_compose_1.29.2/build/toolchain/Frameworks/Python.framework/Versions/3.9/lib/python3.9/traceback.py", line 288, in line
  File "/Users/administrator/jenkins/workspace/dsg_compose_1.29.2/build/toolchain/Frameworks/Python.framework/Versions/3.9/lib/python3.9/linecache.py", line 30, in getline
  File "/Users/administrator/jenkins/workspace/dsg_compose_1.29.2/build/toolchain/Frameworks/Python.framework/Versions/3.9/lib/python3.9/linecache.py", line 46, in getlines
  File "/Users/administrator/jenkins/workspace/dsg_compose_1.29.2/build/toolchain/Frameworks/Python.framework/Versions/3.9/lib/python3.9/linecache.py", line 136, in updatecache
  File "tokenize.py", line 394, in open
  File "tokenize.py", line 371, in detect_encoding
  File "tokenize.py", line 335, in find_cookie
SyntaxError: invalid or missing encoding declaration for '/Applications/Docker.app/Contents/Resources/bin/docker-compose-v1/docker-compose'
[48682] Failed to execute script docker-compose
