### ISSUE TITLE
Connection broken: IncompleteRead

### ISSUE THREAD

**Issue by psychok7** [docker/compose#3387]
Not sure if it is related to https://github.com/docker/compose/issues/3341 but i upgraded my Host to Ubuntu 16.04 (clean install), reinstalled docker `1.11.0` and docker-compose `1.7.0` and i started getting the following error when crawling a website:

Inside my docker containers i am using `python3` and crawling a website. After succefully crawling about 5% of my content this error happens and the containers/services get killed.

Any ideas?

```
mongo_1         | 2016-04-26T19:52:53.676+0000 I NETWORK  [initandlisten] connection accepted from 172.19.0.9:60772 #4 (4 connections now open)
Exception in thread Thread-13:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/dist-packages/compose/cli/log_printer.py", line 190, in watch_events
    for event in event_stream:
  File "/usr/local/lib/python2.7/dist-packages/compose/project.py", line 343, in events
    decode=True
  File "/usr/local/lib/python2.7/dist-packages/docker/client.py", line 225, in _stream_helper
    data = reader.read(1)
  File "/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/response.py", line 271, in read
    raise ProtocolError('Connection broken: %r' % e, e)
ProtocolError: ('Connection broken: IncompleteRead(0 bytes read)', IncompleteRead(0 bytes read))
```

**Comment by aleks** [comment]
This seems related to #3336

**Comment by psychok7** [comment]
@aleks i uninstalled `docker-compose` for python 2.7 and i installed it again for python3 with `sudo pip3 install docker-compose` to see if the problem continues.

**Comment by aleks** [comment]
@psychok7 and? Did it work? :grin:

**Comment by psychok7** [comment]
@aleks left the script running... Will let you know in a few hours but it's looking good so far

**Comment by psychok7** [comment]
@aleks i think this is the workaround. It's way past the point were i used to get that error so i am assuming this works.

**Comment by aleks** [comment]
@psychok7 i still have the same problem with python3 and pip3. 😢

**Comment by psychok7** [comment]
I haven't had this problem again "yet". you uninstalled `docker-compose` and `sudo pip3 install docker-compose` right?

Anyways this looks like a nasty bug, hope the mantainers fix this issues soons

**Comment by emirb** [comment]
Got this error in OSX 10.13 on MBPro Retina 2015:

```
Exception in thread Thread-4:
Traceback (most recent call last):
  File "threading.py", line 801, in __bootstrap_inner
  File "threading.py", line 754, in run
  File "compose/cli/log_printer.py", line 203, in watch_events
  File "compose/project.py", line 357, in events
  File "site-packages/docker/api/client.py", line 290, in _stream_helper
  File "site-packages/docker/utils/json_stream.py", line 66, in split_buffer
  File "site-packages/docker/utils/json_stream.py", line 22, in stream_as_text
  File "site-packages/docker/api/client.py", line 296, in _stream_helper
  File "site-packages/requests/packages/urllib3/response.py", line 324, in read
  File "contextlib.py", line 35, in __exit__
  File "site-packages/requests/packages/urllib3/response.py", line 250, in _error_catcher
ProtocolError: ('Connection broken: IncompleteRead(0 bytes read)', IncompleteRead(0 bytes read))
```

**Comment by mrcasablr** [comment]
I get this error too pretty consistently - 
```
...
Step 2/6 : ADD build/libs/api-proxy-0.0.1.jar app.jar
Traceback (most recent call last):
  File "bin/docker-compose", line 6, in <module>
  File "compose/cli/main.py", line 71, in main
  File "compose/cli/main.py", line 124, in perform_command
  File "compose/cli/main.py", line 254, in build
  File "compose/project.py", line 364, in build
  File "compose/service.py", line 972, in build
  File "compose/progress_stream.py", line 18, in stream_output
  File "compose/utils.py", line 61, in split_buffer
  File "compose/utils.py", line 37, in stream_as_text
  File "site-packages/docker/api/client.py", line 304, in _stream_helper
  File "site-packages/urllib3/response.py", line 401, in read
  File "contextlib.py", line 35, in __exit__
  File "site-packages/urllib3/response.py", line 320, in _error_catcher
urllib3.exceptions.ProtocolError: ('Connection broken: IncompleteRead(0 bytes read)', IncompleteRead(0 bytes read))
Failed to execute script docker-compose
```
docker-compose version 1.18.0, build 8dd22a9
fedora 27 x86_64
Python 2.7.14

**Comment by 344310362** [comment]
Has the problem been solved?

**Comment by rg687** [comment]
Hello, 

I have the same problem, is there a solution? 

Thanks

**Comment by dayrim** [comment]
Got the same problem
```
[52] Failed to execute script docker-compose
Traceback (most recent call last):
  File "http/client.py", line 554, in _get_chunk_left
  File "http/client.py", line 521, in _read_next_chunk_size
ValueError: invalid literal for int() with base 16: b''
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "http/client.py", line 586, in _readinto_chunked
  File "http/client.py", line 556, in _get_chunk_left
http.client.IncompleteRead: IncompleteRead(0 bytes read)
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "site-packages/urllib3/response.py", line 437, in _error_catcher
  File "site-packages/urllib3/response.py", line 519, in read
  File "http/client.py", line 457, in read
  File "http/client.py", line 491, in readinto
  File "http/client.py", line 602, in _readinto_chunked
http.client.IncompleteRead: IncompleteRead(0 bytes read)
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "bin/docker-compose", line 6, in <module>
  File "compose/cli/main.py", line 72, in main
  File "compose/cli/main.py", line 128, in perform_command
  File "compose/cli/main.py", line 304, in build
  File "compose/project.py", line 403, in build
  File "compose/project.py", line 385, in build_service
  File "compose/service.py", line 1110, in build
  File "compose/progress_stream.py", line 25, in stream_output
  File "compose/utils.py", line 61, in split_buffer
  File "compose/utils.py", line 37, in stream_as_text
  File "site-packages/docker/api/client.py", line 345, in _stream_helper
  File "site-packages/urllib3/response.py", line 541, in read
  File "contextlib.py", line 130, in __exit__
  File "site-packages/urllib3/response.py", line 455, in _error_catcher
urllib3.exceptions.ProtocolError: ('Connection broken: IncompleteRead(0 bytes read)', IncompleteRead(0 bytes read))
```
