### ISSUE TITLE
Error while compose scale

### ISSUE THREAD

**Issue by Rohlik** [docker/compose#3406]
Hello,
I have this simple docker-compose.yml

```
test:
 build: .
 ports:
  - "80"
```

When I run _docker-compose scale test=5_ then this happened:

```
Creating and starting tmp_test_1 ... 
Creating and starting tmp_test_2 ... 
Creating and starting tmp_test_3 ... 
Creating and starting tmp_test_4 ... 
Creating and starting tmp_test_5 ... 
Building test
Building test
Building test
Building test
Building test
Step 1 : FROM busybox
 ---> 47bcc53f74dc
Step 2 : EXPOSE 80
Step 1 : FROM busybox
 ---> 47bcc53f74dc
Step 2 : EXPOSE 80
Step 1 : FROM busybox
 ---> 47bcc53f74dc
Step 2 : EXPOSE 80
 ---> Running in 67c494d6da7d
 ---> Running in f8fd96e4b336
 ---> dcacc53a6dcf
 ---> 8c8c276f9943
 ---> Running in d49b060238f8
Removing intermediate container 67c494d6da7d
Step 3 : CMD ping -c 30 google.cz
 ---> Running in 28ea5fee9747
 ---> cb9320a8981c
Removing intermediate container f8fd96e4b336
Step 3 : CMD ping -c 30 google.cz
 ---> 002a4455dd94
 ---> Running in 526dbfa5015a
Removing intermediate container d49b060238f8
Step 3 : CMD ping -c 30 google.cz
 ---> Running in 9b97d8908d67
Removing intermediate container 28ea5fee9747
Successfully built 002a4455dd94
WARNING: Image for service test was built because it did not already exist. To rebuild this image you must use `docker-compose build` or `docker-compose up --build`.
 ---> c29188599737
 ---> 8a749f22b5b1
Removing intermediate container 9b97d8908d67
Creating and starting tmp_test_1 ... done
Creating and starting tmp_test_2 ... done
Creating and starting tmp_test_3 ... done
Successfully built 8a749f22b5b1
WARNING: Image for service test was built because it did not already exist. To rebuild this image you must use `docker-compose build` or `docker-compose up --build`.

ERROR: for tmp_test_5  [Errno 2] No such file or directory: '/tmp/tmpyMpwoc'

ERROR: for tmp_test_4  [Errno 2] No such file or directory: '/tmp/tmpyMpwoc'
Traceback (most recent call last):
  File "<string>", line 3, in <module>
  File "compose/cli/main.py", line 57, in main
  File "compose/cli/main.py", line 108, in perform_command
  File "compose/cli/main.py", line 619, in scale
  File "compose/service.py", line 238, in scale
  File "compose/parallel.py", line 60, in parallel_execute
OSError: [Errno 2] No such file or directory: '/tmp/tmpyMpwoc'
docker-compose returned -1
```

Is it bug?

My Docker version is:
`Docker version 1.11.0, build 4dc5990`
My compose version is:

```
docker-compose version 1.7.0, build 0d7bf73
docker-py version: 1.8.0
CPython version: 2.7.9
OpenSSL version: OpenSSL 1.0.1e 11 Feb 2013
```

Using RHEL7 - 3.10.0-327.el7.x86_64

**Comment by shin-** [comment]
Interesting, did you run `docker-compose up` before running `docker-compose scale` ?

**Comment by Rohlik** [comment]
@shin- When I use `docker-compose up` and then `docker-compose scale` everything is OK.
But the fact `docker-compose scale` can be used before `docker-compose up` is wrong and should be handled somehow I think.

**Comment by cecton** [comment]
@shin- same issue here. I have a colleague who encountered the issue and it's true that when you see at the terminal, it just looks wrong. It should either create the network if it doesn't exist or prevent you to scale something that doesn't exist at all.

```
[0] [14:07:04] ~/r/webcat master > dc scale resource=2
WARNING: The "resource" service specifies a port on the host. If multiple containers for this service are created on a single host, the port will clash.
Creating and starting webcat_resource_1 ... error
Creating and starting webcat_resource_2 ... error

ERROR: for webcat_resource_2  Cannot start service resource: b'network webcat_default not found'

ERROR: for webcat_resource_1  Cannot start service resource: b'network webcat_default not found'
[0] [14:07:27] ~/r/webcat master > dc down
Removing webcat_resource_2 ... done
Removing webcat_resource_1 ... done
Removing network webcat_default
WARNING: Network webcat_default not found.
```

**Comment by shin-** [comment]
Closing as `docker-compose scale` is now deprecated.
