### ISSUE TITLE
ERROR: argument of type 'NoneType' is not iterable

### ISSUE THREAD

**Issue by johanneswuerbach** [docker/compose#3451]
When trying to `docker-compose up` with ~20 services on Docker for Mac 1.11.1-beta11 I quite often get errors like the following:

```
ERROR: for ui  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)

ERROR: An HTTP request took too long to complete. Retry with --verbose to obtain debug information.
If you encounter this issue regularly because of slow network conditions, consider setting COMPOSE_HTTP_TIMEOUT to a higher value (current value: 60).
```

and another  `docker-compose up` results in

```
ERROR: for ui  argument of type 'NoneType' is not iterable
Traceback (most recent call last):
  File "<string>", line 3, in <module>
  File "compose/cli/main.py", line 58, in main
  File "compose/cli/main.py", line 109, in perform_command
  File "compose/cli/main.py", line 734, in up
  File "compose/project.py", line 398, in up
  File "compose/parallel.py", line 60, in parallel_execute
TypeError: argument of type 'NoneType' is not iterable
```

The error is not limited to the `ui` service and hits different services in each up attempt.

The ui service itself:

```
$ docker ps -a | grep ui
1d57c16d2ad3  lab_ui    "node_modules/.bin/gu"   5 minutes ago       Created   lab_ui_1
$ docker inspect 1d57c16d2ad3
https://gist.github.com/johanneswuerbach/da5f69e2a1da245f474eb61f4db93ae2
```

When starting the service manually using `docker start 1d57c16d2ad3`, the error disappears.

```
$ docker-compose -v
docker-compose version 1.7.1, build 0a9ab35
```

**Comment by shin-** [comment]
Thanks for the report!

**Comment by shin-** [comment]
Just as an update, my attempts at reproducing this issue have so far been unsuccessful. If someone has more info on that, or can share a reproducible use-case, it would be much appreciated!

**Comment by M0on75e1l** [comment]
Same error with this:
https://github.com/LaraDock/laradock

**Comment by NuckChorris** [comment]
Confirming that I see the same in some of my projects on Docker for Mac beta13.1

**Comment by elirambu** [comment]
I also get this error on Amazon EC2 with docker-compose up

**Comment by pcherednichenko** [comment]
I have the same error on a Mac Mini 2014, Mac OS El Capitan 10.11.6
```
docker version
Client:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 23:54:00 2016
 OS/Arch:      darwin/amd64
```
[bug.zip](https://github.com/docker/compose/files/422604/bug.zip)

**Comment by goliatone** [comment]
I was getting a similar error:

```
ERROR: for server  'NoneType' object is not iterable
Traceback (most recent call last):
  File "/usr/local/bin/docker-compose", line 11, in <module>
    load_entry_point('docker-compose==1.11.1', 'console_scripts', 'docker-compose')()
  File "/usr/local/Cellar/docker-compose/1.11.1/libexec/lib/python2.7/site-packages/compose/cli/main.py", line 88, in main
    command()
  File "/usr/local/Cellar/docker-compose/1.11.1/libexec/lib/python2.7/site-packages/compose/cli/main.py", line 140, in perform_command
    handler(command, command_options)
  File "/usr/local/Cellar/docker-compose/1.11.1/libexec/lib/python2.7/site-packages/compose/cli/main.py", line 900, in up
    remove_orphans=remove_orphans)
  File "/usr/local/Cellar/docker-compose/1.11.1/libexec/lib/python2.7/site-packages/compose/project.py", line 416, in up
    get_deps
  File "/usr/local/Cellar/docker-compose/1.11.1/libexec/lib/python2.7/site-packages/compose/parallel.py", line 66, in parallel_execute
    raise error_to_reraise
TypeError: 'NoneType' object is not iterable

```

The culprit was an empty string in the `docker-compose.yml`:
```yaml
version: '3'

services:
  server:
    build: .
    image: goliatone/hotdesk-dashboard
    hostname: hotdesk-dashboard-staging
    command: dumb-init npm start
    ports:
      - "3232:8989"
      - ""
    restart: always
    logging:
      options:
        max-size: "50m"
        max-file: "3"
```

Removing the `""` fixed the issue.

```
docker-compose version 1.11.1, build unknown
Docker version 1.13.1, build 092cba3
docker-machine version 0.9.0, build 15fd4c7
MBP 2014, macOS Sierra, 10.12.1.
```
