### ISSUE TITLE
ssl.SSLError when logging

### ISSUE THREAD

**Issue by iMerica** [docker/compose#3479]
docker-compose version 1.7.0, build 0d7bf73

Run log with follow:

```
$ docker-compose logs --follow web
```

(wait a few minutes)

```
Traceback (most recent call last):
  File "<string>", line 3, in <module>
  File "compose/cli/main.py", line 57, in main
  File "compose/cli/main.py", line 108, in perform_command
  File "compose/cli/main.py", line 414, in logs
  File "compose/cli/log_printer.py", line 86, in run
  File "compose/cli/log_printer.py", line 222, in consume_queue
ssl.SSLError: ('The read operation timed out',)
docker-compose returned -1
```

This is happening on multiple computers in my office.

**Comment by iMerica** [comment]
I'm using attach as a workaround in the interim:

`docker attach $(docker ps  | grep {container_name} | awk '{print $1}') `

**Comment by thiagocaiubi** [comment]
I'm facing the same issue.

```
Traceback (most recent call last):
  File "/usr/local/Cellar/docker-compose/1.7.1/libexec/bin/docker-compose", line 9, in <module>
    load_entry_point('docker-compose==1.7.1', 'console_scripts', 'docker-compose')()
  File "/usr/local/Cellar/docker-compose/1.7.1/libexec/lib/python2.7/site-packages/compose/cli/main.py", line 58, in main
    command()
  File "/usr/local/Cellar/docker-compose/1.7.1/libexec/lib/python2.7/site-packages/compose/cli/main.py", line 109, in perform_command
    handler(command, command_options)
  File "/usr/local/Cellar/docker-compose/1.7.1/libexec/lib/python2.7/site-packages/compose/cli/main.py", line 420, in logs
    event_stream=self.project.events(service_names=options['SERVICE'])).run()
  File "/usr/local/Cellar/docker-compose/1.7.1/libexec/lib/python2.7/site-packages/compose/cli/log_printer.py", line 86, in run
    for line in consume_queue(queue, self.cascade_stop):
  File "/usr/local/Cellar/docker-compose/1.7.1/libexec/lib/python2.7/site-packages/compose/cli/log_printer.py", line 222, in consume_queue
    raise item.exc
ssl.SSLError: ('The read operation timed out',)
```
