### ISSUE TITLE
UnixHTTPConnectionPool(host='localhost', port=None): Pool is closed.

### ISSUE THREAD

**Issue by mj-nowak** [docker/compose#3586]
When attempting to run docker-compose up for the first time on a machine with about 30 services I am receiving this error:

```
==> default: ERROR: for integrate-resourcepermissions  UnixHTTPConnectionPool(host='localhost', port=None): Pool is closed.
==> default:
==> default: ERROR: for integrate-roles  UnixHTTPConnectionPool(host='localhost', port=None): Pool is closed.
==> default: Traceback (most recent call last):
==> default:   File "/usr/bin/docker-compose", line 9, in <module>
==> default:     load_entry_point('docker-compose==1.7.1', 'console_scripts', 'docker-compose')()
==> default:   File "/usr/lib/python2.7/site-packages/compose/cli/main.py", line 58, in main
==> default:     command()
==> default:   File "/usr/lib/python2.7/site-packages/compose/cli/main.py", line 109, in perform_command
==> default:     handler(command, command_options)
==> default:   File "/usr/lib/python2.7/site-packages/compose/cli/main.py", line 734, in up
==> default:     remove_orphans=remove_orphans)
==> default:   File "/usr/lib/python2.7/site-packages/compose/project.py", line 398, in up
==> default:     get_deps
==> default:   File "/usr/lib/python2.7/site-packages/compose/parallel.py", line 60, in parallel_execute
==> default:     raise error_to_reraise
==> default: requests.packages.urllib3.exceptions.ClosedPoolError: UnixHTTPConnectionPool(host='localhost', port=None): Pool is closed.
```

Seems to only happen on the initial creation, if I rerun the command the error does not occur, but if I delete the containers and images and run again, the error occurs.  Does not happen 100% of the time but more likely then not it fails.

uname -a 
```
Linux mnowak 3.10.0-327.18.2.el7.x86_64 #1 SMP Thu May 12 11:03:55 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```

docker info
```
Linux mnowak 3.10.0-327.18.2.el7.x86_64 #1 SMP Thu May 12 11:03:55 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
[root@mnowak ~]# ^C
[root@mnowak ~]# docker info
Containers: 40
 Running: 40
 Paused: 0
 Stopped: 0
Images: 40
Server Version: 1.11.1
Storage Driver: devicemapper
 Pool Name: docker-thinpool
 Pool Blocksize: 524.3 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file:
 Metadata file:
 Data Space Used: 12.95 GB
 Data Space Total: 40.8 GB
 Data Space Available: 27.85 GB
 Metadata Space Used: 7.664 MB
 Metadata Space Total: 427.8 MB
 Metadata Space Available: 420.2 MB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Library Version: 1.02.107-RHEL7 (2015-12-01)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null host bridge
Kernel Version: 3.10.0-327.18.2.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 5.671 GiB
Name: mnowak
ID: LLH4:TRW5:AQN6:DTVW:GNRD:ARXF:JPVX:EX2L:B2UP:OO25:PTGP:YV4Y
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): false
Registry: https://index.docker.io/v1/
```

docker version
```
Client:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Wed Apr 27 00:34:42 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Wed Apr 27 00:34:42 2016
 OS/Arch:      linux/amd64
```

docker-compose version
```
docker-compose version 1.7.1, build 6c29830
docker-py version: 1.8.1
CPython version: 2.7.5
OpenSSL version: OpenSSL 1.0.1e-fips 11 Feb 2013
```

**Comment by shin-** [comment]
Thank you for the report.

**Comment by HadesArchitect** [comment]
The same for me.

The amount of services: 37

Logs:

> ERROR: for xyz-service  UnixHTTPConnectionPool(host='localhost', port=None): Pool is closed.
> Traceback (most recent call last):
>   File "<string>", line 3, in <module>
>   File "compose/cli/main.py", line 58, in main
>   File "compose/cli/main.py", line 109, in perform_command
>   File "compose/cli/main.py", line 734, in up
>   File "compose/project.py", line 398, in up
>   File "compose/parallel.py", line 60, in parallel_execute
> requests.packages.urllib3.exceptions.ClosedPoolError: UnixHTTPConnectionPool(host='localhost', port=None): Pool is closed.
> docker-compose returned -1

Docker version:

> Client:
>  Version:      1.11.2
>  API version:  1.23
>  Go version:   go1.5.4
>  Git commit:   b9f10c9
>  Built:        Wed Jun  1 21:47:50 2016
>  OS/Arch:      linux/amd64
> 
> Server:
>  Version:      1.11.2
>  API version:  1.23
>  Go version:   go1.5.4
>  Git commit:   b9f10c9
>  Built:        Wed Jun  1 21:47:50 2016
>  OS/Arch:      linux/amd64
> 

Docker Compose version:

> docker-compose version 1.7.1, build 0a9ab35
> docker-py version: 1.8.1
> CPython version: 2.7.9
> OpenSSL version: OpenSSL 1.0.1e 11 Feb 2013

**Comment by mhmxs** [comment]
Same for me:

Docker version:
```
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5/1.9.1
 Built:
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5/1.9.1
 Built:
 OS/Arch:      linux/amd64
```

Compose version:
```
docker-compose version 1.7.1, build 0a9ab35
docker-py version: 1.8.1
CPython version: 2.7.9
OpenSSL version: OpenSSL 1.0.1e 11 Feb 2013
```

OS:
```
Linux ip-10-0-0-203 4.4.8-20.46.amzn1.x86_64 #1 SMP Wed Apr 27 19:28:52 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by mj-nowak** [comment]
Just as an update, this is still occurring for me on docker engine 1.11.2 and docker-compose 1.8.0rc2 even with COMPOSE_HTTP_TIMEOUT=200 set.  Can replicate about 50% of the time with 1.8.0rc2 and about 75% of the time on 1.7.1

**Comment by jstrejc** [comment]
We have exactly the same problem, happens when launching multiple containers (about 40) at once

```
Docker version 1.11.2, build b9f10c9
docker-compose version 1.7.1, build 0a9ab35
OS: Ubuntu 16.04 Linux 4.4.0-28-generic #47-Ubuntu SMP Fri Jun 24 10:09:13 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```

Happens in about 15% runs

**Comment by HadesArchitect** [comment]
The only workaround for now which we have found is to:

```
docker-compose  up -d service1 service2 service3 ...  service10
docker-compose  up -d service11 service12 service13 ...  service20
docker-compose  up -d # To start the rest of them
```

**Comment by harai** [comment]
The same problem happens on my CI server.

# Number of Containers

16

# Error Messages

```
ERROR: for abcd_container  UnixHTTPConnectionPool(host='localhost', port=None): Pool is closed.
Traceback (most recent call last):
  File "<string>", line 3, in <module>
  File "compose/cli/main.py", line 58, in main
  File "compose/cli/main.py", line 109, in perform_command
  File "compose/cli/main.py", line 734, in up
  File "compose/project.py", line 398, in up
  File "compose/parallel.py", line 60, in parallel_execute
requests.packages.urllib3.exceptions.ClosedPoolError: UnixHTTPConnectionPool(host='localhost', port=None): Pool is closed.
docker-compose returned -1
```

# Docker Version

```
$ docker version
Client:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 22:11:10 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 22:11:10 2016
 OS/Arch:      linux/amd64
```

# Docker Info

```
$ docker info
Containers: 32
 Running: 18
 Paused: 0
 Stopped: 14
Images: 50
Server Version: 1.12.0
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 207
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: overlay null bridge host
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor seccomp
Kernel Version: 4.4.0-31-generic
Operating System: Ubuntu 16.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 3.613 GiB
Name: ci
ID: WNXZ:W73C:MXIE:ZKAY:G5MC:NL22:EW42:WIET:UOWO:AJJI:P7RE:EGPA
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
 127.0.0.0/8
```

# Docker Compose Version

```
$ docker-compose version
docker-compose version 1.7.1, build 0a9ab35
docker-py version: 1.8.1
CPython version: 2.7.9
OpenSSL version: OpenSSL 1.0.1e 11 Feb 2013
```

# OS

```
$ uname -a
Linux ci 4.4.0-31-generic #50-Ubuntu SMP Wed Jul 13 00:07:12 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by yunghoy** [comment]
---
ERROR: for ranked2  UnixHTTPConnectionPool(host='localhost', port=None): Pool is closed.
Traceback (most recent call last):
  File "<string>", line 3, in <module>
  File "compose/cli/main.py", line 61, in main
  File "compose/cli/main.py", line 113, in perform_command
  File "compose/cli/main.py", line 835, in up
  File "compose/project.py", line 400, in up
  File "compose/parallel.py", line 64, in parallel_execute
requests.packages.urllib3.exceptions.ClosedPoolError: UnixHTTPConnectionPool(host='localhost', port=None): Pool is closed.
docker-compose returned -1
---
[Docker Version]
Client:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 22:00:36 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 22:00:36 2016
 OS/Arch:      linux/amd64
---
[Docker-Compose Version]
docker-compose version 1.8.0, build f3628c7
docker-py version: 1.9.0
CPython version: 2.7.9
OpenSSL version: OpenSSL 1.0.1e 11 Feb 2013
---
