### ISSUE TITLE
Docker-compose exec always return error "exit status 255" when executed by go os/exec package.

### ISSUE THREAD

**Issue by jaggerwang** [docker/compose#3678]
### The go code and output:
**go code**
```
func emptyDB() (err error) {
	cmd := exec.Command("docker-compose", "-p", "zqctest", "exec", "server", "zqc", "db", "empty")
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr
	cmd.Dir = filepath.Join(os.Getenv("GOPATH"), "src", "zaiqiuchang.com", "server")
	err = cmd.Run()
	fmt.Printf("%+v\n", cmd)
	fmt.Println(err)
	return err
}
```
**output:**
```
Traceback (most recent call last):
  File "<string>", line 3, in <module>
  File "compose/cli/main.py", line 58, in main
  File "compose/cli/main.py", line 109, in perform_command
  File "compose/cli/main.py", line 396, in exec_command
  File "site-packages/dockerpty/pty.py", line 338, in start
  File "site-packages/dockerpty/io.py", line 32, in set_blocking
ValueError: file descriptor cannot be a negative integer (-1)
docker-compose returned -1
&{Path:/usr/local/bin/docker-compose Args:[docker-compose -p zqctest exec server zqc db empty] Env:[] Dir:/Users/jagger/go/src/zaiqiuchang.com/server Stdin:<nil> Stdout:0xc820090008 Stderr:0xc820090010 ExtraFiles:[] SysProcAttr:<nil> Process:0xc82020c580 ProcessState:exit status 255 lookPathErr:<nil> finished:true childFiles:[0xc820090180 0xc820090008 0xc820090010] closeAfterStart:[0xc820090180] closeAfterWait:[] goroutine:[] errch:0xc82006f680}
exit status 255
```
As you can see, the err returned by emptyDB is "exit status 255". 

### Chang command to pwd, and it works fine:
But if I change the command to some other, like "pwd", it works fine.
```
func emptyDB() (err error) {
	cmd := exec.Command("pwd")
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr
	cmd.Dir = filepath.Join(os.Getenv("GOPATH"), "src", "zaiqiuchang.com", "server")
	err = cmd.Run()
	fmt.Printf("%+v\n", cmd)
	fmt.Println(err)
	return err
}

/Users/jagger/go/src/zaiqiuchang.com/server
&{Path:/bin/pwd Args:[pwd] Env:[] Dir:/Users/jagger/go/src/zaiqiuchang.com/server Stdin:<nil> Stdout:0xc82002a010 Stderr:0xc82002a018 ExtraFiles:[] SysProcAttr:<nil> Process:0xc8201f0780 ProcessState:exit status 0 lookPathErr:<nil> finished:true childFiles:[0xc82002a198 0xc82002a010 0xc82002a018] closeAfterStart:[0xc82002a198] closeAfterWait:[] goroutine:[] errch:0xc82006d680}
<nil
```

### Make sure exec works on local command line:
```
➜  server git:(master) ✗ pwd
/Users/jagger/go/src/zaiqiuchang.com/server
➜  server git:(master) ✗ docker-compose -p zqctest exec server zqc db empty
using config file ./config.json
empty db ok
➜  server git:(master) ✗ echo $?
0
```

**Comment by lanzz** [comment]
Seems to be the same issue as https://github.com/docker/compose/issues/3352
