### ISSUE TITLE
Read operation timeout in docker compose

### ISSUE THREAD

**Issue by razasayed** [docker/compose#3750]
Im using docker-compose version 1.7.1, build 0a9ab35 to run my Rails application. I notice that after some time, i get the following error in the logs.

```
Traceback (most recent call last):
  File "<string>", line 3, in <module>
  File "compose/cli/main.py", line 58, in main
  File "compose/cli/main.py", line 109, in perform_command
  File "compose/cli/main.py", line 420, in logs
  File "compose/cli/log_printer.py", line 86, in run
  File "compose/cli/log_printer.py", line 222, in consume_queue
ssl.SSLError: ('The read operation timed out',)
docker-compose returned -1
```

The logs stop after this but the application continues to run in the container. I have tried running my application with ```docker-compose up -d --timeout 3600``` and then doing ```docker-compose logs -f```, but the same thing happens.  Is there any way to fix this ?

**Comment by Gaston-Fartek** [comment]
same here, any solution to this issue?

**Comment by razasayed** [comment]
None yet, except we can do this to delay the HTTP Timeout, for example by 1 hr : `COMPOSE_HTTP_TIMEOUT=3600 docker-compose up`

**Comment by aanand** [comment]
This might be a duplicate of https://github.com/docker/compose/issues/3106
