### ISSUE TITLE
docker-compose cannot handle unicode file paths on Windows

### ISSUE THREAD

**Issue by BYK** [docker/compose#3870]
I've just hit this error:

```
Traceback (most recent call last):
  File "<string>", line 3, in <module>
  File "compose\cli\main.py", line 61, in main
  File "compose\cli\main.py", line 113, in perform_command
  File "compose\cli\main.py", line 219, in build
  File "compose\project.py", line 300, in build
  File "compose\service.py", line 727, in build
  File "site-packages\docker\api\build.py", line 54, in build
  File "site-packages\docker\utils\utils.py", line 103, in tar
  File "tarfile.py", line 2006, in add
  File "tarfile.py", line 1878, in gettarinfo
WindowsError: [Error 123] The filename, directory name, or volume label syntax is incorrect: 'C:\\[redacted]\\?.jpg'
```

The actual file name is `∆.jpg` (don't ask why). This looks like the same issue in http://stackoverflow.com/questions/11545185/handling-utf-filenames-in-python

**Comment by BYK** [comment]
I've installed the project using Python 3.5.1 and it seems to be working without any issues.

**Comment by saurabsa** [comment]
I am getting the above error in **Mac**:
docker-compose -f /Users/saurabhsarkar/Documents/ASPNetCore/Console☃App/docker-compose.debug.yml down
/var/folders/sj/k148ghk548v7b8lqf_4yd41m0000gn/T/_MEIpZB1OL/compose/config/config.py:222: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
Traceback (most recent call last):
  File "<string>", line 3, in <module>
  File "compose/cli/main.py", line 61, in main
  File "compose/cli/main.py", line 110, in perform_command
  File "compose/cli/command.py", line 35, in project_from_options
  File "compose/cli/command.py", line 98, in get_project
  File "compose/config/config.py", line 234, in find
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 49: ordinal not in range(128)
docker-compose returned -1
_[using **docker-compose version 1.8.0, build f3628c7**]_

On **Windows** when I am running the command on Powershell or cmd:
docker-compose -f "C:\Users\saurabsa\documents\visual studio 2015\Projects\WebApplication☃3\src\WebApplication☃3\docker-compose.yml" down
its throwing the error:
RROR: .IOError: [Errno 22] invalid mode ('r') or filename: 'C:\\Users\\saurabsa\\documents\\visual studio 2015\\Projects\\WeApplication?3\\src\\WebApplication?3\\docker-compose.yml'
_[using **docker-compose version 1.8.0, build d988a55**]_

**Comment by marciusvinicius** [comment]
same error here when I try build a project who mount a volume with a file with special character.

```WindowsError: [Error 123] The filename, directory name, or volume label syntax is incorrect: 'C:\\Users\\marci\\Documents\\GitHub\\Walletsaver\\bestarnew\\test\\data\\suggestion?067927c0-ad49-11e6-84cd-b797ecf45ea3.json```

**Comment by happiness801** [comment]
@BYK For a work around, how do you "install the project using Python 3.5.1"?

**Comment by BYK** [comment]
@happiness801 it's been a long time but I think I did `pip install git+https://github.com/docker/compose.git`
