### ISSUE TITLE
'NoneType' object is not callable on shutdown

### ISSUE THREAD

**Issue by skrysmanski** [docker/compose#3893]
I just got this error (running version 1.8.0, build f3628c7):

```
pxeboot_1  | dnsmasq: exiting on receipt of SIGTERM
pxedocker_pxeboot_1 exited with code 0
Exception in thread Thread-3 (most likely raised during interpreter shutdown):
Traceback (most recent call last):
  File "threading.py", line 810, in __bootstrap_inner
  File "threading.py", line 763, in run
  File "compose/cli/log_printer.py", line 190, in watch_events
  File "compose/project.py", line 343, in events
  File "site-packages/docker/client.py", line 245, in _stream_helper
  File "site-packages/requests/packages/urllib3/response.py", line 243, in read
  File "httplib.py", line 549, in read
  File "httplib.py", line 593, in _read_chunked
<type 'exceptions.TypeError'>: 'NoneType' object is not callable
```

Happened when I called `docker-compose down`.

**Comment by shin-** [comment]
It looks like a bug in `httplib`. Are you able to reproduce consistently?

**Comment by bamarni** [comment]
I've also hit this by sending sigint, docker-compose was running in the foreground :

```
^CGracefully stopping... (press Ctrl+C again to force)
Stopping api_orders_1 ... done
Stopping api_mongo_1 ... done
Stopping api_rabbit_1 ... done
Exception in thread Thread-7 (most likely raised during interpreter shutdown):
Traceback (most recent call last):
  File "threading.py", line 810, in __bootstrap_inner
  File "threading.py", line 763, in run
  File "compose/cli/log_printer.py", line 197, in watch_events
  File "compose/project.py", line 356, in events
  File "compose/container.py", line 42, in from_id
  File "site-packages/docker/utils/decorators.py", line 21, in wrapped
  File "site-packages/docker/api/container.py", line 197, in inspect_container
  File "site-packages/docker/utils/decorators.py", line 47, in inner
  File "site-packages/docker/client.py", line 139, in _get
  File "site-packages/requests/sessions.py", line 477, in get
  File "site-packages/requests/sessions.py", line 436, in request
<type 'exceptions.TypeError'>: 'NoneType' object is not callable
```

After upping and stopping again, the error was a bit different :
```
Exception in thread Thread-7 (most likely raised during interpreter shutdown):
Traceback (most recent call last):
  File "threading.py", line 810, in __bootstrap_inner
  File "threading.py", line 763, in run
  File "compose/cli/log_printer.py", line 197, in watch_events
  File "compose/project.py", line 356, in events
  File "compose/container.py", line 42, in from_id
  File "site-packages/docker/utils/decorators.py", line 21, in wrapped
  File "site-packages/docker/api/container.py", line 197, in inspect_container
  File "site-packages/docker/utils/decorators.py", line 47, in inner
  File "site-packages/docker/client.py", line 139, in _get
  File "site-packages/requests/sessions.py", line 477, in get
  File "site-packages/requests/sessions.py", line 465, in request
  File "site-packages/requests/sessions.py", line 573, in send
  File "site-packages/requests/adapters.py", line 414, in send
<type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'error'
```

It seems very random, the third time didn't produce any error, then the fourth I had the second error, and since then I'm not able to reproduce anymore :) (however I didn't change anything in docker-compose.yml or my application accross all those retries)

```
docker-compose version 1.8.1, build 878cff1
docker-py version: 1.10.3
CPython version: 2.7.9
OpenSSL version: OpenSSL 1.0.1e 11 Feb 2013
```
