### ISSUE TITLE
IOError: [Errno 22] invalid mode ('rb') or filename

### ISSUE THREAD

**Issue by netroby** [docker/compose#3902]
```
PS D:\workspace\hzfeng\deyihome-phpsource> docker-compose up -d
Building db
Traceback (most recent call last):
  File "<string>", line 3, in <module>
  File "compose\cli\main.py", line 61, in main
  File "compose\cli\main.py", line 113, in perform_command
  File "compose\cli\main.py", line 835, in up
  File "compose\project.py", line 382, in up
  File "compose\service.py", line 305, in ensure_image_exists
  File "compose\service.py", line 727, in build
  File "site-packages\docker\api\build.py", line 54, in build
  File "site-packages\docker\utils\utils.py", line 103, in tar
  File "tarfile.py", line 2021, in add
IOError: [Errno 22] invalid mode ('rb') or filename: 'D:\\...\\public\\mas\\node_modu
es\\.bin\\cake'
docker-compose returned -1
```

**Comment by netroby** [comment]
I can confirm the file exists . and i can copy file to another location

**Comment by shin-** [comment]
Thanks for the report. Would you potentially be able to share the Dockerfile for this build?

**Comment by netroby** [comment]
```
FROM mysql:5.7
ADD ./sqls/01-all-prod.sql /docker-entrypoint-initdb.d/
```

**Comment by netroby** [comment]
```
FROM nginx
ADD ./etc/site.conf /etc/nginx/conf.d/site.conf
```

**Comment by shin-** [comment]
I'll try and debug this on a Windows system soon. Thanks for being patient!

**Comment by shin-** [comment]
Hey @netroby , if I'm reading your original report correctly, it seems that you have a folder in there called
```
node_modu
es
```

with a carriage return in it. If so, that is an invalid character for a folder name in Windows. While I don't know how it happened to be created in the first place, I'm afraid we can't support this use case even if we wanted to.

Please let me know if I'm mistaken and that is not the case.

**Comment by withinboredom** [comment]
I'm also seeing this: 

```
Creating network "caddyphp_default" with the default driver
Building php
Traceback (most recent call last):
  File "<string>", line 3, in <module>
  File "compose\cli\main.py", line 65, in main
  File "compose\cli\main.py", line 117, in perform_command
  File "compose\cli\main.py", line 849, in up
  File "compose\project.py", line 382, in up
  File "compose\service.py", line 309, in ensure_image_exists
  File "compose\service.py", line 742, in build
  File "site-packages\docker\api\build.py", line 55, in build
  File "site-packages\docker\utils\utils.py", line 95, in tar
  File "tarfile.py", line 2022, in add
IOError: [Errno 22] invalid mode ('rb') or filename: 'C:\\Users\\withi\\code\\caddy-php\\src\\vendor\\bin\\aerys'
```

It happens that the file in question is a bash for windows installed symlink using docker-compose for windows native.

**Comment by joshuacc** [comment]
I am also experiencing this problem with symlinks on a Windows 7 host using Docker Toolbox.

```
$ docker-compose up
Building front
Traceback (most recent call last):
  File "<string>", line 3, in <module>
  File "compose\cli\main.py", line 62, in main
  File "compose\cli\main.py", line 114, in perform_command
  File "compose\cli\main.py", line 835, in up
  File "compose\project.py", line 382, in up
  File "compose\service.py", line 305, in ensure_image_exists
  File "compose\service.py", line 727, in build
  File "site-packages\docker\api\build.py", line 55, in build
  File "site-packages\docker\utils\utils.py", line 95, in tar
  File "tarfile.py", line 2022, in add
IOError: [Errno 22] invalid mode ('rb') or filename: 'c:\\Users\\NAME\\Documents\\GitHub\\PROJECT\\node_modules\\.bi
n\\acorn'
docker-compose returned -1
```

The file `acorn` above is alphabetically the first symlink in a directory full of symlinks.

**Comment by shin-** [comment]
I believe this should be fixed by the recent changes we made to build in https://github.com/docker/docker-py/pull/1825

Please ping me if this is still an issue on 1.19.0+ and I'll take a closer look again.
