### ISSUE TITLE
`docker-compose up` seems to hang every time on Windows

### ISSUE THREAD

**Issue by PsychoThinker** [docker/compose#3984]
docker version

```
Client:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 17:52:38 2016
 OS/Arch:      windows/amd64

Server:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 17:52:38 2016
 OS/Arch:      linux/amd64
```

docker-compose.yml

```
version: '2'
services:
    hello:
        image: tutum/hello-world
        ports:
            - "80:80"
```

docker-compose --verbose up

```
compose.config.config.find: Using configuration files: .\docker-compose.yml
docker.auth.auth.load_config: Found 'credsStore' section
compose.cli.command.get_client: docker-compose version 1.8.0, build d988a55
docker-py version: 1.9.0
CPython version: 2.7.11
OpenSSL version: OpenSSL 1.0.2d 9 Jul 2015
compose.cli.command.get_client: Docker base_url: http://127.0.0.1:2375
compose.cli.command.get_client: Docker version: KernelVersion=4.4.20-moby, Os=linux, BuildTime=2016-08-18T17:52:38.255390991+00:00, ApiVersion=1.24, Version=1.12.1, GitCommit=23cf638, Arch=amd64, GoVersion=go1.6.3
compose.cli.verbose_proxy.proxy_callable: docker info <- ()
compose.cli.verbose_proxy.proxy_callable: docker info -> {u'Architecture': u'x86_64',
 u'BridgeNfIp6tables': True,
 u'BridgeNfIptables': True,
 u'CPUSet': True,
 u'CPUShares': True,
 u'CgroupDriver': u'cgroupfs',
 u'ClusterAdvertise': u'',
 u'ClusterStore': u'',
 u'Containers': 6,
 u'ContainersPaused': 0,
...
compose.cli.verbose_proxy.proxy_callable: docker inspect_network <- (u'default_default')
compose.cli.verbose_proxy.proxy_callable: docker inspect_network -> {u'Containers': {},
 u'Driver': u'bridge',
 u'EnableIPv6': False,
 u'IPAM': {u'Config': [{u'Gateway': u'172.19.0.1/16',
                        u'Subnet': u'172.19.0.0/16'}],
           u'Driver': u'default',
           u'Options': None},
 u'Id': u'8cfa51101b448d9b9c41774d41b77fdfc00aa56bdc3c5e40518c0e4b4b0946da',
 u'Internal': False,
 u'Labels': {},
...
compose.cli.verbose_proxy.proxy_callable: docker containers <- (all=False, filters={u'label': [u'com.docker.compose.project=default', u'com.docker.compose.oneoff=False']})
compose.cli.verbose_proxy.proxy_callable: docker containers -> (list with 0 items)
compose.cli.verbose_proxy.proxy_callable: docker containers <- (all=True, filters={u'label': [u'com.docker.compose.project=default', u'com.docker.compose.service=hello', u'com.docker.compose.oneoff=False']})
compose.cli.verbose_proxy.proxy_callable: docker containers -> (list with 1 items)
compose.cli.verbose_proxy.proxy_callable: docker inspect_container <- (u'75883080f9e0664e87b61a95698c050257e681581b600b4b39c91fcde17c3e59')
compose.cli.verbose_proxy.proxy_callable: docker inspect_container -> {u'AppArmorProfile': u'',
 u'Args': [u'-c',
           u'php-fpm -d variables_order="EGPCS" && (tail -F /var/log/nginx/access.log &) && exec nginx -g "daemon off;"'],
 u'Config': {u'AttachStderr': False,
             u'AttachStdin': False,
             u'AttachStdout': False,
             u'Cmd': [u'/bin/sh',
                      u'-c',
                      u'php-fpm -d variables_order="EGPCS" && (tail -F /var/log/nginx/access.log &) && exec nginx -g "daemon off;"'],
             u'Domainname': u'',
...
compose.cli.verbose_proxy.proxy_callable: docker inspect_image <- ('tutum/hello-world')
compose.cli.verbose_proxy.proxy_callable: docker inspect_image -> {u'Architecture': u'amd64',
 u'Author': u'support@tutum.co',
 u'Comment': u'',
 u'Config': {u'AttachStderr': False,
             u'AttachStdin': False,
             u'AttachStdout': False,
             u'Cmd': [u'/bin/sh',
                      u'-c',
                      u'php-fpm -d variables_order="EGPCS" && (tail -F /var/log/nginx/access.log &) && exec nginx -g "daemon off;"'],
             u'Domainname': u'',
...
compose.cli.verbose_proxy.proxy_callable: docker containers <- (all=True, filters={u'label': [u'com.docker.compose.project=default', u'com.docker.compose.service=hello', u'com.docker.compose.oneoff=False']})
compose.cli.verbose_proxy.proxy_callable: docker containers -> (list with 1 items)
compose.cli.verbose_proxy.proxy_callable: docker inspect_image <- ('tutum/hello-world')
compose.cli.verbose_proxy.proxy_callable: docker inspect_image -> {u'Architecture': u'amd64',
 u'Author': u'support@tutum.co',
 u'Comment': u'',
 u'Config': {u'AttachStderr': False,
             u'AttachStdin': False,
             u'AttachStdout': False,
             u'Cmd': [u'/bin/sh',
                      u'-c',
                      u'php-fpm -d variables_order="EGPCS" && (tail -F /var/log/nginx/access.log &) && exec nginx -g "daemon off;"'],
             u'Domainname': u'',
...
compose.cli.verbose_proxy.proxy_callable: docker inspect_container <- (u'75883080f9e0664e87b61a95698c050257e681581b600b4b39c91fcde17c3e59')
compose.cli.verbose_proxy.proxy_callable: docker inspect_container -> {u'AppArmorProfile': u'',
 u'Args': [u'-c',
           u'php-fpm -d variables_order="EGPCS" && (tail -F /var/log/nginx/access.log &) && exec nginx -g "daemon off;"'],
 u'Config': {u'AttachStderr': False,
             u'AttachStdin': False,
             u'AttachStdout': False,
             u'Cmd': [u'/bin/sh',
                      u'-c',
                      u'php-fpm -d variables_order="EGPCS" && (tail -F /var/log/nginx/access.log &) && exec nginx -g "daemon off;"'],
             u'Domainname': u'',
...
compose.parallel.feed_queue: Pending: set([<Service: hello>])
compose.parallel.feed_queue: Starting producer thread for <Service: hello>
compose.service.start_container_if_stopped: Starting default_hello_1
compose.cli.verbose_proxy.proxy_callable: docker attach <- (u'75883080f9e0664e87b61a95698c050257e681581b600b4b39c91fcde17c3e59', stream=True, stderr=True, stdout=True)
compose.parallel.feed_queue: Pending: set([])
compose.parallel.feed_queue: Pending: set([])
compose.parallel.feed_queue: Pending: set([])
compose.parallel.feed_queue: Pending: set([])
compose.parallel.feed_queue: Pending: set([])
compose.parallel.feed_queue: Pending: set([])
compose.parallel.feed_queue: Pending: set([])
compose.parallel.feed_queue: Pending: set([])
compose.parallel.feed_queue: Pending: set([])
..
compose.parallel.feed_queue: Pending: set([])
compose.parallel.feed_queue: Pending: set([])
compose.parallel.feed_queue: Pending: set([])
compose.parallel.feed_queue: Pending: set([])
compose.parallel.feed_queue: Pending: set([])
compose.parallel.parallel_execute_iter: Failed: <Service: hello>
compose.parallel.feed_queue: Pending: set([])

ERROR: for hello  HTTPConnectionPool(host='127.0.0.1', port=2375): Read timed out. (read timeout=60)
Traceback (most recent call last):
  File "<string>", line 3, in <module>
  File "compose\cli\main.py", line 61, in main
  File "compose\cli\main.py", line 113, in perform_command
  File "contextlib.py", line 35, in __exit__
  File "compose\cli\errors.py", line 56, in handle_connection_errors
TypeError: log_timeout_error() takes exactly 1 argument (0 given)
docker-compose returned -1
```

I can invoke the same command on OSX without any problems (logs on the console appear immediately), also adding "-d" option on windows machine fixes the issue, but without it  i have "Read timed out." every time :(

**Comment by shin-** [comment]
Unfortunately, interactive mode on Windows is not currently supported. The good news is we plan to have it in the next release of the project. You can track progress for this issue here: #3194

**Comment by rwilliams** [comment]
How is this related to the interactive mode changes? I didn't think `up` was interactive by design.

**Comment by PsychoThinker** [comment]
@shin- it seems that these problems are not related - can I ask you to reopen this issue?

**Comment by aanand** [comment]
Does the following command work?

    docker run -p 80:80 tutum/hello-world

**Comment by PsychoThinker** [comment]
@aanand thank you

Yes, `docker run -p 80:80 tutum/hello-world` command works.

**Comment by shin-** [comment]
Sorry about my earlier message - I misidentified the issue.
@PsychoThinker Can you try upgrading to Compose 1.8.1 and see if it improves things?

**Comment by matsaleh13** [comment]
I just want to add that I ran into this same issue while diving deeper on https://github.com/docker/for-win/issues/113. 

I ran ```docker-compose -f docker-compose-test.yml --verbose up --build mongodbtest``` and got:

```
<snip>
compose.parallel.feed_queue: Pending: set([<Service: mongodbtest>])
compose.parallel.feed_queue: Starting producer thread for <Service: mongodbtest>
compose.service.start_container_if_stopped: Starting server_mongodbtest_1
compose.cli.verbose_proxy.proxy_callable: docker attach <- (u'8bdca183d0332607ab522d89251076022251fa884d568033633bed6d5eb0d72f', stream=True, stderr=True, stdout=True)
compose.parallel.feed_queue: Pending: set([])
compose.parallel.feed_queue: Pending: set([])

<snip>

compose.parallel.feed_queue: Pending: set([])
compose.parallel.parallel_execute_iter: Failed: <Service: mongodbtest>
compose.parallel.feed_queue: Pending: set([])

ERROR: for mongodbtest  HTTPConnectionPool(host='127.0.0.1', port=2375): Read timed out. (read timeout=60)
Traceback (most recent call last):
  File "<string>", line 3, in <module>
  File "compose\cli\main.py", line 61, in main
  File "compose\cli\main.py", line 113, in perform_command
  File "contextlib.py", line 35, in __exit__
  File "compose\cli\errors.py", line 56, in handle_connection_errors
TypeError: log_timeout_error() takes exactly 1 argument (0 given)
docker-compose returned -1
```
**docker version**
Client:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 17:52:38 2016
 OS/Arch:      windows/amd64

Server:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 17:52:38 2016
 OS/Arch:      linux/amd64

**docker-compose version** 
1.8.0, build d988a55
docker-py version: 1.9.0
CPython version: 2.7.11
OpenSSL version: OpenSSL 1.0.2d 9 Jul 2015

Following the above example, I ran the mongodbtest image  ```docker run mongo:3.0.7 ``` and it succeeded.

I will try using docker-compose 1.8.1 as suggested, but I just wanted to +1 the report by @PsychoThinker

**Comment by matsaleh13** [comment]
FYI I did upgrade to 1.8.1 and that fixed the python traceback:

E:\Dev\GitHub\vcme\phoenix-proto\server>docker-compose version
docker-compose version 1.8.1, build 004ddae
docker-py version: 1.10.3
CPython version: 2.7.12
OpenSSL version: OpenSSL 1.0.2h  3 May 2016

Didn't fix my timeout however, but I'm sure that's an entirely different thing. :)

**Comment by PsychoThinker** [comment]
@shin- I carried out my test on versions 1.8.1 and 1.9 (build 9db7acd) of docker-composer - I do not see any improvement.

**Comment by campbel** [comment]
Try setting http_proxy="" and then retrying. If this works then open Hyper_V manager and grab the IP for your Moby Linux VM and adding it to your NO_PROXY environment variable.

**Comment by PsychoThinker** [comment]
@campbel I'm not sure if I am doing it correctly, but following change in docker settings is not a solution to my problem:

![docker_settings](https://cloud.githubusercontent.com/assets/17953552/20055950/f9ea875a-a4e3-11e6-9436-7a0fb4d2ed25.png)

I still have: "HTTPConnectionPool(host='127.0.0.1', port=2375): Read timed out." when I call "docker-compose up" without "-d" parameter

**Comment by PsychoThinker** [comment]
@aanand It seems that this problem no longer exists in the latest version of the docker-compose (1.10.0)

**Comment by aravindravva** [comment]
no it exists even now
