### ISSUE TITLE
docker-compose up can't run my app because filename contains special character å

### ISSUE THREAD

**Issue by piqoni** [docker/compose#4055]
I am on Windows 7 using docker-compose version 1.8.1, build 004ddae.

My file has a name of  **blå.jpg** and docker-compose up fails as below:

$ docker-compose up -d
Building web
Traceback (most recent call last):
  File "<string>", line 3, in <module>
  File "compose\cli\main.py", line 62, in main
  File "compose\cli\main.py", line 114, in perform_command
  File "compose\cli\main.py", line 835, in up
  File "compose\project.py", line 382, in up
  File "compose\service.py", line 305, in ensure_image_exists
  File "compose\service.py", line 727, in build
  File "site-packages\docker\api\build.py", line 55, in build
  File "site-packages\docker\utils\utils.py", line 95, in tar
  File "tarfile.py", line 2007, in add
  File "tarfile.py", line 1879, in gettarinfo
**WindowsError: [Error 2] The system cannot find the file specified: 'C:\Users\U
ser\project\image\bla\xb0.jpg'**
docker-compose returned -1

Any suggestion?

**Comment by shin-** [comment]
Is that a carriage return in your path?
```
C:\Users\U
ser\project\image\bla\xb0.jpg'
```

**Comment by piqoni** [comment]
Sorry, that is the newline copy pasted from cmd. Im positive the issue has to do with unicode characters because when I rename given file, it throws the error on another filename that has such characters.

**Comment by shin-** [comment]
@piqoni Thanks for confirming. Looks like the same issue as #3870

**Comment by piqoni** [comment]
For others that might encounter the same, my workaround was:
Reinstalling docker-compose using Python 3 (via pip), get **docker-compose.exe** and **docker-compose-script.py** from Python's Scripts directory and paste them to the Docker Toolbox directory, since I am using the toolbox.  
That worked.

**Comment by FabianKoestring** [comment]
Same Problem over here.
