### ISSUE TITLE
Working with multiple Windows containers: All pipe instances are busy.

### ISSUE THREAD

**Issue by StefanScherer** [docker/compose#4082]
It seems that running up multiple windows containers in parallel result in a problem using the named pipes.

### versions used

```
PS C:\xxxx> docker-compose --version
docker-compose version 1.9.0-rc1, build 28788bd
PS C:\xxxx> docker version
Client:
 Version:      1.12.2-cs2-ws-beta
 API version:  1.25
 Go version:   go1.7.1
 Git commit:   050b611
 Built:        Tue Oct 11 02:35:40 2016
 OS/Arch:      windows/amd64

Server:
 Version:      1.12.2-cs2-ws-beta
 API version:  1.25
 Go version:   go1.7.1
 Git commit:   050b611
 Built:        Tue Oct 11 02:35:40 2016
 OS/Arch:      windows/amd64
PS C:\xxxx> ls env:DOCKER_HOST
ls : Cannot find path 'DOCKER_HOST' because it does not exist.
At line:1 char:1
+ ls env:DOCKER_HOST
+ ~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (DOCKER_HOST:String) [Get-ChildItem], ItemNotFoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetChildItemCommand
PS C:\> docker info
Containers: 7
 Running: 0
 Paused: 0
 Stopped: 7
Images: 12
Server Version: 1.12.2-cs2-ws-beta
Storage Driver: windowsfilter
 Windows:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: nat null overlay
Swarm: inactive
Default Isolation: process
Kernel Version: 10.0 14393 (14393.321.amd64fre.rs1_release_inmarket.161004-2338)
Operating System: Windows Server 2016 Standard Evaluation
OSType: windows
Architecture: x86_64
CPUs: 2
Total Memory: 5.953 GiB
Name: win-docker
ID: NB2R:NMW5:X6KW:VEX5:PW7C:PKP5:ORCZ:RJTL:IJQA:RVAS:AEKT:QGBW
Docker Root Dir: C:\ProgramData\docker
Debug Mode (client): false
Debug Mode (server): false
Username: comguest
Registry: https://index.docker.io/v1/
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

### test docker-compose up and kill

```
PS C:\xxxx> docker-compose up -d
Creating xxxx_db_1
Creating xxxx_consul_1
Creating xxxx_servicexyz_1
Creating xxxx_serivcefoo_1
Creating xxxx_serviceklm_1
Creating xxxx_servicebar_1
Creating xxxx_serviceabc_1

ERROR: for servicexyz  (231, 'CreateFile', 'All pipe instances are busy.')

ERROR: for checkout  (231, 'CreateFile', 'All pipe instances are busy.')

ERROR: for bodyscanner  (231, 'CreateFile', 'All pipe instances are busy.')

ERROR: for notifier  (231, 'CreateFile', 'All pipe instances are busy.')
Traceback (most recent call last):
  File "<string>", line 3, in <module>
  File "compose\cli\main.py", line 64, in main
  File "compose\cli\main.py", line 116, in perform_command
  File "compose\cli\main.py", line 848, in up
  File "compose\project.py", line 400, in up
  File "compose\parallel.py", line 64, in parallel_execute
pywintypes.error: (231, 'CreateFile', 'All pipe instances are busy.')
docker-compose returned -1
PS C:\xxxx> docker-compose ps
        Name                       Command               State                                                Ports
----------------------------------------------------------------------------------------------------------------------------------------------------------------
xxxx_servicebar_1       c:\run.cmd /code/bin/app.js      Up       0.0.0.0:515->515/tcp                      
xxxx_consul_1        \consul.exe agent -config- ...   Up       0.0.0.0:8300->8300/tcp, 0.0.0.0:8301->8301/tcp, 0.0.0.0:8301->8301/udp, 0.0.0.0:8500->8500/tcp
xxxx_db_1            mongod --config /etc/mongo ...   Up       0.0.0.0:27017->27017/tcp                  
xxxx_serviceabc_1    c:\run.cmd /code/bin/app.js      Up       0.0.0.0:1978->1978/tcp                    
xxxx_serivcefoo_1   c:\run.cmd /code/bin/app.js      Up                                                 
xxxx_servicexyz_1    c:\run.cmd /code/bin/app.js      Exit 0                                             
xxxx_serviceklm_1          c:\run.cmd /code/bin/app.js      Up       0.0.0.0:8080->8080/tcp                    
PS C:\xxxx> docker-compose kill
Killing xxxx_serviceabc_1 ... done
Killing xxxx_servicebar_1 ... done
Killing xxxx_serviceklm_1 ...
Killing xxxx_serivcefoo_1 ... done
Killing xxxx_consul_1 ... done
Killing xxxx_db_1 ... done

ERROR: for xxxx_serviceklm_1  (231, 'CreateFile', 'All pipe instances are busy.')
Traceback (most recent call last):
  File "<string>", line 3, in <module>
  File "compose\cli\main.py", line 64, in main
  File "compose\cli\main.py", line 116, in perform_command
  File "compose\cli\main.py", line 493, in kill
  File "compose\project.py", line 269, in kill
  File "compose\parallel.py", line 250, in parallel_kill
  File "compose\parallel.py", line 229, in parallel_operation
  File "compose\parallel.py", line 64, in parallel_execute
pywintypes.error: (231, 'CreateFile', 'All pipe instances are busy.')
docker-compose returned -1
PS C:\xxxx> docker-compose kill
Killing xxxx_serviceklm_1 ... done
```

**Comment by StefanScherer** [comment]
Workaround: Still use TCP

```
PS C:\xxxx> $env:DOCKER_HOST="tcp://127.0.0.1:2376"
PS C:\xxxx> $env:DOCKER_TLS_VERIFY=1
PS C:\xxxx> docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
PS C:\xxxx> docker-compose up -d
Starting xxxx_consul_1
Starting xxxx_db_1
Creating xxxx_xx1_1
Starting xxxx_xx2_1
Starting xxxx_xx3_1
Starting xxxx_xx4_1
Starting xxxx_xx5_1
Starting xxxx_xx6_1
Creating xxxx_xx7_1
Creating xxxx_xx8_1
```

**Comment by shin-** [comment]
@StefanScherer Thanks for the report - We fixed it in RC2 yesterday :)

Related: https://github.com/docker/docker-py/pull/1274

**Comment by StefanScherer** [comment]
Thanks! Wow, that was fast! I've updated compose today.
