### ISSUE TITLE
Working with multiple Windows containers: The semaphore timeout period has expired.

### ISSUE THREAD

**Issue by StefanScherer** [docker/compose#4089]
Starting twelve containers with docker-compose 1.9.0-rc2 still shows a problem. Follow up of #4082 

```
PS C:\xxxxx> docker-compose up -d
Creating xxxxx_consul_1
Creating xxxxx_db_1
Creating xxxxx_service1_1
Creating xxxxx_service2_1
Creating xxxxx_service3_1
Creating xxxxx_service4_1
Creating xxxxx_service5_1
Creating xxxxx_cli_1

ERROR: for service6  (121, 'WaitNamedPipe', 'The semaphore timeout period has expired.')

ERROR: for service7  (121, 'WaitNamedPipe', 'The semaphore timeout period has expired.')

ERROR: for service8  (121, 'WaitNamedPipe', 'The semaphore timeout period has expired.')

ERROR: for service9  (121, 'WaitNamedPipe', 'The semaphore timeout period has expired.')

ERROR: for service3  (121, 'WaitNamedPipe', 'The semaphore timeout period has expired.')
Traceback (most recent call last):
  File "<string>", line 3, in <module>
  File "compose\cli\main.py", line 65, in main
  File "compose\cli\main.py", line 117, in perform_command
  File "compose\cli\main.py", line 849, in up
  File "compose\project.py", line 400, in up
  File "compose\parallel.py", line 64, in parallel_execute
pywintypes.error: (121, 'WaitNamedPipe', 'The semaphore timeout period has expired.')
docker-compose returned -1
PS C:\xxxxx> docker-compose --version
docker-compose version 1.9.0-rc2, build d41f869
```

**Comment by shin-** [comment]
Thanks for reporting. Haven't seen that one before.

**Comment by shin-** [comment]
From a quick research, it seems that error usually appears when the client can not reach the server through the named pipe - any chance your Docker Engine might have errored out or been down during that test for some reason? Can you reproduce consistently?

Thanks

**Comment by StefanScherer** [comment]
I can reproduce it. Tried today starting 6 services at once and got the same error. Docker engine does not show any errors in Event log.

I also checked with
```powershell
iwr https://github.com/Microsoft/Virtualization-Documentation/raw/master/windows-server-container-tools/Debug-ContainerHost/Debug-ContainerHost.ps1 -UseBasicParsing | iex
```

Windows Defender is running with high CPU load in background. Trying to turn it off.

**Comment by shin-** [comment]
@StefanScherer Thanks for the feedback. I'll try and reproduce.

**Comment by shin-** [comment]
I identified the issue: docker/docker-py#1284 (Fix PR: docker/docker-py#1285)

**Comment by shin-** [comment]
@StefanScherer Do you mind testing [this build](https://ci.appveyor.com/project/docker/compose/build/master-2528/artifacts) to make sure it fixes the issue for you as well?

**Comment by StefanScherer** [comment]
@shin- 

I tried it and tested with all twelve services I want to start in one call.

```
PS C:\xxx> docker-compose up -d
Creating xxx_serv1_1
Creating xxx_serv2_1
Creating xxx_serv3_1
Creating xxx_serv4_1
Creating xxx_serv5_1
Creating xxx_serv6_1
Creating xxx_serv7_1
Creating xxx_serv8_1
Creating xxx_serv9_1
Creating xxx_serva_1
Creating xxx_servb_1
Creating xxx_servc_1

ERROR: for importconfig  Cannot start service importconfig: container 7bf4c46d6aebb4243e4b94fb5ca34c1b6595f8c7b0e9530482c8afc3d8586e6b encountered an error during Start: failure in a Windows system call: This operation returned because the timeout period expired. (0x5b4)

ERROR: for checkin  Cannot start service checkin: container 39970ab23997770c91734967815e0935ff2434ed986231411c0f050401c49e5f encountered an error during Start: failure in a Windows system call: This operation returned because the timeout period expired. (0x5b4)

ERROR: for dispatcher  Cannot start service dispatcher: container e648b58ecd3deb6b7c593d090439550637527a910eb7980391bfbef859845739 encountered an error during Start: failure in a Windows system call: This operation returned because the timeout period expired. (0x5b4)

ERROR: for rest  Cannot start service rest: container cdaeea867da110248cd588ed08b6cd3ca924c502e6cec11175cc488510aa190c encountered an error during Start: failure in a Windows system call: This operation returned because the timeout period expired. (0x5b4)
ERROR: Encountered errors while bringing up the project.
```

Eight services are up and running and four haven't made it.
But it's much better than in previous versions.

**Comment by shin-** [comment]
Thank you for testing. Could you estimate how long it takes for those
messages to appear? The start operation is obviously timing out, but I
wonder what the threshold is.

**Comment by StefanScherer** [comment]
Wow, stopping some other Windows VM's on my MBP and restarting the Win2016 VM it got way better.

```
PS C:\xxx> filter timestamp {"$(Get-Date -Format o): $_"}
PS C:\xxx> docker-compose up -d 2>&1 | timestamp
2016-11-03T11:15:31.1634373-07:00: Creating xxx_serv1_1
2016-11-03T11:15:31.1653775-07:00: Creating xxx_serv2_1
2016-11-03T11:15:31.1683067-07:00: Creating xxx_serv3_1
2016-11-03T11:15:33.4510426-07:00: Creating xxx_serv4_1
2016-11-03T11:15:33.6257937-07:00: Creating xxx_serv5_1
2016-11-03T11:15:33.8718397-07:00: Creating xxx_serv6_1
2016-11-03T11:15:33.8874592-07:00: Creating xxx_serv7_1
2016-11-03T11:15:33.9138359-07:00: Creating xxx_serv8_1
2016-11-03T11:15:33.9421358-07:00: Creating xxx_serv9_1
2016-11-03T11:15:33.9655713-07:00: Creating xxx_serva_1
2016-11-03T11:15:33.9724023-07:00: Creating xxx_servb_1
2016-11-03T11:15:33.9743804-07:00: Creating xxx_servc_1
2016-11-03T11:15:41.6953853-07:00: Creating xxx_servd_1
```


And tried it again to measure the whole time:

```
PS C:\xxx> Measure-Command { docker-compose up -d }


Days              : 0
Hours             : 0
Minutes           : 0
Seconds           : 10
Milliseconds      : 908
Ticks             : 109085109
TotalDays         : 0.000126255913194444
TotalHours        : 0.00303014191666667
TotalMinutes      : 0.181808515
TotalSeconds      : 10.9085109
TotalMilliseconds : 10908.5109
```

And all services are up and running. So there was some other high CPU load earlier that caused the timeouts.

**Comment by shin-** [comment]
Ah, that's good to hear. Thank you!

**Comment by StefanScherer** [comment]
Thanks!
