### ISSUE TITLE
'NoneType' object has no attribute 'get'

### ISSUE THREAD

**Issue by watnotte** [docker/compose#4103]
I just upgraded to the latest beta version:

```
docker -v
Docker version 1.12.3, build 6b644ec, experimental

docker-compose -v
docker-compose version 1.9.0-rc2, build a2da43b
```

docker-compose was working fine just previous to the upgrade but now it just spits out:

```
docker-compose up
Traceback (most recent call last):
  File "<string>", line 3, in <module>
  File "compose/cli/main.py", line 65, in main
  File "compose/cli/main.py", line 114, in perform_command
  File "compose/cli/command.py", line 36, in project_from_options
  File "compose/cli/command.py", line 103, in get_project
  File "compose/config/config.py", line 323, in load
  File "compose/config/config.py", line 416, in load_services
  File "compose/config/config.py", line 395, in build_services
  File "compose/config/config.py", line 380, in build_service
  File "compose/config/config.py", line 484, in run
  File "compose/config/config.py", line 528, in resolve_extends
  File "compose/config/config.py", line 774, in merge_service_dicts
  File "compose/config/config.py", line 728, in merge_field
  File "compose/config/config.py", line 807, in merge_logging
  File "compose/config/config.py", line 750, in merge_scalar
AttributeError: 'NoneType' object has no attribute 'get'
docker-compose returned -1
```

**Comment by shin-** [comment]
Thanks for the report! Can you share your compose file(s) so we can pinpoint the issue?

**Comment by srgrn** [comment]
I have the same issue. 
see the attached files they contain docker-compose and docker-compose.override that are the smallest i managed to create that reproduce this issue, seems to be related to the logging part (atleast in my own configuration)

[Archive.zip](https://github.com/docker/compose/files/569081/Archive.zip)

**Comment by awesomescot** [comment]
I'm seeing a very similar issue.  Same error message.  I'm only seeing it when I add a service that extends another though.  If I take the new service out of the docker-compose.yml file, it works fine.  Any ideas?
Docker version 1.12.3, build 6b644ec
docker-compose version 1.9.0-rc2, build a2da43b

**Comment by shin-** [comment]
@awesomescot Does the service you're overriding have a `logging` section in either the base or override? If so, #4113 fixes this. As a workaround until that fix makes it into a release, you can define an empty `logging: {}` section where it's absent.

**Comment by awesomescot** [comment]
Yes, the parent service has a logging section.  I've given up on the extends.  But thanks for the help.
