### ISSUE TITLE
docker-compose.yml merge broken

### ISSUE THREAD

**Issue by hc2p** [docker/compose#4108]
when i want to merge two docker-compose.yml i get following error with the current beta 1.12.3-beta29.3 (619507e)

    docker-compose -f ../docker-compose.yml -f docker-compose.yml up myService

```
Traceback (most recent call last):
  File "<string>", line 3, in <module>
  File "compose/cli/main.py", line 65, in main
  File "compose/cli/main.py", line 114, in perform_command
  File "compose/cli/command.py", line 36, in project_from_options
  File "compose/cli/command.py", line 103, in get_project
  File "compose/config/config.py", line 323, in load
  File "compose/config/config.py", line 414, in load_services
  File "compose/config/config.py", line 405, in merge_services
  File "compose/config/config.py", line 405, in <dictcomp>
  File "compose/config/config.py", line 704, in merge_service_dicts_from_files
  File "compose/config/config.py", line 774, in merge_service_dicts
  File "compose/config/config.py", line 728, in merge_field
  File "compose/config/config.py", line 807, in merge_logging
  File "compose/config/config.py", line 749, in merge_scalar
  File "compose/config/config.py", line 720, in needs_merge
TypeError: argument of type 'NoneType' is not iterable
docker-compose returned -1
```

diagnostic id: E9B25A88-ABE3-46AF-B578-39A426964940

**Comment by shin-** [comment]
Thanks for the report!

Related: #4103

**Comment by WillaLuo** [comment]
Hi, I also have the same problem
-bash-4.1$ docker version
Client:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   b9264d4
 Built:
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   b9264d4
 Built:
 OS/Arch:      linux/amd64

-bash-4.1$ docker-compose version
docker-compose version 1.9.0, build 2585387
docker-py version: 1.10.6
CPython version: 2.7.9
OpenSSL version: OpenSSL 1.0.1t  3 May 2016

Thanks!

**Comment by khvn26** [comment]
Regression on docker-compose version 1.24.0-rc1, build 0f3d4dda

```
  docker-compose up                                                           SIGINT(2) ↵  4313  21:36:02
Traceback (most recent call last):
  File "docker-compose", line 6, in <module>
  File "compose/cli/main.py", line 71, in main
  File "compose/cli/main.py", line 124, in perform_command
  File "compose/cli/command.py", line 42, in project_from_options
  File "compose/cli/command.py", line 115, in get_project
  File "compose/config/config.py", line 404, in load
  File "compose/config/config.py", line 504, in load_services
  File "compose/config/config.py", line 483, in build_services
  File "compose/config/config.py", line 483, in <listcomp>
  File "compose/config/config.py", line 466, in build_service
  File "compose/config/config.py", line 584, in run
  File "compose/config/config.py", line 637, in resolve_extends
  File "compose/config/config.py", line 1064, in merge_service_dicts
  File "compose/config/config.py", line 1020, in merge_field
  File "compose/config/config.py", line 1176, in merge_networks
  File "compose/config/config.py", line 1015, in merge_field
  File "compose/config/config.py", line 1012, in needs_merge
TypeError: argument of type 'NoneType' is not iterable
[93622] Failed to execute script docker-compose
```

**Comment by burci** [comment]
There is a separate bug ticket for this: #6525
