### ISSUE TITLE
Overflow Error Python int too large to convert to C long

### ISSUE THREAD

**Issue by mtgerb** [docker/compose#4109]
After some long lines of debug output from a java application running in one of the docker containers docker-compose terminated with  an overflow error:

```
Traceback (most recent call last):
  File "<string>", line 3, in <module>
  File "compose\cli\main.py", line 62, in main
  File "compose\cli\main.py", line 114, in perform_command
  File "compose\cli\main.py", line 848, in up
  File "compose\cli\log_printer.py", line 87, in run
  File "compose\cli\log_printer.py", line 229, in consume_queue
OverflowError: Python int too large to convert to C long
docker-compose returned -1
```

The docker containers started by docker-compose are still running, but docker-compose terminated with the error message above.

I am using docker toolbox 12.2 on windows 10 with virtualbox. Output of docker-compose version:
```
docker-compose version 1.8.1, build 004ddae
docker-py version: 1.10.3
CPython version: 2.7.12
OpenSSL version: OpenSSL 1.0.2h  3 May 2016
```

**Comment by danielalves** [comment]
Same error here. After a very long debug output string:
```
Traceback (most recent call last):
  File "<string>", line 3, in <module>
  File "compose/cli/main.py", line 65, in main
  File "compose/cli/main.py", line 117, in perform_command
  File "compose/cli/main.py", line 862, in up
  File "compose/cli/log_printer.py", line 87, in run
  File "compose/cli/log_printer.py", line 229, in consume_queue
OverflowError: signed integer is greater than maximum
docker-compose returned -1
```
I'm running
```
dkc version
docker-compose version 1.9.0-rc4, build 181a4e9
docker-py version: 1.10.6
CPython version: 2.7.12
OpenSSL version: OpenSSL 1.0.2j  26 Sep 2016
```
on OSX Yosimite 10.10.5

**Comment by laurent-malvert** [comment]
Same issue here.

sample output:

```
logstashIndexer_1                     |             "log" => "2016-06-06 02:26:16,900 WARN  [][update-electronicsIndex-cronJob::de.hybris.platform.servicelayer.internal.jalo.ServicelayerJob][(update-electronicsIndex-cronJob) ][ENGINE] data commit failed\norg.hsqldb.HsqlException: file input/output error: /opt/hybris-commerce-suite/hybris/data/hsqldb/mydb.log\n\tat org.hsqldb.error.Error.error(Unknown Source)\n\tat org.hsqldb.error.Error.error(Unknown Source)\n\tat org.hsqldb.persist.Log.writeDeleteStatement(Unknown Source)\n\tat org.hsqldb.persist.Logger.writeDeleteStatement(Unknown Source)\n\tat org.hsqldb.persist.RowStoreAVLDisk.commitRow(Unknown Source)\n\tat org.hsqldb.TransactionManagerCommon.persistCommit(Unknown Source)\n\tat org.hsqldb.TransactionManagerMVCC.commitTransaction(Unknown Source)\n\tat org.hsqldb.Session.commit(Unknown Source)\n\tat org.hsqldb.Session.executeCompiledStatement(Unknown Source)\n\tat org.hsqldb.Session.execute(Unknown Source)\n\tat org.hsqldb.jdbc.JDBCPreparedStatement.fetchResult(Unknown Source)\n\tat org.hsqldb.jdbc.JDBCPreparedStatement.executeUpdate(Unknown Source)\n\tat de.hybris.platform.jdbcwrapper.PreparedStatementImpl.executeUpdate(PreparedStatementImpl.java:250)\n\tat de.hybris.platform.persistence.GenericBMPBean$GenericItemEntityState.storeChanges(GenericBMPBean.java:1593)\n\tat de.hybris.platform.persistence.GenericBMPBean.ejbStore(GenericBMPBean.java:307)\n\tat de.hybris.platform.persistence.framework.RemoteInvocationHandler.performOutsideTx(RemoteInvocationHandler.java:189)\n\tat de.hybris.platform.persistence.framework.RemoteInvocationHandler.performOther(RemoteInvocationHandler.java:164)\n\tat de.hybris.platform.persistence.framework.RemoteInvocationHandler.invoke(RemoteInvocationHandler.java:107)\n\tat com.sun.proxy.$Proxy47.setProperty(Unknown Source)\n\tat de.hybris.platform.persistence.ExtensibleItemEJBImpl.setProperty(ExtensibleItemEJBImpl.java:91)\n\tat de.hybris.platform.jalo.ExtensibleItem$1.compute(ExtensibleItem.java:288)\n\tat de.hybris.platform.jalo.Item$CachedSetter.set(Item.java:859)\n\tat de.hybris.platform.jalo.ExtensibleItem.setProperty(ExtensibleItem.java:290)\n\tat de.hybris.platform.jalo.ExtensibleItem.setProperty(ExtensibleItem.java:234)\n\tat de.hybris.platform.cronjob.jalo.CronJob.setStatus(CronJob.java:1475)\n\tat de.hybris.platform.cronjob.jalo.CronJob.setCronJobResult(CronJob.java:2070)\n\tat de.hybris.platform.cronjob.jalo.Job.execute(Job.java:1275)\n\tat de.hybris.platform.cronjob.jalo.Job.performImpl(Job.java:794)\n\tat de.hybris.platform.cronjob.jalo.Job.access$1(Job.java:747)\n\tat de.hybris.platform.cronjob.jalo.Job$JobRunable.run(Job.java:667)\n\tat de.hybris.platform.util.threadpool.PoolableThread.run(PoolableThread.java:198)",
logstashIndexer_1                     |        "@version" => "1",
logstashIndexer_1                     |            "host" => "36b47c272a2c",
Traceback (most recent call last):
  File "<string>", line 3, in <module>
  File "compose/cli/main.py", line 62, in main
  File "compose/cli/main.py", line 114, in perform_command
  File "compose/cli/main.py", line 848, in up
  File "compose/cli/log_printer.py", line 87, in run
  File "compose/cli/log_printer.py", line 229, in consume_queue
OverflowError: signed integer is greater than maximum
docker-compose returned -1
```

platform info:

```
$> docker version                                            255 master->!?
Client:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        Wed Oct 26 23:26:11 2016
 OS/Arch:      darwin/amd64

Server:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        Wed Oct 26 23:26:11 2016
 OS/Arch:      linux/amd64
```

**Comment by 92bondstreet** [comment]
Same issue on Yosemite 10.10.5 

```
❯ docker-compose version
docker-compose version 1.8.1, build 878cff1
docker-py version: 1.10.3
CPython version: 2.7.9
OpenSSL version: OpenSSL 1.0.2h  3 May 2016
```

```
 docker version
Client:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        Wed Oct 26 23:26:11 2016
 OS/Arch:      darwin/amd64

Server:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        Wed Oct 26 23:26:11 2016
 OS/Arch:      linux/amd64
```

**Comment by VincenzoFerme** [comment]
Same issue on Sierra 10.12.1

```
❯ docker-compose version
docker-compose version 1.9.0, build 2585387
docker-py version: 1.10.6
CPython version: 2.7.12
OpenSSL version: OpenSSL 1.0.2j  26 Sep 2016
```

```
❯ docker version
Client:
 Version:      1.13.0-rc3
 API version:  1.25
 Go version:   go1.7.3
 Git commit:   4d92237
 Built:        Tue Dec  6 01:15:44 2016
 OS/Arch:      darwin/amd64

Server:
 Version:      1.13.0-rc3
 API version:  1.25 (minimum version 1.12)
 Go version:   go1.7.3
 Git commit:   4d92237
 Built:        Tue Dec  6 01:15:44 2016
 OS/Arch:      linux/amd64
 Experimental: true
```

**Comment by myuseringithub** [comment]
How to solve it ?

**Comment by shin-** [comment]
Is this still happening with newer versions of Compose?

**Comment by creativeKoder** [comment]
yes
