### ISSUE TITLE
unexpected keyword argument 'environment'

### ISSUE THREAD

**Issue by piotrpalek** [docker/compose#4230]
Hey, I'm on Fedora 25 and I have this error when trying to run `docker-composed up`:

```Traceback (most recent call last):
  File "/usr/bin/docker-compose", line 9, in <module>
    load_entry_point('docker-compose==1.8.1', 'console_scripts', 'docker-compose')()
  File "/usr/lib/python2.7/site-packages/compose/cli/main.py", line 62, in main
    command()
  File "/usr/lib/python2.7/site-packages/compose/cli/main.py", line 111, in perform_command
    project = project_from_options('.', options)
  File "/usr/lib/python2.7/site-packages/compose/cli/command.py", line 35, in project_from_options
    environment=environment
  File "/usr/lib/python2.7/site-packages/compose/cli/command.py", line 110, in get_project
    host=host, environment=environment
  File "/usr/lib/python2.7/site-packages/compose/cli/command.py", line 82, in get_client
    environment=environment, tls_version=get_tls_version(environment)
  File "/usr/lib/python2.7/site-packages/compose/cli/docker_client.py", line 52, in docker_client
    kwargs = kwargs_from_env(environment=environment, ssl_version=tls_version)
TypeError: kwargs_from_env() got an unexpected keyword argument 'environment'```

Tried reinstalling a bunch of packages but the issue remains.

**Comment by piotrpalek** [comment]
I tried to apply the advice from #3973 namely: 

> Just pip install --upgrade 'docker-py>=1.9.0' and you'll be set.

but that didn't work. But that gave me a hint to check if I have any local versions of those packages. Turned out after I've `rm -rf ~/.local/lib/python2.7/site-packages/*` docker-compose seemed to work again.

**Comment by wenxingyu** [comment]
very nice post

**Comment by srodriguezt** [comment]
The same issue appears suddenly in my environments. 
```
docker-compose version 1.29.2, build unknown
Docker version 27.3.1, build ce12230
```
@piotrpalek your last comment solve the issue (8 years later). I removed with `rm -rf /usr/local/lib/python3.10/dist-packages/*` and docker-compose starts working again.
