### ISSUE TITLE
Upgraded from Docker 1.12.3 to 1.12.4 and now docker-compose 'ImportError: No module named docker.errors'

### ISSUE THREAD

**Issue by ElijahLynn** [docker/compose#4254]
Just upgraded from Docker 1.12.3 to 1.12.4 and now docker-compose 'ImportError: No module named docker.errors'.  I have docker-engine installed with apt-get on Ubuntu and docker-compose installed with pip. 

docker-compose is at 1.9.0.

**Comment by ElijahLynn** [comment]
```
Traceback (most recent call last):
  File "/usr/local/bin/docker-compose", line 9, in <module>
    load_entry_point('docker-compose==1.9.0', 'console_scripts', 'docker-compose')()
  File "/home/elijah/.local/lib/python2.7/site-packages/setuptools-7.0-py2.7.egg/pkg_resources.py", line 339, in load_entry_point
    run_main = run_script   # backward compatibility
  File "/home/elijah/.local/lib/python2.7/site-packages/setuptools-7.0-py2.7.egg/pkg_resources.py", line 2470, in load_entry_point
    def _parsed_pkg_info(self):
  File "/home/elijah/.local/lib/python2.7/site-packages/setuptools-7.0-py2.7.egg/pkg_resources.py", line 2184, in load
    if version is not None:
  File "/usr/local/lib/python2.7/dist-packages/compose/cli/main.py", line 17, in <module>
    from . import errors
  File "/usr/local/lib/python2.7/dist-packages/compose/cli/errors.py", line 10, in <module>
    from docker.errors import APIError
ImportError: No module named docker.errors
```

**Comment by ElijahLynn** [comment]
I am thinking I should install docker-compose without pip.

**Comment by shin-** [comment]
What's the output of `pip freeze | grep docker` ?

**Comment by ElijahLynn** [comment]
```
docker-compose==1.9.0
docker-py==1.10.6
docker-pycreds==0.2.1
dockerpty==0.4.1
```

**Comment by shin-** [comment]
That's peculiar. The package you need is present (`docker-py`) What's the version of your default python interpreter? (`python --version`)
You might want to try reinstalling `docker-py`:

`pip uninstall docker-py; pip install -U docker-py==1.10.6`

**Comment by ElijahLynn** [comment]
Python 2.7.6

**Comment by ElijahLynn** [comment]
Ran `pip uninstall docker-py; pip install -U docker-py==1.10.6` and now I get:

```
Traceback (most recent call last):
  File "/usr/local/bin/docker-compose", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/home/elijah/.local/lib/python2.7/site-packages/setuptools-7.0-py2.7.egg/pkg_resources.py", line 2880, in <module>
    
  File "/home/elijah/.local/lib/python2.7/site-packages/setuptools-7.0-py2.7.egg/pkg_resources.py", line 434, in _build_master
    """
  File "/home/elijah/.local/lib/python2.7/site-packages/setuptools-7.0-py2.7.egg/pkg_resources.py", line 447, in _build_from_requirements
    
  File "/home/elijah/.local/lib/python2.7/site-packages/setuptools-7.0-py2.7.egg/pkg_resources.py", line 626, in resolve
    # unfortunately, zc.buildout uses a str(err)
pkg_resources.DistributionNotFound: requests>=2.6.1,!=2.11.0,<2.12
```

**Comment by shin-** [comment]
Compose is a bit more strict with the requests version it's willing to work with compared to `docker-py`.

Does running `pip install -U requests==2.11.1` resolve the issue?

**Comment by ElijahLynn** [comment]
`pip install -U requests==2.11.1` works!

**Comment by shin-** [comment]
Okay, that's great news!

It seems somehow the install of Compose 1.9.0 left the `docker-py` dependency in an invalid state. Re-installing that dependency was the solution, but it came with a newer version of requests that's not supported by Compose 1.9.0 that we had to downgrade.
