### ISSUE TITLE
Traceback after pip3 installation (Ubuntu 16.04)

### ISSUE THREAD

**Issue by MrMino** [docker/compose#4272]
I got into a healthy habit of trying to push everything on my OS to be compatible with python 3, so imagine my surprise when after:

    sudo -H pip3 install docker-compose

running the `docker-compose` command yield:

    Traceback (most recent call last):
       File "/usr/local/bin/docker-compose", line 5, in <module>
        from pkg_resources import load_entry_point
      File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2927, in <module>
        @_call_aside
      File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2913, in _call_aside
        f(*args, **kwargs)
      File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2940, in     _initialize_master_working_set
        working_set = WorkingSet._build_master()
      File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 637, in _build_master
        return cls._build_from_requirements(__requires__)
      File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 650, in _build_from_requirements
        dists = ws.resolve(reqs, Environment())
      File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 829, in resolve
        raise DistributionNotFound(req, requirers)
    pkg_resources.DistributionNotFound: The 'backports.ssl-match-hostname>=3.5; python_version < "3.5"' distribution was not found and is required by docker-py

I'm running Ubuntu Gnome 16.04

**Comment by shin-** [comment]
The `backports.ssl-match-hostname` module should be pulled in as part of the dependency tree, but in the rare cases it isn't, you can install it yourself with `pip install 'backports.ssl-match-hostname>=3.5'` (or in your case, `sudo -H pip3 install  'backports.ssl-match-hostname>=3.5'`)
