### ISSUE TITLE
I run docker-compose up with new docker ,but it print error info,how can I resolved?

### ISSUE THREAD

**Issue by rainleon** [docker/compose#4278]
➜  docker-registry git:(develop) docker -v
Docker version 1.12.5, build 7392c3b
➜  docker-registry git:(develop) docker-compose -v
docker-compose version 1.9.0, build 2585387

Traceback (most recent call last):
  File "<string>", line 3, in <module>
  File "compose/cli/main.py", line 65, in main
  File "compose/cli/main.py", line 117, in perform_command
  File "compose/cli/main.py", line 849, in up
  File "compose/project.py", line 382, in up
  File "compose/service.py", line 297, in ensure_image_exists
  File "compose/service.py", line 319, in image
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe5 in position 33: ordinal not in range(128)

**Comment by shin-** [comment]
Also, please make sure your project name only uses ASCII characters. 
By default, your project name is the name of the directory containing your project.
You can override your project name by setting the `COMPOSE_PROJECT_NAME` environment variable or using the `-p` option.
