### ISSUE TITLE
Compose version 1.10.1 fails without creating network when using a remote DOCKER_HOST

### ISSUE THREAD

**Issue by bernardoVale** [docker/compose#4446]
**Compose Version**
```
$ docker-compose -v
docker-compose version 1.10.1, build b252738
```

**STEPS TO REPRODUCE**
1. Execute `docker-compose up` using a remote `DOCKER_HOST`
```
$ DOCKER_HOST=tcp://REMOTE_HOST:2376 docker-compose -f production.yml up -d
Traceback (most recent call last):
  File "/usr/local/bin/docker-compose", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/compose/cli/main.py", line 88, in main
    command()
  File "/usr/local/lib/python2.7/dist-packages/compose/cli/main.py", line 140, in perform_command
    handler(command, command_options)
  File "/usr/local/lib/python2.7/dist-packages/compose/cli/main.py", line 872, in up
    remove_orphans=remove_orphans)
  File "/usr/local/lib/python2.7/dist-packages/compose/project.py", line 381, in up
    self.initialize()
  File "/usr/local/lib/python2.7/dist-packages/compose/project.py", line 425, in initialize
    self.networks.initialize()
  File "/usr/local/lib/python2.7/dist-packages/compose/network.py", line 203, in initialize
    network.ensure()
  File "/usr/local/lib/python2.7/dist-packages/compose/network.py", line 59, in ensure
    data = self.inspect()
  File "/usr/local/lib/python2.7/dist-packages/compose/network.py", line 91, in inspect
    return self.client.inspect_network(self.full_name)
  File "/usr/local/lib/python2.7/dist-packages/docker/utils/decorators.py", line 35, in wrapper
    return f(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/docker/api/network.py", line 158, in inspect_network
    return self._result(res, json=True)
  File "/usr/local/lib/python2.7/dist-packages/docker/api/client.py", line 216, in _result
    self._raise_for_status(response)
  File "/usr/local/lib/python2.7/dist-packages/docker/api/client.py", line 210, in _raise_for_status
    response.raise_for_status()
  File "/usr/share/python-wheels/requests-2.9.1-py2.py3-none-any.whl/requests/models.py", line 840, in raise_for_status
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http://REMOTE_HOST:2376/v1.22/networks/website_default
```

**WORKAROUND**
Rollback to version `1.10.0`:

```sudo pip install docker-compose==1.10.0```

**Comment by shin-** [comment]
Which version of the `docker` package did you have installed when encountering the error?

**Comment by bernardoVale** [comment]
1.13.0

**Comment by shin-** [comment]
Sorry, by "docker package" I meant the python package named `docker`. You can check using `pip freeze | grep docker`

**Comment by bernardoVale** [comment]
No problem.

Before rolling back
```
$ pip freeze | grep docker
docker==2.0.2
docker-compose==1.10.1
docker-pycreds==0.2.1
dockerpty==0.4.1
```

After:
```
docker==2.0.2
docker-compose==1.10.0
docker-pycreds==0.2.1
dockerpty==0.4.1
```
