### ISSUE TITLE
Exception on 404 when using the HTTP interface directly

### ISSUE THREAD

**Issue by ColinHebert** [docker/compose#4483]
Hi guys.

I've been struggling with a weird issue:

```
compose.cli.verbose_proxy.proxy_callable: docker inspect_network <- (u'mytest_default')
Traceback (most recent call last):
  File "/usr/local/bin/docker-compose", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/compose/cli/main.py", line 88, in main
    command()
  File "/usr/local/lib/python2.7/dist-packages/compose/cli/main.py", line 140, in perform_command
    handler(command, command_options)
  File "/usr/local/lib/python2.7/dist-packages/compose/cli/main.py", line 900, in up
    remove_orphans=remove_orphans)
  File "/usr/local/lib/python2.7/dist-packages/compose/project.py", line 387, in up
    self.initialize()
  File "/usr/local/lib/python2.7/dist-packages/compose/project.py", line 431, in initialize
    self.networks.initialize()
  File "/usr/local/lib/python2.7/dist-packages/compose/network.py", line 203, in initialize
    network.ensure()
  File "/usr/local/lib/python2.7/dist-packages/compose/network.py", line 59, in ensure
    data = self.inspect()
  File "/usr/local/lib/python2.7/dist-packages/compose/network.py", line 91, in inspect
    return self.client.inspect_network(self.full_name)
  File "/usr/local/lib/python2.7/dist-packages/compose/cli/verbose_proxy.py", line 55, in proxy_callable
    result = getattr(self.obj, call_name)(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/docker/utils/decorators.py", line 35, in wrapper
    return f(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/docker/api/network.py", line 158, in inspect_network
    return self._result(res, json=True)
  File "/usr/local/lib/python2.7/dist-packages/docker/api/client.py", line 216, in _result
    self._raise_for_status(response)
  File "/usr/local/lib/python2.7/dist-packages/docker/api/client.py", line 210, in _raise_for_status
    response.raise_for_status()
  File "/usr/share/python-wheels/requests-2.9.1-py2.py3-none-any.whl/requests/models.py", line 840, in raise_for_status
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http://docker:2375/v1.25/networks/baseagent_default
```

From the looks of it, the client fails to recover from a 404 (an expected one, the network `mytest_default` doesn't exist yet.

I have been able to create a more self-contained test to reproduce the error (spoiler alert it relies on dind, but that should be irrelevant): https://github.com/ColinHebert/compose-404
It may sound a bit convoluted but here is what's happening:
 - docker-compose.yaml starts two containers, the first one is dind (the one we're going to test against through http). It uses privileges to run docker properly.
 - The second container runs a docker container "client" which is an ubuntu box with docker-compose installed. The client container is linked to dind container and has the env variable `DOCKER_HOST=docker:2375` (meaning that docker commands run inside this container are going straight to dind
 - When starting the client container, we attempt to run docker-compose which ends up failing on the 404.

I'm not 100% across the reason why the HTTP 404 bubbles up in my case. When running against a socket (albeit a different environment), the 404 gets caught properly ending with:

```pip._vendor.requests.packages.urllib3.connectionpool._make_request: "GET /v1.25/networks/mytest_default HTTP/1.1" 404 50```

**Comment by ColinHebert** [comment]
After more testing, it seems that the problem was introduce between `1.10.0` and `1.10.1`.
(Tested changing `RUN pip install docker-compose` into `RUN pip install docker-compose==1.10.0` in the Dockerfile) which is when docker-py 2.0.2 was introduced...

The search continues...

**Comment by shin-** [comment]
@ColinHebert If you use 1.10.0 in combination with `docker==2.0.2`, you don't get the issue?

**Comment by ColinHebert** [comment]
Indeed, I thought it was docker-py 2.0.2 as well, but it clearly isn't the case.

I've been staring at the diff between 1.10.0 and 1.10.1 in github and nothing in there seems to be relevant to the problem

**Comment by ColinHebert** [comment]
Here's a pip freeze with 1.10.1 (failing with 404):
```
client_1  | backports.ssl-match-hostname==3.5.0.1
client_1  | cached-property==1.3.0
client_1  | colorama==0.3.7
client_1  | docker==2.0.2
client_1  | docker-compose==1.10.1
client_1  | docker-pycreds==0.2.1
client_1  | dockerpty==0.4.1
client_1  | docopt==0.6.2
client_1  | enum34==1.1.6
client_1  | functools32==3.2.3.post2
client_1  | ipaddress==1.0.18
client_1  | jsonschema==2.6.0
client_1  | PyYAML==3.12
client_1  | requests==2.11.1
client_1  | six==1.10.0
client_1  | texttable==0.8.7
client_1  | websocket-client==0.40.0
```

And with 1.10.0 (successfully running):
```
client_1  | backports.ssl-match-hostname==3.5.0.1
client_1  | cached-property==1.3.0
client_1  | colorama==0.3.7
client_1  | docker==2.0.2
client_1  | docker-compose==1.10.0
client_1  | docker-pycreds==0.2.1
client_1  | dockerpty==0.4.1
client_1  | docopt==0.6.2
client_1  | enum34==1.1.6
client_1  | functools32==3.2.3.post2
client_1  | ipaddress==1.0.18
client_1  | jsonschema==2.6.0
client_1  | PyYAML==3.12
client_1  | requests==2.11.1
client_1  | six==1.10.0
client_1  | texttable==0.8.7
client_1  | websocket-client==0.40.0
```

**Comment by ColinHebert** [comment]
Okay, after attempts to reintroduce the problem by adding changes one by one, it seems that the cause is this:

```
# Attempt to detect https://github.com/docker/compose/issues/4344
try:
    # A regular import statement causes PyInstaller to freak out while
    # trying to load pip. This way it is simply ignored.
    pip = __import__('pip')
    pip_packages = pip.get_installed_distributions()
    if 'docker-py' in [pkg.project_name for pkg in pip_packages]:
        from .colors import red
        print(
            red('ERROR:'),
            "Dependency conflict: an older version of the 'docker-py' package "
            "is polluting the namespace. "
            "Run the following command to remedy the issue:\n"
            "pip uninstall docker docker-py; pip install docker",
            file=sys.stderr
        )
        sys.exit(1)
except ImportError:
    # pip is not available, which indicates it's probably the binary
    # distribution of Compose which is not affected
    pass
```

**Comment by ColinHebert** [comment]
I narrowed it down to the `pip = __import__('pip')` alone.
This is outside of my domain of expertise now, but this line alone is causing some trouble :/

**Comment by shin-** [comment]
I found a temporary "fix" submitted to your reproduction case: ColinHebert/compose-404#1
It looks like the pip import confuses things, and this issue looks like another symptom of the one described in #4425

**Comment by shin-** [comment]
If you have a chance, please test the potential fix in #4484

**Comment by ColinHebert** [comment]
The fix doesn't seem to work. I tried to reduce it to just running

```
original_sys_path = sys.path[:]
print(sys.path[:])
pip = __import__('pip')
print(sys.path[:])
sys.path[:] = original_sys_path
print(sys.path[:])
```

And it prints out the following:
```
['/usr/local/bin', '/usr/lib/python2.7', '/usr/lib/python2.7/plat-x86_64-linux-gnu', '/usr/lib/python2.7/lib-tk', '/usr/lib/python2.7/lib-old', '/usr/lib/python2.7/lib-dynload', '/usr/local/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages']
['/usr/share/python-wheels/ipaddress-0.0.0-py2.py3-none-any.whl', '/usr/share/python-wheels/pyparsing-2.0.3-py2.py3-none-any.whl', '/usr/share/python-wheels/packaging-16.6-py2.py3-none-any.whl', '/usr/share/python-wheels/chardet-2.3.0-py2.py3-none-any.whl', '/usr/share/python-wheels/retrying-1.3.3-py2.py3-none-any.whl', '/usr/share/python-wheels/urllib3-1.13.1-py2.py3-none-any.whl', '/usr/share/python-wheels/setuptools-20.7.0-py2.py3-none-any.whl', '/usr/share/python-wheels/wheel-0.29.0-py2.py3-none-any.whl', '/usr/share/python-wheels/requests-2.9.1-py2.py3-none-any.whl', '/usr/share/python-wheels/CacheControl-0.11.5-py2.py3-none-any.whl', '/usr/share/python-wheels/progress-1.2-py2.py3-none-any.whl', '/usr/share/python-wheels/colorama-0.3.7-py2.py3-none-any.whl', '/usr/share/python-wheels/distlib-0.2.2-py2.py3-none-any.whl', '/usr/share/python-wheels/six-1.10.0-py2.py3-none-any.whl', '/usr/share/python-wheels/pkg_resources-0.0.0-py2.py3-none-any.whl', '/usr/share/python-wheels/html5lib-0.999-py2.py3-none-any.whl', '/usr/share/python-wheels/pip-8.1.1-py2.py3-none-any.whl', '/usr/share/python-wheels/lockfile-0.12.2-py2.py3-none-any.whl', '/usr/local/bin', '/usr/lib/python2.7', '/usr/lib/python2.7/plat-x86_64-linux-gnu', '/usr/lib/python2.7/lib-tk', '/usr/lib/python2.7/lib-old', '/usr/lib/python2.7/lib-dynload', '/usr/local/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages']
['/usr/local/bin', '/usr/lib/python2.7', '/usr/lib/python2.7/plat-x86_64-linux-gnu', '/usr/lib/python2.7/lib-tk', '/usr/lib/python2.7/lib-old', '/usr/lib/python2.7/lib-dynload', '/usr/local/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages']
```

I think we're on the right tracks, but there might be another side effect.

**Comment by shin-** [comment]
Yeah, taking another look, it looks like `pip` loads the system's bundled `requests` wheel, so removing it from sys.path after the fact doesn't do anything.
I updated #4484 again going with a completely different approach, I'm pretty confident this should fix the issue for good this time.

**Comment by ColinHebert** [comment]
Yep, I can confirm, 66f4a79 fixes the problem. Thanks!
