### ISSUE TITLE
docker-compose config raises pyyaml exception with secrets in a service.

### ISSUE THREAD

**Issue by Robpol86** [docker/compose#4658]
I am attempting to run "docker-compose config" on a compose file using the `secrets` configuration. It seems to work fine when I run it on my docker compose stack on Fedora 25. The bug appears to happen only when validating configs when it tries to serialize the already-parsed compose file.

The exception:
```
Traceback (most recent call last):
  File "/Users/robpol86/workspace/influxdb/env/bin/docker-compose", line 11, in <module>
    sys.exit(main())
  File "/Users/robpol86/workspace/influxdb/env/lib/python3.6/site-packages/compose/cli/main.py", line 64, in main
    command()
  File "/Users/robpol86/workspace/influxdb/env/lib/python3.6/site-packages/compose/cli/main.py", line 110, in perform_command
    handler(command, options, command_options)
  File "/Users/robpol86/workspace/influxdb/env/lib/python3.6/site-packages/compose/cli/main.py", line 315, in config
    print(serialize_config(compose_config))
  File "/Users/robpol86/workspace/influxdb/env/lib/python3.6/site-packages/compose/config/serialize.py", line 57, in serialize_config
    width=80)
  File "/Users/robpol86/workspace/influxdb/env/lib/python3.6/site-packages/yaml/__init__.py", line 216, in safe_dump
    return dump_all([data], stream, Dumper=SafeDumper, **kwds)
  File "/Users/robpol86/workspace/influxdb/env/lib/python3.6/site-packages/yaml/__init__.py", line 188, in dump_all
    dumper.represent(data)
  File "/Users/robpol86/workspace/influxdb/env/lib/python3.6/site-packages/yaml/representer.py", line 26, in represent
    node = self.represent_data(data)
  File "/Users/robpol86/workspace/influxdb/env/lib/python3.6/site-packages/yaml/representer.py", line 47, in represent_data
    node = self.yaml_representers[data_types[0]](self, data)
  File "/Users/robpol86/workspace/influxdb/env/lib/python3.6/site-packages/yaml/representer.py", line 205, in represent_dict
    return self.represent_mapping('tag:yaml.org,2002:map', data)
  File "/Users/robpol86/workspace/influxdb/env/lib/python3.6/site-packages/yaml/representer.py", line 116, in represent_mapping
    node_value = self.represent_data(item_value)
  File "/Users/robpol86/workspace/influxdb/env/lib/python3.6/site-packages/yaml/representer.py", line 47, in represent_data
    node = self.yaml_representers[data_types[0]](self, data)
  File "/Users/robpol86/workspace/influxdb/env/lib/python3.6/site-packages/yaml/representer.py", line 205, in represent_dict
    return self.represent_mapping('tag:yaml.org,2002:map', data)
  File "/Users/robpol86/workspace/influxdb/env/lib/python3.6/site-packages/yaml/representer.py", line 116, in represent_mapping
    node_value = self.represent_data(item_value)
  File "/Users/robpol86/workspace/influxdb/env/lib/python3.6/site-packages/yaml/representer.py", line 47, in represent_data
    node = self.yaml_representers[data_types[0]](self, data)
  File "/Users/robpol86/workspace/influxdb/env/lib/python3.6/site-packages/yaml/representer.py", line 205, in represent_dict
    return self.represent_mapping('tag:yaml.org,2002:map', data)
  File "/Users/robpol86/workspace/influxdb/env/lib/python3.6/site-packages/yaml/representer.py", line 116, in represent_mapping
    node_value = self.represent_data(item_value)
  File "/Users/robpol86/workspace/influxdb/env/lib/python3.6/site-packages/yaml/representer.py", line 57, in represent_data
    node = self.yaml_representers[None](self, data)
  File "/Users/robpol86/workspace/influxdb/env/lib/python3.6/site-packages/yaml/representer.py", line 229, in represent_undefined
    raise RepresenterError("cannot represent an object: %s" % data)
yaml.representer.RepresenterError: cannot represent an object: <map object at 0x103f6d6d8>
```

The problematic compose file:

```yaml
version: '3.1'

services:
  grafana:
    container_name: grafana
    image: grafana/grafana
    restart: always
    secrets:
      - grafana

secrets:
  grafana:
    file: ./.secrets/grafana.ini
```

However the command works fine with:

```yaml
version: '3.1'

services:
  grafana:
    container_name: grafana
    image: grafana/grafana
    restart: always

secrets:
  grafana:
    file: ./.secrets/grafana.ini
```

```
$ docker-compose config
networks: {}
services:
  grafana:
    container_name: grafana
    image: grafana/grafana
    restart: always
version: '3.1'
volumes: {}
```

Running: docker-compose version 1.11.2, build dfed245

```
$ python -m pdb $(which docker-compose) config
> /Users/robpol86/workspace/influxdb/env/bin/docker-compose(4)<module>()
-> import re
(Pdb) c
Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.6.0/Frameworks/Python.framework/Versions/3.6/lib/python3.6/pdb.py", line 1667, in main
    pdb._runscript(mainpyfile)
  File "/usr/local/Cellar/python3/3.6.0/Frameworks/Python.framework/Versions/3.6/lib/python3.6/pdb.py", line 1548, in _runscript
    self.run(statement)
  File "/usr/local/Cellar/python3/3.6.0/Frameworks/Python.framework/Versions/3.6/lib/python3.6/bdb.py", line 431, in run
    exec(cmd, globals, locals)
  File "<string>", line 1, in <module>
  File "/Users/robpol86/workspace/influxdb/env/bin/docker-compose", line 4, in <module>
    import re
  File "/Users/robpol86/workspace/influxdb/env/lib/python3.6/site-packages/compose/cli/main.py", line 64, in main
    command()
  File "/Users/robpol86/workspace/influxdb/env/lib/python3.6/site-packages/compose/cli/main.py", line 110, in perform_command
    handler(command, options, command_options)
  File "/Users/robpol86/workspace/influxdb/env/lib/python3.6/site-packages/compose/cli/main.py", line 315, in config
    print(serialize_config(compose_config))
  File "/Users/robpol86/workspace/influxdb/env/lib/python3.6/site-packages/compose/config/serialize.py", line 57, in serialize_config
    width=80)
  File "/Users/robpol86/workspace/influxdb/env/lib/python3.6/site-packages/yaml/__init__.py", line 216, in safe_dump
    return dump_all([data], stream, Dumper=SafeDumper, **kwds)
  File "/Users/robpol86/workspace/influxdb/env/lib/python3.6/site-packages/yaml/__init__.py", line 188, in dump_all
    dumper.represent(data)
  File "/Users/robpol86/workspace/influxdb/env/lib/python3.6/site-packages/yaml/representer.py", line 26, in represent
    node = self.represent_data(data)
  File "/Users/robpol86/workspace/influxdb/env/lib/python3.6/site-packages/yaml/representer.py", line 47, in represent_data
    node = self.yaml_representers[data_types[0]](self, data)
  File "/Users/robpol86/workspace/influxdb/env/lib/python3.6/site-packages/yaml/representer.py", line 205, in represent_dict
    return self.represent_mapping('tag:yaml.org,2002:map', data)
  File "/Users/robpol86/workspace/influxdb/env/lib/python3.6/site-packages/yaml/representer.py", line 116, in represent_mapping
    node_value = self.represent_data(item_value)
  File "/Users/robpol86/workspace/influxdb/env/lib/python3.6/site-packages/yaml/representer.py", line 47, in represent_data
    node = self.yaml_representers[data_types[0]](self, data)
  File "/Users/robpol86/workspace/influxdb/env/lib/python3.6/site-packages/yaml/representer.py", line 205, in represent_dict
    return self.represent_mapping('tag:yaml.org,2002:map', data)
  File "/Users/robpol86/workspace/influxdb/env/lib/python3.6/site-packages/yaml/representer.py", line 116, in represent_mapping
    node_value = self.represent_data(item_value)
  File "/Users/robpol86/workspace/influxdb/env/lib/python3.6/site-packages/yaml/representer.py", line 47, in represent_data
    node = self.yaml_representers[data_types[0]](self, data)
  File "/Users/robpol86/workspace/influxdb/env/lib/python3.6/site-packages/yaml/representer.py", line 205, in represent_dict
    return self.represent_mapping('tag:yaml.org,2002:map', data)
  File "/Users/robpol86/workspace/influxdb/env/lib/python3.6/site-packages/yaml/representer.py", line 116, in represent_mapping
    node_value = self.represent_data(item_value)
  File "/Users/robpol86/workspace/influxdb/env/lib/python3.6/site-packages/yaml/representer.py", line 57, in represent_data
    node = self.yaml_representers[None](self, data)
  File "/Users/robpol86/workspace/influxdb/env/lib/python3.6/site-packages/yaml/representer.py", line 229, in represent_undefined
    raise RepresenterError("cannot represent an object: %s" % data)
yaml.representer.RepresenterError: cannot represent an object: <map object at 0x10f5151d0>
Uncaught exception. Entering post mortem debugging
Running 'cont' or 'step' will restart the program
> /Users/robpol86/workspace/influxdb/env/lib/python3.6/site-packages/yaml/representer.py(229)represent_undefined()
-> raise RepresenterError("cannot represent an object: %s" % data)
(Pdb) u
> /Users/robpol86/workspace/influxdb/env/lib/python3.6/site-packages/yaml/representer.py(57)represent_data()
-> node = self.yaml_representers[None](self, data)
(Pdb) u
> /Users/robpol86/workspace/influxdb/env/lib/python3.6/site-packages/yaml/representer.py(116)represent_mapping()
-> node_value = self.represent_data(item_value)
(Pdb) u
> /Users/robpol86/workspace/influxdb/env/lib/python3.6/site-packages/yaml/representer.py(205)represent_dict()
-> return self.represent_mapping('tag:yaml.org,2002:map', data)
(Pdb) u
> /Users/robpol86/workspace/influxdb/env/lib/python3.6/site-packages/yaml/representer.py(47)represent_data()
-> node = self.yaml_representers[data_types[0]](self, data)
(Pdb) u
> /Users/robpol86/workspace/influxdb/env/lib/python3.6/site-packages/yaml/representer.py(116)represent_mapping()
-> node_value = self.represent_data(item_value)
(Pdb) u
> /Users/robpol86/workspace/influxdb/env/lib/python3.6/site-packages/yaml/representer.py(205)represent_dict()
-> return self.represent_mapping('tag:yaml.org,2002:map', data)
(Pdb) u
> /Users/robpol86/workspace/influxdb/env/lib/python3.6/site-packages/yaml/representer.py(47)represent_data()
-> node = self.yaml_representers[data_types[0]](self, data)
(Pdb) u
> /Users/robpol86/workspace/influxdb/env/lib/python3.6/site-packages/yaml/representer.py(116)represent_mapping()
-> node_value = self.represent_data(item_value)
(Pdb) u
> /Users/robpol86/workspace/influxdb/env/lib/python3.6/site-packages/yaml/representer.py(205)represent_dict()
-> return self.represent_mapping('tag:yaml.org,2002:map', data)
(Pdb) u
> /Users/robpol86/workspace/influxdb/env/lib/python3.6/site-packages/yaml/representer.py(47)represent_data()
-> node = self.yaml_representers[data_types[0]](self, data)
(Pdb) u
> /Users/robpol86/workspace/influxdb/env/lib/python3.6/site-packages/yaml/representer.py(26)represent()
-> node = self.represent_data(data)
(Pdb) u
> /Users/robpol86/workspace/influxdb/env/lib/python3.6/site-packages/yaml/__init__.py(188)dump_all()
-> dumper.represent(data)
(Pdb) u
> /Users/robpol86/workspace/influxdb/env/lib/python3.6/site-packages/yaml/__init__.py(216)safe_dump()
-> return dump_all([data], stream, Dumper=SafeDumper, **kwds)
(Pdb) u
> /Users/robpol86/workspace/influxdb/env/lib/python3.6/site-packages/compose/config/serialize.py(57)serialize_config()
-> width=80)
(Pdb) l
 52  	def serialize_config(config):
 53  	    return yaml.safe_dump(
 54  	        denormalize_config(config),
 55  	        default_flow_style=False,
 56  	        indent=2,
 57  ->	        width=80)
 58  	
 59  	
 60  	def serialize_ns_time_value(value):
 61  	    result = (value, 'ns')
 62  	    table = [
(Pdb) from pprint import pprint
(Pdb) pprint(denormalize_config(config))
{'networks': {},
 'services': {'grafana': {'container_name': 'grafana',
                          'image': 'grafana/grafana',
                          'restart': 'always',
                          'secrets': <map object at 0x110e39da0>}},
 'version': '3.1',
 'volumes': {}}
(Pdb) 
```

Notice the missing top-level `secrets` key is missing, only the one in the service. I wonder if that's related?

**Comment by Robpol86** [comment]
Nevermind, forgot to test latest master. Seems to work fine:

```
$ docker-compose config
networks: {}
secrets:
  grafana:
    file: /Users/robpol86/workspace/influxdb/.secrets/grafana.ini
services:
  grafana:
    container_name: grafana
    image: grafana/grafana
    restart: always
    secrets:
    - source: grafana
version: '3.1'
volumes: {}
```
