### ISSUE TITLE
subprocess.py raises UnicodeDecodeError

### ISSUE THREAD

**Issue by djs55** [docker/compose#4663]
Version `1.11.2` of `docker-compose` bundled in Docker for Mac `17.03.0-ce` fails to run for some users. According to the report in https://github.com/docker/for-mac/issues/1428 it fails like this:
```
 docker-compose --version
Traceback (most recent call last):
File "docker-compose", line 2, in 
File "/private/var/folders/my/m6ynh3bn6tq06h7xr3js0z7r0000gn/T/pip-build-MW5H3j/pyinstaller/PyInstaller/loader/pyimod03_importers.py", line 389, in load_module
File "compose/cli/init.py", line 16, in 
File "subprocess.py", line 711, in init
File "subprocess.py", line 1343, in _execute_child
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 0: ordinal not in range(128)
Failed to execute script docker-compose
```
For many people (including me) it's totally fine, but several users report this error.

The compose binary comes from  https://github.com/docker/compose/releases/download/1.11.2/docker-compose-Darwin-x86_64

I don't know how to debug it further -- any pointers would be appreciated!

**Comment by shin-** [comment]
I found someone reporting a similar traceback with ansible: https://www.reddit.com/r/ansible/comments/60i2hn/macos_unicodedecodeerror_ascii_codec_cant_decode/

**Comment by shin-** [comment]
I added a workaround as part of #4652 that should make it in 1.12.0 RC2

**Comment by shin-** [comment]
@djs55 1.12.0 RC2 released, let me know if that problem reappears.

**Comment by laichihfei** [comment]
Version 1.11.2 of docker-compose bundled in Docker for Mac 17.03.0-ce.

I use the version 1 of docker-compose.yml and when I add 'volumes' tag, it will cause the following error:
``Traceback (most recent call last):
  File "docker-compose", line 3, in <module>
  File "compose/cli/main.py", line 64, in main
  File "compose/cli/main.py", line 113, in perform_command
  File "compose/cli/command.py", line 36, in project_from_options
  File "compose/cli/command.py", line 103, in get_project
  File "compose/config/config.py", line 333, in load
  File "compose/config/config.py", line 457, in load_services
  File "compose/config/config.py", line 436, in build_services
  File "compose/config/config.py", line 421, in build_service
  File "compose/config/config.py", line 668, in process_service
  File "compose/config/config.py", line 988, in resolve_volume_paths
  File "compose/config/config.py", line 993, in resolve_volume_path
  File "compose/config/config.py", line 1077, in split_path_mapping
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe6 in position 27: ordinal not in range(128)
Failed to execute script docker-compose
``

**Comment by mackankowski** [comment]
Somehow but removing entire content in `~/.docker/config.json` fixed the problem for me.

**Comment by denisglotov** [comment]
Watch you command line. You must have used some unicode (0xe2): for example long unicode '--' instead of ascii '-'.
