### ISSUE TITLE
docker-compose doesn't work on FreeBSD

### ISSUE THREAD

**Issue by lifanov** [docker/compose#4723]
I'm trying to do the "getting started" tutorial here: https://docs.docker.com/compose/gettingstarted/

```
$ ls
app.py			Dockerfile
docker-compose.yml	requirements.txt
$ /home/lifanov/.local/bin/docker-compose up
Traceback (most recent call last):
  File "/home/lifanov/.local/bin/docker-compose", line 7, in <module>
    from compose.cli.main import main
  File "/home/lifanov/.local/lib/python2.7/site-packages/compose/cli/main.py", line 20, in <module>
    from ..bundle import get_image_digests
  File "/home/lifanov/.local/lib/python2.7/site-packages/compose/bundle.py", line 14, in <module>
    from .service import format_environment
  File "/home/lifanov/.local/lib/python2.7/site-packages/compose/service.py", line 108, in <module>
    @enum.unique
AttributeError: 'module' object has no attribute 'unique'
```

**Comment by lifanov** [comment]
Environment:

FreeBSD 11.0
Docker 17.04.0
Docker Machine 0.10.0

Docker Machine backend is VirtualBox

**Comment by lifanov** [comment]
The same environment but inside of a CentOS 7 chroot works.

**Comment by shin-** [comment]
What's the output of `pip freeze` in that environment? You probably have to uninstall the `enum` package.

**Comment by lifanov** [comment]
You are exactly right! I had both enum and enum34. I uninstalled enum and it works now!
