### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'keys'

### ISSUE THREAD

**Issue by dunklesToast** [docker/compose#4767]
hey,

i want to install mailcow-dockerized on my debian jessie machine and after `docker pull` I need to run `docker-compose up -d` but it throws following error:
```sh
Traceback (most recent call last):
  File "bin/docker-compose", line 3, in <module>
  File "compose/cli/main.py", line 68, in main
  File "compose/cli/main.py", line 118, in perform_command
  File "compose/cli/main.py", line 924, in up
  File "compose/project.py", line 389, in up
  File "compose/project.py", line 437, in initialize
  File "compose/network.py", line 252, in initialize
  File "compose/network.py", line 60, in ensure
  File "compose/network.py", line 180, in check_remote_network_config
  File "compose/network.py", line 163, in check_remote_ipam_config
AttributeError: 'NoneType' object has no attribute 'keys'
Failed to execute script docker-compose
```

since I dont know python I dont know wheres the problem.

**Comment by shin-** [comment]
What version of the Docker Engine are you using - can you share the output of `docker version`?

**Comment by dunklesToast** [comment]
Sure! Look here:
```
Client:
 Version:      17.03.1-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Mon Mar 27 17:07:28 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.1-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Mon Mar 27 17:07:28 2017
 OS/Arch:      linux/amd64
 Experimental: false

```

**Comment by shin-** [comment]
Thanks - I believe I identified the issue as a bug in Compose.
As a workaround, you might want to try running `docker-compose down && docker-compose up -d` instead.

**Comment by dunklesToast** [comment]
That worked!
Thanks!

**Comment by rbadrana** [comment]
> Thanks - I believe I identified the issue as a bug in Compose. As a workaround, you might want to try running `docker-compose down && docker-compose up -d` instead.

thanks ...worked for me also
