### ISSUE TITLE
ValueError: invalid literal for int() with base 16: b'

### ISSUE THREAD

**Issue by pacuna** [docker/compose#4822]
Hi, I just installed Docker and Docker Compose on Fedora 26 using dnf. Everything seems to work fine except when running `docker-compose logs -f` on a project. After a few seconds, the command crashes and all the containers are stopped. This is part of the log:

```
...
kenneth-migrate_1  |    -> 0.0783s
kenneth-migrate_1  | -- create_table("users", {:force=>:cascade, :options=>"ENGINE=InnoDB DEFAULT CHARSET=latin1"})
kenneth-migrate_1  |    -> 0.0978s
kenneth-migrate_1  | -- initialize_schema_migrations_table()
kenneth-migrate_1  |    -> 0.0636s
Traceback (most recent call last):
  File "/usr/lib64/python3.6/http/client.py", line 546, in _get_chunk_left
    chunk_left = self._read_next_chunk_size()
  File "/usr/lib64/python3.6/http/client.py", line 513, in _read_next_chunk_size
    return int(line, 16)
ValueError: invalid literal for int() with base 16: b''

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib64/python3.6/http/client.py", line 578, in _readinto_chunked
    chunk_left = self._get_chunk_left()
  File "/usr/lib64/python3.6/http/client.py", line 548, in _get_chunk_left
    raise IncompleteRead(b'')
http.client.IncompleteRead: IncompleteRead(0 bytes read)

During handling of the above exception, another exception occurred:
...
```
Docker version:

```
Client:
 Version:         1.13.1
 API version:     1.26
 Package version: <unknown>
 Go version:      go1.8
 Git commit:      14cc629/1.13.1
 Built:           Thu Apr 13 20:40:33 2017
 OS/Arch:         linux/amd64

Server:
 Version:         1.13.1
 API version:     1.26 (minimum version 1.12)
 Package version: <unknown>
 Go version:      go1.8
 Git commit:      14cc629/1.13.1
 Built:           Thu Apr 13 20:40:33 2017
 OS/Arch:         linux/amd64
 Experimental:    false
```

Docker Compose version:

```
docker-compose version 1.11.2, build dfed245
docker-py version: 2.1.0
CPython version: 3.6.1
OpenSSL version: OpenSSL 1.1.0e-fips  16 Feb 2017
```

Any clues? Thanks in advance.

**Comment by shin-** [comment]
Are you able to try with Python 3.4 or 2.7 instead? We don't officially support Python 3.6 at the moment, that might be a source of issues.

**Comment by pacuna** [comment]
@shin- Thanks. I switched to python 2.7 and the error went away but now I'm getting this one:

```
...
neufert-es_1            | [2017-05-17 01:58:42,677][INFO ][transport                ] [Matador] bound_address {inet[/0:0:0:0:0:0:0:0:9300]}, publish_address {inet[/172.19.0.5:9300]}
neufert-es_1            | [2017-05-17 01:58:42,727][INFO ][discovery                ] [Matador] elasticsearch/ZGGEsiYwTNCpA-dNVG3cjA
neufert-db-load-dump_1  | neufert_dump.sql
neufert-db-load-dump_1  | Done!
Exception in thread Thread-6:
Traceback (most recent call last):
  File "threading.py", line 801, in __bootstrap_inner
  File "threading.py", line 754, in run
  File "compose/cli/log_printer.py", line 203, in watch_events
  File "compose/project.py", line 370, in events
  File "compose/container.py", line 42, in from_id
  File "site-packages/docker/utils/decorators.py", line 21, in wrapped
  File "site-packages/docker/api/container.py", line 748, in inspect_container
  File "site-packages/docker/utils/decorators.py", line 47, in inner
  File "site-packages/docker/api/client.py", line 183, in _get
  File "site-packages/requests/sessions.py", line 488, in get
  File "site-packages/requests/sessions.py", line 475, in request
  File "site-packages/requests/sessions.py", line 596, in send
  File "site-packages/requests/adapters.py", line 473, in send
ConnectionError: ('Connection aborted.', BadStatusLine("''",))

Traceback (most recent call last):
  File "bin/docker-compose", line 3, in <module>
  File "compose/cli/main.py", line 68, in main
  File "compose/cli/main.py", line 118, in perform_command
  File "compose/cli/main.py", line 559, in logs
  File "compose/cli/log_printer.py", line 87, in run
  File "compose/cli/log_printer.py", line 235, in consume_queue
requests.packages.urllib3.exceptions.ProtocolError: ('Connection broken: IncompleteRead(0 bytes read)', IncompleteRead(0 bytes read))
Failed to execute script docker-compose
...
```

Any ideas? I'm using Fedora 26 and this is the new docker-compose version:

```
docker-compose version 1.13.0, build 1719ceb
docker-py version: 2.2.1
CPython version: 2.7.13
OpenSSL version: OpenSSL 1.0.1t  3 May 2016
```

**Comment by shin-** [comment]
Thank you! That's typically the kind of error we see when the connection is closed abruptly by the remote engine. That tends to happen when the Docker Engine crashes for some reason. Do you see anything in the engine logs (`journalctl -u docker.service`) that would confirm this?

**Comment by pacuna** [comment]
@shin- I think something specific at that moment. I haven't had any issues since, so everything is working now :).

Thanks for the help!
