### ISSUE TITLE
Windows 10 installation of Docker-compose on windows require pypiwin32

### ISSUE THREAD

**Issue by arozumenko** [docker/compose#4842]
installation of pypiwin32 should be added either to docks or to requirements

PS D:\Downloads> docker-compose up -d
Traceback (most recent call last):
  File "c:\python27\lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "c:\python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Python27\Scripts\docker-compose.exe\__main__.py", line 9, in <module>
  File "c:\python27\lib\site-packages\compose\cli\main.py", line 68, in main
    command()
  File "c:\python27\lib\site-packages\compose\cli\main.py", line 115, in perform_command
    project = project_from_options('.', options)
  File "c:\python27\lib\site-packages\compose\cli\command.py", line 37, in project_from_options
    override_dir=options.get('--project-directory'),
  File "c:\python27\lib\site-packages\compose\cli\command.py", line 99, in get_project
    host=host, environment=environment
  File "c:\python27\lib\site-packages\compose\cli\command.py", line 71, in get_client
    environment=environment, tls_version=get_tls_version(environment)
  File "c:\python27\lib\site-packages\compose\cli\docker_client.py", line 95, in docker_client
    return APIClient(**kwargs)
  File "c:\python27\lib\site-packages\docker\api\client.py", line 123, in __init__
    'Install pypiwin32 package to enable npipe:// support'
docker.errors.DockerException: Install pypiwin32 package to enable npipe:// support

installation of pypiwin32 with pip solves the exception

**Comment by shin-** [comment]
It's already in our requirements.txt: https://github.com/docker/compose/blob/master/requirements.txt#L12

**Comment by h3xstream** [comment]
For those having the previous error on Windows, here is a quick fix : `pip install pypiwin32`

**Comment by vardhmanandroid2015** [comment]
getting into same issue - pypiwin32 is installed still getting **docker.errors.DockerException: Install pypiwin32 package to enable npipe:// support**
C:\Users\<username>>pip install pypiwin32
Requirement already satisfied: pypiwin32 in c:\users\<username>\appdata\local\programs\python\python37\lib\site-packages\pypiwin32-223-py3.7.egg (223)
Requirement already satisfied: pywin32>=223 in c:\users\<username>\appdata\local\programs\python\python37\lib\site-packages\pywin32-223-py3.7-win-amd64.egg (from pypiwin32) (223)

**Comment by TTimo** [comment]
Same here, latest pypiwin32 and pywin32 are installed, and this error is still coming up.

**Comment by prashantalhat** [comment]
Why is this issue closed? I am still getting this on windows machine.

**Comment by TTimo** [comment]
In my case it turned out to be a snafu on my end, after the relevant pip upgrades the problem no longer happened.

**Comment by asevans48** [comment]
This is not fixed.
