### ISSUE TITLE
Specifying figfile with -f doesn't carry the path forward into build steps

### ISSUE THREAD

**Issue by brianclements** [docker/compose#488]
using this fig file:
```yml
logs:
    image: "radial/axle-base:latest"
    volumes:
        - /log
hub:
    build: hub
    volumes_from:
        - logs
    volumes:
        - /config
        - /data
        - /run
nginx:
    build: spoke
    volumes_from:
        - hub
    ports:
        - "8080:80"
        - "4430:443"
        - "22229:22"
```

`fig -f some/path/fig.yml up` will find the fig file OK, but then will crash because it can't find the directories specified in my 'build' key.

```
Traceback (most recent call last):
  File "/usr/local/bin/fig", line 9, in <module>
    load_entry_point('fig==0.5.2', 'console_scripts', 'fig')()
  File "/usr/local/lib/python2.7/dist-packages/fig/cli/main.py", line 30, in main
    command.sys_dispatch()
  File "/usr/local/lib/python2.7/dist-packages/fig/cli/docopt_command.py", line 21, in sys_dispatch
    self.dispatch(sys.argv[1:], None)
  File "/usr/local/lib/python2.7/dist-packages/fig/cli/command.py", line 31, in dispatch
    super(Command, self).dispatch(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/fig/cli/docopt_command.py", line 24, in dispatch
    self.perform_command(*self.parse(argv, global_options))
  File "/usr/local/lib/python2.7/dist-packages/fig/cli/command.py", line 50, in perform_command
    return super(Command, self).perform_command(options, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/fig/cli/docopt_command.py", line 27, in perform_command
    handler(command_options)
  File "/usr/local/lib/python2.7/dist-packages/fig/cli/main.py", line 340, in up
    recreate=recreate
  File "/usr/local/lib/python2.7/dist-packages/fig/project.py", line 170, in up
    for (_, container) in service.recreate_containers():
  File "/usr/local/lib/python2.7/dist-packages/fig/service.py", line 166, in recreate_containers
    container = self.create_container(**override_options)
  File "/usr/local/lib/python2.7/dist-packages/fig/service.py", line 146, in create_container
    container_options = self._get_container_create_options(override_options, one_off=one_off)
  File "/usr/local/lib/python2.7/dist-packages/fig/service.py", line 348, in _get_container_create_options
    self.build()
  File "/usr/local/lib/python2.7/dist-packages/fig/service.py", line 366, in build
    nocache=no_cache,
  File "/usr/local/lib/python2.7/dist-packages/fig/packages/docker/client.py", line 354, in build
    context = utils.tar(path)
  File "/usr/local/lib/python2.7/dist-packages/fig/packages/docker/utils/utils.py", line 48, in tar
    t.add(path, arcname='.')
  File "/usr/lib/python2.7/tarfile.py", line 1979, in add
    tarinfo = self.gettarinfo(name, arcname)
  File "/usr/lib/python2.7/tarfile.py", line 1851, in gettarinfo
    statres = os.lstat(name)
OSError: [Errno 2] No such file or directory: 'hub'
```
however if I cd into /some/path and try again, I have success. Any path specified using `-f` should be remembered going forward so that we can use fig in more complex situations where the CWD can be random or not set at all.

**Comment by pospispa** [comment]
IMHO, `build: path` in `.yml` file should be relative to the file and not the CWD because at the time of writing the `.yml` file I know the relative path of the `build: path` to the `.yml` file, however, I have no idea from which CWD I will call `docker-compose`.
As the backward compatibility can't be broken I think a switch must be added to `docker-compose up` and `docker-compose build` commands. I propose to add `--relative` switch to these two commands that will make the `build: path` in `.yml` file relative to the `.yml` file location.

**Comment by dnephin** [comment]
Paths in the `docker-compose.yml` are now relative to the file (I think that was in 1.3?).
