### ISSUE TITLE
Error when using registry: first path segment in URL cannot contain colon

### ISSUE THREAD

**Issue by jamshid** [docker/compose#4924]
I haven't tried to narrow this down, but using Docker for Mac Edge (docker-compose 1.14.0-rc2) with a docker 17.05 server I'm seeing below error. Maybe it's a docker / docker for mac problem?
```
$ docker-compose --version
docker-compose version 1.14.0-rc2, build 24dae73
$ docker version
Client:
 Version:      17.06.0-ce-rc2
 API version:  1.29 (downgraded from 1.30)
 Go version:   go1.8.1
 Git commit:   402dd4a
 Built:        Wed Jun  7 10:02:52 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      17.05.0-ce
 API version:  1.29 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:10:54 2017
 OS/Arch:      linux/amd64
 Experimental: false
```
```
  foo:
    image: 192.168.2.61:5000/foo:latest
   ...
```
```
$ docker-compose pull
...
Downloading images / checking for updates...
Pulling foo (192.168.2.61:5000/foo:latest)...
Traceback (most recent call last):
  File "docker-compose", line 3, in <module>
  File "compose/cli/main.py", line 68, in main
  File "compose/cli/main.py", line 118, in perform_command
  File "compose/cli/main.py", line 641, in pull
  File "compose/project.py", line 480, in pull
  File "compose/service.py", line 994, in pull
  File "site-packages/docker/api/image.py", line 358, in pull
  File "site-packages/docker/auth.py", line 50, in get_config_header
  File "site-packages/docker/auth.py", line 85, in resolve_authconfig
  File "site-packages/docker/auth.py", line 129, in _resolve_authconfig_credstore
docker.errors.DockerException: Credentials store error: StoreError('Credentials store docker-credential-osxkeychain exited with "parse 192.168.2.61:5000: first path segment in URL cannot contain colon".',)
Failed to execute script docker-compose
```

**Comment by jamshid** [comment]
It does seem like this bug/regression is specific to docker-compose. `docker pull` works fine:
```
$ docker pull 192.168.2.61:5000/foo:latest
latest: Pulling from foo
Digest: sha256:71a8268082f7dac4f1e9a875a126ea0c1d7a001001dadd930cdee4c9cdba53a1
Status: Image is up to date for 192.168.2.61:5000/foo:latest
```

**Comment by shin-** [comment]
It might be related to https://github.com/docker/docker-credential-helpers/pull/62 but I'm not too sure why that's happening now.

**Comment by shin-** [comment]
@n4ss I tried to reproduce this on Linux with the `secretservice` 0.5.1 binary but I wasn't able to. Any clue why that might fail on OSX?

**Comment by jamshid** [comment]
If it helps:
```
Docker for Mac: version: 17.06.0-rc2-ce-mac14 (4cdec4294a50b2233146b09469b49937dabdebdd)
macOS: version 10.12.5 (build: 16F73)
logs: /tmp/D6C0858E-2E0F-4F48-AE9C-7E68EE9E2F13/20170613-221725.tar.gz
[OK]     db.git
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[OK]     docker-cli
[OK]     menubar
[OK]     disk
```

**Comment by n4ss** [comment]
This is a known issue as we failed parsing properly URLs + Go 1.8 modifying the behavior for `url.Parse()` that we use for the credentials store on OSX. It doesn't handle yet URLs starting with a digit and with a colon, you'll have to specify the protocol (`http://192.168.2.61:5000/foo:latest`)

This is being solved in https://github.com/docker/docker-credential-helpers/pull/55, I'm currently working on it to get this merged in rc3.

**Comment by shin-** [comment]
Thanks @n4ss, looking forward to it!

**Comment by jamshid** [comment]
Thanks @n4ss and @shin-, this is fixed by the latest Docker for Mac Edge release `17.06.0-rc4-ce-mac15 (18357)`. Feel free to close this, hopefully after adding an automated test that uses a docker-compose.yml that references an image in a registry.

**Comment by shin-** [comment]
Good to know, thanks!

**Comment by sanju7** [comment]
I have Docker version 17.06.0-ce, build 02c1d87. The issue seems to persist.
