### ISSUE TITLE
pip installed docker-compose cannot start up the docker containers

### ISSUE THREAD

**Issue by haoel** [docker/compose#4966]
Not sure I report this issue here is the right place.

If I installed the `docker-compose` by using `pip install docker-compose`, then when I start up, it reports the following error:

```
ERROR: for registry  expected string or buffer
Traceback (most recent call last):
  File "/usr/local/bin/docker-compose", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/compose/cli/main.py", line 68, in main
    command()
  File "/usr/local/lib/python2.7/dist-packages/compose/cli/main.py", line 118, in perform_command
    handler(command, command_options)
  File "/usr/local/lib/python2.7/dist-packages/compose/cli/main.py", line 926, in up
    scale_override=parse_scale_args(options['--scale']),
  File "/usr/local/lib/python2.7/dist-packages/compose/project.py", line 424, in up
    get_deps
  File "/usr/local/lib/python2.7/dist-packages/compose/parallel.py", line 69, in parallel_execute
    raise error_to_reraise
TypeError: expected string or buffer
```

**There NO problem if I used `curl -L "https://github.com/docker/compose/releases/download/1.14.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose` install the docker-compose**

**Information**

```
$ uname -a
Linux ip-172-31-6-145 4.4.0-59-generic #80-Ubuntu SMP Fri Jan 6 17:47:47 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```

```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.1 LTS
Release:	16.04
Codename:	xenial
```

```
$ docker-compose --version
docker-compose version 1.14.0, build c7bdf9e
```

```
$ cat docker-registry.yaml
nginx:
  image: "nginx:1.9"
  ports:
    - 443:443
  links:
    - registry:registry
  volumes:
    - /docker-registry/nginx/:/etc/nginx/conf.d
    - /etc/ssl/:/etc/ssl
registry:
  image: registry:2
  ports:
    - 127.0.0.1:5000:5000
  environment:
    REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /data
  volumes:
    - /docker-registry/data:/data
```

```
$ docker-compose -f docker-registry.yaml up

ERROR: for registry  expected string or buffer
Traceback (most recent call last):
  File "/usr/local/bin/docker-compose", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/compose/cli/main.py", line 68, in main
    command()
  File "/usr/local/lib/python2.7/dist-packages/compose/cli/main.py", line 118, in perform_command
    handler(command, command_options)
  File "/usr/local/lib/python2.7/dist-packages/compose/cli/main.py", line 926, in up
    scale_override=parse_scale_args(options['--scale']),
  File "/usr/local/lib/python2.7/dist-packages/compose/project.py", line 424, in up
    get_deps
  File "/usr/local/lib/python2.7/dist-packages/compose/parallel.py", line 69, in parallel_execute
    raise error_to_reraise
TypeError: expected string or buffer
```

**Comment by alwynpan** [comment]
I have the exact same problem here.

**Comment by alwynpan** [comment]
tobiasfrust's solution worked for me.

https://github.com/docker/compose/issues/4967

**Comment by alexntt** [comment]
Yeah, `requirements.txt` says:

```
docker==2.3.0
```

but `setup.py` says:

```
docker >= 2.3.0, < 3.0
```

**Comment by tobiasfrust** [comment]
Seems to be introduced with docker==2.4.0 as described here: https://github.com/docker/docker-py/issues/1668

**Comment by haoel** [comment]
Either using `requirements.txt` or adding `docker==2.3.0` work for me, but they all are workaround solutions.

**Comment by Ed42** [comment]
latest docker update via apt-get has broken docker-compose. This is similar but different to the above error:
```
$ docker-compose up -d

ERROR: for elasticsearch  Invalid port "_ServicePort(target=9200, published=9200, protocol=None, mode=None, external_ip=None)", should be [[remote_ip:]remote_port[-remote_port]:]port[/protocol]

ERROR: for redis  Invalid port "_ServicePort(target=6379, published=6379, protocol=None, mode=None, external_ip=None)", should be [[remote_ip:]remote_port[-remote_port]:]port[/protocol]

ERROR: for database  Invalid port "_ServicePort(target=5432, published=5432, protocol=None, mode=None, external_ip=None)", should be [[remote_ip:]remote_port[-remote_port]:]port[/protocol]
Traceback (most recent call last):
  File "/usr/local/bin/docker-compose", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/compose/cli/main.py", line 68, in main
    command()
  File "/usr/local/lib/python2.7/dist-packages/compose/cli/main.py", line 118, in perform_command
    handler(command, command_options)
  File "/usr/local/lib/python2.7/dist-packages/compose/cli/main.py", line 926, in up
    scale_override=parse_scale_args(options['--scale']),
  File "/usr/local/lib/python2.7/dist-packages/compose/project.py", line 424, in up
    get_deps
  File "/usr/local/lib/python2.7/dist-packages/compose/parallel.py", line 69, in parallel_execute
    raise error_to_reraise
ValueError: Invalid port "_ServicePort(target=9200, published=9200, protocol=None, mode=None, external_ip=None)", should be [[remote_ip:]remote_port[-remote_port]:]port[/protocol]
```
I've tried uninstalling docker-compose and re-installing via pip, no luck

**Comment by shin-** [comment]
Somehow I missed this issue - sorry!
You should be able to upgrade `docker` to 2.4.2 now. See #4972
