### ISSUE TITLE
UnicodeEncodeError: 'ascii' codec can't encode character '\u2714' in position 21: ordinal not in range(128)

### ISSUE THREAD

**Issue by Adiqq** [docker/compose#5088]
Hi, I'm using Arch linux and this package https://www.archlinux.org/packages/community/x86_64/docker-compose/ . There's no problem on windows, but on arch there's exception on `docker-compose up`.

```
Traceback (most recent call last):
  File "/usr/bin/docker-compose", line 11, in <module>
    load_entry_point('docker-compose==1.15.0', 'console_scripts', 'docker-compose')()
  File "/usr/lib/python3.6/site-packages/compose/cli/main.py", line 68, in main
    command()
  File "/usr/lib/python3.6/site-packages/compose/cli/main.py", line 118, in perform_command
    handler(command, command_options)
  File "/usr/lib/python3.6/site-packages/compose/cli/main.py", line 944, in up
    cascade_starter = log_printer.run()
  File "/usr/lib/python3.6/site-packages/compose/cli/log_printer.py", line 105, in run
    self.output.write(line)
UnicodeEncodeError: 'ascii' codec can't encode character '\u2714' in position 21: ordinal not in range(128)
```

**Comment by shin-** [comment]
Can you try with a Python 2.7 install and see if the same issue occurs?

**Comment by Adiqq** [comment]
Hi, error occured few times then I reinstalled docker-compose and it disappeared.
It works on Python 3.6, but I'm not sure why it occured in the first place.

**Comment by shin-** [comment]
This part of the code deals with the service logs, so it might not trigger if you don't have unicode characters in your output at this time.

Regardless, thank you for reporting it, I'll take a closer look.
