### ISSUE TITLE
Error shutting down: 'NoneType' object is not callable

### ISSUE THREAD

**Issue by andrewmichaelsmith** [docker/compose#522]
I'm occasionally seeing this error when my application exits with error code 1:

    app_app_1 exited with code 1
    Gracefully stopping... (press Ctrl+C again to force)
    Stopping app_couchdb_1...
    Exception in thread Thread-1 (most likely raised during interpreter shutdown):
    Traceback (most recent call last):
      File "/code/build/fig/out00-PYZ.pyz/threading", line 810, in __bootstrap_inner
      File "/code/build/fig/out00-PYZ.pyz/threading", line 763, in run
      File "/code/build/fig/out00-PYZ.pyz/fig.cli.multiplexer", line 41, in _enqueue_output
      File "/code/build/fig/out00-PYZ.pyz/fig.cli.log_printer", line 56, in _make_log_generator
      File "/code/build/fig/out00-PYZ.pyz/fig.container", line 128, in wait
      File "/code/build/fig/out00-PYZ.pyz/fig.packages.docker.client", line 855, in wait
      File "/code/build/fig/out00-PYZ.pyz/fig.packages.docker.client", line 66, in _post
      File "/code/build/fig/out00-PYZ.pyz/requests.sessions", line 425, in post
      File "/code/build/fig/out00-PYZ.pyz/requests.sessions", line 335, in request
    <type 'exceptions.TypeError'>: 'NoneType' object is not callable

**Comment by pbecotte** [comment]
Exception in thread Thread-1 (most likely raised during interpreter shutdown):
Traceback (most recent call last):
  File "/code/build/docker-compose/out00-PYZ.pyz/threading", line 552, in __bootstrap_inner
  File "/code/build/docker-compose/out00-PYZ.pyz/threading", line 505, in run
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.cli.multiplexer", line 41, in _enqueue_output
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.cli.log_printer", line 62, in _make_log_generator
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.container", line 139, in wait
  File "/code/build/docker-compose/out00-PYZ.pyz/docker.client", line 999, in wait
  File "/code/build/docker-compose/out00-PYZ.pyz/docker.client", line 78, in _post
  File "/code/build/docker-compose/out00-PYZ.pyz/requests.sessions", line 425, in post
  File "/code/build/docker-compose/out00-PYZ.pyz/requests.sessions", line 383, in request
  File "/code/build/docker-compose/out00-PYZ.pyz/requests.sessions", line 486, in send
  File "/code/build/docker-compose/out00-PYZ.pyz/requests.adapters", line 374, in send
<type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'error'

**Comment by dnephin** [comment]
Are you still seeing this bug with the latest version?  It seems to be a bug in `requests`, we need to upgrade it anyway.

**Comment by andrewmichaelsmith** [comment]
I have not seen it in quite some time.

**Comment by dnephin** [comment]
Excellent, going to close this issue.  The `requests` upgrade will happen as part of another issue.

**Comment by j-baker** [comment]
I saw this problem recently. Concerning is that when it happened, the return value was 0. We run our end-to-end tests using docker compose, so this would lead to failing tests being marked as passing. Not sure whether the `requests` upgrade has landed yet, but it would be nice to do something with this error and return nonzero when it happens.
