### ISSUE TITLE
Unable to mount volumes on Windows 10: UnboundLocalError: local variable 'cells_to_erase' referenced before assignment

### ISSUE THREAD

**Issue by AkimaLunar** [docker/compose#5263]
I am getting a persistent error on `docker-compose up`.  I am getting the same error on two different Windows 10 Pro machines.

```
Traceback (most recent call last):
  File "docker-compose", line 6, in <module>
  File "compose\cli\main.py", line 68, in main
  File "compose\cli\main.py", line 121, in perform_command
  File "compose\cli\main.py", line 954, in up
  File "compose\cli\log_printer.py", line 105, in run
  File "compose\cli\log_printer.py", line 109, in write
  File "codecs.py", line 370, in write
  File "site-packages\colorama\ansitowin32.py", line 40, in write
  File "site-packages\colorama\ansitowin32.py", line 141, in write
  File "site-packages\colorama\ansitowin32.py", line 167, in write_and_convert
  File "site-packages\colorama\ansitowin32.py", line 181, in convert_ansi
  File "site-packages\colorama\ansitowin32.py", line 212, in call_win32
  File "site-packages\colorama\winterm.py", line 132, in erase_screen
UnboundLocalError: local variable 'cells_to_erase' referenced before assignment
Failed to execute script docker-compose
```

After the error the port is open and the application is running, but the volumes are not mounted. Here is my setup:

- Edition: Windows 10 Pro
- Version: 1703
- OS Build 15063.674

- Docker version 17.09.0-ce, build afdb6d4
- docker-compose version 1.16.1, build 6d1ac219

**Dockerfile**
```
# Use an official Ubuntu Xenial as a parent image
FROM ubuntu:16.04

# Install Node.js 8 and npm 5
RUN apt-get update
RUN apt-get -qq upgrade
RUN apt-get install -y build-essential
RUN apt-get install -y curl
RUN curl -sL https://deb.nodesource.com/setup_8.x | bash
RUN apt-get install -y nodejs

# Set the working directory to /pretty-prism
WORKDIR /pretty-prism

# Copy the package.json into the container at /pretty-prism
COPY package.json /pretty-prism

# Install any needed packages specified in package.json
RUN npm install

# Define environment variable

# Make port 8080 available to the world outside this container
EXPOSE 8080

# Run `npm start` when the container launches
CMD ["npm", "start"]
```

**docker-compose.yml**
```
version: '3'
services:
  preact:
    build: .
    command: npm start
    ports:
      - "8080:8080"
    volumes:
      - .:/pretty-prism
```

**Comment by shin-** [comment]
This looks to be a bug in one of our dependencies. I created an [issue report](https://github.com/tartley/colorama/issues/147) upstream. In the meantime, You might be able to circumvent the issue using the `--no-ansi` flag. Let me know if that helps!

**Comment by AkimaLunar** [comment]
Thanks, @shin- ! Nope, getting the same error with the flag.

First, the application in the container starts and the exposed port works fine too. But then after any change in files, I get that error.

**Comment by shin-** [comment]
@AkimaLunar Does [this binary](https://ci.appveyor.com/project/docker/compose/build/5263-bump-colorama-3738/artifacts) fix your issue?

**Comment by AkimaLunar** [comment]
Sorry, still getting the same error.

```
Traceback (most recent call last):
  File "docker-compose", line 6, in <module>
  File "compose\cli\main.py", line 68, in main
  File "compose\cli\main.py", line 121, in perform_command
  File "compose\cli\main.py", line 954, in up
  File "compose\cli\log_printer.py", line 105, in run
  File "compose\cli\log_printer.py", line 109, in write
  File "codecs.py", line 370, in write
  File "site-packages\colorama\ansitowin32.py", line 40, in write
  File "site-packages\colorama\ansitowin32.py", line 141, in write
  File "site-packages\colorama\ansitowin32.py", line 167, in write_and_convert
  File "site-packages\colorama\ansitowin32.py", line 181, in convert_ansi
  File "site-packages\colorama\ansitowin32.py", line 212, in call_win32
  File "site-packages\colorama\winterm.py", line 132, in erase_screen
UnboundLocalError: local variable 'cells_to_erase' referenced before assignment
Failed to execute script docker-compose
```

**Comment by shin-** [comment]
That's odd. What's the output of the `version` subcommand with the alternative binary?

**Comment by AkimaLunar** [comment]
It's `docker-compose version 1.16.1, build 6d1ac219`.

**Comment by shin-** [comment]
@AkimaLunar `6d1ac219` is the commit for the 1.16.1 release, it doesn't correspond to the binary I linked to.  To confirm, the build number you should see when testing is `d601408c`.

**Comment by aleho70** [comment]
`d601408c` is not working, `--no-ansi` is mentioned only in main help, but it is not possible to use it with `build` or `up`

**Comment by shin-** [comment]
@aleho70 Could you be more specific? What do you mean when you say d601408 is not working? Do you get the same error message? Something else?

As for `--no-ansi`, it can be used with any subcommand.

**Comment by AkimaLunar** [comment]
@shin-, I am probably not installing it correctly. I am just running the .exe (_as an admin_) and restarting Docker. Is there something else/differently I need to do?

**Comment by AnnatarHe** [comment]
Same issue here.

**Comment by AkimaLunar** [comment]
Just wanted to clarify, that the same config works fine on a Mac, including volumes.

**Comment by shin-** [comment]
@AkimaLunar To test the binary you downloaded, you'll have to replace `docker-compose` in your commands with the full path to the new binary, so instead of `docker-compose up`, something like `C:\Users\Username\Downloads\docker-compose.exe up`

**Comment by AkimaLunar** [comment]
Yup! That solved the issue. I am now getting a more helpful error:

```
ERROR: for preact  Cannot start service preact: error while creating mount source path '/C/Users/akima/Documents/GitHub/pretty-prism-preact': mkdir /C/Users/akima/Documents: permission denied
ERROR: Encountered errors while bringing up the project.
```
Thanks, @shin- ! I feel like this issue can be closed now.

**Comment by shin-** [comment]
Ah, good to hear, and thank you for the follow-up!

**Comment by IngoVals** [comment]
> As for --no-ansi, it can be used with any subcommand.

Is this factual?

`docker-compose up -d  --no-ansi`

Results has the same result as running 

`docker-compose up -h`
