### ISSUE TITLE
AttributeError: 'SocketIO' object has no attribute 'raw'

### ISSUE THREAD

**Issue by graingert** [docker/compose#5353]
docker-composeup redis
Creating procensus_redis_1 ... 
Creating procensus_redis_1

ERROR: for procensus_redis_1  'SocketIO' object has no attribute 'raw'

ERROR: for redis  'SocketIO' object has no attribute 'raw'
```pytb
Traceback (most recent call last):
  File "/home/graingert/.virtualenvs/gitlab/bin/docker-compose", line 11, in <module>
    sys.exit(main())
  File "/home/graingert/.virtualenvs/gitlab/lib/python3.6/site-packages/compose/cli/main.py", line 68, in main
    command()
  File "/home/graingert/.virtualenvs/gitlab/lib/python3.6/site-packages/compose/cli/main.py", line 121, in perform_command
    handler(command, command_options)
  File "/home/graingert/.virtualenvs/gitlab/lib/python3.6/site-packages/compose/cli/main.py", line 952, in up
    start=not no_start
  File "/home/graingert/.virtualenvs/gitlab/lib/python3.6/site-packages/compose/project.py", line 455, in up
    get_deps,
  File "/home/graingert/.virtualenvs/gitlab/lib/python3.6/site-packages/compose/parallel.py", line 70, in parallel_execute
    raise error_to_reraise
  File "/home/graingert/.virtualenvs/gitlab/lib/python3.6/site-packages/compose/parallel.py", line 168, in producer
    result = func(obj)
  File "/home/graingert/.virtualenvs/gitlab/lib/python3.6/site-packages/compose/project.py", line 441, in do
    start=start
  File "/home/graingert/.virtualenvs/gitlab/lib/python3.6/site-packages/compose/service.py", line 471, in execute_convergence_plan
    scale, detached, start
  File "/home/graingert/.virtualenvs/gitlab/lib/python3.6/site-packages/compose/service.py", line 396, in _execute_convergence_create
    "Creating",
  File "/home/graingert/.virtualenvs/gitlab/lib/python3.6/site-packages/compose/parallel.py", line 70, in parallel_execute
    raise error_to_reraise
  File "/home/graingert/.virtualenvs/gitlab/lib/python3.6/site-packages/compose/parallel.py", line 168, in producer
    result = func(obj)
  File "/home/graingert/.virtualenvs/gitlab/lib/python3.6/site-packages/compose/service.py", line 394, in <lambda>
    lambda n: create_and_start(self, n),
  File "/home/graingert/.virtualenvs/gitlab/lib/python3.6/site-packages/compose/service.py", line 387, in create_and_start
    container.attach_log_stream()
  File "/home/graingert/.virtualenvs/gitlab/lib/python3.6/site-packages/compose/container.py", line 177, in attach_log_stream
    self.log_stream = self.attach(stdout=True, stderr=True, stream=True)
  File "/home/graingert/.virtualenvs/gitlab/lib/python3.6/site-packages/compose/container.py", line 254, in attach
    return self.client.attach(self.id, *args, **kwargs)
  File "/home/graingert/.virtualenvs/gitlab/lib/python3.6/site-packages/docker/utils/decorators.py", line 19, in wrapped
    return f(self, resource_id, *args, **kwargs)
  File "/home/graingert/.virtualenvs/gitlab/lib/python3.6/site-packages/docker/api/container.py", line 56, in attach
    response, stream, self._check_is_tty(container)
  File "/home/graingert/.virtualenvs/gitlab/lib/python3.6/site-packages/docker/api/client.py", line 368, in _read_from_socket
    socket = self._get_raw_response_socket(response)
  File "/home/graingert/.virtualenvs/gitlab/lib/python3.6/site-packages/docker/api/client.py", line 276, in _get_raw_response_socket
    sock = response.raw._fp.fp.raw
AttributeError: 'SocketIO' object has no attribute 'raw'
```

**Comment by graingert** [comment]
probably an issue with docker==2.6.0

**Comment by graingert** [comment]
Issue raised over there: https://github.com/docker/docker-py/issues/1799
