### ISSUE TITLE
Docker compose up sometimes fails

### ISSUE THREAD

**Issue by Timunas** [docker/compose#5382]
Hello guys, 
I'm running tests in jenkins and I'm launching containers with docker-compose. So basically I'm running 8 tests at time (concurrently) and each one launches 6 containers. Sometimes tests pass with success other times it fails to start the containers. 
So I managed to see using docker-compose logs that they are not starting because of this errors below:

> Couldn't connect to Docker daemon at http+docker://localunixsocket - is it running?
> If it's at a non-standard location, specify the URL with the DOCKER_HOST environment variable.

What could be causing this issue? Most of builds run all tests with success, but sometimes they fail because of one or two tests that have this error.

Thanks

**Comment by shin-** [comment]
If the engine receives a lot of requests at the same time, some may be reaching the HTTP timeout and assume the daemon to be down as a result. Try setting `COMPOSE_HTTP_TIMEOUT` to a high value (e.g. 600) and see if it helps.

**Comment by Timunas** [comment]
Correct if I'm mistaken but it seems that default timeout is 1 minute, and commands fails in 10 seconds. So probably this is not the problem.

**Comment by shin-** [comment]
Sometimes the only way to be sure is to try it out. But if that doesn't help:

1. Start `dockerd` with debug logs (e.g. `sudo dockerd -D`)
2. Start the jenkins job(s) as you usually do
3. When encountering a failure, inspect the daemon logs. There should be some information in there as to what's causing the connection to be dropped.

**Comment by Timunas** [comment]
Ok. 
I searched in daemon logs to last time it failed and I saw this at the time that test failed:

```
Nov 16 23:49:58 jenkins-node dockerd[87266]: time="2017-11-16T23:49:58.026475188Z" level=info msg="Layer sha256:44d30e0f5d04b8415fa03b18e9e8f6d7db21b3123cf52b78f9161ff0cb3772e8 cleaned up"
Nov 16 23:50:44 jenkins-node dockerd[87266]: http: panic serving @: runtime error: invalid memory address or nil pointer dereference
                                                   goroutine 1943 [running]:
                                                   net/http.(*conn).serve.func1(0xc420c0fe00)
                                                           /usr/local/go/src/net/http/server.go:1721 +0xd0
                                                   panic(0x18463e0, 0x2714250)
                                                           /usr/local/go/src/runtime/panic.go:489 +0x2cf
                                                   github.com/docker/docker/vendor/github.com/docker/libnetwork/drivers/bridge.(*networkConfiguration).conflictsWithNetworks(0xc420acb4a0, 0xc420bcd100, 0x4
                                                           /root/rpmbuild/BUILD/src/engine/.gopath/src/github.com/docker/docker/vendor/github.com/docker/libnetwork/drivers/bridge/bridge.go:349 +0xf0
                                                   github.com/docker/docker/vendor/github.com/docker/libnetwork/drivers/bridge.(*driver).createNetwork(0xc4201edb80, 0xc420acb4a0, 0x0, 0x0)
                                                           /root/rpmbuild/BUILD/src/engine/.gopath/src/github.com/docker/docker/vendor/github.com/docker/libnetwork/drivers/bridge/bridge.go:686 +0x9b6
                                                   github.com/docker/docker/vendor/github.com/docker/libnetwork/drivers/bridge.(*driver).CreateNetwork(0xc4201edb80, 0xc420bcd100, 0x40, 0xc421a06fc0, 0x273
                                                           /root/rpmbuild/BUILD/src/engine/.gopath/src/github.com/docker/docker/vendor/github.com/docker/libnetwork/drivers/bridge/bridge.go:610 +0x21c
                                                   github.com/docker/docker/vendor/github.com/docker/libnetwork.(*controller).addNetwork(0xc420351b00, 0xc423967d40, 0xc421e6b208, 0xc423967d40)
                                                           /root/rpmbuild/BUILD/src/engine/.gopath/src/github.com/docker/docker/vendor/github.com/docker/libnetwork/controller.go:945 +0x157
                                                   github.com/docker/docker/vendor/github.com/docker/libnetwork.(*controller).NewNetwork(0xc420351b00, 0x1abaede, 0x6, 0xc4211cb3a0, 0x12, 0xc420bcd100, 0x4
                                                           /root/rpmbuild/BUILD/src/engine/.gopath/src/github.com/docker/docker/vendor/github.com/docker/libnetwork/controller.go:807 +0xb00
                                                   github.com/docker/docker/daemon.(*Daemon).createNetwork(0xc4203fa600, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x100, 0x0, ...)
                                                           /root/rpmbuild/BUILD/src/engine/.gopath/src/github.com/docker/docker/daemon/network.go:348 +0x5c0
                                                   github.com/docker/docker/daemon.(*Daemon).CreateNetwork(0xc4203fa600, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x100, 0x0, ...)
                                                           /root/rpmbuild/BUILD/src/engine/.gopath/src/github.com/docker/docker/daemon/network.go:279 +0x87
                                                   github.com/docker/docker/api/server/router/network.(*networkRouter).postNetworkCreate(0xc420b1e570, 0x7f14baba94a8, 0xc421a067e0, 0x2754140, 0xc4212f7880
                                                           /root/rpmbuild/BUILD/src/engine/.gopath/src/github.com/docker/docker/api/server/router/network/network_routes.go:231 +0x1ed
                                                   github.com/docker/docker/api/server/router/network.(*networkRouter).(github.com/docker/docker/api/server/router/network.postNetworkCreate)-fm(0x7f14baba9
                                                           /root/rpmbuild/BUILD/src/engine/.gopath/src/github.com/docker/docker/api/server/router/network/network.go:37 +0x69
                                                   github.com/docker/docker/api/server/middleware.ExperimentalMiddleware.WrapHandler.func1(0x7f14baba94a8, 0xc421a067e0, 0x2754140, 0xc4212f7880, 0xc421e895
                                                           /root/rpmbuild/BUILD/src/engine/.gopath/src/github.com/docker/docker/api/server/middleware/experimental.go:27 +0xd8
                                                   github.com/docker/docker/api/server/middleware.VersionMiddleware.WrapHandler.func1(0x7f14baba94a8, 0xc421a067b0, 0x2754140, 0xc4212f7880, 0xc421e89500, 0
                                                           /root/rpmbuild/BUILD/src/engine/.gopath/src/github.com/docker/docker/api/server/middleware/version.go:58 +0x487
                                                   github.com/docker/docker/pkg/authorization.(*Middleware).WrapHandler.func1(0x7f14baba94a8, 0xc421a067b0, 0x2754140, 0xc4212f7880, 0xc421e89500, 0xc421a06
                                                           /root/rpmbuild/BUILD/src/engine/.gopath/src/github.com/docker/docker/pkg/authorization/middleware.go:59 +0x871
                                                   github.com/docker/docker/api/server.(*Server).makeHTTPHandler.func1(0x2754140, 0xc4212f7880, 0xc421e89500)
                                                           /root/rpmbuild/BUILD/src/engine/.gopath/src/github.com/docker/docker/api/server/server.go:137 +0x21a
                                                   net/http.HandlerFunc.ServeHTTP(0xc420d79260, 0x2754140, 0xc4212f7880, 0xc421e89500)
                                                           /usr/local/go/src/net/http/server.go:1942 +0x44
                                                   github.com/docker/docker/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc42041fe50, 0x2754140, 0xc4212f7880, 0xc421e89500)
                                                           /root/rpmbuild/BUILD/src/engine/.gopath/src/github.com/docker/docker/vendor/github.com/gorilla/mux/mux.go:103 +0x255
                                                   github.com/docker/docker/api/server.(*routerSwapper).ServeHTTP(0xc420db77b0, 0x2754140, 0xc4212f7880, 0xc421e89500)
                                                           /root/rpmbuild/BUILD/src/engine/.gopath/src/github.com/docker/docker/api/server/router_swapper.go:29 +0x70
                                                   net/http.serverHandler.ServeHTTP(0xc4204471e0, 0x2754140, 0xc4212f7880, 0xc421e89500)
                                                           /usr/local/go/src/net/http/server.go:2568 +0x92
                                                   net/http.(*conn).serve(0xc420c0fe00, 0x2755d40, 0xc420bcc880)
                                                           /usr/local/go/src/net/http/server.go:1825 +0x612
                                                   created by net/http.(*Server).Serve
                                                           /usr/local/go/src/net/http/server.go:2668 +0x2ce
```

Is this the problem? 

Meanwhile I'm trying to reproduce it, with daemon in debug mode

**Comment by shin-** [comment]
Yup, that's a crash alright, and that totally explains Compose not being able to connect while the daemon is recovering (restarting) after the event. What version of Docker are you using? Is that a RHEL server?

**Comment by Timunas** [comment]
It is a CentOS Linux release 7.4.1708 server and I'm running Docker version 17.09.0-ce

**Comment by shin-** [comment]
Cool, thank you for sharing / confirming. Looks like you're hitting https://github.com/moby/moby/issues/34515. I recommend following that thread as well as https://github.com/docker/libnetwork/pull/1918 for resolution.

**Comment by Timunas** [comment]
ok. Thanks for the help!
