### ISSUE TITLE
1.20.0 output character error

### ISSUE THREAD

**Issue by helsont** [docker/compose#5784]
I recently upgraded to using version 1.20.0-rc2 and encountered this issue I'd never seen before. From the looks of it, it looks like it's an encoding issue... any other context needed?

```
Traceback (most recent call last):
  File "bin/docker-compose", line 6, in <module>
  File "compose/cli/main.py", line 71, in main
  File "compose/cli/main.py", line 127, in perform_command
  File "compose/cli/main.py", line 280, in build
  File "compose/project.py", line 372, in build
  File "compose/service.py", line 1003, in build
  File "compose/progress_stream.py", line 23, in stream_output
  File "compose/progress_stream.py", line 90, in print_output_event
UnicodeEncodeError: 'ascii' codec can't encode character '\u2013' in position 151: ordinal not in range(128)
[96] Failed to execute script docker-compose
Exited with code 255
```

**Comment by shin-** [comment]
Thanks for the report! I'll take a closer look, but is there a possibility your shell isn't configured to output utf-8 encoded characters?

**Comment by helsont** [comment]
I've run these same scripts using docker 1.12 and I didn't have any issues with it before.

**Comment by shin-** [comment]
@helsont I'm having trouble reproducing this locally. If you don't mind answering those questions, that would be super helpful:

1. How did you install Compose?
2. What is the output of `docker-compose version`?
3. What command are you executing that causes the error to appear?
4. Are you redirecting the output of the program to a file or device other than the console?

Thanks!

**Comment by helsont** [comment]
To prefix this: I'm running docker-compose from within circleci's local testing CLI tool. It runs by using my local docker to emulate what's going on in their build servers.

1. I installed compose with the following commands:
```
curl -L https://github.com/docker/compose/releases/download/1.20.0-rc1/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
chmod +x ~/docker-compose
sudo mv ~/docker-compose /usr/local/bin/docker-compose```
2. docker-compose version:
```docker-compose version 1.20.0-rc1, build 86428af
docker-py version: 3.1.0
CPython version: 3.6.4
OpenSSL version: OpenSSL 1.0.1t  3 May 2016
```
3. The command that triggers it is `composer install` in a PHP laravel project. 
Expected output:
```
...
namshi/jose suggests installing phpseclib/phpseclib (Allows to use Phpseclib as crypto engine, use version ^2.0.)
php-amqplib/php-amqplib suggests installing ext-sockets (Use AMQPSocketConnection)
voku/portable-utf8 suggests installing ext-intl (Use Intl for best performance)
phpspec/phpspec suggests installing phpspec/nyan-formatters (~1.0 – Adds Nyan formatters)
sebastian/global-state suggests installing ext-uopz (*)
```
Actual output:
```
...
namshi/jose suggests installing phpseclib/phpseclib (Allows to use Phpseclib as crypto engine, use version ^2.0.)
php-amqplib/php-amqplib suggests installing ext-sockets (Use AMQPSocketConnection)
voku/portable-utf8 suggests installing ext-intl (Use Intl for best performance)
Traceback (most recent call last):
  File "bin/docker-compose", line 6, in <module>
  File "compose/cli/main.py", line 71, in main
  File "compose/cli/main.py", line 127, in perform_command
  File "compose/cli/main.py", line 280, in build
  File "compose/project.py", line 372, in build
  File "compose/service.py", line 1004, in build
  File "compose/progress_stream.py", line 23, in stream_output
  File "compose/progress_stream.py", line 90, in print_output_event
UnicodeEncodeError: 'ascii' codec can't encode character '\u2013' in position 71: ordinal not in range(128)
[39] Failed to execute script docker-compose
```

4. It's being run inside a docker container managed by circleci.

**Comment by shin-** [comment]
Thank you!
