### ISSUE TITLE
Error on docker-compose up with TCP connection to Docker for Win daemon

### ISSUE THREAD

**Issue by tejksat** [docker/compose#5851]
##  Description of the issue

"OSError: [Errno 9] Bad file descriptor" exception is raised when running `docker-compose up` command for Docker for Win while using the TCP connection to the Docker daemon.

This scenario, however unusual, though required for the Docker Compose integration in IntelliJ products 2018.1. Please see https://youtrack.jetbrains.com/issue/PY-29185.

## Context information

```
C:\>docker-compose version
docker-compose version 1.20.1, build 5d8c71b2
docker-py version: 3.1.4
CPython version: 3.6.4
OpenSSL version: OpenSSL 1.0.2k  26 Jan 2017
```

```
C:\>docker version
Client:
 Version:       18.03.0-ce
 API version:   1.37
 Go version:    go1.9.4
 Git commit:    0520e24
 Built: Wed Mar 21 23:06:28 2018
 OS/Arch:       windows/amd64
 Experimental:  false
 Orchestrator:  swarm

Server:
 Engine:
  Version:      18.03.0-ce
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.9.4
  Git commit:   0520e24
  Built:        Wed Mar 21 23:14:32 2018
  OS/Arch:      linux/amd64
  Experimental: true
```

```
C:\Users\user\project>docker-compose config
services:
  app:
    image: python:3
version: '3.0'


```

## Steps to reproduce the issue

1. In Docker _Settings_ on _General_ tab select _Expose daemon on tcp://localhost:2375 without TLS_ checkbox.
2. Run `set DOCKER_HOST=tcp://localhost:2375` in a Command Prompt.
3. Run `docker-compose up` in the Command Prompt for the specified docker-compose configuration file.

### Observed result
```
Starting dockercompose_app_1 ... done
Attaching to dockercompose_app_1
Traceback (most recent call last):
  File "docker-compose", line 6, in <module>
  File "compose\cli\main.py", line 71, in main
  File "compose\cli\main.py", line 127, in perform_command
  File "compose\cli\main.py", line 1065, in up
  File "compose\cli\log_printer.py", line 87, in run
  File "compose\cli\log_printer.py", line 245, in consume_queue
  File "compose\cli\log_printer.py", line 160, in tail_container_logs
  File "compose\utils.py", line 61, in split_buffer
  File "compose\utils.py", line 37, in stream_as_text
  File "site-packages\docker\utils\socket.py", line 73, in frames_iter
  File "site-packages\docker\utils\socket.py", line 60, in next_frame_size
  File "site-packages\docker\utils\socket.py", line 45, in read_exactly
  File "site-packages\docker\utils\socket.py", line 32, in read
OSError: [Errno 9] Bad file descriptor
[11820] Failed to execute script docker-compose
```

### Expected result
Successful execution.

### Stacktrace / full error message

```
Traceback (most recent call last):
  File "docker-compose", line 6, in <module>
  File "compose\cli\main.py", line 71, in main
  File "compose\cli\main.py", line 127, in perform_command
  File "compose\cli\main.py", line 1065, in up
  File "compose\cli\log_printer.py", line 87, in run
  File "compose\cli\log_printer.py", line 245, in consume_queue
  File "compose\cli\log_printer.py", line 160, in tail_container_logs
  File "compose\utils.py", line 61, in split_buffer
  File "compose\utils.py", line 37, in stream_as_text
  File "site-packages\docker\utils\socket.py", line 73, in frames_iter
  File "site-packages\docker\utils\socket.py", line 60, in next_frame_size
  File "site-packages\docker\utils\socket.py", line 45, in read_exactly
  File "site-packages\docker\utils\socket.py", line 32, in read
OSError: [Errno 9] Bad file descriptor
[11820] Failed to execute script docker-compose
```

## Additional information

```
C:\>ver

Microsoft Windows [Version 10.0.16299.309]
```

**Comment by shin-** [comment]
Thanks for the report!

**Comment by fechnert** [comment]
Any progress or further information on this bug? Happened to experience the same issue with the newest PyCharm version `2018.1.1`

**Comment by pfyod** [comment]
Workaround for IDEA (and I guess other IntelliJ IDEs running on Windows):
Create a script `docker-compose-proxy.bat` containing
```
@echo off
set DOCKER_HOST=
docker-compose %*
```
Configure IDEA's "Docker Compose executable" to use this script.

**Comment by nissimk** [comment]
I can report the same issue happening with compose from docker toolbox on Windows connecting to docker host in a virtualbox linux vm. Same behavior happens from git bash with / without winpty and from CMD window. Workaround of unsetting DOCKER_HOST does not work because the default pipe is not available in virtualbox configuration.

$ docker-compose version
docker-compose version 1.20.1, build 5d8c71b2
docker-py version: 3.1.4
CPython version: 3.6.4
OpenSSL version: OpenSSL 1.0.2k  26 Jan 2017

$ docker info
Containers: 7
 Running: 2
 Paused: 0
 Stopped: 5
Images: 24
Server Version: 1.13.0
Storage Driver: overlay
 Backing Filesystem: xfs
 Supports d_type: false
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log:
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 03e5862ec0d8d3b3f750e19fca3ee367e13c090e
runc version: 2f7393a47307a16f8cee44a37b262e8b81021e3e
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-514.6.1.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 3.702GiB
Name: XXXX
ID: XXXX
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
HTTP Proxy: XXXX
No Proxy: localhost,127.0.0.1
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

**Comment by shin-** [comment]
Will be fixed by https://github.com/docker/docker-py/pull/2045 in the next release.
