### ISSUE TITLE
Failed to execute

### ISSUE THREAD

**Issue by Chin077** [docker/compose#5856]
Hi, i am quiet new to docker and i want to host a discord bot on it so when i try it this happends

`PS C:\Users\chinw\Desktop\Fredboat> docker-compose up -d
Traceback (most recent call last):
  File "docker-compose", line 6, in <module>
  File "compose\cli\main.py", line 71, in main
  File "compose\cli\main.py", line 124, in perform_command
  File "compose\cli\command.py", line 38, in project_from_options
  File "compose\cli\docker_client.py", line 84, in tls_config_from_options
  File "site-packages\docker\tls.py", line 81, in __init__
docker.errors.TLSParameterError: Path to a certificate and key files must be provided through the client_config param. TLS configurations should map the Docker CLI client configurations. See https://docs.docker.com/engine/articles/https/ for API details.
[6068] Failed to execute script docker-compose`

**Comment by shin-** [comment]
It won't be possible for us to help if you don't fill out the issue template properly. If you're still struggling with this, please recreate the issue with the required information.
