### ISSUE TITLE
Docker-compose source code build steps on ppc64le

### ISSUE THREAD

**Issue by AnitaNayak** [docker/compose#6133]
Can anyone please let me know what are the steps to build docker-compose binary on ppc64le.

**Comment by shin-** [comment]
Speaking candidly, this is not something that is officially supported, or even expected to be in the future. That said, it seems like PyInstaller should be compatible with PowerPC architectures (ref: https://github.com/pyinstaller/pyinstaller/issues/2050 , https://github.com/pyinstaller/pyinstaller/issues/2000) with some tinkering (as described in the aforementioned issues), meaning it should be possible to do in theory.

**Comment by AnitaNayak** [comment]
Thank you. pyinstaller is available on ppc64le. Installer it through pip. But still when I tried building docker-compose 1.21.2, getting below error:
18348 INFO: Building PKG (CArchive) out00-PKG.pkg completed successfully.
18355 INFO: Bootloader /root/WCV/docker-compose-git/compose/venv/lib/python3.5/site-packages/PyInstaller/bootloader/Linux-64bit/run
18355 INFO: checking EXE
18355 INFO: Building EXE because out00-EXE.toc is non existent
18355 INFO: Building EXE from out00-EXE.toc
18355 INFO: Appending archive to ELF section in EXE /root/WCV/docker-compose-git/compose/dist/docker-compose
Traceback (most recent call last):
  File "venv/bin/pyinstaller", line 11, in <module>
    sys.exit(run())
  File "/root/WCV/docker-compose-git/compose/venv/lib/python3.5/site-packages/PyInstaller/__main__.py", line 94, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "/root/WCV/docker-compose-git/compose/venv/lib/python3.5/site-packages/PyInstaller/__main__.py", line 46, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "/root/WCV/docker-compose-git/compose/venv/lib/python3.5/site-packages/PyInstaller/building/build_main.py", line 791, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "/root/WCV/docker-compose-git/compose/venv/lib/python3.5/site-packages/PyInstaller/building/build_main.py", line 737, in build
    exec(text, spec_namespace)
  File "<string>", line 101, in <module>

I could find there is a binary under ./venv/bin/docker-compose, which is working on the same setup. But when I copy this binary to some other setup, but getting error (it is looking for exact build path where I built this)-- compose-1.21.2/venv/bin/python3: bad interpreter: No such file or directory
