### ISSUE TITLE
[probably duplicate?] IndexError from Validation

### ISSUE THREAD

**Issue by andy-d** [docker/compose#6325]
Stack trace below. Here is version info:

``` bash
$ docker-compose version
docker-compose version 1.22.0, build f46880f
docker-py version: 3.5.0
CPython version: 3.5.2
OpenSSL version: OpenSSL 1.0.2p  14 Aug 2018
```

Stack trace
``` python
$ docker-compose up
Traceback (most recent call last):
  File "/Users/andy/virtualenvs/kode-venv/bin/docker-compose", line 11, in <module>
    sys.exit(main())
  File "/Users/andy/virtualenvs/kode-venv/lib/python3.5/site-packages/compose/cli/main.py", line 71, in main
    command()
  File "/Users/andy/virtualenvs/kode-venv/lib/python3.5/site-packages/compose/cli/main.py", line 124, in perform_command
    project = project_from_options('.', options)
  File "/Users/andy/virtualenvs/kode-venv/lib/python3.5/site-packages/compose/cli/command.py", line 41, in project_from_options
    compatibility=options.get('--compatibility'),
  File "/Users/andy/virtualenvs/kode-venv/lib/python3.5/site-packages/compose/cli/command.py", line 113, in get_project
    config_data = config.load(config_details, compatibility)
  File "/Users/andy/virtualenvs/kode-venv/lib/python3.5/site-packages/compose/config/config.py", line 385, in load
    for config_file in config_details.config_files
  File "/Users/andy/virtualenvs/kode-venv/lib/python3.5/site-packages/compose/config/config.py", line 385, in <listcomp>
    for config_file in config_details.config_files
  File "/Users/andy/virtualenvs/kode-venv/lib/python3.5/site-packages/compose/config/config.py", line 552, in process_config_file
    validate_against_config_schema(config_file)
  File "/Users/andy/virtualenvs/kode-venv/lib/python3.5/site-packages/compose/config/validation.py", line 437, in validate_against_config_schema
    config_file.filename)
  File "/Users/andy/virtualenvs/kode-venv/lib/python3.5/site-packages/compose/config/validation.py", line 498, in handle_errors
    error_msg = '\n'.join(format_error_func(error) for error in errors)
  File "/Users/andy/virtualenvs/kode-venv/lib/python3.5/site-packages/compose/config/validation.py", line 498, in <genexpr>
    error_msg = '\n'.join(format_error_func(error) for error in errors)
  File "/Users/andy/virtualenvs/kode-venv/lib/python3.5/site-packages/compose/config/validation.py", line 420, in process_config_schema_errors
    error_msg = handle_error_for_schema_with_id(error, path)
  File "/Users/andy/virtualenvs/kode-venv/lib/python3.5/site-packages/compose/config/validation.py", line 274, in handle_error_for_schema_with_id
    invalid_config_key = parse_key_from_error_msg(error)
  File "/Users/andy/virtualenvs/kode-venv/lib/python3.5/site-packages/compose/config/validation.py", line 333, in parse_key_from_error_msg
    return error.message.split("'")[1]
IndexError: list index out of range
```

**Comment by shin-** [comment]
@andy-d Thanks for the report! We'll make sure that gets fixed.

FWIW, your Compose file should look like this instead:
```yaml
{
  "services": {
    "postgres": {
      "image": "postgres:9.6",
      "ports": ["5432:5432"]
    },
  },
  "version": "3.1"
}
```

(see the [Compose file reference](https://docs.docker.com/compose/compose-file) for details)

**Comment by andy-d** [comment]
Thanks @shin- yep I corrected that. The issue was the stack trace as you know clearly.
