### ISSUE TITLE
"docker-compose config" fails with UnicodeEncodeError when launched with output redirection if output contains unicode characters

### ISSUE THREAD

**Issue by bwateratmsft** [docker/compose#6348]
## Description of the issue
If "docker-compose config" is run against YAML files such that the output contains unicode characters (for example, path, of the dockerfile), and run with output redirection, it fails with:

```
[9388] Failed to execute script docker-compose
Traceback (most recent call last):
  File "docker-compose", line 6, in <module>
  File "compose\cli\main.py", line 71, in main
  File "compose\cli\main.py", line 121, in perform_command
  File "compose\cli\main.py", line 351, in config
  File "c:\projects\compose\venv\lib\encodings\cp1252.py", line 19, in encode
UnicodeEncodeError: 'charmap' codec can't encode characters in position 87-90: character maps to <undefined>
```

## Context information (for bug reports)

**Output of `docker-compose version`**
```
>docker-compose version
docker-compose version 1.22.0, build f46880fe
docker-py version: 3.4.1
CPython version: 3.6.6
OpenSSL version: OpenSSL 1.0.2o  27 Mar 2018
```

**Output of `docker version`**
```
>docker version
Client:
 Version:           18.06.1-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        e68fc7a
 Built:             Tue Aug 21 17:21:34 2018
 OS/Arch:           windows/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.1-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       e68fc7a
  Built:            Tue Aug 21 17:29:02 2018
  OS/Arch:          linux/amd64
  Experimental:     true
```

**Output of `docker-compose config`**
```
>docker-compose -f "C:\Users\myUser\source\repos\MyApp2 雕\docker-compose.yml" -f "C:\Users\myUser\source\repos\MyApp2 雕\docker-compose.override.yml" -p dockercompose597229694053810312 --no-ansi config
services:
  myapp2:
    build:
      context: C:\Users\myUser\source\repos\MyApp2 雕
      dockerfile: MyApp2 雕/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_HTTPS_PORT: '44343'
      ASPNETCORE_URLS: https://+:443;http://+:80
    image: myapp2
    ports:
    - published: 58378
      target: 80
    - published: 44343
      target: 443
    volumes:
    - C:\Users\myUser\AppData\Roaming\ASP.NET\Https:/root/.aspnet/https:ro
    - C:\Users\myUser\AppData\Roaming\Microsoft\UserSecrets:/root/.microsoft/usersecrets:ro
version: '3.4'
```

## Steps to reproduce the issue

1. Create a simple C# console project that will run docker-compose config
2. In it, use a ProcessStartInfo with UseShellExecute=false, RedirectStandardOutput true, FileName "docker-compose", arguments like @"-f ""C:\Users\myUser\source\repos\MyApp2 雕\docker-compose.yml"" -f ""C:\Users\myUser\source\repos\MyApp2 雕\docker-compose.override.yml"" -p dockercompose597229694053810312 --no-ansi config"
3. Launch

### Observed result
Printing the output of standard error gives the below stack trace from UnicodeEncodeError

### Expected result
No error, and the config is printed like when launched from command line

### Stacktrace / full error message

```
[9388] Failed to execute script docker-compose
Traceback (most recent call last):
  File "docker-compose", line 6, in <module>
  File "compose\cli\main.py", line 71, in main
  File "compose\cli\main.py", line 121, in perform_command
  File "compose\cli\main.py", line 351, in config
  File "c:\projects\compose\venv\lib\encodings\cp1252.py", line 19, in encode
UnicodeEncodeError: 'charmap' codec can't encode characters in position 87-90: character maps to <undefined>
```

## Additional information

Win 10 version 1809
Please note the output of the above commands is lightly redacted.

**Comment by shin-** [comment]
Thanks for the report!

Do you know if regional / language settings are relevant at all when attempting to reproduce the issue?

**Comment by bwateratmsft** [comment]
It definitely might be related.  I'm on an ENU OS.  I did try changing code page to 65001 together with the command but it didn't seem to have any effect. (cmd /C chcp 65001 & docker-compose …)

**Comment by shin-** [comment]
I see! The stacktrace you shared mentions [this line](https://github.com/docker/compose/blob/1.22.0/compose/cli/main.py#L351), which is where we attempt to print the serialized configuration (internally encoded to utf-8) to the terminal (which may not support said encoding / may be expecting cp1252 instead).
I'll take a look and see if we can add a fallback mechanism there.

**Comment by pratiksanglikar** [comment]
We can still reproduce this issue on the latest docker desktop.
```
mbp ~ % docker-compose -version
docker-compose version 1.25.5, build 8a1c60f6
mbp ~ % docker version         
Client: Docker Engine - Community
 Version:           19.03.8
 API version:       1.40
 Go version:        go1.12.17
 Git commit:        afacb8b
 Built:             Wed Mar 11 01:21:11 2020
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.8
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.17
  Git commit:       afacb8b
  Built:            Wed Mar 11 01:29:16 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

Can you please reopen the issue?
