### ISSUE TITLE
Execute docker-compose failed: Failed to execute script pyiboot01_bootstrap

### ISSUE THREAD

**Issue by leikao** [docker/compose#6462]
## Description of the issue

Run `docker-compose -v` failed: 
> ./docker-compose -v
> Traceback (most recent call last):
>   File "site-packages/PyInstaller/loader/pyiboot01_bootstrap.py", line 127, in <module>
>   File "<frozen importlib._bootstrap>", line 971, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
>   File "/code/.tox/py36/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 631, in exec_module
>   File "ctypes/__init__.py", line 538, in <module>
>   File "ctypes/__init__.py", line 273, in _reset_cache
> MemoryError
> [128273] Failed to execute script pyiboot01_bootstrap

## Context information (for bug reports)
`docker-compose` download link:
https://github.com/docker/compose/releases/download/1.23.2/docker-compose-Linux-x86_64

OS info:
> $ lsb_release -a
> LSB Version:	:core-4.1-amd64:core-4.1-noarch
> Distributor ID:	CentOS
> Description:	CentOS Linux release 7.6.1810 (Core) 
> Release:	7.6.1810
> Codename:	Core
> $ uname -r
> 3.10.0-957.1.3.el7.x86_64
> $ arch
> x86_64
> $ docker -v
> Docker version 18.09.1, build 4c52b90

## Steps to reproduce the issue

1. curl -L "https://github.com/docker/compose/releases/download/1.23.2/docker-compose-Linux-x86_64" > ./docker-compose
2. chmod +x ./docker-compose
3. ./docker-compose -v

**Comment by chris-crone** [comment]
I tried to reproduce this on a CentOS virtual machine and wasn't able to. It appears that you have a `MemoryError` so I suspect it might be related to your specific system.

**Comment by leikao** [comment]
I downgrade the version of CentOS from *7.6.1810* to *7.4.1708*, then it works well again.
- **CentOS v7.4.1708** works well
- **CentOS v7.6.1810** works well
- **CentOS v7.4.1708 upgrade to v7.6.1810** NOT work

There may be something wrong with the CentOS upgrade process. I'll close the thread, thank you all again.

**Comment by chris-crone** [comment]
Thanks for taking the time to debug @leikao! Definitely sounds like there's something up with the upgrade process.

**Comment by MostHated** [comment]
I get a similar error now as well. Sometimes I go to run a command (docker-compose up, down, etc) and it will sit there and hang, sometimes for minutes at a time with no cpu activity, but with the cursor moved to the next line as if its running. Sometimes it will eventually run, others I get the following:

```
Traceback (most recent call last):

  File "bin/docker-compose", line 5, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "/code/.tox/py36/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 631, in exec_module
  File "compose/cli/main.py", line 17, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "/code/.tox/py36/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 631, in exec_module
  File "site-packages/docker/__init__.py", line 2, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "/code/.tox/py36/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 631, in exec_module
  File "site-packages/docker/api/__init__.py", line 2, in <module>
```

It continues on for several more lines like this. but the very last part is:

```
  File "site-packages/nacl/bindings/__init__.py", line 377, in <module>
  File "site-packages/nacl/bindings/sodium_core.py", line 32, in sodium_init
  File "site-packages/nacl/bindings/sodium_core.py", line 22, in _sodium_init
[23994] Failed to execute script docker-compose
```

docker-compose version 1.24.0, build 0aa59064
Docker version 18.09.2, build 6247962
Python 3.6.8

**Comment by glebmish** [comment]
I also have same error as @MostHated 

docker-compose version 1.24.0 (don't know exact build as `docker-compose --version` fails, but downloaded from https://github.com/docker/compose/releases/download/1.24.0/docker-compose-Linux-x86_64)
Docker version 18.09.5, build e8ff056
Python 3.5.2

Previous version works fine: docker-compose version 1.23.0, build c8524dc1

**Comment by xBioDreadx** [comment]
got same error sometimes...

Docker version 18.09.6, build 481bc77
docker-compose version 1.24.0, build 0aa59064
Python 3.6.8
Ubuntu 18.04.2 LTS (GNU/Linux 4.15.0-1033-gcp x86_64)

**Comment by lonix1** [comment]
Same here

Did anyone solve this?

**Comment by lonix1** [comment]
If this was a problem for you please upvote https://github.com/docker/compose/issues/6931 so we can get better docs, which would have avoided lots of wasted time chasing down this problem.

**Comment by technoweenie** [comment]
This is happening to me on a brand new docker-compose install on a freshly installed mac os.  Installed v1.25.0 with homebrew, "Poured from bottle on 2019-12-29 at 21:40:08".

**Comment by ravindu1024** [comment]
Thanks for that @lonix1 :+1: 
Can confirm that installing haveged fixed this for me. Had the same issue and the available entropy was about 10. It went up to 2000+ after installing haveged and all docker-compose commands work now.
Docker version: 20.10.1
Docker Compose version: 1.27.4
OS version: Ubuntu 20.04 LTS
