### ISSUE TITLE
docker-compose fails with ssh:// protocol with PasswordRequiredException: Private key file is encrypted

### ISSUE THREAD

**Issue by ssbarnea** [docker/compose#6513]
It seems that current paramiko code in code in docker-compose is flawed and fails to use ssh key loaded in the agent.

It seems that the same bug also afectts docker-py at https://github.com/docker/docker-py/issues/2251 but I am sure that this use-case is covered by paramiko because other tools using it have no problems using the ssh key (example ansible).

It should not be hard to replicate the issue locally using a loopback ssh connection, no need for a remote server.

```bash
export DOCKER_HOST=ssh://$USER@localhost
docker info
# ^ this works, docker is able to use the ssh protocol

docker-compose build
```

The command abone will choke with an error similar to below:

```
$ docker-compose build                                                                                                                                                                                 {u'stackOrchestrator': u'swarm'}
Connected (version 2.0, client OpenSSH_7.4)
Authentication (publickey) failed.
Authentication (publickey) failed.
Traceback (most recent call last):
File "/Users/ssbarnea/.pyenv/versions/2.7.15/bin/docker-compose", line 11, in <module>
sys.exit(main())
File "/Users/ssbarnea/.pyenv/versions/2.7.15/lib/python2.7/site-packages/compose/cli/main.py", line 71, in main
command()
File "/Users/ssbarnea/.pyenv/versions/2.7.15/lib/python2.7/site-packages/compose/cli/main.py", line 124, in perform_command
project = project_from_options('.', options)
File "/Users/ssbarnea/.pyenv/versions/2.7.15/lib/python2.7/site-packages/compose/cli/command.py", line 42, in project_from_options
compatibility=options.get('--compatibility'),
File "/Users/ssbarnea/.pyenv/versions/2.7.15/lib/python2.7/site-packages/compose/cli/command.py", line 123, in get_project
host=host, environment=environment
File "/Users/ssbarnea/.pyenv/versions/2.7.15/lib/python2.7/site-packages/compose/cli/command.py", line 94, in get_client
environment=environment, tls_version=get_tls_version(environment)
File "/Users/ssbarnea/.pyenv/versions/2.7.15/lib/python2.7/site-packages/compose/cli/docker_client.py", line 127, in docker_client
client = APIClient(**kwargs)
File "/Users/ssbarnea/os/docker-py/docker/api/client.py", line 166, in __init__
base_url, timeout, pool_connections=num_pools
File "/Users/ssbarnea/os/docker-py/docker/transport/sshconn.py", line 94, in __init__
password=None
File "/Users/ssbarnea/.pyenv/versions/2.7.15/lib/python2.7/site-packages/paramiko/client.py", line 437, in connect
passphrase,
File "/Users/ssbarnea/.pyenv/versions/2.7.15/lib/python2.7/site-packages/paramiko/client.py", line 749, in _auth
raise saved_exception
paramiko.ssh_exception.PasswordRequiredException: Private key file is encrypted
```

I removed the encrypted key, hopping that docker will use the agent one,  but instead It fails with
```
paramiko.ssh_exception.AuthenticationException: Authentication failed.
```

The proof that I do have key working (and obviously doing ssh works):
```
$ ssh-add -l
4096 SHA256:IIgRCJ84QIlEIoYJ1RiFYRwPlbxXVr3z/7jo+FTM6zg  (RSA)
```

**Comment by ssbarnea** [comment]
It proved to be caused by paramiko https://github.com/paramiko/paramiko/issues/1383 -- in case someone else encounters it we could maybe add a runtime warning if the ssh:// url does not contain a user. Missing user does not mean that `~/.ssh/config` one will be used, just mean current user.

`docker` will user the one from ssh config but docker-compose or docker-py would not!

**Comment by maxbaluev** [comment]
How fix it?

**Comment by NitroBAY** [comment]
I have the same problem, I'm using windows 10 cmd. Docker info works not docker compose. I have DOCKER_HOST=ssh://root@149.91.81.121 and the exact same bug as you.
"paramiko.ssh_exception.PasswordRequiredException: Private key file is encrypted"

>  if the ssh:// url does not contain a user.
root is the user in my url right ? I still have this bug though

**Comment by NitroBAY** [comment]
@ssbarnea

**Comment by qm3ster** [comment]
same problem

**Comment by jsgv** [comment]
I encountered the same error. It seems like `~/.ssh/config` is not respected.

Adding the key to ssh-agent fixed it for me. `ssh-add -K ~/.ssh/customkey`. Make sure you don't have too many keys in your agent otherwise it will try all keys and it might fail before reaching the correct one.

**Comment by azsdaja** [comment]
Can't help it on Windows. Used `-k` (Load only keys and not certificates) since there was no `-K` option in ssh-add.
I also created config file with User and IdentityFile properties for given host, even though I believe it's not needed in my case.
`docker -H` commands work, but `docker-compose -H` still are giving me `paramiko.ssh_exception.AuthenticationException: Authentication failed`.

**Comment by xcellenceit** [comment]
Does this issue is resolved?

**Comment by franzfloresjr** [comment]
Having the same problem. Can't deploy with `docker context` on remote host.

**Comment by raybiwo** [comment]
how fix it?

**Comment by aiordache** [comment]
Hi! Would you mind trying with docker-compose 1.28.0-rc2 / rc3 please? This version connects via shellout to the ssh client, it is not using paramiko.

**Comment by mpkayeuk** [comment]
> Hi! Would you mind trying with docker-compose 1.28.0-rc2 / rc3 please? This version connects via shellout to the ssh client, it is not using paramiko.

I've just tried this with docker-compose 1.28.2 and it works perfectly. Thanks!

**Comment by moracabanas** [comment]
> Hi! Would you mind trying with docker-compose 1.28.0-rc2 / rc3 please? This version connects via shellout to the ssh client, it is not using paramiko.

I trying everything to get docker-compose working but I get this trace:
```error
$ docker-compose up

Traceback (most recent call last):
  File "bin/docker-compose", line 3, in <module>
  File "compose/cli/main.py", line 67, in main
  File "compose/cli/main.py", line 123, in perform_command
  File "compose/cli/command.py", line 69, in project_from_options
  File "compose/cli/command.py", line 132, in get_project
  File "compose/cli/docker_client.py", line 43, in get_client
  File "compose/cli/docker_client.py", line 170, in docker_client
  File "docker/api/client.py", line 164, in __init__
  File "docker/transport/sshconn.py", line 113, in __init__
  File "docker/transport/sshconn.py", line 121, in _connect
  File "paramiko/client.py", line 446, in connect
  File "paramiko/client.py", line 764, in _auth
  File "paramiko/client.py", line 735, in _auth
  File "paramiko/client.py", line 586, in _key_from_filepath
  File "paramiko/pkey.py", line 235, in from_private_key_file
  File "paramiko/rsakey.py", line 55, in __init__
  File "paramiko/rsakey.py", line 175, in _from_private_key_file
  File "paramiko/pkey.py", line 308, in _read_private_key_file
  File "paramiko/pkey.py", line 337, in _read_private_key
  File "paramiko/pkey.py", line 439, in _read_private_key_openssh
paramiko.ssh_exception.PasswordRequiredException: private key file is encrypted
[493] Failed to execute script docker-compose
```

I am using Docker Destop on windows 10 and docker-compose on WSL2 (already integrated with Docker in settings)

I just do a fresh Docker Destop install and doesn't work.

`docker-compose version` repots:

docker-compose version 1.27.4, build 40524192
docker-py version: 4.3.1
CPython version: 3.7.7
OpenSSL version: OpenSSL 1.1.0l  10 Sep 2019

How can I upgrade docker-compose on this setup to 1.28.2?

Thanks you

**Comment by swilliams96** [comment]
> @moracabanas 
How can I upgrade docker-compose on this setup to 1.28.2?

If you right click the Docker Desktop icon in your taskbar and click "Check for Updates" it will bring up a window with the new version. After it installs you can run `docker-compose version` again and you should see `1.28.5` or greater.

**Comment by moracabanas** [comment]
> > @moracabanas 
> How can I upgrade docker-compose on this setup to 1.28.2?
> 
> If you right click the Docker Desktop icon in your taskbar and click "Check for Updates" it will bring up a window with the new version. After it installs you can run `docker-compose version` again and you should see `1.28.5` or greater.

You are right! I downloaded Docker Desktop again from the main source, but that wasn't the latest version at all.
I had to check for updated as you mention and after the upgrade the docker-compose issue was gone!
