### ISSUE TITLE
Fig failing randomly on remote server

### ISSUE THREAD

**Issue by naps62** [docker/compose#672]
I set up a digital ocean machine (with the docker image "Docker 1.3.1 on Ubuntu 14.04).
Right now I'm calling fig manually via SSH to test my setup

The setup is the following:

```yml
web:
  build: docker/web
  command: bundle exec puma -C config/puma.rb
  volumes:
    - .:/usr/src/app
  links:
    - db
  ports:
    - 8080:80
db:
  build: docker/db
  volumes:
    - "~/docker-deploy-demo/shared/db/:/var/lib/postgresql/data/"
```

The problem is, sometimes `fig build` fails, with the following output:

```
Traceback (most recent call last):
  File "<string>", line 3, in <module>
  File "/code/build/fig/out00-PYZ.pyz/fig.cli.main", line 31, in main
  File "/code/build/fig/out00-PYZ.pyz/fig.cli.docopt_command", line 21, in sys_dispatch
  File "/code/build/fig/out00-PYZ.pyz/fig.cli.command", line 28, in dispatch
  File "/code/build/fig/out00-PYZ.pyz/fig.cli.docopt_command", line 24, in dispatch
  File "/code/build/fig/out00-PYZ.pyz/fig.cli.command", line 56, in perform_command
  File "/code/build/fig/out00-PYZ.pyz/fig.cli.main", line 199, in build
  File "/code/build/fig/out00-PYZ.pyz/fig.project", line 166, in build
  File "/code/build/fig/out00-PYZ.pyz/fig.service", line 410, in build
TypeError: __init__() takes exactly 3 arguments (2 given)
```

If i retry the command multiple times, eventually it will work. Sometimes, cleaning my docker data (delete images & containers) seems to help as well, although I'm not sure it actually does

I tried to debug this myself a bit, but my knowledge of Python is very limited...

**Comment by dnephin** [comment]
The issue with masking the error was fixed a while ago, so if this fails again you should be a proper error message about the failure.
