### ISSUE TITLE
[Windows] docker-compose pull failed on non-english version

### ISSUE THREAD

**Issue by ebriney** [docker/compose#6861]
## Description of the issue

Docker Desktop CI has a french slave and we have a test failing when compose grabs the credentials with wincred helper (I suppose because the error message is localized).

## Context information (for bug reports)

**Output of `docker-compose version`**
```
docker-compose version 1.24.1, build 4667896b
docker-py version: 3.7.3
CPython version: 3.6.8
OpenSSL version: OpenSSL 1.1.0j  20 Nov 2018
```

**Output of `docker version`**
```
Client: Docker Engine - Community
 Version:           19.03.1
 API version:       1.40
 Go version:        go1.12.5
 Git commit:        74b1e89
 Built:             Thu Jul 25 21:18:17 2019
 OS/Arch:           darwin/amd64
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          19.03.1
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.5
  Git commit:       74b1e89
  Built:            Thu Jul 25 21:17:52 2019
  OS/Arch:          linux/amd64
  Experimental:     true
 containerd:
  Version:          v1.2.6
  GitCommit:        894b81a4b802e4eb2a91d1ce216b8817763c29fb
 runc:
  Version:          1.0.0-rc8
  GitCommit:        425e105d5a03fabd737a126ad93d62a9eeede87f
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Output of `docker-compose config`**
(Make sure to add the relevant `-f` and other flags)
```
services:
  myimage:
    build:
      context: C:\myfolder\myimage
    volumes:
    - C:\myfolder:/work:rw
  web0:
    image: dockerpinata/httpd:1.0
    ports:
    - 8080/tcp
  web1:
    image: dockerpinata/httpd:1.0
    ports:
    - 8080/tcp
version: '2.0'
```

## Steps to reproduce the issue

1. On win10 non-english machine (tested with french system)
2. Use a private image in your compose file
3. Do a docker-compose pull

### Observed result

exit -1

### Expected result

it pulls the images without error using credentials in credential manager

### Stacktrace / full error message

```
   error running [C:\Program Files\Docker\Docker\resources\bin\docker-compose.exe pull]:
    Command stdout:
    
    stderr:
    Pulling web0    ... 

    Pulling web1    ... 

    Pulling myimage ... 

    [1A[2K
Pulling myimage ... [32mdone[0m
[1B[6488] Failed to execute script docker-compose
    
    ERROR: for web1  Credentials store error: StoreError('Credentials store docker-credential-desktop exited with "error getting credentials - err: exit status 1, out: `�l�ment introuvable.`".',)
    
    ERROR: for web0  Credentials store error: StoreError('Credentials store docker-credential-desktop exited with "error getting credentials - err: exit status 1, out: `�l�ment introuvable.`".',)
    Traceback (most recent call last):
      File "site-packages\dockerpycreds\store.py", line 80, in _execute
      File "subprocess.py", line 356, in check_output
      File "subprocess.py", line 438, in run
    subprocess.CalledProcessError: Command '['C:\\Program Files\\Docker\\Docker\\resources\\bin\\docker-credential-desktop.EXE', 'get']' returned non-zero exit status 1.
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "site-packages\docker\auth.py", line 264, in _resolve_authconfig_credstore
      File "site-packages\dockerpycreds\store.py", line 35, in get
      File "site-packages\dockerpycreds\store.py", line 93, in _execute
    dockerpycreds.errors.StoreError: Credentials store docker-credential-desktop exited with "error getting credentials - err: exit status 1, out: `�l�ment introuvable.`".
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "docker-compose", line 6, in <module>
      File "compose\cli\main.py", line 71, in main
      File "compose\cli\main.py", line 127, in perform_command
      File "compose\cli\main.py", line 762, in pull
      File "compose\project.py", line 634, in pull
      File "compose\parallel.py", line 112, in parallel_execute
      File "compose\parallel.py", line 210, in producer
      File "compose\project.py", line 615, in pull_service
      File "compose\service.py", line 1187, in _do_pull
      File "site-packages\docker\api\image.py", line 381, in pull
      File "site-packages\docker\auth.py", line 48, in get_config_header
      File "site-packages\docker\auth.py", line 322, in resolve_authconfig
      File "site-packages\docker\auth.py", line 235, in resolve_authconfig
      File "site-packages\docker\auth.py", line 281, in _resolve_authconfig_credstore
    docker.errors.DockerException: Credentials store error: StoreError('Credentials store docker-credential-desktop exited with "error getting credentials - err: exit status 1, out: `�l�ment introuvable.`".',)
    
    error:
    exit status 4294967295
```

## Additional information

OS version / distribution, `docker-compose` install method, etc.

Installed with Docker Desktop community installer for Windows on 17.09 os

**Comment by danielborges93** [comment]
If you login in Docker Hub (using desktop app) resolve this issue.

**Comment by leventefarkas** [comment]
> If you login in Docker Hub (using desktop app) resolve this issue.

Thank you! It worked for me.

**Comment by nalmeida84** [comment]
It's mandatory to log in???

**Comment by leventefarkas** [comment]
@nalmeida84 Yes. But it's not payable.

**Comment by cleval** [comment]
I solved this issue by registering at https://hub.docker.com/
Choose version not payment
Thanks for the suggestion

**Comment by nalmeida84** [comment]
It's awkwards to need to be loged just for download an image.

If I test the "hello-word" image it's works but if I try to download others (postgre, tomcat, etc...) then the error happens.
