### ISSUE TITLE
docker-compose config throws traceback if interval is a string without a suitable suffix.

### ISSUE THREAD

**Issue by pmav99** [docker/compose#6902]
## Description of the issue

docker-compose config throws a traceback if interval is a string without a suitable suffix.

## Context information (for bug reports)

**Output of `docker-compose version`**
```
docker-compose version 1.24.1, build 4667896
docker-py version: 3.7.3
CPython version: 3.6.8
OpenSSL version: OpenSSL 1.1.1  11 Sep 2018
```

**Output of `docker version`**
```
Client: Docker Engine - Community
 Version:           19.03.2
 API version:       1.40
 Go version:        go1.12.8
 Git commit:        6a30dfc
 Built:             Thu Aug 29 05:29:11 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.2
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.8
  Git commit:       6a30dfc
  Built:            Thu Aug 29 05:27:45 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.6
  GitCommit:        894b81a4b802e4eb2a91d1ce216b8817763c29fb
 runc:
  Version:          1.0.0-rc8
  GitCommit:        425e105d5a03fabd737a126ad93d62a9eeede87f
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

## Steps to reproduce the issue

1. Create this `docker-compose.yml`
```
---
version: '3.7'
services:
  db:
    image: postgresql
    healthcheck:
      test: ["CMD", "/healthcheck.sh"]
      interval: "10"  # you can also try with e.g. "10a"
```

2. Run `docker-compose config`

### Observed result

You will see this traceback:

```
Traceback (most recent call last):
  File "/home/pmav99/.local/bin/docker-compose", line 10, in <module>
    sys.exit(main())
  File "/home/pmav99/.local/pipx/venvs/docker-compose/lib/python3.6/site-packages/compose/cli/main.py", line 71, in main
    command()
  File "/home/pmav99/.local/pipx/venvs/docker-compose/lib/python3.6/site-packages/compose/cli/main.py", line 121, in perform_command
    handler(command, command_options)
  File "/home/pmav99/.local/pipx/venvs/docker-compose/lib/python3.6/site-packages/compose/cli/main.py", line 367, in config
    print(serialize_config(compose_config, image_digests))
  File "/home/pmav99/.local/pipx/venvs/docker-compose/lib/python3.6/site-packages/compose/config/serialize.py", line 98, in serialize_config
    denormalize_config(config, image_digests),
  File "/home/pmav99/.local/pipx/venvs/docker-compose/lib/python3.6/site-packages/compose/config/serialize.py", line 60, in denormalize_config
    for service_dict in config.services
  File "/home/pmav99/.local/pipx/venvs/docker-compose/lib/python3.6/site-packages/compose/config/serialize.py", line 60, in <listcomp>
    for service_dict in config.services
  File "/home/pmav99/.local/pipx/venvs/docker-compose/lib/python3.6/site-packages/compose/config/serialize.py", line 147, in denormalize_service_dict
    service_dict['healthcheck']['interval']
  File "/home/pmav99/.local/pipx/venvs/docker-compose/lib/python3.6/site-packages/compose/config/serialize.py", line 116, in serialize_ns_time_value
    tmp = value / stage[0]
TypeError: unsupported operand type(s) for /: 'NoneType' and 'float'
```
### Expected result

Detecting that the healthcheck value is invalid and showing an appropriate error would be nice.

**Comment by pmav99** [comment]
This is still an issue on:
```
$ docker-compose version
docker-compose version 1.25.4, build unknown
docker-py version: 4.2.0
CPython version: 3.8.2
OpenSSL version: OpenSSL 1.1.1d  10 Sep 2019
```

**Comment by longuyen97** [comment]
Same problem here:

```
Traceback (most recent call last):
  File "/usr/bin/docker-compose", line 11, in <module>
    load_entry_point('docker-compose==1.17.1', 'console_scripts', 'docker-compose')()
  File "/usr/lib/python2.7/dist-packages/compose/cli/main.py", line 68, in main
    command()
  File "/usr/lib/python2.7/dist-packages/compose/cli/main.py", line 121, in perform_command
    handler(command, command_options)
  File "/usr/lib/python2.7/dist-packages/compose/cli/main.py", line 952, in up
    start=not no_start
  File "/usr/lib/python2.7/dist-packages/compose/project.py", line 431, in up
    svc.ensure_image_exists(do_build=do_build)
  File "/usr/lib/python2.7/dist-packages/compose/service.py", line 302, in ensure_image_exists
    self.build()
  File "/usr/lib/python2.7/dist-packages/compose/service.py", line 923, in build
    shmsize=parse_bytes(build_opts.get('shm_size')) if build_opts.get('shm_size') else None,
  File "/usr/lib/python2.7/dist-packages/docker/api/build.py", line 148, in build
    path, exclude=exclude, dockerfile=dockerfile, gzip=gzip
  File "/usr/lib/python2.7/dist-packages/docker/utils/build.py", line 14, in tar
    root=root, fileobj=fileobj, gzip=gzip
  File "/usr/lib/python2.7/dist-packages/docker/utils/utils.py", line 117, in create_archive
    t.addfile(i, None)
  File "/usr/lib/python2.7/tarfile.py", line 2050, in addfile
    buf = tarinfo.tobuf(self.format, self.encoding, self.errors)
  File "/usr/lib/python2.7/tarfile.py", line 1008, in tobuf
    return self.create_gnu_header(info)
  File "/usr/lib/python2.7/tarfile.py", line 1039, in create_gnu_header
    return buf + self._create_header(info, GNU_FORMAT)
  File "/usr/lib/python2.7/tarfile.py", line 1124, in _create_header
    itn(info.get("mtime", 0), 12, format),
  File "/usr/lib/python2.7/tarfile.py", line 221, in itn
    s = chr(n & 0377) + s
TypeError: unsupported operand type(s) for &: 'float' and 'int'
```

**Comment by EpiqSty** [comment]
This is still an issue on:

```
$ docker-compose --version
docker-compose version 1.26.0, build d4451659
$  docker-compose config
Traceback (most recent call last):
  File "bin/docker-compose", line 6, in <module>
  File "compose/cli/main.py", line 72, in main
  File "compose/cli/main.py", line 122, in perform_command
  File "compose/cli/main.py", line 354, in config
  File "compose/config/serialize.py", line 106, in serialize_config
  File "compose/config/serialize.py", line 62, in denormalize_config
  File "compose/config/serialize.py", line 62, in <listcomp>
  File "compose/config/serialize.py", line 159, in denormalize_service_dict
  File "compose/config/serialize.py", line 124, in serialize_ns_time_value
TypeError: unsupported operand type(s) for /: 'NoneType' and 'float'
[13809] Failed to execute script docker-compose
```
