### ISSUE TITLE
python application not restarting

### ISSUE THREAD

**Issue by nkostoulas** [docker/compose#6921]
## Description of the issue
Using docker-compose clustering for multiple applications, one of which is a Docker container running a python application. An exception is raised from inside the application but the container doesn't stop or compose fails to restart it.

## Context information (for bug reports)

Application run using:
```
    command: >-
      python3 -u -m app_name --param1 1 --param2 2
```

Deploy config used:
```
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
```

### Stacktrace / full error message
```
2019-09-25 07:55:00    
PID="15294" message="Exception: Node thread has stopped" identifier="federation_2"
2019-09-25 07:55:00    
PID="15294" message=" raise Exception("Node thread has stopped")" identifier="federation_2"
2019-09-25 07:55:00    
PID="15294" message=" File "/usr/local/lib/python3.7/site-packages/federation-0.1-py3.7.egg/federation/federation.py", line 87, in main" identifier="federation_2"
2019-09-25 07:55:00    
PID="15294" message=" federation.main()" identifier="federation_2"
2019-09-25 07:55:00    
PID="15294" message=" File "/usr/local/lib/python3.7/site-packages/federation-0.1-py3.7.egg/federation/__main__.py", line 3, in <module>" identifier="federation_2"
2019-09-25 07:55:00    
PID="15294" message=" exec(code, run_globals)" identifier="federation_2"
2019-09-25 07:55:00    
PID="15294" message=" File "/usr/local/lib/python3.7/runpy.py", line 85, in _run_code" identifier="federation_2"
2019-09-25 07:55:00    
PID="15294" message=" "__main__", mod_spec)" identifier="federation_2"
2019-09-25 07:55:00    
PID="15294" message=" File "/usr/local/lib/python3.7/runpy.py", line 193, in _run_module_as_main" identifier="federation_2"
2019-09-25 07:55:00    
PID="15294" message="Traceback (most recent call last):" identifier="federation_2"
2019-09-25 07:55:00    
```

**Comment by nkostoulas** [comment]
Works fine locally with `docker stack deploy`.
