### ISSUE TITLE
docker-compose-up fails to fetch remote images

### ISSUE THREAD

**Issue by davidje13** [docker/compose#6939]
## Description of the issue

If an image used by `docker-compose.yml` is not cached locally, running `docker-compose up` will fail with the errors shown below (appears to be related to credentials).

## Context information (for bug reports)

**Output of `docker-compose version`**
```
docker-compose version 1.24.1, build 4667896b
docker-py version: 3.7.3
CPython version: 3.6.8
OpenSSL version: OpenSSL 1.1.0j  20 Nov 2018
```

**Output of `docker version`**
```
Client: Docker Engine - Community
 Version:           19.03.2
 API version:       1.40
 Go version:        go1.12.8
 Git commit:        6a30dfc
 Built:             Thu Aug 29 05:26:49 2019
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.2
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.8
  Git commit:       6a30dfc
  Built:            Thu Aug 29 05:32:21 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.6
  GitCommit:        894b81a4b802e4eb2a91d1ce216b8817763c29fb
 runc:
  Version:          1.0.0-rc8
  GitCommit:        425e105d5a03fabd737a126ad93d62a9eeede87f
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Output of `docker-compose config`**
```
services:
  anything:
    image: nginx
version: '2.0'
```

(nginx is used as an example here but any docker hub image will do)

## Steps to reproduce the issue

1. Ensure you do not have the configured image locally
2. Run `docker-compose up`

### Observed result

An error (see below)

### Expected result

Image is downloaded

### Stacktrace / full error message

```
Pulling anything (nginx:)...
Traceback (most recent call last):
  File "site-packages/dockerpycreds/store.py", line 80, in _execute
  File "subprocess.py", line 356, in check_output
  File "subprocess.py", line 438, in run
subprocess.CalledProcessError: Command '['/usr/local/bin/docker-credential-desktop', 'get']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "site-packages/docker/auth.py", line 264, in _resolve_authconfig_credstore
  File "site-packages/dockerpycreds/store.py", line 35, in get
  File "site-packages/dockerpycreds/store.py", line 93, in _execute
dockerpycreds.errors.StoreError: Credentials store docker-credential-desktop exited with "No stored credential for https://index.docker.io/v1/".

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "docker-compose", line 6, in <module>
  File "compose/cli/main.py", line 71, in main
  File "compose/cli/main.py", line 127, in perform_command
  File "compose/cli/main.py", line 1085, in up
  File "compose/cli/main.py", line 1081, in up
  File "compose/project.py", line 527, in up
  File "compose/service.py", line 354, in ensure_image_exists
  File "compose/service.py", line 1222, in pull
  File "compose/progress_stream.py", line 102, in get_digest_from_pull
  File "compose/service.py", line 1187, in _do_pull
  File "site-packages/docker/api/image.py", line 381, in pull
  File "site-packages/docker/auth.py", line 48, in get_config_header
  File "site-packages/docker/auth.py", line 322, in resolve_authconfig
  File "site-packages/docker/auth.py", line 235, in resolve_authconfig
  File "site-packages/docker/auth.py", line 281, in _resolve_authconfig_credstore
docker.errors.DockerException: Credentials store error: StoreError('Credentials store docker-credential-desktop exited with "No stored credential for https://index.docker.io/v1/".',)
[3629] Failed to execute script docker-compose
```

## Additional information

I have never signed in to the docker daemon (I do not have an account).

Pulling the image first (i.e. `docker pull nginx`) makes the command succeed.

OS version: macOS 10.14.6

**Comment by ndeloof** [comment]
I tried to reproduce on a fresh new docker installation (Linux) and image is pulled as expected. This issue seem to be specific to Docker4Desktop integration.

**Comment by davidje13** [comment]
From the errors produced, it looks like something is assuming everybody will have a docker login, and doesn't support pulling images without a login (even public images). But the stack trace does suggest this is in docker compose itself, rather than the external daemon.

I imagine OS X and Linux have different APIs for their keychains, so that's where I'd suspect the difference lies.

**Comment by claritee** [comment]
Running `docker pull nginx` pulled the latest image of nginx, however the issue was resolved for me, by logging in unfortunately. 

I had to login with `docker login` and followed the prompts.

**Comment by davidje13** [comment]
@claritee are you on mac or linux? (I'd like to know if this is unique to mac as suggested before)

**Comment by marcelormourao** [comment]
I had the same problem right now. I am using mac.

```
Pulling backend (marcelormourao/backend:)...
Traceback (most recent call last):
  File "site-packages/dockerpycreds/store.py", line 80, in _execute
  File "subprocess.py", line 356, in check_output
  File "subprocess.py", line 438, in run
subprocess.CalledProcessError: Command '['/usr/local/bin/docker-credential-desktop', 'get']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "site-packages/docker/auth.py", line 264, in _resolve_authconfig_credstore
  File "site-packages/dockerpycreds/store.py", line 35, in get
  File "site-packages/dockerpycreds/store.py", line 93, in _execute
dockerpycreds.errors.StoreError: Credentials store docker-credential-desktop exited with "No stored credential for https://index.docker.io/v1/".

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "docker-compose", line 6, in <module>
  File "compose/cli/main.py", line 71, in main
  File "compose/cli/main.py", line 127, in perform_command
  File "compose/cli/main.py", line 1085, in up
  File "compose/cli/main.py", line 1081, in up
  File "compose/project.py", line 527, in up
  File "compose/service.py", line 354, in ensure_image_exists
  File "compose/service.py", line 1222, in pull
  File "compose/progress_stream.py", line 102, in get_digest_from_pull
  File "compose/service.py", line 1187, in _do_pull
  File "site-packages/docker/api/image.py", line 381, in pull
  File "site-packages/docker/auth.py", line 48, in get_config_header
  File "site-packages/docker/auth.py", line 322, in resolve_authconfig
  File "site-packages/docker/auth.py", line 235, in resolve_authconfig
  File "site-packages/docker/auth.py", line 281, in _resolve_authconfig_credstore
docker.errors.DockerException: Credentials store error: StoreError('Credentials store docker-credential-desktop exited with "No stored credential for https://index.docker.io/v1/".',)
[5281] Failed to execute script docker-compose
```

**Comment by davidje13** [comment]
I did some further digging and reported this to the docker-py repository here: https://github.com/docker/docker-py/issues/2482

**Comment by hzb** [comment]
@davidje13 Which system do you use Docker on? I met this issue on macOS, and I logged in Docker Desktop on macOS, and then the issue is fixed.

**Comment by davidje13** [comment]
@hzb yes this appears to be limited to macOS. I have tracked it down to a bug in dockerpy-creds, which is throwing the wrong exception when credentials are not found on mac (https://github.com/shin-/dockerpy-creds/issues/13), causing docker-py to mishandle the exception (https://github.com/docker/docker-py/issues/2482), which results in this bug.

btw, logging in may work around this issue, but it should not be required, and is not required on linux.

**Comment by hzb** [comment]
@davidje13 Yes, I am the same as you think, whey does it be required on macOS, but not on Linux.

BTW, If these images are not from the docker hub (index.docker.io), but from other places, such as docker.package.github.com. This problem still occurs, even if you logged in. All you need to do is check the option in Docker Desktop, as shown in red in the following picture.

![issue](https://user-images.githubusercontent.com/535675/71517921-3633a000-28eb-11ea-8612-8de96a113a0e.png)

**Comment by davidje13** [comment]
Since this issue has been stale-closed I'll add a link to the (very nested) issue which was eventually raised:

https://github.com/docker/docker-credential-helpers/issues/177

**Comment by netmute** [comment]
In case anybody else runs into the problem, and discovers this stale issue. A workaround for the problem is here:
https://github.com/docker/for-mac/issues/3805#issuecomment-518619953
