### ISSUE TITLE
Encoding error running `docker-compose down`

### ISSUE THREAD

**Issue by ruliuyunxi** [docker/compose#6961]
```
[root@ciip-k8s-00018-613l7 harbor]# docker-compose down
Traceback (most recent call last):
  File "bin/docker-compose", line 6, in <module>
  File "compose/cli/main.py", line 71, in main
  File "compose/cli/main.py", line 124, in perform_command
  File "compose/cli/command.py", line 42, in project_from_options
  File "compose/cli/command.py", line 123, in get_project
  File "compose/cli/command.py", line 94, in get_client
  File "compose/cli/docker_client.py", line 127, in docker_client
  File "site-packages/docker/api/client.py", line 118, in __init__
  File "site-packages/docker/auth.py", line 258, in load_config
  File "site-packages/docker/auth.py", line 215, in parse_auth
  File "site-packages/docker/auth.py", line 159, in decode_auth
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xee in position 0: invalid continuation byte
[16263] Failed to execute script docker-compose

```

**Comment by ndeloof** [comment]
Hi. Can you please write issues in english ?
According to google translate:
"Need to stop the harbor service, in the harbor directory, execute doceker-compose down, failed. Error is as follows"
(Please correct if google is wrong)

Error seems to demonstrate an encoding issue with your ~/.docker/config.json configuration file. Can you please check it's correctly encoded as UTF-8 (you can use some online service for this purpose, like https://onlineutf8tools.com/validate-utf8)
