### ISSUE TITLE
When piping compose config cannot run `sh`

### ISSUE THREAD

**Issue by baflo** [docker/compose#6981]
## Description of the issue

I have a simple config file, that I pipe to `docker-compose` through `stdin`. In my case it's JSON, as I dynamically create it using a nodejs script:

```json
{
  "version": "3.3",
  "services": {
    "app": {
      "image": "node:10",
      "tty": true,
      "stdin_open": true
    }
  }
}
```

This works flawlessly for `run` or `up`, as long as I don't try to use a shell. The following commands silent quit:

```sh
cat docker-compose.json | docker-compose -f- run --rm app sh
cat docker-compose.json | docker-compose -f- run --rm --entrypoint=/bin/sh app
```

## Context information (for bug reports)

**Output of `docker-compose version`**
```
docker-compose version 1.24.1, build 4667896b
docker-py version: 3.7.3
CPython version: 3.6.8
OpenSSL version: OpenSSL 1.1.0j  20 Nov 2018
```

**Output of `docker version`**
```
Client: Docker Engine - Community
 Version:           19.03.2
 API version:       1.40
 Go version:        go1.12.8
 Git commit:        6a30dfca03
 Built:             Thu Aug 29 05:29:49 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.2
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.8
  Git commit:       6a30dfc
  Built:            Thu Aug 29 05:32:21 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.6
  GitCommit:        894b81a4b802e4eb2a91d1ce216b8817763c29fb
 runc:
  Version:          1.0.0-rc8
  GitCommit:        425e105d5a03fabd737a126ad93d62a9eeede87f
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Output of `docker-compose config`**
(Make sure to add the relevant `-f` and other flags)

cat docker-compose.json | docker-compose -f- config                              
```yaml
services:
  app:
    image: node:10
    stdin_open: true
    tty: true
version: '3.3'
```

docker-compose -f docker-compose.json config
```yaml
services:
  app:
    image: node:10
    stdin_open: true
    tty: true
version: '3.3'
```

## Steps to reproduce the issue

1.
2.
3.

### Stacktrace / full error message

```
(paste here)
```

## Additional information

OS version / distribution, `docker-compose` install method, etc.

**Comment by atomi** [comment]
I think all of piping is now broken with one of the newer commits. 

I used to be able to do this `echo "$composefile" | docker-compose -f- up -d`   
But now I get Traceback

```
Traceback (most recent call last):
  File "/home/atomi/.local/bin/docker-compose", line 8, in <module>
    sys.exit(main())
  File "/home/atomi/.local/lib/python3.6/site-packages/compose/cli/main.py", line 71, in main
    command()
  File "/home/atomi/.local/lib/python3.6/site-packages/compose/cli/main.py", line 124, in perform_command
    project = project_from_options('.', options)
  File "/home/atomi/.local/lib/python3.6/site-packages/compose/cli/command.py", line 64, in project_from_options
    environment_file=environment_file
  File "/home/atomi/.local/lib/python3.6/site-packages/compose/cli/command.py", line 156, in get_project
    execution_context_labels(config_details, environment_file),
  File "/home/atomi/.local/lib/python3.6/site-packages/compose/cli/command.py", line 163, in execution_context_labels
    '{0}={1}'.format(LABEL_CONFIG_FILES, config_files_label(config_details)),
  File "/home/atomi/.local/lib/python3.6/site-packages/compose/cli/command.py", line 173, in config_files_label
    map(str, (os.path.normpath(c.filename) for c in config_details.config_files)))
  File "/home/atomi/.local/lib/python3.6/site-packages/compose/cli/command.py", line 173, in <genexpr>
    map(str, (os.path.normpath(c.filename) for c in config_details.config_files)))
  File "/usr/lib/python3.6/posixpath.py", line 340, in normpath
    path = os.fspath(path)
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

**Comment by atomi** [comment]
I hope I'm not hijacking this issue as I think they are likely related. 


I've tested this command `echo "$composefile" | docker-compose -f- up -d` through the various tags.


tag | status
--- | --- 
bump-1.24.0 | works
bump-1.24.1 | works
bump-1.25-rc1 | works
bump-1.25-rc2 | works
bump-1.25-rc3 | fails
bump-1.25-rc4 | fails

**Comment by cjunge-work** [comment]
@ulyssessouza This is still occurring on Linux with the latest 1.25.1-rc1 release. I downgraded to 1.24.1 and the problem goes away.

**Comment by webark** [comment]
@baflo did you ever get this working? I was playing around with this idea and was not able to.

**Comment by baflo** [comment]
I think when the fix came in #7073 I tried it and it worked. But I already had another setup. I added the following script to my `docker-compose.js` and run it without piping:

```javascript
/**
 * The main "loop". If this script is called as main module, but without
 * any arguments, prints the above config. If called with at least one
 * parameter, writes the configuration to a temporary file and calls
 * `docker-compose` with the passed arguments.
 */
if (require.main === module) {
  if (process.argv.length <= 2) {
    console.log(config);
    process.exit(0);
  }

  // Extract arguments for docker compose and make sure no file options remain
  const composeArgs = removeComposeFileOption(process.argv.slice(2));

  // Create configuration file
  const tempfile = path.join(__dirname, "temp", "base-apps", "docker-compose.json");
  fs.mkdirSync(path.dirname(tempfile), { recursive: true });
  fs.writeFileSync(tempfile, config, { encoding: "utf8" });

  // Spawn `docker-compose`
  const dockerCompose = /win/.test(os.platform()) ? "docker-compose.exe" : "docker-compose";
  child_process.spawnSync(dockerCompose, ["-f", tempfile, ...composeArgs], { stdio: "inherit" });
}

/**
 * @param {string[]} args Docker compose arguments list
 */
function removeComposeFileOption(args) {
  const isFileOptionRegex = /^(-f|--file)/;
  return args.filter((element, index, target) => !isFileOptionRegex.test(element) && (index === 0 || index - 1 !== target.findIndex(el => isFileOptionRegex.test(el))))
}

```

**Comment by webark** [comment]
hmm.. yea. generating the file the removing it.. hmm.

but yea, I've been trying
```
ytt -f composes/ | docker-compose -f -  run --rm web bash
```
and it doesn't work for me.

**Comment by alanjcastonguay** [comment]
Got bit by this. Somewhat annoyingly: the last version in Debian bullseye is 1.25.0. https://packages.debian.org/bullseye/all/docker-compose/filelist

```
$ docker-compose version
docker-compose version 1.25.0, build unknown
docker-py version: 4.1.0
CPython version: 3.9.2
OpenSSL version: OpenSSL 1.1.1k  25 Mar 2021
```

```
$ apt show docker-compose
Package: docker-compose
Version: 1.25.0-1
Status: install ok installed
Priority: optional
Section: admin
Maintainer: Docker Compose Team <team+docker-compose@tracker.debian.org>
Installed-Size: 692 kB
Depends: python3-cached-property (>= 1.2.0), python3-docker (>= 4.0.0), python3-dockerpty (>= 0.4.1), python3-docopt (>= 0.6.1), python3-jsonschema, python3-requests (>= 2.20.0), python3-six (<< 2), python3-six (>= 1.3.0), python3-texttable (>= 0.9.0), python3-websocket (>= 0.32.0), python3-yaml (>= 3.10), python3:any (>= 3.6~), python3-distutils
Recommends: docker.io (>= 1.9.0)
Homepage: https://docs.docker.com/compose/
Download-Size: unknown
APT-Manual-Installed: yes
APT-Sources: /var/lib/dpkg/status
Description: Punctual, lightweight development environments using Docker
 docker-compose is a service management software built on top of docker. Define
 your services and their relationships in a simple YAML file, and let compose
 handle the rest.
```
