### ISSUE TITLE
Docker compose not respecting docker-machine's settings in WSL (Ubuntu)

### ISSUE THREAD

**Issue by rajat1saxena** [docker/compose#6985]
## Description of the issue
I wrote this little script to automate deployments on local and prod environments and I am using Docker Toolbox for Windows and running the commands from inside of WSL (Ubuntu) which is running on Windows 10 Home. 

```
# Usage: ./up.sh docker-machine-name your-env-file docker-compose-build-option

if [ -z "$1" ]; then
    echo "Error: specify the Docker machine's name"
    exit 1
fi

if [ -z "$2" ]; then
    echo "Error: specify an environment file"
    exit 1
fi

FILE=$2
if test -f "$FILE"; then
    cp $FILE .env
    eval $("docker-machine.exe" env $1 --shell bash)
    echo $DOCKER_HOST
    docker-compose.exe $3 build
    docker-compose.exe up -d
else
    echo "Error: $FILE does not exist"
    exit 1
fi
```

But it always deploys to the local environment i.e. the local default docker machine hosted at `192.168.99.101`. It can also be noticed in docker-compose build logs.

## Context information (for bug reports)

**Output of `docker-compose version`**
```
docker-compose version 1.24.1, build 4667896b
```

**Output of `docker version`**
```
Docker version 19.03.1, build 74b1e89e8a
```

### Observed result
`docker-compose`  builds and deploys on local system i.e. `192.168.99.101`

### Expected result
`docker-compose` should build and deploy on host specified by DOCKER_HOST environment variable.

### Stacktrace / full error message

```
urllib3.connectionpool._make_request: https://192.168.99.101:2376 "GET /v1.25/networks/onlinecoursemaker_default HTTP/1.
1" 404 58
```

## Additional information

OS version: WSL (Ubuntu) running inside Windows 10 Home
Related SO post: [link](https://stackoverflow.com/questions/58568338/docker-compose-not-respecting-docker-machines-settings)

**Comment by ndeloof** [comment]
I was not able to reproduce your issue:

```
C:\Users\nicolas>set DOCKER_HOST=tcp://8.8.8.8
C:\Users\nicolas>docker version
Client: Docker Engine - Community
 Version:           19.03.4
 API version:       1.40
 Go version:        go1.12.10
 Git commit:        9013bf5
 Built:             Thu Oct 17 23:44:48 2019
 OS/Arch:           windows/amd64
 Experimental:      false
error during connect: Get http://8.8.8.8:2375/v1.40/version: dial tcp 8.8.8.8:2375: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
C:\Users\nicolas>docker-compose up
Traceback (most recent call last):
  File "docker-compose", line 6, in <module>
  File "compose\cli\main.py", line 71, in main
  File "compose\cli\main.py", line 124, in perform_command
  File "compose\cli\command.py", line 42, in project_from_options
  File "compose\cli\command.py", line 123, in get_project
  File "compose\cli\command.py", line 94, in get_client
  File "compose\cli\docker_client.py", line 127, in docker_client
  File "site-packages\docker\api\client.py", line 133, in __init__
  File "site-packages\docker\utils\utils.py", line 288, in parse_host
docker.errors.DockerException: Invalid bind address format: port is required: tcp://8.8.8.8
[3424] Failed to execute script docker-compose
``

Can you please try to do the same ?
