### ISSUE TITLE
OS X Catalina Link from /etc/synthetic.conf is resolved and won't start docker-compose container

### ISSUE THREAD

**Issue by ystreibel** [docker/compose#7084]
Hi,

My Docker Desktop version:

<img width="763" alt="Capture d’écran 2019-12-06 à 15 51 16" src="https://user-images.githubusercontent.com/3459111/70331700-44d4ed00-1840-11ea-89f1-9c9b22b8386a.png">

The issues:

```
Creating dockercompose_mongo_1 ...

ERROR: for dockercompose_mongo_1  a bytes-like object is required, not 'str'

ERROR: for mongo  a bytes-like object is required, not 'str'
Traceback (most recent call last):
  File "site-packages/docker/api/client.py", line 261, in _raise_for_status
  File "site-packages/requests/models.py", line 940, in raise_for_status
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: http+docker://localhost/v1.21/containers/441bd3367a8488fd3559b73b26d7d2989b86cc07c029e00eb8d6de167397c1d1/start

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "compose/service.py", line 625, in start_container
  File "compose/container.py", line 241, in start
  File "site-packages/docker/utils/decorators.py", line 19, in wrapped
  File "site-packages/docker/api/container.py", line 1095, in start
  File "site-packages/docker/api/client.py", line 263, in _raise_for_status
  File "site-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
docker.errors.APIError: 500 Server Error: Internal Server Error **("b'Mounts denied: EOF'")**

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "docker-compose", line 6, in <module>
  File "compose/cli/main.py", line 71, in main
  File "compose/cli/main.py", line 127, in perform_command
  File "compose/cli/main.py", line 1106, in up
  File "compose/cli/main.py", line 1102, in up
  File "compose/project.py", line 570, in up
  File "compose/parallel.py", line 112, in parallel_execute
  File "compose/parallel.py", line 210, in producer
  File "compose/project.py", line 556, in do
  File "compose/service.py", line 546, in execute_convergence_plan
  File "compose/service.py", line 467, in _execute_convergence_create
  File "compose/parallel.py", line 112, in parallel_execute
  File "compose/parallel.py", line 210, in producer
  File "compose/service.py", line 465, in <lambda>
  File "compose/service.py", line 457, in create_and_start
  File "compose/service.py", line 627, in start_container
TypeError: a bytes-like object is required, not 'str'
[5845] Failed to execute script docker-compose
```
In `Preferences > Resources > File Sharing` when I add my `/dockervolume` directory, docker desktop add, instead of, the full path of the link directory `/Users/<user>/dockervolume`.

the linked directory is mount with OS X by `/etc/synthetic.conf` file.

I found a workaround by editing `/Users/<user>/Library/Group\ Containers/group.com.docker/settings.json` and change in filesharingDirectories array the path of `/dockervolume`directory:

```
{
  "filesharingDirectories" : [
    "\/Users",
    "\/Volumes",
    "\/private",
    "\/tmp",
    "\/dockervolume"
  ],
  ...
}
```

**Comment by ndeloof** [comment]
Seems to me this is a Docker Desktop issue, unrelated to docker-compose.
Would you mind testing a pure container command to reproduce this issue (something like `docker run -v /dockervolume:/dockervolume alpine ls /dockervolume` should report bind error or missing folder) and report this on https://github.com/docker/for-mac with ?
