### ISSUE TITLE
Fig installation fails on Mac OS X

### ISSUE THREAD

**Issue by shedd** [docker/compose#71]
I'm trying to get fig running on Mac OS X (Mountain Lion).  My versions:

```
Python 2.7.2
pip 1.5.2 from /Library/Python/2.7/site-packages/pip-1.5.2-py2.7.egg (python 2.7)
Vagrant 1.4.3
VirtualBox 4.3.7
```

When I try to do anything with `fig`, I get the following error:

```
$ fig
Traceback (most recent call last):
  File "/usr/local/bin/fig", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 2603, in <module>
    working_set.require(__requires__)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 666, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 565, in resolve
    raise DistributionNotFound(req)  # XXX put more info here
pkg_resources.DistributionNotFound: six>=1.3.0
```

I tried making sure that `six` is installed and it appears to be:

```
$ sudo pip install -U six
Requirement already up-to-date: six in /Library/Python/2.7/site-packages
```

I tried installing `fig` again:

```
$ sudo pip install -U fig
Requirement already up-to-date: fig in /Library/Python/2.7/site-packages
Requirement already up-to-date: docopt==0.6.1 in /Library/Python/2.7/site-packages (from fig)
Requirement already up-to-date: PyYAML==3.10 in /Library/Python/2.7/site-packages (from fig)
Requirement already up-to-date: requests==2.2.1 in /Library/Python/2.7/site-packages (from fig)
Requirement already up-to-date: six>=1.3.0 in /Library/Python/2.7/site-packages (from fig)
Requirement already up-to-date: texttable==0.8.1 in /Library/Python/2.7/site-packages (from fig)
Requirement already up-to-date: websocket-client==0.11.0 in /Library/Python/2.7/site-packages (from fig)
Cleaning up...
```

`six` appears to be at the right version - in `/Library/Python/2.7/site-packages` I'm seeing `six-1.5.2.dist-info`

Not sure where to go from here?  Any ideas?

**Comment by xixuebin** [comment]
fix it with 
```
sudo pip install --upgrade distribute  
```

**Comment by mprototype** [comment]
sudo pip install --upgrade distribute  works for me

**Comment by liusongsen** [comment]
遇到这个问题，我就直接通过二进制包方式安装了：

发布的二进制包可以在 https://github.com/docker/compose/releases 找到。

下载后直接放到执行路径即可。

例如，在常见的 Linux 平台上。

$ sudo curl -L https://github.com/docker/compose/releases/download/1.2.0/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose
$ sudo chmod a+x /usr/local/bin/docker-compose
