### ISSUE TITLE
UnicodeDecodeError - Windows 10

### ISSUE THREAD

**Issue by michalpietryka** [docker/compose#7204]
## Description of the issue
I can not use docker-compose. No matter what i put in my docker-compose.yaml file, I end with this error. 

## Context information (for bug reports)

**Output of `docker-compose version`**
```
docker-compose version 1.25.2, build 698e2846
docker-py version: 4.1.0
CPython version: 2.7.16
OpenSSL version: OpenSSL 1.0.2q  20 Nov 2018
```

**Output of `docker version`**
```
Client: Docker Engine - Community
 Version:           19.03.5
 API version:       1.40
 Go version:        go1.12.12
 Git commit:        633a0ea
 Built:             Wed Nov 13 07:22:37 2019
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.5
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.12
  Git commit:       633a0ea
  Built:            Wed Nov 13 07:29:19 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Output of `docker-compose config`**
(Make sure to add the relevant `-f` and other flags)
```
services:
  db:
    image: mysql:5.7
version: '3.0'
```

## Steps to reproduce the issue

1. run docker-compose up

### Observed result
UnicodeDecodeError: 'ascii' codec can't decode byte 0xb3 in position 12: ordinal not in range(128)

### Expected result
docker-compose runs normally

### Stacktrace / full error message

```
Pulling db (mysql:5.7)...
Traceback (most recent call last):
  File "docker-compose", line 6, in <module>
  File "compose\cli\main.py", line 72, in main
  File "compose\cli\main.py", line 128, in perform_command
  File "compose\cli\main.py", line 1077, in up
  File "compose\cli\main.py", line 1073, in up
  File "compose\project.py", line 548, in up
  File "compose\service.py", line 361, in ensure_image_exists
  File "compose\service.py", line 1250, in pull
  File "compose\progress_stream.py", line 102, in get_digest_from_pull
  File "compose\service.py", line 1215, in _do_pull
  File "site-packages\docker\api\image.py", line 396, in pull
  File "site-packages\docker\auth.py", line 48, in get_config_header
  File "site-packages\docker\auth.py", line 324, in resolve_authconfig
  File "site-packages\docker\auth.py", line 235, in resolve_authconfig
  File "site-packages\docker\auth.py", line 262, in _resolve_authconfig_credstore
  File "site-packages\docker\auth.py", line 287, in _get_store_instance
  File "site-packages\docker\credentials\store.py", line 20, in __init__
  File "site-packages\docker\credentials\utils.py", line 24, in find_executable
  File "ntpath.py", line 85, in join
UnicodeDecodeError: 'ascii' codec can't decode byte 0xb3 in position 12: ordinal not in range(128)    [15120] Failed to execute script docker-compose
```

## Additional information

OS version: Windows 10 Pro

**Comment by michalpietryka** [comment]
Fixed changing Windows user account name.
