### ISSUE TITLE
compose doesn't set a default port when talking to dockerd

### ISSUE THREAD

**Issue by sixcorners** [docker/compose#7205]
## Description of the issue
ssh -f cac -L2375:/var/run/docker.sock sleep 3
DOCKER_HOST=localhost docker info
works

ssh -f cac -L2375:/var/run/docker.sock sleep 3
DOCKER_HOST=localhost docker-compose logs
docker.errors.DockerException: Invalid bind address format: port is required: localhost
## Context information (for bug reports)

**Output of `docker-compose version`**
```
docker-compose version 1.25.3, build unknown
docker-py version: 4.1.0
CPython version: 3.7.5
OpenSSL version: OpenSSL 1.1.1c  28 May 2019
```

**Output of `docker version`**
```
Client: Docker Engine - Community
 Version:           19.03.5
 API version:       1.40
 Go version:        go1.12.12
 Git commit:        633a0ea838
 Built:             Wed Nov 13 07:29:52 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.5
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.12
  Git commit:       633a0ea838
  Built:            Wed Nov 13 07:28:22 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

## Steps to reproduce the issue
ssh -f cac -L2375:/var/run/docker.sock sleep 3
DOCKER_HOST=localhost docker-compose logs

### Observed result
docker.errors.DockerException: Invalid bind address format: port is required: localhost

### Expected result
no error

### Stacktrace / full error message

```
Traceback (most recent call last):
  File "/home/sixcorners/.local/bin/docker-compose", line 10, in <module>
    sys.exit(main())
  File "/home/sixcorners/.local/lib/python3.7/site-packages/compose/cli/main.py", line 72, in main
    command()
  File "/home/sixcorners/.local/lib/python3.7/site-packages/compose/cli/main.py", line 125, in perform_command
    project = project_from_options('.', options)
  File "/home/sixcorners/.local/lib/python3.7/site-packages/compose/cli/command.py", line 65, in project_from_options
    environment_file=environment_file
  File "/home/sixcorners/.local/lib/python3.7/site-packages/compose/cli/command.py", line 149, in get_project
    host=host, environment=environment
  File "/home/sixcorners/.local/lib/python3.7/site-packages/compose/cli/command.py", line 120, in get_client
    environment=environment, tls_version=get_tls_version(environment)
  File "/home/sixcorners/.local/lib/python3.7/site-packages/compose/cli/docker_client.py", line 127, in docker_client
    client = APIClient(**kwargs)
  File "/home/sixcorners/.local/lib/python3.7/site-packages/docker/api/client.py", line 133, in __init__
    base_url, IS_WINDOWS_PLATFORM, tls=bool(tls)
  File "/home/sixcorners/.local/lib/python3.7/site-packages/docker/utils/utils.py", line 288, in parse_host
    ' {}'.format(addr)
docker.errors.DockerException: Invalid bind address format: port is required: localhost
```

## Additional information
ubuntu
I think I used apt. If not I used pip3.

**Comment by ndeloof** [comment]
This is actually a docker-py issue

**Comment by ashtneoi** [comment]
This is still happening on 1.28.3. Can we reopen it?
