### ISSUE TITLE
When building containers via docker-compose and DOCKER_HOST env var is set to "ssh://user@host", it fails with a "x.x.x.x not found in known_hosts" paramiko error

### ISSUE THREAD

**Issue by terroirman** [docker/compose#7267]
##  Description of the issue
When acting on remote containers via docker-compose "up/down" (ex.: docker-compose.exe down)
AND: DOCKER_HOST env var is set to "ssh://user@a.b.c.d"
Then: it fails with a "a.b.c.d not found in known_hosts" paramiko error.

I double checked that the host is in the the c:\Users\user\.ssh\know_hosts
I can successful log in the remote server using the ssh keys.

The problem doesn't appear : 
- If no "up" or "down" command are used (ex.: docker-compose.exe config --services would work)
OR
- If DOCKER_HOST is set to "tcp://127.0.0.1:23750" (and a ssh tunnel is up between workstation and server via :  ssh -NL localhost:23750:/var/run/docker.sock user@a.b.c.d)

## Context information (for bug reports)

**Output of `docker-compose version`**
```
docker-compose version 1.25.4, build unknown
docker-py version: 4.1.0
CPython version: 3.7.2
OpenSSL version: OpenSSL 1.1.0j  20 Nov 2018
```

**Output of `docker version` (server part is remote)**
```
Client:
 Version:           19.03.3
 API version:       1.39 (downgraded from 1.40)
 Go version:        go1.12.10
 Git commit:        2355349d-
 Built:             10/14/2019 16:41:26
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.1
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.6
  Git commit:       4c52b90
  Built:            Wed Jan  9 19:06:30 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

**Output of `docker-compose config`**
(Make sure to add the relevant `-f` and other flags)
```
services:
  database:
    build:
      context: C:\
      dockerfile: ./database/Dockerfile
  web_server:
    build:
      context: C:\
      dockerfile: web_server/Dockerfile
    ports:
    - published: 80
      target: 80
    volumes:
    - app:/app:rw
    working_dir: /app
version: '3.3'
volumes:
  app: {}
```

## Steps to reproduce the issue

1. setup basic docker-compose.yml file
2. set env var DOCKER_HOST=ssh://user@host
3. execute docker-compose.exe down

### Observed result
fails with paramiko error "paramiko.ssh_exception.SSHException: Server 'a.b.c.d' not found in known_hosts"

### Expected result
The containers are brought up (or down) without any paramiko error.

### Stacktrace / full error message

**Bug reproduced with DOCKER_HOST="ssh://user@a.b.c.d"**
```
PS C:\TEMP> $Env:DOCKER_HOST="ssh://user@a.b.c.d"
PS C:\TEMP> docker-compose.exe --verbose --log-level DEBUG down
compose.config.config.find: Using configuration files: .\docker-compose.yml
docker.utils.config.find_config_file: Trying paths: ['C:\\Users\\user\\.docker\\config.json', 'C:\\Users\\user\\.dockercfg']
docker.utils.config.find_config_file: No config file found
docker.utils.config.find_config_file: Trying paths: ['C:\\Users\\user\\.docker\\config.json', 'C:\\Users\\user\\.dockercfg']
docker.utils.config.find_config_file: No config file found
paramiko.transport._log: starting thread (client mode): 0x9beebda0
paramiko.transport._log: Local version/idstring: SSH-2.0-paramiko_2.7.1
paramiko.transport._log: Remote version/idstring: SSH-2.0-OpenSSH_7.4
paramiko.transport._log: Connected (version 2.0, client OpenSSH_7.4)
paramiko.transport._log: kex algos:['curve25519-sha256', 'curve25519-sha256@libssh.org', 'ecdh-sha2-nistp256', 'ecdh-sha2-nistp384', 'ecdh-sha2-nistp521', 'diffie-hellman-group-exchange-sha256', 'diffie-hellman-group16-sha512', 'diffie-hellman-group18-sha512', 'diffie-hellman-group-exchange-sha1', 'diffie-hellman-group14-sha256', 'diffie-hellman-group14-sha1', 'diffie-hellman-group1-sha1'] server key:['ssh-rsa', 'rsa-sha2-512', 'rsa-sha2-256', 'ecdsa-sha2-nistp256', 'ssh-ed25519'] client encrypt:['chacha20-poly1305@openssh.com', 'aes128-ctr', 'aes192-ctr', 'aes256-ctr', 'aes128-gcm@openssh.com', 'aes256-gcm@openssh.com', 'aes128-cbc', 'aes192-cbc', 'aes256-cbc', 'blowfish-cbc', 'cast128-cbc', '3des-cbc'] server encrypt:['chacha20-poly1305@openssh.com', 'aes128-ctr', 'aes192-ctr', 'aes256-ctr', 'aes128-gcm@openssh.com', 'aes256-gcm@openssh.com', 'aes128-cbc', 'aes192-cbc', 'aes256-cbc', 'blowfish-cbc', 'cast128-cbc', '3des-cbc'] client mac:['umac-64-etm@openssh.com', 'umac-128-etm@openssh.com', 'hmac-sha2-256-etm@openssh.com', 'hmac-sha2-512-etm@openssh.com', 'hmac-sha1-etm@openssh.com', 'umac-64@openssh.com', 'umac-128@openssh.com', 'hmac-sha2-256', 'hmac-sha2-512', 'hmac-sha1'] server mac:['umac-64-etm@openssh.com', 'umac-128-etm@openssh.com', 'hmac-sha2-256-etm@openssh.com', 'hmac-sha2-512-etm@openssh.com', 'hmac-sha1-etm@openssh.com', 'umac-64@openssh.com', 'umac-128@openssh.com', 'hmac-sha2-256', 'hmac-sha2-512', 'hmac-sha1'] client compress:['none', 'zlib@openssh.com'] server compress:['none', 'zlib@openssh.com'] client lang:[''] server lang:[''] kex follows?False
paramiko.transport._log: Kex agreed: curve25519-sha256@libssh.org
paramiko.transport._log: HostKey agreed: ssh-ed25519
paramiko.transport._log: Cipher agreed: aes128-ctr
paramiko.transport._log: MAC agreed: hmac-sha2-256
paramiko.transport._log: Compression agreed: none
paramiko.transport._log: kex engine KexCurve25519 specified hash_algo <built-in function openssl_sha256>
paramiko.transport._log: Switch to new keys ...
paramiko.transport._log: Rejecting ssh-ed25519 host key for a.b.c.d: b'3df952ba3b2d0f4dd65b388fe8c6f942'
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python37\Scripts\docker-compose-script.py", line 11, in <module>
    load_entry_point('docker-compose', 'console_scripts', 'docker-compose')()
  File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\site-packages\compose\cli\main.py", line 72, in main
    command()
  File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\site-packages\compose\cli\main.py", line 125, in perform_command
    project = project_from_options('.', options)
  File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\site-packages\compose\cli\command.py", line 65, in project_from_options
    environment_file=environment_file
  File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\site-packages\compose\cli\command.py", line 149, in get_project
    host=host, environment=environment
  File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\site-packages\compose\cli\command.py", line 120, in get_client
    environment=environment, tls_version=get_tls_version(environment)
  File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\site-packages\compose\cli\docker_client.py", line 127, in docker_client
    client = APIClient(**kwargs)
  File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\site-packages\docker\api\client.py", line 166, in __init__
    base_url, timeout, pool_connections=num_pools
  File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\site-packages\docker\transport\sshconn.py", line 84, in __init__
    self._connect()
  File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\site-packages\docker\transport\sshconn.py", line 94, in _connect
    parsed.hostname, parsed.port, parsed.username,
  File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\site-packages\paramiko\client.py", line 416, in connect
    self, server_hostkey_name, server_key
  File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\site-packages\paramiko\client.py", line 824, in missing_host_key
    "Server {!r} not found in known_hosts".format(hostname)
paramiko.ssh_exception.SSHException: Server 'a.b.c.d' not found in known_hosts
paramiko.transport._log: EOF in transport thread
```

**with DOCKER_HOST=tcp://127.0.0.1:23750**
```
PS C:\TEMP> $Env:DOCKER_HOST="tcp://127.0.0.1:23750"
PS C:\TEMP> docker-compose.exe --verbose --log-level DEBUG down
compose.config.config.find: Using configuration files: .\docker-compose.yml
docker.utils.config.find_config_file: Trying paths: ['C:\\Users\\user\\.docker\\config.json', 'C:\\Users\\user\\.dockercfg']
docker.utils.config.find_config_file: No config file found
docker.utils.config.find_config_file: Trying paths: ['C:\\Users\\user\\.docker\\config.json', 'C:\\Users\\user\\.dockercfg']
docker.utils.config.find_config_file: No config file found
urllib3.connectionpool._new_conn: Starting new HTTP connection (1): 127.0.0.1:23750
urllib3.connectionpool._make_request: http://127.0.0.1:23750 "GET /v1.30/version HTTP/1.1" 200 570
compose.cli.command.get_client: docker-compose version 1.25.4, build unknown
docker-py version: 4.1.0
CPython version: 3.7.2
OpenSSL version: OpenSSL 1.1.0j  20 Nov 2018
compose.cli.command.get_client: Docker base_url: http://127.0.0.1:23750
compose.cli.command.get_client: Docker version: Platform={'Name': 'Docker Engine - Community'}, Components=[{'Name': 'Engine', 'Version': '18.09.1', 'Details': {'ApiVersion': '1.39', 'Arch': 'amd64', 'BuildTime': '2019-01-09T19:06:30.000000000+00:00', 'Experimental': 'false', 'GitCommit': '4c52b90', 'GoVersion': 'go1.10.6', 'KernelVersion': '3.10.0-957.el7.x86_64', 'MinAPIVersion': '1.12', 'Os': 'linux'}}], Version=18.09.1, ApiVersion=1.39, MinAPIVersion=1.12, GitCommit=4c52b90, GoVersion=go1.10.6, Os=linux, Arch=amd64, KernelVersion=3.10.0-957.el7.x86_64, BuildTime=2019-01-09T19:06:30.000000000+00:00
compose.cli.verbose_proxy.proxy_callable: docker inspect_network <- ('temp_default')
urllib3.connectionpool._make_request: http://127.0.0.1:23750 "GET /v1.30/networks/temp_default HTTP/1.1" 200 553
compose.cli.verbose_proxy.proxy_callable: docker inspect_network -> {'Attachable': True,
 'ConfigFrom': {'Network': ''},
 'ConfigOnly': False,
 'Containers': {},
 'Created': '2020-03-04T07:11:42.86124979-07:00',
 'Driver': 'bridge',
 'EnableIPv6': False,
 'IPAM': {'Config': [{'Gateway': '192.168.0.1', 'Subnet': '192.168.0.0/20'}],
          'Driver': 'default',
          'Options': None},
...
compose.cli.verbose_proxy.proxy_callable: docker inspect_volume <- ('temp_app')
urllib3.connectionpool._make_request: http://127.0.0.1:23750 "GET /v1.30/volumes/temp_app HTTP/1.1" 200 281
compose.cli.verbose_proxy.proxy_callable: docker inspect_volume -> {'CreatedAt': '2020-03-04T07:11:43-07:00',
 'Driver': 'local',
 'Labels': {'com.docker.compose.project': 'temp',
            'com.docker.compose.version': '1.25.4',
            'com.docker.compose.volume': 'app'},
 'Mountpoint': '/var/lib/docker/volumes/temp_app/_data',
 'Name': 'temp_app',
 'Options': None,
 'Scope': 'local'}
compose.cli.verbose_proxy.proxy_callable: docker containers <- (all=False, filters={'label': ['com.docker.compose.project=temp']})
urllib3.connectionpool._make_request: http://127.0.0.1:23750 "GET /v1.30/containers/json?limit=-1&all=0&size=0&trunc_cmd=0&filters=%7B%22label%22%3A+%5B%22com.docker.compose.project%3Dtemp%22%5D%7D HTTP/1.1" 200 3
compose.cli.verbose_proxy.proxy_callable: docker containers -> (list with 0 items)
compose.cli.verbose_proxy.proxy_callable: docker containers <- (all=False, filters={'label': ['com.docker.compose.project=temp']})
urllib3.connectionpool._make_request: http://127.0.0.1:23750 "GET /v1.30/containers/json?limit=-1&all=0&size=0&trunc_cmd=0&filters=%7B%22label%22%3A+%5B%22com.docker.compose.project%3Dtemp%22%5D%7D HTTP/1.1" 200 3
compose.cli.verbose_proxy.proxy_callable: docker containers -> (list with 0 items)
compose.parallel.feed_queue: Pending: set()
compose.cli.verbose_proxy.proxy_callable: docker containers <- (all=False, filters={'label': ['com.docker.compose.project=temp', 'com.docker.compose.oneoff=False']})
urllib3.connectionpool._make_request: http://127.0.0.1:23750 "GET /v1.30/containers/json?limit=-1&all=0&size=0&trunc_cmd=0&filters=%7B%22label%22%3A+%5B%22com.docker.compose.project%3Dtemp%22%2C+%22com.docker.compose.oneoff%3DFalse%22%5D%7D HTTP/1.1" 200 3
compose.cli.verbose_proxy.proxy_callable: docker containers -> (list with 0 items)
compose.cli.verbose_proxy.proxy_callable: docker containers <- (all=False, filters={'label': ['com.docker.compose.project=temp', 'com.docker.compose.oneoff=False']})
urllib3.connectionpool._make_request: http://127.0.0.1:23750 "GET /v1.30/containers/json?limit=-1&all=0&size=0&trunc_cmd=0&filters=%7B%22label%22%3A+%5B%22com.docker.compose.project%3Dtemp%22%2C+%22com.docker.compose.oneoff%3DFalse%22%5D%7D HTTP/1.1" 200 3
compose.cli.verbose_proxy.proxy_callable: docker containers -> (list with 0 items)
compose.cli.verbose_proxy.proxy_callable: docker containers <- (all=True, filters={'label': ['com.docker.compose.project=temp', 'com.docker.compose.oneoff=False']})
urllib3.connectionpool._make_request: http://127.0.0.1:23750 "GET /v1.30/containers/json?limit=-1&all=1&size=0&trunc_cmd=0&filters=%7B%22label%22%3A+%5B%22com.docker.compose.project%3Dtemp%22%2C+%22com.docker.compose.oneoff%3DFalse%22%5D%7D HTTP/1.1" 200 3
compose.cli.verbose_proxy.proxy_callable: docker containers -> (list with 0 items)
compose.cli.verbose_proxy.proxy_callable: docker containers <- (all=True, filters={'label': ['com.docker.compose.project=temp', 'com.docker.compose.oneoff=False']})
urllib3.connectionpool._make_request: http://127.0.0.1:23750 "GET /v1.30/containers/json?limit=-1&all=1&size=0&trunc_cmd=0&filters=%7B%22label%22%3A+%5B%22com.docker.compose.project%3Dtemp%22%2C+%22com.docker.compose.oneoff%3DFalse%22%5D%7D HTTP/1.1" 200 3
compose.cli.verbose_proxy.proxy_callable: docker containers -> (list with 0 items)
compose.cli.verbose_proxy.proxy_callable: docker containers <- (all=True, filters={'label': ['com.docker.compose.project=temp']})
urllib3.connectionpool._make_request: http://127.0.0.1:23750 "GET /v1.30/containers/json?limit=-1&all=1&size=0&trunc_cmd=0&filters=%7B%22label%22%3A+%5B%22com.docker.compose.project%3Dtemp%22%5D%7D HTTP/1.1" 200 3
compose.cli.verbose_proxy.proxy_callable: docker containers -> (list with 0 items)
compose.cli.verbose_proxy.proxy_callable: docker containers <- (all=True, filters={'label': ['com.docker.compose.project=temp']})
urllib3.connectionpool._make_request: http://127.0.0.1:23750 "GET /v1.30/containers/json?limit=-1&all=1&size=0&trunc_cmd=0&filters=%7B%22label%22%3A+%5B%22com.docker.compose.project%3Dtemp%22%5D%7D HTTP/1.1" 200 3
compose.cli.verbose_proxy.proxy_callable: docker containers -> (list with 0 items)
compose.parallel.feed_queue: Pending: set()
compose.network.remove: Removing network temp_default
compose.cli.verbose_proxy.proxy_callable: docker remove_network <- ('temp_default')
urllib3.connectionpool._make_request: http://127.0.0.1:23750 "DELETE /v1.30/networks/temp_default HTTP/1.1" 204 0
compose.cli.verbose_proxy.proxy_callable: docker remove_network -> None
```

## Additional information

OS version / distribution, `docker-compose` install method, etc.
Windows 10 10.0.16299.1686
docker installed via choco package manager
docker-compose installed via python "pip install"
**Output of `ssh -V`**
```
OpenSSH_for_Windows_8.0p1, LibreSSL 2.6.5
```

**Comment by terroirman** [comment]
Finally, I don't think this is due to compose. This problem was seen through vscode remote container development extension. I think it changes the home env variable, and this is what makes paramiko fails. I'll check with vscode team again.
