### ISSUE TITLE
docker.auth.auth.load_config: File doesn't exist

### ISSUE THREAD

**Issue by hochan222** [docker/compose#7278]
## Description of the issue
docker.auth.auth.load_config: File doesn't exist

However I remove all docker image and docker process it works well
Can you explain why you are getting this error?

## Context information (for bug reports)

**Output of `docker-compose version`**
```
docker-compose version 1.8.0, build unknown
```

**Output of `docker version`**
```
Docker version 19.03.7, build 7141c199a2
```

**Output of `docker-compose config`**
(Make sure to add the relevant `-f` and other flags)
```
version: '2.0'
services:
  web:
    build: .
    ports:
      - "5000:5000"
  redis:
    image: "redis:alpine"
```

## Steps to reproduce the issue

1.
2.
3.

### Stacktrace / full error message

```
hochan@hochan-node:~/Desktop/pfc/dockercompose$ sudo docker-compose up
WARNING: Found orphan containers (dockercompose_redis-server_1) for this project. If you removed or renamed this service in your compose file, you can run this command with the --remove-orphans flag to clean it up.
Recreating dockercompose_web_1
Starting dockercompose_redis_1
Attaching to dockercompose_redis_1, dockercompose_web_1
redis_1  | 1:C 10 Mar 2020 19:25:16.801 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
redis_1  | 1:C 10 Mar 2020 19:25:16.801 # Redis version=5.0.7, bits=64, commit=00000000, modified=0, pid=1, just started
redis_1  | 1:C 10 Mar 2020 19:25:16.801 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
redis_1  | 1:M 10 Mar 2020 19:25:16.802 * Running mode=standalone, port=6379.
redis_1  | 1:M 10 Mar 2020 19:25:16.802 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
redis_1  | 1:M 10 Mar 2020 19:25:16.802 # Server initialized
redis_1  | 1:M 10 Mar 2020 19:25:16.802 # WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue run the command 'echo never > /sys/kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is disabled.
redis_1  | 1:M 10 Mar 2020 19:25:16.802 * DB loaded from disk: 0.000 seconds
redis_1  | 1:M 10 Mar 2020 19:25:16.802 * Ready to accept connections
web_1    | npm WARN app No description
web_1    | npm WARN app No repository field.
web_1    | npm WARN app No license field.
web_1    | 
web_1    | audited 130 packages in 1.281s
web_1    | found 0 vulnerabilities
web_1    | 
dockercompose_web_1 exited with code 0

hochan@hochan-node:~/Desktop/pfc/dockercompose$ sudo docker-hochan@hochan-node:~/Desktop/pfc/dockercompose$ sudo docker-compose ps
[sudo] password for hochan: 
          Name                        Command               State     Ports   
-----------------------------------------------------------------------------
dockercompose_node-app_1   docker-entrypoint.sh npm i ...   Exit 0            
dockercompose_redis_1      docker-entrypoint.sh redis ...   Up       6379/tcp 

hochan@hochan-node:~/Desktop/pfc/dockercompose$ docker-compose --verbose up
compose.config.config.find: Using configuration files: ./docker-compose.yml
docker.auth.auth.load_config: File doesn't exist
Traceback (most recent call last):
  File "/usr/bin/docker-compose", line 9, in <module>
    load_entry_point('docker-compose==1.8.0', 'console_scripts', 'docker-compose')()
  File "/usr/lib/python2.7/dist-packages/compose/cli/main.py", line 61, in main
    command()
  File "/usr/lib/python2.7/dist-packages/compose/cli/main.py", line 110, in perform_command
    project = project_from_options('.', options)
  File "/usr/lib/python2.7/dist-packages/compose/cli/command.py", line 35, in project_from_options
    environment=environment
  File "/usr/lib/python2.7/dist-packages/compose/cli/command.py", line 110, in get_project
    host=host, environment=environment
  File "/usr/lib/python2.7/dist-packages/compose/cli/command.py", line 85, in get_client
    version_info = six.iteritems(client.version())
  File "/usr/lib/python2.7/dist-packages/docker/api/daemon.py", line 76, in version
    return self._result(self._get(url), json=True)
  File "/usr/lib/python2.7/dist-packages/docker/utils/decorators.py", line 47, in inner
    return f(self, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/docker/client.py", line 140, in _get
    return self.get(url, **self._set_request_timeout(kwargs))
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 492, in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 480, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 588, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 426, in send
    raise ConnectionError(err, request=request)
```

## Additional information

OS version / distribution, `docker-compose` install method, etc.
Ubuntu 16.04

**Comment by hochan222** [comment]
FROM node:alpine

WORKDIR /code
COPY package.json .
RUN npm install
COPY . .

CMD ["npm", "install"]

it's my old Dockerfile

FROM node:alpine

WORKDIR /code
COPY package.json .
RUN npm install
COPY . .

CMD ["npm", "start"]

it's my new Dockerfile

I did not run npm start.
Maybe 'docker.auth.auth.load_config: File doesn't exist' error seems to be caused by a configuration problem.
