### ISSUE TITLE
CHOWN failing when trying to set up named volume from compose yaml

### ISSUE THREAD

**Issue by jarodwsams** [docker/compose#7279]
## Description of the issue
I'm using Portainer on a Raspberry Pi 4. I have 2 other compose yamls that I've used with success, so I know it's not my overall yaml syntax. On my 3rd yaml, I tried to include the volume declaration in the file. However, I'm getting an error and creation fails:
> Deployment error
> failed to copy file info for /var/lib/docker/volumes/sonarr_config/_data: failed to chown /var/lib/docker/volumes/sonarr_config/_data: lchown /var/lib/docker/volumes/sonarr_config/_data: operation not permitted
![image](https://user-images.githubusercontent.com/22972834/76373781-5d591580-630f-11ea-902f-601bf34611db.png)

## Context information (for bug reports)
Screenshot of the daemon.log:
![image](https://user-images.githubusercontent.com/22972834/76373905-b1fc9080-630f-11ea-9e9b-9e41b1922167.png)
```Mar 10 20:37:08 athena systemd[5129]: var-lib-docker-volumes-sonarr_config-_data.mount: Succeeded.
Mar 10 20:37:08 athena systemd[1]: var-lib-docker-volumes-sonarr_config-_data.mount: Succeeded.
Mar 10 20:37:08 athena systemd[1]: var-lib-docker-overlay2-aaa2864eb8bd3b02ce1972053aaae9ea43e7b10d62d0a134ee67f23d6950c97e-merged.mount: Succeeded.
Mar 10 20:37:08 athena systemd[5129]: var-lib-docker-overlay2-aaa2864eb8bd3b02ce1972053aaae9ea43e7b10d62d0a134ee67f23d6950c97e-merged.mount: Succeeded.
Mar 10 20:37:08 athena dockerd[543]: time="2020-03-10T20:37:08.901960461-05:00" level=error msg="Handler for POST /v1.24/containers/create returned error: failed to copy file info for /var/lib/docker/volumes/sonarr_config/_data: failed to chown /var/lib/docker/volumes/sonarr_config/_data: lchown /var/lib/docker/volumes/sonarr_config/_data: operation not permitted"
Mar 10 20:37:24 athena systemd[5129]: var-lib-docker-overlay2-83b186bd3a878b9e2e329f0eb9aa664bd0eb18114d19c076ecbda7eb54f0b436\x2dinit-merged.mount: Succeeded.
Mar 10 20:37:24 athena systemd[1]: var-lib-docker-volumes-sonarr_config-_data.mount: Succeeded.
Mar 10 20:37:24 athena systemd[5129]: var-lib-docker-volumes-sonarr_config-_data.mount: Succeeded.
Mar 10 20:37:24 athena systemd[1]: var-lib-docker-overlay2-83b186bd3a878b9e2e329f0eb9aa664bd0eb18114d19c076ecbda7eb54f0b436-merged.mount: Succeeded.
Mar 10 20:37:24 athena systemd[5129]: var-lib-docker-overlay2-83b186bd3a878b9e2e329f0eb9aa664bd0eb18114d19c076ecbda7eb54f0b436-merged.mount: Succeeded.
Mar 10 20:37:25 athena dockerd[543]: time="2020-03-10T20:37:25.118395056-05:00" level=error msg="Handler for POST /v1.24/containers/create returned error: failed to copy file info for /var/lib/docker/volumes/sonarr_config/_data: failed to chown /var/lib/docker/volumes/sonarr_config/_data: lchown /var/lib/docker/volumes/sonarr_config/_data: operation not permitted"
Mar 10 20:37:54 athena systemd[5129]: run-docker-runtime\x2drunc-moby-9da1bfe047fef8fbfdc014c34958d4ae7ca151eaf40086a8abc5f64cafa73c9e-runc.s9jVfv.mount: Succeeded.
Mar 10 20:37:54 athena systemd[1]: run-docker-runtime\x2drunc-moby-9da1bfe047fef8fbfdc014c34958d4ae7ca151eaf40086a8abc5f64cafa73c9e-runc.s9jVfv.mount: Succeeded.
Mar 10 20:37:59 athena systemd[5129]: var-lib-docker-overlay2-c49522daafe4246c21f13c81661f9c607d1dd36691589844840eaab4b545474d\x2dinit-merged.mount: Succeeded.
Mar 10 20:37:59 athena systemd[1]: var-lib-docker-overlay2-c49522daafe4246c21f13c81661f9c607d1dd36691589844840eaab4b545474d\x2dinit-merged.mount: Succeeded.
Mar 10 20:37:59 athena systemd[1]: var-lib-docker-volumes-sonarr_config-_data.mount: Succeeded.
Mar 10 20:37:59 athena systemd[5129]: var-lib-docker-volumes-sonarr_config-_data.mount: Succeeded.
Mar 10 20:37:59 athena systemd[1]: var-lib-docker-overlay2-c49522daafe4246c21f13c81661f9c607d1dd36691589844840eaab4b545474d-merged.mount: Succeeded.
Mar 10 20:37:59 athena systemd[5129]: var-lib-docker-overlay2-c49522daafe4246c21f13c81661f9c607d1dd36691589844840eaab4b545474d-merged.mount: Succeeded.
Mar 10 20:37:59 athena dockerd[543]: time="2020-03-10T20:37:59.923908255-05:00" level=error msg="Handler for POST /v1.24/containers/create returned error: failed to copy file info for /var/lib/docker/volumes/sonarr_config/_data: failed to chown /var/lib/docker/volumes/sonarr_config/_data: lchown /var/lib/docker/volumes/sonarr_config/_data: operation not permitted"
Mar 10 20:39:25 athena systemd[5129]: run-docker-runtime\x2drunc-moby-9da1bfe047fef8fbfdc014c34958d4ae7ca151eaf40086a8abc5f64cafa73c9e-runc.V0nPLd.mount: Succeeded.
Mar 10 20:39:25 athena systemd[1]: run-docker-runtime\x2drunc-moby-9da1bfe047fef8fbfdc014c34958d4ae7ca151eaf40086a8abc5f64cafa73c9e-runc.V0nPLd.mount: Succeeded.
Mar 10 20:39:55 athena systemd[5129]: run-docker-runtime\x2drunc-moby-9da1bfe047fef8fbfdc014c34958d4ae7ca151eaf40086a8abc5f64cafa73c9e-runc.Ir8V9z.mount: Succeeded.
Mar 10 20:39:55 athena systemd[1]: run-docker-runtime\x2drunc-moby-9da1bfe047fef8fbfdc014c34958d4ae7ca151eaf40086a8abc5f64cafa73c9e-runc.Ir8V9z.mount: Succeeded.
Mar 10 20:40:25 athena systemd[5129]: run-docker-runtime\x2drunc-moby-9da1bfe047fef8fbfdc014c34958d4ae7ca151eaf40086a8abc5f64cafa73c9e-runc.hB23EW.mount: Succeeded.
Mar 10 20:40:25 athena systemd[1]: run-docker-runtime\x2drunc-moby-9da1bfe047fef8fbfdc014c34958d4ae7ca151eaf40086a8abc5f64cafa73c9e-runc.hB23EW.mount: Succeeded.
Mar 10 20:41:26 athena systemd[5129]: run-docker-runtime\x2drunc-moby-9da1bfe047fef8fbfdc014c34958d4ae7ca151eaf40086a8abc5f64cafa73c9e-runc.hmC4kA.mount: Succeeded.
Mar 10 20:41:26 athena systemd[1]: run-docker-runtime\x2drunc-moby-9da1bfe047fef8fbfdc014c34958d4ae7ca151eaf40086a8abc5f64cafa73c9e-runc.hmC4kA.mount: Succeeded.
```

Docker-Compose yaml:
```---
version: "2"
services:
  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
      - UMASK_SET=022
    volumes:
      - config:/config
      - library:/tv
      - downloads:/downloads
    ports:
      - 56470:8989
    restart: unless-stopped

volumes:
  config:
    driver_opts:
      type: "nfs4"
      o: "addr=10.0.0.200,rw,noatime,rsize=8192,wsize=8192,tcp,timeo=14"
      device: ":/mnt/pantheon/apps/sonarr"
  library:
    driver_opts:
      type: "nfs4"
      o: "addr=10.0.0.200,rw,noatime,rsize=8192,wsize=8192,tcp,timeo=14"
      device: ":/mnt/pantheon/library/television"
  downloads:
    driver_opts:
      type: "nfs4"
      o: "addr=10.0.0.200,rw,noatime,rsize=8192,wsize=8192,tcp,timeo=14"
      device: ":/mnt/pantheon/downloads/dst/Television"
```

**Output of `docker-compose version`**
```
root@athena:/var/lib/docker/volumes# docker-compose version
Traceback (most recent call last):
  File "/usr/local/bin/docker-compose", line 6, in <module>
    from compose.cli.main import main
  File "/usr/local/lib/python2.7/dist-packages/compose/cli/main.py", line 18, in <module>
    import docker.errors
  File "/usr/local/lib/python2.7/dist-packages/docker/__init__.py", line 2, in <module>
    from .api import APIClient
  File "/usr/local/lib/python2.7/dist-packages/docker/api/__init__.py", line 2, in <module>
    from .client import APIClient
  File "/usr/local/lib/python2.7/dist-packages/docker/api/client.py", line 10, in <module>
    from .build import BuildApiMixin
  File "/usr/local/lib/python2.7/dist-packages/docker/api/build.py", line 6, in <module>
    from .. import auth
  File "/usr/local/lib/python2.7/dist-packages/docker/auth.py", line 9, in <module>
    from .utils import config
  File "/usr/local/lib/python2.7/dist-packages/docker/utils/__init__.py", line 3, in <module>
    from .decorators import check_resource, minimum_version, update_headers
  File "/usr/local/lib/python2.7/dist-packages/docker/utils/decorators.py", line 4, in <module>
    from . import utils
  File "/usr/local/lib/python2.7/dist-packages/docker/utils/utils.py", line 13, in <module>
    from .. import tls
  File "/usr/local/lib/python2.7/dist-packages/docker/tls.py", line 5, in <module>
    from .transport import SSLHTTPAdapter
  File "/usr/local/lib/python2.7/dist-packages/docker/transport/__init__.py", line 3, in <module>
    from .ssladapter import SSLHTTPAdapter
  File "/usr/local/lib/python2.7/dist-packages/docker/transport/ssladapter.py", line 23, in <module>
    from backports.ssl_match_hostname import match_hostname
ImportError: No module named ssl_match_hostname
```

**Output of `docker version`**
```
root@athena:/var/lib/docker/volumes# docker version
Client: Docker Engine - Community
 Version:           19.03.7
 API version:       1.40
 Go version:        go1.12.17
 Git commit:        7141c19
 Built:             Wed Mar  4 01:55:10 2020
 OS/Arch:           linux/arm
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.7
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.17
  Git commit:       7141c19
  Built:            Wed Mar  4 01:49:01 2020
  OS/Arch:          linux/arm
  Experimental:     false
 containerd:
  Version:          1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Output of `docker-compose config`**
```
root@athena:/var/lib/docker/volumes# docker-compose config
Traceback (most recent call last):
  File "/usr/local/bin/docker-compose", line 6, in <module>
    from compose.cli.main import main
  File "/usr/local/lib/python2.7/dist-packages/compose/cli/main.py", line 18, in <module>
    import docker.errors
  File "/usr/local/lib/python2.7/dist-packages/docker/__init__.py", line 2, in <module>
    from .api import APIClient
  File "/usr/local/lib/python2.7/dist-packages/docker/api/__init__.py", line 2, in <module>
    from .client import APIClient
  File "/usr/local/lib/python2.7/dist-packages/docker/api/client.py", line 10, in <module>
    from .build import BuildApiMixin
  File "/usr/local/lib/python2.7/dist-packages/docker/api/build.py", line 6, in <module>
    from .. import auth
  File "/usr/local/lib/python2.7/dist-packages/docker/auth.py", line 9, in <module>
    from .utils import config
  File "/usr/local/lib/python2.7/dist-packages/docker/utils/__init__.py", line 3, in <module>
    from .decorators import check_resource, minimum_version, update_headers
  File "/usr/local/lib/python2.7/dist-packages/docker/utils/decorators.py", line 4, in <module>
    from . import utils
  File "/usr/local/lib/python2.7/dist-packages/docker/utils/utils.py", line 13, in <module>
    from .. import tls
  File "/usr/local/lib/python2.7/dist-packages/docker/tls.py", line 5, in <module>
    from .transport import SSLHTTPAdapter
  File "/usr/local/lib/python2.7/dist-packages/docker/transport/__init__.py", line 3, in <module>
    from .ssladapter import SSLHTTPAdapter
  File "/usr/local/lib/python2.7/dist-packages/docker/transport/ssladapter.py", line 23, in <module>
    from backports.ssl_match_hostname import match_hostname
ImportError: No module named ssl_match_hostname
```

## Steps to reproduce the issue

1. copy/paste the provided yaml into Portainer (Stacks > Add Stack > Web Editor)
2. name the new stack
3. click "deploy stack"

### Observed result
Volumes are created, but the error mentioned above is generated.
The desired container is not created.

### Expected result
Volumes would be created and then the desired container(s) would be created and started

### Stacktrace / full error message

```
Deployment error
failed to copy file info for /var/lib/docker/volumes/sonarr_config/_data: failed to chown /var/lib/docker/volumes/sonarr_config/_data: lchown /var/lib/docker/volumes/sonarr_config/_data: operation not permitted
```
![image](https://user-images.githubusercontent.com/22972834/76373781-5d591580-630f-11ea-902f-601bf34611db.png)

## Additional information

Raspbian Buster Lite (Feb 2020 update)
Docker-Compose installed as part of Portainer, I'm assuming

**Comment by SamuelLarkin** [comment]
Hi,
 I'm facing the same issue.  I'm not using portainer to start my `docker-compose` but rather going straight from the command line and I'm getting the same error.

```
docker-compose  version
Traceback (most recent call last):
  File "/usr/local/bin/docker-compose", line 6, in <module>
    from compose.cli.main import main
  File "/usr/local/lib/python2.7/dist-packages/compose/cli/main.py", line 18, in <module>
    import docker.errors
  File "/usr/local/lib/python2.7/dist-packages/docker/__init__.py", line 2, in <module>
    from .api import APIClient
  File "/usr/local/lib/python2.7/dist-packages/docker/api/__init__.py", line 2, in <module>
    from .client import APIClient
  File "/usr/local/lib/python2.7/dist-packages/docker/api/client.py", line 10, in <module>
    from .build import BuildApiMixin
  File "/usr/local/lib/python2.7/dist-packages/docker/api/build.py", line 6, in <module>
    from .. import auth
  File "/usr/local/lib/python2.7/dist-packages/docker/auth.py", line 9, in <module>
    from .utils import config
  File "/usr/local/lib/python2.7/dist-packages/docker/utils/__init__.py", line 3, in <module>
    from .decorators import check_resource, minimum_version, update_headers
  File "/usr/local/lib/python2.7/dist-packages/docker/utils/decorators.py", line 4, in <module>
    from . import utils
  File "/usr/local/lib/python2.7/dist-packages/docker/utils/utils.py", line 13, in <module>
    from .. import tls
  File "/usr/local/lib/python2.7/dist-packages/docker/tls.py", line 5, in <module>
    from .transport import SSLHTTPAdapter
  File "/usr/local/lib/python2.7/dist-packages/docker/transport/__init__.py", line 3, in <module>
    from .ssladapter import SSLHTTPAdapter
  File "/usr/local/lib/python2.7/dist-packages/docker/transport/ssladapter.py", line 23, in <module>
    from backports.ssl_match_hostname import match_hostname
ImportError: No module named ssl_match_hostname
```

My sdcard died on me thus I was in the process of rebuilding my raspberry pi 4 with `2020-02-13-raspbian-buster-lite` and I used the following commands to setup docker/docker-compose as I did previously:

```
sudo apt-get install -y libffi-dev libssl-dev
sudo apt-get install -y python python-pip
sudo apt-get remove python-configparser
curl -sSL https://get.docker.com | sh
sudo usermod -aG docker pi
sudo pip install docker-compose
docker volume create portainer_data
docker \
  run \
    --detach \
    --publish 8000:8000 \
    --publish 9000:9000 \
    --name=portainer \
    --restart=always \
    --volume /var/run/docker.sock:/var/run/docker.sock \
    --volume portainer_data:/data \
    portainer/portainer
```

**Comment by SamuelLarkin** [comment]
Hi,
as to complete my documentation on this error, I fixed my issue.  After rebuilding my raspberry pi 4 and installing `docker` & `docker-compose`, I forgot an crutial step `sudo apt-get remove python-configparser`.  Once I did this, I was able to user `docker-compose` once again.  Thus, the install procedure should be:

```
sudo apt-get install -y libffi-dev libssl-dev
sudo apt-get install -y python python-pip
sudo apt-get remove python-configparser  # If you skip this line, docker-compose will break.
curl -sSL https://get.docker.com | sh
sudo usermod -aG docker pi
sudo pip install docker-compose
docker volume create portainer_data
docker \
  run \
    --detach \
    --publish 8000:8000 \
    --publish 9000:9000 \
    --name=portainer \
    --restart=always \
    --volume /var/run/docker.sock:/var/run/docker.sock \
    --volume portainer_data:/data \
    portainer/portainer
```
