### ISSUE TITLE
Rails Quickstart Fails

### ISSUE THREAD

**Issue by brandonzylstra** [docker/compose#73]
Following [the directions for the Rails quick start](http://orchardup.github.io/fig/rails.html), I get an error running fig:

```
$ fig run web rails new . --force --database=postgresql --skip-bundle
Traceback (most recent call last):
  File "/usr/local/bin/fig", line 9, in <module>
    load_entry_point('fig==0.2.0', 'console_scripts', 'fig')()
  File "/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/fig/cli/main.py", line 39, in main
    command.sys_dispatch()
  File "/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/fig/cli/docopt_command.py", line 21, in sys_dispatch
    self.dispatch(sys.argv[1:], None)
  File "/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/fig/cli/command.py", line 24, in dispatch
    super(Command, self).dispatch(*args, **kwargs)
  File "/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/fig/cli/docopt_command.py", line 24, in dispatch
    self.perform_command(*self.parse(argv, global_options))
  File "/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/fig/cli/docopt_command.py", line 27, in perform_command
    handler(command_options)
  File "/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/fig/cli/main.py", line 215, in run
    container = service.create_container(one_off=True, **container_options)
  File "/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/fig/service.py", line 108, in create_container
    container_options = self._get_container_options(override_options, one_off=one_off)
  File "/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/fig/service.py", line 225, in _get_container_options
    container_options['name'] = self.next_container_name(one_off)
  File "/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/fig/service.py", line 199, in next_container_name
    return '_'.join(bits + [str(self.next_container_number(one_off=one_off))])
  File "/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/fig/service.py", line 202, in next_container_number
    numbers = [parse_name(c.name)[2] for c in self.containers(stopped=True, one_off=one_off)]
  File "/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/fig/service.py", line 38, in containers
    for container in self.client.containers(all=stopped):
  File "/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/fig/packages/docker/client.py", line 399, in containers
    res = self._result(self._get(u, params=params), True)
  File "/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/fig/packages/docker/client.py", line 98, in _get
    return self.get(url, **self._set_request_timeout(kwargs))
  File "/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/requests/sessions.py", line 395, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/requests/sessions.py", line 349, in request
    prep = self.prepare_request(req)
  File "/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/requests/sessions.py", line 287, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/requests/models.py", line 287, in prepare
    self.prepare_url(url, params)
  File "/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/requests/models.py", line 338, in prepare_url
    "Perhaps you meant http://{0}?".format(url))
requests.exceptions.MissingSchema: Invalid URL u'localhost/v1.6/containers/json': No schema supplied. Perhaps you meant http://localhost/v1.6/containers/json?
```

It is not at all obvious to me what is causing this or where it is coming from.  But I checked all files (and even copied the contents from the directions to make sure I had not fat-fingered anything), and the error persisted.  All dependencies appeared to install correctly.

**Comment by JemiloII** [comment]
Just do:

`export DOCKER_HOST=/path/to/docker.sock`

**Comment by SMalchenko** [comment]
Thanks @rusllonrails

**Comment by ashish-arora02** [comment]
thanks @rusllonrails you saved my life.
