### ISSUE TITLE
Failed to execute script docker-compose

### ISSUE THREAD

**Issue by dark0ghost** [docker/compose#7333]
## Context information (for bug reports)

**Output of `docker-compose version`**
```
docker-compose version 1.21.0, build 5920eb0

```

**Output of `docker version`**
```
Docker version 19.03.8, build afacb8b7f0

```

**Output of `docker-compose config`**
(Make sure to add the relevant `-f` and other flags)
```
version: '3.3'

services:
  postgres:
    image:
      postgres:11
    volumes:
      - "./postgres/data:/var/lib/postgresql/data/pgdata"
    environment:
      -POSTGRES_USER=aiopg
      -POSTGRES_PASSWORD=passwd
      -PGDATA=./postgres/data:/var/lib/postgresql/data/pgdata
    restart:
      always
    ports:
      5432:5432



  redis:
      container_name: redis
      image:
        redis:alpine
      ports:
        - "6379:6379"
      command:
        - 'redis-server'
        - '--loglevel ${REDIS_LOGLEVEL:-warning}'
        - '--databases 2'
        - '--maxmemory ${REDIS_MAXMEM:-50mb}'
        - '--maxmemory-policy ${REDIS_POLICY:-noeviction}'
      volumes:
        - ../data/redis:/data
      restart: always

  adminer:
      image:
        adminer
      restart:
        always
      ports:
        - 8080:8080
```

## Steps to reproduce the issue

1.
2.
3.

### Stacktrace / full error message

```
error 
up servises

/usr/local/bin/docker-compose -f /home/project/0104/docker-compose.yml up -d postgres
Traceback (most recent call last):
  File "bin/docker-compose", line 6, in <module>
  File "compose/cli/main.py", line 71, in main
  File "compose/cli/main.py", line 124, in perform_command
  File "compose/cli/command.py", line 38, in project_from_options
  File "compose/cli/docker_client.py", line 84, in tls_config_from_options
  File "site-packages/docker/tls.py", line 81, in __init__
docker.errors.TLSParameterError: Path to a certificate and key files must be provided through the client_config param. TLS configurations should map the Docker CLI client configurations. See https://docs.docker.com/engine/articles/https/ for API details.
[10541] Failed to execute script docker-compose
Failed to deploy 'Compose: docker-compose.yml': `docker-compose` process finished with exit code 255
```

## Additional information

OS version / distribution, `docker-compose` install method, etc.
debian 10

**Comment by zethis** [comment]
Same here with docker 19.03.8, no problem with the same docker-compose file on 19.03.5.

**Comment by alexisrodriguezead** [comment]
Same here, docker 19.03.8 on MacOS catalina, upgrading from docker toolbox

**Comment by alopez1039** [comment]
Same issue here, macOS Mojave 10.14.5.
Docker version 19.03.8, build afacb8b
docker-compose version 1.25.5, build 8a1c60f6

**Comment by dark0ghost** [comment]
> Same issue here, macOS Mojave 10.14.5.
> Docker version 19.03.8, build afacb8b
> docker-compose version 1.25.5, build 8a1c60f6
> 
> Noticed you are using compose file version 3.3, could that be the issue? VIC docs say the following: ["vSphere Integrated Containers Engine 1.5 supports Docker Compose file version 2, 2.1, and 2.2." ](https://vmware.github.io/vic-product/assets/files/html/1.5/vic_app_dev/docker_compose_file_options.html)

that not the issue
