### ISSUE TITLE
docker-compose 1.26.0rc3 installed from pip fails with "No module named 'dotenv'"

### ISSUE THREAD

**Issue by mxl** [docker/compose#7347]
## Description of the issue

docker-compose 1.26.0rc3 fails with "No module named 'dotenv'" error.

## Context information (for bug reports)

**Output of `docker-compose version`**
See above error.

**Output of `docker version`**
```
Client: Docker Engine - Community
 Version:           19.03.8
 API version:       1.40
 Go version:        go1.12.17
 Git commit:        afacb8b
 Built:             Wed Mar 11 01:21:11 2020
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.8
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.17
  Git commit:       afacb8b
  Built:            Wed Mar 11 01:29:16 2020
  OS/Arch:          linux/amd64
  Experimental:     true
 containerd:
  Version:          v1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Output of `docker-compose config`**

See above error.

## Steps to reproduce the issue

Install docker-compose 1.26.0rc3 from pip:
```bash
$ pip install docker-compose==1.26.0-rc3
```

Then running it:
```bash
$ docker-compose
```
gives:
```
Traceback (most recent call last):
  File "/Users/mledin/.pyenv/versions/default/bin/docker-compose", line 6, in <module>
    from compose.cli.main import main
  File "/Users/mledin/.pyenv/versions/3.8.2/envs/default/lib/python3.8/site-packages/compose/cli/main.py", line 24, in <module>
    from ..config import ConfigurationError
  File "/Users/mledin/.pyenv/versions/3.8.2/envs/default/lib/python3.8/site-packages/compose/config/__init__.py", line 5, in <module>
    from . import environment
  File "/Users/mledin/.pyenv/versions/3.8.2/envs/default/lib/python3.8/site-packages/compose/config/environment.py", line 8, in <module>
    import dotenv
ModuleNotFoundError: No module named 'dotenv'
```

Trying to install dotenv:
```bash
$ pip install dotenv
```
outputs
```
Collecting dotenv
  Using cached dotenv-0.0.5.tar.gz (2.4 kB)
    ERROR: Command errored out with exit status 1:
     command: /Users/mledin/.pyenv/versions/3.8.2/envs/default/bin/python3.8 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/0v/9cjc_d9919qc2kk1wm9b4t5w0000gn/T/pip-install-62wejvik/dotenv/setup.py'"'"'; __file__='"'"'/private/var/folders/0v/9cjc_d9919qc2kk1wm9b4t5w0000gn/T/pip-install-62wejvik/dotenv/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/0v/9cjc_d9919qc2kk1wm9b4t5w0000gn/T/pip-install-62wejvik/dotenv/pip-egg-info
         cwd: /private/var/folders/0v/9cjc_d9919qc2kk1wm9b4t5w0000gn/T/pip-install-62wejvik/dotenv/
    Complete output (68 lines):
    Traceback (most recent call last):
      File "/Users/mledin/.pyenv/versions/3.8.2/envs/default/lib/python3.8/site-packages/setuptools/sandbox.py", line 154, in save_modules
        yield saved
      File "/Users/mledin/.pyenv/versions/3.8.2/envs/default/lib/python3.8/site-packages/setuptools/sandbox.py", line 194, in setup_context
        __import__('setuptools')
      File "/private/var/folders/0v/9cjc_d9919qc2kk1wm9b4t5w0000gn/T/easy_install-b08izsyd/distribute-0.7.3/setuptools/__init__.py", line 2, in <module>
      File "/private/var/folders/0v/9cjc_d9919qc2kk1wm9b4t5w0000gn/T/easy_install-b08izsyd/distribute-0.7.3/setuptools/extension.py", line 5, in <module>
      File "/private/var/folders/0v/9cjc_d9919qc2kk1wm9b4t5w0000gn/T/easy_install-b08izsyd/distribute-0.7.3/setuptools/dist.py", line 7, in <module>
      File "/private/var/folders/0v/9cjc_d9919qc2kk1wm9b4t5w0000gn/T/easy_install-b08izsyd/distribute-0.7.3/setuptools/command/__init__.py", line 8, in <module>
      File "/private/var/folders/0v/9cjc_d9919qc2kk1wm9b4t5w0000gn/T/easy_install-b08izsyd/distribute-0.7.3/setuptools/command/install_scripts.py", line 3, in <module>
      File "/private/var/folders/0v/9cjc_d9919qc2kk1wm9b4t5w0000gn/T/easy_install-b08izsyd/distribute-0.7.3/pkg_resources.py", line 1518, in <module>
    AttributeError: module 'importlib._bootstrap' has no attribute 'SourceFileLoader'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/0v/9cjc_d9919qc2kk1wm9b4t5w0000gn/T/pip-install-62wejvik/dotenv/setup.py", line 13, in <module>
        setup(name='dotenv',
      File "/Users/mledin/.pyenv/versions/3.8.2/envs/default/lib/python3.8/site-packages/setuptools/__init__.py", line 144, in setup
        _install_setup_requires(attrs)
      File "/Users/mledin/.pyenv/versions/3.8.2/envs/default/lib/python3.8/site-packages/setuptools/__init__.py", line 139, in _install_setup_requires
        dist.fetch_build_eggs(dist.setup_requires)
      File "/Users/mledin/.pyenv/versions/3.8.2/envs/default/lib/python3.8/site-packages/setuptools/dist.py", line 716, in fetch_build_eggs
        resolved_dists = pkg_resources.working_set.resolve(
      File "/Users/mledin/.pyenv/versions/3.8.2/envs/default/lib/python3.8/site-packages/pkg_resources/__init__.py", line 780, in resolve
        dist = best[req.key] = env.best_match(
      File "/Users/mledin/.pyenv/versions/3.8.2/envs/default/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1065, in best_match
        return self.obtain(req, installer)
      File "/Users/mledin/.pyenv/versions/3.8.2/envs/default/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1077, in obtain
        return installer(requirement)
      File "/Users/mledin/.pyenv/versions/3.8.2/envs/default/lib/python3.8/site-packages/setuptools/dist.py", line 786, in fetch_build_egg
        return cmd.easy_install(req)
      File "/Users/mledin/.pyenv/versions/3.8.2/envs/default/lib/python3.8/site-packages/setuptools/command/easy_install.py", line 679, in easy_install
        return self.install_item(spec, dist.location, tmpdir, deps)
      File "/Users/mledin/.pyenv/versions/3.8.2/envs/default/lib/python3.8/site-packages/setuptools/command/easy_install.py", line 705, in install_item
        dists = self.install_eggs(spec, download, tmpdir)
      File "/Users/mledin/.pyenv/versions/3.8.2/envs/default/lib/python3.8/site-packages/setuptools/command/easy_install.py", line 890, in install_eggs
        return self.build_and_install(setup_script, setup_base)
      File "/Users/mledin/.pyenv/versions/3.8.2/envs/default/lib/python3.8/site-packages/setuptools/command/easy_install.py", line 1158, in build_and_install
        self.run_setup(setup_script, setup_base, args)
      File "/Users/mledin/.pyenv/versions/3.8.2/envs/default/lib/python3.8/site-packages/setuptools/command/easy_install.py", line 1144, in run_setup
        run_setup(setup_script, args)
      File "/Users/mledin/.pyenv/versions/3.8.2/envs/default/lib/python3.8/site-packages/setuptools/sandbox.py", line 233, in run_setup
        with setup_context(setup_dir):
      File "/Users/mledin/.pyenv/versions/3.8.2/lib/python3.8/contextlib.py", line 113, in __enter__
        return next(self.gen)
      File "/Users/mledin/.pyenv/versions/3.8.2/envs/default/lib/python3.8/site-packages/setuptools/sandbox.py", line 195, in setup_context
        yield
      File "/Users/mledin/.pyenv/versions/3.8.2/lib/python3.8/contextlib.py", line 131, in __exit__
        self.gen.throw(type, value, traceback)
      File "/Users/mledin/.pyenv/versions/3.8.2/envs/default/lib/python3.8/site-packages/setuptools/sandbox.py", line 166, in save_modules
        saved_exc.resume()
      File "/Users/mledin/.pyenv/versions/3.8.2/envs/default/lib/python3.8/site-packages/setuptools/sandbox.py", line 141, in resume
        six.reraise(type, exc, self._tb)
      File "/Users/mledin/.pyenv/versions/3.8.2/envs/default/lib/python3.8/site-packages/setuptools/_vendor/six.py", line 685, in reraise
        raise value.with_traceback(tb)
      File "/Users/mledin/.pyenv/versions/3.8.2/envs/default/lib/python3.8/site-packages/setuptools/sandbox.py", line 154, in save_modules
        yield saved
      File "/Users/mledin/.pyenv/versions/3.8.2/envs/default/lib/python3.8/site-packages/setuptools/sandbox.py", line 194, in setup_context
        __import__('setuptools')
      File "/private/var/folders/0v/9cjc_d9919qc2kk1wm9b4t5w0000gn/T/easy_install-b08izsyd/distribute-0.7.3/setuptools/__init__.py", line 2, in <module>
      File "/private/var/folders/0v/9cjc_d9919qc2kk1wm9b4t5w0000gn/T/easy_install-b08izsyd/distribute-0.7.3/setuptools/extension.py", line 5, in <module>
      File "/private/var/folders/0v/9cjc_d9919qc2kk1wm9b4t5w0000gn/T/easy_install-b08izsyd/distribute-0.7.3/setuptools/dist.py", line 7, in <module>
      File "/private/var/folders/0v/9cjc_d9919qc2kk1wm9b4t5w0000gn/T/easy_install-b08izsyd/distribute-0.7.3/setuptools/command/__init__.py", line 8, in <module>
      File "/private/var/folders/0v/9cjc_d9919qc2kk1wm9b4t5w0000gn/T/easy_install-b08izsyd/distribute-0.7.3/setuptools/command/install_scripts.py", line 3, in <module>
      File "/private/var/folders/0v/9cjc_d9919qc2kk1wm9b4t5w0000gn/T/easy_install-b08izsyd/distribute-0.7.3/pkg_resources.py", line 1518, in <module>
    AttributeError: module 'importlib._bootstrap' has no attribute 'SourceFileLoader'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

## Additional information

OS version: macOS 10.15.4
docker-compose 1.26.0rc3 installed with pip.
Tried both with Python 2.7 installed from homebrew and with Python 3.8.2 installed with pyenv-virtualenv.

**Comment by itavy** [comment]
hi,

i encountered same error, i installed `python-dotenv` package and it worked

the error comes from missing dependency in [setup.py#L32](https://github.com/docker/compose/blob/1.26.x/setup.py#L32)

in master branch i see that python-dotenv is already listed as install dependency

Regards,
Octavian

**Comment by alexanderadam** [comment]
I'm suddenly experiencing the same issue.
I installed [`docker-compose`](https://formulae.brew.sh/formula/docker-compose) ([source](https://github.com/Homebrew/homebrew-core/blob/master/Formula/docker-compose.rb)) via [Homebrew/Linuxbrew](https://docs.brew.sh/Homebrew-on-Linux) and I'm even getting this issue when checking the version:

```bash
$ docker-compose --version
Traceback (most recent call last):
  File "/home/linuxbrew/.linuxbrew/bin/docker-compose", line 33, in <module>
    sys.exit(load_entry_point('docker-compose==1.27.4', 'console_scripts', 'docker-compose')())
  File "/home/linuxbrew/.linuxbrew/bin/docker-compose", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/home/linuxbrew/.linuxbrew/opt/python@3.9/lib/python3.9/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/home/linuxbrew/.linuxbrew/opt/python@3.9/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/linuxbrew/.linuxbrew/opt/python@3.9/lib/python3.9/site-packages/compose/cli/main.py", line 20, in <module>
    from ..config import ConfigurationError
  File "/home/linuxbrew/.linuxbrew/opt/python@3.9/lib/python3.9/site-packages/compose/config/__init__.py", line 2, in <module>
    from . import environment
  File "/home/linuxbrew/.linuxbrew/opt/python@3.9/lib/python3.9/site-packages/compose/config/environment.py", line 5, in <module>
    import dotenv
ModuleNotFoundError: No module named 'dotenv'
```

**Comment by Anu2001dev** [comment]
I first installed `python-dotenv` with `yay -S python-dotenv` and then I had to install `cached_property` with `pip install cached_property` after that everything was fine.
