### ISSUE TITLE
docker-compose 1.26.0-rc3 from Docker Desktop for macOS doesn't use TLS ("Client sent an HTTP request to an HTTPS server.")

### ISSUE THREAD

**Issue by mxl** [docker/compose#7348]
## Context information (for bug reports)

**Output of `docker-compose version`**
```
docker-compose version 1.26.0-rc3, build 46118bc5
docker-py version: 4.2.0
CPython version: 3.7.6
OpenSSL version: OpenSSL 1.1.1d  10 Sep 2019
```

**Output of `docker version` (Docker Desktop for macOS)**
```
Client: Docker Engine - Community
 Version:           19.03.8
 API version:       1.40
 Go version:        go1.12.17
 Git commit:        afacb8b
 Built:             Wed Mar 11 01:21:11 2020
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.8
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.17
  Git commit:       afacb8b
  Built:            Wed Mar 11 01:29:16 2020
  OS/Arch:          linux/amd64
  Experimental:     true
 containerd:
  Version:          v1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Output of `docker version` (docker-ce package on Ubuntu)**
```
Client: Docker Engine - Community
 Version:           19.03.8
 API version:       1.40
 Go version:        go1.12.17
 Git commit:        afacb8b7f0
 Built:             Wed Mar 11 01:25:46 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.8
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.17
  Git commit:       afacb8b7f0
  Built:            Wed Mar 11 01:24:19 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Output of `docker-compose config`**
(Make sure to add the relevant `-f` and other flags)
```
services:
  gitlab:
    container_name: gitlab
    domainname: gitlab.example.com
    hostname: gitlab
    image: gitlab/gitlab-ce:latest
    ports:
    - 127.0.0.1:8050:80/tcp
    - 0.0.0.0:2022:22/tcp
    restart: always
version: '2.0'
```

## Steps to reproduce the issue

1. Install Docker Desktop for Mac from edge channel version 2.2.3.0 (43965)
2. Install docker on remote host using docker-machine (see [this guide](https://dev.to/zac_siegel/using-docker-machine-to-provision-a-remote-docker-host-1267)) with name and host `example.com` (use your own docker host IP or domain here).
3. Run `eval $(docker-machine env example.com)` command in current shell which will setup following environment variables:
```
export DOCKER_TLS_VERIFY="1"
export DOCKER_HOST="tcp://example.com:2376"
export DOCKER_CERT_PATH="/Users/mledin/.docker/machine/machines/example.com"
export DOCKER_MACHINE_NAME="example.com"
```
4. Try to pull image for `gitlab` service (see above `docker-compose config` output) or run any other command that will interact with remote docker host.

```bash
$ docker-compose pull gitlab
```

### Observed result
```
ERROR: Client sent an HTTP request to an HTTPS server.
```
or with `--verbose` option:
```
compose.config.config.find: Using configuration files: ./docker-compose.yml
docker.utils.config.find_config_file: Trying paths: ['/Users/mledin/.docker/config.json', '/Users/mledin/.dockercfg']
docker.utils.config.find_config_file: Found file at path: /Users/mledin/.docker/config.json
docker.auth.load_config: Found 'auths' section
docker.auth.parse_auth: Auth data for https://index.docker.io/v1/ is absent. Client might be using a credentials store instead.
docker.auth.load_config: Found 'credsStore' section
urllib3.connectionpool._new_conn: Starting new HTTP connection (1): example.com:2376
urllib3.connectionpool._make_request: http://example.com:2376 "GET /v1.22/version HTTP/1.1" 400 None
Traceback (most recent call last):
  File "site-packages/docker/api/client.py", line 261, in _raise_for_status
  File "site-packages/requests/models.py", line 940, in raise_for_status
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: http://example.com:2376/v1.22/version

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "docker-compose", line 6, in <module>
  File "compose/cli/main.py", line 72, in main
  File "compose/cli/main.py", line 125, in perform_command
  File "compose/cli/command.py", line 76, in project_from_options
  File "compose/cli/command.py", line 142, in get_project
  File "compose/cli/docker_client.py", line 50, in get_client
  File "site-packages/docker/api/daemon.py", line 181, in version
  File "site-packages/docker/api/client.py", line 267, in _result
  File "site-packages/docker/api/client.py", line 263, in _raise_for_status
  File "site-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
docker.errors.APIError: 400 Client Error: Bad Request ("b'Client sent an HTTP request to an HTTPS server.'")
[94780] Failed to execute script docker-compose
```

### Expected result

Pull gitlab image.

## Additional information

Removing /usr/local/bin/docker-compose symlink and installing docker-compose 1.25.4 from homebrew fixes the issue:

```
compose.config.config.find: Using configuration files: ./docker-compose.yml
docker.utils.config.find_config_file: Trying paths: ['/Users/mledin/.docker/config.json', '/Users/mledin/.dockercfg']
docker.utils.config.find_config_file: Found file at path: /Users/mledin/.docker/config.json
docker.auth.load_config: Found 'auths' section
docker.auth.parse_auth: Auth data for https://index.docker.io/v1/ is absent. Client might be using a credentials store instead.
docker.auth.load_config: Found 'credsStore' section
urllib3.connectionpool._new_conn: Starting new HTTPS connection (1): example.com:2376
urllib3.connectionpool._make_request: https://example.com:2376 "GET /v1.22/version HTTP/1.1" 200 860
compose.cli.command.get_client: docker-compose version 1.25.4, build unknown
docker-py version: 4.2.0
CPython version: 3.8.2
OpenSSL version: OpenSSL 1.1.1f  31 Mar 2020
compose.cli.command.get_client: Docker base_url: https://example.com:2376
compose.cli.command.get_client: Docker version: Platform={'Name': 'Docker Engine - Community'}, Components=[{'Name': 'Engine', 'Version': '19.03.8', 'Details': {'ApiVersion': '1.40', 'Arch': 'amd64', 'BuildTime': '2020-03-11T01:24:19.000000000+00:00', 'Experimental': 'false', 'GitCommit': 'afacb8b7f0', 'GoVersion': 'go1.12.17', 'KernelVersion': '4.15.0-91-generic', 'MinAPIVersion': '1.12', 'Os': 'linux'}}, {'Name': 'containerd', 'Version': '1.2.13', 'Details': {'GitCommit': '7ad184331fa3e55e52b890ea95e65ba581ae3429'}}, {'Name': 'runc', 'Version': '1.0.0-rc10', 'Details': {'GitCommit': 'dc9208a3303feef5b3839f4323d9beb36df0a9dd'}}, {'Name': 'docker-init', 'Version': '0.18.0', 'Details': {'GitCommit': 'fec3683'}}], Version=19.03.8, ApiVersion=1.40, MinAPIVersion=1.12, GitCommit=afacb8b7f0, GoVersion=go1.12.17, Os=linux, Arch=amd64, KernelVersion=4.15.0-91-generic, BuildTime=2020-03-11T01:24:19.000000000+00:00
compose.cli.verbose_proxy.proxy_callable: docker inspect_network <- ('gitlab_default')
urllib3.connectionpool._make_request: https://example.com:2376 "GET /v1.22/networks/gitlab_default HTTP/1.1" 404 41
...
```

Local machine OS where docker-compose and docker-machine are executed: macOS 10.15.4
docker-compose is installed with Docker Desktop for Mac from edge channel version 2.2.3.0 (43965).
Remote docker host OS: Ubuntu 18.04.4 LTS with 4.15.0-91-generic kernel.

docker on remote host is launched by systemd `/etc/systemd/system/docker.service`:
```
[Service]
ExecStart=/usr/bin/dockerd -H tcp://0.0.0.0:2376 -H unix:///var/run/docker.sock --storage-driver aufs --tlsverify --tlscacert /etc/docker/ca.pem --tlscert /etc/docker/server.pem --tlskey /etc/docker/server-key.pem --label provider=generic
LimitNOFILE=1048576
LimitNPROC=1048576
LimitCORE=infinity
Environment=

[Install]
WantedBy=multi-user.target
```

**Comment by glenfordwilliams** [comment]
having the same issue

docker-compose version

```
docker-compose version 1.26.0-rc3, build 46118bc5
docker-py version: 4.2.0
CPython version: 3.7.4
OpenSSL version: OpenSSL 1.1.1c  28 May 2019
```

docker version
``` 
Client: Docker Engine - Community
 Version:           19.03.8
 API version:       1.40
 Go version:        go1.12.17
 Git commit:        afacb8b
 Built:             Wed Mar 11 01:23:10 2020
 OS/Arch:           windows/amd64
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          19.03.8
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.17
  Git commit:       afacb8b
  Built:            Wed Mar 11 01:29:16 2020
  OS/Arch:          linux/amd64
  Experimental:     true
 containerd:
  Version:          v1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Comment by gitoshh** [comment]
Facing the same issue here. 
docker-compose version 
```1.26.0-rc3, build 46118bc5```

**Comment by maxruby** [comment]
Same problem here.

**Comment by oocx** [comment]
I see the same problem. Fixed it by downgrading docker-compose to 1.25.4.

**Comment by scuml** [comment]
Same issue in docker-compose version 1.26.0-rc4, build d279b7a8

**Comment by number5** [comment]
Have same issue, upgraded docker-compose to 1.26.0 fixed it
```
λ docker-compose version                                               [06-27 20:22]
docker-compose version 1.26.0, build unknown
docker-py version: 4.2.1
CPython version: 3.7.7
OpenSSL version: OpenSSL 1.1.1g  21 Apr 2020
```

**Comment by rlanore** [comment]
Have same issue on dind alpine with pip install docker-compose
```
/builds/test-ci # docker-compose version
docker-compose version 1.27.3, build unknown
docker-py version: 4.3.1
CPython version: 3.8.5
OpenSSL version: OpenSSL 1.1.1g  21 Apr 2020
```

**Comment by tkent** [comment]
Seeing this same issue using Docker Desktop for Mac `3.3.0`. The `docker-compose version` command shows:

```
docker-compose version 1.29.0, build 07737305
docker-py version: 5.0.0
CPython version: 3.9.0
OpenSSL version: OpenSSL 1.1.1h  22 Sep 2020
```

I also had to install an older version of `docker-compose` to work around the problem

**Comment by ndeloof** [comment]
Closing as docker-compose v1 is EoL
