### ISSUE TITLE
Docker compose up not working as expected

### ISSUE THREAD

**Issue by aaronspin** [docker/compose#7349]
- [x] I have tried with the latest version of my channel (Stable or Edge)  -- I tried downgrading, this still happens.
  - [ x] I have uploaded Diagnostics
  - Diagnostics ID: 97BD6841-8F6E-4BB7-A03A-88A50BFAA93D/20200407041621

Output for docker-compose up, running macOS Version: 10.15.4

```
Traceback (most recent call last):
  File "docker-compose", line 6, in <module>
  File "compose/cli/main.py", line 72, in main
  File "compose/cli/main.py", line 128, in perform_command
  File "compose/cli/main.py", line 1077, in up
  File "compose/cli/main.py", line 1073, in up
  File "compose/project.py", line 548, in up
  File "compose/service.py", line 355, in ensure_image_exists
  File "compose/service.py", line 381, in image
  File "site-packages/docker/utils/decorators.py", line 17, in wrapped
docker.errors.NullResource: Resource ID was not provided
[64031] Failed to execute script docker-compose
```

Re-inistalling docker does nothing to fix this. Honestly stumped by this one. Would appreciate any help.

**Comment by aaronspin** [comment]
For others having a similar issue, it was caused by undefined environment variables. Tricky issue.

**Comment by tuxuser** [comment]
@aaronspin Can you please elaborate which specific env variables were missing?
