### ISSUE TITLE
Windows  docker-compose 1.26.0-rc3 error when connecting to remote host

### ISSUE THREAD

**Issue by bampo** [docker/compose#7353]
## Description of the issue
After update windows Docker Desktop to version 2.2.3.0(43965) with docker compose 1.26.0-rc3
any docker-compose command for remote hosts rise an error:
"ERROR: Couldn't connect to Docker daemon at http://efir-docker:2376 - is it running?
If it's at a non-standard location, specify the URL with the DOCKER_HOST environment variable."
DOCKER_HOST and other env variables with TLS settings exists. And the simple 'docker' command works perfectly.
## Context information (for bug reports)

**Output of `docker-compose version`**
```
docker-compose version 1.26.0-rc3, build 46118bc5
docker-py version: 4.2.0
CPython version: 3.7.4
OpenSSL version: OpenSSL 1.1.1c  28 May 2019
```

**Output of `docker version`**
```
Docker version 19.03.8, build afacb8b
```

## Steps to reproduce the issue

1. set DOCKER_HOST=tcp://remote_host:3276 (for normal set also DOCKER_TLS_*  but not for bug reproduction)
2. docker-compose ps
3. 

### Observed result
Recieve ERROR: Couldn't connect to Docker daemon at http://...
### Stacktrace / full error message
With --vebose option 

```
docker-compose --verbose ps
compose.config.config.find: Using configuration files: .\docker-compose.yml
docker.utils.config.find_config_file: Trying paths: ['C:\\Users\\ss\\.docker\\config.json', 'C:\\Users\\ss\\.dockercfg']
docker.utils.config.find_config_file: Found file at path: C:\Users\ss\.docker\config.json
docker.auth.load_config: Found 'credsStore' section
urllib3.connectionpool._new_conn: Starting new HTTP connection (1): efir-docker:2376
Traceback (most recent call last):
  File "site-packages\urllib3\connectionpool.py", line 672, in urlopen
  File "site-packages\urllib3\connectionpool.py", line 421, in _make_request
  File "<string>", line 3, in raise_from
  File "site-packages\urllib3\connectionpool.py", line 416, in _make_request
  File "http\client.py", line 1336, in getresponse
  File "http\client.py", line 306, in begin
  File "http\client.py", line 288, in _read_status
http.client.BadStatusLine:  


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "site-packages\requests\adapters.py", line 449, in send
  File "site-packages\urllib3\connectionpool.py", line 720, in urlopen
  File "site-packages\urllib3\util\retry.py", line 400, in increment
  File "site-packages\urllib3\packages\six.py", line 734, in reraise
  File "site-packages\urllib3\connectionpool.py", line 672, in urlopen
  File "site-packages\urllib3\connectionpool.py", line 421, in _make_request
  File "<string>", line 3, in raise_from
  File "site-packages\urllib3\connectionpool.py", line 416, in _make_request
  File "http\client.py", line 1336, in getresponse
  File "http\client.py", line 306, in begin
  File "http\client.py", line 288, in _read_status
urllib3.exceptions.ProtocolError: ('Connection aborted.', BadStatusLine('\x15\x03\x01\x00\x02\x02\n'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "docker-compose", line 6, in <module>
  File "compose\cli\main.py", line 72, in main
  File "compose\cli\main.py", line 125, in perform_command
  File "compose\cli\command.py", line 76, in project_from_options
  File "compose\cli\command.py", line 142, in get_project
  File "compose\cli\docker_client.py", line 50, in get_client
  File "site-packages\docker\api\daemon.py", line 181, in version
  File "site-packages\docker\utils\decorators.py", line 46, in inner
  File "site-packages\docker\api\client.py", line 230, in _get
  File "site-packages\requests\sessions.py", line 546, in get
  File "site-packages\requests\sessions.py", line 533, in request
  File "site-packages\requests\sessions.py", line 646, in send
  File "site-packages\requests\adapters.py", line 498, in send
requests.exceptions.ConnectionError: ('Connection aborted.', BadStatusLine('\x15\x03\x01\x00\x02\x02\n'))
[15200] Failed to execute script docker-compose
```

## Additional information
Windows 10 ver. 2004 Build 19041.173

**Comment by robertklent** [comment]
I am facing exact same issue with exact same versions. docker-compose version 1.26.0-rc3, build 46118bc5
