### ISSUE TITLE
Cannot get version of docker-compose

### ISSUE THREAD

**Issue by ORESoftware** [docker/compose#7382]
When I run:

```
docker-compose --version
```

I get:

```
$ docker-compose --version 
Traceback (most recent call last):
  File "/home/oleg/.local/bin/docker-compose", line 7, in <module>
    from compose.cli.main import main
  File "/home/oleg/.local/lib/python2.7/site-packages/compose/cli/main.py", line 17, in <module>
    import docker
  File "/home/oleg/.local/lib/python2.7/site-packages/docker/__init__.py", line 2, in <module>
    from .api import APIClient
  File "/home/oleg/.local/lib/python2.7/site-packages/docker/api/__init__.py", line 2, in <module>
    from .client import APIClient
  File "/home/oleg/.local/lib/python2.7/site-packages/docker/api/client.py", line 10, in <module>
    from .build import BuildApiMixin
  File "/home/oleg/.local/lib/python2.7/site-packages/docker/api/build.py", line 6, in <module>
    from .. import auth
  File "/home/oleg/.local/lib/python2.7/site-packages/docker/auth.py", line 9, in <module>
    from .utils import config
  File "/home/oleg/.local/lib/python2.7/site-packages/docker/utils/__init__.py", line 3, in <module>
    from .decorators import check_resource, minimum_version, update_headers
  File "/home/oleg/.local/lib/python2.7/site-packages/docker/utils/decorators.py", line 4, in <module>
    from . import utils
  File "/home/oleg/.local/lib/python2.7/site-packages/docker/utils/utils.py", line 13, in <module>
    from .. import tls
  File "/home/oleg/.local/lib/python2.7/site-packages/docker/tls.py", line 5, in <module>
    from .transport import SSLAdapter
  File "/home/oleg/.local/lib/python2.7/site-packages/docker/transport/__init__.py", line 3, in <module>
    from .ssladapter import SSLAdapter
  File "/home/oleg/.local/lib/python2.7/site-packages/docker/transport/ssladapter.py", line 21, in <module>
    from backports.ssl_match_hostname import match_hostname
ImportError: No module named ssl_match_hostname

```

also see:
https://github.com/hasura/graphql-engine/issues/4468

**Comment by dinyadin** [comment]
@ORESoftware : I think your docker-compose is not installed properly. Can you please check this link "https://docs.docker.com/compose/install/" and depending upon the OS install the docker-compose module.
I would suggest to follow each and every step properly.
Kindly let me know if there is any issue while installation.
