### ISSUE TITLE
Unable to deploy with docker-compose to ACI

### ISSUE THREAD

**Issue by JorTurFer** [docker/compose#7565]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 471142C6-D7FC-4141-8495-387A49CCA664/20200628174539

### Expected behavior
Following [this doc](https://docs.docker.com/engine/context/aci-integration/), It should be possible to deploy multiple containers to Azure Container Instances using docker compose.
### Actual behavior
When I try to deploy a simple docker-compose file I get an error with this trace:
```
PS C:\Users\jorge> docker-compose -f .\compose.yml up
Traceback (most recent call last):
  File "site-packages\docker\context\context.py", line 81, in _load_meta
KeyError: 'SkipTLSVerify'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "docker-compose", line 6, in <module>
  File "compose\cli\main.py", line 72, in main
  File "compose\cli\main.py", line 125, in perform_command
  File "compose\cli\command.py", line 76, in project_from_options
  File "compose\cli\command.py", line 142, in get_project
  File "compose\cli\docker_client.py", line 47, in get_client
  File "compose\cli\docker_client.py", line 143, in docker_client
  File "site-packages\docker\context\api.py", line 130, in get_current_context
  File "site-packages\docker\context\api.py", line 95, in get_context
  File "site-packages\docker\context\context.py", line 62, in load_context
  File "site-packages\docker\context\context.py", line 85, in _load_meta
Exception: Detected corrupted meta file for
                        context myacicontext : 'SkipTLSVerify'
[7232] Failed to execute script docker-compose
```
### Information

  - Windows Version: Windows 10 Home 2004
  - Docker Desktop Version: 2.3.2.0 (46268) Edge
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No

### Steps to reproduce the behavior

  1. Install the latest version of the edge channel and configure the context to use Azure Container Instances
  2. Create a docker-compose.yml file like this:
```yml
version: '3.4'

services:
  web:    
    image: nginx
    ports:
    - 80:80
```
  3. Try to deploy it using docker-compose

**Comment by JorTurFer** [comment]
Thanks @StefanScherer ! 
Now it works
