### ISSUE TITLE
ImportError: cannot import name ReadTimeout

### ISSUE THREAD

**Issue by bruciebruce** [docker/compose#7567]
## docker-compose is broken on Ubuntu 18.04

I have been using docker-compose for a couple of weeks without issues.  I must have installed something recently that has broken it.   I cannot even retrieve the version number.  I am forced to use Python 2.7 because I am testing an old application that requires 2.7

$ docker-compose -V

Traceback (most recent call last):
  File "/usr/bin/docker-compose", line 11, in <module>
    load_entry_point('docker-compose==1.17.1', 'console_scripts', 'docker-compose')()
  File "/home/bruce/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/bruce/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2852, in load_entry_point
    return ep.load()
  File "/home/bruce/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2443, in load
    return self.resolve()
  File "/home/bruce/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python2.7/dist-packages/compose/cli/main.py", line 17, in <module>
    from . import errors
  File "/usr/lib/python2.7/dist-packages/compose/cli/errors.py", line 13, in <module>
    from requests.exceptions import ReadTimeout
ImportError: cannot import name ReadTimeout

**Here is my version of requests**
```
$ pip2 list | grep requests
requests (2.22.0)

```
**OS = Ubuntu 18.04**

Thanking you in advance.

**Comment by bruciebruce** [comment]
Here is my docker-compose file:

#!/usr/bin/python
#EASY-INSTALL-ENTRY-SCRIPT: docker-compose==1.17.1,console_scripts,docker-compose
__requires__ = docker-compose==1.17.1
import re
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(
        load_entry_point('docker-compose==1.17.1', 'console_scripts', 'docker-compose')()
    )

**Comment by bruciebruce** [comment]
Installed a different version instead.
