### ISSUE TITLE
NameError: name 'NpipeHTTPAdapter' is not defined

### ISSUE THREAD

**Issue by dominikbraun** [docker/compose#7609]
This is a development-related issue.

When I run `python compose up` in the project root, the following error occurs:

<details>
<summary>NameError: name 'NpipeHTTPAdapter' is not defined</summary>

Stack Trace:

```shell script
Traceback (most recent call last):
  File "C:\Users\domin\AppData\Local\Programs\Python\Python38\lib\site-packages\docker-4.2.2-py3.8.egg\docker\api\client.py", line 154, in __init__
    self._custom_adapter = NpipeHTTPAdapter(
NameError: name 'NpipeHTTPAdapter' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\domin\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\domin\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "compose\__main__.py", line 3, in <module>
    main()
  File "c:\projects\compose\compose\cli\main.py", line 68, in main
    command()
  File "c:\projects\compose\compose\cli\main.py", line 121, in perform_command
    project = project_from_options('.', options)
  File "c:\projects\compose\compose\cli\command.py", line 61, in project_from_options
    return get_project(
  File "c:\projects\compose\compose\cli\command.py", line 136, in get_project
    client = get_client(
  File "c:\projects\compose\compose\cli\docker_client.py", line 41, in get_client
    client = docker_client(
  File "c:\projects\compose\compose\cli\docker_client.py", line 170, in docker_client
    client = APIClient(**kwargs)
  File "C:\Users\domin\AppData\Local\Programs\Python\Python38\lib\site-packages\docker-4.2.2-py3.8.egg\docker\api\client.py", line 158, in __init__
    raise DockerException(
docker.errors.DockerException: Install pypiwin32 package to enable npipe:// support
```
</details>

This led me to the conclusion that `pypiwin32` is missing. However, running `pip install pypiwin32` produces the following output:

```shell script
Requirement already satisfied: pypiwin32 in c:\users\domin\appdata\local\programs\python\python38\lib\site-packages\pypiwin32-223-py3.8.egg (223)
Requirement already satisfied: pywin32>=223 in c:\users\domin\appdata\local\programs\python\python38\lib\site-packages\pywin32-228-py3.8-win-amd64.egg (from pypiwin32) (228)
```

Any ideas how to fix that?

**Comment by dominikbraun** [comment]
This did the trick:

```
$ pip uninstall pywin32
$ pip install -Iv pywin32==227
```

Note that the package here is `pywin32`, not `pypiwin32`.
