### ISSUE TITLE
Connection broken: IncompleteRead

### ISSUE THREAD

**Issue by dayrim** [docker/compose#7630]
## Description of the issue

Receiving an error while running a docker compose command inside a CI/CD pipeline hosted on bitbucket. Works locally but not in a CI/CD pipeline that is using latest docker/compose image from docker hub. The error appears during a specific Dockerfile step which is running a NodeJS script for building react application (react-scripts build). 

## Context information (for bug reports)

**Output of `docker-compose version`**
```
docker-compose version 1.26.2, build eefe0d3
docker-py version: 4.2.2
CPython version: 3.7.7
OpenSSL version: OpenSSL 1.1.1g  21 Apr 2020
```

**Output of `docker version`**
```
Client: Docker Engine - Community
 Version:           19.03.8
 API version:       1.39 (downgraded from 1.40)
 Go version:        go1.12.17
 Git commit:        afacb8b7f0
 Built:             Wed Mar 11 01:22:56 2020
 OS/Arch:           linux/amd64
 Experimental:      false
Server: Docker Engine - Community
 Engine:
  Version:          18.09.1
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.6
  Git commit:       4c52b90
  Built:            Wed Jan  9 19:41:57 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

**Output of `docker-compose config`**
(Make sure to add the relevant `-f` and other flags)
```
services:
  web-legion:
    build:
      args:
        NODE_ENV: production
      context: /opt/atlassian/pipelines/agent/build/apps/web-legion
      dockerfile: Dockerfile
    image: ftwopen/web-legion:0.1.10
    labels:
      kompose.service.expose: "true"
      kompose.service.type: loadbalancer
    ports:
    - 80:80/tcp
version: '3.0'
```

### Observed result
Received an error while running react-scripts build step.

### Expected result
Proceed to next step of Dockerfile build order. 

### Stacktrace / full error message

```
Step 11/11 : RUN yarn run build
 ---> Running in 04312ffc1a3f
yarn run v1.22.4
$ react-scripts build
Creating an optimized production build...
[52] Failed to execute script docker-compose
Traceback (most recent call last):
  File "http/client.py", line 554, in _get_chunk_left
  File "http/client.py", line 521, in _read_next_chunk_size
ValueError: invalid literal for int() with base 16: b''
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "http/client.py", line 586, in _readinto_chunked
  File "http/client.py", line 556, in _get_chunk_left
http.client.IncompleteRead: IncompleteRead(0 bytes read)
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "site-packages/urllib3/response.py", line 437, in _error_catcher
  File "site-packages/urllib3/response.py", line 519, in read
  File "http/client.py", line 457, in read
  File "http/client.py", line 491, in readinto
  File "http/client.py", line 602, in _readinto_chunked
http.client.IncompleteRead: IncompleteRead(0 bytes read)
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "bin/docker-compose", line 6, in <module>
  File "compose/cli/main.py", line 72, in main
  File "compose/cli/main.py", line 128, in perform_command
  File "compose/cli/main.py", line 304, in build
  File "compose/project.py", line 403, in build
  File "compose/project.py", line 385, in build_service
  File "compose/service.py", line 1110, in build
  File "compose/progress_stream.py", line 25, in stream_output
  File "compose/utils.py", line 61, in split_buffer
  File "compose/utils.py", line 37, in stream_as_text
  File "site-packages/docker/api/client.py", line 345, in _stream_helper
  File "site-packages/urllib3/response.py", line 541, in read
  File "contextlib.py", line 130, in __exit__
  File "site-packages/urllib3/response.py", line 455, in _error_catcher
urllib3.exceptions.ProtocolError: ('Connection broken: IncompleteRead(0 bytes read)', IncompleteRead(0 bytes read))
```

## Additional information

Running the latest docker/compose image. Linux/amd64. https://hub.docker.com/layers/docker/compose/latest/images/sha256-b60a020c0f68047b353a4a747f27f5e5ddb17116b7b018762edfb6f7a6439a82?context=explore

Related: https://github.com/docker/compose/issues/3387

**Comment by mdczaplicki** [comment]
Same here in bitbucket pipelines.

**Comment by Madvinking** [comment]
same issue with jenkins pipeline.
ubuntu xenial
docker-compose version 1.27.4
Docker version 19.03.13

**Comment by ivictbor** [comment]
Able to reproduce constantly when I change

```
DOCKER_HOST=ssh://
docker-compose xxx build
```
To:

```
DOCKER_HOST=ssh://
docker-compose xxx build --parallel
```

**Comment by mdczaplicki** [comment]
> Able to reproduce constantly when I change
> 
> ```
> DOCKER_HOST=ssh://
> docker-compose xxx build
> ```
> 
> To:
> 
> ```
> DOCKER_HOST=ssh://
> docker-compose xxx build --parallel
> ```

Check out your RAM usage when you run them in parallel.
