### ISSUE TITLE
docker-compose Import Error cannot import name 'ImageNotFound' from 'docker.errors'

### ISSUE THREAD

**Issue by GitHubprajwal** [docker/compose#7631]
## Description of the issue
i have installed docker-compose with 
**Output of `pip3 install docker-compose`**
```
Installing collected packages: docker-compose
Successfully installed docker-compose-1.26.2
```
but if i run `docker-compose -f compose.yml up -d` 
i got following error :-
```
Traceback (most recent call last):
  File "/usr/local/bin/docker-compose", line 5, in <module>
    from compose.cli.main import main
  File "/usr/local/lib/python3.7/dist-packages/compose/cli/main.py", line 35, in <module>
    from ..project import get_image_digests
  File "/usr/local/lib/python3.7/dist-packages/compose/project.py", line 14, in <module>
    from docker.errors import ImageNotFound
ImportError: cannot import name 'ImageNotFound' from 'docker.errors' (/usr/local/lib/python3.7/dist-packages/docker/errors.py)
```
**Output of `docker-compose version`**
```
Traceback (most recent call last):
  File "/usr/local/bin/docker-compose", line 5, in <module>
    from compose.cli.main import main
  File "/usr/local/lib/python3.7/dist-packages/compose/cli/main.py", line 35, in <module>
    from ..project import get_image_digests
  File "/usr/local/lib/python3.7/dist-packages/compose/project.py", line 14, in <module>
    from docker.errors import ImageNotFound
ImportError: cannot import name 'ImageNotFound' from 'docker.errors' (/usr/local/lib/python3.7/dist-packages/docker/errors.py)
```

**Output of `docker version`**
```
Docker version 19.03.12, build 48a66213fe
```

**Output of `docker-compose config`**
(Make sure to add the relevant `-f` and other flags)
```
Traceback (most recent call last):
  File "/usr/local/bin/docker-compose", line 5, in <module>
    from compose.cli.main import main
  File "/usr/local/lib/python3.7/dist-packages/compose/cli/main.py", line 35, in <module>
    from ..project import get_image_digests
  File "/usr/local/lib/python3.7/dist-packages/compose/project.py", line 14, in <module>
    from docker.errors import ImageNotFound
ImportError: cannot import name 'ImageNotFound' from 'docker.errors' (/usr/local/lib/python3.7/dist-packages/docker/errors.py)
```

## Steps to reproduce the issue

1. Install docker compose using pip
2. create .env file with variable in VARIABLE=variable format and in compose call variable with $VARIABLE 
3. run docker-compose -f compose.yml up -d

### Observed result
Traceback (most recent call last):
  File "/usr/local/bin/docker-compose", line 5, in <module>
    from compose.cli.main import main
  File "/usr/local/lib/python3.7/dist-packages/compose/cli/main.py", line 35, in <module>
    from ..project import get_image_digests
  File "/usr/local/lib/python3.7/dist-packages/compose/project.py", line 14, in <module>
    from docker.errors import ImageNotFound
ImportError: cannot import name 'ImageNotFound' from 'docker.errors' (/usr/local/lib/python3.7/dist-packages/docker/errors.py)

### Expected result
container should startup

### Stacktrace / full error message

```
Traceback (most recent call last):
  File "/usr/local/bin/docker-compose", line 5, in <module>
    from compose.cli.main import main
  File "/usr/local/lib/python3.7/dist-packages/compose/cli/main.py", line 35, in <module>
    from ..project import get_image_digests
  File "/usr/local/lib/python3.7/dist-packages/compose/project.py", line 14, in <module>
    from docker.errors import ImageNotFound
ImportError: cannot import name 'ImageNotFound' from 'docker.errors' (/usr/local/lib/python3.7/dist-packages/docker/errors.py)

```

## Additional information

OS version / distribution, `docker-compose` install method, etc.
Debian10 / buster
docker-compose is installed using pip3

**Comment by hardcoreslacker** [comment]
I had the same problem on a fresh install of Ubuntu 20.04. I was running: `apt-get -y update && apt-get install -y docker.io python3 python3-pip docker && apt-get -y upgrade` and then `pip3 install docker-compose`

I solved the problem on my box by removing docker (`apt-get -y remove docker`) and re-installing docker-compose. Similarly, if I skipped installing the docker package (while still installing docker.io) everything was fine.

**Comment by shpatrickguo** [comment]
I ran into the same issue after doing ```pip install docker-compose```.
My ```docker-py/errors.py``` file didn't have anything after ```class NullResource(DockerException, ValueError):``` on line 121 in https://github.com/docker/docker-py/blob/master/docker/errors.py.
I just copied and pasted everything in the github file above and it solved the issue.
