### ISSUE TITLE
JSON Schema Not Found

### ISSUE THREAD

**Issue by 1995parham** [docker/compose#7641]
###  Description of the issue
After issuing the following command:

```
docker-compose config
```

I get the exception that I have attached.

## Context information (for bug reports)

**Output of `docker-compose version`**
```
docker-compose version 1.26.2, build unknown
docker-py version: 4.2.2
CPython version: 3.8.5
OpenSSL version: OpenSSL 1.1.1g  21 Apr 2020
```

**Output of `docker version`**
```
Client: Docker Engine - Community
 Version:           19.03.12
 API version:       1.40
 Go version:        go1.13.10
 Git commit:        48a66213fe
 Built:             Mon Jun 22 15:45:44 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.12
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.10
  Git commit:       48a66213fe
  Built:            Mon Jun 22 15:44:15 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

```

**Output of `docker-compose config`**
```
Traceback (most recent call last):
  File "/home/linuxbrew/.linuxbrew/Cellar/docker-compose/1.26.2/libexec/lib/python3.8/site-packages/jsonschema/validators.py", line 774, in resolve_from_url
    document = self.store[url]
  File "/home/linuxbrew/.linuxbrew/Cellar/docker-compose/1.26.2/libexec/lib/python3.8/site-packages/jsonschema/_utils.py", line 22, in __getitem__
    return self.store[self.normalize(uri)]
KeyError: 'file:///home/linuxbrew/.linuxbrew/Cellar/docker-compose/1.26.2/libexec/lib/python3.8/site-packages/compose/config/config_schema_v3.2.json'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/linuxbrew/.linuxbrew/Cellar/docker-compose/1.26.2/libexec/lib/python3.8/site-packages/jsonschema/validators.py", line 777, in resolve_from_url
    document = self.resolve_remote(url)
  File "/home/linuxbrew/.linuxbrew/Cellar/docker-compose/1.26.2/libexec/lib/python3.8/site-packages/jsonschema/validators.py", line 863, in resolve_remote
    with urlopen(uri) as url:
  File "/home/linuxbrew/.linuxbrew/opt/python@3.8/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/home/linuxbrew/.linuxbrew/opt/python@3.8/lib/python3.8/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/home/linuxbrew/.linuxbrew/opt/python@3.8/lib/python3.8/urllib/request.py", line 536, in _open
    result = self._call_chain(self.handle_open, 'default',
  File "/home/linuxbrew/.linuxbrew/opt/python@3.8/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/home/linuxbrew/.linuxbrew/opt/python@3.8/lib/python3.8/urllib/request.py", line 806, in <lambda>
    meth(r, proxy, type))
  File "/home/linuxbrew/.linuxbrew/opt/python@3.8/lib/python3.8/urllib/request.py", line 834, in proxy_open
    return self.parent.open(req, timeout=req.timeout)
  File "/home/linuxbrew/.linuxbrew/opt/python@3.8/lib/python3.8/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/home/linuxbrew/.linuxbrew/opt/python@3.8/lib/python3.8/urllib/request.py", line 640, in http_response
    response = self.parent.error(
  File "/home/linuxbrew/.linuxbrew/opt/python@3.8/lib/python3.8/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/home/linuxbrew/.linuxbrew/opt/python@3.8/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/home/linuxbrew/.linuxbrew/opt/python@3.8/lib/python3.8/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 400: Bad Request

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/linuxbrew/.linuxbrew/bin/docker-compose", line 33, in <module>
    sys.exit(load_entry_point('docker-compose==1.26.2', 'console_scripts', 'docker-compose')())
  File "/home/linuxbrew/.linuxbrew/Cellar/docker-compose/1.26.2/libexec/lib/python3.8/site-packages/compose/cli/main.py", line 72, in main
    command()
  File "/home/linuxbrew/.linuxbrew/Cellar/docker-compose/1.26.2/libexec/lib/python3.8/site-packages/compose/cli/main.py", line 122, in perform_command
    handler(command, command_options)
  File "/home/linuxbrew/.linuxbrew/Cellar/docker-compose/1.26.2/libexec/lib/python3.8/site-packages/compose/cli/main.py", line 326, in config
    compose_config = get_config_from_options('.', self.toplevel_options, additional_options)
  File "/home/linuxbrew/.linuxbrew/Cellar/docker-compose/1.26.2/libexec/lib/python3.8/site-packages/compose/cli/command.py", line 104, in get_config_from_options
    return config.load(
  File "/home/linuxbrew/.linuxbrew/Cellar/docker-compose/1.26.2/libexec/lib/python3.8/site-packages/compose/config/config.py", line 392, in load
    processed_files = [
  File "/home/linuxbrew/.linuxbrew/Cellar/docker-compose/1.26.2/libexec/lib/python3.8/site-packages/compose/config/config.py", line 393, in <listcomp>
    process_config_file(config_file, config_details.environment, interpolate=interpolate)
  File "/home/linuxbrew/.linuxbrew/Cellar/docker-compose/1.26.2/libexec/lib/python3.8/site-packages/compose/config/config.py", line 581, in process_config_file
    validate_against_config_schema(config_file)
  File "/home/linuxbrew/.linuxbrew/Cellar/docker-compose/1.26.2/libexec/lib/python3.8/site-packages/compose/config/validation.py", line 449, in validate_against_config_schema
    handle_errors(
  File "/home/linuxbrew/.linuxbrew/Cellar/docker-compose/1.26.2/libexec/lib/python3.8/site-packages/compose/config/validation.py", line 509, in handle_errors
    errors = list(sorted(errors, key=str))
  File "/home/linuxbrew/.linuxbrew/Cellar/docker-compose/1.26.2/libexec/lib/python3.8/site-packages/jsonschema/validators.py", line 328, in iter_errors
    for error in errors:
  File "/home/linuxbrew/.linuxbrew/Cellar/docker-compose/1.26.2/libexec/lib/python3.8/site-packages/jsonschema/_validators.py", line 282, in properties
    for error in validator.descend(
  File "/home/linuxbrew/.linuxbrew/Cellar/docker-compose/1.26.2/libexec/lib/python3.8/site-packages/jsonschema/validators.py", line 344, in descend
    for error in self.iter_errors(instance, schema):
  File "/home/linuxbrew/.linuxbrew/Cellar/docker-compose/1.26.2/libexec/lib/python3.8/site-packages/jsonschema/validators.py", line 328, in iter_errors
    for error in errors:
  File "/home/linuxbrew/.linuxbrew/Cellar/docker-compose/1.26.2/libexec/lib/python3.8/site-packages/jsonschema/_validators.py", line 23, in patternProperties
    for error in validator.descend(
  File "/home/linuxbrew/.linuxbrew/Cellar/docker-compose/1.26.2/libexec/lib/python3.8/site-packages/jsonschema/validators.py", line 344, in descend
    for error in self.iter_errors(instance, schema):
  File "/home/linuxbrew/.linuxbrew/Cellar/docker-compose/1.26.2/libexec/lib/python3.8/site-packages/jsonschema/validators.py", line 328, in iter_errors
    for error in errors:
  File "/home/linuxbrew/.linuxbrew/Cellar/docker-compose/1.26.2/libexec/lib/python3.8/site-packages/jsonschema/_validators.py", line 259, in ref
    scope, resolved = validator.resolver.resolve(ref)
  File "/home/linuxbrew/.linuxbrew/Cellar/docker-compose/1.26.2/libexec/lib/python3.8/site-packages/jsonschema/validators.py", line 766, in resolve
    return url, self._remote_cache(url)
  File "/home/linuxbrew/.linuxbrew/Cellar/docker-compose/1.26.2/libexec/lib/python3.8/site-packages/jsonschema/validators.py", line 779, in resolve_from_url
    raise exceptions.RefResolutionError(exc)
jsonschema.exceptions.RefResolutionError: HTTP Error 400: Bad Request
```

**Comment by 1995parham** [comment]
I have investigated more, this issue happens because `site-packages/jsonschema/validators.py:774` search for:

```
file:///home/linuxbrew/.linuxbrew/Cellar/docker-compose/1.26.2/libexec/lib/python3.8/site-packages/compose/config/config_schema_v3.2.json
```

but the following URL exists:

```
file:///home/linuxbrew/.linuxbrew/Cellar/docker-compose/1.26.2/libexec/lib/python3.8/site-packages/compose/config/
```

and I can fix the issue by changing the URL with following code at `site-packages/jsonschema/validators.py:774`:

```
document = self.store[url.rsplit('/', 1)[0] + '/']
```

**Comment by 1995parham** [comment]
Personally I think this related to python3.8 but It would be great if I can have your opinions too.
