### ISSUE TITLE
deploy key crash application start with Compose 1.27.0-rc1

### ISSUE THREAD

**Issue by glours** [docker/compose#7671]
## Description of the issue
When running the [`minecraft`](https://github.com/docker/awesome-compose/blob/master/minecraft/docker-compose.yml) sample of [`awesome-compose`](https://github.com/docker/awesome-compose) with Compose `1.27.0-rc1`  we get the following error

```shell
$ docker-compose up --build
WARNING: Some services (minecraft) use the 'deploy' key, which will be ignored. Compose does not support 'deploy' configuration - use `docker stack deploy` to deploy to a swarm.
Traceback (most recent call last):
  File "docker-compose", line 3, in <module>
  File "compose/cli/main.py", line 67, in main
  File "compose/cli/main.py", line 120, in perform_command
  File "compose/cli/command.py", line 70, in project_from_options
  File "compose/cli/command.py", line 144, in get_project
  File "compose/project.py", line 130, in from_config
  File "compose/project.py", line 326, in get_service_scale
TypeError: '<' not supported between instances of 'NoneType' and 'NoneType'
[11029] Failed to execute script docker-compose
```

With the `1.26.2` version of Compose we get also the warning message but the application start. 

## Context information (for bug reports)

**Output of `docker-compose version`**
```
docker-compose version 1.27.0-rc1, build f9228ae4
docker-py version: 4.3.0
CPython version: 3.7.7
OpenSSL version: OpenSSL 1.1.1g  21 Apr 2020
```

**Output of `docker version`**
```
Client: Docker Engine - Community
 Azure integration  0.1.10
 Version:           19.03.12
 API version:       1.40
 Go version:        go1.13.10
 Git commit:        48a66213fe
 Built:             Mon Jun 22 15:41:33 2020
 OS/Arch:           darwin/amd64
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          19.03.12
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.10
  Git commit:       48a66213fe
  Built:            Mon Jun 22 15:49:27 2020
  OS/Arch:          linux/amd64
  Experimental:     true
 containerd:
  Version:          v1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Output of `docker-compose config`**
(Make sure to add the relevant `-f` and other flags)
```
WARNING: Some services (minecraft) use the 'deploy' key, which will be ignored. Compose does not support 'deploy' configuration - use `docker stack deploy` to deploy to a swarm.
services:
  minecraft:
    deploy:
      resources:
        limits:
          memory: 1.5G
    environment:
      EULA: "TRUE"
    image: itzg/minecraft-server
    ports:
    - published: 25565
      target: 25565
    volumes:
    - /Users/gulliaumelours/minecraft_data:/data:rw
version: '3'
```

## Steps to reproduce the issue

1. `compose.yaml` with `deploy` section
2. `docker-compose up`

### Observed result
Compose application didn't start

### Expected result
Compose application should start and print the warning about ignoring the `deploy` key.

### Stacktrace / full error message

```
WARNING: Some services (minecraft) use the 'deploy' key, which will be ignored. Compose does not support 'deploy' configuration - use `docker stack deploy` to deploy to a swarm.
Traceback (most recent call last):
  File "docker-compose", line 3, in <module>
  File "compose/cli/main.py", line 67, in main
  File "compose/cli/main.py", line 120, in perform_command
  File "compose/cli/command.py", line 70, in project_from_options
  File "compose/cli/command.py", line 144, in get_project
  File "compose/project.py", line 130, in from_config
  File "compose/project.py", line 326, in get_service_scale
TypeError: '<' not supported between instances of 'NoneType' and 'NoneType'
[11029] Failed to execute script docker-compose
```

## Additional information

docker-compose static binary on macOS Catalina 10.15.6

**Comment by ulyssessouza** [comment]
Closed by: https://github.com/docker/compose/pull/7676

**Comment by ulyssessouza** [comment]
Closed by https://github.com/docker/compose/pull/7676
