### ISSUE TITLE
Not able to install docker-compose on redhat 7 of ppc64le arch type.

### ISSUE THREAD

**Issue by venkat44488** [docker/compose#7687]
## Description of the issue
**As I am trying to install docker-compose on redhat 7 power9 server its arch type is : ppc64le. getting below error Hardware is IBM power9 server**

## Context information (for bug reports)

[root@prh0706A1 software]# pip install docker-compose
Traceback (most recent call last):
  File "/usr/local/bin/pip", line 8, in <module>
    sys.exit(main())
  File "/usr/lib/python2.7/site-packages/pip/_internal/cli/main.py", line 73, in main
    command = create_command(cmd_name, isolated=("--isolated" in cmd_args))
  File "/usr/lib/python2.7/site-packages/pip/_internal/commands/__init__.py", line 104, in create_command
    module = importlib.import_module(module_path)
  File "/usr/lib64/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/usr/lib/python2.7/site-packages/pip/_internal/commands/install.py", line 14, in <module>
    from pip._internal.cache import WheelCache
  File "/usr/lib/python2.7/site-packages/pip/_internal/cache.py", line 15, in <module>
    from pip._internal.utils.temp_dir import TempDirectory, tempdir_kinds
  File "/usr/lib/python2.7/site-packages/pip/_internal/utils/temp_dir.py", line 11, in <module>
    from pip._vendor.six import ensure_text
ImportError: cannot import name ensure_text

**Output of `docker-compose version`**
```
(paste here)
```

**Output of `docker version`**
```
(paste here)
```

**Output of `docker-compose config`**
(Make sure to add the relevant `-f` and other flags)
```
(paste here)
```

## Steps to reproduce the issue

1.
2.
3.

### Stacktrace / full error message

```
(paste here)
```

## Additional information

OS version / distribution, `docker-compose` install method, etc.

**Comment by aiordache** [comment]
Hi @venkat44488. Python2.7 is not supported anymore, please try with Python3.5 or later.
