### ISSUE TITLE
Unknown Exception when using docker-compose with --context

### ISSUE THREAD

**Issue by hellos3b** [docker/compose#7764]
## Description of the issue
Trying to start a docker-compose service using `--context {context}` set on a remote host fails with `ERROR: Unknown exception: q must be exactly 160, 224, or 256 bits long`. Worked fine before Docker Desktop updated this morning

## Context information (for bug reports)

**Output of `docker-compose version`**
```
docker-compose version 1.27.2, build 18f557f9
docker-py version: 4.3.1
CPython version: 3.7.7
OpenSSL version: OpenSSL 1.1.1g  21 Apr 2020
```

**Output of `docker version`**
```
Client: Docker Engine - Community
 Azure integration  0.1.15
 Version:           19.03.12
 API version:       1.40
 Go version:        go1.13.10
 Git commit:        48a66213fe
 Built:             Mon Jun 22 15:41:33 2020
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.12
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.10
  Git commit:       48a66213fe
  Built:            Mon Jun 22 15:49:27 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Output of `docker-compose config`**
```
services:
  hello_world:
    command:
    - /bin/echo
    - Hello world
    image: ubuntu
version: '2'
```

## Steps to reproduce the issue

1. Add a remote context: `docker context create SomeName --docker "host=ssh://user@host"`
2. Using any docker-compose.yml file, run `docker-compose --context SomeName up`

### Observed result
docker-compose errors out immediately

### Expected result
The normal docker-compose build steps should occur, and end with "app HelloWorld running"

### Stacktrace / full error message
```
ERROR: Unknown exception: q must be exactly 160, 224, or 256 bits long
ERROR: Traceback (most recent call last):
ERROR:   File "site-packages/paramiko/transport.py", line 2109, in run
ERROR:   File "site-packages/paramiko/auth_handler.py", line 298, in _parse_service_accept
ERROR:   File "site-packages/paramiko/dsskey.py", line 116, in sign_ssh_data
ERROR:   File "site-packages/cryptography/hazmat/primitives/asymmetric/dsa.py", line 244, in private_key
ERROR:   File "site-packages/cryptography/hazmat/backends/openssl/backend.py", line 772, in load_dsa_private_numbers
ERROR:   File "site-packages/cryptography/hazmat/primitives/asymmetric/dsa.py", line 144, in _check_dsa_private_numbers
ERROR:   File "site-packages/cryptography/hazmat/primitives/asymmetric/dsa.py", line 136, in _check_dsa_parameters
ERROR: ValueError: q must be exactly 160, 224, or 256 bits long
ERROR: 
Traceback (most recent call last):
  File "docker-compose", line 3, in <module>
  File "compose/cli/main.py", line 67, in main
  File "compose/cli/main.py", line 123, in perform_command
  File "compose/cli/command.py", line 69, in project_from_options
  File "compose/cli/command.py", line 132, in get_project
  File "compose/cli/docker_client.py", line 43, in get_client
  File "compose/cli/docker_client.py", line 170, in docker_client
  File "site-packages/docker/api/client.py", line 164, in __init__
  File "site-packages/docker/transport/sshconn.py", line 113, in __init__
  File "site-packages/docker/transport/sshconn.py", line 121, in _connect
  File "site-packages/paramiko/client.py", line 446, in connect
  File "site-packages/paramiko/client.py", line 680, in _auth
  File "site-packages/paramiko/transport.py", line 1580, in auth_publickey
  File "site-packages/paramiko/auth_handler.py", line 236, in wait_for_response
  File "site-packages/paramiko/transport.py", line 2109, in run
  File "site-packages/paramiko/auth_handler.py", line 298, in _parse_service_accept
  File "site-packages/paramiko/dsskey.py", line 116, in sign_ssh_data
  File "site-packages/cryptography/hazmat/primitives/asymmetric/dsa.py", line 244, in private_key
  File "site-packages/cryptography/hazmat/backends/openssl/backend.py", line 772, in load_dsa_private_numbers
  File "site-packages/cryptography/hazmat/primitives/asymmetric/dsa.py", line 144, in _check_dsa_private_numbers
  File "site-packages/cryptography/hazmat/primitives/asymmetric/dsa.py", line 136, in _check_dsa_parameters
ValueError: q must be exactly 160, 224, or 256 bits long
[46220] Failed to execute script docker-compose
```

## Additional information

OS: MacOS Mojave 10.14.6
docker-compose installed via Docker Desktop installer
Docker Desktop was updated to 2.3.0.5 this morning, the command worked yesterday

Also, `docker --context s3bby container ls` works as expected

**Comment by hellos3b** [comment]
I was able to find a fix for this. It was an issue with my `~/.ssh/config` for my domain setting, where I had `Host my-domain` instead of `Host domain my-domain.com`. Don't know why it worked before.

[This comment on the Paramiko repo](https://github.com/paramiko/paramiko/issues/750#issuecomment-634540604) is what made me check the config
