### ISSUE TITLE
`docker-compose` unexpectly ran docker-credential-glcoud

### ISSUE THREAD

**Issue by shockw4ver** [docker/compose#7777]
**Question**:
How to disable docker-credential-gcloud?

**Description**:
As I ran `docker-compose`, a error reported that CANNOT find command `docker-credential-gcloud`.
Then [I ask the container's team](https://github.com/Requarks/wiki/issues/2468) if this container requires google cloud sdk, but they explained maybe this is a environment problem.
But I never do things about `docker-credential-gcloud`, so how can I disable this using?

**Output**:
```
[31 ms] Start: Resolving remote
[33 ms] Setting up container for folder or workspace: /Users/zhangyongchao/selfspace/wiki.js/wiki

[34 ms] Start: Check Docker is running
[34 ms] Start: Run: docker info
[147 ms] Start: Run: docker-compose version --short
[596 ms] Start: Run: docker ps -q -a --filter label=com.docker.compose.project=containers --filter label=com.docker.compose.service=wiki
[640 ms] Start: Run: docker-compose -f /Users/zhangyongchao/selfspace/wiki.js/wiki/dev/containers/docker-compose.yml config --services
[1097 ms] db
adminer
wiki
[1097 ms] 
[1098 ms] Start: Run: docker events --format {{json .}} --filter status=start
[1103 ms] Start: Run: docker-compose --project-name containers -f /Users/zhangyongchao/selfspace/wiki.js/wiki/dev/containers/docker-compose.yml up -d --build
Building wiki
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/bin/docker-compose", line 10, in <module>
    sys.exit(main())
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/compose/cli/main.py", line 67, in main
    command()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/compose/cli/main.py", line 126, in perform_command
    handler(command, command_options)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/compose/cli/main.py", line 1070, in up
    to_attach = up(False)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/compose/cli/main.py", line 1066, in up
    cli=native_builder,
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/compose/project.py", line 615, in up
    svc.ensure_image_exists(do_build=do_build, silent=silent, cli=cli)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/compose/service.py", line 346, in ensure_image_exists
    self.build(cli=cli)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/compose/service.py", line 1125, in build
    platform=self.platform,
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/docker/api/build.py", line 261, in build
    self._set_auth_headers(headers)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/docker/api/build.py", line 308, in _set_auth_headers
    auth_data = self._auth_configs.get_all_credentials()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/docker/auth.py", line 311, in get_all_credentials
    reg, store_name
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/docker/auth.py", line 262, in _resolve_authconfig_credstore
    store = self._get_store_instance(credstore_name)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/docker/auth.py", line 287, in _get_store_instance
    name, environment=self._credstore_env
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/docker/credentials/store.py", line 25, in __init__
    self.program
docker.credentials.errors.InitializationError: docker-credential-gcloud not installed or not available in PATH
[2419 ms] Command failed: docker-compose --project-name containers -f /Users/zhangyongchao/selfspace/wiki.js/wiki/dev/containers/docker-compose.yml up -d --build
```

**Comment by iongion** [comment]
Using this on ubuntu 20.10
```
docker-compose --version
docker-compose version 1.27.4, build 40524192
```

Getting the above issue

```
Traceback (most recent call last):
  File "bin/docker-compose", line 3, in <module>
  File "compose/cli/main.py", line 67, in main
  File "compose/cli/main.py", line 126, in perform_command
  File "compose/cli/main.py", line 302, in build
  File "compose/project.py", line 468, in build
  File "compose/project.py", line 450, in build_service
  File "compose/service.py", line 1125, in build
  File "docker/api/build.py", line 261, in build
  File "docker/api/build.py", line 308, in _set_auth_headers
  File "docker/auth.py", line 311, in get_all_credentials
  File "docker/auth.py", line 262, in _resolve_authconfig_credstore
  File "docker/auth.py", line 287, in _get_store_instance
  File "docker/credentials/store.py", line 25, in __init__
docker.credentials.errors.InitializationError: docker-credential-gcloud not installed or not available in PATH
```

Any solution ?

**Comment by shockw4ver** [comment]
@iongion thx I'll try this！

**Comment by tymons** [comment]
Why it is completed? I've similar error with VS Code dev-container resulting with following error:

> Traceback (most recent call last):
>   File "docker-compose", line 3, in <module>
>   File "compose/cli/main.py", line 81, in main
>   File "compose/cli/main.py", line 203, in perform_command
>   File "compose/metrics/decorator.py", line 18, in wrapper
>   File "compose/cli/main.py", line 849, in pull
>   File "compose/project.py", line 757, in pull
>   File "compose/project.py", line 807, in parallel_pull
>   File "compose/parallel.py", line 108, in parallel_execute
>   File "compose/parallel.py", line 206, in producer
>   File "compose/project.py", line 789, in pull_service
>   File "compose/service.py", line 1218, in _do_pull
>   File "docker/api/image.py", line 411, in pull
>   File "docker/auth.py", line 48, in get_config_header
>   File "docker/auth.py", line 324, in resolve_authconfig
>   File "docker/auth.py", line 235, in resolve_authconfig
>   File "docker/auth.py", line 262, in _resolve_authconfig_credstore
>   File "docker/auth.py", line 287, in _get_store_instance
>   File "docker/credentials/store.py", line 25, in __init__
> docker.credentials.errors.InitializationError: docker-credential-dev-containers-eaff0e0e-3137-418e-8b36-dc61dddcce3c not installed or not available in PATH
> [54040] Failed to execute script docker-compose

my `config.json` (probably created by dev-container) is the following:

`
{
	"auths": {
		"registry.gitlab.com": {
			"auth": "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
		}
	},
	"credsStore": "dev-containers-eaff0e0e-3137-418e-8b36-dc61dddcce3c"
}
`
Maybe we should provide some clarification on that?

Thanks
