### ISSUE TITLE
One more bug

### ISSUE THREAD

**Issue by hakuno** [docker/compose#7852]
Hey!

Everytime I update the Docker For Windows I get some bad surprise.

The beta channel is buggy. And I guess some bug came to the stable channel recently.

The last message error after I updated:

```
Traceback (most recent call last):
  File "site-packages\docker\api\client.py", line 259, in _raise_for_status
  File "site-packages\requests\models.py", line 941, in raise_for_status
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: http+docker://localnpipe/version

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "site-packages\docker\api\client.py", line 205, in _retrieve_server_version
  File "site-packages\docker\api\daemon.py", line 181, in version
  File "site-packages\docker\api\client.py", line 265, in _result
  File "site-packages\docker\api\client.py", line 261, in _raise_for_status
  File "site-packages\docker\errors.py", line 31, in create_api_error_from_http_exception
docker.errors.APIError: 500 Server Error: Internal Server Error ("b'i/o timeout'")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "docker-compose", line 3, in <module>
  File "compose\cli\main.py", line 67, in main
  File "compose\cli\main.py", line 123, in perform_command
  File "compose\cli\command.py", line 69, in project_from_options
  File "compose\cli\command.py", line 132, in get_project
  File "compose\cli\docker_client.py", line 43, in get_client
  File "compose\cli\docker_client.py", line 170, in docker_client
  File "site-packages\docker\api\client.py", line 188, in __init__
  File "site-packages\docker\api\client.py", line 213, in _retrieve_server_version
docker.errors.DockerException: Error while fetching server API version: 500 Server Error: Internal Server Error ("b'i/o timeout'")
[32872] Failed to execute script docker-compose
```

The version is `2.4.0.0` from `2020-09-28`. Channel: stable.

BTW can I downgrade? 😢

**Comment by leoamrl** [comment]
I'm with the same problem.

**Comment by hakuno** [comment]
I got the edge release like said at https://github.com/docker/for-win/issues/8828

It runs properly with `2.4.1.0` (edge release) against the stable release.

Ps.: some time ago I had to go back to the stable channel because the edge one was broken for me. Now I'm on edge again.

Thanks in advance in somehow.

**Comment by hakuno** [comment]
@leoamrl e aí, goiano. Tudo bem? O beta está funcionando. (The edge release works.) Cheers!

**Comment by wingzero0** [comment]
I getting the similar error after upgrading to 2.4.0.0 too

```
Traceback (most recent call last):
  File "site-packages\docker\api\client.py", line 259, in _raise_for_status
  File "site-packages\requests\models.py", line 941, in raise_for_status
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: http+docker://localnpipe/version

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "site-packages\docker\api\client.py", line 205, in _retrieve_server_version
  File "site-packages\docker\api\daemon.py", line 181, in version
  File "site-packages\docker\api\client.py", line 265, in _result
  File "site-packages\docker\api\client.py", line 261, in _raise_for_status
  File "site-packages\docker\errors.py", line 31, in create_api_error_from_http_exception
docker.errors.APIError: 500 Server Error: Internal Server Error ("b'i/o timeout'")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "docker-compose", line 3, in <module>
  File "compose\cli\main.py", line 67, in main
  File "compose\cli\main.py", line 123, in perform_command
  File "compose\cli\command.py", line 69, in project_from_options
  File "compose\cli\command.py", line 132, in get_project
  File "compose\cli\docker_client.py", line 43, in get_client
  File "compose\cli\docker_client.py", line 170, in docker_client
  File "site-packages\docker\api\client.py", line 188, in __init__
  File "site-packages\docker\api\client.py", line 213, in _retrieve_server_version
docker.errors.DockerException: Error while fetching server API version: 500 Server Error: Internal Server Error ("b'i/o timeout'")
```

**Comment by wingzero0** [comment]
More description about my situation,

I could run container by docker-compose. But it hanged after about 15 mins. Then I could not run any docker command. It showed the i/o timeout message 


> I getting the similar error after upgrading to 2.4.0.0 too
> 
> ```
> Traceback (most recent call last):
>   File "site-packages\docker\api\client.py", line 259, in _raise_for_status
>   File "site-packages\requests\models.py", line 941, in raise_for_status
> requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: http+docker://localnpipe/version
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "site-packages\docker\api\client.py", line 205, in _retrieve_server_version
>   File "site-packages\docker\api\daemon.py", line 181, in version
>   File "site-packages\docker\api\client.py", line 265, in _result
>   File "site-packages\docker\api\client.py", line 261, in _raise_for_status
>   File "site-packages\docker\errors.py", line 31, in create_api_error_from_http_exception
> docker.errors.APIError: 500 Server Error: Internal Server Error ("b'i/o timeout'")
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "docker-compose", line 3, in <module>
>   File "compose\cli\main.py", line 67, in main
>   File "compose\cli\main.py", line 123, in perform_command
>   File "compose\cli\command.py", line 69, in project_from_options
>   File "compose\cli\command.py", line 132, in get_project
>   File "compose\cli\docker_client.py", line 43, in get_client
>   File "compose\cli\docker_client.py", line 170, in docker_client
>   File "site-packages\docker\api\client.py", line 188, in __init__
>   File "site-packages\docker\api\client.py", line 213, in _retrieve_server_version
> docker.errors.DockerException: Error while fetching server API version: 500 Server Error: Internal Server Error ("b'i/o timeout'")
> ```

**Comment by hakuno** [comment]
Weird. My Docker is hanging on pulling image right now.

```
Creating network "hub-dev-rede" with the default driver
Creating volume "hub-dev-database" with default driver
Creating volume "hub-dev_esdata01" with local driver
Pulling messenger (redis:alpine)...
ERROR: Get https://registry-1.docker.io/v2/: dial tcp: lookup registry-1.docker.io on 192.168.65.1:53: read udp 192.168.65.3:46129->192.168.65.1:53: i/o timeout
```

**Comment by elektrovert** [comment]
Getting the same thing here:  
`
Traceback (most recent call last):
  File "site-packages\docker\api\client.py", line 259, in _raise_for_status
  File "site-packages\requests\models.py", line 941, in raise_for_status
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: http://127.0.0.1:2375/version

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "site-packages\docker\api\client.py", line 205, in _retrieve_server_version
  File "site-packages\docker\api\daemon.py", line 181, in version
  File "site-packages\docker\api\client.py", line 265, in _result
  File "site-packages\docker\api\client.py", line 261, in _raise_for_status
  File "site-packages\docker\errors.py", line 31, in create_api_error_from_http_exception
docker.errors.APIError: 500 Server Error: Internal Server Error ("b'i/o timeout'")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "docker-compose", line 3, in <module>
  File "compose\cli\main.py", line 67, in main
  File "compose\cli\main.py", line 123, in perform_command
  File "compose\cli\command.py", line 69, in project_from_options
  File "compose\cli\command.py", line 132, in get_project
  File "compose\cli\docker_client.py", line 43, in get_client
  File "compose\cli\docker_client.py", line 170, in docker_client
  File "site-packages\docker\api\client.py", line 188, in __init__
  File "site-packages\docker\api\client.py", line 213, in _retrieve_server_version
docker.errors.DockerException: Error while fetching server API version: 500 Server Error: Internal Server Error ("b'i/o timeout'")
[41328] Failed to execute script docker-compose
`

**Comment by Elichkoto** [comment]
I'm getting exactly the same errors after having containers up for 30 minutes.
Sometimes even the restart of Docker is not helping.

```
Traceback (most recent call last):
  File "site-packages\docker\api\client.py", line 259, in _raise_for_status
  File "site-packages\requests\models.py", line 941, in raise_for_status
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: http+docker://localnpipe/version

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "site-packages\docker\api\client.py", line 205, in _retrieve_server_version
  File "site-packages\docker\api\daemon.py", line 181, in version
  File "site-packages\docker\api\client.py", line 265, in _result
  File "site-packages\docker\api\client.py", line 261, in _raise_for_status
  File "site-packages\docker\errors.py", line 31, in create_api_error_from_http_exception
docker.errors.APIError: 500 Server Error: Internal Server Error ("b'i/o timeout'")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "docker-compose", line 3, in <module>
  File "compose\cli\main.py", line 67, in main
  File "compose\cli\main.py", line 123, in perform_command
  File "compose\cli\command.py", line 69, in project_from_options
  File "compose\cli\command.py", line 132, in get_project
  File "compose\cli\docker_client.py", line 43, in get_client
  File "compose\cli\docker_client.py", line 170, in docker_client
  File "site-packages\docker\api\client.py", line 188, in __init__
  File "site-packages\docker\api\client.py", line 213, in _retrieve_server_version
docker.errors.DockerException: Error while fetching server API version: 500 Server Error: Internal Server Error ("b'i/o timeout'")
```

Versions:
```
Client: Docker Engine - Community
 Cloud integration  0.1.18
 Version:           19.03.13
 API version:       1.40
 Go version:        go1.13.15
 Git commit:        4484c46d9d
 Built:             Wed Sep 16 17:00:27 2020
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.13
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       4484c46d9d
  Built:            Wed Sep 16 17:07:04 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.3.7
  GitCommit:        8fba4e9a7d01810a393d5d25a3621dc101981175
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

Docker Desktop Community version: 2.4.0.0

Hope it helps.

**Comment by arthurpietruch** [comment]
Go to Docker Preferences, then select "Reset to factory defaults".
Solved the problem for me.

**Comment by Elichkoto** [comment]
> Go to Docker Preferences, then select "Reset to factory defaults".
> Solved the problem for me.

I did, but it happened again afterwards.
The only thing, which is working for me right now, is downgrading to version 2.3.0.2.

**Comment by wingzero0** [comment]
For me, in 2.4.0.0, "Reset to factory defaults" not helping.

I also try to uninstall 2.4.0.0 and reinstall 2.3.0.5, but problem still occurs (hanging).

I wonder if any component was not uninstalled correctly, or problem is related to windows update?

> > Go to Docker Preferences, then select "Reset to factory defaults".
> > Solved the problem for me.
> 
> I did, but it happened again afterwards.
> The only thing, which is working for me right now, is downgrading to version 2.3.0.2.

**Comment by yaruna-chan** [comment]
I also got a bunch of io timeouts when upgrading to 2.4.0.0. 
At first I did reset to factory defaults, which seemed to help for a while... but then the issue started to appear again and then it worked to uninstall it and install 2.3.0.5

**Comment by alligator77** [comment]
same issue

**Comment by prashant71ht** [comment]
@Elichkoto @wingzero0  I got the same error, any workaround?

**Comment by Elichkoto** [comment]
> @Elichkoto @wingzero0 I got the same error, any workaround?

Version 2.3.0.2 is working for me. Hope it helps :)

**Comment by blazestudios23** [comment]
Just updated to 2.5 and got the same issue.

**Comment by maslunde** [comment]
me2

**Comment by peterssond** [comment]
Same problem here.
Channel: Stable
Version: 2.5.0.1 (49550)
Engine: 19.03.13
Compose: 1.27.4

**Comment by Chisonm** [comment]
i am also having the same error
Traceback (most recent call last):
  File "site-packages\docker\api\client.py", line 205, in _retrieve_server_version
  File "site-packages\docker\api\daemon.py", line 181, in version
  File "site-packages\docker\utils\decorators.py", line 46, in inner
  File "site-packages\docker\api\client.py", line 228, in _get
  File "site-packages\requests\sessions.py", line 543, in get
  File "site-packages\requests\sessions.py", line 530, in request
  File "site-packages\requests\sessions.py", line 643, in send
  File "site-packages\requests\adapters.py", line 449, in send
  File "site-packages\urllib3\connectionpool.py", line 677, in urlopen
  File "site-packages\urllib3\connectionpool.py", line 392, in _make_request
  File "http\client.py", line 1244, in request
  File "http\client.py", line 1290, in _send_request
  File "http\client.py", line 1239, in endheaders
  File "http\client.py", line 1026, in _send_output
  File "http\client.py", line 966, in send
  File "site-packages\docker\transport\npipeconn.py", line 32, in connect
  File "site-packages\docker\transport\npipesocket.py", line 23, in wrapped
  File "site-packages\docker\transport\npipesocket.py", line 72, in connect
  File "site-packages\docker\transport\npipesocket.py", line 59, in connect
pywintypes.error: (2, 'CreateFile', 'The system cannot find the file specified.')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "docker-compose", line 3, in <module>
  File "compose\cli\main.py", line 67, in main
  File "compose\cli\main.py", line 123, in perform_command
  File "compose\cli\command.py", line 69, in project_from_options
  File "compose\cli\command.py", line 132, in get_project
  File "compose\cli\docker_client.py", line 43, in get_client
  File "compose\cli\docker_client.py", line 170, in docker_client
  File "site-packages\docker\api\client.py", line 188, in __init__
  File "site-packages\docker\api\client.py", line 213, in _retrieve_server_version
docker.errors.DockerException: Error while fetching server API version: (2, 'CreateFile', 'The system cannot find the file specified.')
[24668] Failed to execute script docker-compose

**Comment by remif25** [comment]
Hi everyone,

I got the same error on a project which work on month ago 

Traceback (most recent call last):
  File "site-packages\docker\api\client.py", line 205, in _retrieve_server_version
  File "site-packages\docker\api\daemon.py", line 181, in version
  File "site-packages\docker\utils\decorators.py", line 46, in inner
  File "site-packages\docker\api\client.py", line 228, in _get
  File "site-packages\requests\sessions.py", line 543, in get
  File "site-packages\requests\sessions.py", line 530, in request
  File "site-packages\requests\sessions.py", line 643, in send
  File "site-packages\requests\adapters.py", line 449, in send
  File "site-packages\urllib3\connectionpool.py", line 677, in urlopen
  File "site-packages\urllib3\connectionpool.py", line 392, in _make_request
  File "http\client.py", line 1244, in request
  File "http\client.py", line 1290, in _send_request
  File "http\client.py", line 1239, in endheaders
  File "http\client.py", line 1026, in _send_output
  File "http\client.py", line 966, in send
  File "site-packages\docker\transport\npipeconn.py", line 32, in connect
  File "site-packages\docker\transport\npipesocket.py", line 23, in wrapped
  File "site-packages\docker\transport\npipesocket.py", line 72, in connect
  File "site-packages\docker\transport\npipesocket.py", line 59, in connect
pywintypes.error: (2, 'CreateFile', 'Le fichier spécifié est introuvable.')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "docker-compose", line 3, in <module>
  File "compose\cli\main.py", line 67, in main
  File "compose\cli\main.py", line 123, in perform_command
  File "compose\cli\command.py", line 69, in project_from_options
  File "compose\cli\command.py", line 132, in get_project
  File "compose\cli\docker_client.py", line 43, in get_client
  File "compose\cli\docker_client.py", line 170, in docker_client
  File "site-packages\docker\api\client.py", line 188, in __init__
  File "site-packages\docker\api\client.py", line 213, in _retrieve_server_version
docker.errors.DockerException: Error while fetching server API version: (2, 'CreateFile', 'Le fichier spécifié est introuvable.')
[17676] Failed to execute script docker-compose
PS D:\angular\coopplay> docker-compose up
Traceback (most recent call last):
  File "site-packages\docker\api\client.py", line 205, in _retrieve_server_version
  File "site-packages\docker\api\daemon.py", line 181, in version
  File "site-packages\docker\utils\decorators.py", line 46, in inner
  File "site-packages\docker\api\client.py", line 228, in _get
  File "site-packages\requests\sessions.py", line 543, in get
  File "site-packages\requests\sessions.py", line 530, in request
  File "site-packages\requests\sessions.py", line 643, in send
  File "site-packages\requests\adapters.py", line 449, in send
  File "site-packages\urllib3\connectionpool.py", line 677, in urlopen
  File "site-packages\urllib3\connectionpool.py", line 392, in _make_request
  File "http\client.py", line 1244, in request
  File "http\client.py", line 1290, in _send_request
  File "http\client.py", line 1239, in endheaders
  File "http\client.py", line 1026, in _send_output
  File "http\client.py", line 966, in send
  File "site-packages\docker\transport\npipeconn.py", line 32, in connect
  File "site-packages\docker\transport\npipesocket.py", line 23, in wrapped
  File "site-packages\docker\transport\npipesocket.py", line 72, in connect
  File "site-packages\docker\transport\npipesocket.py", line 59, in connect
pywintypes.error: (2, 'CreateFile', 'Le fichier spécifié est introuvable.')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "docker-compose", line 3, in <module>
  File "compose\cli\main.py", line 67, in main
  File "compose\cli\main.py", line 123, in perform_command
  File "compose\cli\command.py", line 69, in project_from_options
  File "compose\cli\command.py", line 132, in get_project
  File "compose\cli\docker_client.py", line 43, in get_client
  File "compose\cli\docker_client.py", line 170, in docker_client
  File "site-packages\docker\api\client.py", line 188, in __init__
  File "site-packages\docker\api\client.py", line 213, in _retrieve_server_version
docker.errors.DockerException: Error while fetching server API version: (2, 'CreateFile', 'Le fichier spécifié est introuvable.')
[18312] Failed to execute script docker-compose

**Comment by peterssond** [comment]
@hakuno could this issue get a more descriptive name, to make it easier to find and understand what this bug is about?

**Comment by manishmoon8** [comment]
Was facing the same issue, restarting the docker did the trick for me.

**Comment by hakuno** [comment]
@peterssond Any tips? The error sounds too generic for me. Something about returning 500 status code from API fetch at start... whatever.

**Comment by besiwims** [comment]
Good day

I installed docker and was running an image yesterday without a problem, but now when I run these "docker-compose pull && docker-compose up -d", I get the error below.

Traceback (most recent call last):
  File "site-packages\docker\api\client.py", line 205, in _retrieve_server_version
  File "site-packages\docker\api\daemon.py", line 181, in version
  File "site-packages\docker\utils\decorators.py", line 46, in inner
  File "site-packages\docker\api\client.py", line 228, in _get
  File "site-packages\requests\sessions.py", line 543, in get
  File "site-packages\requests\sessions.py", line 530, in request
  File "site-packages\requests\sessions.py", line 643, in send
  File "site-packages\requests\adapters.py", line 449, in send
  File "site-packages\urllib3\connectionpool.py", line 677, in urlopen
  File "site-packages\urllib3\connectionpool.py", line 392, in _make_request
  File "http\client.py", line 1244, in request
  File "http\client.py", line 1290, in _send_request
  File "http\client.py", line 1239, in endheaders
  File "http\client.py", line 1026, in _send_output
  File "http\client.py", line 966, in send
  File "site-packages\docker\transport\npipeconn.py", line 32, in connect
  File "site-packages\docker\transport\npipesocket.py", line 23, in wrapped
  File "site-packages\docker\transport\npipesocket.py", line 72, in connect
  File "site-packages\docker\transport\npipesocket.py", line 59, in connect
pywintypes.error: (2, 'CreateFile', 'The system cannot find the file specified.')

During handling of the above exception, another exception occurred: etc

How do I fix this?
