### ISSUE TITLE
docker-compose --env-file is not working at all

### ISSUE THREAD

**Issue by Yehonal** [docker/compose#7882]
Description of the issue

--env-file doesn't work. The variables cannot be used within the docker-compose file. I'm following this doc: https://docs.docker.com/compose/environment-variables/#substitute-environment-variables-in-compose-files

**Output of `docker-compose version`**
```
docker-compose version 1.27.4, build 40524192
```

**Output of `docker version`**
```
Docker version 19.03.13, build 4484c46d9d
```

**Output of `docker-compose config`**
(Make sure to add the relevant `-f` and other flags)
```
WARNING: The IMAGE variable is not set. Defaulting to a blank string.
services:
  web:
    image: ''
version: '3.9'
```

## Steps to reproduce the issue

Just this: https://docs.docker.com/compose/environment-variables/#substitute-environment-variables-in-compose-files

1. Create docker-compose.yml:

```
services:
  web:
   image: "${IMAGE}"
```

2. create .env.dev

`IMAGE=node:12`

3. run:

`docker-compose --env-file ./.env.dev up `

### Observed result

```
WARNING: The IMAGE variable is not set. Defaulting to a blank string.
Traceback (most recent call last):
  File "bin/docker-compose", line 3, in <module>
  File "compose/cli/main.py", line 67, in main
  File "compose/cli/main.py", line 126, in perform_command
  File "compose/cli/main.py", line 1070, in up
  File "compose/cli/main.py", line 1066, in up
  File "compose/project.py", line 615, in up
  File "compose/service.py", line 350, in ensure_image_exists
  File "compose/service.py", line 376, in image
  File "docker/utils/decorators.py", line 17, in wrapped
docker.errors.NullResource: Resource ID was not provided
[50006] Failed to execute script docker-compose
```

### Expected result

It should read from the .env.dev

### Stacktrace / full error message

```
WARNING: The IMAGE variable is not set. Defaulting to a blank string.
Traceback (most recent call last):
  File "bin/docker-compose", line 3, in <module>
  File "compose/cli/main.py", line 67, in main
  File "compose/cli/main.py", line 126, in perform_command
  File "compose/cli/main.py", line 1070, in up
  File "compose/cli/main.py", line 1066, in up
  File "compose/project.py", line 615, in up
  File "compose/service.py", line 350, in ensure_image_exists
  File "compose/service.py", line 376, in image
  File "docker/utils/decorators.py", line 17, in wrapped
docker.errors.NullResource: Resource ID was not provided
[50006] Failed to execute script docker-compose
```

## Additional information

Ubuntu 20.04

**Comment by gozeloglu** [comment]
Hi @Yehonal. I faced the same issue. https://github.com/docker/compose/issues/7495#issuecomment-642915975 and https://github.com/docker/compose/issues/7495#issuecomment-643092956 worked for me. You can try it.

**Comment by Yehonal** [comment]
Thank you! it solved for me too
