### ISSUE TITLE
using .env file gives python-dotenv error

### ISSUE THREAD

**Issue by DonRichie** [docker/compose#7903]
## Description of the issue

I am trying to use a .env file and get a python error when using any docker-compose command.

The error says a named argument for a function in python-dotenv is missing. I believe everything should be up to date and wonder where exactly a version mismatch happens.

## Context information (for bug reports)

**Output of `docker-compose version`**
```
docker-compose version 1.27.4, build unknown
```

**Version of python-dotenv**
```
community/python-dotenv 0.15.0-1 (28.2 KiB 97.5 KiB) (Installed)
```

**Output of `docker version`**
```
Client:
 Version:           19.03.13-ce
 API version:       1.40
 Go version:        go1.15.2
 Git commit:        4484c46d9d
 Built:             Sat Sep 26 12:04:46 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          19.03.13-ce
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.15.2
  Git commit:       4484c46d9d
  Built:            Sat Sep 26 12:03:35 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.4.1.m
  GitCommit:        c623d1b36f09f8ef6536a057bd658b3aa8632828.m
 runc:
  Version:          1.0.0-rc92
  GitCommit:        ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**docker-compose.yml**
```
version: "3.8"

services:
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
```

**.env (utf-8 encoded)**
```
TEST=test
```

**Output of `docker-compose config`**
(Make sure to add the relevant `-f` and other flags)
```
Traceback (most recent call last):
  File "/usr/bin/docker-compose", line 33, in <module>
    sys.exit(load_entry_point('docker-compose==1.27.4', 'console_scripts', 'docker-compose')())
  File "/usr/lib/python3.8/site-packages/compose/cli/main.py", line 67, in main
    command()
  File "/usr/lib/python3.8/site-packages/compose/cli/main.py", line 120, in perform_command
    handler(command, command_options)
  File "/usr/lib/python3.8/site-packages/compose/cli/main.py", line 324, in config
    compose_config = get_config_from_options('.', self.toplevel_options, additional_options)
  File "/usr/lib/python3.8/site-packages/compose/cli/command.py", line 93, in get_config_from_options
    environment = Environment.from_env_file(override_dir or base_dir, environment_file)
  File "/usr/lib/python3.8/site-packages/compose/config/environment.py", line 66, in from_env_file
    instance = _initialize()
  File "/usr/lib/python3.8/site-packages/compose/config/environment.py", line 61, in _initialize
    return cls(env_vars_from_file(env_file_path))
  File "/usr/lib/python3.8/site-packages/compose/config/environment.py", line 38, in env_vars_from_file
    env = dotenv.dotenv_values(dotenv_path=filename, encoding='utf-8-sig', interpolate=interpolate)
TypeError: dotenv_values() got an unexpected keyword argument 'encoding'
```

## Steps to reproduce the issue
1. create docker-compose.yml and .env
2. have same version of docker-compose and python-dotenv as I do
3. try any docker-compose command utilizing the mentioned files

### Observed result
```
Traceback (most recent call last):
  File "/usr/bin/docker-compose", line 33, in <module>
    sys.exit(load_entry_point('docker-compose==1.27.4', 'console_scripts', 'docker-compose')())
  File "/usr/lib/python3.8/site-packages/compose/cli/main.py", line 67, in main
    command()
  File "/usr/lib/python3.8/site-packages/compose/cli/main.py", line 123, in perform_command
    project = project_from_options('.', options)
  File "/usr/lib/python3.8/site-packages/compose/cli/command.py", line 40, in project_from_options
    environment = Environment.from_env_file(override_dir or project_dir, environment_file)
  File "/usr/lib/python3.8/site-packages/compose/config/environment.py", line 66, in from_env_file
    instance = _initialize()
  File "/usr/lib/python3.8/site-packages/compose/config/environment.py", line 61, in _initialize
    return cls(env_vars_from_file(env_file_path))
  File "/usr/lib/python3.8/site-packages/compose/config/environment.py", line 38, in env_vars_from_file
    env = dotenv.dotenv_values(dotenv_path=filename, encoding='utf-8-sig', interpolate=interpolate)
TypeError: dotenv_values() got an unexpected keyword argument 'encoding'
```

### Expected result
docker-compose should spin up a container

## Additional information
OS: Arch Linux

**Comment by ulyssessouza** [comment]
Hello @DonRichie ! I couldn't reproduce with `python-dotenv 0.15.0`. The version you posted is not listed on pip.
Could you please use the binary version from the release page?

**Comment by ViktorLavrenenko** [comment]
Did you fix that?)

**Comment by ViktorLavrenenko** [comment]
I've fixed that by deleting .env file, I've been using Fedora 33 and python 3.9.1

**Comment by DonRichie** [comment]
Hey, 
I actually reinstalled the operating system on the machine I mentioned. 
Currently having no issues. Will close the issue. 
Thank you for you hint, will try it out next time.

**Comment by ViktorLavrenenko** [comment]
I had docker-compose installed via dnf
I deleted it and installed via pip. It helped me)
