### ISSUE TITLE
compose raises exception when it can't connect to docker socket

### ISSUE THREAD

**Issue by BretFisher** [docker/compose#7915]
## Description of the issue
Rather than the previous friendly error of:

```
ERROR: Couldn't connect to Docker daemon at http+docker://localhost - is it running?

If it's at a non-standard location, specify the URL with the DOCKER_HOST environment variable.
```

We now get an exception when unable to connect in compose 1.27:

```
Traceback (most recent call last):
  File "site-packages/urllib3/connectionpool.py", line 677, in urlopen
  File "site-packages/urllib3/connectionpool.py", line 392, in _make_request
  File "http/client.py", line 1252, in request
  File "http/client.py", line 1298, in _send_request
  File "http/client.py", line 1247, in endheaders
  File "http/client.py", line 1026, in _send_output
  File "http/client.py", line 966, in send
  File "site-packages/docker/transport/unixconn.py", line 43, in connect
ConnectionRefusedError: [Errno 61] Connection refused
........
```

## Context information (for bug reports)

**Output of `docker-compose version`**
```
docker-compose version 1.27.4, build 40524192
docker-py version: 4.3.1
CPython version: 3.7.7
OpenSSL version: OpenSSL 1.1.1g  21 Apr 2020
```

**Output of `docker version`**
```
Client: Docker Engine - Community
 Cloud integration: 0.1.22
 Version:           20.10.0-beta1
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        ac365d7
 Built:             Tue Oct 13 18:13:53 2020
 OS/Arch:           darwin/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.0-beta1
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       9c15e82
  Built:            Tue Oct 13 18:17:18 2020
  OS/Arch:          linux/amd64
  Experimental:     true
 containerd:
  Version:          v1.4.1
  GitCommit:        c623d1b36f09f8ef6536a057bd658b3aa8632828
 runc:
  Version:          1.0.0-rc92
  GitCommit:        ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Comment by rfay** [comment]
@BretFisher could you please specify the version of docker-compose that had your expected "ERROR: Couldn't connect to Docker daemon at http+docker://localhost - is it running?"

**Comment by BretFisher** [comment]
I have this on a different Ubuntu machine
```
docker-compose version
docker-compose version 1.25.0-rc2, build 661ac20e
docker-py version: 4.0.1
CPython version: 3.7.4
OpenSSL version: OpenSSL 1.1.0k  28 May 2019```

**Comment by xiuyi0312** [comment]
I use the same version exactly as yours, and when I connect to the wifi in my company, the same problem occurs, and then I connect to my iphone's personal hotspot, it started downloading.

**Comment by FlavourDaveMasterDDissle-theDtotheissle** [comment]
Same on Mac OS

```
docker-compose version 1.27.4, build 40524192
docker-py version: 4.3.1
CPython version: 3.7.7
OpenSSL version: OpenSSL 1.1.1g  21 Apr 2020
```

**Comment by FlavourDaveMasterDDissle-theDtotheissle** [comment]
> I have this on a different Ubuntu machine
> 
> ```
> docker-compose version
> docker-compose version 1.25.0-rc2, build 661ac20e
> docker-py version: 4.0.1
> CPython version: 3.7.4
> OpenSSL version: OpenSSL 1.1.0k  28 May 2019
> ```

Same on Mac OS:

```
docker-compose version 1.27.4, build 40524192
docker-py version: 4.3.1
CPython version: 3.7.7
OpenSSL version: OpenSSL 1.1.1g  21 Apr 2020
```

**Comment by veysel-code** [comment]
I have exactly the same error since today. With almost the same version on my Mac OS.
Someone knows what is happening ?

**Comment by DylanMeeus** [comment]
Same issue here, latest version of docker + debian. :( 

```
docker-compose version 1.28.5, build c4eb3a1f
docker-py version: 4.4.4
CPython version: 3.7.10
OpenSSL version: OpenSSL 1.1.0l  10 Sep 2019
```

**Comment by Piotr1215** [comment]
I had same issue today, on Ubuntu 20.04.2 (WSL2)

```
docker-compose version 1.27.4, build 40524192
docker-py version: 4.3.1
CPython version: 3.7.7
OpenSSL version: OpenSSL 1.1.0l  10 Sep 2019
```

Solved it by re-enabling docker desktop integration with WSL2.

![image](https://user-images.githubusercontent.com/8086638/110205869-d3d51880-7e7a-11eb-8ee1-ba7d87cc076e.png)

**Comment by chetanyachopra** [comment]
solved it by restarting docker daemon in macos ... 
as`docker ps` says daemon is not up .. so restarted and it worked like a charm
