### ISSUE TITLE
Wrong image name breaks docker-compose build

### ISSUE THREAD

**Issue by maxkratz** [docker/compose#7920]
## Description of the issue

`docker-compose build` crashes with a useless error message if the specified image name (target) for a build does not meet the Docker requirements.

## Context information (for bug reports)

**Output of `docker-compose version`**
```
docker-compose version 1.25.4, build 8d51620a
docker-py version: 4.1.0
CPython version: 3.7.5
OpenSSL version: OpenSSL 1.1.0l  10 Sep 2019
```

**Output of `docker version`**
```
Client: Docker Engine - Community
 Version:           19.03.13
 API version:       1.40
 Go version:        go1.13.15
 Git commit:        4484c46d9d
 Built:             Wed Sep 16 17:02:36 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.13
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       4484c46d9d
  Built:            Wed Sep 16 17:01:06 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.3.7
  GitCommit:        8fba4e9a7d01810a393d5d25a3621dc101981175
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Output of `docker-compose config`**
(Make sure to add the relevant `-f` and other flags)
```
services:
  app:
    build:
      context: /home/maxkratz/gits/vfl
    cpu_count: 2
    cpu_percent: 75
    environment:
      TZ: Europe/Berlin
    image: registry/test/XYZ:latest
    mem_limit: 4G
    memswap_limit: 4G
    ports:
    - 8080:8080/tcp
    restart: unless-stopped
version: '2.4'
```

## Steps to reproduce the issue

1. Create a `docker-compose.yml` with an image name that does not meet the docker requirements, e.g. "registry/test/XYZ:latest" (In this example the UPPERCASE letters are invalid symbols.)
2. Run `docker-compose build --no-cache`

### Observed result

`docker-compose` shows a message, that it couldn't connect to Docker daemon (see later section with output trace).

Docker itself provides a helpful error message e.g. if I run `docker build -t registry/test/XYZ:latest . --no-cache`:

```
invalid argument "registry/test/XYZ:latest" for "-t, --tag" flag: invalid reference format: repository name must be lowercase
See 'docker build --help'.
```

### Expected result

A helpful error message e.g. "Specified docker image name does not meet requirement(s) xy."

### Stacktrace / full error message

```
Building app
ERROR: Couldn't connect to Docker daemon at http+docker://localhost - is it running?

If it's at a non-standard location, specify the URL with the DOCKER_HOST environment variable.
```

## Additional information

OS version / distribution:
* Linux Mint 19.2 Tina x86_64 with Linux Kernel 5.6.17-050617-generic.

`docker-compose` install method
* `docker-compose` was installed as described here: https://docs.docker.com/compose/install/ (Downloaded from github release pages and marked as executable.)

**Comment by Hackebein** [comment]
> * Create a `docker-compose.yml` with an image name that does not meet the docker requirements, e.g. "registry/test/XYZ:latest" (In this example the UPPERCASE letters are invalid symbols.)
> * Run `docker-compose build --no-cache`

As i found out it depends on files in the same folder (or sub folders) with docker-compose.yml.
For example:
* Take an empty folder.
* Create an invalid `docker-compose.yml` file as descripted above.
* Install npm package lodash (`npm install lodash`)
* Try `docker-compose build` (to get the error message).

After removing the `node_modules` folder, `docker-compose build` is working as expected again.

My research can be found here: https://github.com/Hackebein/github-action-docker-compose-connection-error-example

Here some context Informations from where i tryed my tests:
```
# uname -a
Linux server01 5.4.0-54-generic #60-Ubuntu SMP Fri Nov 6 10:37:59 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
# docker-compose version
docker-compose version 1.22.0, build f46880fe
docker-py version: 3.4.1
CPython version: 3.6.6
OpenSSL version: OpenSSL 1.1.0f  25 May 2017
# docker version
Client: Docker Engine - Community
 Version:           20.10.0
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        7287ab3
 Built:             Tue Dec  8 18:59:40 2020
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.0
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       eeddea2
  Built:            Tue Dec  8 18:57:45 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.3
  GitCommit:        269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc:
  Version:          1.0.0-rc92
  GitCommit:        ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```
```
# uname -a
Linux server02 5.4.0-54-generic #60-Ubuntu SMP Fri Nov 6 10:37:59 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
# docker-compose version
docker-compose version 1.27.4, build 40524192
docker-py version: 4.3.1
CPython version: 3.7.7
OpenSSL version: OpenSSL 1.1.0l  10 Sep 2019
# docker version
Client: Docker Engine - Community
 Version:           20.10.0
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        7287ab3
 Built:             Tue Dec  8 18:59:40 2020
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.0
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       eeddea2
  Built:            Tue Dec  8 18:57:45 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.3
  GitCommit:        269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc:
  Version:          1.0.0-rc92
  GitCommit:        ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```
```
# uname -a
Linux Hinkelstein 4.19.128-microsoft-standard #1 SMP Tue Jun 23 12:58:10 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
$ docker-compose version
docker-compose version 1.27.4, build 40524192
docker-py version: 4.3.1
CPython version: 3.7.7
OpenSSL version: OpenSSL 1.1.0l  10 Sep 2019
$ docker version
Client: Docker Engine - Community
 Cloud integration: 1.0.4
 Version:           20.10.0
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        7287ab3
 Built:             Tue Dec  8 18:59:53 2020
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.0
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       eeddea2
  Built:            Tue Dec  8 18:58:04 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.4.3
  GitCommit:        269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc:
  Version:          1.0.0-rc92
  GitCommit:        ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```
```
$ uname -a
Linux fv-az212-682 5.4.0-1031-azure #32-Ubuntu SMP Tue Oct 6 09:47:33 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
$ docker-compose version
docker-compose version 1.27.4, build 40524192
docker-py version: 4.3.1
CPython version: 3.7.7
OpenSSL version: OpenSSL 1.1.0l  10 Sep 2019
$ docker version
Client:
 Version:           19.03.13+azure
 API version:       1.40
 Go version:        go1.13.15
 Git commit:        cd8016b6bcc51a51f577bcffb37e6a870f7813f9
 Built:             Tue Sep 15 23:02:04 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          19.03.13+azure
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       bd33bbf0497b2327516dc799a5e541b720822a4c
  Built:            Mon Mar 12 00:00:00 2018
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.3.7+azure
  GitCommit:        8fba4e9a7d01810a393d5d25a3621dc101981175
 runc:
  Version:          1.0.0-rc92
  GitCommit:        ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 docker-init:
  Version:          0.18.0
  GitCommit:        
```
Error Message with `--verbose`:
```
compose.config.config.find: Using configuration files: ./docker-compose.fails.yml
docker.utils.config.find_config_file: Trying paths: ['/home/runner/.docker/config.json', '/home/runner/.dockercfg']
docker.utils.config.find_config_file: Found file at path: /home/runner/.docker/config.json
docker.utils.config.find_config_file: Trying paths: ['/home/runner/.docker/config.json', '/home/runner/.dockercfg']
docker.utils.config.find_config_file: Found file at path: /home/runner/.docker/config.json
docker.auth.load_config: Found 'auths' section
docker.auth.parse_auth: Found entry (registry='https://index.docker.io/v1/', username='githubactions')
urllib3.connectionpool._make_request: http://localhost:None "GET /version HTTP/1.1" 200 905
urllib3.connectionpool._make_request: http://localhost:None "GET /v1.40/version HTTP/1.1" 200 905
compose.cli.docker_client.get_client: docker-compose version 1.27.4, build 40524192
docker-py version: 4.3.1
CPython version: 3.7.7
OpenSSL version: OpenSSL 1.1.0l  10 Sep 2019
compose.cli.docker_client.get_client: Docker base_url: http+docker://localhost
compose.cli.docker_client.get_client: Docker version: Platform={'Name': ''}, Components=[{'Name': 'Engine', 'Version': '19.03.13+azure', 'Details': {'ApiVersion': '1.40', 'Arch': 'amd64', 'BuildTime': '2018-03-12T00:00:00.000000000+00:00', 'Experimental': 'false', 'GitCommit': 'bd33bbf0497b2327516dc799a5e541b720822a4c', 'GoVersion': 'go1.13.15', 'KernelVersion': '5.4.0-1031-azure', 'MinAPIVersion': '1.12', 'Os': 'linux'}}, {'Name': 'containerd', 'Version': '1.3.7+azure', 'Details': {'GitCommit': '8fba4e9a7d01810a393d5d25a3621dc101981175'}}, {'Name': 'runc', 'Version': '1.0.0-rc92', 'Details': {'GitCommit': 'ff819c7e9184c13b7c2607fe6c30ae19403a7aff'}}, {'Name': 'docker-init', 'Version': '0.18.0', 'Details': {'GitCommit': ''}}], Version=19.03.13+azure, ApiVersion=1.40, MinAPIVersion=1.12, GitCommit=bd33bbf0497b2327516dc799a5e541b720822a4c, GoVersion=go1.13.15, Os=linux, Arch=amd64, KernelVersion=5.4.0-1031-azure, BuildTime=2018-03-12T00:00:00.000000000+00:00
compose.cli.verbose_proxy.proxy_callable: docker inspect_network <- ('null_default')
urllib3.connectionpool._make_request: http://localhost:None "GET /v1.40/networks/null_default HTTP/1.1" 404 45
compose.service.build: Building latest
compose.cli.verbose_proxy.proxy_callable: docker build <- (path='/home/runner/work/null/null', tag='Hackebein/null:latest', rm=True, forcerm=False, pull=False, nocache=False, dockerfile='Dockerfile', cache_from=None, labels=None, buildargs={}, network_mode=None, target=None, shmsize=None, extra_hosts=None, container_limits={'memory': None}, gzip=False, isolation=None, platform=None)
docker.api.build._set_auth_headers: Looking for auth config
docker.api.build._set_auth_headers: Sending auth config ('https://index.docker.io/v1/')
compose.cli.errors.exit_with_error: Couldn't connect to Docker daemon at http+docker://localhost - is it running?

If it's at a non-standard location, specify the URL with the DOCKER_HOST environment variable.
Error: Process completed with exit code 1.
```

**Comment by maxkratz** [comment]
> As i found out it depends on files in the same folder (or sub folders) with docker-compose.yml.

@Hackebein as I understand, the error also occurs inside an empty folder (except for `docker-compose.yml`) on my machine:

```
 ✘ maxkratz@thinkbrett  ~/test  tree                                    
.
└── docker-compose.yml

0 directories, 1 file
```

The error mentioned above still occurs:

```
 maxkratz@thinkbrett  ~/test  docker-compose build
Building app
ERROR: Couldn't connect to Docker daemon at http+docker://localhost - is it running?

If it's at a non-standard location, specify the URL with the DOCKER_HOST environment variable.
```

**Comment by Hackebein** [comment]
okay, i can't confirm that on my system. Are we using the exact same `docker-compose.yml` file?

```
$ cat docker-compose.yml
services:
  app:
    build:
      context: /home/maxkratz/gits/vfl
    cpu_count: 2
    cpu_percent: 75
    environment:
      TZ: Europe/Berlin
    image: registry/test/XYZ:latest
    mem_limit: 4G
    memswap_limit: 4G
    ports:
     - 8080:8080/tcp
    restart: unless-stopped
version: '2.4'
$ docker-compose build
Building app

Traceback (most recent call last):
  File "compose/cli/main.py", line 67, in main
  File "compose/cli/main.py", line 126, in perform_command
  File "compose/cli/main.py", line 302, in build
  File "compose/project.py", line 468, in build
  File "compose/project.py", line 450, in build_service
  File "compose/service.py", line 1147, in build
compose.service.BuildError: (<Service: app>, {'message': 'invalid reference format: repository name must be lowercase'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "bin/docker-compose", line 3, in <module>
  File "compose/cli/main.py", line 78, in main
TypeError: can only concatenate str (not "dict") to str
[2655] Failed to execute script docker-compose
```

**Comment by maxkratz** [comment]
There are no hidden files and as far as I can see, we are using the exact same `docker-compose.yml` file:

```
 maxkratz@thinkbrett  ~/test  ls -la
insgesamt 48
drwxrwxr-x 2 maxkratz maxkratz  4096 Dez 11 20:17 .
drwxr-xr-x 6 maxkratz maxkratz 28672 Dez 11 20:36 ..
-rw-rw-r-- 1 maxkratz maxkratz   295 Dez 11 20:17 docker-compose.yml
 maxkratz@thinkbrett  ~/test  docker-compose build
Building app
ERROR: Couldn't connect to Docker daemon at http+docker://localhost - is it running?

If it's at a non-standard location, specify the URL with the DOCKER_HOST environment variable.
 ✘ maxkratz@thinkbrett  ~/test  cat docker-compose.yml         
services:
  app:
    build:
      context: /home/maxkratz/gits/vfl
    cpu_count: 2
    cpu_percent: 75
    environment:
      TZ: Europe/Berlin
    image: registry/test/XYZ:latest
    mem_limit: 4G
    memswap_limit: 4G
    ports:
    - 8080:8080/tcp
    restart: unless-stopped
version: '2.4'
 maxkratz@thinkbrett  ~/test  
```
