### ISSUE TITLE
Exec fails

### ISSUE THREAD

**Issue by Arashtbr** [docker/compose#7937]
## Description of the issue

Docker-compose exec fails 

## Context information (for bug reports)
**Output of `docker-compose version`**

```
docker-compose version 1.27.4, build 40524192
docker-py version: 4.3.1
CPython version: 3.7.7
OpenSSL version: OpenSSL 1.1.1g  21 Apr 2020

```

**Output of `docker version`**

```
Client: Docker Engine - Community
 Cloud integration: 1.0.2
 Version:           19.03.13
 API version:       1.40
 Go version:        go1.13.15
 Git commit:        4484c46d9d
 Built:             Wed Sep 16 16:58:31 2020
 OS/Arch:           darwin/amd64
 Experimental:      false
Error response from daemon: dial unix docker.raw.sock: connect: no such file or directory

```

**Output of `docker-compose config`**
(Make sure to add the relevant `-f` and other flags)

```
services:
  client:
    build:
      context: /Users/Atbr/Documents/GitHub/keto-calculator
    command:
    - webpack-dev-server
    - --progress
    - --profile
    - --hot
    ports:
    - published: 8080
      target: 8080
    volumes:
    - /Users/Atbr/Documents/GitHub/keto-calculator:/var/www:rw
    - /var/www/node_modules
version: '2'

```

## Steps to reproduce the issue

1. Run ```docker-compose up```

### Observed result

```
Traceback (most recent call last):
  File "site-packages/docker/api/client.py", line 259, in _raise_for_status
  File "site-packages/requests/models.py", line 941, in raise_for_status
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: http+docker://localhost/version

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "site-packages/docker/api/client.py", line 205, in _retrieve_server_version
  File "site-packages/docker/api/daemon.py", line 181, in version
  File "site-packages/docker/api/client.py", line 265, in _result
  File "site-packages/docker/api/client.py", line 261, in _raise_for_status
  File "site-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
docker.errors.APIError: 500 Server Error: Internal Server Error ("b'dial unix docker.raw.sock: connect: no such file or directory'")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "docker-compose", line 3, in <module>
  File "compose/cli/main.py", line 67, in main
  File "compose/cli/main.py", line 123, in perform_command
  File "compose/cli/command.py", line 69, in project_from_options
  File "compose/cli/command.py", line 132, in get_project
  File "compose/cli/docker_client.py", line 43, in get_client
  File "compose/cli/docker_client.py", line 170, in docker_client
  File "site-packages/docker/api/client.py", line 188, in __init__
  File "site-packages/docker/api/client.py", line 213, in _retrieve_server_version
docker.errors.DockerException: Error while fetching server API version: 500 Server Error: Internal Server Error ("b'dial unix docker.raw.sock: connect: no such file or directory'")
[44676] Failed to execute script docker-compose

```

### Expected result

```
keto-calculator_client_1 is up-to-date
Attaching to keto-calculator_client_1
client_1  | http://0.0.0.0:8080/
client_1  | webpack result is served from /
client_1  | content is served from ./public
4861ms build modules      
cli5ms seal 
9ms optimize 
53ms hashing
74ms create chunk assets
40ms additional chunk assets
1056ms optimize chunk assets
5ms optimize assets 
cli44ms emit

```
### Stacktrace / full error message

```

Traceback (most recent call last):
  File "site-packages/docker/api/client.py", line 259, in _raise_for_status
  File "site-packages/requests/models.py", line 941, in raise_for_status
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: http+docker://localhost/version

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "site-packages/docker/api/client.py", line 205, in _retrieve_server_version
  File "site-packages/docker/api/daemon.py", line 181, in version
  File "site-packages/docker/api/client.py", line 265, in _result
  File "site-packages/docker/api/client.py", line 261, in _raise_for_status
  File "site-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
docker.errors.APIError: 500 Server Error: Internal Server Error ("b'dial unix docker.raw.sock: connect: no such file or directory'")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "docker-compose", line 3, in <module>
  File "compose/cli/main.py", line 67, in main
  File "compose/cli/main.py", line 123, in perform_command
  File "compose/cli/command.py", line 69, in project_from_options
  File "compose/cli/command.py", line 132, in get_project
  File "compose/cli/docker_client.py", line 43, in get_client
  File "compose/cli/docker_client.py", line 170, in docker_client
  File "site-packages/docker/api/client.py", line 188, in __init__
  File "site-packages/docker/api/client.py", line 213, in _retrieve_server_version
docker.errors.DockerException: Error while fetching server API version: 500 Server Error: Internal Server Error ("b'dial unix docker.raw.sock: connect: no such file or directory'")
[44853] Failed to execute script docker-compose

```
## Additional information

OS version / distribution, `docker-compose` install method, etc.

I'm running docker on macOS Catalina Version 10.15.4

**Comment by ulyssessouza** [comment]
Hello @Arashtbr !

From here it looks like it's not a `docker-compose` issue. When you run `docker version` you already have the message:
```
Error response from daemon: dial unix docker.raw.sock: connect: no such file or directory
```

So, it looks like your daemon is not running. Can you confirm that?

**Comment by Arashtbr** [comment]
That's right, restarted docker and it's fixed now, thanks.

**Comment by doitmaan** [comment]
yes!
