### ISSUE TITLE
[1.28.0-rc1] Requires docker-py >=4.4.0 for use_ssh_client but asks for docker-py >=4.3.1 in setup.py only

### ISSUE THREAD

**Issue by hartwork** [docker/compose#7970]
Hi!

`setup.py` is not up to date with requiring `docker-py >=4.4.0`. The current `docker[ssh] >= 4.3.1` does not satisfy parameter `use_ssh_client` for `DockerClient.__init__` so e.g. tests will fail. Please fix before making 1.28.0 final. Thanks!

Best, Sebastian

```console
[..]
[..]__ DockerClientTestCase.test_user_agent __[..]
tests/unit/cli/docker_client_test.py:58: in test_user_agent
    client = docker_client(os.environ, version=DEFAULT_DOCKER_API_VERSION)
compose/cli/docker_client.py:170: in docker_client
    client = APIClient(use_ssh_client=not use_paramiko_ssh, **kwargs)
E   TypeError: __init__() got an unexpected keyword argument 'use_ssh_client'
[..]
```

PS: The 1.28.0-rc1 change log has multiple typos.

**Comment by aiordache** [comment]
My bad. Thank you for noticing! :sweat_smile:

**Comment by krichter722** [comment]
@aiordache  This bug somehow made it into the release and is still present in 1.28.2:

```
Traceback (most recent call last):
  File "/usr/local/bin/docker-compose", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/compose/cli/main.py", line 80, in main
    command_func()
  File "/usr/local/lib/python3.8/dist-packages/compose/cli/main.py", line 189, in perform_command
    project = project_from_options('.', options)
  File "/usr/local/lib/python3.8/dist-packages/compose/cli/command.py", line 60, in project_from_options
    return get_project(
  File "/usr/local/lib/python3.8/dist-packages/compose/cli/command.py", line 152, in get_project
    client = get_client(
  File "/usr/local/lib/python3.8/dist-packages/compose/cli/docker_client.py", line 41, in get_client
    client = docker_client(
  File "/usr/local/lib/python3.8/dist-packages/compose/cli/docker_client.py", line 170, in docker_client
    client = APIClient(use_ssh_client=not use_paramiko_ssh, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'use_ssh_client'
```

Should I open a new issue?

**Comment by hartwork** [comment]
> @aiordache This bug somehow made it into the release and is still present in 1.28.2:

Cannot confirm, looks fine to me:
```console
# wget https://files.pythonhosted.org/packages/9f/44/67b2c982a86a164ee540886d9efd08a131eea09844e9c05ce8a965052273/docker-compose-1.28.2.tar.gz
# tar xf docker-compose-1.28.2.tar.gz
# fgrep 4.4.0 docker-compose-1.28.2/setup.py
    'docker[ssh] >= 4.4.0, < 5',
```
Have you checked `pip check` output for dependency conflicts? Am I missing something?

**Comment by krichter722** [comment]
I've seen this issue several times in the last days, but I can't reproduce, not even in a clean Docker image `docker:20.10.3`.

**Comment by hartwork** [comment]
> I've seen this issue several times in the last days, but I can't reproduce, not even in a clean Docker image `docker:20.10.3`.

Then I'm assuming that you have pinned an older version of docker-py somewhere *and* do not have any protection layer in place that would reject it at installation time? Are you running `pip check` in your build somewhere? If we cannot reproduce it, we cannot fix it, right? :smiley:

PS: Here's what I do in my Python projects to [make sure that I have a conflict-free, complete, fully pinned "closure" of dependences](https://github.com/hartwork/jawanndenn/blob/8221dcf4c36f0dc0d631f031126c43c2fd0bdca4/Dockerfile#L28-L30) if you're interested.

**Comment by thomasmerz** [comment]
Here on **OpenSUSE 15.2** I also have this problem since a "not well known amount of days".  
My last successfull `docker-compose`  which I can find for sure was on 2021-01-28T06:15.
```
Traceback (most recent call last):
  File "/usr/bin/docker-compose", line 8, in <module>
    sys.exit(main())
  File "/usr/lib/python3.6/site-packages/compose/cli/main.py", line 80, in main
    command_func()
  File "/usr/lib/python3.6/site-packages/compose/cli/main.py", line 189, in perform_command
    project = project_from_options('.', options)
  File "/usr/lib/python3.6/site-packages/compose/cli/command.py", line 70, in project_from_options
    enabled_profiles=get_profiles_from_options(options, environment)
  File "/usr/lib/python3.6/site-packages/compose/cli/command.py", line 153, in get_project
    verbose=verbose, version=api_version, context=context, environment=environment
  File "/usr/lib/python3.6/site-packages/compose/cli/docker_client.py", line 43, in get_client
    environment=environment, tls_version=get_tls_version(environment)
  File "/usr/lib/python3.6/site-packages/compose/cli/docker_client.py", line 170, in docker_client
    client = APIClient(use_ssh_client=not use_paramiko_ssh, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'use_ssh_client'
```

```
$ docker-compose version
docker-compose version 1.28.2, build unknown
docker-py version: 4.2.2
CPython version: 3.6.12
OpenSSL version: OpenSSL 1.1.1d  10 Sep 2019
```

I found some updates after this last "good" date above:
```
2021-01-02 17:53:39|install|python3-docker|4.2.2-42.1|noarch||devel_languages_python|fc9b7cbad0ba9cb08153ffba3ea2d0e00157710bfca3261334a8584bb612d6b5|
2021-01-02 17:53:40|install|python3-dockerpty|0.4.1-16.2|noarch||devel_languages_python|7a9cb90023cba213c4eef11a9f3d50375a4bb39aa65bbc7d6bf482e75a1ab1ef|
2021-02-14 08:08:11|install|docker-runc|1.0.0rc10+gitr3981_dc9208a3303f-lp152.2.3.1|x86_64||repo-update-oss|0a0f0708db42214490ea1621bba8a466701eb809cab4c6225783efb0b14d8cb1|
2021-02-14 08:08:22|install|docker-libnetwork|0.7.0.1+gitr2908_55e924b8a842-lp152.2.3.1|x86_64||repo-update-oss|611180c7bbe4d45c155a5aab9ade81e759b985b35bd1a009dc5000b7a12f1f34|
2021-02-14 08:08:39|install|docker|19.03.15_ce-lp152.2.3.1|x86_64||repo-update-oss|4ef7eaea8520ba2ae8a8f2d4339ceec0dc884449112f8fe195ea561cf180dda6|
2021-02-14 08:08:40|install|docker-zsh-completion|19.03.15_ce-lp152.2.3.1|noarch||repo-update-oss|33bdd1d1023b349f643d93acc388db572c42a387ec49071132bd7605b5dcf848|
2021-02-14 08:08:40|install|docker-bash-completion|19.03.15_ce-lp152.2.3.1|noarch||repo-update-oss|86efdb46342786e9fe9154db88eae2e511b3af202607f4a853e09e41b7bdc7a7|
```

**Comment by hartwork** [comment]
@thomasmerz your output says `docker-py version: 4.2.2`. My guess that `pip check` would complain — have you tried? — and that maybe some external pinning or explicit install request pulled in `docker-py==4.2.2` for you. The master branch [seems fine as of today](https://github.com/docker/compose/blob/master/setup.py#L35) so I think it's something in your setup somewhere.

**Comment by thomasmerz** [comment]
```
🦎🖥  thomas@merz-nimbus:~ [0/4736]
16:08 $ pip3 check
requests 2.25.1 has requirement idna<3,>=2.5, but you have idna 3.1.
exif 1.2.0 has requirement plum-py==0.3.1, but you have plum-py 0.4.0.
🦎🖥  thomas@merz-nimbus:~ [0/4737]
16:08 $
```

But your hint gave me the right impulse, because *this* is quite more interesting:
```
🦎🖥  thomas@merz-nimbus:~ [0/4740]
16:09 $ pip3 list --outdated
Package        Version  Latest   Type
-------------- -------- -------- -----
…
docker         4.4.1    4.4.3    wheel
docker-compose 1.28.2   1.28.3   wheel
…
🦎🖥  thomas@merz-nimbus:~ [0/4741]
```

After updating these outdated packages everything is fine now. Thanks 😘   
I should sync my auto-update-times of RPM- and Python-Packages to avoid problems like this in the future…

**Comment by yangyang5214** [comment]
a error case...

```
pi@raspberrypi:~/docker-compose/selenium$ pip3  list  | grep docker
docker             4.4.4    
docker-compose     1.28.5   
dockerpty          0.4.1    
```

```
pi@raspberrypi:~/docker-compose/selenium$ docker-compose up
Traceback (most recent call last):
  File "/home/pi/.local/bin/docker-compose", line 10, in <module>
    sys.exit(main())
  File "/home/pi/.local/lib/python3.7/site-packages/compose/cli/main.py", line 80, in main
    command_func()
  File "/home/pi/.local/lib/python3.7/site-packages/compose/cli/main.py", line 189, in perform_command
    project = project_from_options('.', options)
  File "/home/pi/.local/lib/python3.7/site-packages/compose/cli/command.py", line 70, in project_from_options
    enabled_profiles=get_profiles_from_options(options, environment)
  File "/home/pi/.local/lib/python3.7/site-packages/compose/cli/command.py", line 153, in get_project
    verbose=verbose, version=api_version, context=context, environment=environment
  File "/home/pi/.local/lib/python3.7/site-packages/compose/cli/docker_client.py", line 43, in get_client
    environment=environment, tls_version=get_tls_version(environment)
  File "/home/pi/.local/lib/python3.7/site-packages/compose/cli/docker_client.py", line 170, in docker_client
    client = APIClient(use_ssh_client=not use_paramiko_ssh, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'use_ssh_client'
```

**Comment by hartwork** [comment]
@yangyang5214 I cannot confirm or reproduce:

```console
# virtualenv --python=python3.7 venv
# source venv/bin/activate
# pip install docker==4.4.4
# python -c 'from docker import APIClient; APIClient(use_ssh_client=False)' ; echo $?
0
# pip install docker-compose==1.28.5
# python -c 'from compose.cli.docker_client import APIClient; APIClient(use_ssh_client=False)' ; echo $?
0
# docker-compose version | fgrep docker-py
docker-py version: 4.4.4
```

Are you mixing different virtualenvs?
Does `docker-compose version | fgrep docker-py` also say 4.4.4 for you?

**Comment by yangyang5214** [comment]
@hartwork    thanks for reply. 

```
pi@raspberrypi:~$ docker-compose version | fgrep docker-py
docker-py version: 4.3.1
```

**Comment by hartwork** [comment]
@yangyang5214 so that's the cause — docker-py 4.3.1. Thanks for the update! :+1:

**Comment by ovuruska** [comment]
`
pip3 install --upgrade docker-py `docker-compose`
`
solved issue for me.

**Comment by SingingBush** [comment]
I encountered this issue on Fedora 36 today with:

- **docker-compose** version 1.29.2, build unknown
- **docker-py** version: 4.2.2
- **CPython** version: 3.10.5
- **OpenSSL** version: OpenSSL 3.0.3 3 May 2022

I've raised bug on Fedora's bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=2099555
