### ISSUE TITLE
Better message when Docker for Windows isn't running

### ISSUE THREAD

**Issue by SteveDesmond-ca** [docker/compose#8026]
**Is your feature request related to a problem? Please describe.**
Running `docker-compose up` when Docker for Windows isn't started gives a bunch of Python stack traces that aren't directly helpful in determining the root of the problem.
```
$ docker-compose up
Traceback (most recent call last):
  File "site-packages\docker\api\client.py", line 205, in _retrieve_server_version
  File "site-packages\docker\api\daemon.py", line 181, in version
  File "site-packages\docker\utils\decorators.py", line 46, in inner
  File "site-packages\docker\api\client.py", line 228, in _get
  File "site-packages\requests\sessions.py", line 543, in get
  File "site-packages\requests\sessions.py", line 530, in request
  File "site-packages\requests\sessions.py", line 643, in send
  File "site-packages\requests\adapters.py", line 449, in send
  File "site-packages\urllib3\connectionpool.py", line 677, in urlopen
  File "site-packages\urllib3\connectionpool.py", line 392, in _make_request
  File "http\client.py", line 1244, in request
  File "http\client.py", line 1290, in _send_request
  File "http\client.py", line 1239, in endheaders
  File "http\client.py", line 1026, in _send_output
  File "http\client.py", line 966, in send
  File "site-packages\docker\transport\npipeconn.py", line 32, in connect
  File "site-packages\docker\transport\npipesocket.py", line 23, in wrapped
  File "site-packages\docker\transport\npipesocket.py", line 72, in connect
  File "site-packages\docker\transport\npipesocket.py", line 59, in connect
pywintypes.error: (2, 'CreateFile', 'The system cannot find the file specified.')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "docker-compose", line 3, in <module>
  File "compose\cli\main.py", line 67, in main
  File "compose\cli\main.py", line 123, in perform_command
  File "compose\cli\command.py", line 69, in project_from_options
  File "compose\cli\command.py", line 132, in get_project
  File "compose\cli\docker_client.py", line 43, in get_client
  File "compose\cli\docker_client.py", line 170, in docker_client
  File "site-packages\docker\api\client.py", line 188, in __init__
  File "site-packages\docker\api\client.py", line 213, in _retrieve_server_version
docker.errors.DockerException: Error while fetching server API version: (2, 'CreateFile', 'The system cannot find the file specified.')
[6820] Failed to execute script docker-compose
```

**Describe the solution you'd like**
A more helpful message, like "Docker pipe could not be found, are you sure Docker is installed and running?"

**Describe alternatives you've considered**
Having Docker run at system startup, but would rather keep startup fast and only allocate resources to Docker when necessary.

**Additional context**
I don't have a Mac to test on, but this is probably the same problem there. Maybe even true on Linux when Docker Compose is installed but not Docker?

**Comment by NickCraver** [comment]
I've hit this on every system I've had - I think it's even a common thing for users who don't auto-start Docker with their OS. Totally agree it would be a good improvement to have a much clearer error message for the case here.

**Comment by SteveDesmond-ca** [comment]
FWIW, it's a little better using `docker compose up` instead of `docker-compose up`:
```
error during connect: This error may indicate that the docker daemon is not running.: Get "http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.24/containers/json?all=1&filters=%7B%22label%22%3A%7B%22com.docker.compose.project%3Dapp%22%3Atrue%7D%7D&limit=0": open //./pipe/docker_engine: The system cannot find the file specified.
```
