### ISSUE TITLE
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 17: character maps to <undefined>

### ISSUE THREAD

**Issue by geelife** [docker/compose#8083]
Hi,
Though I have found similar reports, I couldn't solve the problem of which I am not sure whether this is a bug or not.

## Description of the issue
Running docker-compose up -d results in UnicodeDecodeError.
Tried on two different Windows 10 machines running Docker for Windows.

## Context information (for bug reports)

**Output of `docker-compose version`**
```
docker-compose version 1.27.4, build 40524192
```

**Output of `docker version`**
```
Docker version 20.10.2, build 2291f61
```

**Output of `docker-compose config`**
(Make sure to add the relevant `-f` and other flags)
```
services:
  app:
    build:
      context: F:\repos\repo
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    depends_on:
      db:
        condition: service_started
    environment:
      RAILS_ENV: development
    links:
    - db
    ports:
    - published: 3000
      target: 3000
    volumes:
    - F:\repos\repo:/app:rw
  db:
    environment:
      MYSQL_DATABASE: development_db
      MYSQL_PASSWORD: blablabla123
      MYSQL_ROOT_PASSWORD: blablabla123rootpw
      MYSQL_USER: jay
    image: mysql:5.7
    ports:
    - published: 3306
      target: 3306
version: '3.9'
```

## Steps to reproduce the issue

1. Navigate to app folder
2. Run docker-compose up -d

### Observed result
see stacktrace

### Expected result
composed app

### Stacktrace / full error message

```
Building app
Traceback (most recent call last):
  File "docker-compose", line 3, in <module>
  File "compose\cli\main.py", line 67, in main
  File "compose\cli\main.py", line 126, in perform_command
  File "compose\cli\main.py", line 1070, in up
  File "compose\cli\main.py", line 1066, in up
  File "compose\project.py", line 615, in up
  File "compose\service.py", line 362, in ensure_image_exists
  File "compose\service.py", line 1125, in build
  File "site-packages\docker\api\build.py", line 156, in build
  File "c:\jenkins\workspace\dsg_compose_1.27.4\venv\lib\encodings\cp1252.py", line 23, in decode
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 17: character maps to <undefined>
[4144] Failed to execute script docker-compose
```

## Additional information

Windows 10 Pro, Version = 2004, OS build = 19041.746
docker-compose installed through Docker for Windows

Thanks in advance!
Best regards

**Comment by geelife** [comment]
I now tried to execute "docker compose up -d" instead of "docker**-**compose up -d" and this works. Not sure if it supposed to work with the "-" sign?
