### ISSUE TITLE
More intuitive error message when Docker service is not running

### ISSUE THREAD

**Issue by marcauberer** [docker/compose#8086]
Hi,
the usage experience could be optimized by displaying a clearer error message when trying to execute `docker-compose up` and the Docker service is not running.

Currently it only throws a StackTrace (e.g on Windows):
```
Traceback (most recent call last):
  File "site-packages\docker\api\client.py", line 205, in _retrieve_server_version
  File "site-packages\docker\api\daemon.py", line 181, in version
  File "site-packages\docker\utils\decorators.py", line 46, in inner
  File "site-packages\docker\api\client.py", line 228, in _get
  File "site-packages\requests\sessions.py", line 543, in get
  File "site-packages\requests\sessions.py", line 530, in request
  File "site-packages\requests\sessions.py", line 643, in send
  File "site-packages\requests\adapters.py", line 449, in send
  File "site-packages\urllib3\connectionpool.py", line 677, in urlopen
  File "site-packages\urllib3\connectionpool.py", line 392, in _make_request
  File "http\client.py", line 1244, in request
  File "http\client.py", line 1290, in _send_request
  File "http\client.py", line 1239, in endheaders
  File "http\client.py", line 1026, in _send_output
  File "http\client.py", line 966, in send
  File "site-packages\docker\transport\npipeconn.py", line 32, in connect
  File "site-packages\docker\transport\npipesocket.py", line 23, in wrapped
  File "site-packages\docker\transport\npipesocket.py", line 72, in connect
  File "site-packages\docker\transport\npipesocket.py", line 59, in connect
pywintypes.error: (2, 'CreateFile', 'Das System kann die angegebene Datei nicht finden.')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "docker-compose", line 3, in <module>
  File "compose\cli\main.py", line 67, in main
  File "compose\cli\main.py", line 123, in perform_command
  File "compose\cli\command.py", line 69, in project_from_options
  File "compose\cli\command.py", line 132, in get_project
  File "compose\cli\docker_client.py", line 43, in get_client
  File "compose\cli\docker_client.py", line 170, in docker_client
  File "site-packages\docker\api\client.py", line 188, in __init__
  File "site-packages\docker\api\client.py", line 213, in _retrieve_server_version
docker.errors.DockerException: Error while fetching server API version: (2, 'CreateFile', 'Das System kann die angegebene Datei nicht finden.')
[15880] Failed to execute script docker-compose
```
More unexperienced folks could have problems to understand what to do, so this would be a great addition.

A better solution would be to check if the Docker service is reachable by docker-compose and if not, show a message like this:
**Linux**:
`The Docker service is currently not available. Please start it by executing 'sudo systemctl start docker' and try it again.`
**Windows**:
`The Docker service is currently not available. Please launch 'Docker Desktop' on your computer and try it again.`

Would be cool if this was realized.

Cheers,
Marc

**Comment by MaximeAtWiztopic** [comment]
Same as https://github.com/docker/compose/issues/7915.

**Comment by metalsheep** [comment]
+1, seems to also duplicate
https://github.com/docker/compose/issues/8405
https://github.com/docker/compose/issues/8378
and caused me to give my terminal a phat double-take when it happened today.
