### ISSUE TITLE
Fig up hanging

### ISSUE THREAD

**Issue by mikekelly** [docker/compose#812]
Indeterminate hanging while creating containers during a `fig up`.

@aanand @bfirsh I caught hanging behaviour while running with the verbose option, but I haven't managed to figure out the conditions to reproduce. Here's the output right up until the hanging starts:

```
Creating project_container_1...
docker containers <- (all=True)
docker containers -> (list with 21 items)
docker images <- (name=u'project_container')
docker images -> (list with 1 items)
docker create_container <- (name=u'project_container_1', image=u'project_container', environment={}, command='./figrun.sh', volumes={u'/code': {}}, ports=[u'4188'])
docker create_container -> {u'Id': u'036c7d5c45582068dfaea2ccf04c22b3825b126a9c8ae6577c6ee8bacbd4a827',
 u'Warnings': None}
docker inspect_container <- (u'036c7d5c45582068dfaea2ccf04c22b3825b126a9c8ae6577c6ee8bacbd4a827')
docker inspect_container -> {u'AppArmorProfile': u'',
 u'Args': [],
 u'Config': {u'AttachStderr': True,
             u'AttachStdin': False,
             u'AttachStdout': True,
             u'Cmd': [u'./figrun.sh'],
             u'CpuShares': 0,
             u'Cpuset': u'',
             u'Domainname': u'',
             u'Entrypoint': None,
...
docker containers <- (all=False)
docker containers -> (list with 20 items)
docker containers <- (all=False)
```

The hanging can be stopped by running `fig ps` in another terminal session, at which point the `fig up` immediately continues (but will sometimes fail again further on).

If left to hang the command exits with the following stack trace:

```
Traceback (most recent call last):
  File "/usr/local/bin/fig", line 9, in <module>
    load_entry_point('fig==1.0.1', 'console_scripts', 'fig')()
  File "/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/fig/cli/main.py", line 31, in main
    command.sys_dispatch()
  File "/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/fig/cli/docopt_command.py", line 21, in sys_dispatch
    self.dispatch(sys.argv[1:], None)
  File "/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/fig/cli/command.py", line 28, in dispatch
    super(Command, self).dispatch(*args, **kwargs)
  File "/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/fig/cli/docopt_command.py", line 24, in dispatch
    self.perform_command(*self.parse(argv, global_options))
  File "/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/fig/cli/command.py", line 56, in perform_command
    handler(project, command_options)
  File "/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/fig/cli/main.py", line 427, in up
    insecure_registry=insecure_registry,
  File "/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/fig/project.py", line 174, in up
    for (_, container) in service.recreate_containers(insecure_registry=insecure_registry):
  File "/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/fig/service.py", line 199, in recreate_containers
    container = self.create_container(insecure_registry=insecure_registry, **override_options)
  File "/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/fig/service.py", line 178, in create_container
    return Container.create(self.client, **container_options)
  File "/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/fig/container.py", line 37, in create
    response = client.create_container(**options)
  File "/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/docker/client.py", line 526, in create_container
    return self.create_container_from_config(config, name)
  File "/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/docker/client.py", line 533, in create_container_from_config
    res = self._post_json(u, data=config, params=params)
  File "/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/docker/client.py", line 236, in _post_json
    return self._post(url, data=json.dumps(data2), **kwargs)
  File "/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/docker/client.py", line 73, in _post
    return self.post(url, **self._set_request_timeout(kwargs))
  File "/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/requests/sessions.py", line 500, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/requests/sessions.py", line 457, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/requests/sessions.py", line 569, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/requests/adapters.py", line 422, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='192.168.59.103', port=2376): Read timed out. (read timeout=60)
```

**Comment by bfirsh** [comment]
Thanks so much for tracking this down, @mikekelly! We'll investigate...

**Comment by mikekelly** [comment]
no worries. If I figure out how to reproduce I'll drop details here

**Comment by mikekelly** [comment]
If it helps, we have 31 containers. If there's any other info about our setup that would help you let me know.

**Comment by aanand** [comment]
I'm occasionally able to reproduce this, but not at all reliably: what I've done is create a fig.yml with 12 dummy containers in it which just `sleep infinity`, and run:

    $ while true; do fig --project-name app${RANDOM} up -d; done

which just creates loads of containers forever. Eventually, one will hang, which as you say can be stopped by typing `docker ps` in another terminal.

Interestingly, while cleaning up (`docker rm -f $(docker ps -q)`), I experienced exactly the same hanging, which I was able to stop in exactly the same way - furthering my suspicion that this is a problem with the Docker daemon.

**Comment by jjn2009** [comment]
I have a hunch that a full disk might be causing the same error for myself:
```
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='192.168.59.103', port=2376): Read timed out. (read timeout=60)
```

**Comment by cank** [comment]
Having the same problem, timeouts with the following:

```
requests.exceptions.Timeout: HTTPSConnectionPool(host='192.168.59.103', port=2376): Read timed out.
```

Am running this on OS X with the boot2docker VM, so I started that up in terminal mode in VirtualBox and found that I am indeed out of disk space on that machine, like @jn2009 hinted. I will repartition the VM and see if that makes a difference.

**Comment by jjn2009** [comment]
@cank Same environment here, I have been playing around with machine, fig, and boot2docker and this has been a recurring error in OSX. I've decided to move on and use Ubuntu instead. 

If cleaning your drive doesn't help (I don't remember it being particularly helpful to myself) Might not be a bad idea to ssh in and try to setup fig within the boot2docker vm, then see if running fig from the command line prompt in the vm changes anything. 

Might help to isolate the problem.

So I'm guessing ```docker ps``` works but not ```fig up``` for you as well?

**Comment by chacken** [comment]
Im having the same problem.  I had to nuke the whole box and recreate.

**Comment by jrtowell** [comment]
+1

**Comment by andreaskoch** [comment]
I do experience the same issue when starting a set of containers where one is "media"-container that is only used as a volume with a rather large image (~ 2.2 GB).

I do believe that the timeout of 60 seconds is just to small for moving all that data (on a slow vm). But I am not sure because I have not figured out yet how I can increase the timeout for a quick test.

But I do now for sure that it does work if use a smaller image ( < 200 MB).

**Comment by sdake** [comment]
I have experienced a similar issue in docker-compose and have root caused it.  The issue I have is that I use volume data containers.  The intermediate container has no timeout, so fig locks up forever.  I have produced a small workaround at http://paste.fedoraproject.org/201072/69966901 .  I have found this *only* affects containers that have volume_from in 20 hours of testing/debug.

I believe the docker daemon is busted.  the Docker API wait command is not returning because wait defaults to wait until the container exits, because docker believes the containers are still running (as shown via ps  http://paste.fedoraproject.org/201073/26997245).  However, docker thinks the container is both running and not running.  See http://paste.fedoraproject.org/201074/97377142.

Regards
-steve

**Comment by jdoshi1** [comment]
This is still an issue for me. Sometimes `docker-compose up` just hangs.
docker-compose version 1.5.2
docker version 1.7.1
is there a fix or workaround? Upgrading is not really an option for me at this point in time. 
@sdake - The links you posted doesn't seem to be valid anymore.

**Comment by dnephin** [comment]
You can run with `--verbose` to see which API call is hanging. There is a known issue with using `tty: True`, but otherwise we haven't see many reports of this recently.

I'm not sure how you plan to get the fix if you can't upgrade.

**Comment by yunghoy** [comment]
Always happens . Five or Six times a day.
