### ISSUE TITLE
remote build context in git over ssh does not work on Windows

### ISSUE THREAD

**Issue by libor-m** [docker/compose#8146]
## Description of the issue
When trying to build an image from a private git repo, an error message saying `cannot run ssh` is produced. `ssh` and `git` are accessible in the shell where I am running the `docker-compose up`, but are not available system-wide (as the Git for Windows advises against that).

## Context information (for bug reports)

**Output of `docker-compose version`**
```
docker-compose version 1.27.4, build 40524192
docker-py version: 4.3.1
CPython version: 3.7.4
OpenSSL version: OpenSSL 1.1.1c  28 May 2019
```

**Output of `docker version`**
```
Client: Docker Engine - Community
 Cloud integration: 1.0.7
 Version:           20.10.2
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        2291f61
 Built:             Mon Dec 28 16:14:16 2020
 OS/Arch:           windows/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.2
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       8891c58
  Built:            Mon Dec 28 16:15:28 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.3
  GitCommit:        269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc:
  Version:          1.0.0-rc92
  GitCommit:        ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Output of `docker-compose config`**
Only the relevant bit:
```
.. redacted.. 

  front-end:
    build: 
      context: git@bitbucket.org:{my_org}/{my_private_repo}.git#docker

.. redacted ..
```

## Steps to reproduce the issue

1.  use remote git+ssh context in `docker-compose.yml`

2. run `docker compose  -f $DOCKDIR/docker-compose.yml up` (I'm using a non-default location for the file, and did not try otherwise)

### Observed result
```
error fetching: error: cannot run ssh: No such file or directory\nfatal: unable to fork\n: exit status 128
```

### Expected result
An image built by using the `Dockerfile` in the `docker` branch of the remote repo.

### Stacktrace / full error message
```
Building front-end

Traceback (most recent call last):
  File "compose\cli\main.py", line 67, in main
  File "compose\cli\main.py", line 126, in perform_command
  File "compose\cli\main.py", line 1070, in up
  File "compose\cli\main.py", line 1066, in up
  File "compose\project.py", line 615, in up
  File "compose\service.py", line 362, in ensure_image_exists
  File "compose\service.py", line 1147, in build
compose.service.BuildError: (<Service: front-end>, {'message': 'error fetching: error: cannot run ssh: No such file or directory\nfatal: unable to fork\n: exit status 128'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "docker-compose", line 3, in <module>
  File "compose\cli\main.py", line 78, in main
TypeError: can only concatenate str (not "dict") to str
[19140] Failed to execute script docker-compose
```

## Additional information
- Windows 10 20H2
- docker-compose installed as a part of Docker Desktop
- tested in "Git CMD", "Git Bash", and Ubuntu on WSL2 (seems that the build request is forwarded to the host machine anyways, the error is the same)

**Comment by libor-m** [comment]
Just tested that the remote context works via https with [Bitbucket App Password](https://support.atlassian.com/bitbucket-cloud/docs/app-passwords/).
