### ISSUE TITLE
docker-compose crashes in optimized mode

### ISSUE THREAD

**Issue by jonapich** [docker/compose#8175]
Running docker-compose from a shell with the `PYTHONOPTIMIZE=2` (https://docs.python.org/3/using/cmdline.html#cmdoption-oo) environment variable will crash:

```
$ PYTHONOPTIMIZE=2 docker-compose --version
Traceback (most recent call last):
  File "/usr/bin/docker-compose", line 8, in <module>
    sys.exit(main())
  File "/opt/venvs/docker-compose/lib/python3.8/site-packages/compose/cli/main.py", line 79, in main
    command_func = dispatch()
  File "/opt/venvs/docker-compose/lib/python3.8/site-packages/compose/cli/main.py", line 149, in dispatch
    options, handler, command_options = dispatcher.parse(sys.argv[1:])
  File "/opt/venvs/docker-compose/lib/python3.8/site-packages/compose/cli/docopt_command.py", line 28, in parse
    command_help, options, command = DocoptDispatcher.get_command_and_options(
  File "/opt/venvs/docker-compose/lib/python3.8/site-packages/compose/cli/docopt_command.py", line 23, in get_command_and_options
    opt = docopt_full_help(command_help, argv, **options)
  File "/opt/venvs/docker-compose/lib/python3.8/site-packages/compose/cli/docopt_command.py", line 9, in docopt_full_help
    return docopt(docstring, *args, **kwargs)
  File "/opt/venvs/docker-compose/lib/python3.8/site-packages/docopt.py", line 558, in docopt
    DocoptExit.usage = printable_usage(doc)
  File "/opt/venvs/docker-compose/lib/python3.8/site-packages/docopt.py", line 466, in printable_usage
    usage_split = re.split(r'([Uu][Ss][Aa][Gg][Ee]:)', doc)
  File "/usr/lib/python3.8/re.py", line 231, in split
    return _compile(pattern, flags).split(string, maxsplit)
TypeError: expected string or bytes-like object
```

The other optimization mode works:
```
$ PYTHONOPTIMIZE=1 docker-compose --version
docker-compose version 1.28.5, build unknown
```

Since `-OO` strips out the docstrings, I suppose the `docopt` stuff gets confused / can't work.

**Comment by funkyfuture** [comment]
indeed, since `docopt` relies on the functions' docstrings, Docker-Compose should quit with an error when it detects a set optmization.

as an alternative, the stdlib's `argparse` is just fine.

**Comment by jonapich** [comment]
Something else to consider:

- docopt has got its last commit in 2018
- docopt was tested up to python 3.6 (according to its readme)
