### ISSUE TITLE
docker-compose 1.28.5 hangs on Debian 10

### ISSUE THREAD

**Issue by adams-family** [docker/compose#8179]
## Description of the issue

`docker-compose` randomly hangs for a very long time (several minutes) on all commands.

Even a simple `docker-compose --version` command takes several minutes:

```
$ time docker-compose --version
docker-compose version 1.28.5, build c4eb3a1f

real	1m41.867s
user	0m0.672s
sys	0m0.112s
```

On a second call, it runs fine:

```
$ time docker-compose --version
docker-compose version 1.28.5, build c4eb3a1f

real	0m0.941s
user	0m0.826s
sys	0m0.108s
```

Running after a few minutes it takes very long again.

## Context information (for bug reports)

**Output of `docker-compose version`**
```
docker-compose version 1.28.5, build c4eb3a1f
```

**Output of `docker version`**
```
Client: Docker Engine - Community
 Version:           20.10.5
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        55c4c88
 Built:             Tue Mar  2 20:17:50 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.5
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       363e9a8
  Built:            Tue Mar  2 20:15:47 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.3
  GitCommit:        269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc:
  Version:          1.0.0-rc92
  GitCommit:        ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Output of `docker-compose config`**
Irrelevant, takes long even without any config file in the current directory.

## Steps to reproduce the issue

1. Run `docker-config --version`

### Observed result

Takes >1 - 5 minutes.

### Expected result

Should finish immediately.

### Stacktrace / full error message

It is impossible to break the command with Ctrl-C (even when pressing Ctrl-C it keeps hanging). However, if Ctrl-C is pressed then the following error message is printed out after the waiting period has ended:

```
Traceback (most recent call last):
  File "docker-compose", line 2, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "/code/.tox/py37/lib/python3.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 493, in exec_module
```

## Additional information

OS version:
```
cat /etc/issue
Debian GNU/Linux 10 \n \l
```

docker-compost install method:
```
curl -L "https://github.com/docker/compose/releases/download/1.28.5/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
chmod +x /usr/local/bin/docker-compose
```

**Comment by aiordache** [comment]
Hi @adams-family
I cannot reproduce your issue. Maybe you have some environmental problems.

**Comment by BjarneRentz** [comment]
Hi
I encounterd the same issue on version 1.28.4 on Ubuntu 20.04.02 LTS

```
time docker-compose --version
docker-compose version 1.28.4, build cabd5cfb

real    0m40.970s
user    0m0.640s
sys     0m0.093s 
``` 
and the second call:

```
time docker-compose --version
docker-compose version 1.28.4, build cabd5cfb

real    0m0.647s
user    0m0.581s
sys     0m0.063s
```
Bevore i did `apt-get update` and `upgrade` everything worked as expeted.

**Comment by adams-family** [comment]
@BjarneRentz thanks for joining the group.

@aiordache I have a clean Debian 10 set up with docker + docker-compose. I'm using the same projects as on my Debian 9 (with older docker and older docker-compose) where they work like a charm.

**Comment by aiordache** [comment]
@adams-family @BjarneRentz  I tried running containers with the versions you mentioned and I cannot reproduce.  

I copied the binary I had locally with `docker cp` to  the containers to avoid  altering the initial state with apt updates.

```
$ docker run --rm -it debian:10 bash
root@1b7b86a71c4a:/# chmod +x docker-compose-Linux-x86_64 
root@1b7b86a71c4a:/# time ./docker-compose-Linux-x86_64 version
docker-compose version 1.28.5, build c4eb3a1f
docker-py version: 4.4.4
CPython version: 3.7.10
OpenSSL version: OpenSSL 1.1.0l  10 Sep 2019

real	0m0.340s
user	0m0.309s
sys	0m0.030s

```
```
$ docker run --rm -it ubuntu:latest bash
root@4c4152304968:~# chmod +x docker-compose-Linux-x86_64 
root@4c4152304968:~# time ./docker-compose-Linux-x86_64 version
docker-compose version 1.28.5, build c4eb3a1f
docker-py version: 4.4.4
CPython version: 3.7.10
OpenSSL version: OpenSSL 1.1.0l  10 Sep 2019

real	0m0.337s
user	0m0.296s
sys	0m0.040s

```

**Comment by BjarneRentz** [comment]
Thanks for your efforts @aiordache!
In the last few days i wasnt able anymore to reproduce the error. Only onced the error occured but i did nothing relevant (as far as i can tell) bevore and all the other times `docker-compose` worked as expected.

**Comment by adams-family** [comment]
@aiordache @BjarneRentz It still happens on my side, pretty much ever time I run docker-compose. It's a clean Debian 10 + Docker CE + docker-compose + mc, there is nothing else installed.

Usually when I run the command for the second time, it's fast. Third time ok, then, at some point, it gets slow again. I think it gets slow when it 'cools down'.

I'm happy to debug this if something is willing to help me with it. Maybe it can help someone in the future. If I just wipe out the machine, even if I solve the problem, it won't help anyone.

**Comment by seriousidea** [comment]
I have exactly the same problem on multiple virtual machines that have the same environment:
DigitalOcean, Debian 9, Docker 19.03.15, docker-compose 1.29.1.

**Comment by debuggerboy** [comment]
I am having the same issue with `docker-compose version 1.29.2, build 5becea4c` on Digitalocean Ubuntu 20.04 LTS.

Its hangs for a min and then throw these error and then when I execute the same command next time it works fine.

```
$ docker-compose up -d --remove-orphans                                                                                                                                                          
Traceback (most recent call last):                                                                                                                                                                                                             
  File "docker-compose", line 2, in <module>                                                                                                                                                                                                   
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load                                                                                                                                                                            
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked                                                                                                                                                                   
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked                                                                                                                                                                            
  File "/code/.tox/py37/lib/python3.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 493, in exec_module                                                                                                                        
  File "compose/cli/main.py", line 13, in <module>                                                                                                                                                                                             
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load                                                                                                                                                                            
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked                                                                                                                                                                   
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked                                                                                                                                                                            
  File "/code/.tox/py37/lib/python3.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 493, in exec_module 
  File "docker/__init__.py", line 2, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "/code/.tox/py37/lib/python3.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 493, in exec_module 
  File "docker/api/__init__.py", line 2, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "/code/.tox/py37/lib/python3.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 493, in exec_module
```

**Comment by adams-family** [comment]
I confirm that this still happens on a brand new DigitalOcean droplet preconfigured with Docker and Docker-Compose.

However, according to this bug:
  https://github.com/docker/compose/issues/6678

The following should solve the problem:

```
apt-get install haveged
```

*(Just installed, working so far, will see if the problem is gone)*
