### ISSUE TITLE
docker-compose from windows to remote linux over SSH -> OSError: [WinError 6] Invalid handle

### ISSUE THREAD

**Issue by maltaesousa** [docker/compose#8207]
## Description of the issue

After a docker update, `docker-compose down` from windows powershell with `DOCKER_HOST` env set to a remote over SSH returns an error:

```
Exception ignored in: <function Popen.__del__ at 0x000001388757AE50>
Traceback (most recent call last):
  File "subprocess.py", line 1051, in __del__
  File "subprocess.py", line 1453, in _internal_poll
OSError: [WinError 6] Invalid handle
```

## Context information (for bug reports)

**Output of `docker-compose version`**
```
docker-compose version 1.28.5, build c4eb3a1f
docker-py version: 4.4.4
CPython version: 3.9.0
OpenSSL version: OpenSSL 1.1.1g  21 Apr 2020
```

**Output of `docker version`**
```
Client: Docker Engine - Community
 Cloud integration: 1.0.9
 Version:           20.10.5
 API version:       1.40
 Go version:        go1.13.15
 Git commit:        55c4c88
 Built:             Tue Mar  2 20:14:53 2021
 OS/Arch:           windows/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          19.03.10
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.3
  Git commit:       9424aea
  Built:            Thu Aug  6 02:55:27 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc9
  GitCommit:        d736ef14f0288d6993a1845745d6756cfc9ddd5a
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Output of `docker-compose config`**

```
services:
  redis:
    image: redis:alpine
  web:
    build:
      context: C:\temp\composetest
    ports:
    - published: 5800
      target: 5000
version: '3.9'
```

## Steps to reproduce the issue

This steps were done on a windows machine with a remote linux over SSH. Private key is set in `%USERPROFILE%/.ssh/id_rsa`.

1. Open powershell where your `docker-compose.yml` is.
2. Set `DOCKER_HOST` environment variable: `$env:DOCKER_HOST="ssh://user@server.example.com"`
3. `docker-compose up -d`
4. `docker-compose down`

### Observed result

```
Stopping composetest_redis_1 ... done
Stopping composetest_web_1   ... done
Removing composetest_redis_1 ... done
Removing composetest_web_1   ... done
Removing network composetest_default
Exception ignored in: <function Popen.__del__ at 0x00000199602FAE50>
Traceback (most recent call last):
  File "subprocess.py", line 1051, in __del__
  File "subprocess.py", line 1453, in _internal_poll
OSError: [WinError 6] Invalid handle
```

### Expected result

No OSError.

### Stacktrace / full error message

This is the output of `docker-compose down`

```
Stopping composetest_redis_1 ... done
Stopping composetest_web_1   ... done
Removing composetest_redis_1 ... done
Removing composetest_web_1   ... done
Removing network composetest_default
Exception ignored in: <function Popen.__del__ at 0x00000199602FAE50>
Traceback (most recent call last):
  File "subprocess.py", line 1051, in __del__
  File "subprocess.py", line 1453, in _internal_poll
OSError: [WinError 6] Descripteur non valide
```

## Additional information

Same composition and same remote but using a WSL 2 shell on same machine produces no error.

**Comment by metya** [comment]
Confirm that.

**Comment by stephaneerard** [comment]
Confirm too.


```
PS C:\code\frenchex2\cli.ts_i1\tmp> docker-compose ps                                          
Traceback (most recent call last):
  File "docker-compose", line 3, in <module>
  File "compose\cli\main.py", line 80, in main
  File "compose\cli\main.py", line 189, in perform_command
  File "compose\cli\command.py", line 60, in project_from_options
  File "compose\cli\command.py", line 152, in get_project
  File "compose\cli\docker_client.py", line 41, in get_client
  File "compose\cli\docker_client.py", line 170, in docker_client
  File "docker\api\client.py", line 171, in __init__
  File "docker\transport\sshconn.py", line 180, in __init__
  File "docker\transport\sshconn.py", line 225, in _connect
  File "paramiko\client.py", line 368, in connect
paramiko.ssh_exception.NoValidConnectionsError: [Errno None] Unable to connect to port 22 on 127.0.0.1
[8780] Failed to execute script docker-compose
Traceback (most recent call last):
  File "docker-compose", line 3, in <module>
  File "compose\cli\main.py", line 80, in main
  File "compose\cli\main.py", line 189, in perform_command
  File "compose\cli\command.py", line 60, in project_from_options
  File "compose\cli\command.py", line 152, in get_project
  File "compose\cli\docker_client.py", line 41, in get_client
  File "compose\cli\docker_client.py", line 170, in docker_client
  File "docker\api\client.py", line 171, in __init__
  File "docker\transport\sshconn.py", line 180, in __init__
  File "docker\transport\sshconn.py", line 225, in _connect
  File "paramiko\client.py", line 368, in connect
paramiko.ssh_exception.NoValidConnectionsError: [Errno None] Unable to connect to port 22 on 127.0.0.1
[8780] Failed to execute script docker-compose
```

```
docker context list
NAME                DESCRIPTION                               DOCKER ENDPOINT                   KUBERNETES ENDPOINT   ORCHESTRATOR
c0 *                                                          ssh://vagrant@vdi-00-control-00                         swarm

PS C:\code\frenchex2\cli.ts_i1\tmp> docker-compose version
docker-compose version 1.28.5, build c4eb3a1f
docker-py version: 4.4.4
CPython version: 3.9.0
OpenSSL version: OpenSSL 1.1.1g  21 Apr 2020
PS C:\code\frenchex2\cli.ts_i1\tmp> docker version
Client:
 Version:           19.03.12
 API version:       1.40
 Go version:        go1.13.12
 Git commit:        0ed913b8-
 Built:             07/28/2020 16:36:03
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          20.10.5
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       363e9a8
  Built:            Tue Mar  2 20:15:47 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.4
  GitCommit:        05f951a3781f4f2c1911b05e61c160e9c30eaa8e
 runc:
  Version:          1.0.0-rc93
  GitCommit:        12644e614e25b05da6fd08a38ffa0cfe1903fdec
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```


`ssh -l vagrant -p 2222 -- 127.0.0.1 docker system dial-stdio` works well.

my $HOME/.ssh/config is a `vagrant ssh-config` output : 
```
Host vdi-00-control-00
  HostName 127.0.0.1
  User vagrant
  Port 2222
  UserKnownHostsFile /dev/null
  StrictHostKeyChecking no
  PasswordAuthentication no
  IdentityFile C:/code/frenchex2/cli.ts_i1/tmp/.vagrant/machines/vdi-00-control-00/virtualbox/private_key
  IdentitiesOnly yes
  LogLevel FATAL


```

**Comment by mrtrizer** [comment]
Same
```
docker-compose --context france -f .\docker-compose.yml -f .\production.yml up -d
Building nginx-proxy
Sending build context to Docker daemon  30.21kB

....

Successfully built 582c03076457
Successfully tagged webserver_nginx-proxy:latest
SECURITY WARNING: You are building a Docker image from Windows against a non-Windows Docker host. All files and directories added to build context will have '-rwxr-xr-x' permissions. It is recommended to double check and reset permissions for sensitive files and directories.
WARNING: Image for service nginx-proxy was built because it did not already exist. To rebuild this image you must use `docker-compose build` or `docker-compose up --build`.
Creating webserver_frontend_1 ... done
Creating webserver_nginx-proxy_1 ... done
Exception ignored in: <function Popen.__del__ at 0x0000016864127CA0>
Traceback (most recent call last):
  File "subprocess.py", line 1051, in __del__
  File "subprocess.py", line 1453, in _internal_poll
OSError: [WinError 6] The handle is invalid
```

**Comment by gumish** [comment]
I have the same problem. Is there any progress?

**Comment by danich93** [comment]
Same here. Any workarounds?

**Comment by mrtrizer** [comment]
@danich93 I have my ugly workaround. Just uploading the image to the server and run it there. I'm doing this for hobby project, so don't take too serious :) 
```
docker build . -t news-publisher
rm news-publisher.tar
docker save news-publisher -o news-publisher.tar
7z a -r news-publisher.7z .\news-publisher.tar
scp -prqv .\news-publisher.7z <host>:~
ssh <host> docker load --input news-publisher.tar
ssh <host> docker run -p 80:80 news-publisher -d
```

**Comment by gumish** [comment]
I was successful when I switched my "docker-compose" to version 2:
docker-compose enable-v2

As it is writen here:
https://www.docker.com/blog/improved-volume-management-docker-dev-environments-and-more-in-desktop-3-5/
