### ISSUE TITLE
Docker-Compose Error13/ConnectionError 111 

### ISSUE THREAD

**Issue by MukaiGuy** [docker/compose#8236]
## Actions Taken 
- [x] Checked The Forum & Googled the issue and nothing has resolved this issue.
- [x] Uninstalled & Re-installed
- [x] Followed all existing documentation (including adding the docker group)  
### Disclosure
> I am not new to Docker or Docker-compose, I have previously never had this seemingly unresolveable PermissionsError #13. I have installed Docker and its tools 100's of times in the past on a wide variety of platforms. However, I know I am not an expert by any measure.

## Description of the issue
Anytime I have tried to run `docker-compose` I am receiving a permissions error.  At first I assumed I had forgotten to add myself to the docker group. However, it wasn't the case. Then I tried to run it as `sudo` and it returned `('Connection aborted.', ConnectionRefusedError(111, 'Connection refused'))` 

## Context information (for bug reports)

**Output of `docker-compose version`**
```shell
docker-compose version 1.28.6, build 5db8d86f
```

**Output of `docker version`**
```shell
Docker version 20.10.5, build 55c4c88
```

**Output of `docker-compose config`**
(Make sure to add the relevant `-f` and other flags)
```yaml
 docker-compose config  
services:
  netbox:
    depends_on:
      netbox-worker:
        condition: service_started
      postgres:
        condition: service_started
      redis:
        condition: service_started
      redis-cache:
        condition: service_started
    environment:
      CORS_ORIGIN_ALLOW_ALL: "True"
      DB_HOST: postgres
      DB_NAME: netbox
      DB_PASSWORD: J5brHrAXFLQSif0K
      DB_USER: netbox
      EMAIL_FROM: netbox@bar.com
      EMAIL_PASSWORD: ''
      EMAIL_PORT: '25'
      EMAIL_SERVER: localhost
      EMAIL_SSL_CERTFILE: ''
      EMAIL_SSL_KEYFILE: ''
      EMAIL_TIMEOUT: '5'
      EMAIL_USERNAME: netbox
      EMAIL_USE_SSL: "false"
      EMAIL_USE_TLS: "false"
      MAX_PAGE_SIZE: '1000'
      MEDIA_ROOT: /opt/netbox/netbox/media
      METRICS_ENABLED: "false"
      NAPALM_PASSWORD: ''
      NAPALM_TIMEOUT: '10'
      NAPALM_USERNAME: ''
      REDIS_CACHE_DATABASE: '1'
      REDIS_CACHE_HOST: redis-cache
      REDIS_CACHE_PASSWORD: t4Ph722qJ5QHeQ1qfu36
      REDIS_CACHE_SSL: "false"
      REDIS_DATABASE: '0'
      REDIS_HOST: redis
      REDIS_PASSWORD: H733Kdjndks81
      REDIS_SSL: "false"
      RELEASE_CHECK_URL: https://api.github.com/repos/netbox-community/netbox/releases
      SECRET_KEY: r8OwDznj!!dci#P9ghmRfdu1Ysxm0AiPeDCQhKE+N_rClfWNj
      SKIP_STARTUP_SCRIPTS: "false"
      SKIP_SUPERUSER: "false"
      SUPERUSER_API_TOKEN: 0123456789abcdef0123456789abcdef01234567
      SUPERUSER_EMAIL: admin@example.com
      SUPERUSER_NAME: admin
      SUPERUSER_PASSWORD: admin
      WEBHOOKS_ENABLED: "true"
    image: netboxcommunity/netbox:latest
    ports:
    - target: 8080
    - published: 8000
      target: 8080
    user: '101'
    volumes:
    - /home/rmukai/netbox-docker/netbox-docker/configuration:/etc/netbox/config:z,ro
    - /home/rmukai/netbox-docker/netbox-docker/reports:/etc/netbox/reports:z,ro
    - /home/rmukai/netbox-docker/netbox-docker/scripts:/etc/netbox/scripts:z,ro
    - /home/rmukai/netbox-docker/netbox-docker/initializers:/opt/netbox/initializers:z,ro
    - netbox-media-files:/opt/netbox/netbox/media:z
    - /home/rmukai/netbox-docker/netbox-docker/startup_scripts:/opt/netbox/startup_scripts:z,ro
  netbox-worker:
    command:
    - rqworker
    depends_on:
      redis:
        condition: service_started
    entrypoint:
    - /opt/netbox/venv/bin/python
    - /opt/netbox/netbox/manage.py
    environment:
      CORS_ORIGIN_ALLOW_ALL: "True"
      DB_HOST: postgres
      DB_NAME: netbox
      DB_PASSWORD: J5brHrAXFLQSif0K
      DB_USER: netbox
      EMAIL_FROM: netbox@bar.com
      EMAIL_PASSWORD: ''
      EMAIL_PORT: '25'
      EMAIL_SERVER: localhost
      EMAIL_SSL_CERTFILE: ''
      EMAIL_SSL_KEYFILE: ''
      EMAIL_TIMEOUT: '5'
      EMAIL_USERNAME: netbox
      EMAIL_USE_SSL: "false"
      EMAIL_USE_TLS: "false"
      MAX_PAGE_SIZE: '1000'
      MEDIA_ROOT: /opt/netbox/netbox/media
      METRICS_ENABLED: "false"
      NAPALM_PASSWORD: ''
      NAPALM_TIMEOUT: '10'
      NAPALM_USERNAME: ''
      REDIS_CACHE_DATABASE: '1'
      REDIS_CACHE_HOST: redis-cache
      REDIS_CACHE_PASSWORD: t4Ph722qJ5QHeQ1qfu36
      REDIS_CACHE_SSL: "false"
      REDIS_DATABASE: '0'
      REDIS_HOST: redis
      REDIS_PASSWORD: H733Kdjndks81
      REDIS_SSL: "false"
      RELEASE_CHECK_URL: https://api.github.com/repos/netbox-community/netbox/releases
      SECRET_KEY: r8OwDznj!!dci#P9ghmRfdu1Ysxm0AiPeDCQhKE+N_rClfWNj
      SKIP_STARTUP_SCRIPTS: "false"
      SKIP_SUPERUSER: "false"
      SUPERUSER_API_TOKEN: 0123456789abcdef0123456789abcdef01234567
      SUPERUSER_EMAIL: admin@example.com
      SUPERUSER_NAME: admin
      SUPERUSER_PASSWORD: admin
      WEBHOOKS_ENABLED: "true"
    image: netboxcommunity/netbox:latest
    ports: []
    user: '101'
    volumes:
    - /home/rmukai/netbox-docker/netbox-docker/configuration:/etc/netbox/config:z,ro
    - /home/rmukai/netbox-docker/netbox-docker/reports:/etc/netbox/reports:z,ro
    - /home/rmukai/netbox-docker/netbox-docker/scripts:/etc/netbox/scripts:z,ro
    - /home/rmukai/netbox-docker/netbox-docker/initializers:/opt/netbox/initializers:z,ro
    - netbox-media-files:/opt/netbox/netbox/media:z
    - /home/rmukai/netbox-docker/netbox-docker/startup_scripts:/opt/netbox/startup_scripts:z,ro
  postgres:
    environment:
      POSTGRES_DB: netbox
      POSTGRES_PASSWORD: J5brHrAXFLQSif0K
      POSTGRES_USER: netbox
    image: postgres:12-alpine
    volumes:
    - netbox-postgres-data:/var/lib/postgresql/data:rw
  redis:
    command:
    - sh
    - -c
    - redis-server --appendonly yes --requirepass $$REDIS_PASSWORD
    environment:
      REDIS_PASSWORD: H733Kdjndks81
    image: redis:6-alpine
    volumes:
    - netbox-redis-data:/data:rw
  redis-cache:
    command:
    - sh
    - -c
    - redis-server --requirepass $$REDIS_PASSWORD
    environment:
      REDIS_PASSWORD: t4Ph722qJ5QHeQ1qfu36
    image: redis:6-alpine
version: '3.4'
volumes:
  netbox-media-files:
    driver: local
  netbox-postgres-data:
    driver: local
  netbox-redis-data:
    driver: local
```

## Steps to reproduce the issue
> **PLEASE NOTE:** This issue has occurred anytime I have used the docker-compose command recently. NetBox just happens to the project I am working on now. 
1. Follow the NetBox Steps [Here](https://github.com/netbox-community/netbox-docker#quickstart)
2. run the docker-compose pull 
3. In a private project run docker-compose up and it woul fail.

### Observed result
```shell
$ docker-compose pull 
Traceback (most recent call last):
  File "urllib3/connectionpool.py", line 677, in urlopen
  File "urllib3/connectionpool.py", line 392, in _make_request
  File "http/client.py", line 1277, in request
  File "http/client.py", line 1323, in _send_request
  File "http/client.py", line 1272, in endheaders
  File "http/client.py", line 1032, in _send_output
  File "http/client.py", line 972, in send
  File "docker/transport/unixconn.py", line 43, in connect
PermissionError: [Errno 13] Permission denied

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "requests/adapters.py", line 449, in send
  File "urllib3/connectionpool.py", line 727, in urlopen
  File "urllib3/util/retry.py", line 410, in increment
  File "urllib3/packages/six.py", line 734, in reraise
  File "urllib3/connectionpool.py", line 677, in urlopen
  File "urllib3/connectionpool.py", line 392, in _make_request
  File "http/client.py", line 1277, in request
  File "http/client.py", line 1323, in _send_request
  File "http/client.py", line 1272, in endheaders
  File "http/client.py", line 1032, in _send_output
  File "http/client.py", line 972, in send
  File "docker/transport/unixconn.py", line 43, in connect
urllib3.exceptions.ProtocolError: ('Connection aborted.', PermissionError(13, 'Permission denied'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "docker/api/client.py", line 214, in _retrieve_server_version
  File "docker/api/daemon.py", line 181, in version
  File "docker/utils/decorators.py", line 46, in inner
  File "docker/api/client.py", line 237, in _get
  File "requests/sessions.py", line 543, in get
  File "requests/sessions.py", line 530, in request
  File "requests/sessions.py", line 643, in send
  File "requests/adapters.py", line 498, in send
requests.exceptions.ConnectionError: ('Connection aborted.', PermissionError(13, 'Permission denied'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "docker-compose", line 3, in <module>
  File "compose/cli/main.py", line 81, in main
  File "compose/cli/main.py", line 198, in perform_command
  File "compose/cli/command.py", line 70, in project_from_options
  File "compose/cli/command.py", line 153, in get_project
  File "compose/cli/docker_client.py", line 43, in get_client
  File "compose/cli/docker_client.py", line 170, in docker_client
  File "docker/api/client.py", line 197, in __init__
  File "docker/api/client.py", line 222, in _retrieve_server_version
docker.errors.DockerException: Error while fetching server API version: ('Connection aborted.', PermissionError(13, 'Permission denied'))
[2624884] Failed to execute script docker-compose
| rmukai @ dellsvr1  3:23PM ⟫  ~/netbox-docker/netbox-docker  | release ✔ |
|➜  sudo dpkg-reconfigure apparmor
Reloading AppArmor profiles 
Skipping profile in /etc/apparmor.d/disable: usr.sbin.rsyslogd
| rmukai @ dellsvr1  3:26PM ⟫  ~/netbox-docker/netbox-docker  | release ✔ |
|➜  sudo apparmor_parser -r /var/lib/snapd/apparmor/profiles/snap.docker.compose
| rmukai @ dellsvr1  3:26PM ⟫  ~/netbox-docker/netbox-docker  | release ✔ |
|➜  refresh
 
| rmukai @ dellsvr1  3:26PM ⟫  ~/netbox-docker/netbox-docker  | release ✔ |
|➜  docker-compose pull
Traceback (most recent call last):
  File "urllib3/connectionpool.py", line 677, in urlopen
  File "urllib3/connectionpool.py", line 392, in _make_request
  File "http/client.py", line 1277, in request
  File "http/client.py", line 1323, in _send_request
  File "http/client.py", line 1272, in endheaders
  File "http/client.py", line 1032, in _send_output
  File "http/client.py", line 972, in send
  File "docker/transport/unixconn.py", line 43, in connect
PermissionError: [Errno 13] Permission denied

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "requests/adapters.py", line 449, in send
  File "urllib3/connectionpool.py", line 727, in urlopen
  File "urllib3/util/retry.py", line 410, in increment
  File "urllib3/packages/six.py", line 734, in reraise
  File "urllib3/connectionpool.py", line 677, in urlopen
  File "urllib3/connectionpool.py", line 392, in _make_request
  File "http/client.py", line 1277, in request
  File "http/client.py", line 1323, in _send_request
  File "http/client.py", line 1272, in endheaders
  File "http/client.py", line 1032, in _send_output
  File "http/client.py", line 972, in send
  File "docker/transport/unixconn.py", line 43, in connect
urllib3.exceptions.ProtocolError: ('Connection aborted.', PermissionError(13, 'Permission denied'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "docker/api/client.py", line 214, in _retrieve_server_version
  File "docker/api/daemon.py", line 181, in version
  File "docker/utils/decorators.py", line 46, in inner
  File "docker/api/client.py", line 237, in _get
  File "requests/sessions.py", line 543, in get
  File "requests/sessions.py", line 530, in request
  File "requests/sessions.py", line 643, in send
  File "requests/adapters.py", line 498, in send
requests.exceptions.ConnectionError: ('Connection aborted.', PermissionError(13, 'Permission denied'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "docker-compose", line 3, in <module>
  File "compose/cli/main.py", line 81, in main
  File "compose/cli/main.py", line 198, in perform_command
  File "compose/cli/command.py", line 70, in project_from_options
  File "compose/cli/command.py", line 153, in get_project
  File "compose/cli/docker_client.py", line 43, in get_client
  File "compose/cli/docker_client.py", line 170, in docker_client
  File "docker/api/client.py", line 197, in __init__
  File "docker/api/client.py", line 222, in _retrieve_server_version
docker.errors.DockerException: Error while fetching server API version: ('Connection aborted.', PermissionError(13, 'Permission denied'))
[2627170] Failed to execute script docker-compose
```

```shell 
$ sudo docker-compose pull
Traceback (most recent call last):
  File "urllib3/connectionpool.py", line 677, in urlopen
  File "urllib3/connectionpool.py", line 392, in _make_request
  File "http/client.py", line 1277, in request
  File "http/client.py", line 1323, in _send_request
  File "http/client.py", line 1272, in endheaders
  File "http/client.py", line 1032, in _send_output
  File "http/client.py", line 972, in send
  File "docker/transport/unixconn.py", line 43, in connect
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "requests/adapters.py", line 449, in send
  File "urllib3/connectionpool.py", line 727, in urlopen
  File "urllib3/util/retry.py", line 410, in increment
  File "urllib3/packages/six.py", line 734, in reraise
  File "urllib3/connectionpool.py", line 677, in urlopen
  File "urllib3/connectionpool.py", line 392, in _make_request
  File "http/client.py", line 1277, in request
  File "http/client.py", line 1323, in _send_request
  File "http/client.py", line 1272, in endheaders
  File "http/client.py", line 1032, in _send_output
  File "http/client.py", line 972, in send
  File "docker/transport/unixconn.py", line 43, in connect
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionRefusedError(111, 'Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "docker/api/client.py", line 214, in _retrieve_server_version
  File "docker/api/daemon.py", line 181, in version
  File "docker/utils/decorators.py", line 46, in inner
  File "docker/api/client.py", line 237, in _get
  File "requests/sessions.py", line 543, in get
  File "requests/sessions.py", line 530, in request
  File "requests/sessions.py", line 643, in send
  File "requests/adapters.py", line 498, in send
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionRefusedError(111, 'Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "docker-compose", line 3, in <module>
  File "compose/cli/main.py", line 81, in main
  File "compose/cli/main.py", line 198, in perform_command
  File "compose/cli/command.py", line 70, in project_from_options
  File "compose/cli/command.py", line 153, in get_project
  File "compose/cli/docker_client.py", line 43, in get_client
  File "compose/cli/docker_client.py", line 170, in docker_client
  File "docker/api/client.py", line 197, in __init__
  File "docker/api/client.py", line 222, in _retrieve_server_version
docker.errors.DockerException: Error while fetching server API version: ('Connection aborted.', ConnectionRefusedError(111, 'Connection refused'))
[2635269] Failed to execute script docker-compose
```
### Expected result
I expect it to run normally...

### Stacktrace / full error message

```shell
$ sudo docker-compose --log-level DEBUG pull
Using configuration files: ./docker-compose.yml,./docker-compose.override.yml
Traceback (most recent call last):
  File "urllib3/connectionpool.py", line 677, in urlopen
  File "urllib3/connectionpool.py", line 392, in _make_request
  File "http/client.py", line 1277, in request
  File "http/client.py", line 1323, in _send_request
  File "http/client.py", line 1272, in endheaders
  File "http/client.py", line 1032, in _send_output
  File "http/client.py", line 972, in send
  File "docker/transport/unixconn.py", line 43, in connect
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "requests/adapters.py", line 449, in send
  File "urllib3/connectionpool.py", line 727, in urlopen
  File "urllib3/util/retry.py", line 410, in increment
  File "urllib3/packages/six.py", line 734, in reraise
  File "urllib3/connectionpool.py", line 677, in urlopen
  File "urllib3/connectionpool.py", line 392, in _make_request
  File "http/client.py", line 1277, in request
  File "http/client.py", line 1323, in _send_request
  File "http/client.py", line 1272, in endheaders
  File "http/client.py", line 1032, in _send_output
  File "http/client.py", line 972, in send
  File "docker/transport/unixconn.py", line 43, in connect
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionRefusedError(111, 'Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "docker/api/client.py", line 214, in _retrieve_server_version
  File "docker/api/daemon.py", line 181, in version
  File "docker/utils/decorators.py", line 46, in inner
  File "docker/api/client.py", line 237, in _get
  File "requests/sessions.py", line 543, in get
  File "requests/sessions.py", line 530, in request
  File "requests/sessions.py", line 643, in send
  File "requests/adapters.py", line 498, in send
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionRefusedError(111, 'Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "docker-compose", line 3, in <module>
  File "compose/cli/main.py", line 81, in main
  File "compose/cli/main.py", line 198, in perform_command
  File "compose/cli/command.py", line 70, in project_from_options
  File "compose/cli/command.py", line 153, in get_project
  File "compose/cli/docker_client.py", line 43, in get_client
  File "compose/cli/docker_client.py", line 170, in docker_client
  File "docker/api/client.py", line 197, in __init__
  File "docker/api/client.py", line 222, in _retrieve_server_version
docker.errors.DockerException: Error while fetching server API version: ('Connection aborted.', ConnectionRefusedError(111, 'Connection refused'))
[2648069] Failed to execute script docker-compose
| rmukai @ dellsvr1  4:00PM ⟫  ~/netbox-docker/netbox-docker  | release ✔ |
|➜  sudo docker-compose --log-level ERROR pull
Traceback (most recent call last):
  File "urllib3/connectionpool.py", line 677, in urlopen
  File "urllib3/connectionpool.py", line 392, in _make_request
  File "http/client.py", line 1277, in request
  File "http/client.py", line 1323, in _send_request
  File "http/client.py", line 1272, in endheaders
  File "http/client.py", line 1032, in _send_output
  File "http/client.py", line 972, in send
  File "docker/transport/unixconn.py", line 43, in connect
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "requests/adapters.py", line 449, in send
  File "urllib3/connectionpool.py", line 727, in urlopen
  File "urllib3/util/retry.py", line 410, in increment
  File "urllib3/packages/six.py", line 734, in reraise
  File "urllib3/connectionpool.py", line 677, in urlopen
  File "urllib3/connectionpool.py", line 392, in _make_request
  File "http/client.py", line 1277, in request
  File "http/client.py", line 1323, in _send_request
  File "http/client.py", line 1272, in endheaders
  File "http/client.py", line 1032, in _send_output
  File "http/client.py", line 972, in send
  File "docker/transport/unixconn.py", line 43, in connect
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionRefusedError(111, 'Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "docker/api/client.py", line 214, in _retrieve_server_version
  File "docker/api/daemon.py", line 181, in version
  File "docker/utils/decorators.py", line 46, in inner
  File "docker/api/client.py", line 237, in _get
  File "requests/sessions.py", line 543, in get
  File "requests/sessions.py", line 530, in request
  File "requests/sessions.py", line 643, in send
  File "requests/adapters.py", line 498, in send
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionRefusedError(111, 'Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "docker-compose", line 3, in <module>
  File "compose/cli/main.py", line 81, in main
  File "compose/cli/main.py", line 198, in perform_command
  File "compose/cli/command.py", line 70, in project_from_options
  File "compose/cli/command.py", line 153, in get_project
  File "compose/cli/docker_client.py", line 43, in get_client
  File "compose/cli/docker_client.py", line 170, in docker_client
  File "docker/api/client.py", line 197, in __init__
  File "docker/api/client.py", line 222, in _retrieve_server_version
docker.errors.DockerException: Error while fetching server API version: ('Connection aborted.', ConnectionRefusedError(111, 'Connection refused'))
[2648315] Failed to execute script docker-compose
| rmukai @ dellsvr1  4:01PM ⟫  ~/netbox-docker/netbox-docker  | release ✔ |
|➜  
```

## Additional information
OS version / distribution, `docker-compose` install method, etc.

I followed the official documentation as show [here](https://docs.docker.com/compose/install/#install-compose-on-linux-systems) 

## System Summary 
```shell
neofetch
            .-/+oossssoo+/-.               rmukai@<hidden>
        `:+ssssssssssssssssss+:`           ------------------------- 
      -+ssssssssssssssssssyyssss+-         OS: Ubuntu 20.04.2 LTS x86_64 
    .ossssssssssssssssssdMMMNysssso.       Host: PowerEdge R620 
   /ssssssssssshdmmNNmmyNMMMMhssssss/      Kernel: 5.4.0-67-generic 
  +ssssssssshmydMMMMMMMNddddyssssssss+     Uptime: 3 days, 1 hour, 19 mins 
 /sssssssshNMMMyhhyyyyhmNMMMNhssssssss/    Packages: 13 (snap) 
.ssssssssdMMMNhsssssssssshNMMMdssssssss.   Shell: zsh 5.8 
+sssshhhyNMMNyssssssssssssyNMMMysssssss+   Resolution: 1920x1200, 1920x1080, 2560x1080 
ossyNMMMNyMMhsssssssssssssshmmmhssssssso   WM: Mutter 
ossyNMMMNyMMhsssssssssssssshmmmhssssssso   WM Theme: Adwaita 
+sssshhhyNMMNyssssssssssssyNMMMysssssss+   Theme: Adwaita [GTK3] 
.ssssssssdMMMNhsssssssssshNMMMdssssssss.   Icons: Adwaita [GTK3] 
 /sssssssshNMMMyhhyyyyhdNMMMNhssssssss/    Terminal: /dev/pts/1 
  +sssssssssdmydMMMMMMMMddddyssssssss+     CPU: Intel Xeon E5-2643 0 (8) @ 3.500GHz 
   /ssssssssssshdmNNNNmyNMMMMhssssss/      GPU: 0b:00.0 Matrox Electronics Systems Ltd. G200eR2 
    .ossssssssssssssssssdMMMNysssso.       Memory: 989MiB / 64270MiB 
      -+sssssssssssssssssyyyssss+-
        `:+ssssssssssssssssss+:`                                   
            .-/+oossssoo+/-.                                       

```

**Comment by MukaiGuy** [comment]
Today it worked after I ran `which docker-compose`

I am going to close this for now.

**Comment by judicandus** [comment]
> Today it worked after I ran `which docker-compose`
> 
> I am going to close this for now.

I have Terramaster NAS and was having the exact same problem on a Vanilla clean installation with any docker-compose yml. Running `which docker-compose` also solved the problem for me.
