### ISSUE TITLE
Docker Compose 1.28.6 randomly hanging SSH session

### ISSUE THREAD

**Issue by hexcowboy** [docker/compose#8238]
## Description of the issue

Using the `docker-compose` command will randomly hang the SSH session. The conditions for this to happen are unknown but it occurs frequently and manages to fix itself after 1-10 minutes.

## Context information (for bug reports)

**Output of `docker-compose version`**
<details>
<summary>Output</summary>

```
root@ubuntu:~# docker-compose version
docker-compose version 1.28.6, build 5db8d86f
docker-py version: 4.4.4
CPython version: 3.7.10
OpenSSL version: OpenSSL 1.1.0l  10 Sep 2019
```
</details>

**Output of `docker version`**
<details>
<summary>Output</summary>

```
root@ubuntu:~# docker version
Client: Docker Engine - Community
 Version:           20.10.5
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        55c4c88
 Built:             Tue Mar  2 20:18:20 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.5
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       363e9a8
  Built:            Tue Mar  2 20:16:15 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.4
  GitCommit:        05f951a3781f4f2c1911b05e61c160e9c30eaa8e
 runc:
  Version:          1.0.0-rc93
  GitCommit:        12644e614e25b05da6fd08a38ffa0cfe1903fdec
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```
</details>

**Output of `docker-compose config`**
(Make sure to add the relevant `-f` and other flags)
<details>
<summary>Output</summary>

```
synapse:
    environment:
      SYNAPSE_CONFIG_PATH: /data/homeserver.yaml
    image: docker.io/matrixdotorg/synapse:latest
    ports:
    - published: 8008
      target: 8008
    restart: unless-stopped
    volumes:
    - /matrix/files:/data:rw
version: 3
```
</details>

## Steps to reproduce the issue

1. Install Ubuntu 20.04 or Debian 10 default image and do a `apt update && apt upgrade`
2. Install `docker` and `docker-compose` per official documentation
3. Connect over SSH
4. Start using `docker-compose` commands

### Observed result

The `docker-compose` command periodically crashes and hangs the SSH session and doesn't finish executing. I cannot identify what triggers it to hang. I can run the exact same command once and it will execute, other times it will hang. Once the session hangs, it randomly can start functioning again in periods of 1-10 minutes. To close the SSH session I use the `~.` keystroke and reconnect. It has happened with all variety of commands like `docker-compose help`, `docker-compose up`, `docker-compose version`, and more.

### Expected result

Running the `docker-compose` command should not hang.

### Stacktrace / full error message

The following command ran for ~10 minutes until the error was generated.

<details>
<summary>Stack trace</summary>

```
root@ubuntu-synpase:~# docker-compose help
^C^C^C^C
^C
Traceback (most recent call last):
  File "docker-compose", line 2, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "/code/.tox/py37/lib/python3.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 493, in exec_module
  File "compose/cli/main.py", line 13, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "/code/.tox/py37/lib/python3.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 493, in exec_module
  File "docker/__init__.py", line 2, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "/code/.tox/py37/lib/python3.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 493, in exec_module
  File "docker/api/__init__.py", line 2, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "/code/.tox/py37/lib/python3.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 493, in exec_module
  File "docker/api/client.py", line 10, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "/code/.tox/py37/lib/python3.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 493, in exec_module
  File "docker/auth.py", line 9, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "/code/.tox/py37/lib/python3.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 493, in exec_module
  File "docker/utils/__init__.py", line 3, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "/code/.tox/py37/lib/python3.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 493, in exec_module
  File "docker/utils/decorators.py", line 4, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "/code/.tox/py37/lib/python3.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 493, in exec_module
  File "docker/utils/utils.py", line 13, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "/code/.tox/py37/lib/python3.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 493, in exec_module
  File "docker/tls.py", line 5, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "/code/.tox/py37/lib/python3.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 493, in exec_module
  File "docker/transport/__init__.py", line 11, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "/code/.tox/py37/lib/python3.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 493, in exec_module
  File "docker/transport/sshconn.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "/code/.tox/py37/lib/python3.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 493, in exec_module
  File "paramiko/__init__.py", line 22, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "/code/.tox/py37/lib/python3.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 493, in exec_module
  File "paramiko/transport.py", line 90, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "/code/.tox/py37/lib/python3.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 493, in exec_module
  File "paramiko/ed25519key.py", line 22, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "/code/.tox/py37/lib/python3.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 493, in exec_module
  File "nacl/signing.py", line 17, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "/code/.tox/py37/lib/python3.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 493, in exec_module
  File "nacl/bindings/__init__.py", line 423, in <module>
  File "nacl/bindings/sodium_core.py", line 32, in sodium_init
  File "nacl/bindings/sodium_core.py", line 22, in _sodium_init
KeyboardInterrupt
[1709] Failed to execute script docker-compose
```
</details>

## Additional information

Tested on Ubuntu 20.04 and Debian 10 on DigitalOcean. Same results for both. 

Docker installed from the [Ubuntu official documentation](https://docs.docker.com/engine/install/ubuntu/) and also the [Debian official documentation](https://docs.docker.com/engine/install/debian/)

Docker-compose installed from the Linux section of the [official documentation](https://docs.docker.com/compose/install/).

**Comment by marko-x** [comment]
We have similar problems with connecting via ssh. 

Sometimes its working - sometimes it isnt. We cant find any problems.
Since version 1.28 [https://docs.docker.com/compose/release-notes/#1280](Release Notes) we have to use the fallback to use Paramiko to create a connection. 

> Changed the SSH connection approach to the Docker CLI by shelling out to the local SSH client. Set the COMPOSE_PARAMIKO_SSH=1 environment variable to enable the old behavior.

Without setting up the fallback docker-compose cant create any connection at all ("connection refused"). With Paramiko, as i said, sometimes its connecting. Sometimes not.

**Comment by jswny** [comment]
Also having the same problem. I have to kill the SSH session manually to fix it. Commands sometimes work sometimes not. Have seen this with `logs` and `down`.

**Comment by seriousidea** [comment]
I have exactly the same problem.
DigitalOcean, Debian 9, Docker 19.03.15, docker-compose 1.29.1.

**Comment by hexcowboy** [comment]
I have a feeling this may be due to a lack of resources. This issue usually occurs on cloud instances with 1GB memory. I can't find any documentation for what is required to run `docker-compose` so I'm not entirely sure, but usually I never have this problem with 4+ GB of memory.

Closing for now.

**Comment by settermjd** [comment]
I'm having what seems to be a similar issue, however it seems to be from `docker-compose` opening numerous ssh sessions and UFW blocking them periodically. What's interesting is that `docker compose` doesn't have this issue.

**Comment by marko-x** [comment]
@jswny 

> I have to kill the SSH session manually to fix it.

Can you explain how you do this?
