### ISSUE TITLE
Variable interpolation quoted results make integer values fail

### ISSUE THREAD

**Issue by kikito** [docker/compose#8297]
## Description of the issue

docker-compose variable interpolation quotes the result. On the other hand, docker-compose expect some values to be integers. As a result, we cannot use variable interpolation on such integer variables.

## Context information (for bug reports)

**Output of `docker-compose version`**
```
docker-compose version 1.29.0, build 07737305
docker-py version: 5.0.0
CPython version: 3.9.0
OpenSSL version: OpenSSL 1.1.1h  22 Sep 2020
```

**Output of `docker version`**
```
Client: Docker Engine - Community
 Cloud integration: 1.0.12
 Version:           20.10.5
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        55c4c88
 Built:             Tue Mar  2 20:13:00 2021
 OS/Arch:           darwin/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.5
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       363e9a8
  Built:            Tue Mar  2 20:15:47 2021
  OS/Arch:          linux/amd64
  Experimental:     true
 containerd:
  Version:          1.4.4
  GitCommit:        05f951a3781f4f2c1911b05e61c160e9c30eaa8e
 runc:
  Version:          1.0.0-rc93
  GitCommit:        12644e614e25b05da6fd08a38ffa0cfe1903fdec
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

## Steps to reproduce the issue

1. Minimal example showing string interpolation quoted result:

``` sh
$ docker-compose --file - config <<<' 
version: "3.8"
services:
  hello-world:
    image: "hello-world:latest"
    cpu_shares: ${CPU_SHARES:-1024}
'
services:
  hello-world:
    cpu_shares: '1024'
    image: hello-world:latest
version: '3.8'
```

Notice how the `1024` in `cpu_shares` has quotes around it.

2. Attempt to run via `docker-compose up` results in error:

``` sh
docker-compose --file - up <<<'
version: "3.8"
services:
  hello-world:
    image: "hello-world:latest"
    cpu_shares: ${CPU_SHARES:-1024}
'
<SNIP - full logs below>

Creating docker-hello-world_1 ...

ERROR: for docker-hello-world_1  Invalid type for cpu_shares param: expected int but found <class 'str'>

ERROR: for hello-world  Invalid type for cpu_shares param: expected int but found <class 'str'>
Traceback (most recent call last):
<SNIP - full logs below>
```

3. Similar error happens when attempting the experimental `docker compose` command:

``` sh
docker compose --file - config <<<' 
version: "3.8"
services:
  hello-world:
    image: "hello-world:latest"
    cpu_shares: ${CPU_SHARES:-1024}
'
The new 'docker compose' command is currently experimental. To provide feedback or request new features please open issues at https://github.com/docker/compose-cli
1 error(s) decoding:

* 'cpu_shares' expected type 'int64', got unconvertible type 'string', value: '1024'
```

### Observed result

Variable interpolation produces a quoted result which clashes/confuses the integer type variable checking.

### Expected result

Variable interpolation should work for integer types without errors.

### Stacktrace / full error message

Full `docker-compose up` error logs:

``` sh
docker-compose --file - up <<<'
version: "3.8"
services:
  hello-world:
    image: "hello-world:latest"
    cpu_shares: ${CPU_SHARES:-1024}
'
Docker Compose is now in the Docker CLI, try `docker compose up`

WARNING: The Docker Engine you're using is running in swarm mode.

Compose does not use swarm mode to deploy services to multiple nodes in a swarm. All containers will be scheduled on the current node.

To deploy your application across the swarm, use `docker stack deploy`.

Creating docker-hello-world_1 ...

ERROR: for docker-hello-world_1  Invalid type for cpu_shares param: expected int but found <class 'str'>

ERROR: for hello-world  Invalid type for cpu_shares param: expected int but found <class 'str'>
Traceback (most recent call last):
  File "docker-compose", line 3, in <module>
  File "compose/cli/main.py", line 81, in main
  File "compose/cli/main.py", line 202, in perform_command
  File "compose/metrics/decorator.py", line 18, in wrapper
  File "compose/cli/main.py", line 1188, in up
  File "compose/cli/main.py", line 1168, in up
  File "compose/project.py", line 708, in up
  File "compose/parallel.py", line 108, in parallel_execute
  File "compose/parallel.py", line 206, in producer
  File "compose/project.py", line 690, in do
  File "compose/service.py", line 578, in execute_convergence_plan
  File "compose/service.py", line 492, in _execute_convergence_create
  File "compose/parallel.py", line 108, in parallel_execute
  File "compose/parallel.py", line 206, in producer
  File "compose/service.py", line 497, in <lambda>
  File "compose/service.py", line 476, in create_and_start
  File "compose/service.py", line 331, in create_container
  File "compose/service.py", line 957, in _get_container_create_options
  File "compose/service.py", line 1032, in _get_container_host_config
  File "docker/api/container.py", line 598, in create_host_config
  File "docker/types/containers.py", line 448, in __init__
TypeError: Invalid type for cpu_shares param: expected int but found <class 'str'>
[92579] Failed to execute script docker-compose
```

## Additional information

OS: MacOS 10.14.6.

Docker-compose installed via Docker Desktop (v 3.3.1)

## Personal opinion

The fix depends on whether one considers the quotes a "bug" or a "feature".

Removing the quotes on variable interpolation might break docker-compose for people who rely on it for "strings which happen to look like numbers", like a randomly generated password which happens to be all integers. They would have to put quotes around those to fix it.

Alternatively, integer fields like `cpu_shares` could accept both "YAML integers" or "YAML strings that look like integers" (at least when interpolation was used).

Finally, there could be a different syntax for "interpolating without quotes". For example parenthesis instead of brackets: `$(CPU_SHARES:-1024)` would not quote, while `${CPU_SHARES:-1024}` quotes. This trades full backwards compatibility with more complexity in docker-compose.

**Comment by AndreaPro** [comment]
I am experiencing the same issue trying to set an env variable for cpu_shares.

And here there is [another issue reporting the same problem](https://github.com/docker/compose/issues/6580)

**Comment by mcnilz** [comment]
Still an issue. 😢 
Docker Compose version v2.6.0

**Comment by michaelfranzl** [comment]
This is a real limitation and should not be closed.
