### ISSUE TITLE
Add support for spaces in volume mapping

### ISSUE THREAD

**Issue by hamiltont** [docker/compose#832]
Currently fig.yml is required to use this format: 

```
   volumes:
     - /lxc/nginx/sites-available:/etc/nginx/sites-available
     - /lxc/nginx/sites-enabled:/etc/nginx/sites-enabled
     - /lxc/nginx/logs:/var/log/nginx
     - /lxc/shared/certs:/certs
     - /lxc/nginx/nginx.conf:/etc/nginx.conf
```

Instead of the much more readable:

```
   volumes:
     - /lxc/nginx/sites-available:  /etc/nginx/sites-available
     - /lxc/nginx/sites-enabled:    /etc/nginx/sites-enabled
     - /lxc/nginx/logs:             /var/log/nginx
     - /lxc/shared/certs:           /certs
     - /lxc/nginx/nginx.conf:       /etc/nginx.conf
```

If you attempt to use the second format, this error happens: 

```
Creating media_nginx_1...
Traceback (most recent call last):
  File "/usr/local/bin/fig", line 9, in <module>
    load_entry_point('fig==1.0.1', 'console_scripts', 'fig')()
  File "/usr/local/lib/python2.7/dist-packages/fig/cli/main.py", line 31, in main
    command.sys_dispatch()
  File "/usr/local/lib/python2.7/dist-packages/fig/cli/docopt_command.py", line 21, in sys_dispatch
    self.dispatch(sys.argv[1:], None)
  File "/usr/local/lib/python2.7/dist-packages/fig/cli/command.py", line 28, in dispatch
    super(Command, self).dispatch(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/fig/cli/docopt_command.py", line 24, in dispatch
    self.perform_command(*self.parse(argv, global_options))
  File "/usr/local/lib/python2.7/dist-packages/fig/cli/command.py", line 56, in perform_command
    handler(project, command_options)
  File "/usr/local/lib/python2.7/dist-packages/fig/cli/main.py", line 427, in up
    insecure_registry=insecure_registry,
  File "/usr/local/lib/python2.7/dist-packages/fig/project.py", line 174, in up
    for (_, container) in service.recreate_containers(insecure_registry=insecure_registry):
  File "/usr/local/lib/python2.7/dist-packages/fig/service.py", line 199, in recreate_containers
    container = self.create_container(insecure_registry=insecure_registry, **override_options)
  File "/usr/local/lib/python2.7/dist-packages/fig/service.py", line 176, in create_container
    container_options = self._get_container_create_options(override_options, one_off=one_off)
  File "/usr/local/lib/python2.7/dist-packages/fig/service.py", line 366, in _get_container_create_options
    for v in container_options['volumes'])
  File "/usr/local/lib/python2.7/dist-packages/fig/service.py", line 366, in <genexpr>
    for v in container_options['volumes'])
  File "/usr/local/lib/python2.7/dist-packages/fig/service.py", line 470, in parse_volume_spec
    parts = volume_config.split(':')
AttributeError: 'dict' object has no attribute 'split'
```

**Comment by dnephin** [comment]
The error is because the yaml parser interprets these as dicts instead of string. 

What happens if you quote them?

```
  volumes:
     - "/lxc/nginx/sites-available:  /etc/nginx/sites-available"
     - "/lxc/nginx/sites-enabled:    /etc/nginx/sites-enabled"
     - "/lxc/nginx/logs:             /var/log/nginx"
     - "/lxc/shared/certs:           /certs"
     - "/lxc/nginx/nginx.conf:       /etc/nginx.conf"
```

It might still require a `strip()` somewhere, but that is something that can be fixed.  The yaml parser is probably correct in it's parsing of the file.

**Comment by hamiltont** [comment]
If I quote them, fig does not report any errors, but those volumes are also not mounted inside of the container. If I'm reading the verbose output correctly, the lack of error reporting is mainly because there's no feedback coming from the docker daemon that the mount failed. 

I suppose there are two fixes - either require the quotations to force a string, and add in the necessary trimming calls, or check if the given type is a dict and flatten the nested dicts into the proper string type (which is more complex, but perhaps slightly more readable. I'm open to either method

PS - for what it's worth, the more readable approach works out of the box in maestro-ng, no quotations needed. I don't know if they are forcing their parser to intentionally mis-read the YAML spec or if they are flattening the dictionaries
