### ISSUE TITLE
Environmental variable value escaping

### ISSUE THREAD

**Issue by europ** [docker/compose#8330]
### Feature

Add an option to escape variable value.

### About

Docker compose does not escape variable values that are stored in environment variable files directly in compose file.

### Related documentation

* https://docs.docker.com/compose/environment-variables/
* https://docs.docker.com/compose/compose-file/compose-file-v3/#variable-substitution

### Inspiration

Bash does support variable content escaping, see the docs - https://www.gnu.org/savannah-checkouts/gnu/bash/manual/bash.html#Shell-Parameter-Expansion.

```
$ TEST_VAR="aaa=bbb'ccc\"ddd$eee@fff#ggg"
$ echo $TEST_VAR
aaa=bbb'ccc"ddd@fff#ggg
$ echo ${TEST_VAR@Q}
'aaa=bbb'\''ccc"ddd@fff#ggg'
```

### Problem

Content of `.env` file:
```
FILE_DOTENV_VAR=aaa=bbb'ccc"ddd$eee@fff#ggg
```

Content of `docker-compose.yml` file:
```yaml
--
version: '3.9'
services:
  custom_service:
    image: oraclelinux:8
    command: >
      bash -c '
          set -x \
          && echo ${FILE_DOTENV_VAR} \
          && cat <<< ${FILE_DOTENV_VAR} \
          && true
      '
```

Result:
```console
$ docker-compose up
Creating test_custom_service_1 ... 

ERROR: for test_custom_service_1  No closing quotation

ERROR: for custom_service  No closing quotation
Traceback (most recent call last):
  File "docker-compose", line 3, in <module>
  File "compose/cli/main.py", line 81, in main
  File "compose/cli/main.py", line 203, in perform_command
  File "compose/metrics/decorator.py", line 18, in wrapper
  File "compose/cli/main.py", line 1189, in up
  File "compose/cli/main.py", line 1185, in up
  File "compose/project.py", line 702, in up
  File "compose/parallel.py", line 108, in parallel_execute
  File "compose/parallel.py", line 206, in producer
  File "compose/project.py", line 688, in do
  File "compose/service.py", line 581, in execute_convergence_plan
  File "compose/service.py", line 503, in _execute_convergence_recreate
  File "compose/parallel.py", line 108, in parallel_execute
  File "compose/parallel.py", line 206, in producer
  File "compose/service.py", line 496, in recreate
  File "compose/service.py", line 615, in recreate_container
  File "compose/service.py", line 341, in create_container
  File "compose/container.py", line 48, in create
  File "docker/api/container.py", line 428, in create_container
  File "docker/api/container.py", line 433, in create_container_config
  File "docker/types/containers.py", line 703, in __init__
  File "docker/utils/utils.py", line 464, in split_command
  File "shlex.py", line 310, in split
  File "shlex.py", line 299, in __next__
  File "shlex.py", line 109, in get_token
  File "shlex.py", line 191, in read_token
ValueError: No closing quotation
[54859] Failed to execute script docker-compose
```

### Workaround

Content of `.env` file:
```
FILE_DOTENV_VAR=aaa=bbb'ccc"ddd$eee@fff#ggg
```

Content of `docker-compose.yml` file:
```yaml
---
version: '3.9'
services:
  custom_service:
    image: oraclelinux:8
    environment:
      - CNTNR_ENV_VAR=${FILE_DOTENV_VAR}
    command: >
      bash -c '
          set -x \
          && echo $${CNTNR_ENV_VAR} \
          && cat <<< $${CNTNR_ENV_VAR}
      '
```

Result:
```console
$ docker-compose up
Creating test_custom_service_1 ... done
Attaching to test_custom_service_1
custom_service_1  | + echo 'aaa=bbb'\''ccc"ddd$eee@fff#ggg'
custom_service_1  | aaa=bbb'ccc"ddd$eee@fff#ggg
custom_service_1  | + cat
custom_service_1  | aaa=bbb'ccc"ddd$eee@fff#ggg
custom_service_1  | + true
test_custom_service_1 exited with code 0
```

**Comment by europ** [comment]
ping
