### ISSUE TITLE
ImportError: cannot import name 'ContextAPI'

### ISSUE THREAD

**Issue by immanishbainsla** [docker/compose#8366]
## Description of the issue
when running docker-compose up or docker-compose build 
error is: 
```
Traceback (most recent call last):
  File "/home/mbainsla/.local/bin/docker-compose", line 5, in <module>
    from compose.cli.main import main
  File "/home/mbainsla/.local/lib/python3.6/site-packages/compose/cli/main.py", line 28, in <module>
    from ..metrics.decorator import metrics
  File "/home/mbainsla/.local/lib/python3.6/site-packages/compose/metrics/decorator.py", line 3, in <module>
    from compose.metrics.client import MetricsCommand
  File "/home/mbainsla/.local/lib/python3.6/site-packages/compose/metrics/client.py", line 5, in <module>
    from docker import ContextAPI
ImportError: cannot import name 'ContextAPI'
```
## Context information (for bug reports)
my docker-compose.yml file contains
```
version: '3'

services: 
    web: 
        build: .
        command: python manage.py runserver 0.0.0.0:8000
        ports: 
            - 8000:8000
```

my Dockerfile contains 
```
FROM python:3

ENV PYTHONUNBUFFERED=1

WORKDIR /app

ADD . /app

COPY ./requirements.txt /app/requirements.txt

RUN pip install -r requirements.txt

COPY . /app
```

**Output of `docker-compose version`**
```
Traceback (most recent call last):
  File "/home/mbainsla/.local/bin/docker-compose", line 5, in <module>
    from compose.cli.main import main
  File "/home/mbainsla/.local/lib/python3.6/site-packages/compose/cli/main.py", line 28, in <module>
    from ..metrics.decorator import metrics
  File "/home/mbainsla/.local/lib/python3.6/site-packages/compose/metrics/decorator.py", line 3, in <module>
    from compose.metrics.client import MetricsCommand
  File "/home/mbainsla/.local/lib/python3.6/site-packages/compose/metrics/client.py", line 5, in <module>
    from docker import ContextAPI
ImportError: cannot import name 'ContextAPI'
```

**Output of `docker version`**
```
Client:
 Version:           19.03.13
 API version:       1.40
 Go version:        go1.15.1
 Git commit:        4484c46
 Built:             Fri Oct  2 19:31:30 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          19.03.13
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.15.1
  Git commit:       4484c46
  Built:            Fri Oct  2 00:00:00 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.3
  GitCommit:        269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc:
  Version:          1.0.0-rc92
  GitCommit:        ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 docker-init:
  Version:          0.18.0
  GitCommit:        
```

**Output of `docker-compose config`**
(Make sure to add the relevant `-f` and other flags)
```
Traceback (most recent call last):
  File "/home/mbainsla/.local/bin/docker-compose", line 5, in <module>
    from compose.cli.main import main
  File "/home/mbainsla/.local/lib/python3.6/site-packages/compose/cli/main.py", line 28, in <module>
    from ..metrics.decorator import metrics
  File "/home/mbainsla/.local/lib/python3.6/site-packages/compose/metrics/decorator.py", line 3, in <module>
    from compose.metrics.client import MetricsCommand
  File "/home/mbainsla/.local/lib/python3.6/site-packages/compose/metrics/client.py", line 5, in <module>
    from docker import ContextAPI
ImportError: cannot import name 'ContextAPI'
(env) [mbainsla@localhost urlshortener]$ docker-compose config -f
Traceback (most recent call last):
  File "/home/mbainsla/.local/bin/docker-compose", line 5, in <module>
    from compose.cli.main import main
  File "/home/mbainsla/.local/lib/python3.6/site-packages/compose/cli/main.py", line 28, in <module>
    from ..metrics.decorator import metrics
  File "/home/mbainsla/.local/lib/python3.6/site-packages/compose/metrics/decorator.py", line 3, in <module>
    from compose.metrics.client import MetricsCommand
  File "/home/mbainsla/.local/lib/python3.6/site-packages/compose/metrics/client.py", line 5, in <module>
    from docker import ContextAPI
ImportError: cannot import name 'ContextAPI'
```

## Steps to reproduce the issue

1. clone this repo : https://github.com/immanishbainsla/url-shortener
2. run : docker-compose up

### Observed result
```
Traceback (most recent call last):
  File "/home/mbainsla/.local/bin/docker-compose", line 5, in <module>
    from compose.cli.main import main
  File "/home/mbainsla/.local/lib/python3.6/site-packages/compose/cli/main.py", line 28, in <module>
    from ..metrics.decorator import metrics
  File "/home/mbainsla/.local/lib/python3.6/site-packages/compose/metrics/decorator.py", line 3, in <module>
    from compose.metrics.client import MetricsCommand
  File "/home/mbainsla/.local/lib/python3.6/site-packages/compose/metrics/client.py", line 5, in <module>
    from docker import ContextAPI
ImportError: cannot import name 'ContextAPI'
```
### Expected result
should build app

### Stacktrace / full error message

```
Traceback (most recent call last):
  File "/home/mbainsla/.local/bin/docker-compose", line 5, in <module>
    from compose.cli.main import main
  File "/home/mbainsla/.local/lib/python3.6/site-packages/compose/cli/main.py", line 28, in <module>
    from ..metrics.decorator import metrics
  File "/home/mbainsla/.local/lib/python3.6/site-packages/compose/metrics/decorator.py", line 3, in <module>
    from compose.metrics.client import MetricsCommand
  File "/home/mbainsla/.local/lib/python3.6/site-packages/compose/metrics/client.py", line 5, in <module>
    from docker import ContextAPI
ImportError: cannot import name 'ContextAPI'
```

## Additional information

OS version / distribution, `docker-compose` install method, etc.
Fedora 33 / Docker version 19.03.13, build 4484c46

**Comment by pauljohnt** [comment]
I ran into this recently. Turns out I had installed `docker-py` from pypi which has not been updated since 2016.

Install `docker` from pypi instead. The latest version as of this comment is 5.0.0. I hope this works for you.

**Comment by samartha-kar23** [comment]
I had `docker-py` as well as `docker==5.0.3` and encountered this problem. Suggest removing `docker-py`. 
```
ubuntu$ pip freeze | grep docker
docker==5.0.3                 <-----keep
docker-compose==1.29.2
docker-py==1.10.6          <-----remove
docker-pycreds==0.4.0
dockerpty==0.4.1
```
