### ISSUE TITLE
Problem trying to run docker-compose up|pull|build

### ISSUE THREAD

**Issue by ambersariya** [docker/compose#8378]
## Description of the issue

Seeing a stack trace when trying to run any of the following commands:

docker-compose up
docker-compose pull
docker-compose build

trying to run the above with `sudo` works but this should have to be this way as I've followed the post-install steps for Linux and added my current user to the docker group.

Running docker run hello-world works fine.

Note: I've had this problem after upgrading from Ubuntu 20.04 to 21.04 and have reinstalled docker-compose to ensure i had the latest binary at the time.

## Context information (for bug reports)

**Output of `docker-compose version`**
```
docker-compose version 1.29.2, build 5becea4c
docker-py version: 5.0.0
CPython version: 3.7.10
OpenSSL version: OpenSSL 1.1.0l  10 Sep 2019

```

**Output of `docker version`**
```
Client: Docker Engine - Community
 Version:           20.10.7
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        f0df350
 Built:             Wed Jun  2 12:00:45 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.7
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       b0f5bc3
  Built:            Wed Jun  2 11:58:56 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.6
  GitCommit:        d71fcd7d8303cbf684402823e425e9dd2e99285d
 runc:
  Version:          1.0.0-rc95
  GitCommit:        b9ee9c6314599f1b4a7f497e1f1f856fe433d3b7
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Output of `docker-compose config`**
(Make sure to add the relevant `-f` and other flags)
```
services:
  hello-world:
    image: hello-world:latest
version: '3.0'
```

## Steps to reproduce the issue
From the project directory

1. docker-compose up

### Observed result
```
Traceback (most recent call last):
  File "docker-compose", line 3, in <module>
  File "compose/cli/main.py", line 81, in main
  File "compose/cli/main.py", line 200, in perform_command
  File "compose/cli/command.py", line 70, in project_from_options
  File "compose/cli/command.py", line 153, in get_project
  File "compose/cli/docker_client.py", line 43, in get_client
  File "compose/cli/docker_client.py", line 170, in docker_client
  File "docker/api/client.py", line 132, in __init__
  File "docker/auth.py", line 361, in load_config
  File "docker/auth.py", line 185, in load_config
  File "docker/auth.py", line 141, in parse_auth
  File "docker/auth.py", line 335, in decode_auth
ValueError: not enough values to unpack (expected 2, got 1)
[26847] Failed to execute script docker-compose
```

### Expected result

This is if I run `docker-compose up` with `sudo` as the current user is added to the docker group on linux

```
Starting docker_hello-world_1 ... done
Attaching to docker_hello-world_1
hello-world_1  | 
hello-world_1  | Hello from Docker!
hello-world_1  | This message shows that your installation appears to be working correctly.
hello-world_1  | 
hello-world_1  | To generate this message, Docker took the following steps:
hello-world_1  |  1. The Docker client contacted the Docker daemon.
hello-world_1  |  2. The Docker daemon pulled the "hello-world" image from the Docker Hub.
hello-world_1  |     (amd64)
hello-world_1  |  3. The Docker daemon created a new container from that image which runs the
hello-world_1  |     executable that produces the output you are currently reading.
hello-world_1  |  4. The Docker daemon streamed that output to the Docker client, which sent it
hello-world_1  |     to your terminal.
hello-world_1  | 
hello-world_1  | To try something more ambitious, you can run an Ubuntu container with:
hello-world_1  |  $ docker run -it ubuntu bash
hello-world_1  | 
hello-world_1  | Share images, automate workflows, and more with a free Docker ID:
hello-world_1  |  https://hub.docker.com/
hello-world_1  | 
hello-world_1  | For more examples and ideas, visit:
hello-world_1  |  https://docs.docker.com/get-started/
hello-world_1  | 
docker_hello-world_1 exited with code 0
```

### Stacktrace / full error message

```
Traceback (most recent call last):
  File "docker-compose", line 3, in <module>
  File "compose/cli/main.py", line 81, in main
  File "compose/cli/main.py", line 200, in perform_command
  File "compose/cli/command.py", line 70, in project_from_options
  File "compose/cli/command.py", line 153, in get_project
  File "compose/cli/docker_client.py", line 43, in get_client
  File "compose/cli/docker_client.py", line 170, in docker_client
  File "docker/api/client.py", line 132, in __init__
  File "docker/auth.py", line 361, in load_config
  File "docker/auth.py", line 185, in load_config
  File "docker/auth.py", line 141, in parse_auth
  File "docker/auth.py", line 335, in decode_auth
ValueError: not enough values to unpack (expected 2, got 1)
[26847] Failed to execute script docker-compose

```

## Additional information

OS version / distribution, `docker-compose` install method, etc.

Install method: https://docs.docker.com/engine/install/ubuntu/#install-using-the-repository + post install steps ran

**Comment by metalsheep** [comment]
For future people who find their way here: your Docker daemon probably isn't running if you get this behavior.  Make sure docker is on and hopefully we can get some more useful error messages in the future.

**Comment by Tubar2** [comment]
> Just in case it helps someone else, this problem can occur if you have a `~/.docker/config.json` with a malformed `auths` entry. In my case, due to some faulty automation, the file had been created with the following contents:
> 
> { "auths": { "https://index.docker.io/v1/": { "auth": "" }}}
> The empty string value of `auth` is incorrect and decoding it fails.

For me this is exactly what happened and all I did to fix was remove the `auth` portion, resulting only in:
```
"auths": {
		"https://index.docker.io/v1/": {}
	}
```
