### ISSUE TITLE
ERROR `docker-compose up` (beginner/macos)

### ISSUE THREAD

**Issue by molleweide** [docker/compose#8380]
Hi,

I stumbled upon the error attached below when running `docker-compose up` and I wanted to ask anyone here if anyone else has seen this? This is the first time I use docker and I am setting up a wordpress site. Maybe there is an obvious solution. Please tell me if I should provide additional info. I am super excited to learn how this works!

`OS  macos mojave`

How I installed docker
```
brew install docker docker-compose
brew install --cask docker
```
---
### What I have tried
 read and follow
    - https://github.com/docker/compose/issues/7896
    -  https://stackoverflow.com/questions/44084846/cannot-connect-to-the-docker-daemon-on-macos
---    

```
Output of "docker-compose version"
docker-compose version 1.29.2, build unknown
```

```
Output of "docker version"
Docker version 20.10.7, build f0df35096d
```

```
Output of "docker ps"
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
```

```
Output of "docker-compose config"
services:
  db:
    command:
    - --default_authentication_plugin=mysql_native_password
    - --character-set-server=utf8mb4
    - --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_ROOT_PASSWORD: password
    image: mysql:latest
    ports:
    - 127.0.0.1:3306:3306/tcp
    volumes:
    - /Users/hjalmarjakobsson/code/wordpress-docker-compose/wp-data:/docker-entrypoint-initdb.d:rw
    - db_data:/var/lib/mysql:rw
  pma:
    environment:
      MYSQL_ROOT_PASSWORD: password
      PMA_HOST: db
      PMA_PORT: 3306
    image: phpmyadmin/phpmyadmin
    links:
    - db:db
    ports:
    - 127.0.0.1:8080:80/tcp
  wp:
    depends_on:
      db:
        condition: service_started
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_DB_USER: root
    image: wordpress:latest
    links:
    - db
    ports:
    - 127.0.0.1:80:80/tcp
    volumes:
    - /Users/hjalmarjakobsson/code/wordpress-docker-compose/config/php.conf.ini:/usr/local/etc/php/conf.d/conf.ini:rw
    - /Users/hjalmarjakobsson/code/wordpress-docker-compose/wp-app:/var/www/html:rw
  wpcli:
    depends_on:
      db:
        condition: service_started
      wp:
        condition: service_started
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_DB_USER: root
    image: wordpress:cli
    volumes:
    - /Users/hjalmarjakobsson/code/wordpress-docker-compose/config/php.conf.ini:/usr/local/etc/php/conf.d/conf.ini:rw
    - /Users/hjalmarjakobsson/code/wordpress-docker-compose/wp-app:/var/www/html:rw
version: '3'
volumes:
  db_data: {}
```
## the error 
```
╰ docker-compose up
Traceback (most recent call last):
  File "/usr/local/Cellar/docker-compose/1.29.2/libexec/lib/python3.9/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/Cellar/docker-compose/1.29.2/libexec/lib/python3.9/site-packages/urllib3/connectionpool.py", line 394, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/local/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1253, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1299, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1248, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1008, in _send_output
    self.send(msg)
  File "/usr/local/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 948, in send
    self.connect()
  File "/usr/local/Cellar/docker-compose/1.29.2/libexec/lib/python3.9/site-packages/docker/transport/unixconn.py", line 43, in connect
    sock.connect(self.unix_socket)
FileNotFoundError: [Errno 2] No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Cellar/docker-compose/1.29.2/libexec/lib/python3.9/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/local/Cellar/docker-compose/1.29.2/libexec/lib/python3.9/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/usr/local/Cellar/docker-compose/1.29.2/libexec/lib/python3.9/site-packages/urllib3/util/retry.py", line 532, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/local/Cellar/docker-compose/1.29.2/libexec/lib/python3.9/site-packages/urllib3/packages/six.py", line 734, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/Cellar/docker-compose/1.29.2/libexec/lib/python3.9/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/Cellar/docker-compose/1.29.2/libexec/lib/python3.9/site-packages/urllib3/connectionpool.py", line 394, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/local/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1253, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1299, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1248, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1008, in _send_output
    self.send(msg)
  File "/usr/local/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 948, in send
    self.connect()
  File "/usr/local/Cellar/docker-compose/1.29.2/libexec/lib/python3.9/site-packages/docker/transport/unixconn.py", line 43, in connect
    sock.connect(self.unix_socket)
urllib3.exceptions.ProtocolError: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Cellar/docker-compose/1.29.2/libexec/lib/python3.9/site-packages/docker/api/client.py", line 214, in _retrieve_server_version
    return self.version(api_version=False)["ApiVersion"]
  File "/usr/local/Cellar/docker-compose/1.29.2/libexec/lib/python3.9/site-packages/docker/api/daemon.py", line 181, in version
    return self._result(self._get(url), json=True)
  File "/usr/local/Cellar/docker-compose/1.29.2/libexec/lib/python3.9/site-packages/docker/utils/decorators.py", line 46, in inner
    return f(self, *args, **kwargs)
  File "/usr/local/Cellar/docker-compose/1.29.2/libexec/lib/python3.9/site-packages/docker/api/client.py", line 237, in _get
    return self.get(url, **self._set_request_timeout(kwargs))
  File "/usr/local/Cellar/docker-compose/1.29.2/libexec/lib/python3.9/site-packages/requests/sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/Cellar/docker-compose/1.29.2/libexec/lib/python3.9/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/Cellar/docker-compose/1.29.2/libexec/lib/python3.9/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/Cellar/docker-compose/1.29.2/libexec/lib/python3.9/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/docker-compose", line 33, in <module>
    sys.exit(load_entry_point('docker-compose==1.29.2', 'console_scripts', 'docker-compose')())
  File "/usr/local/Cellar/docker-compose/1.29.2/libexec/lib/python3.9/site-packages/compose/cli/main.py", line 81, in main
    command_func()
  File "/usr/local/Cellar/docker-compose/1.29.2/libexec/lib/python3.9/site-packages/compose/cli/main.py", line 200, in perform_command
    project = project_from_options('.', options)
  File "/usr/local/Cellar/docker-compose/1.29.2/libexec/lib/python3.9/site-packages/compose/cli/command.py", line 60, in project_from_options
    return get_project(
  File "/usr/local/Cellar/docker-compose/1.29.2/libexec/lib/python3.9/site-packages/compose/cli/command.py", line 152, in get_project
    client = get_client(
  File "/usr/local/Cellar/docker-compose/1.29.2/libexec/lib/python3.9/site-packages/compose/cli/docker_client.py", line 41, in get_client
    client = docker_client(
  File "/usr/local/Cellar/docker-compose/1.29.2/libexec/lib/python3.9/site-packages/compose/cli/docker_client.py", line 170, in docker_client
    client = APIClient(use_ssh_client=not use_paramiko_ssh, **kwargs)
  File "/usr/local/Cellar/docker-compose/1.29.2/libexec/lib/python3.9/site-packages/docker/api/client.py", line 197, in __init__
    self._version = self._retrieve_server_version()
  File "/usr/local/Cellar/docker-compose/1.29.2/libexec/lib/python3.9/site-packages/docker/api/client.py", line 221, in _retrieve_server_version
    raise DockerException(
docker.errors.DockerException: Error while fetching server API version: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))
```

**Comment by molleweide** [comment]
i found this issue also now which seems to be the same so i am going to read through it and get back.
https://github.com/docker/compose/issues/7896

**Comment by molleweide** [comment]
> How I installed docker
> 
> ```
> brew install docker docker-compose
> brew install --cask docker
> ```

SOLVED

1. `brew uninstall docker docker-compose`
2. then run `brew install --cask docker`

I thought you could use only the docker and docker-compose package but it turns out
you only should install the cask, and nothing else.
