### ISSUE TITLE
how can i fix it

### ISSUE THREAD

**Issue by Tilek0** [docker/compose#8405]
sudo docker-compose exec mysql bash
Traceback (most recent call last):
  File "docker\api\client.py", line 214, in _retrieve_server_version
  File "docker\api\daemon.py", line 181, in version
  File "docker\utils\decorators.py", line 46, in inner
  File "docker\api\client.py", line 237, in _get
  File "requests\sessions.py", line 543, in get
  File "requests\sessions.py", line 530, in request
  File "requests\sessions.py", line 643, in send
  File "requests\adapters.py", line 439, in send
  File "urllib3\connectionpool.py", line 670, in urlopen
  File "urllib3\connectionpool.py", line 392, in _make_request
  File "http\client.py", line 1255, in request
  File "http\client.py", line 1301, in _send_request
  File "http\client.py", line 1250, in endheaders
  File "http\client.py", line 1010, in _send_output
  File "http\client.py", line 950, in send
  File "docker\transport\npipeconn.py", line 32, in connect
  File "docker\transport\npipesocket.py", line 23, in wrapped
  File "docker\transport\npipesocket.py", line 72, in connect
  File "docker\transport\npipesocket.py", line 52, in connect

**Comment by Tilek0** [comment]
when i try: sudo docker-compose exec mysql bash vs-code returned next errors

**Comment by metalsheep** [comment]
For future people who find their way here: your Docker daemon probably isn't running if you get this behavior.  Make sure docker is on and hopefully we can get some more useful error messages in the future.
