### ISSUE TITLE
Environment.from_env_file is broken

### ISSUE THREAD

**Issue by POD666** [docker/compose#8423]
## Description of the issue
I have a custom wrapper around docker-compose and just encountered an issue after I updated from 1.27
```
DEPLOYMENT_ROOT="/root/deployment/"
CURRENT_CONF_FILE="current.env"

Environment.from_env_file(DEPLOYMENT_ROOT, CURRENT_CONF_FILE)

Traceback (most recent call last):
...
File "/usr/local/lib/python3.6/site-packages/compose/config/environment.py", line 67, in from_env_file
    instance = _initialize()
  File "/usr/local/lib/python3.6/site-packages/compose/config/environment.py", line 58, in _initialize
    return cls(env_vars_from_file(env_file_path))
  File "/usr/local/lib/python3.6/site-packages/compose/config/environment.py", line 34, in env_vars_from_file
    raise EnvFileNotFound("Couldn't find env file: {}".format(filename))
compose.config.errors.EnvFileNotFound: Couldn't find env file: /root/.env
```

## Context information (for bug reports)
It worked perfectly with this implementation in 1.27.*
https://github.com/docker/compose/blob/1.27.x/compose/config/environment.py#L51
But the new implementation doesn't work as expected:
https://github.com/docker/compose/blob/1.28.x/compose/config/environment.py#L54-L60

**Comment by asolopovas** [comment]
+1
