### ISSUE TITLE
`--skip-hostname-check` and `--tlsverify` are ignored

### ISSUE THREAD

**Issue by corewidedevops** [docker/compose#8452]
## Description of the issue

`--skip-hostname-check` option is ignored in TLS connections to remote Docker Engine.

## Context information (for bug reports)

Version:

```
docker-compose version 1.29.2, build 5becea4c
docker-py version: 5.0.0
CPython version: 3.7.10
OpenSSL version: OpenSSL 1.1.0l  10 Sep 2019
```

**Output of `docker version`**
```
Client: Docker Engine - Community
 Cloud integration: 1.0.17
 Version:           20.10.5
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        55c4c88
 Built:             Tue Mar  2 20:18:20 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.5
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       363e9a8
  Built:            Tue Mar  2 20:16:15 2021
  OS/Arch:          linux/amd64
  Experimental:     true
 containerd:
  Version:          1.4.4
  GitCommit:        05f951a3781f4f2c1911b05e61c160e9c30eaa8e
 runc:
  Version:          1.0.0-rc93
  GitCommit:        12644e614e25b05da6fd08a38ffa0cfe1903fdec
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Output of `docker-compose config`**

Irrelevant

## Steps to reproduce the issue

Attempt to connect to a remote Docker API via TLS.

```bash
# export DOCKER_HOST=tcp://x.x.x.x:2376
# docker-compose --tlsverify=false ps # --tlsverify=false is not even supported (throws help text):
# export DOCKER_TLS_VERIFY=1
# docker-compose --skip-hostname-check ps
```

### Observed result

`docker-compose --skip-hostname-check ps` fails to connect to the remote Docker Engine via TLS because of mismatching hostnames in certificates:

```bash
# docker-compose --skip-hostname-check ps
...
requests.exceptions.SSLError: HTTPSConnectionPool(host='x.x.x.x', port=2376): Max retries exceeded with url: /version (Caused by SSLError(SSLCertVerificationError("hostname 'x.x.x.x' doesn't match either of 'z.z.z.z', 'y.y.y.y'",))
```

### Expected result

`docker-compose --skip-hostname-check ps` connects successfully to the remote Docker Engine via TLS ignoring mismatching hostnames in certificates and shows running containers in the stack.

Here is what it looks like with plain `docker` CLI - setting the endpoint, ensuring TLS, then using TLS without verification:

```bash
# export DOCKER_HOST=tcp://x.x.x.x:2376
# docker ps
Error response from daemon: Client sent an HTTP request to an HTTPS server.
# export DOCKER_TLS_VERIFY=1
# docker ps
error during connect: Get https://x.x.x.x:2376/v1.24/containers/json: x509: certificate is valid for z.z.z.z, not x.x.x.x
# docker --tlsverify=false ps
CONTAINER ID   IMAGE     COMMAND   CREATED   STATUS    PORTS     NAMES
...
```

### Stacktrace / full error message

```bash
# export DOCKER_HOST=tcp://x.x.x.x:2376
# docker-compose --tlsverify --skip-hostname-check ps
Traceback (most recent call last):
  File "docker/api/client.py", line 268, in _raise_for_status
  File "requests/models.py", line 941, in raise_for_status
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: http://x.x.x.x:2376/version

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "docker/api/client.py", line 214, in _retrieve_server_version
  File "docker/api/daemon.py", line 181, in version
  File "docker/api/client.py", line 274, in _result
  File "docker/api/client.py", line 270, in _raise_for_status
  File "docker/errors.py", line 31, in create_api_error_from_http_exception
docker.errors.APIError: 400 Client Error for http://x.x.x.x:2376/version: Bad Request ("b'Client sent an HTTP request to an HTTPS server.'")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "docker-compose", line 3, in <module>
  File "compose/cli/main.py", line 81, in main
  File "compose/cli/main.py", line 200, in perform_command
  File "compose/cli/command.py", line 70, in project_from_options
  File "compose/cli/command.py", line 153, in get_project
  File "compose/cli/docker_client.py", line 43, in get_client
  File "compose/cli/docker_client.py", line 170, in docker_client
  File "docker/api/client.py", line 197, in __init__
  File "docker/api/client.py", line 222, in _retrieve_server_version
docker.errors.DockerException: Error while fetching server API version: 400 Client Error for http://x.x.x.x:2376/version: Bad Request ("b'Client sent an HTTP request to an HTTPS server.'")
[1372600] Failed to execute script docker-compose

# export DOCKER_TLS_VERIFY=1
# docker-compose --skip-hostname-check ps
Traceback (most recent call last):
  File "urllib3/connectionpool.py", line 677, in urlopen
  File "urllib3/connectionpool.py", line 381, in _make_request
  File "urllib3/connectionpool.py", line 978, in _validate_conn
  File "urllib3/connection.py", line 397, in connect
  File "urllib3/connection.py", line 407, in _match_hostname
  File "ssl.py", line 334, in match_hostname
ssl.SSLCertVerificationError: ("hostname 'x.x.x.x' doesn't match either of 'z.z.z.z', 'y.y.y.y'",)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "requests/adapters.py", line 449, in send
  File "urllib3/connectionpool.py", line 727, in urlopen
  File "urllib3/util/retry.py", line 446, in increment
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='x.x.x.x', port=2376): Max retries exceeded with url: /version (Caused by SSLError(SSLCertVerificationError("hostname 'x.x.x.x' doesn't match either of 'z.z.z.z', 'y.y.y.y'",))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "docker/api/client.py", line 214, in _retrieve_server_version
  File "docker/api/daemon.py", line 181, in version
  File "docker/utils/decorators.py", line 46, in inner
  File "docker/api/client.py", line 237, in _get
  File "requests/sessions.py", line 543, in get
  File "requests/sessions.py", line 530, in request
  File "requests/sessions.py", line 643, in send
  File "requests/adapters.py", line 514, in send
requests.exceptions.SSLError: HTTPSConnectionPool(host='x.x.x.x', port=2376): Max retries exceeded with url: /version (Caused by SSLError(SSLCertVerificationError("hostname 'x.x.x.x' doesn't match either of 'z.z.z.z', 'y.y.y.y'",))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "docker-compose", line 3, in <module>
  File "compose/cli/main.py", line 81, in main
  File "compose/cli/main.py", line 200, in perform_command
  File "compose/cli/command.py", line 70, in project_from_options
  File "compose/cli/command.py", line 153, in get_project
  File "compose/cli/docker_client.py", line 43, in get_client
  File "compose/cli/docker_client.py", line 170, in docker_client
  File "docker/api/client.py", line 197, in __init__
  File "docker/api/client.py", line 222, in _retrieve_server_version
docker.errors.DockerException: Error while fetching server API version: HTTPSConnectionPool(host='x.x.x.x', port=2376): Max retries exceeded with url: /version (Caused by SSLError(SSLCertVerificationError("hostname 'x.x.x.x' doesn't match either of 'z.z.z.z', 'y.y.y.y'",))
[1372969] Failed to execute script docker-compose
```

## Additional information

OS: Ubuntu 20.04.2
 `docker-compose` installed via `curl` from the releases page.

**Comment by PaulKobaNix** [comment]
Can confirm it's still relevant, please reopen
