### ISSUE TITLE
panic: `runtime error: index out of range [1] with length 1` in compose.buildContainerMountOptions

### ISSUE THREAD

**Issue by jamshid** [docker/compose#8505]
**Description**

Bringing up an existing v1 environment with v2 results in below panic. One of my services has multiple replicas and has two local anonymous(?) volumes, that seems to be the trigger.
```
  foo:
    deploy:
      replicas: 3
    volumes:
      # directory is unique per container
      - /var/foo1
      - /var/foo2
```

I would be fine with having to `docker-compose down` the v1 environment, that seems to allow `docker-compose up -d` to then work, but that loses the unnamed per-container volume on my scaled `foo` service. So I'm still unable to migrate a running v1 environment to v2.0.0-rc.2. Also, I get this error even when starting with v2 and recreating containers -- it's not specific to a pre-existing v1 environment, so I'm still unable to use v2.

PS: contact me I'm "jamshid" in the Docker Community slack if you want access to the yml and registry creds needed to run this environment. Or, if you could explain how to run a test build of compose v2 in Docker for Mac maybe I could try that before the rc3 release to shake out any remaining bugs.

**Steps to reproduce the issue:**
1. Using docker-compose v2 bring up this docker-compose.yml using `docker-compose up -d`, it should come up fine:
```
services:
  test:
    deploy:
      replicas: 3
    image: centos
    volumes:
    - type: volume
      target: /var/perm1
      volume: {}
    - type: volume
      target: /var/perm2
      volume: {}
    command: sleep 300
```
2. Now bring it up again, recreating containers. It fails with the below panic:
```
$ docker-compose up -d --force-recreate
[+] Running 0/0
 ⠋ Container test_test_1  Recreate                                                                                 0.1s
 ⠋ Container test_test_3  Recreate                                                                                 0.1s
 ⠋ Container test_test_2  Recreate                                                                                 0.1s
...
[+] Running 0/3
 ⠸ Container test_test_1  Recreate                                                                                10.4s
 ⠸ Container test_test_3  Recreate                                                                                10.4s
 ⠸ Container test_test_2  Recreate                                                                                10.4s
panic: runtime error: index out of range [1] with length 1

goroutine 86 [running]:
github.com/docker/compose-cli/pkg/compose.buildContainerMountOptions(0xc0005b403d, 0x4, 0xc0005b4030, 0x11, 0xc0000c6a00, 0x1, 0x1, 0xc0002dd080, 0xc0002dd0b0, 0xc0002dd0e0, ...)
	github.com/docker/compose-cli/pkg/compose/create.go:702 +0x94d
github.com/docker/compose-cli/pkg/compose.(*composeService).buildContainerVolumes(0xc0005ae060, 0x2120e88, 0xc0002dd1d0, 0xc0005b403d, 0x4, 0xc0005b4030, 0x11, 0xc0000c6a00, 0x1, 0x1, ...)
	github.com/docker/compose-cli/pkg/compose/create.go:636 +0x213
github.com/docker/compose-cli/pkg/compose.(*composeService).getCreateOptions(0xc0005ae060, 0x2120e88, 0xc0002dd1d0, 0xc0002db360, 0xc0001aabf0, 0x4, 0x0, 0x0, 0x0, 0x0, ...)
	github.com/docker/compose-cli/pkg/compose/create.go:267 +0x6e5
github.com/docker/compose-cli/pkg/compose.(*composeService).createMobyContainer(0xc0005ae060, 0x2120e88, 0xc0002dd1d0, 0xc0002db360, 0xc0001aabf0, 0x4, 0x0, 0x0, 0x0, 0x0, ...)
	github.com/docker/compose-cli/pkg/compose/convergence.go:411 +0xf1
github.com/docker/compose-cli/pkg/compose.(*composeService).recreateContainer(0xc0005ae060, 0x2120e88, 0xc0002dd1d0, 0xc0002db360, 0xc0001aabf0, 0x4, 0x0, 0x0, 0x0, 0x0, ...)
	github.com/docker/compose-cli/pkg/compose/convergence.go:371 +0x516
github.com/docker/compose-cli/pkg/compose.(*convergence).ensureService.func2(0x0, 0x0)
	github.com/docker/compose-cli/pkg/compose/convergence.go:200 +0x133
golang.org/x/sync/errgroup.(*Group).Go.func1(0xc00051c510, 0xc0002444d0)
	golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:57 +0x59
created by golang.org/x/sync/errgroup.(*Group).Go
	golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:54 +0x66
```

**Describe the results you received:**

see above panic stack trace

**Describe the results you expected:**

Working transition for environments running docker-compose v1 to v2 and working "recreate" on v2.

**Additional information you deem important (e.g. issue happens only occasionally):**

figured out a minimum consistent repro since this wasn't only a problem when migrating from v1 to v2, it happens even when starting with v2

**Output of `docker-compose --version`:**

```
Docker Compose version v2.0.0-rc.2
```

**Output of `docker version`:**

```
Client:
 Cloud integration: 1.0.17
 Version:           20.10.8
 API version:       1.41
 Go version:        go1.16.6
 Git commit:        3967b7d
 Built:             Fri Jul 30 19:55:20 2021
 OS/Arch:           darwin/amd64
 Context:           newdefault
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.8
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.6
  Git commit:       75249d8
  Built:            Fri Jul 30 19:52:10 2021
  OS/Arch:          linux/amd64
  Experimental:     true
 containerd:
  Version:          1.4.9
  GitCommit:        e25210fe30a0a703442421b0f60afac609f950a3
 runc:
  Version:          1.0.1
  GitCommit:        v1.0.1-0-g4144b63
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

```

**Output of `docker context show`:**  
You can also run `docker context inspect context-name` to give us more details but don't forget to remove sensitive content.

```
default
```

**Output of `docker info`:**

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Build with BuildKit (Docker Inc., v0.6.1-docker)
  compose: Docker Compose (Docker Inc., v2.0.0-rc.2)
  scan: Docker Scan (Docker Inc., v0.8.0)

Server:
 Containers: 43
  Running: 40
  Paused: 0
  Stopped: 3
 Images: 80
 Server Version: 20.10.8
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc io.containerd.runc.v2 io.containerd.runtime.v1.linux
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: e25210fe30a0a703442421b0f60afac609f950a3
 runc version: v1.0.1-0-g4144b63
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.10.47-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 13.67GiB
 Name: docker-desktop
 ID: TGR7:NLBE:2IB2:NFEG:SVWA:B4JM:HLHT:D5QR:B7DK:3N6G:BIQE:6SOH
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: true
```

**Additional environment details (AWS ECS, Azure ACI, local, etc.):**
Docker for Mac 4.0.0

**Comment by jamshid** [comment]
Surprised this isn't seen by more people. This is still reproducible on `Docker Compose version v2.0.0`. Hope it gets fixed soon, it's a blocker for me.
