### ISSUE TITLE
compose logs crashes with fatal error: concurrent map read and map write

### ISSUE THREAD

**Issue by federicobond** [docker/compose#8542]
**Description**

A crash happened while using the `compose logs` command, due to concurrent map read and write. Looks like the `register` function [here](https://github.com/docker/compose-cli/blob/2605aae33f816794e59c68b7c3c0e0e9d28a7104/cli/formatter/logs.go#L45) is not performing any kind of concurrency control over the `presenters` field.

**Steps to reproduce the issue:**
1. Spin up some containers with `docker compose`
2. Run `docker compose logs -f`

**Describe the results you received:**

After several printed lines of logs:

```
fatal error: concurrent map read and map write

goroutine 41 [running]:
runtime.throw(0x1f1239e, 0x21)
	runtime/panic.go:1117 +0x72 fp=0xc0001659a8 sp=0xc000165978 pc=0x1036b12
runtime.mapaccess2_faststr(0x1d4b820, 0xc00015c1e0, 0xc000400b86, 0x8, 0x2, 0x0)
	runtime/map_faststr.go:116 +0x4a5 fp=0xc000165a18 sp=0xc0001659a8 pc=0x1014165
github.com/docker/compose-cli/cli/formatter.(*logConsumer).Log(0xc00038bb40, 0xc000400b86, 0x8, 0xc000400c00, 0x6, 0xc0006472c0, 0x94)
	github.com/docker/compose-cli/cli/formatter/logs.go:69 +0x8f fp=0xc000165ac8 sp=0xc000165a18 pc=0x172d4af
github.com/docker/compose-cli/local/compose.(*composeService).Logs.func1.1(0x0, 0xc000400b86, 0x8, 0xc000400c00, 0x6, 0xc0006472c0, 0x94, 0x0)
	github.com/docker/compose-cli/local/compose/logs.go:61 +0x67 fp=0xc000165b10 sp=0xc000165ac8 pc=0x1c36807
github.com/docker/compose-cli/utils.(*splitBuffer).Write(0xc0001b8370, 0xc000328008, 0x95, 0x8001, 0x659, 0x0, 0x0)
	github.com/docker/compose-cli/utils/logs.go:94 +0x137 fp=0xc000165bb0 sp=0xc000165b10 pc=0x169ded7
github.com/docker/docker/pkg/stdcopy.StdCopy(0xb9e9000, 0xc0001b8370, 0xb9e9000, 0xc0001b8370, 0x20740e0, 0xc000384900, 0xd, 0xc000224410, 0x47)
	github.com/docker/docker@v20.10.1+incompatible/pkg/stdcopy/stdcopy.go:174 +0x4c6 fp=0xc000165cb8 sp=0xc000165bb0 pc=0x1788806
github.com/docker/compose-cli/local/compose.(*composeService).Logs.func1(0x0, 0x0)
	github.com/docker/compose-cli/local/compose/logs.go:66 +0x571 fp=0xc000165f78 sp=0xc000165cb8 pc=0x1c36d91
golang.org/x/sync/errgroup.(*Group).Go.func1(0xc00015c9c0, 0xc0004b2140)
	golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:57 +0x59 fp=0xc000165fd0 sp=0xc000165f78 pc=0x1693859
runtime.goexit()
	runtime/asm_amd64.s:1371 +0x1 fp=0xc000165fd8 sp=0xc000165fd0 pc=0x106d421
created by golang.org/x/sync/errgroup.(*Group).Go
	golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:54 +0x66

goroutine 1 [semacquire]:
sync.runtime_Semacquire(0xc00015c9d0)
	runtime/sema.go:56 +0x45
sync.(*WaitGroup).Wait(0xc00015c9c8)
	sync/waitgroup.go:130 +0x65
golang.org/x/sync/errgroup.(*Group).Wait(0xc00015c9c0, 0xc0001caf00, 0xc00050e3c0)
	golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:40 +0x31
github.com/docker/compose-cli/local/compose.(*composeService).Logs(0xc0000ca060, 0x2095648, 0xc0001b4200, 0xc00044a798, 0x4, 0x208d2d0, 0xc00038bb40, 0xc000021ce0, 0x0, 0x3, ...)
	github.com/docker/compose-cli/local/compose/logs.go:71 +0x4df
github.com/docker/compose-cli/api/compose.(*ServiceDelegator).Logs(0xc000260c70, 0x2095648, 0xc0001b4200, 0xc00044a798, 0x4, 0x208d2d0, 0xc00038bb40, 0xc000021ce0, 0x0, 0x3, ...)
	github.com/docker/compose-cli/api/compose/delegator.go:77 +0xaf
github.com/docker/compose-cli/cli/cmd/compose.runLogs(0x2095648, 0xc0001b4200, 0x20aa608, 0xc000260c70, 0xc000481dc0, 0x0, 0x0, 0x0, 0x0, 0x1, ...)
	github.com/docker/compose-cli/cli/cmd/compose/logs.go:69 +0x257
github.com/docker/compose-cli/cli/cmd/compose.logsCommand.func1(0x2095648, 0xc0001b4200, 0xc000021ce0, 0x0, 0x3, 0xc0000441f8, 0x12)
	github.com/docker/compose-cli/cli/cmd/compose/logs.go:48 +0x106
github.com/docker/compose-cli/cli/cmd/compose.Adapt.func1(0xc00002e2c0, 0xc000021ce0, 0x0, 0x3, 0x0, 0x0)
	github.com/docker/compose-cli/cli/cmd/compose/compose.go:60 +0x12f
github.com/spf13/cobra.(*Command).execute(0xc00002e2c0, 0xc0001b82a0, 0x3, 0x3, 0xc00002e2c0, 0xc0001b82a0)
	github.com/spf13/cobra@v1.1.1/command.go:850 +0x472
github.com/spf13/cobra.(*Command).ExecuteC(0xc00009f340, 0xc00009f340, 0xc0001b8280, 0x5)
	github.com/spf13/cobra@v1.1.1/command.go:958 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.1.1/command.go:895
github.com/docker/cli/cli-plugins/plugin.RunPlugin(0xc00018e000, 0xc00017cb00, 0x1ef1803, 0x5, 0x1ef852a, 0xb, 0x2059580, 0xc, 0x0, 0x0, ...)
	github.com/docker/cli@v20.10.3-0.20210127070556-d26bdfd4ea23+incompatible/cli-plugins/plugin/plugin.go:51 +0x146
github.com/docker/cli/cli-plugins/plugin.Run(0x1f63a38, 0x1ef1803, 0x5, 0x1ef852a, 0xb, 0x2059580, 0xc, 0x0, 0x0, 0x0, ...)
	github.com/docker/cli@v20.10.3-0.20210127070556-d26bdfd4ea23+incompatible/cli-plugins/plugin/plugin.go:64 +0x13f
main.main()
	github.com/docker/compose-cli/main.go:37 +0x125

goroutine 8 [runnable]:
github.com/docker/compose-cli/cli/formatter.init.0.func1(0xc0000a29f0)
	github.com/docker/compose-cli/cli/formatter/colors.go:120 +0x2f5
created by github.com/docker/compose-cli/cli/formatter.init.0
	github.com/docker/compose-cli/cli/formatter/colors.go:104 +0x22b

goroutine 9 [chan receive]:
k8s.io/klog/v2.(*loggingT).flushDaemon(0x27e8680)
	k8s.io/klog/v2@v2.4.0/klog.go:1169 +0x8b
created by k8s.io/klog/v2.init.0
	k8s.io/klog/v2@v2.4.0/klog.go:417 +0xdf

goroutine 13 [syscall]:
os/signal.signal_recv(0x1f63c98)
	runtime/sigqueue.go:165 +0x9d
os/signal.loop()
	os/signal/signal_unix.go:23 +0x25
created by os/signal.Notify.func1.1
	os/signal/signal.go:151 +0x45

goroutine 11 [select]:
net/http.(*persistConn).readLoop(0xc0000c0c60)
	net/http/transport.go:2203 +0x967
created by net/http.(*Transport).dialConn
	net/http/transport.go:1743 +0xc77

goroutine 12 [select]:
net/http.(*persistConn).writeLoop(0xc0000c0c60)
	net/http/transport.go:2382 +0xf7
created by net/http.(*Transport).dialConn
	net/http/transport.go:1744 +0xc9c

goroutine 39 [chan receive]:
github.com/docker/compose-cli/cli/cmd/compose.Adapt.func1.1(0xc00031c060, 0xc000416030)
	github.com/docker/compose-cli/cli/cmd/compose/compose.go:56 +0x34
created by github.com/docker/compose-cli/cli/cmd/compose.Adapt.func1
	github.com/docker/compose-cli/cli/cmd/compose/compose.go:55 +0x494

goroutine 53 [IO wait]:
internal/poll.runtime_pollWait(0xb989ec8, 0x72, 0xffffffffffffffff)
	runtime/netpoll.go:222 +0x55
internal/poll.(*pollDesc).wait(0xc0000a8198, 0x72, 0x1000, 0x1000, 0xffffffffffffffff)
	internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
	internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0xc0000a8180, 0xc0000c2000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	internal/poll/fd_unix.go:166 +0x1d5
net.(*netFD).Read(0xc0000a8180, 0xc0000c2000, 0x1000, 0x1000, 0x1069619, 0xc0001b006c, 0xc000000000)
	net/fd_posix.go:55 +0x4f
net.(*conn).Read(0xc0001ae7b0, 0xc0000c2000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	net/net.go:183 +0x91
net/http.(*persistConn).Read(0xc00014b560, 0xc0000c2000, 0x1000, 0x1000, 0x0, 0x1, 0x0)
	net/http/transport.go:1922 +0x77
bufio.(*Reader).fill(0xc00070c540)
	bufio/bufio.go:101 +0x108
bufio.(*Reader).ReadSlice(0xc00070c540, 0x107960a, 0x27c38a0, 0xc0001f6580, 0x3, 0xc0002ab9a0, 0x10f61f1)
	bufio/bufio.go:360 +0x3d
net/http/internal.readChunkLine(0xc00070c540, 0x380, 0x7a, 0x0, 0x0, 0x7a)
	net/http/internal/chunked.go:122 +0x34
net/http/internal.(*chunkedReader).beginChunk(0xc00015cd50)
	net/http/internal/chunked.go:48 +0x32
net/http/internal.(*chunkedReader).Read(0xc00015cd50, 0xc0002ae000, 0x8009, 0x8009, 0xc00038f50a, 0xffffffffffffffff, 0xc00038f5d0)
	net/http/internal/chunked.go:93 +0x134
net/http.(*body).readLocked(0xc00050e700, 0xc0002ae000, 0x8009, 0x8009, 0xc0005cf200, 0x5e, 0xc0002abba0)
	net/http/transfer.go:842 +0x5f
net/http.(*body).Read(0xc00050e700, 0xc0002ae000, 0x8009, 0x8009, 0x0, 0x0, 0x0)
	net/http/transfer.go:834 +0xf9
net/http.(*bodyEOFSignal).Read(0xc00050e740, 0xc0002ae000, 0x8009, 0x8009, 0x0, 0x0, 0x0)
	net/http/transport.go:2764 +0xe2
github.com/docker/docker/pkg/stdcopy.StdCopy(0xb9e9000, 0xc0004bc140, 0xb9e9000, 0xc0004bc140, 0x20740e0, 0xc00050e740, 0x47, 0xc000224320, 0x47)
	github.com/docker/docker@v20.10.1+incompatible/pkg/stdcopy/stdcopy.go:108 +0xe7
github.com/docker/compose-cli/local/compose.(*composeService).Logs.func1(0x0, 0x0)
	github.com/docker/compose-cli/local/compose/logs.go:66 +0x571
golang.org/x/sync/errgroup.(*Group).Go.func1(0xc00015c9c0, 0xc0004441e0)
	golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:57 +0x59
created by golang.org/x/sync/errgroup.(*Group).Go
	golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:54 +0x66

goroutine 16 [select]:
net/http.(*persistConn).readLoop(0xc0000c1560)
	net/http/transport.go:2203 +0x967
created by net/http.(*Transport).dialConn
	net/http/transport.go:1743 +0xc77

goroutine 65 [select]:
net/http.(*persistConn).writeLoop(0xc0000c1560)
	net/http/transport.go:2382 +0xf7
created by net/http.(*Transport).dialConn
	net/http/transport.go:1744 +0xc9c

goroutine 51 [select]:
net/http.(*persistConn).readLoop(0xc00014b560)
	net/http/transport.go:2203 +0x967
created by net/http.(*Transport).dialConn
	net/http/transport.go:1743 +0xc77

goroutine 52 [select]:
net/http.(*persistConn).writeLoop(0xc00014b560)
	net/http/transport.go:2382 +0xf7
created by net/http.(*Transport).dialConn
	net/http/transport.go:1744 +0xc9c

goroutine 22 [select]:
net/http.(*persistConn).readLoop(0xc0001779e0)
	net/http/transport.go:2203 +0x967
created by net/http.(*Transport).dialConn
	net/http/transport.go:1743 +0xc77

goroutine 23 [select]:
net/http.(*persistConn).writeLoop(0xc0001779e0)
	net/http/transport.go:2382 +0xf7
created by net/http.(*Transport).dialConn
	net/http/transport.go:1744 +0xc9c

goroutine 42 [IO wait]:
internal/poll.runtime_pollWait(0xb989cf8, 0x72, 0xffffffffffffffff)
	runtime/netpoll.go:222 +0x55
internal/poll.(*pollDesc).wait(0xc000262398, 0x72, 0x1000, 0x1000, 0xffffffffffffffff)
	internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
	internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0xc000262380, 0xc0002bf000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	internal/poll/fd_unix.go:166 +0x1d5
net.(*netFD).Read(0xc000262380, 0xc0002bf000, 0x1000, 0x1000, 0x106f240, 0xc0002a7828, 0x0)
	net/fd_posix.go:55 +0x4f
net.(*conn).Read(0xc00000e088, 0xc0002bf000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	net/net.go:183 +0x91
net/http.(*persistConn).Read(0xc000177b00, 0xc0002bf000, 0x1000, 0x1000, 0x0, 0x1, 0x0)
	net/http/transport.go:1922 +0x77
bufio.(*Reader).fill(0xc0001b11a0)
	bufio/bufio.go:101 +0x108
bufio.(*Reader).ReadSlice(0xc0001b11a0, 0x107960a, 0x27c38a0, 0xc000134780, 0x7, 0xc0002a79a0, 0x10f61f1)
	bufio/bufio.go:360 +0x3d
net/http/internal.readChunkLine(0xc0001b11a0, 0x180, 0x87, 0x0, 0x0, 0x87)
	net/http/internal/chunked.go:122 +0x34
net/http/internal.(*chunkedReader).beginChunk(0xc00015d140)
	net/http/internal/chunked.go:48 +0x32
net/http/internal.(*chunkedReader).Read(0xc00015d140, 0xc0004a4000, 0x8009, 0x8009, 0xc00041740a, 0xffffffffffffffff, 0xc000417410)
	net/http/internal/chunked.go:93 +0x134
net/http.(*body).readLocked(0xc00050ea80, 0xc0004a4000, 0x8009, 0x8009, 0xc000208d20, 0x69, 0xc0002a7ba0)
	net/http/transfer.go:842 +0x5f
net/http.(*body).Read(0xc00050ea80, 0xc0004a4000, 0x8009, 0x8009, 0x0, 0x0, 0x0)
	net/http/transfer.go:834 +0xf9
net/http.(*bodyEOFSignal).Read(0xc00050eac0, 0xc0004a4000, 0x8009, 0x8009, 0x0, 0x0, 0x0)
	net/http/transport.go:2764 +0xe2
github.com/docker/docker/pkg/stdcopy.StdCopy(0xb9e9000, 0xc0004bc320, 0xb9e9000, 0xc0004bc320, 0x20740e0, 0xc00050eac0, 0xb, 0xc000224690, 0x47)
	github.com/docker/docker@v20.10.1+incompatible/pkg/stdcopy/stdcopy.go:108 +0xe7
github.com/docker/compose-cli/local/compose.(*composeService).Logs.func1(0x0, 0x0)
	github.com/docker/compose-cli/local/compose/logs.go:66 +0x571
golang.org/x/sync/errgroup.(*Group).Go.func1(0xc00015c9c0, 0xc0004b23c0)
	golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:57 +0x59
created by golang.org/x/sync/errgroup.(*Group).Go
	golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:54 +0x66

goroutine 25 [select]:
net/http.(*persistConn).readLoop(0xc000177b00)
	net/http/transport.go:2203 +0x967
created by net/http.(*Transport).dialConn
	net/http/transport.go:1743 +0xc77

goroutine 26 [select]:
net/http.(*persistConn).writeLoop(0xc000177b00)
	net/http/transport.go:2382 +0xf7
created by net/http.(*Transport).dialConn
	net/http/transport.go:1744 +0xc9c

goroutine 81 [IO wait]:
internal/poll.runtime_pollWait(0xb989de0, 0x72, 0xffffffffffffffff)
	runtime/netpoll.go:222 +0x55
internal/poll.(*pollDesc).wait(0xc000262118, 0x72, 0x1000, 0x1000, 0xffffffffffffffff)
	internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
	internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0xc000262100, 0xc000231000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	internal/poll/fd_unix.go:166 +0x1d5
net.(*netFD).Read(0xc000262100, 0xc000231000, 0x1000, 0x1000, 0x106f240, 0xc000163828, 0xc000000000)
	net/fd_posix.go:55 +0x4f
net.(*conn).Read(0xc00000e068, 0xc000231000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	net/net.go:183 +0x91
net/http.(*persistConn).Read(0xc0001779e0, 0xc000231000, 0x1000, 0x1000, 0x0, 0x1, 0x449ffff)
	net/http/transport.go:1922 +0x77
bufio.(*Reader).fill(0xc0001b0cc0)
	bufio/bufio.go:101 +0x108
bufio.(*Reader).ReadSlice(0xc0001b0cc0, 0x107960a, 0x27c38a0, 0xc0001f6580, 0x3, 0xc0001639a0, 0x10f61f1)
	bufio/bufio.go:360 +0x3d
net/http/internal.readChunkLine(0xc0001b0cc0, 0x380, 0x7f, 0x0, 0x0, 0x7f)
	net/http/internal/chunked.go:122 +0x34
net/http/internal.(*chunkedReader).beginChunk(0xc00015ca80)
	net/http/internal/chunked.go:48 +0x32
net/http/internal.(*chunkedReader).Read(0xc00015ca80, 0xc0005de000, 0x8009, 0x8009, 0xc00053490a, 0xffffffffffffffff, 0xc000534950)
	net/http/internal/chunked.go:93 +0x134
net/http.(*body).readLocked(0xc000384340, 0xc0005de000, 0x8009, 0x8009, 0xc0005da2a0, 0x61, 0xc000163ba0)
	net/http/transfer.go:842 +0x5f
net/http.(*body).Read(0xc000384340, 0xc0005de000, 0x8009, 0x8009, 0x0, 0x0, 0x0)
	net/http/transfer.go:834 +0xf9
net/http.(*bodyEOFSignal).Read(0xc000384380, 0xc0005de000, 0x8009, 0x8009, 0x0, 0x0, 0x0)
	net/http/transport.go:2764 +0xe2
github.com/docker/docker/pkg/stdcopy.StdCopy(0xb9e9000, 0xc000102230, 0xb9e9000, 0xc000102230, 0x20740e0, 0xc000384380, 0x7, 0xc0002248c0, 0x47)
	github.com/docker/docker@v20.10.1+incompatible/pkg/stdcopy/stdcopy.go:108 +0xe7
github.com/docker/compose-cli/local/compose.(*composeService).Logs.func1(0x0, 0x0)
	github.com/docker/compose-cli/local/compose/logs.go:66 +0x571
golang.org/x/sync/errgroup.(*Group).Go.func1(0xc00015c9c0, 0xc0001ca960)
	golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:57 +0x59
created by golang.org/x/sync/errgroup.(*Group).Go
	golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:54 +0x66

goroutine 82 [runnable]:
github.com/docker/compose-cli/cli/formatter.(*presenter).setPrefix(0xc00015cf30, 0xf)
	github.com/docker/compose-cli/cli/formatter/logs.go:114 +0xea
github.com/docker/compose-cli/cli/formatter.(*logConsumer).register(0xc00038bb40, 0xc000400fc6, 0x7, 0x7)
	github.com/docker/compose-cli/cli/formatter/logs.go:58 +0x17d
github.com/docker/compose-cli/cli/formatter.(*logConsumer).Log(0xc00038bb40, 0xc000400fc6, 0x7, 0xc000401014, 0x5, 0xc000047130, 0x4c)
	github.com/docker/compose-cli/cli/formatter/logs.go:71 +0x265
github.com/docker/compose-cli/local/compose.(*composeService).Logs.func1.1(0x0, 0xc000400fc6, 0x7, 0xc000401014, 0x5, 0xc000047130, 0x4c, 0x0)
	github.com/docker/compose-cli/local/compose/logs.go:61 +0x67
github.com/docker/compose-cli/utils.(*splitBuffer).Write(0xc000102410, 0xc000270008, 0x4d, 0x8001, 0x9a9, 0x0, 0x0)
	github.com/docker/compose-cli/utils/logs.go:94 +0x137
github.com/docker/docker/pkg/stdcopy.StdCopy(0xb9e9000, 0xc000102410, 0xb9e9000, 0xc000102410, 0x20740e0, 0xc0003847c0, 0xa, 0xc000224910, 0x47)
	github.com/docker/docker@v20.10.1+incompatible/pkg/stdcopy/stdcopy.go:174 +0x4c6
github.com/docker/compose-cli/local/compose.(*composeService).Logs.func1(0x0, 0x0)
	github.com/docker/compose-cli/local/compose/logs.go:66 +0x571
golang.org/x/sync/errgroup.(*Group).Go.func1(0xc00015c9c0, 0xc0001caf00)
	golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:57 +0x59
created by golang.org/x/sync/errgroup.(*Group).Go
	golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:54 +0x66
```

**Describe the results you expected:**

`logs` command should work normally.

**Additional information you deem important (e.g. issue happens only occasionally):** yes, only happens occasionally, when printing a lot of output from multiple containers

**Output of `docker version`:**

```
Client:
 Cloud integration: 1.0.14
 Version:           20.10.6
 API version:       1.41
 Go version:        go1.16.3
 Git commit:        370c289
 Built:             Fri Apr  9 22:46:57 2021
 OS/Arch:           darwin/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.6
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       8728dd2
  Built:            Fri Apr  9 22:44:56 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.4
  GitCommit:        05f951a3781f4f2c1911b05e61c160e9c30eaa8e
 runc:
  Version:          1.0.0-rc93
  GitCommit:        12644e614e25b05da6fd08a38ffa0cfe1903fdec
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Output of `docker context show`:**  
You can also run `docker context inspect context-name` to give us more details but don't forget to remove sensitive content.

```
default
```

**Output of `docker info`:**

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)
  compose: Docker Compose (Docker Inc., 2.0.0-beta.1)
  scan: Docker Scan (Docker Inc., v0.8.0)

Server:
 Containers: 25
  Running: 6
  Paused: 0
  Stopped: 19
 Images: 21
 Server Version: 20.10.6
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 05f951a3781f4f2c1911b05e61c160e9c30eaa8e
 runc version: 12644e614e25b05da6fd08a38ffa0cfe1903fdec
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.10.25-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 7.776GiB
 Name: docker-desktop
 ID: KNXI:7I5F:4PS7:XFLL:GOPU:72XK:Z3T4:QZNC:UVKK:F65J:BNM4:GZDW
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Additional environment details (AWS ECS, Azure ACI, local, etc.):**

Local environment.

**Comment by nbuesing** [comment]
this same issue is happening for me a lot (daily), but running command again it usually works.  Started noticing it when I upgraded to  4.0.0.

**Comment by mat007** [comment]
Duplicates of #8599
