### ISSUE TITLE
[V2] Scale down => index out of range [1] with length 1

### ISSUE THREAD

**Issue by mdantonio** [docker/compose#8567]
## Context information (for bug reports)

- [x]  Using Compose V2 `docker compose ...`
- [ ] Using Compose V1 `docker-compose ...`

**Output of `docker(-)compose version`**
```
Docker Compose version v2.0.0-rc.3
```

**Output of `docker version`**
```
Client: Docker Engine - Community
 Cloud integration: 1.0.17
 Version:           20.10.8
 API version:       1.41
 Go version:        go1.16.6
 Git commit:        3967b7d
 Built:             Fri Jul 30 19:54:27 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.8
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.6
  Git commit:       75249d8
  Built:            Fri Jul 30 19:52:33 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.8
  GitCommit:        7eba5930496d9bbe375fdf71603e610ad737d2b2
 runc:
  Version:          1.0.0
  GitCommit:        v1.0.0-0-g84113ee
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Output of `docker-compose config`**
(Make sure to add the relevant `-f` and other flags)
```
services:
  mytest:
    command:
    - sleep
    - infinity
    image: alpine
    networks:
      default: null
networks:
  default:
    name: compose_rc2_default
```

## Steps to reproduce the issue

1. docker compose up -d --scale mytest=2
2. docker compose up -d --scale mytest=1

### Observed result

Scale up works fine, but scale scale down does not work due to a panic error

### Expected result

Of course scale is expected to work in both directions

### Stacktrace / full error message

```
panic: runtime error: index out of range [1] with length 1

goroutine 52 [running]:
github.com/docker/compose/v2/pkg/compose.(*convergence).ensureService(0xc00000cc00, 0x1528d68, 0xc0002b9920, 0xc000477b80, 0xc0002940b8, 0x6, 0x0, 0x0, 0x0, 0x0, ...)
	github.com/docker/compose/v2/pkg/compose/convergence.go:222 +0x11f1
github.com/docker/compose/v2/pkg/compose.(*convergence).apply.func1(0x1528d68, 0xc0002b9920, 0xc0002940b8, 0x6, 0x202020200a2c7d22, 0x736f682220202020)
	github.com/docker/compose/v2/pkg/compose/convergence.go:99 +0x21f
github.com/docker/compose/v2/pkg/compose.run.func1(0x6c6562616c222020, 0x7224227b203a2273)
	github.com/docker/compose/v2/pkg/compose/dependencies.go:102 +0xa3
golang.org/x/sync/errgroup.(*Group).Go.func1(0xc000355f80, 0xc0001ac3c0)
	golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:57 +0x59
created by golang.org/x/sync/errgroup.(*Group).Go
	golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:54 +0x66
```

## Additional information

OS version / distribution, `docker-compose` install method, etc.

**Comment by targzeta** [comment]
It seems that also scale=0 doesn't work.

Emanuele

**Comment by ndeloof** [comment]
closing as a duplicate for https://github.com/docker/compose/issues/8506

**Comment by ndeloof** [comment]
I created https://github.com/docker/compose/issues/8571 for the scale=0 issue
