### ISSUE TITLE
ModuleNotFoundError: No module named 'websocket' at `up` command

### ISSUE THREAD

**Issue by pbertoni89** [docker/compose#8574]
## Context information (for bug reports)

- [ ] Using Compose V2 `docker compose ...`
- [x] Using Compose V1 `docker-compose ...`

**Output of `docker(-)compose version`**
```
$ which docker-compose 
${HOME}/.local/bin/docker-compose

$ docker-compose version
docker-compose version 1.29.2, build unknown
docker-py version: 5.0.2
CPython version: 3.8.10
OpenSSL version: OpenSSL 1.1.1f  31 Mar 2020

$ sudo docker-compose version
Traceback (most recent call last):
  File "/usr/bin/docker-compose", line 11, in <module>
    load_entry_point('docker-compose==1.25.0', 'console_scripts', 'docker-compose')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 490, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2854, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2445, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2451, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3/dist-packages/compose/cli/main.py", line 18, in <module>
    import docker
  File "/usr/lib/python3/dist-packages/docker/__init__.py", line 2, in <module>
    from .api import APIClient
  File "/usr/lib/python3/dist-packages/docker/api/__init__.py", line 2, in <module>
    from .client import APIClient
  File "/usr/lib/python3/dist-packages/docker/api/client.py", line 8, in <module>
    import websocket
ModuleNotFoundError: No module named 'websocket'

```

**Output of `docker version`**
```
$ docker version
Client:
 Version:           20.10.7
 API version:       1.41
 Go version:        go1.13.8
 Git commit:        20.10.7-0ubuntu1~20.04.1
 Built:             Wed Aug  4 22:52:25 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true
Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get http://%2Fvar%2Frun%2Fdocker.sock/v1.24/version: dial unix /var/run/docker.sock: connect: permission denied

$ sudo docker version
Client:
 Version:           20.10.7
 API version:       1.41
 Go version:        go1.13.8
 Git commit:        20.10.7-0ubuntu1~20.04.1
 Built:             Wed Aug  4 22:52:25 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server:
 Engine:
  Version:          20.10.7
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.8
  Git commit:       20.10.7-0ubuntu1~20.04.1
  Built:            Wed Aug  4 19:07:47 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.5.2-0ubuntu1~20.04.2
  GitCommit:        
 runc:
  Version:          1.0.0~rc95-0ubuntu1~20.04.2
  GitCommit:        
 docker-init:
  Version:          0.19.0
  GitCommit:  
```

**Output of `docker-compose config`**
(Make sure to add the relevant `-f` and other flags)
```
$ docker-compose -f docker-compose-smi.yml config
services:
  peoca:
    command: ls -l /usr/bin/
    image: nvidia/cuda:11.0-base
version: '3.8'
```

## Steps to reproduce the issue

1. purge and reinstall `docker-compose` from `apt`
2. run any `docker-compose` subcommand
3.

### Stacktrace / full error message

```
Traceback (most recent call last):
  File "/usr/bin/docker-compose", line 11, in <module>
    load_entry_point('docker-compose==1.25.0', 'console_scripts', 'docker-compose')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 490, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2854, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2445, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2451, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3/dist-packages/compose/cli/main.py", line 18, in <module>
    import docker
  File "/usr/lib/python3/dist-packages/docker/__init__.py", line 2, in <module>
    from .api import APIClient
  File "/usr/lib/python3/dist-packages/docker/api/__init__.py", line 2, in <module>
    from .client import APIClient
  File "/usr/lib/python3/dist-packages/docker/api/client.py", line 8, in <module>
    import websocket
ModuleNotFoundError: No module named 'websocket'
```

## Additional information

```
$ sudo lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.3 LTS
Release:        20.04
Codename:       focal
```

Perhaps my installation was messed by the following steps:

1. install `docker-ce` in a remote past
2. added my user to `docker` group in order to avoid `sudo` prompt
3. moved to `docker.io` recently
4. (un)installed `docker-compose` from `pip`, both with/without `sudo`, a couple of time
5. end up with multiple? installations

Some similarities with #1290.

```
$ which docker-compose 
/home/xnext//.local/bin/docker-compose

$ cat /home/xnext/.local/bin/docker-compose
#!/usr/bin/python3.8
# -*- coding: utf-8 -*-
import re
import sys
from compose.cli.main import main
if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])
    sys.exit(main())

$ sudo which docker-compose 
/usr/bin/docker-compose

$ cat /usr/bin/docker-compose 
#!/usr/bin/python3
# EASY-INSTALL-ENTRY-SCRIPT: 'docker-compose==1.25.0','console_scripts','docker-compose'
__requires__ = 'docker-compose==1.25.0'
import re
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(
        load_entry_point('docker-compose==1.25.0', 'console_scripts', 'docker-compose')()
    )
```

All dependencies installed but maybe messed?

```
$ dpkg -l | grep 'compose\|websocket'
ii  docker-compose                                1.25.0-1
ii  python3-websocket                             0.53.0-2ubuntu1
```

```
$ pip list | grep 'compose\|websocket'
docker-compose          1.29.2
websocket               0.2.1
websocket-client        0.59.0
```

**Comment by pbertoni89** [comment]
Seems a `sudo pip` issue. In facts,

```
sudo pip install jsonschema websocket
```

Solves the error. Anyway, it's not still clear to me how this discrepancy started.
