### ISSUE TITLE
RC3 fails to `up` existing RC2 environment with `panic: invalid type for size types.UnitBytes` due to `shm_size: ${VAR}`

### ISSUE THREAD

**Issue by jamshid** [docker/compose#8613]
## Description of the issue

Get `panic: invalid type for size types.UnitBytes` from RC3 trying to `up` an existing RC2 environment. The trigger is using `shm_size: ${VAR}` with an env var. Hardcoding the same value works.

## Context information (for bug reports)

- [X ] Using Compose V2 `docker compose ...`
- [ ] Using Compose V1 `docker-compose ...`

**Output of `docker(-)compose version`**
```
% docker-compose --version
Docker Compose version v2.0.0-rc.3
```

**Output of `docker version`**
```
% docker version
Client:
 Cloud integration: 1.0.17
 Version:           20.10.8
 API version:       1.41
 Go version:        go1.16.6
 Git commit:        3967b7d
 Built:             Fri Jul 30 19:55:20 2021
 OS/Arch:           darwin/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.8
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.6
  Git commit:       75249d8
  Built:            Fri Jul 30 19:52:10 2021
  OS/Arch:          linux/amd64
  Experimental:     true
 containerd:
  Version:          1.4.9
  GitCommit:        e25210fe30a0a703442421b0f60afac609f950a3
 runc:
  Version:          1.0.1
  GitCommit:        v1.0.1-0-g4144b63
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
 Kubernetes:
  Version:          v1.19.7
  StackAPI:         Unknown
```

**Output of `docker-compose config`**
(Make sure to add the relevant `-f` and other flags)
```
% docker-compose config      
panic: invalid type for size types.UnitBytes

goroutine 1 [running]:
github.com/compose-spec/compose-go/loader.glob..func15(0x1dc7040, 0xc0006312a0, 0xc0008295b0, 0xc000192090, 0xc000631201, 0x0)
	github.com/compose-spec/compose-go@v0.0.0-20210901090333-feb401cda7f7/loader/loader.go:1016 +0x1a6
github.com/compose-spec/compose-go/loader.createTransformHook.func1(0x213cdc8, 0x1dc7040, 0x213cdc8, 0x1dc7040, 0x1dc7040, 0xc0006312a0, 0xc0008296e8, 0x169b505, 0x1dddde0, 0xc000398a40)
	github.com/compose-spec/compose-go@v0.0.0-20210901090333-feb401cda7f7/loader/loader.go:369 +0x7f
github.com/mitchellh/mapstructure.DecodeHookExec(0x1de8800, 0xc0003ad890, 0x1dc7040, 0xc0006312a0, 0x86, 0x1dc7040, 0xc0001f17f0, 0x186, 0x0, 0x1db1e40, ...)
	github.com/mitchellh/mapstructure@v1.4.1/decode_hooks.go:47 +0x28f
```

## Steps to reproduce the issue

1. Have something in my yml that is apparently now illegal, ok it's related to `shm_size`. Hardcoding the same value instead of using the env var works, that is weird.
```
services:
  test:
    deploy:
      replicas: 3
    image: centos
    # https://github.com/docker/compose/issues/8613
    # Why does hardcoding to "500000000" work but fails when using env var?
    # % SWARM_SHM_SIZE=500000000 docker-compose up
    # panic: invalid type for size types.UnitBytes
    # 
    # goroutine 1 [running]:
    # github.com/compose-spec/compose-go/loader.glob..func15(0x1dc7040, 0xc00003eef0, 0xc00061d2a0, 0xc000301ab8, 0xc00003ee01, 0x0)
    # 	github.com/compose-spec/compose-go@v0.0.0-20210901090333-feb401cda7f7/loader/loader.go:1016 +0x1a6
    # github.com/compose-spec/compose-go/loader.createTransformHook.func1(0x213cdc8, 0x1dc7040, 0x213cdc8, 0x1dc7040, 0x1dc7040, 0xc00003eef0, 0xc00061d3d8, 0x169b505, 0x1dddde0, 0xc00040ece0)
    # 	github.com/compose-spec/compose-go@v0.0.0-20210901090333-feb401cda7f7/loader/loader.go:369 +0x7f
    # github.com/mitchellh/mapstructure.DecodeHookExec(0x1de8800, 0xc0002de210, 0x1dc7040, 0xc00003eef0, 0x86, 0x1dc7040, 0xc0001dcdf0, 0x186, 0x0, 0x1db1e40, ...)
    # 	github.com/mitchellh/mapstructure@v1.4.1/decode_hooks.go:47 +0x28f
    # github.com/mitchellh/mapstructure.ComposeDecodeHookFunc.func1(0x1dc7040, 0xc00003eef0, 0x86, 0x1dc7040, 0xc0001dcdf0, 0x186, 0xa743280, 0x10, 0x10, 0x2d00108)
#    shm_size: "500000000"  # this works
    shm_size: "${SWARM_SHM_SIZE}"  # this fails
    volumes:
    - type: volume
      target: /var/perm1
      volume: {}
# This still causes failure with RC3 (https://github.com/docker/compose/issues/8505)
#    - type: volume
#      target: /var/perm2
#      volume: {}
    command: sleep 300
```

### Observed result

```
% docker-compose --debug up -d
panic: invalid type for size types.UnitBytes

goroutine 1 [running]:
github.com/compose-spec/compose-go/loader.glob..func15(0x1dc7040, 0xc0004738d8, 0xc00079d2a0, 0xc00051be30, 0xc000473801, 0x0)
	github.com/compose-spec/compose-go@v0.0.0-20210901090333-feb401cda7f7/loader/loader.go:1016 +0x1a6
github.com/compose-spec/compose-go/loader.createTransformHook.func1(0x213cdc8, 0x1dc7040, 0x213cdc8, 0x1dc7040, 0x1dc7040, 0xc0004738d8, 0xc00079d3d8, 0x169b505, 0x1dddde0, 0xc0006164a0)
	github.com/compose-spec/compose-go@v0.0.0-20210901090333-feb401cda7f7/loader/loader.go:369 +0x7f
...
```
### Expected result

Should be able to `up` an existing docker compose V2 RC2 environment.

### Stacktrace / full error message

```
% docker-compose --debug up -d
panic: invalid type for size types.UnitBytes

goroutine 1 [running]:
github.com/compose-spec/compose-go/loader.glob..func15(0x1dc7040, 0xc0004738d8, 0xc00079d2a0, 0xc00051be30, 0xc000473801, 0x0)
	github.com/compose-spec/compose-go@v0.0.0-20210901090333-feb401cda7f7/loader/loader.go:1016 +0x1a6
github.com/compose-spec/compose-go/loader.createTransformHook.func1(0x213cdc8, 0x1dc7040, 0x213cdc8, 0x1dc7040, 0x1dc7040, 0xc0004738d8, 0xc00079d3d8, 0x169b505, 0x1dddde0, 0xc0006164a0)
	github.com/compose-spec/compose-go@v0.0.0-20210901090333-feb401cda7f7/loader/loader.go:369 +0x7f
github.com/mitchellh/mapstructure.DecodeHookExec(0x1de8800, 0xc0006146a0, 0x1dc7040, 0xc0004738d8, 0x86, 0x1dc7040, 0xc0005397f0, 0x186, 0x0, 0x1db1e40, ...)
	github.com/mitchellh/mapstructure@v1.4.1/decode_hooks.go:47 +0x28f
github.com/mitchellh/mapstructure.ComposeDecodeHookFunc.func1(0x1dc7040, 0xc0004738d8, 0x86, 0x1dc7040, 0xc0005397f0, 0x186, 0xae205b0, 0x10, 0x10, 0x2e40108)
	github.com/mitchellh/mapstructure@v1.4.1/decode_hooks.go:68 +0xd4
github.com/mitchellh/mapstructure.DecodeHookExec(0x1db1e40, 0xc0006164a0, 0x1dc7040, 0xc0004738d8, 0x86, 0x1dc7040, 0xc0005397f0, 0x186, 0x1015247, 0xc0005d7df8, ...)
	github.com/mitchellh/mapstructure@v1.4.1/decode_hooks.go:51 +0xe2
github.com/mitchellh/mapstructure.(*Decoder).decode(0xc0001c3698, 0x1d9cd67, 0x8, 0x1dc7040, 0xc0004738d8, 0x1dc7040, 0xc0005397f0, 0x186, 0x94, 0x0)
	github.com/mitchellh/mapstructure@v1.4.1/mapstructure.go:431 +0x8ba
github.com/mitchellh/mapstructure.(*Decoder).decodeStructFromMap(0xc0001c3698, 0x0, 0x0, 0x1dbd300, 0xc000475ad0, 0x15, 0x1f6bc80, 0xc000539400, 0x199, 0x0, ...)
	github.com/mitchellh/mapstructure@v1.4.1/mapstructure.go:1377 +0x226f
github.com/mitchellh/mapstructure.(*Decoder).decodeStruct(0xc0001c3698, 0x0, 0x0, 0x1dbd300, 0xc000475ad0, 0x1f6bc80, 0xc000539400, 0x199, 0x1dbd300, 0xc000475ad0)
	github.com/mitchellh/mapstructure@v1.4.1/mapstructure.go:1203 +0x63a
github.com/mitchellh/mapstructure.(*Decoder).decode(0xc0001c3698, 0x0, 0x0, 0x1dbd300, 0xc000475ad0, 0x1f6bc80, 0xc000539400, 0x199, 0xc000539400, 0x199)
	github.com/mitchellh/mapstructure@v1.4.1/mapstructure.go:454 +0x776
github.com/mitchellh/mapstructure.(*Decoder).Decode(0xc0001c3698, 0x1dbd300, 0xc000475ad0, 0x0, 0xc0006164a0)
	github.com/mitchellh/mapstructure@v1.4.1/mapstructure.go:389 +0xf0
github.com/compose-spec/compose-go/loader.Transform(0x1dbd300, 0xc000475ad0, 0x1defc40, 0xc000539400, 0x0, 0x0, 0x0, 0x0, 0x0)
	github.com/compose-spec/compose-go@v0.0.0-20210901090333-feb401cda7f7/loader/loader.go:321 +0x1bc
github.com/compose-spec/compose-go/loader.LoadService(0xc00011a210, 0x5, 0xc000475ad0, 0xc00024c000, 0x31, 0xc00079e990, 0x0, 0x0, 0x0)
	github.com/compose-spec/compose-go@v0.0.0-20210901090333-feb401cda7f7/loader/loader.go:524 +0x77
github.com/compose-spec/compose-go/loader.loadServiceWithExtends(0xc00024c000, 0x49, 0xc00011a210, 0x5, 0xc0005d36e0, 0xc00024c000, 0x31, 0xc00079e990, 0xc0000b40c0, 0xc00079e3a0, ...)
	github.com/compose-spec/compose-go@v0.0.0-20210901090333-feb401cda7f7/loader/loader.go:451 +0x133
github.com/compose-spec/compose-go/loader.LoadServices(0xc00024c000, 0x49, 0xc0005d36e0, 0xc00024c000, 0x31, 0xc00079e990, 0xc0000b40c0, 0x1dbd300, 0xc0002de5b8, 0xc00017c300, ...)
	github.com/compose-spec/compose-go@v0.0.0-20210901090333-feb401cda7f7/loader/loader.go:435 +0x2d3
github.com/compose-spec/compose-go/loader.loadSections(0xc00024c000, 0x49, 0xc0000b5d70, 0x0, 0x0, 0xc00024c000, 0x31, 0xc0001c7500, 0x5, 0x8, ...)
	github.com/compose-spec/compose-go@v0.0.0-20210901090333-feb401cda7f7/loader/loader.go:256 +0x1c5
github.com/compose-spec/compose-go/loader.Load(0x0, 0x0, 0xc00024c000, 0x31, 0xc0001c7500, 0x5, 0x8, 0xc0000b4000, 0xc00000e040, 0x1, ...)
	github.com/compose-spec/compose-go@v0.0.0-20210901090333-feb401cda7f7/loader/loader.go:167 +0x345
github.com/compose-spec/compose-go/cli.ProjectFromOptions(0xc000568000, 0x0, 0x0, 0x0)
	github.com/compose-spec/compose-go@v0.0.0-20210901090333-feb401cda7f7/cli/options.go:331 +0x4bf
github.com/docker/compose/v2/cmd/compose.(*projectOptions).toProject(0xc0005421c0, 0xc0003acff0, 0x0, 0x1, 0x0, 0x0, 0x0, 0xc00052a3f0, 0x0, 0x0)
	github.com/docker/compose/v2/cmd/compose/compose.go:163 +0x97
github.com/docker/compose/v2/cmd/compose.(*projectOptions).WithServices.func1(0x2126320, 0xc0000b2000, 0xc0003acff0, 0x0, 0x1, 0xc00052a408, 0x12)
	github.com/docker/compose/v2/cmd/compose/compose.go:108 +0x8b
github.com/docker/compose/v2/cmd/compose.Adapt.func1(0xc000272a00, 0xc0003acff0, 0x0, 0x1, 0x0, 0x0)
	github.com/docker/compose/v2/cmd/compose/compose.go:62 +0x12f
github.com/spf13/cobra.(*Command).execute(0xc000272a00, 0xc0001c9ba0, 0x1, 0x2, 0xc000272a00, 0xc0001c9ba0)
	github.com/spf13/cobra@v1.2.1/command.go:856 +0x472
github.com/spf13/cobra.(*Command).ExecuteC(0xc0002aec80, 0xc0002aec80, 0xc0001c9b80, 0x3)
	github.com/spf13/cobra@v1.2.1/command.go:974 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.2.1/command.go:902
github.com/docker/cli/cli-plugins/plugin.RunPlugin(0xc00018e410, 0xc000272780, 0x1f6f82d, 0x5, 0x1f768a6, 0xb, 0x20e7bf0, 0xb, 0x0, 0x0, ...)
	github.com/docker/cli@v20.10.7+incompatible/cli-plugins/plugin/plugin.go:51 +0x146
github.com/docker/cli/cli-plugins/plugin.Run(0x1fe99d8, 0x1f6f82d, 0x5, 0x1f768a6, 0xb, 0x20e7bf0, 0xb, 0x0, 0x0, 0x0, ...)
	github.com/docker/cli@v20.10.7+incompatible/cli-plugins/plugin/plugin.go:64 +0x13f
main.main()
	github.com/docker/compose/v2/cmd/main.go:38 +0xd8
```

## Additional information

OS version / distribution, `docker-compose` install method, etc.
Just upgraded to Docker for Mac 4.0.1 / compose RC3

**Comment by toniopelo** [comment]
Not sure if this is a regression but this still doesn't work for me with Windows 11 / wsl2 / compose v2.2.1.

`shm-size: 1G` work ok but `shm_size: ${SHM_SIZE}` with the same value as SHM_SIZE env var fail with :
```
error while interpolating services.backend.shm_size: failed to cast to expected type: strconv.ParseInt: parsing "1G": invalid syntax
```
