### ISSUE TITLE
SyntaxError: invalid or missing encoding declaration for '/Applications/Docker.app/Contents/Resources/bin/docker-compose-v1/docker-compose'

### ISSUE THREAD

**Issue by inieves** [docker/compose#8886]
When triggering a graceful shutdown of "docker-compose up" via control-c on MacOS terminal:
- docker-compose version 1.29.2, build 5becea4
- docker-py version: 5.0.0
- CPython version: 3.9.0
- MacOS 12.0.1 (21A559)

I occasionally see (once every 10 attempts or so) that the graceful shutdown terminate quickly with the message:
^CERROR: Aborting.

To investigate this further, I added verbose output to docker-compose.  That verbose output was able to show more detail (full log output at the end of this message), with the last few lines:
"/Users/administrator/jenkins/workspace/dsg_compose_1.29.2/build/toolchain/Frameworks/Python.framework/Versions/3.9/lib/python3.9/linecache.py", line 46, in getlines
  File "/Users/administrator/jenkins/workspace/dsg_compose_1.29.2/build/toolchain/Frameworks/Python.framework/Versions/3.9/lib/python3.9/linecache.py", line 136, in updatecache
  File "tokenize.py", line 394, in open
  File "tokenize.py", line 371, in detect_encoding
  File "tokenize.py", line 335, in find_cookie
SyntaxError: invalid or missing encoding declaration for '/Applications/Docker.app/Contents/Resources/bin/docker-compose-v1/docker-compose'
[48682] Failed to execute script docker-compose

After some digging, I noticed that there is an open Python bug relating to the parsing and tokenization of files which is able to produce a similar error output:
https://bugs.python.org/issue18961

The expected behavior is that graceful shutdown is initiated every time control-c is pressed, even if the graceful shutdown does not complete successfully for any number of reasons.

This may be related to some bugs that are closed although people are still seeing in the wild:
https://github.com/docker/compose/issues/3347
https://github.com/docker/compose/issues/3317

Full Log Output
=========================
^CGracefully stopping... (press Ctrl+C again to force)
compose.cli.verbose_proxy.proxy_callable: docker containers <- (all=False, filters={'label': ['com.docker.compose.project=stuco_dev-route', 'com.docker.compose.oneoff=False']})
--- Logging error ---
Traceback (most recent call last):
  File "compose/cli/main.py", line 1530, in up_shutdown_context
  File "compose/cli/main.py", line 1216, in up
  File "compose/cli/log_printer.py", line 88, in run
  File "compose/cli/log_printer.py", line 241, in consume_queue
  File "queue.py", line 180, in get
  File "threading.py", line 316, in wait
  File "compose/cli/signals.py", line 15, in shutdown
compose.cli.signals.ShutdownException

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging/__init__.py", line 1082, in emit
  File "compose/cli/signals.py", line 15, in shutdown
compose.cli.signals.ShutdownException
Call stack:
Traceback (most recent call last):
  File "compose/cli/main.py", line 1530, in up_shutdown_context
  File "compose/cli/main.py", line 1216, in up
  File "compose/cli/log_printer.py", line 88, in run
  File "compose/cli/log_printer.py", line 241, in consume_queue
  File "queue.py", line 180, in get
  File "threading.py", line 316, in wait
  File "compose/cli/signals.py", line 15, in shutdown
compose.cli.signals.ShutdownException

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging/__init__.py", line 1082, in emit
  File "compose/cli/signals.py", line 15, in shutdown
compose.cli.signals.ShutdownException

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tokenize.py", line 330, in find_cookie
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xcf in position 0: invalid continuation byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "docker-compose", line 3, in <module>
  File "compose/cli/main.py", line 81, in main
  File "compose/cli/main.py", line 203, in perform_command
  File "compose/metrics/decorator.py", line 18, in wrapper
  File "compose/cli/main.py", line 1229, in up
  File "contextlib.py", line 135, in __exit__
  File "compose/cli/main.py", line 1533, in up_shutdown_context
  File "compose/project.py", line 411, in stop
  File "compose/project.py", line 854, in containers
  File "compose/project.py", line 834, in _labeled_containers
  File "compose/cli/verbose_proxy.py", line 45, in proxy_callable
  File "logging/__init__.py", line 1434, in info
  File "logging/__init__.py", line 1577, in _log
  File "logging/__init__.py", line 1587, in handle
  File "logging/__init__.py", line 1649, in callHandlers
  File "logging/__init__.py", line 948, in handle
  File "logging/__init__.py", line 1087, in emit
  File "logging/__init__.py", line 1010, in handleError
  File "/Users/administrator/jenkins/workspace/dsg_compose_1.29.2/build/toolchain/Frameworks/Python.framework/Versions/3.9/lib/python3.9/traceback.py", line 190, in print_stack
  File "/Users/administrator/jenkins/workspace/dsg_compose_1.29.2/build/toolchain/Frameworks/Python.framework/Versions/3.9/lib/python3.9/traceback.py", line 211, in extract_stack
  File "/Users/administrator/jenkins/workspace/dsg_compose_1.29.2/build/toolchain/Frameworks/Python.framework/Versions/3.9/lib/python3.9/traceback.py", line 366, in extract
  File "/Users/administrator/jenkins/workspace/dsg_compose_1.29.2/build/toolchain/Frameworks/Python.framework/Versions/3.9/lib/python3.9/traceback.py", line 288, in line
  File "/Users/administrator/jenkins/workspace/dsg_compose_1.29.2/build/toolchain/Frameworks/Python.framework/Versions/3.9/lib/python3.9/linecache.py", line 30, in getline
  File "/Users/administrator/jenkins/workspace/dsg_compose_1.29.2/build/toolchain/Frameworks/Python.framework/Versions/3.9/lib/python3.9/linecache.py", line 46, in getlines
  File "/Users/administrator/jenkins/workspace/dsg_compose_1.29.2/build/toolchain/Frameworks/Python.framework/Versions/3.9/lib/python3.9/linecache.py", line 136, in updatecache
  File "tokenize.py", line 394, in open
  File "tokenize.py", line 371, in detect_encoding
  File "tokenize.py", line 335, in find_cookie
SyntaxError: invalid or missing encoding declaration for '/Applications/Docker.app/Contents/Resources/bin/docker-compose-v1/docker-compose'
[48682] Failed to execute script docker-compose

**Comment by inieves** [comment]
Using docker-compose version 2.0.0 I have experimented further (starting up and then attempting to gracefully shutdown with verbose logging), and I find a similar failure mode with the following error output:

^CGracefully stopping... (press Ctrl+C again to force)
DEBU[0001] FIXME: Got an status-code for which error does not match any expected type!!!: -1  module=api status_code=-1
DEBU[0001] FIXME: Got an status-code for which error does not match any expected type!!!: -1  module=api status_code=-1
canceled
