### ISSUE TITLE
Setting environment variable on CLI raises exception when service has environment definition

### ISSUE THREAD

**Issue by gijzelaerr** [docker/compose#927]
It looks like I can't set an environment variable in the fig.yml and on the console at the same time.

fig version: `1.0.1`
python version: `2.7 (homebrew)`
OS: OSX `10.10.2`

*fig.yml:*
```bliep:
  image: ubuntu:14.04
  environment:
    - SECRET_KEY
```

*full output:*
```
$ fig run -e BLA=bla bliep
Traceback (most recent call last):
  File "/usr/local/bin/fig", line 9, in <module>
    load_entry_point('fig==1.0.1', 'console_scripts', 'fig')()
  File "/usr/local/lib/python2.7/site-packages/fig/cli/main.py", line 31, in main
    command.sys_dispatch()
  File "/usr/local/lib/python2.7/site-packages/fig/cli/docopt_command.py", line 21, in sys_dispatch
    self.dispatch(sys.argv[1:], None)
  File "/usr/local/lib/python2.7/site-packages/fig/cli/command.py", line 28, in dispatch
    super(Command, self).dispatch(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/fig/cli/docopt_command.py", line 24, in dispatch
    self.perform_command(*self.parse(argv, global_options))
  File "/usr/local/lib/python2.7/site-packages/fig/cli/command.py", line 56, in perform_command
    handler(project, command_options)
  File "/usr/local/lib/python2.7/site-packages/fig/cli/main.py", line 312, in run
    service.options['environment'][k] = v
TypeError: list indices must be integers, not unicode
```

**Comment by dnephin** [comment]
hmm, I thought this was fixed. Maybe it's in 1.1 or still in a PR somewhere.

I believe the workaround for now is to use the mapping form in the fig.yml

 ```yaml
 image: ubuntu:14.04
   environment:
     SECRET_KEY:
```

**Comment by gijzelaerr** [comment]
sorry, nope:

```
$  cat fig.yml
bliep:
  image: ubuntu:14.04
  environment:
    - BLOP:
$  fig run -e BLOP=bla bliep
Traceback (most recent call last):
  File "/usr/local/bin/fig", line 9, in <module>
    load_entry_point('fig==1.0.1', 'console_scripts', 'fig')()
  File "/usr/local/lib/python2.7/site-packages/fig/cli/main.py", line 31, in main
    command.sys_dispatch()
  File "/usr/local/lib/python2.7/site-packages/fig/cli/docopt_command.py", line 21, in sys_dispatch
    self.dispatch(sys.argv[1:], None)
  File "/usr/local/lib/python2.7/site-packages/fig/cli/command.py", line 28, in dispatch
    super(Command, self).dispatch(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/fig/cli/docopt_command.py", line 24, in dispatch
    self.perform_command(*self.parse(argv, global_options))
  File "/usr/local/lib/python2.7/site-packages/fig/cli/command.py", line 56, in perform_command
    handler(project, command_options)
  File "/usr/local/lib/python2.7/site-packages/fig/cli/main.py", line 312, in run
    service.options['environment'][k] = v
TypeError: list indices must be integers, not unicode
```

**Comment by dnephin** [comment]
You did not make the change I suggested. You still have a list in `environment`. You need to remove the dash.

**Comment by gijzelaerr** [comment]
sorry, you are right and yes, that workaround works.
