### ISSUE TITLE
`docker-compose down` panics when specifying both `-p` and `--rmi` flags 

### ISSUE THREAD

**Issue by tomern0** [docker/compose#9407]
**Description**
```docker-compose down``` panics when specifying both -p and --rmi 

**Steps to reproduce the issue:**
1. docker-compose.yml:
 ```
version: '3'

name: "test_name"

services:

  test_registry:
    image: registry:2.7.0
    ports:
      - 5000:5000
 ```
2. ```docker compose up -d test_registry```
3. ```docker compose -p test_name down --rmi local```

**Describe the results you received:**
The container is stopped, but network is not removed.
```
[+] Running 0/1
 - Container test_name-test_registry-1  Stopping                                                                                                 0.3s 
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x28 pc=0x18505b5]

goroutine 32 [running]:
github.com/docker/compose/v2/pkg/compose.(*composeService).getServiceImages(0x19c92c0, {0x0, 0x0, 0x0, {0xc00019a0d8, 0x3}, 0x0}, {0xc00019a0a0, 0x9})
        github.com/docker/compose/v2/pkg/compose/down.go:149 +0x75
github.com/docker/compose/v2/pkg/compose.(*composeService).ensureImagesDown(0xc000526000, {0x1d3b2c8, 0xc00004c360}, {0xc00019a0a0, 0x9}, {0x0, 0x0, 0x0, {0xc00019a0d8, 0x3}, ...}, ...)
        github.com/docker/compose/v2/pkg/compose/down.go:119 +0xc8
github.com/docker/compose/v2/pkg/compose.(*composeService).down(0xc000526000, {0x1d3b2c8, 0xc00004c360}, {0xc00019a0a0, 0x9}, {0x0, 0x0, 0x0, {0xc00019a0d8, 0x3}, ...})
        github.com/docker/compose/v2/pkg/compose/down.go:85 +0x4b4
github.com/docker/compose/v2/pkg/compose.(*composeService).Down.func1({0x1d3b2c8, 0xc00004c360})
        github.com/docker/compose/v2/pkg/compose/down.go:39 +0x85
github.com/docker/compose/v2/pkg/progress.Run.func1({0x1d3b2c8, 0xc00004c360})
        github.com/docker/compose/v2/pkg/progress/writer.go:61 +0x27
github.com/docker/compose/v2/pkg/progress.RunWithStatus.func2()
        github.com/docker/compose/v2/pkg/progress/writer.go:82 +0x87
golang.org/x/sync/errgroup.(*Group).Go.func1()
        golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:57 +0x67
created by golang.org/x/sync/errgroup.(*Group).Go
        golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:54 +0x92
```

**Describe the results you expected:**
Should stop and remove the container and network.

**Additional information you deem important (e.g. issue happens only occasionally):**
Only happens when both -p and --rmi are used.

**Output of `docker compose version`:**

```
Docker Compose version v2.4.1
```

**Output of `docker info`:**

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc., v0.8.2)
  compose: Docker Compose (Docker Inc., v2.4.1)
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc., 0.6.0)
  scan: Docker Scan (Docker Inc., v0.17.0)

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 9
 Server Version: 20.10.14
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 3df54a852345ae127d1fa3092b95168e4a88e2f8
 runc version: v1.0.3-0-gf46b6ba
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.10.102.1-microsoft-standard-WSL2
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 15.49GiB
 Name: docker-desktop
 ID: DL6I:E6ZT:FK24:UP7G:C47P:COCF:DXDP:TEXO:DBY3:QAWA:4MV6:DQVO
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 No Proxy: hubproxy.docker.internal
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  hubproxy.docker.internal:5000
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No blkio throttle.read_bps_device support
WARNING: No blkio throttle.write_bps_device support
WARNING: No blkio throttle.read_iops_device support
WARNING: No blkio throttle.write_iops_device support
```

**Comment by kibblewhite** [comment]
I'm experiencing the same issue. If anyone needs any information on the error from me, I'm happy to provide it, but it is pretty much identical to the above.

**Comment by ibrt** [comment]
Same issue here, started after I upgraded Docker Desktop for Mac to 4.7.1.

**Comment by ndeloof** [comment]
Closing as a duplicate for https://github.com/docker/compose/issues/9353
(fixed on master)
