### ISSUE TITLE
Windows: pywintypes.error: (2, 'CreateFile', 'The system cannot find the file specified.')

### ISSUE THREAD

**Issue by BaseMax** [docker/compose#9734]
**Description**

docker-compose.yml file:
```
version: '3.2'

services:
  nginx:
    image: richarvey/nginx-php-fpm:latest
    container_name: nginx
    restart: always
    ports:
     - "80:80"
    volumes:
     - "./nginx/:/etc/nginx"
     - "./webroot/:/var/www/html"
    external_links:
     - mariadb:mariadb
     - phpmyadmin:phpmyadmin

  mariadb:
    image: mariadb
    container_name: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: your_sql_root_password
    volumes:
     - "./mariadb/:/var/lib/mysql"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpMyAdmin
    restart: always
    environment:
     - "PMA_HOST=mariadb"
     - "PMA_PORT=3306"
     - "PMA_ABSOLUTE_URI=https://phpmyadmin.your.domain"
    external_links:
     - mariadb:mariadb
    volumes:
     - "./phpmyadmin/sessions:/sessions"

```

**Steps to reproduce the issue:**
1. cd to project
2. run `docker-compose up`
3. errors!

**Describe the results you received:**

```

C:\Users\Max\Desktop\docker>docker-compose up
Traceback (most recent call last):
  File "docker\api\client.py", line 214, in _retrieve_server_version
  File "docker\api\daemon.py", line 181, in version
  File "docker\utils\decorators.py", line 46, in inner
  File "docker\api\client.py", line 237, in _get
  File "requests\sessions.py", line 543, in get
  File "requests\sessions.py", line 530, in request
  File "requests\sessions.py", line 643, in send
  File "requests\adapters.py", line 439, in send
  File "urllib3\connectionpool.py", line 670, in urlopen
  File "urllib3\connectionpool.py", line 392, in _make_request
  File "http\client.py", line 1255, in request
  File "http\client.py", line 1301, in _send_request
  File "http\client.py", line 1250, in endheaders
  File "http\client.py", line 1010, in _send_output
  File "http\client.py", line 950, in send
  File "docker\transport\npipeconn.py", line 32, in connect
  File "docker\transport\npipesocket.py", line 23, in wrapped
  File "docker\transport\npipesocket.py", line 72, in connect
  File "docker\transport\npipesocket.py", line 52, in connect
pywintypes.error: (2, 'CreateFile', 'The system cannot find the file specified.')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "docker-compose", line 3, in <module>
  File "compose\cli\main.py", line 81, in main
  File "compose\cli\main.py", line 200, in perform_command
  File "compose\cli\command.py", line 60, in project_from_options
  File "compose\cli\command.py", line 152, in get_project
  File "compose\cli\docker_client.py", line 41, in get_client
  File "compose\cli\docker_client.py", line 170, in docker_client
  File "docker\api\client.py", line 197, in __init__
  File "docker\api\client.py", line 221, in _retrieve_server_version
docker.errors.DockerException: Error while fetching server API version: (2, 'CreateFile', 'The system cannot find the file specified.')
[10580] Failed to execute script docker-compose
```

**Describe the results you expected:**

Running the docker image

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker compose version`:**

```

C:\Users\Max\Desktop\docker>docker-compose --version
docker-compose version 1.29.2, build 5becea4c
```

**Output of `docker info`:**

```
C:\Users\Max\Desktop\docker>docker info
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc., v0.8.2)
  compose: Docker Compose (Docker Inc., v2.6.1)
  extension: Manages Docker extensions (Docker Inc., v0.2.7)
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc., 0.6.0)
  scan: Docker Scan (Docker Inc., v0.17.0)

Server:
ERROR: error during connect: This error may indicate that the docker daemon is not running.: Get "http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.24/info": open //./pipe/docker_engine: The system cannot find the file specified.
errors pretty printing info
```

**Additional environment details:**

Windows 11, Laptop

**Comment by glours** [comment]
Hello @BaseMax 

The version 1 of Compose is end-of-line, please use Compose v2 instead. You can define this version in Docker Desktop settings
<img width="1125" alt="Screenshot 2022-07-31 at 11 34 50" src="https://user-images.githubusercontent.com/705411/183590404-1e245525-3454-4abf-8cdc-f870e15d2a8f.png">
 
By the way I think you should double if you Docker Engine is running (ie: Docker Desktop in Windows platform), because the last message looks pretty clear:
>Server: ERROR: error during connect: This error may indicate that the docker daemon is not running.: Get "http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.24/info": open //./pipe/docker_engine: The system cannot find the file specified.
errors pretty printing info

I close this issue as this not link to Compose.
